### PR TITLE
[Swift 3] Defend against reserved words as enum values

### PR DESCRIPTION
**Pull request by jgavris**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- [x] Defend against reserved word enum's in Swift 3 codegen

### CODE REVIEW

**Comment by jaz-ah** [comment]
it looks like we already pulled a PR for this one - could you retry w/ latest @jgavris

**Comment by jgavris** [comment]
Ah, indeed. Mine comes with a test though :)

**Comment by jaz-ah** [comment]
lol ok could you reintegrate that change into this PR and we'll merge this one through?

**Comment by jgavris** [comment]
That was merged into `master`. I suppose this belongs on `master` as well.

**Comment by jgavris** [comment]
@jaz-ah @wing328 When might the next merge of `master` into `2.3.0` happen? We need a few bugfixes from there.

**Comment by wing328** [comment]
@jgavris I've sync'd master into 2.3.0 via https://github.com/swagger-api/swagger-codegen/pull/4497

Please pull the latest master to give it a try.

Moving forward, I'll try to ensure the master is sync'd into 2.3.0 on a weekly basis.

**Comment by jgavris** [comment]
👍  Looks good, thanks @wing328 !

**Pull request closed without merging**
