### PR TITLE
#6718: Add exclusive min and max values for DecimalMin annotation

### PR DESCRIPTION
**Pull request by tobymurray**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

Swagger has the ability to express whether a minimum or maximum value is inclusive or exclusive (via exclusiveMinimum and exclusiveMaximum). This is already a property available on the models. The `@DecimalMin` and `@DecimalMax` annotations are inclusive by default (`inclusive = true`), but can express exclusive limits with the parameter `inclusive = false`. This maps Swagger's exclusiveMinimum to the `inclusive = false` parameter. See [documentation](http://docs.oracle.com/javaee/7/api/javax/validation/constraints/DecimalMin.html#inclusive--)

I've tried the code generation with this change locally and observed it working for `exclusiveMinimum` with a `number` property (and a corresponding `minimum` set).

@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet

### CODE REVIEW

**Comment by tobymurray** [comment]
> Ran the shell script under ./bin/ to update Petstore sample so that CIs can verify the change. 

I know this seems reasonably unambiguous, but if I run, for example, `$ bin/java-petstore-jersey2.sh` I get a diff. The diff is the same as the diff generated by running that script on this branch. Should I be committing the changed files?

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
> I know this seems reasonably unambiguous, but if I run, for example, $ bin/java-petstore-jersey2.sh on master I get a diff.

I'll take a look

**Comment by tobymurray** [comment]
> your commit is not linked to your Github account

Nice catch - I've fixed that.

**Comment by tobymurray** [comment]
Hmm, couple complications - this is Java EE 7 only, and I may need to add `value = ` before the value (not sure on that yet).

**Comment by JFCote** [comment]
Will wait for the final version before reviewing the code. Please tag me when you are done @tobymurray .

**Comment by tobymurray** [comment]
@wing328 - I'm still getting differences, e.g. running `bin/java-petstore-jersey2.sh` (although they may not be the same differences as before). Have you had a chance to take a look? How should I proceed?

Also, I saw the `supportJava6` flag - what JEE versions are officially supported for the server stubs? Should I be worrying about JEE 6 compatibility?

**Comment by wing328** [comment]
> Also, I saw the supportJava6 flag - what JEE versions are officially supported for the server stubs? Should I be worrying about JEE 6 compatibility?

Don't think we support Java 6 for any Java server stub generator. The option was added for Java API client (jersey 1.x or 2.x if I remember correctly) as some developers can't upgrade their JVM to a newer version.

**Comment by cbornet** [comment]
The JAVA clients need JDK6 compatibilité because if Android

**Comment by wing328** [comment]
Please run `bin/java-petstore-jersey2.sh` and commit the change so that we can review more easily.

**Comment by tobymurray** [comment]
> Please run bin/java-petstore-jersey2.sh and commit the change so that we can review more easily.

@wing328 - did so in 1d144c6

**Comment by wing328** [comment]
CircleCI reports the following errors:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project swagger-petstore-jersey2: Compilation failure: Compilation failure:
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/DefaultApi.java:[10,31] cannot find symbol
[ERROR] symbol:   class XmlObject
[ERROR] location: package io.swagger.client.model
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/DefaultApi.java:[43,10] cannot find symbol
[ERROR] symbol:   class XmlObject
[ERROR] location: class io.swagger.client.api.DefaultApi
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/DefaultApi.java:[78,31] cannot find symbol
[ERROR] symbol:   class XmlObject
[ERROR] location: class io.swagger.client.api.DefaultApi
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/DefaultApi.java:[69,17] cannot find symbol
[ERROR] symbol:   class XmlObject
[ERROR] location: class io.swagger.client.api.DefaultApi
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/jersey2/src/main/java/io/swagger/client/api/DefaultApi.java:[69,65] cannot find symbol
[ERROR] symbol:   class XmlObject
[ERROR] location: class io.swagger.client.api.DefaultApi
[ERROR] -> [Help 1]
```
@tobymurray Would you please take a look when you've time?

**Comment by tobymurray** [comment]
I'm no longer working on code that relies on this feature. I'm not sure what this has to do with the test failure about `XmlObject`, but I don't have any intention of finishing this off as it stands. I'll close it so it doesn't get stuck in limbo.

**Pull request closed without merging**
