### PR TITLE
fix(swift3): decoders call parents decoders too

### PR DESCRIPTION
**Pull request by julienfouilhe**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

I was having problems with classes inheriting from other classes, fields defined in parent classes were `nil`. I fixed it by calling the parent's decoder in the child's decoder and passing the child's instance.

### CODE REVIEW

**Comment by wing328** [comment]
@julienfouilhe thanks for the PR.

cc @jaz-ah @Edubits @jgavris  @hexelon

**Comment by jaz-ah** [comment]
@julienfouilhe could you regenerate the sample files and put in here as well?  I wanted to see what the output looks like now...

**Comment by julienfouilhe** [comment]
Hi jaz-ah, it should be in the commit. Most of it is in Models.swift, and the diff is not displayed on github unless you click because it's too large. :)

**Comment by jaz-ah** [comment]
@julienfouilhe ah I meant the actual sample output -i.e. the sample/test project checked into the tree...

**Comment by julienfouilhe** [comment]
@jaz-ah I ran swift3-petstore-all.sh. Tell me if that's not what you needed

**Comment by jaz-ah** [comment]
@julienfouilhe I must have missed it - I see it now - looks good - thx!  +1 @wing328

**Comment by julienfouilhe** [comment]
@jaz-ah Yes I just ran them and amended my commit. ;) 

I don't think there's a test for that though. If you want to see where the bug was, you would need to add an endpoint to the Petstore API `/cats` returning `Cat` objects and not `Pet`. Without this commit, it wouldn't go through the `Pet` decoder, and thus it wouldn't fill fields described in `Pet`

**Comment by wing328** [comment]
@julienfouilhe thanks for the PR.

@jaz-ah thanks for reviewing the change.

**Comment by wuf810** [comment]
I am double checking  but the changes in this PR have broken my swagger generated code .

This line in the template 

`_ = Decoders.decode(clazz: {{parent}}.self, source: source, instance: result) `

generates the following code for classes in the Models.swift file :

`_ = Decoders.decode(clazz: String.self, source: source, instance: result)`

As a result the decode function is looking for a class decoder named "String". 

NB The classes this fails on do use AdditionalProperties (which @danwoodel and I are currently fixing)…and I think this might be the issue as the current implementation of AdditionalProperties handling in the Swift3 codeine is completely wrong in that it tries to make the class a subclass of a string collection. This could be what {{parent}} is mistakenly returning.

Comments/thoughts anyone?

**Comment by dwoodel** [comment]
I think it might be a good idea to add some models in the PetStore example with some additional properties.

**Comment by julienfouilhe** [comment]
We should check if `decoders["\({{parent}}.self)"]` exists too. I should have done that.

**Comment by wing328** [comment]
> I think it might be a good idea to add some models in the PetStore example with some additional properties.

We do have that in [petstore-with-fake-endpoints-models-for-testing.yaml](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L1084), which covers a lot more edge cases.

Currently, the Swift Petstore is using petstore.yaml (the basic one) and I'll create a task to track updating Swift Petstore to use [petstore-with-fake-endpoints-models-for-testing.yaml](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L1084)

**Comment by wing328** [comment]
Created https://github.com/swagger-api/swagger-codegen/issues/5419 for tracking

**Comment by wing328** [comment]
@dwoodel actually swift3 petstore is already using the fake petstore. Please feel free to submit a PR to add additional test cases to fake petstore so as to cover more edge cases.

**Comment by wing328** [comment]
@julienfouilhe when you've time I wonder if you can make the same change against 2.3.0 branch instead as I got merge conflict when syncing the changes from master to 2.3.0. Thanks!

**Comment by julienfouilhe** [comment]
@wing328 Done!

**Pull request merged**
