### PR TITLE
Fixes 5367. Async support is enabled for .NET netstandard API clients

### LINKED ISSUE #5367: Async methods are not generated for .NET API when target framework is netstandard
##### Description

When generating a client for a .NET `netstandard` API, async versions of methods are not generated even when `supportsAsync` option is set to `true`.

##### Swagger-codegen version

Swagger version: 2.2.3-SNAPSHOT
Regression: No. The issue introduced with the support of `netstandard`.

##### Command line used for generation

```
&"java" -DapiTests=false -jar $CodeGenPath generate -i $SpecUri -l csharp -o $OutputFolder --additional-properties packageVersion=$PackageVersion,targetFramework=v5.0
```

##### Steps to reproduce

1. Generate a client for a .NET API using `netstandard` as a target framework

##### Suggest a Fix

The code has a typo. Currently the code in modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java looks like this:
```
additionalProperties.put("supportsAsync", this.supportsUWP);
additionalProperties.put("supportsUWP", this.supportsAsync);
```

Should be
```
additionalProperties.put("supportsAsync", this.supportsAsync);
additionalProperties.put("supportsUWP", this.supportsUWP);
```

Working on a fix.

### PR DESCRIPTION
**Pull request by nikitozz**
### Description of the PR
Fixes #5367.
A typo is fixed in modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/CSharpClientCodegen.java to correctly support async and UWP when generating .NET clients for `netstandard` target framework.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by nikitozz** [comment]
Amended my commit.
Thank you so much, @wing328, for pointing this out.

**Comment by wing328** [comment]
@nikitozz the fix looks good. Thanks for your contribution.

**Comment by wing328** [comment]
If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen)

**Pull request merged**
