### PR TITLE
[rust-server] add license and description to Cargo.toml

### PR DESCRIPTION
**Pull request by bjgill**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

In `rust-server`, we now fill in the `license` and `description` fields. `license` only appears if present in the swagger; `description` defaults to `"No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)"`

This allows the generated crate to be published to crates.io without needing manual modification.

### CODE REVIEW

**Comment by bjgill** [comment]
@farcaller @frol - I believe you are the Rust technical committee. Please may you have a look?

**Comment by farcaller** [comment]
LGTM.

**Comment by frol** [comment]
It seems that according to #4197, the license for the generated clients should be "Unlicense".

**Comment by bjgill** [comment]
OK. Would it be acceptable then to set `Unlicense` as the default, but use the license specified in the swagger info instead if present?

**Comment by wing328** [comment]
@frol is right. The default should be "Unlicense".

**Comment by frol** [comment]
@bjgill It seems that the license specified in the Swagger Spec file is not the same license as one that is used for the generated client.

**Comment by wing328** [comment]
@frol I think the license specified in the spec refers to "License information for the exposed API", which may or may not be the same as the license of the auto-generated code.

**Pull request merged**
