### PR TITLE
Correct some Java Warnings

### PR DESCRIPTION
**Pull request by hiveship**
Just correct some Java warnings (static methods, useless imports, unused
parameters...). Don't impact any features. Tests are OK.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. Instead of using tab, please use 4-space for indentation instead.

I notice that you convert many private instance method into static one. Is that a reason for making that change? Is that based on some Java best practices?

**Comment by hiveship** [comment]
It's a Java Best practice that a method which do not need any instance variable may be declared as static. I only did that on private method since no one will be allow to override it in any other class.
If it make sense to call this method, even if no object has been constructed yet, then it should be static.

**Comment by wing328** [comment]
Thanks. Do you have the URL to the section in best practice that we can find out more?

**Comment by hiveship** [comment]
I don't have a link to the oracle website yet but:

See the accepted answer: http://stackoverflow.com/questions/11240178/what-is-the-gain-from-declaring-a-method-as-static

**Comment by hiveship** [comment]
I added a commit to handle UUID generation in a Java code.

**Comment by wing328** [comment]
The change looks reasonable to me after reading the SO link you provided.

@fehguy do you have any concern switching private instance methods to private static methods?

**Comment by fehguy** [comment]
Hi, I can't merge with tabs vs. spaces, it makes it very painful to diff and doesn't follow our coding standards.

The guts of the PR, from the comments, sound fine--but please try to send a PR with just your changes.  If formatting is a problem, it's best to send formatting changes in a different PR.

**Comment by wing328** [comment]
@hiveship seems like there's an issue with "rebase" as the PR contains 60+ commits. Let me know if you need help fixing that (e.g. using cherry-pick with a new branch)

**Comment by hiveship** [comment]
@wing328 Yes, I would appreciate some help to fix that (I'm really new with git & GitHub). 

@fehguy Do you have a code formatter (for example for Eclipse) to provide ? or any quick solution to fix my indent problems ?

**Comment by wing328** [comment]
@hiveship please try the following:
```
git checkout master
git pull upstream master  // assuming upstream is a remote pointing to swagger-api/swagger-codegen.git
git checkout -b fix_java_warnings
git cherry-pick 7891873c6da49726e36159db597a39cf263dcde0
```
Check the files to confirm the change is present and cherry-pick more commits if needed.

**Comment by hiveship** [comment]
@wing328 all failed and now my local project is in a very bad state (can not commit or pull anything). Is there is way to delete all my local project and reclone again ? (without loosing my work ?)

**Comment by wing328** [comment]
@hiveship no worry. Please don't delete any commit/branch.

I'll create a new branch and cherrypick the following commits this weekend when I've time:
7891873c6da49726e36159db597a39cf263dcde0
f8f906634ee5e1dc23c61c95514684a42b9db0d5
b8df13a2614f6061eaf25a151362e68700d49424

**Comment by hiveship** [comment]
Can close this PR. Too complicated to extract the commits and revert the original code formatting. I will continue my work on the Apache CXF support and I'll send a new pull request when it's finished. (See my question https://github.com/swagger-api/swagger-codegen/issues/1888)

**Comment by hiveship** [comment]
@wing328 if you prefer, I can delete my fork and fork again. I can apply again my changes in a new branch and then ask for a pull request on this branch. I can do the same for my other works;
- Support generation of Java UUID Type
- Support for JAX-RS Apache CXF

**Comment by wing328** [comment]
@hiveship well I just want to save you some time in manually applying those changes in a newly-forked repo. I'll leave it up to you on how you would like to proceed.

One suggestion is to create a new branch and avoid making change directly in the master.

**Comment by hiveship** [comment]
Thank you but I think it could be better to apply change is a newly-forked repo since I am working on other features in the codegen, and the problem will be the same for next PR.
I will create separates branches !

**Pull request closed without merging**
