### PR TITLE
[swift3] empty model with only additional properties

### PR DESCRIPTION
**Pull request by wuf810**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

When a class is defined as having no variables but does have additionalProperties, the class would be created incorrectly as a broken typeAlias.

In addition if a class is defined with no variables and no additionalProperties a broken typeAlias was generated. This is now creates an empty jsonencodable class.

This fixes issue #5535

cc @dwoodel

### CODE REVIEW

**Comment by wuf810** [comment]
Hey is the error ^ something we've done or does the travis test sometime fail?

@wing328

**Comment by wuf810** [comment]
My bad, my local master was one behind which maybe why the tests failed. It is now fixed.

**Comment by wuf810** [comment]
OK same question…any idea why the travis job might have failed?

**Comment by wing328** [comment]
@wuf810 I'll take a look.

**Comment by wing328** [comment]
Tests with updated Petstore samples (swift, swfit3) passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/263164376?utm_source=email&utm_medium=notification

**Comment by wing328** [comment]
cc @jaz-ah @jgavris @Edubits

**Comment by jgavris** [comment]
This is great, I've actually been running this on a private fork for a while. I wasn't sure the implications of it for others so I didn't  PR it.

**Comment by jgavris** [comment]
LGTM

**Comment by jgavris** [comment]
@wing328 What's the status with the github rate limit on the typescript thing?

**Comment by wing328** [comment]
> What's the status with the github rate limit on the typescript thing?

@jgavris The latest master should have fixed it.

**Comment by jgavris** [comment]
Sorry, which commit though? This PR failed on that.

**Comment by wing328** [comment]
> Sorry, which commit though? This PR failed on that.

Should be fixed by https://github.com/swagger-api/swagger-codegen/pull/6178

Let me merge this one into master to see if I could repeat the Github rate limit error (I've not seen this error myself for a while)

**Comment by wing328** [comment]
@wuf810 thanks for the PR, which has been merged into master.

When you've time, I wonder if you can make the same enhancement to Swift4 generator.

cc @ehyche

**Comment by wing328** [comment]
UPDATE about the Github rate limit error: it's my oversight and I've commented out the test in Travis for the time being until someone has cycle to replace `tsd` with `typings` in the TS Angular client.

**Comment by wuf810** [comment]
Of course, I'll take a look at the Swift4 later in the week.

**Comment by wuf810** [comment]
@wing328 @ehyche My apologies but I've not had time to apply the same enhancement to the Swift4 generator. 

I'm currently recovering from surgery so not sure when I am able to look. 

Could one of you do this for me? Or do you want to wait on me?

**Comment by ehyche** [comment]
@wuf810 : No worries. I am working on adding this functionality to the swift4 generator. PR should be up shortly.

**Comment by ehyche** [comment]
@wuf810 @wing328 : I implemented this functionality for swift4 in this PR I just filed: https://github.com/swagger-api/swagger-codegen/pull/6492

**Comment by wuf810** [comment]
Brilliant. Thank you.

**Comment by wing328** [comment]
@wuf810 can you please help test the PR when you've time?
```
git checkout -b ehyche-ehyche_swift4_empty_model_only_additional_properties master
git pull https://github.com/ehyche/swagger-codegen.git ehyche_swift4_empty_model_only_additional_properties
mvn clean package
# generate swift client for testing
```

**Comment by wing328** [comment]
@wuf810 the enhancement has been merged into master. Please pull the latest to give it a try.

**Comment by wuf810** [comment]
@wing328 Sorry still not fully recovered from surgery. However I have managed to have a quick look at the latest master and generated our client code and at first glance everything looks good.

**Pull request merged**
