### PR TITLE
fixed #5692 (wrong python import statement) and regenerated samples

### LINKED ISSUE #5692: python from __future__ import print_statement vs print_function at http://editor.swagger.io/
##### Description

When I generate a python client the readme tells me to import print_statement:
`from __future__ import print_statement`

shouldn't this rather be 
`from __future__ import print_function`

##### Swagger-codegen version
used http://editor.swagger.io/

### PR DESCRIPTION
**Pull request by rompic**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
This should fix #5692.
I changed from __future__ import print_statement to from __future__ import print_function in the template and regenerated the python examples.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@rompic the fix looks good to me. If you don't mind commits not linking to your github account, I'll go ahead and merge this PR into master.

**Comment by rompic** [comment]
sorry just read this point in the faq. fine with me if you can do this.

**Comment by wing328** [comment]
@rompic PR merged into master. Thanks for your contribution.

**Comment by g-bon** [comment]
This is still present [here](https://github.com/swagger-api/swagger-codegen/blob/a2240ac619df5d0bdedad884b1374dc06ab772e3/modules/swagger-codegen/src/main/resources/htmlDocs2/sample_python.mustache)

**Pull request merged**
