### PR TITLE
[Java] better enum naming for symbol

### PR DESCRIPTION
**Pull request by wing328**
For https://github.com/swagger-api/swagger-codegen/issues/2487

### CODE REVIEW

**Comment by sebciok** [comment]
Looking at the changelist there may be a copy/paste error:

       specialCharReplacements.put(">=", "Greater_Than_Or_Equal_To");
       specialCharReplacements.put("!=", "Greater_Than_Or_Equal_To");

Also, would it be possible to do it for . (dot/period) as well?

That's the case I ran into (we have an enumeration with both . (dot) and _ (underscore) and they are both being translated to _ (Java codegen). It would be really nice if underscore on its own would be translated to UNDERSCORE. 

Is there any guess when the new version with this fix would come out?

**Comment by wing328** [comment]
@sebciok fixed via https://github.com/swagger-api/swagger-codegen/pull/3531

**Comment by sebciok** [comment]
@wing328 Fantastic, Thank you.

**Comment by wing328** [comment]
@sebciok thanks again for reporting the issue. Please pull the latest to help confirm it addresses the issue for you as there're quite a few enum-related enhancements and bug fixes. Although we've test cases but still we our users to do a test if possible.

**Comment by sebciok** [comment]
I got latest, built codegen and was able to successfully generate my enumeration. Thank you, works great. 

I run into an unrelated issue where generated code could not resolve JsonCreator annotation, but it could be something on my side. 

If we want to handle more special characters (I do not need them, but just for completeness), I found that those ones are still missing:

QUESTION_MARK ?
COMMA ,
QUOTE '
DOUBLE_QUOTE "
SLASH /
BACKSLASH \
LEFT_PAREN (
RIGHT_PAREN )
LEFT_BRACE {
RIGHT_BRACE }
LEFT_BRACKET [
RIGHT_BRACKET ]
TILDE ~
BACKTICK `

**Comment by wing328** [comment]
> I ran into an unrelated issue where generated code could not resolve JsonCreator annotation, but it could be something on my side.

Which HTTP library did you use? The default one is `okhttp-gson`, which does not use JsonCreator annotation.

For the remaining special characters, we'll add those later.

**Comment by sebciok** [comment]
I just used a default generated maven project without any changes, so it looks like I was using com.squareup.okhttp. I will try generation, on another, larger swagger definition.

**Comment by wing328** [comment]
Thanks for the info.

FYI. Other symbols mapped via https://github.com/swagger-api/swagger-codegen/pull/3546

**Comment by wing328** [comment]
@sebciok thanks for the info. I'm able to repeat the issue and filed a fix: https://github.com/swagger-api/swagger-codegen/pull/3551

**Pull request merged**
