### PR TITLE
Build and upload Swagger Codegen CLI Docker image on release

### PR DESCRIPTION
**Pull request by arnested**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Follow-up on the improved Docker stuff in #2945 this pull request adds building and uploading a [Swagger Codegen CLI Docker image](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/) to Docker Hub on releases.

### CODE REVIEW

**Comment by wing328** [comment]
Seems like there are issues with job running for too long and got timed out: https://travis-ci.org/swagger-api/swagger-codegen/builds/206925853

**Comment by arnested** [comment]
Yes, I did the environment stuff in .travis.yml wrong (adding the two variables as two entries under `env:` which triggers a build for each entry instead of adding the new environment variable to the existing entry).

A fix is pushed. This time the build hopefully should not timeout...

**Comment by arnested** [comment]
Hmmm... The build aborts with
```
The log length has exceeded the limit of 4 MB (this usually means that the test suite is raising the same exception over and over).

The job has been terminated
```
The long log is from mvh downloading everything. I guess the initial faulty build has wiped some travis cache of the downloads for this pull request (since this doesn't appear to be a problem for other pull requests).

I'll close this pull request anf create a new to see if this will fix the problem.

**Comment by arnested** [comment]
The new pull request wasn't enough to cut down on the logging output. But running mvn in betch mode was. So I changed that as well in the other pull request.

**Comment by wing328** [comment]
Ok. One suggestion is to add a 1-liner comment explaining the new tests.

**Comment by arnested** [comment]
I added some comments in the other pull request.

**Pull request closed without merging**
