### PR TITLE
Add basic Javascript SDK support

### PR DESCRIPTION
**Pull request by jfiala**
see also issue #1294 "Document client SDK"

## Add basic Javascript SDK support
 (based on the Java templates):
* Allow to generate model classes
    * including comments
    * including property-level comments + type hints
    * including getters & setters + comment type hints
    * generate inline Enumeration classes to allow Enumeration usage
    * add required parameters to default constructor
    * add .toJson() to print complete model including nested models

* Allow to generate API classes
    * including comments 
    * including JSDoc for params & return  

* Allow for both AMD + plain JS usage

### CODE REVIEW

**Comment by jfiala** [comment]
Only added new class "JavascriptClientCodegen", but it seems all classes implementing CodegenConfig are tested using their name.

However, I ran it using the full class invocation:
-l io.swagger.codegen.languages.JavascriptClientCodegen

The shorthand "javascript" didn't work:
 -l javascript

Please advise how to add a new language only by implementing interface CodegenConfig without breaking the tests.

**Comment by wing328** [comment]
@jfiala thanks for the PR to add Javascript SDK :)

To add a new language, please add the following line to `modules/swagger-codegen/src/main/resources/META-INF/services/io.swagger.codegen.CodegenConfig`:

```
io.swagger.codegen.languages.JavascriptClientCodegen
```

I did a test and no longer see the same error after adding the line above.

**Comment by jfiala** [comment]
added configuration entry in io.swagger.codegen.CodegenConfig, however it could be picked up automatically as it implements the interface CodegenConfig

**Comment by wing328** [comment]
Agree with you that ideally it should be picked up automatically.

**Comment by wing328** [comment]
@jfiala thanks again for your contribution of the JS SDK. I'm sure the community would appreciate your effort :beers:

**Pull request merged**
