### PR TITLE
[Typescript][Angular] Added in injected basePath observable to api service to allow it to respond to external updates to this setting post construction.

### LINKED ISSUE #7949: [typescript-angular] service configuration/basePath modification after construction
##### Description

From what I can tell I cannot achieve what I describe below with current versions of codegen - I'm prepared to stand corrected ;)

A nice feature to have for typescript-angular would be the ability to modify configuration settings on the client stubs *after* the services have been constructed. Currently, basePath is set on service construction and remain impossible to modify for the lifetime of that service once the constructor has completed. There are scenarios where when using ngrx/effects where swagger services can be injected prior to APP_INITIALIZER completing. It would therefore be nice to have the ability to modify the api service configuration post construction.

##### Swagger-codegen version

Whatever dockerhub - swaggerapi/swagger-codegen-cli:latest is currently building - this is unclear from the docker hub info.

##### Suggest a fix/enhancement

I've currently worked around this by extending the generated angular service and injecting a BehaviorSubject of Configuration. The api service subscribes to changes to this stream and updates its configuration/basePath as appropriate. There's obviously a reason the existing basePath property is defined as protected rather than public so I'm clearly circumventing this for my own evil needs.

### PR DESCRIPTION
**Pull request by chrismellard**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes #7949 

Extended api service to allow optional injection of an observable basePath. This facilitates configuration of basePath post service construction which is required in circumstances where runtime setting of basePath cannot be achieved using APP_INITIALIZER tokens in angular. One such use case is when using libraries such as ngrx effects that do not respect such angular APP_INITIALIZER tokens.

Another option is to simply include the injected observable as part of the Configuration class rather than a separate dependency injectable token. If its preferable to move it inside that class I can do so.

### CODE REVIEW

**Comment by chrismellard** [comment]
@macjohnny

**Comment by macjohnny** [comment]
@chrismellard thanks for the PR. would you mind adding a note to the Readme.moustache or add a description of the constructor variable?

**Comment by macjohnny** [comment]
cc @TiFu (2017/07) @taxpon (2017/07) @sebastianhaas (2017/07) @kenisteward (2017/07) @Vrolijkx (2017/09) @macjohnny (2018/01)

**Comment by sebastianhaas** [comment]
Will check tomorrow!

**Comment by chrismellard** [comment]
@macjohnny Sure. Just pushed an update to the README.mustache file with some example usage.

**Comment by macjohnny** [comment]
@wing328 could you please restart the CircleCI tests?
@chrismellard could you please merge the current master into your branch and re-generate the samples?

**Comment by TiFu** [comment]
You can just close and reopen the PR to trigger CI.

Esteban Marin <notifications@github.com> schrieb am Do., 19. Apr. 2018
07:25:

**Comment by chrismellard** [comment]
Thanks - will update now

**Comment by digaus** [comment]
Any reason why this is not merged yet?

**Pull request closed without merging**
