### PR TITLE
[JavaScript] Fix for issue #5358: Regression in 2.3 using `multi` parameters (Cannot read property 'buildCollectionParam' of undefined)

### PR DESCRIPTION
**Pull request by michaelkourlas**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

See #5358.

### CODE REVIEW

**Comment by frol** [comment]
The fix works for me! Thank you!

**Comment by frol** [comment]
@michaelkourlas There is "Update tests" commit which doesn't bring or update any tests; is that intended?

**Comment by michaelkourlas** [comment]
I just regenerated the API libraries for the test -- that's all.

**Comment by frol** [comment]
Thank you for the quick fix!

**Pull request merged**
