### PR TITLE
Replaced \t with spaces

### PR DESCRIPTION
**Pull request by marcindanek85**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@marcindanek85 can you please tell me a bit more about the fix by updating the description and the PR subject line?

**Comment by marcindanek85** [comment]
There was just a compilation error, that .java file contains \t.
In case of the first change - if the type is a content type - the complexType field is set to a type of the array item, but if it is Array<primitiveType> - I could not find any way to get the type of array's items.  I needed this to generate my custom array types like MyCustomArray<type>.
If there is any other way (I'll try the solution with using innerProperty in a few days) - the all fixes are not needed.

**Comment by wing328** [comment]
The "\t" should have been replaced wth spaces in the latest master.

I'll merge the enhancement (copy array type descriptors) into 2.4.0

**Comment by cbornet** [comment]
@wing328 I think it is too early to merge this.
You should be able to get the array type from `property.items`

**Comment by wing328** [comment]
@cbornet I thought it's ok after reviewin the change but I would take your suggestion to roll back the change first and continue the discussion of using `property.items` here.

**Comment by wing328** [comment]
Reverted via e51223eef1fb3b552f8bf4fc3d19120026271a4e

**Pull request merged**
