### PR TITLE
[typescript-angular] error TS1345: An expression of type 'void' cannot be tested for truthiness #8836

### PR DESCRIPTION
**Pull request by emmanuelgautier**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix formParams append issue depending on FormParams type. Related to issue #8836

### CODE REVIEW

**Comment by emmanuelgautier** [comment]
Any reviewer for this PR @mhardorf, @roni-frantchi ?

**Comment by roni-frantchi** [comment]
@emmanuelgautier Looks good to me. Personally I prefer the approach I suggested in #9012 as it eliminates that `instanceof`, but only by a slight. Would do you think?

**Comment by emmanuelgautier** [comment]
@roni-frantchi OK. I did not see your PR and the related issue before. I give you a quick review on your code. I know this PR solution is not the most elegant way with this instanceof. But in both code conditions, this issue with the `HttpParams` type still exists.

**Comment by emmanuelgautier** [comment]
Look this [PR](https://github.com/swagger-api/swagger-codegen/pull/9012) instead.

**Pull request closed without merging**
