### PR TITLE
jaxrs-cxf-cdi :: Add a basic JAX-RS Application and CDI fixes

### PR DESCRIPTION
**Pull request by nickcmaynard**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Add a JAX-RS application, and beans.xml, so that this works on typical JavaEE 7.0 servers.  For example, code generated by this generator will now work directly upon deployment to IBM WAS Liberty, and IBM Bluemix.

### CODE REVIEW

**Comment by nickcmaynard** [comment]
... This fixes a fairly nasty bug where this code, while compiling, doesn't actually *work* on a real server without extra work.

**Comment by nickcmaynard** [comment]
@wing328 It would be great if we could make sure this goes into v2.2.2

**Comment by nickcmaynard** [comment]
@wing328 Sorry to ask, but do you think it might be possible to merge this reasonably swiftly? I have an article pending publication in which I make some statements about this generator (will drop a link in here once it's published) and it'd be great to unblock it...

**Comment by wing328** [comment]
@nickcmaynard PR merged and thanks for mentioning Swagger Codegen in your publication.

**Comment by nickcmaynard** [comment]
Thank you!

**Pull request merged**
