### PR TITLE
samples/client/petstore/lua: Add lua sample

### PR DESCRIPTION
**Pull request by daurnimator**
#WIP 

As suggested in https://github.com/swagger-api/swagger-codegen/issues/4794#issuecomment-320245838

This implementation uses [lua-http](https://github.com/daurnimator/lua-http)

### CODE REVIEW

**Comment by daurnimator** [comment]
I just added code that fleshes it out to use "classes".
I'm not sure exactly what you wanted here. So perhaps look at commits one by one?

**Comment by wing328** [comment]
@daurnimator it definitely looks good as a starting point 👍 Here are some feedbacks:

1) Can we put the following inside a function (e.g. function add_pet )?
```
local req = http_request.new_from_uri(string.format("%s/pet/%d", base, petId))
req.headers:upsert("accept", "application/json")
local headers, stream = req:go()
```

2) can we also put the code inside a module (e.g. petstore)?

Questions:
Is there a way to create sub-module so that Lua developers can call the function like "petstore.pet_api.add_pet" for example?

Is there a way to create object with properties for the models defined in the Swagger/OpenAPI spec? (e.g. https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L654-L692)

**Comment by daurnimator** [comment]
@wing328 much of what you mentioned was done in the second commit.

**Comment by wing328** [comment]
@daurnimator nice. I'll start the reverse engineering process over the weekend.

**Comment by wing328** [comment]
Merged it into master so that credits go to @daurnimator

**Pull request merged**
