### PR TITLE
Using baseName in place of paramName in request header. Closes #3502

### LINKED ISSUE #3502: [JAVA] Feign client generator: HTTP Header params are getting converted to camel case
##### Description
For Java API Client using Feign as library, header param names are getting converted to came case  breaking the API. 
For example: header parameter **user-id** gets converted to **userId**.

##### Swagger-codegen version
2.2.0

##### Suggest a Fix
Issue is with Line 30 of api.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/feign/api.mustache#L30

Changing the template on left hand side from paramName to baseName fixes the issue.
From:
`"{{paramName}}: {{=<% %>=}}{<%paramName%>}<%={{ }}=%>"{{#hasMore}},`
To:
`"{{baseName}}: {{=<% %>=}}{<%paramName%>}<%={{ }}=%>"{{#hasMore}},`

### PR DESCRIPTION
**Pull request by himanshu-mishra**

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by himanshu-mishra** [comment]
@wing328 Thanks for letting me know. Have verified my secondary email id and now the commit is linked to my account.

**Comment by wing328** [comment]
@himanshu-mishra thanks for the contribution.

I've reviewed the `api.mustache` and is it correct to say that Feign client does not support the form parameter at the moment?

**Comment by himanshu-mishra** [comment]
@wing328 I will verify and let you know

**Pull request merged**
