### PR TITLE
Develop 2.0 - support binary input and output

### PR DESCRIPTION
**Pull request by boazsapir**
This is my implementation of Java code generation, including the generic (not language specific) support needed, for binary data in the request body and in the response.
This implementation is based on the agreed spec, as discussed in https://github.com/swagger-api/swagger-spec/issues/50  and depends on my pull request to swagger-core which was merged on Aug-6 (https://github.com/swagger-api/swagger-core/pull/1335)

### CODE REVIEW

**Comment by wing328** [comment]
@boazsapir would you please rebase on the latest develop_2.0 ?

**Comment by boazsapir** [comment]
I am currently travelling will do it early next week

**Comment by boazsapir** [comment]
I have updated this pull request to include only one commit which includes all the changes, rebased (manually) to the latest develop_2.0 code from today

**Comment by webron** [comment]
@boazsapir - I'm afraid that even though you rebased, additional PR merges made it impossible to merge again. I'd have to ask you to rebase again, and resubmit it against the `master` branch (we moved to it just now).

**Comment by boazsapir** [comment]
@webron I created a new PR #1124 for the master branch

**Comment by fehguy** [comment]
I've merged #1124.  Thanks again!

**Pull request closed without merging**
