### PR TITLE
Add Java6 compatibility for Jersey2

### PR DESCRIPTION
**Pull request by k1w1m8**
### PR checklist

- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Java6 compatibility is being added via supportJava6 option. This PR makes a small change to Jersey2 to replace usage of Java 7 class java.nio.file.Files with reference to Apache commons.io.FileUtils. 

I'm not sure exactly how to manage the additional dependency for commons io. Originally I saw it as part of swagger-codegen but of course that is only for the generation process. I doubt we want to add it as a dependency on the swagger runtime code, are you happy for it be up to users of supportJava6 to add manually?

### CODE REVIEW

**Comment by wing328** [comment]
@k1w1m8 thanks! The change looks good to me.

**Comment by k1w1m8** [comment]
Great, thanks. 

Are you happy for it be up to users of supportJava6 to add commons.io dependency manually? Is there somewhere we should document that?

**Comment by wing328** [comment]
Ideally we should do it automatically in the pom.xml, build.gradle, sbt.build so as to save the developer's time.

**Comment by k1w1m8** [comment]
Ah yes, of course. Doh. Forgot we generated those too.

**Pull request merged**
