### PR TITLE
Adding support for properties in ComposedModel

### PR DESCRIPTION
**Pull request by gracekarina**
### PR checklist
Branch: Master

### Description of the PR
refs - swagger-api/swagger-parser/issues/1143 - Adding support for properties in ComposedModel
depends on https://github.com/swagger-api/swagger-parser/pull/1241

### CODE REVIEW

**Comment by frantuma** [comment]
please build

**Comment by frantuma** [comment]
please build

**Comment by frantuma** [comment]
please build

**Comment by frantuma** [comment]
please  build

**Comment by frantuma** [comment]
please build

**Comment by spacether** [comment]
@gracekarina 
Additional properties should also be allowed in composed schemas, but that feature is blocked by a bug in swagger-parser https://github.com/swagger-api/swagger-parser/issues/1252

**Pull request merged**
