### PR TITLE
[PHP] Fixing bug with composer project path in generated sdk

### PR DESCRIPTION
**Pull request by mikolajprzybysz**
There couple of issues with the current version:
* CliOptions `composerVendorName` and `composerProjectName` have no effect, because `gitUserId` and `gitRepoId` have default values so the inverted condition will never work.
* Further more CliOptions `gitUserId` and `gitRepoId` eventhough they would work they are not documented when running `java -jar swagger-codegen-cli.jar config-help -l php` or anywhere else.

### CODE REVIEW

**Comment by arnested** [comment]
Apparently `composerVendorName` and `composerProjectName` were recently deprecated (#2388 / 532d22c5a301ae8e38919e725fe2e264dc3f76d8). So changing back to using them seems wrong.

So I guess the right fix must be to make `gitUserId` and `gitRepoId` work / being documented.

@wing328, can you shed some light on what direction to take?

**Comment by mikolajprzybysz** [comment]
@arnested you are right, I did not notice it got deprecated.

**Comment by wing328** [comment]
@arnested yes, we should move to `gitUserId` and `gitRepoId`, which can be used by other langauges as well.

**Comment by arnested** [comment]
@mikolajprzybysz do you feel like having a go at getting `gitUserId` and `gitRepoId` into the output `config-help`?

Otherwise I can take a go at it sometime but I don't if I'll make it this week and I'm going to Barcelona for vacation next week.

**Comment by wing328** [comment]
@arnested currently, `gitUserId` and `gitRepoId` usage are shown in the general help
```
        --git-repo-id <git repo id>
            Git repo ID, e.g. swagger-codegen.

        --git-user-id <git user id>
            Git user ID, e.g. swagger-api.
```
ref: `java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar help generate`

IMO, a tutorial to walk through an example of generating PHP client covering some CLI options would help new users to understand the typical usage.

**Comment by wing328** [comment]
@mikolajprzybysz FYI. Some links in the markdown documentation are broken and I've filed https://github.com/swagger-api/swagger-codegen/pull/2822 to fix it.

**Comment by mikolajprzybysz** [comment]
@wing328 thanks for the info I will rebuild my project.
@arnested Today I only managed to add gitUserId and gitRepoId to php config-help as I don't have so much time I will try to fix rest this week.

**Comment by mikolajprzybysz** [comment]
Ok so I fixed the issue now it works like this:

Case 1
config contents:
```json
{
  "composerVendorName" : "myCompany",
  "composerProjectName" : "myProjectSdk"
}
```
generated project path in composer and readme files: `myCompany/myProjectSdk`

Case 2
config contents:
```json
{
  "gitUserId" : "myCompany",
  "gitRepoId" : "myProjectSdk"
}
```
generated project path in composer and readme files: `myCompany/myProjectSdk`

Case 3
config contents:
```json
{
  "composerVendorName" : "myCompany",
  "composerProjectName" : "myProjectSdk"
  "gitUserId" : "myCompany",
  "gitRepoId" : "myProjectSdk"
}
```
generated project path in composer and readme files: `myCompany/myProjectSdk`

Case 4
config contents:
```json
{
  "composerVendorName" : "composerMyCompany",
  "composerProjectName" : "composerMyProjectSdk"
  "gitUserId" : "gitMyCompany",
  "gitRepoId" : "gitMyProjectSdk"
}
```
generated project path in composer and readme files: `composerMyCompany/composerMyProjectSdk`

**Comment by wing328** [comment]
@mikolajprzybysz thanks for the fix.

Just so we're all on the same page, **`composerVendorName` and `composerProjectName` will be deprecated and replaced by `gitUserId` and `gitRepoId` respectively in the future stable release of Swagger Codegen.**

**Pull request merged**
