### PR TITLE
fixing a NPE when autoboxing uninitialized boolean

### PR DESCRIPTION
**Pull request by dandonovsc**

### CODE REVIEW

**Comment by dandonovsc** [comment]
fixing a NPE when autoboxing uninitialized boolean

**Comment by wing328** [comment]
@dandonovsc thanks for the PR. Do you mind sharing the swagger spec for repeating the issue?

**Comment by dandonovsc** [comment]
@wing328 my spec is a generated json file from swagger-ui that i hit at /v2/api-docs.json. Unfortunately it is pretty big end extensive and my domain schema is proprietary, but I started getting the NPE when I added a field that has a list of maps ( List<Map<String,Object> sample ). The json spec snippet looks like this:

{"properties":{"sample":{"type":"array","items":{"$ref":"#/definitions/Map«string,object»"}}

**Comment by wing328** [comment]
@dandonovsc thanks. I'll try to repeat the issue using that.

**Comment by wing328** [comment]
@dandonovsc in the spec snippet, is `items` a map (key is string, value is object)? If yes, it should be define as follows:
```
{
  "type": "object",
  "additionalProperties": {
    "type": "object"
  }
}
```
(the key can only be string so there's no need to specify it)

**Comment by dandonovsc** [comment]
@wing328 yes, the items is a Map of key string value object. Please keep in mind my schema is not manually defined but generated by swagger-ui against my public API. Hence I have no control over the schema. I realize this might be an issue of the swagger-ui library, but still the null check against uninitialized boxed primitive is legit, and in my case the codegen works great with this patch.

Also on the same topic , just a heads up: when swagger-ui generates schema when running against declared request parameter that is a List of strings, and builds json schema like this :

"parameters":[{"name":"id","in":"path","description":"id or list of ids of the items  to be retrieved","required":false,"type":"array","items":{"type":"string"}

then running codegen throws the following exception:

java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
	at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:496)
	at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:307)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:656)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1195)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1009)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:470)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:415)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:184)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

I believe the problem is because the json spec shows an array of primitives and not a $ref to a declared object

**Comment by wing328** [comment]
I don't think swagger-ui can generate swagger spec. It should take a swagger-spec and generate the interactive API explorer.

If your API is public, can you share the URL with us?

I couldn't repeat the NPE exception using the followings:
```
"parameters":[{"name":"id","in":"path","description":"id or list of ids of the items to be retrieved","required":false,"type":"array","items":{"type":"string"}
```

```
{"properties":{"sample":{"type":"array","items":{"$ref":"#/definitions/Map«string,object»"}}
```

**Comment by wing328** [comment]
@dandonovsc  we've made improvements to better handle exception in swagger-codegen. Would you please pull the latest master and see if that better handles the NPE you encountered?

**Comment by dandonovsc** [comment]
I am still getting the same error after running against the latest code from master

com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.NullPointerException) (through reference chain: io.swagger.models.properties.RefProperty["$ref"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:210)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:177)
	at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:187)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:647)
	at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:152)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:128)
	at com.fasterxml.jackson.databind.ObjectWriter._configAndWriteValue(ObjectWriter.java:800)
	at com.fasterxml.jackson.databind.ObjectWriter.writeValueAsString(ObjectWriter.java:676)
	at io.swagger.util.Json.pretty(Json.java:23)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:817)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1435)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1235)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:553)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:498)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:239)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)
Caused by: java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
	at sun.reflect.GeneratedMethodAccessor15.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:466)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:639)
	... 13 more
[main] WARN io.swagger.codegen.DefaultCodegen - Error obtaining the datatype from RefProperty:io.swagger.models.properties.RefProperty@e8fe9c77. Datatype default to Object
java.lang.NullPointerException
	at io.swagger.models.properties.RefProperty.get$ref(RefProperty.java:52)
	at io.swagger.codegen.DefaultCodegen.getSwaggerType(DefaultCodegen.java:590)
	at io.swagger.codegen.languages.JavaClientCodegen.getSwaggerType(JavaClientCodegen.java:362)
	at io.swagger.codegen.DefaultCodegen.fromProperty(DefaultCodegen.java:820)
	at io.swagger.codegen.DefaultCodegen.fromParameter(DefaultCodegen.java:1435)
	at io.swagger.codegen.DefaultCodegen.fromOperation(DefaultCodegen.java:1235)
	at io.swagger.codegen.DefaultGenerator.processOperation(DefaultGenerator.java:553)
	at io.swagger.codegen.DefaultGenerator.processPaths(DefaultGenerator.java:498)
	at io.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:239)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:188)
	at io.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:35)

I was going to attach the json from my /v2/api-docs generated file but am unable to , says "Attaching documents requires write permission to this repository". However I know exactly why this exception is being thrown . It is from this segment in the json:

```javascript
   "/physician": {
            "get": {
                "tags": [
                    "physician"
                ],
                "summary": "Provider search ",
                "description": "",
                "operationId": "findProvidersUsingGET",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json",
                    "*/*"
                ],
                "parameters": [
                                       {
                        "name": "additional",
                        "in": "query",
                        "description": "",
                        "required": false,
                        "type": "ref"
                    },
                                        {
                        "name": "page",
                        "in": "query",
                        "description": "page",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    },
                    {
                        "name": "size",
                        "in": "query",
                        "description": "size",
                        "required": false,
                        "type": "integer",
                        "format": "int32"
                    }
                ]
```
The "additional" request param and it's type $ref. This json has been generated by io.springfox:springfox-swagger2:2.2.2 which scans my Spring and Swagger annotations in the request mapping. The field that generates the $ref meta is of type `java.util.List<String>` . I am suspicious that the primitive type of the List is the reason the metadata of the api-docs is not generated correctly. I have other bindings of java.util.List of type composite POJOs and the codegen works correctly with them.   
```javascript 
        "ProviderWorkSpace": {
            "properties": {
                "count": {
                    "type": "integer",
                    "format": "int64"
                },
                "geoPoint": {
                    "$ref": "#/definitions/GeoLocation"
                }
                  
         "GeoLocation": {
            "properties": {
                "lat": {
                    "type": "number",
                    "format": "double"
                },
                "lon": {
                    "type": "number",
                    "format": "double"
                }
            }
        }
````

Not , this might not be an issue of swagger-codegen but springfox-swagger instead. The reason I opened the pull request was a legit NPE caused in a different part of the code. I just felt like I need to report this issue as well

**Comment by wing328** [comment]
@dandonovsc can you put your /v2/api-docs at https://gist.github.com instead?

**Comment by dandonovsc** [comment]
https://gist.github.com/dandonovsc/6447855740b79dff25f8

**Comment by wing328** [comment]
Thanks. I'll use it to reproduce the issue and confirm the fix you submitted.

**Comment by wing328** [comment]
@dandonovsc  I tested with your PR and the the latest master. Both show NPE but latest master has better handle of the NPE, e.g. default to object.

Please give the latest master a try as there are some enhancements to swagger-parser.

**Comment by dandonovsc** [comment]
@wing328 I think that you can go ahead and close this PR since the mainstream code has been  advanced and is probably handling more than what I initially submitted. I think that the issue that I am seeing  now with the references of lists of generic types comes from either SwaggerUI or Springfox generating invalid api-docs schema. Thank you

**Comment by wing328** [comment]
@dandonovsc first of all thanks for submitting the PR to fix the NPE. We truly appreciate your contribution. If you need further help from us on this, please feel free to reopen the issue.

**Pull request closed without merging**
