### PR TITLE
Update JavaJaxRS/resteasy/api.mustache to have swagger annotations

### PR DESCRIPTION
**Pull request by JLLeitschuh**
### PR checklist

- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Update resteasy api classes to have swagger annotations

The annotations should now appear on generated resteasy API classes.

### CODE REVIEW

**Comment by wing328** [comment]
@JLLeitschuh thanks for the PR. Please run the following to update Jax-RS RestEasy Petstore sample.
```
./bin/jaxrs-resteasy-petstore-server.sh
./bin/jaxrs-resteasy-joda-petstore-server.sh
```

**Comment by JLLeitschuh** [comment]
I just modified these files in the github UI. I didn't even clone the repository on my system. Hahhah. 
Will do.

**Comment by JLLeitschuh** [comment]
Is this technically a breaking change because it adds a dependency upon the swagger api's for these two generated projects that didn't have this dependency before?

**Comment by wing328** [comment]
@JLLeitschuh yes, please submit the PR against the 2.3.0 branch instead.

**Comment by JLLeitschuh** [comment]
Done! Love that you can change the PR base right in github.

**Comment by wing328** [comment]
@JLLeitschuh Merged. Thanks for the contribution!

**Pull request merged**
