### PR TITLE
[python] Add default Configuration

### PR DESCRIPTION
**Pull request by mbohlool**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
Adding a default configuration for python client. A use-case for this is a config loader can be called at the beginning of the code to load config in the default location and other API calls do not need to load config again or keep a configuration object.

### CODE REVIEW

**Comment by mbohlool** [comment]
cc @wing328 @taxpon @frol

**Comment by frol** [comment]
This looks good to me, but the `test_separate_default_config_instances` test has to be fixed.

**Comment by mbohlool** [comment]
@frol I've changed the implementation and this one passes test. please take another look.

**Comment by frol** [comment]
I would organize everything into a single class with `__new__` / `__call__` / meta class implementation (it is a singleton pattern) + class-methods, because it will solve a few problems with the current approach: 

* `isinstance(config, Configuration)` will work
* the naming will be in line with PEP8 recommendations
* everything will be in a single place

**Comment by mbohlool** [comment]
@frol  good point. I've changed it. Please take another look.

**Comment by frol** [comment]
@mbohlool This looks much cleaner to me! Thank you! 

@wing328 I think, it is ready for merge.

**Pull request merged**
