### PR TITLE
add undertow test template and upgrade framework to 0.1.6

### PR DESCRIPTION
**Pull request by stevehu**
### PR checklist
- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
### Description of the PR

Add test template for undertow generator and upgrade framework to version 0.1.6.

### CODE REVIEW

**Comment by stevehu** [comment]
The travis-ci builds on both jdk7 and jdk8 and my code base is on Java 8. If this is not possible to merge, then I will stay in my fork. The current ci script prevent developers to use any new features of Java 8.

**Comment by wing328** [comment]
Thanks for the PR. We'll need to add a script to skip the test if it's running on jdk7 so that we can merge this change and continue to leverage CI (travis) to cover the change.

**Comment by stevehu** [comment]
@wing328 Thanks for the quick actions. I thought there is no work around. Anyway, why do we limit developers to work on Java 7 with this travis-ci script? Do you have a plan to drop this jdk7 test and embrace Java 8:)

**Comment by wing328** [comment]
I prefer to keep jdk7 support at the moment as I believe jdk7 is still pretty popular (even though it has reached the EOL)

(there's another thread about updating Java API client to support jdk6, which has reached EOL a while ago)

**Comment by stevehu** [comment]
@wing328 I am not talking about to remove jdk7 support at all. Just enable jdk8 as more and more developers are using it. If we build with jdk8 only, jdk7 or jdk6 code will work as well. In the current setup, jdk8 is not even allowed.

**Comment by stevehu** [comment]
I saw this issue is closed. Is Java 8 allowed in swagger-codegen now?

**Comment by wing328** [comment]
@stevehu sorry. Can you please submit a new one?

I couldn't reopen it as the PR is based on "unknown repository"

**Comment by stevehu** [comment]
Since I could not convince the team that Java 8 is backward compatible to Java 7 and I have to support GraphQL and RPC, I created my own [light-codegen](https://github.com/networknt/light-codegen) instead.

**Pull request closed without merging**
