### PR TITLE
[Swift] #3036 Make APIHelper.convertBoolToString return nil for nil input

### PR DESCRIPTION
**Pull request by Landschaft**
This will prevent the creation of an empty body for GET requests.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by Landschaft** [comment]
What can I do to fix that?

**Comment by wing328** [comment]
@Landschaft there are some solutions mentioned in http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

You can also add the email address (setup locally in your dev environment) in your commit to your Github account

**Comment by jaz-ah** [comment]
+1 looks good - thx!

**Comment by Landschaft** [comment]
@wing328 thanks for your hints. I've updated the authorship of the commit.

**Pull request merged**
