### PR TITLE
Fixes #8988, #8849 New generator options and template improvements + required bug fix

### LINKED ISSUE #8849: [JavaScript] index.js and ApiClient.js generated to incorrect location
##### Description

JavaScriptClientCodegen is broken, and has been for some while. The breakage is that two of the supporting files, ApiClient.js and index.js, are now generated to the hard-coded ${output}/src directory, ignoring the sourceFolder configuration parameter. This can break their module references to the api and model modules if either a sourceFolder other than src is specified or if an invokerPackage is specified. The two files need to be moved back into ${sourceFolder}/${invokerPackage}, otherwise nothing will work! The sample in swagger-codegen/samples/client/petstore/javascript does not override sourceFolder nor does it specify an invokerPackage, so it looks like this, which _does_ work:

```
src/
    api/
        PetApi.js
        ...
    model/
        Animal.js
        ....
    ApiClient.js
    index.js (requires api/*, model/*)
```
**As things currently stand it is no longer possible to generate a project with this structure** if you override sourceFolder and/or invokerPackage. Instead, you'll end up with:
```
${sourceFolder}/
    ${invokerPackage}/
        api/
            PetApi.js
            ...
        model/
            Animal.js
            ....
src/
    ApiClient.js
    index.js (requires unresolvable api/*, model/*)
```

I am quite familiar with this code, as a couple of years ago I submitted several PRs, including one to get proper JSDoc comments that can be parsed by both JSDoc and Tern.js.

In addition, the test specification files are generated to ${outputFolder}/test/api/\*ApiTest.spec.js and ${outputFolder}/test/model/\*.spec.js and contain define() / require() calls that expect the index file to be at (hard-coded) ../../src/index. Given that the proposed fix entails moving index.js and ApiClient.js back to ${sourceFolder}/${invokerPackage} where they belong, the test spec files will have to account for the possbility that the generator configuration might specify an invokerPackage, in which case the index file would be located at ../../${sourceFolder}/${invokerPackage}/index. Furthermore, the output location of the test specification files does not itself currently include ${invokerPackage} and as a consequence when performing multiple YAML generations to the same output folder there is the possibilility of name collisions between identically named APIs or models from different YAMLs. To guard against this possibility the spec files should instead be generated to test/${invokerPackage}/api/\*ApiTest.spec.js and test/${invokerPackage}/model/\*.spec.js, and the relative location of the index files adjusted to suit.

##### Swagger-codegen version

2.4.0-SNAPSHOT (regression since 2.1.6, not exactly sure when)

##### Swagger declaration file content or url

I am not permitted to post the proprietary YAMLs for which this effect is observed but it should be observable with any YAML (e.g., PetStore).

##### Command line used for generation

Generated using swagger-codegen-maven-plugin:
```
<configuration>
	<language>javascript</language>
	<inputSpec>${project.build.yaml.directory}/ae.yaml</inputSpec>
	<output>${project.build.objectapi.directory}</output>
	<invokerPackage>ae</invokerPackage>
	<configOptions>
		<sourceFolder>.</sourceFolder>
	</configOptions>
</configuration>
```

##### Steps to reproduce

Generate the JavaScript then attempt to load the generated index.js or ApiClient.js using AMD or CommonJS - this will fail because src/index.js and ApiClient.js refer to modules under ${invokerPackage}. 

##### Related issues/PRs

#8264, possibly

##### Suggest a fix/enhancement

Revert the swagger-generator change that moved the output location of these two files:

```
    final String[][] JAVASCRIPT_SUPPORTING_FILES = new String[][]{
            ...
            new String[]{"index.mustache", "src/index.js"},
            new String[]{"ApiClient.mustache", "src/ApiClient.js"},
            ...
    };
```

which used to be configured like this in the preprocessSwagger(Swagger) method:

```
        supportingFiles.add(new SupportingFile("index.mustache", createPath(sourceFolder, invokerPackage), "index.js"));
        supportingFiles.add(new SupportingFile("ApiClient.mustache", createPath(sourceFolder, invokerPackage), "ApiClient.js"));
```
I forgot to mention: the current state of affairs prevents you from generating multiple YAMLs to different invokerPackages then aggregating the results, since the index.js and ApiClient.js files are now shared between all executions and thus can only relate to the first of these (subsequent generations skip these files).

I have prepared a fix, for which I will submit a PR in due course.

### LINKED ISSUE #8988: [JavaScript] New generator options and template improvements
##### Description

I've recently developed some new generator options and associated template improvements for the **OpenAPITools/openapi-generator** JAX-RS/CXF server generator, including the ability to generate random test data and serve it up from the generated CXF services, with the additional option of saving/loading the data from a file - see https://github.com/OpenAPITools/openapi-generator/issues/1158. Hitherto the service implementation methods were essentially empty stubs - with this option they can be fully functional services that actually return syntactically valid (if static) data. The PR#https://github.com/OpenAPITools/openapi-generator/pull/1879 is pending review.

SO... in the JavaScript world I've also added a related option to the **swagger-api/swagger-codegen** JavaScript client generator to enable the generated Mocha tests to read the same test data file format and use the data when invoking the service and to compare what the service returns with the expected response. As an alternative approach to loading the test data from a file, I've also made some test template enhancements to support deep programmatic validation of service response values - previously, the Mocha spec files were essentially empty stubs with no assertions and it was a lot of work to populate them. I've also fixed a couple of bugs (including https://github.com/swagger-api/swagger-codegen/issues/8849) along the way.

This Enhancement Issue is to enable me to make this contribution (I already have the necessary legal approval, having done so before).

##### Swagger-codegen version

2.4.0-SNAPSHOT. This is (mostly) an enhancement.

##### Swagger declaration file content or url

n/a

##### Command line used for generation

This enhancement will add the following JavaScript generator options:
- loadTestDataFromFile: Load test data from a JSON file (default false)
- testDataFile: JSON file to contain test data (ignored unless loadTestDataFromFile=true, default ${output}/test/test-data.json)
- preserveLeadingParamChar: Preserves leading $ and _ characters in parameter names. (default false) [Currently they get stripped out, not sure why, and this will remain the default behaviour. This was originally necessitated by the fact that the Java generators do not strip leading $ and _ characters from parameter names, but it should be a useful option to some users especially where **ODATA compliance** is important.]

##### Steps to reproduce

Run bin/javascript-override-default-config-petstore.sh to generate an example that uses the new options.

##### Related issues/PRs

This contribution builds on my previous contributions to the JavaScript Swagger-Codegen generator, see #2258 and related.

##### Suggest a fix/enhancement

I have raised PR#https://github.com/swagger-api/swagger-codegen/pull/9054 with the enhancement and some associated fixes.

### PR DESCRIPTION
**Pull request by demonfiddler**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes #8988: New generator options and template improvements

- New options loadTestDataFromFile, testDataFile and
preserveLeadingParamChar
- Mocha test templates now emit useful assertions on deep response
content (loadTestDataFromFile=false)
- Alternatively, Mocha tests perform deep equality assertions against
response data from file (loadTestDataFromFile=true)
- A new sample to validate correct operation of the new options
- Add scripts to generate javascript-override-default-config sample
- Regenerate sample JavaScript projects

Fixes #8849: Emit index.js and ApiClient.js to ${invokerPackage}

- Emit index.js and ApiClient.js to ${invokerPackage}
- Update index.mustache and api_client.mustache to compute correct path
  to dependency modules

### CODE REVIEW

**Comment by demonfiddler** [comment]
Awww, the Travis CI build failed in a Ruby test... I haven't touched anything remotely Ruby-related - only JavaScript and one innocuous bug fix in DefaultCodegen.

**Comment by frantuma** [comment]
Test has been fixed in #9061 can you please rebase?

**Comment by demonfiddler** [comment]
Tests all passing now - any chance of accepting this PR?

**Comment by demonfiddler** [comment]
CC @CodeNinjai I would appreciate a code review for this PR. Thanks!

**Comment by demonfiddler** [comment]
After four months and repeated rebases to resolve merge conflicts, this PR has still not been accepted, which as a long-standing open source enthusiast and contributor I find hard to come to terms with. This contribution represents several months of painstaking effort from a large software company, who would very much like to continue using and supporting Swagger Codegen. **However, we cannot afford to do so if our contributions are to be ignored or rejected.**

**PLEASE PLEASE PLEASE** can someone either merge this PR now or explain to me why it has been rejected and what changes need to be made in order for it to be accepted?

Thanks, in anticipation of a timely response.

**Comment by HugoMario** [comment]
hello @demonfiddler , thanks a lot for this PR and please, forgive me with this long delay. i've been crazy busy these months :/ anyway i like your changes and they look good for me.

i expect to "hear" from you again in the future xD

**Pull request merged**
