### PR TITLE
Typescript Node: Support Multiple Api Key Auth Methods

### PR DESCRIPTION
**Pull request by pixelshaded**
https://github.com/swagger-api/swagger-codegen/issues/2274

Generate enum from api key auth methods. Use this to set api key of authentication. Update test client to set multiple keys.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR wont' count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

**Comment by pixelshaded** [comment]
thanks for the heads up

**Comment by bherila** [comment]
I am going to merge this into my parent PR now.

**Comment by bherila** [comment]
Here it is: https://github.com/swagger-api/swagger-codegen/pull/2459/commits/b2329f559a8d1791f18444a6bc12a61181a4ec5d

**Comment by wing328** [comment]
@pixelshaded thanks for the PR. The change looks good and test cases passed.

**Pull request merged**
