### PR TITLE
Newline escaping disabled for HTML and HTML2 generators

### PR DESCRIPTION
**Pull request by bazhenov**
### PR checklist
- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
### Description of the PR

Newline escaping disabled for HTML and HTML2 generators. Escaping failing Markdown processors to work correctly on descriptions.

### CODE REVIEW

**Comment by wing328** [comment]
Your suggestion sounds reasonable. I'll review your PR shortly. Thanks for your contribution.

**Comment by GlenDC** [comment]
Does this issue fixes the bug where newline characters (`\n`) in a string value (e.g. `info.description`) get ignored, instead of forcing an HTML linefeed?

e.g. I would expect `foo\nbar` to be translated to:
```html
foo<br>bar
```
or however that should be done in the generated (static) HTML. But for now it just seems to render `foo\nbar` 

Or should I open a new issue for this and, later, open a PR with a fix for it?

**Comment by bazhenov** [comment]
Unfortunately, it doesn't, as far as I can tell.

**Comment by GlenDC** [comment]
So I should open a new issue for this?

**Comment by bazhenov** [comment]
Definitely

**Pull request merged**
