### PR TITLE
Add android dependency to pom if 'parcelableModel' is set (#5801)

### PR DESCRIPTION
**Pull request by BjoernPetersen**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

The generated client stub generated with the `parcelableModel` option could not be built with Maven before, because `Parcelable` and `Parcel` were undefined.

This PR adds the following dependency to the pom.xml, if `parcelableModel` was set:
```xml
<dependency>
    <groupId>com.google.android</groupId>
    <artifactId>android</artifactId>
    <version>4.1.1.4</version>
    <scope>provided</scope>
</dependency>
```

### Known issues
This doesn't solve the somehow related issue #4709.    
The `petstore-with-fake-endpoints-models-for-testing.yaml` used to generate the samples defines `AnimalFarm`, which still makes the petstore sample uncompilable:
```yaml
AnimalFarm:
    type: array
    items:
      $ref: '#/definitions/Animal'
```

### CODE REVIEW

**Comment by wing328** [comment]
Link to https://github.com/swagger-api/swagger-codegen/issues/5801

**Comment by wing328** [comment]
@BjoernPetersen thanks for the PR. We'll review and let you know if we've any question.

**Comment by wing328** [comment]
@BjoernPetersen PR merged into master. Thank you for your contribution.

Tests passed: https://travis-ci.org/swagger-api/swagger-codegen/builds/241090026

**Comment by wing328** [comment]
@BjoernPetersen For #4709, my understanding is that there's a workaround by defining an array of models in another way.

If not, please open a new issue with a minimal spec to reproduce the issue.

**Comment by BjoernPetersen** [comment]
@wing328 I know about that workaround and already applied it to my project.    
The problem is that the petstore samples are generated from a file without the workaround.

However, as you said, this belongs in a new issue.

**Pull request merged**
