### PR TITLE
Android & Java Template Modifications to address List of Query Parameters Issue

### PR DESCRIPTION
**Pull request by sudohippie**
This is to solve the issue #484. Changes are for Android and Java language.

Made the following changes:

* Added a new template called QueryParam.mustache 
* Changed queryParams data structure from Map<String, String> to Set<QueryParam>
* Method signature changes to address new data structure.

### CODE REVIEW

**Comment by sudohippie** [comment]
@who, @webron - I ran the integration tests, and noticed some issues. Modified the sample clients and their unit tests to reflect the changes to the templates.

The tests I ran were:

```
./bin/java-petstore.sh;
./bin/android-java-petstore.sh;
mvn integration-test -Pjava-client;
mvn integration-test -Pandroid-java-client;
```

**Comment by xhh** [comment]
I'm negative on this PR. It adds support of `multi` `collectionFormat` but removes support of `csv` format.

The real problem here is that the current generator does not (fully) support the [`collectionFormat`](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#user-content-parameterCollectionFormat) for parameters, we should address it by supporting all of them.

**Comment by sudohippie** [comment]
@xhh - What you say makes sense. I'll take a look in to codegen to make it extendable.

**Comment by sudohippie** [comment]
Closing this PR. Look at #893.

**Pull request closed without merging**
