### PR TITLE
Fixed config to support transport, and other options

### PR DESCRIPTION
**Pull request by neilotoole**
Addresses #3461 and #3464.

### CODE REVIEW

**Comment by guohuang** [comment]
you forgot to checkin the generated code. otherwise looks good

**Comment by neilotoole** [comment]
@guohuang "checkin the generated code" ... apologies, I may be out of the loop on what is expected here? Check which generated code in, and to where? Again, apologies for the confusion.

**Comment by guohuang** [comment]
@neilotoole you changed the template files, all the files in this folder are outdated, https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/go/go-petstore,

**Comment by neilotoole** [comment]
@guohuang Ah, thank you, I hadn't done this on any of my previous PRs. I will update this PR accordingly.

**Comment by wing328** [comment]
@neilotoole when you've time, please update the Go petstore sample and then I'll merge the PR

**Comment by wing328** [comment]
I've updated the Go Petstore sample and pushed the change to master.

**Pull request merged**
