### PR TITLE
Ruby client: Faraday gem must be loaded correctly when combined with ElasticSearch

### PR DESCRIPTION
**Pull request by wtfiwtz**
This adds the extra `require` statements that are needed for loading Faraday correctly to the generated Ruby client library.

See also https://github.com/typhoeus/typhoeus/issues/226

```
          Ethon::Errors::InvalidOption:
            The option: disable_ssl_peer_verification is invalid.
            Please try ssl_verifypeer instead of disable_ssl_peer_verification.
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy.rb:238:in `block in set_attributes'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy.rb:235:in `each_pair'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy.rb:235:in `set_attributes'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy/http/actionable.rb:99:in `setup'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy/http/post.rb:16:in `setup'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy/http.rb:39:in `http_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/easy_factory.rb:81:in `get'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/addable.rb:19:in `add'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/memoizable.rb:41:in `add'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/cacheable.rb:10:in `add'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/block_connection.rb:30:in `add'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/stubbable.rb:23:in `add'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/before.rb:27:in `add'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/queueable.rb:77:in `dequeue_many'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/runnable.rb:14:in `run'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/typhoeus-1.0.2/lib/typhoeus/hydra/memoizable.rb:51:in `run'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:23:in `perform_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/adapter/typhoeus.rb:14:in `call'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:257:in `call'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/base.rb:257:in `perform_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-transport-1.0.18/lib/elasticsearch/transport/client.rb:128:in `perform_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-api-1.0.18/lib/elasticsearch/api/actions/indices/refresh.rb:49:in `refresh'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-model-0.1.9/lib/elasticsearch/model/indexing.rb:291:in `refresh_index!'
          # /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/elasticsearch-persistence-0.1.9/lib/elasticsearch/persistence/model.rb:71:in `refresh_index!'
          # ./spec/support/elasticsearch_helper.rb:8:in `refresh_elasticsearch_index'
          # ./spec/spec_helper.rb:33:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Ethon::Errors::InvalidOption:
          #   The option: disable_ssl_peer_verification is invalid.
          #   /Users/wtfiwtz/.rvm/gems/ruby-2.2.3/gems/ethon-0.9.0/lib/ethon/easy.rb:238:in `block in set_attributes'
```

### CODE REVIEW

**Comment by wing328** [comment]
@wtfiwtz thanks for the PR. Please run `./bin/ruby-petstore.sh` to update the Ruby petstore sample so that CI (travis) can test the change.

**Comment by wing328** [comment]
Also have you followed the suggestion to use `ssl_verifypeer` instead?
```
           The option: disable_ssl_peer_verification is invalid.
            Please try ssl_verifypeer instead of disable_ssl_peer_verification.
```

**Comment by wtfiwtz** [comment]
Yeah I did... basically without the require line for `typhoeus/adapters/faraday` it loads the incorrect adapter and breaks the library on lots of other things.

I should be able to do this add the petstore sample over the weekend or Monday.

**Comment by wing328** [comment]
@wtfiwtz I ran `rspec` in the updated Ruby petstore sample (samples/client/petstore/ruby) and got the following error:
```
ruby|ActivePipe-activepipe⚡ ⇒ rspec
/Users/williamcheng/.rvm/gems/ruby-2.1.1/gems/typhoeus-1.0.1/lib/typhoeus/adapters/faraday.rb:1:in `require': cannot load such file -- faraday (LoadError)
	from /Users/williamcheng/.rvm/gems/ruby-2.1.1/gems/typhoeus-1.0.1/lib/typhoeus/adapters/faraday.rb:1:in `<top (required)>'
	from /Users/williamcheng/Code/jul2016/swagger-codegen/samples/client/petstore/ruby/lib/petstore.rb:26:in `require'
	from /Users/williamcheng/Code/jul2016/swagger-codegen/samples/client/petstore/ruby/lib/petstore.rb:26:in `<top (required)>'
	from /Users/williamcheng/Code/jul2016/swagger-codegen/samples/client/petstore/ruby/spec/spec_helper.rb:2:in `require'
```
Did you get similar error in your local environment?

**Comment by wing328** [comment]
@wtfiwtz closing this as there's no update from you.

**Pull request closed without merging**
