### PR TITLE
added sort

### LINKED ISSUE #2190: Generator client/server lists should be alphabetized
`GET /gen/clients` and `GET /gen/servers` return the list of results in a seemingly random order. For usability, it would help if those responses where alphabetized.

### PR DESCRIPTION
**Pull request by fehguy**
Fixes #2190

### CODE REVIEW

**Comment by webron** [comment]
@wing328 - can you please review the change and merge if ok?

**Comment by wing328** [comment]
Sure let me review later today.

**Comment by wing328** [comment]
@fehguy @webron 

For server stub:
```
["aspnet5","haskell-servant","inflector","jaxrs","jaxrs-cxf","jaxrs-resteasy","nodejs","python-flask","scalatra","silex-PHP","sinatra","slim","spring-mvc"]                                                                                      
```

For API client:
```
["CsharpDotNet2","akka-scala","android","async-scala","clojure","csharp","dart","dynamic-html","flash","go","html","java","javascript","javascript-closure-angular","jmeter","objc","perl","php","python","qt5cpp","ruby","scala","swagger","swagger-yaml","swift","tizen","typescript-angular","typescript-node"]
```

Please note that `CsharpDotNet2` is the 1st element in the API client list since it starts with a capital letter `C`.

My suggestion is to rename it to `csharp-dotnet2` with another PR.

**Comment by fehguy** [comment]
would a case insensitive search be good here?

**Comment by wing328** [comment]
Yes, that will do as well.

Personally I prefer renaming `CsharpDotNet2` to `csharp-dotnet2` to make the naming (lower case) consistent across all API client and server stub generator.

**Comment by wing328** [comment]
I think case insensitive sort is a better solution for now as renaming requires corresponding change in swagger editor as well.

Let me know if you want me to update the code to use insensitive sort.

**Comment by wing328** [comment]
Tested with `String.CASE_INSENSITIVE_ORDER` and worked as expected:
```
["akka-scala","android","async-scala","clojure","csharp","CsharpDotNet2","dart","dynamic-html","flash","go","html","java","javascript","javascript-closure-angular","jmeter","objc","perl","php","python","qt5cpp","ruby","scala","swagger","swagger-yaml","swift","tizen","typescript-angular","typescript-node"]
```

**Pull request merged**
