### PR TITLE
Update User-Agent for Ruby, Python, PHP, Java, Android

### PR DESCRIPTION
**Pull request by wing328**
Make the User-Agent configurable via `--http-user-agent` CLI option.

Default to `Swagger-Codegen/{version}/{language}`

### CODE REVIEW

**Comment by jqr** [comment]
I'm curious why this was made an option to generate instead of something in the `config.json`. Is there a general move towards options for new things?

**Comment by wing328** [comment]
You can also supply the CLI option in the config, e.g.
```
{
  "sortParamsByRequiredFlag": true,
  "optionalAssemblyInfo": true,
  "httpUserAgent": "XXXXXX"
}
```
I did a test and worked for me. Can you give that a try?

**Comment by jqr** [comment]
Ah, that makes sense. Thanks!

**Comment by inska** [comment]
Hi @wing328,

When can I do like this on the Swift Client?

Thanks,

**Comment by wing328** [comment]
@inska I don't think anyone from the community has started working on it. I'll create a separate task for tracking to implement customisable user-agent in other langauges.

**Comment by wing328** [comment]
Now track via https://github.com/swagger-api/swagger-codegen/issues/2715

**Pull request merged**
