### PR TITLE
#1907 JsonModel deserialization errors

### PR DESCRIPTION
**Pull request by mateuszmackowiak**

### CODE REVIEW

**Comment by wing328** [comment]
@mateuszmackowiak thanks for the PR. Please update the Petstore sample for Objc as mentioned in the guidelines for contributing: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by wing328** [comment]
Please rebase on the latest master and update the test cases as I got error below:
```
/var/tmp/pr/mateuszmackowiak/swagger-codegen/samples/client/petstore/objc/SwaggerClientTests/Tests/DeserializationTest.m:148:34: error: no visible @interface for 'SWGApiClient' declares the selector 'deserialize:class:'
    NSArray *result = [apiClient deserialize:data class:@"NSArray* /* NSArray* /* NSString */ */"];
                       ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~
/var/tmp/pr/mateuszmackowiak/swagger-codegen/samples/client/petstore/objc/SwaggerClientTests/Tests/DeserializationTest.m:160:25: error: no visible @interface for 'SWGApiClient' declares the selector 'deserialize:class:'
    result = [apiClient deserialize:data class:@"NSNumber*"];
              ~~~~~~~~~ ^~~~~~~~~~~~~~~~~~~~~~
```

To run the integration test, please execute the following in `samples/client/petstore/objc/SwaggerClientTests`:

```
mvn integration-test -rf :ObjcPetstoreClientTests
```

**Comment by wing328** [comment]
@mateuszmackowiak looks like the rebase has some issues. I'll create a new one and cherry-pick the commits you created.

Likely this will be done after the 2.1.6 stable release.

**Comment by wing328** [comment]
@mateuszmackowiak also your commits are not linked to your github account, which means your contribution won't count toward https://github.com/swagger-api/swagger-codegen/graphs/contributors.

You will need to change the local git email setting to fix that.

**Comment by mateuszmackowiak** [comment]
@wing328 How about now?

**Comment by wing328** [comment]
@mateuszmackowiak the "Commits" tab is showing 250+ commits. My guess is that the rebase has not been done correctly.

I've handled similar situation before by cherry-picking your commits (which means the credits will still go back to your github account)

**Comment by mateuszmackowiak** [comment]
F.. Don't care about the credits. Then some other time. No time..

**Comment by wing328** [comment]
@mateuszmackowiak how urgently do you need this PR to get into master?

**Comment by mateuszmackowiak** [comment]
He don't care. But he will at the next proeject wright away..

**Comment by mateuszmackowiak** [comment]
Hey. I have piled up the changes into one commit that is created from the head of master on a new branch feature/obj/jsonModel_deserialization_errors.

**Pull request closed without merging**
