### PR TITLE
[TypeScript][Node] Resolve errors for strict compile

### PR DESCRIPTION
**Pull request by S64**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

I'd encountered some error on build with `strict` option.
This pull request is fix an error of `TS7017`.

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

### CODE REVIEW

**Comment by wing328** [comment]
FYI. I'll resolve the merge conflicts as part of the merge so don't worry about it.

**Comment by wing328** [comment]
@S64 Shall we actually add the `strict` option to tsconfig.json in TS Node Petstore client so as to catch the issue in the Travis CI moving forward?

**Comment by S64** [comment]
@wing328 Ok, Let's do so.
It'll be easier to optimize and performance improvement if enable `strict` flag. (and, It's commonly used.)
I added that in 793babf !

**Comment by wing328** [comment]
The change looks good to me.

I'll merge it later today if no one has further question/feedback on this.

**Comment by kenisteward** [comment]
Hey shuma.  Thanks for the pr!  I'm assuming you have locally compiled and
use a lobrary with no problem?  I can see something coming up as an issue
with umd built modules

**Comment by kenisteward** [comment]
Possibly see. I have not tested it yet.

**Comment by S64** [comment]
@kenisteward Thanks! I noticed some mistakes 😭. Maybe, `samples/client/petstore/typescript-node/npm/tsconfig.json` is not updated. I'll check and fix it.

**Comment by wing328** [comment]
Right, I'm missed `samples/client/petstore/typescript-node/npm/tsconfig.json` not being updated. I'll let this PR have more review first before merging.

@S64 please take your time. We appreciate your contribution to make the TS Node client generator better.

**Comment by S64** [comment]
@kenisteward @wing328 
I'd pushed 9 fixes. Please check a00da7e...86d8eaf . Roughly:

- Sync petstore's package.json, tsconfig.json. These is manually created.
- Fix templates and tests
- (Manual check of UMD compile)

**Comment by wing328** [comment]
> Sync petstore's package.json, tsconfig.json. These is manually created.

That's due to these files being whitelisted in `.swagger-codegen-ignore` at the moment.

I'll file another PR to remove those as we should always use the latest package.json, tsconfig.json from the TS node generator.

**Pull request merged**
