### PR TITLE
[All generators] Supports of hyphen-case to camelCase

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

I discovered that the `camelize` function doesn't support `hyphen-case` to `camelCase`. So I added the needed code. Tested by running all the samples from Java Play Framework and it doesn't change anything since all petstore examples are already camelCase or underscore_case. Maybe we should add an example of this. The "instagram" example from swagger.io is all hyphen-case.

### CODE REVIEW

**Comment by wing328** [comment]
@JFCote thanks for the PR. Do you mind adding a few test cases in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/java/io/swagger/codegen/CodegenTest.java#L28 to cover the change.

**Comment by JFCote** [comment]
@wing328 : I will do this next week as today I'm very busy. Thanks!

**Comment by wing328** [comment]
@JFCote Please take your time.

**Comment by JFCote** [comment]
@wing328 Just added the unit tests. Thanks!

**Comment by wing328** [comment]
@JFCote looks good to me 👍

**Pull request merged**
