### PR TITLE
add basic GUI app for swagger-codegen

### PR DESCRIPTION
**Pull request by championswimmer**
This is nowhere ready to be merged right now. Only putting this PR up to see if there is a need for this or will this be accepted. If yes, I'll work further on this. 

Right now only allows selecting a input file, and output directory, and language. 

Signed-off-by: Arnav Gupta <championswimmer@gmail.com>

### CODE REVIEW

**Comment by wing328** [comment]
Thanks @championswimmer. Personally I don't see any drawback adding a GUI for swagger codegen :)

**Comment by webron** [comment]
@championswimmer - just saw your message on IRC. Not sure if you're aware of it, but both the editor and the code generation can be ran in a closed environment that doesn't have access to the internet. The codegen has the 'generator' module which is what's deployed at http://generator.swagger.io/ and the editor, which can be installed locally, can be configured to run against the local deployment.

My main concern with adding another GUI module is that it would be difficult to maintain (for us) and would end up rotting.

**Comment by championswimmer** [comment]
@webron I understand that, and hence I wanted to make sure if this is needed.

I'll present my personal case - I know that they can be ran in a closed environment, but you do need to setup node and download quite a few npm dependencies, then you also have to setup and run a Java webserver for the generator. 

Instead, I have found using the codegen-cli much more simple. And hence was trying to achieve GUI functionality from that angle  - a portable, cross-platform dependency-free executable jar - that I can easily drop my swagger.yaml into, and it spews out the code.

**Comment by webron** [comment]
@championswimmer - don't get me wrong, I'm not saying the idea isn't good. I just don't know if it would do it good to be part of this project rather than as a standalone project that you (or someone else) maintains.

**Comment by fehguy** [comment]
Thanks--I'm going to close this out in favor of the swagger-generator or swagger-codegen-cli.  Thank you!

**Pull request closed without merging**
