### PR TITLE
Fix swagger.json supporting file for the node.js server (fixes #652)

### LINKED ISSUE #652: nodejs generator : /docs doesnt show all operations
Hi all and thanks for this great job !,
I know that embeded generators are in alpha stage but I have just noticed the following behavior : 
with nodejs generated code, UI (with /docs) shows only the last operation for each path.

for exemple : 
```
- /pet 
  - GET 
  - PUT 
```

the unique operation shown will be the PUT
Thx !

### PR DESCRIPTION
**Pull request by templth**

### CODE REVIEW

**Comment by wing328** [comment]
@templth Would you please elaborate a bit on the issue(s) this PR aims to fix ? Thanks

**Comment by templth** [comment]
@wing328 The aim is to fix the issue #652 (problem with the NodeJS server skeleton generation). All one method was handled for each path.

**Comment by wing328** [comment]
Thanks. I'll review it.

**Comment by templth** [comment]
You're welcome!

**Comment by wing328** [comment]
@templth thanks again for the PR. For the change (unused import) in DefaultGenerator.java, are those required ? Understood those (unused) import would not have performance impact but I think we should avoid unused import if possible.

**Comment by hgwood** [comment]
Looks like @templth has forgotten about this. I'll take a look.

**Comment by hgwood** [comment]
@wing328 All cleaned up: no impact on `DefaultGenerator`, and rebased on the latest develop_2.0.

**Comment by wing328** [comment]
Thanks @hgwood 

Merged

**Pull request merged**
