### PR TITLE
[Typescript][Angular2] update to angular2 release version

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Cherry-picking commits from #4223

NOTE: AbstractIntegrationTest is still disabled. We'll re-enable it later and perform tests in different platforms.

### CODE REVIEW

**Comment by wing328** [comment]
cc @Vrolijkx

**Comment by Vrolijkx** [comment]
Thanks @wing328  for helping me with my rebase problems.

**Comment by wing328** [comment]
@Vrolijkx I've merged the PR into 2.3.0. Please pull the latest to do a check when you've time. Thanks!

**Comment by kenisteward** [comment]
I don't see some of these changes on master.  is this correct?

**Comment by wing328** [comment]
@kenisteward this PR was merged into 2.3.0 (not master). Can you pull the latest 2.3.0 to see if you can find these changes?

**Comment by kenisteward** [comment]
They are definitely in 2.3.0. was just wondering if they should be in both.

**Comment by wing328** [comment]
@kenisteward I've updated the description with a list of changes. Can you elaborate on "some of the changes" (non-breaking) that you expect to see in the current master?

**Comment by kenisteward** [comment]
For instances the upgrades to the release of angular could safely be in master. I believe technically the module addition could as well because you can still import from the project directly like old setup or import the module as forConfig

**Comment by wing328** [comment]
> For instances the upgrades to the release of angular could safely be in master.

Yup, agree with you on that one. Do you mind submitting a PR against master for that?

**Comment by kenisteward** [comment]
I don't mind. How would I got about this? Just merge the non breaking commits into master?

**Comment by wing328** [comment]
> Just merge the non breaking commits into master?

Yup, that's one way to do it by cherry-picking the commits.

**Comment by wing328** [comment]
Ref: https://git-scm.com/docs/git-cherry-pick

**Pull request merged**
