### PR TITLE
[csharp] Update JsonSubTypes to 1.1.3 and use nuget dependency

### PR DESCRIPTION
**Pull request by manuc66**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- update JsonSubTypes to 1.1.3 by using nuget dependency (the package is compatible with net40)
- align all version of Newtonsoft.Json to 10.0.3
- update windows scripts

cc: @mandrean, @jimschubert

### CODE REVIEW

**Comment by jimschubert** [comment]
Isn't this nuget artifact incompatible with .net 3.5? I haven't pulled this to try, as I've been busy. .NET 3.5 isn't documented on the Nuget page.

Also, this nuget assembly has to be added to compile.mustache.

**Comment by manuc66** [comment]
@jimschubert The nuget is not compatible with .net 3.5.

Is .net 3.5 supported by swagger-codegen? (I don't see where)

**Comment by jimschubert** [comment]
Yes. Please run the CLI with `config-help -l csharp`.

The default conditions in our templates are .NET 3.5 compatible. Options are passed to templates for additional features such as async support. We also pass additional properties such as `net40` as helpers to indicate special cases. You can generate with debug flags enabled to see these template parameters.

**Comment by manuc66** [comment]
@jimschubert the nuget artifact is compatible with .NET 3.5 but on release `v1.2.0` (see: https://www.nuget.org/packages/JsonSubTypes/1.2.0#show-dependency-groups)

I'll make another PR in order to handle .NET 3.5

**Comment by jimschubert** [comment]
Cool. I didn't see that when I looked.

Are there API differences in usage between these versions? If not, it should just be a simple template switch in the project files, build script, and package file.

**Comment by manuc66** [comment]
@jimschubert There is no API differences in usage

**Pull request merged**
