### PR TITLE
Adding forRoot instead of forConfig and forcing only 1 instantiation of the ApiModule

### LINKED ISSUE #5608: Updating Typescript-Angular2 to forRoot instead of forConfig
##### Description

Currently the best practices for including a module and all of it's provided services for Angular is to use a static forRoot function explained here.
https://angular.io/docs/ts/latest/guide/ngmodule.html#!#core-for-root

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

The sample shows that the template does not use that function name and also includes the providers in the NGModule declaration instead of the forConfig

https://github.com/swagger-api/swagger-codegen/blob/2.3.0/samples/client/petstore/typescript-angular2/npm/api.module.ts

##### Steps to reproduce

run the generator under -l typescript-angular2

##### Related issues

None that are open

##### Suggest a Fix

I'd suggest that the template here
https://github.com/swagger-api/swagger-codegen/blob/2.3.0/modules/swagger-codegen/src/main/resources/typescript-angular2/api.module.mustache

to put the generation of providers in the function and to change the function name to forRoot so it meets current best practices

### PR DESCRIPTION
**Pull request by kenisteward**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

Should close #5608 to follow Angular Best practices

Technical committee reviewers

@TiFu @taxpon @sebastianhaas @Vrolijkx

### CODE REVIEW

**Comment by kenisteward** [comment]
@wing328 I'm not sure why CI is broken :x.  The errors I see have nothing to do with the changes i made but with some ruby stuff

**Comment by sebastianhaas** [comment]
I need to try locally, but from what I can tell this looks very reasonable to me :)

**Comment by kenisteward** [comment]
@wing328 can we get this merged?  I've tested this locally.  Or would you rather wait for one of the others to verify it?

**Comment by kenisteward** [comment]
@wing328 @sebastianhaas 

Updated the Readme to our current api standards.
Updated the listing of providers to make sure that users aren't forced to use .forRoot if they don't want (because they don't want to configure their providers initially)

**Pull request merged**
