### PR TITLE
Support file downloading in Java jersey2 client

### PR DESCRIPTION
**Pull request by ww-mgr**

### CODE REVIEW

**Comment by wing328** [comment]
@ww-mgr thanks for the PR. Do you mind updating the Petstore sample for Java Jersey2 API client as mentioned in the contributing guidelines?

**Comment by ww-mgr** [comment]
Sorry, I missed that part. I've updated the Petstore sample. All generated files have been changed because of the Generated annotation. It is better to commit only the relevant files next time?

**Comment by wing328** [comment]
That's ok. To me, it's fine to commit those files with the timestamps updated in the annotation only.

**Comment by wing328** [comment]
Test result looks good:
```
Tests run: 39, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 30.637 s
[INFO] Finished at: 2016-01-31T19:56:44+08:00
[INFO] Final Memory: 18M/245M
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
