### PR TITLE
[Swift3] Fixed compilation issue on macOS

### PR DESCRIPTION
**Pull request by davidpasztor**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

See #5878 for details.

### CODE REVIEW

**Comment by wing328** [comment]
@davidpasztor thanks for the PR. Please use 4-space instead of tab for code indentation.

**Comment by wing328** [comment]
Tests passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/255155237

**Comment by wing328** [comment]
cc @jgavris @Edubits @jaz-ah

**Comment by davidpasztor** [comment]
@wing328 changed the code indentation for 4-spaces instead of tab as requested.

**Comment by jgavris** [comment]
You'll want to run `./bin/swift3-petstore-all.sh` as we have a few other variants of the generator (`RxSwift` and `PromiseKit`).

**Comment by jgavris** [comment]
Also, if this didn't compile on macOS prior to this PR, and the CI wasn't failing, we should add a failing test configuration before fixing it.

**Comment by davidpasztor** [comment]
@jgavris thanks for the info, I have run that script as well and committed the changes.

**Comment by jgavris** [comment]
LGTM  - @wing328 looks like CI is getting rate limited by github a bit now

**Comment by wing328** [comment]
@jgavris the test result was good: https://travis-ci.org/swagger-api/swagger-codegen/builds/255155237

I'll find some time later this week to add the test for macOS

**Pull request merged**
