### PR TITLE
[Swift3] Download file fix

### PR DESCRIPTION
**Pull request by dwoodel**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fix for issue #6236 

The `schema: file` was unsupported.  The code now downloads a file to the file system and returns a file `URL`.

cc @wuf810

### CODE REVIEW

**Comment by dwoodel** [comment]
pushed up an additional file change.

**Comment by wuf810** [comment]
Again the same question as with my PR (https://github.com/swagger-api/swagger-codegen/pull/6273) any one know why travis may have failed?

**Comment by wing328** [comment]
cc @jaz-ah @jgavris @Edubits

**Comment by jaz-ah** [comment]
+1 LGTM @wing328

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@dwoodel the CI (travis) with updated Swift3 samples, failed with the following error:
```
/Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/AlamofireImplementations.swift:358:22: error: type 'DownloadException' cannot be nested in generic type 'AlamofireRequestBuilder'

    fileprivate enum DownloadException : Error {
```
Please take a look when you've time.

**Comment by dwoodel** [comment]
Yep seen the issue just fixing now.  @wing328 Iv commited under a different email address.  Iv updated my git config with my git hub email address will this fix the contribution problem. :/

**Comment by dwoodel** [comment]
Iv pushed the branch up.  Do a need a new PR to solve the contribution issue?

**Comment by wing328** [comment]
>  Iv updated my git config with my git hub email address will this fix the contribution problem? :/

Yes, it does. The commit is now correctly linked to your Github account.

**Comment by dwoodel** [comment]
I dont think that is me.  Some setup issue to do with travis I think?

**Comment by wing328** [comment]
Tests passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/264604574?utm_source=email&utm_medium=notification

**Comment by wing328** [comment]
@dwoodel thanks for the PR, which has been merged into master. When you've time, I wonder if you can make similar enhancement to the swift4 templates

cc @ehyche

**Comment by dwoodel** [comment]
Hi Wing will do!

**Comment by ehyche** [comment]
@wing328 @dwoodel @jaz-ah @jgavris @Edubits  : I have migrated this change to the swift4 module with this PR:

https://github.com/swagger-api/swagger-codegen/pull/6469

**Pull request merged**
