### PR TITLE
[PowerShell] add an option to specify C# client path

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- Add an option `csharpClientPath` to specify the path to the C# API client.
- revise auto-generated README.md

### CODE REVIEW

**Comment by larssb** [comment]
Hi @wing328,

Do I understand it correctly, that this feature has not yet been fully implemented in the newest version of codegen? Or am I misunderstanding something? As no csharp client is being created at all for the API I'm processing with codegen. My cmdline call looks like: `java -jar swagger-codegen-cli-2.2.3.jar generate -i ./octopusDeploy.j -o folderName -c config.json` and the config.json file contains `{
    "packageName": "Danske.Spil.Octopus.Deploy.API"
}` - so I would expect codegen to use the default folder for the csharp client. No folder i created. However, no errors or exceptions thrown....could you be so kind to give a hint on this 👍 ...

Thank you very much.

**Comment by wing328** [comment]
@larssb you will need to use the `csharpClientPath` option in config.json to specify the location of the C# SDK.
```
	csharpClientPath
	    Path to the C# API client generated by Swagger Codegen, e.g. $ScriptDir\..\csharp\SwaggerClient where $ScriptDir is the current directory. (Default: $ScriptDir\csharp\SwaggerClient)
```

**Comment by larssb** [comment]
Tried that and it is still not creating csharp client. No errors thrown. I also tried defining it as an --additional-properties parameter. Still no fun. Hmmm?

**Comment by wing328** [comment]
@larssb the C# SDK needs to be generated separately using `-l csharp`

**Comment by larssb** [comment]
ooooh okay I see. Thank you very much.

**Comment by wing328** [comment]
@larssb I'll update the help text to inform the users they need to generate the C# SDK separately.

**Comment by wing328** [comment]
UPDATE: revised wording via 30a176126aa3600b6252f80b84040a1ab351c125

**Pull request merged**
