### PR TITLE
[Swift3] Don't crash on invalid responses

### PR DESCRIPTION
**Pull request by philippelatulippe**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. Code generation succeeds and the tests pass, but in the PromiseKit version there seems to be errors that seem to indicate an outdated version of PromiseKit. Also the rxswift version has a test that expects a library to return an error when receiving a null body from a DELETE, but this the null body is handled just fine.
- [x] Filed the PR against the correct branch: `2.3.0` since there are breaking changes

### Description of the PR

Currently, generated swift3 code will call fatalError() when it encounters data that does not match the spec. See issue #4382. This PR implements my suggested fix. Decode methods return an enum with two cases: success, which contain a result, and failure, which contain an error. 

All the relevant changes are in the files *modules/swagger-codegen/src/main/resources/swift3/Models.mustache* and *swagger-codegen/src/main/resources/swift3/AlamofireImplementations.mustache*.

### API Changes

The enum `ErrorResponse` now has a new case: `DecodeError`, which itself contains an enum describing the error. To accommodate this change, `ErrorResponse.Error` has been renamed `ErrorResponse.HttpError`. I have also incorporated the labels from PR #4502, but I reverted the change from an enum to a struct, since we now have multiple kinds of errors. Has the swift3 generator been released? If yes, then this PR is a minor **breaking change**.

The definitions relevant for end users are:

```swift
public enum ErrorResponse : Error {
    case HttpError(statusCode: Int, data: Data?, error: Error)
    case DecodeError(response: Data?, decodeError: DecodeError)
}

public enum DecodeError {
    case typeMismatch(expected: String, actual: String)
    case missingKey(key: String)
    case parseError(message: String)
}

public enum Decoded<ValueType> {
    case success(ValueType)
    case failure(DecodeError)
}
```

### CODE REVIEW

**Comment by wing328** [comment]
@philippelatulippe thanks for the PR. Test result looks good:
```
** TEST SUCCEEDED **

Test Suite 'All tests' started at 2017-01-13 00:25:03.130
Test Suite 'SwaggerClientTests.xctest' started at 2017-01-13 00:25:03.131
Test Suite 'PetAPITests' started at 2017-01-13 00:25:03.131
Test Case '-[SwaggerClientTests.PetAPITests test1CreatePet]' started.
Test Case '-[SwaggerClientTests.PetAPITests test1CreatePet]' passed (1.195 seconds).
Test Case '-[SwaggerClientTests.PetAPITests test2GetPet]' started.
Test Case '-[SwaggerClientTests.PetAPITests test2GetPet]' passed (1.014 seconds).
Test Case '-[SwaggerClientTests.PetAPITests test3DeletePet]' started.
Test Case '-[SwaggerClientTests.PetAPITests test3DeletePet]' passed (0.776 seconds).
Test Suite 'PetAPITests' passed at 2017-01-13 00:25:06.118.
	 Executed 3 tests, with 0 failures (0 unexpected) in 2.985 (2.987) seconds
Test Suite 'StoreAPITests' started at 2017-01-13 00:25:06.120
Test Case '-[SwaggerClientTests.StoreAPITests test1PlaceOrder]' started.
Test Case '-[SwaggerClientTests.StoreAPITests test1PlaceOrder]' passed (0.934 seconds).
Test Case '-[SwaggerClientTests.StoreAPITests test2GetOrder]' started.
Test Case '-[SwaggerClientTests.StoreAPITests test2GetOrder]' passed (0.752 seconds).
Test Case '-[SwaggerClientTests.StoreAPITests test3DeleteOrder]' started.
Test Case '-[SwaggerClientTests.StoreAPITests test3DeleteOrder]' passed (0.838 seconds).
Test Case '-[SwaggerClientTests.StoreAPITests testDownloadProgress]' started.
Test Case '-[SwaggerClientTests.StoreAPITests testDownloadProgress]' passed (0.670 seconds).
Test Suite 'StoreAPITests' passed at 2017-01-13 00:25:09.317.
	 Executed 4 tests, with 0 failures (0 unexpected) in 3.194 (3.197) seconds
Test Suite 'UserAPITests' started at 2017-01-13 00:25:09.318
Test Case '-[SwaggerClientTests.UserAPITests test1CreateUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test1CreateUser]' passed (0.882 seconds).
Test Case '-[SwaggerClientTests.UserAPITests test2GetUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test2GetUser]' passed (1.118 seconds).
Test Case '-[SwaggerClientTests.UserAPITests test3DeleteUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test3DeleteUser]' passed (1.010 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' passed (0.964 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' passed (0.827 seconds).
Test Suite 'UserAPITests' passed at 2017-01-13 00:25:14.123.
	 Executed 5 tests, with 0 failures (0 unexpected) in 4.800 (4.805) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2017-01-13 00:25:14.123.
	 Executed 12 tests, with 0 failures (0 unexpected) in 10.979 (10.993) seconds
Test Suite 'All tests' passed at 2017-01-13 00:25:14.124.
	 Executed 12 tests, with 0 failures (0 unexpected) in 10.979 (10.994) seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:04 min
[INFO] Finished at: 2017-01-13T00:25:14+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```

**Comment by wing328** [comment]
cc @jaz-ah @Edubits @hexelon @jgavris

**Comment by jgavris** [comment]
👍

**Comment by jaz-ah** [comment]
+1

**Comment by wing328** [comment]
@philippelatulippe thanks for your PR, which has been merged into master.

Thanks @jaz-ah @jgavris for reviewing the change.

**Pull request merged**
