### PR TITLE
Ensure identifiers get sanitized & model names have the same formatting

### PR DESCRIPTION
**Pull request by log0ymxm**
…me formatting

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by log0ymxm** [comment]
I'm not sure why the travis test fails, maybe some upstream issue.

One thing on this PR, I re-ran `bin/akka-scala-petstore.sh` and it reverted `pom.xml` changes found in https://github.com/swagger-api/swagger-codegen/commit/2da2a2631d86cf0555b9cc13c56f5d19b31ef903

@wing328 Can you comment on what that pom.xml change was, and if we need to update the shell script or something else for this.

**Comment by log0ymxm** [comment]
Also there's no coverage for the specific case we saw that required the override for `toModelName`. We have a subclass typing patter where we end up with definitions of the form `Customer.Id`, when the period is in there it generated an invalid case class in scala code, so by running the model name through the format identifier method it cleans that period out.

**Comment by ePaul** [comment]
See #5094 for the pom update issue. (This would also cause a problem in CI, though Travis breaks before that for an unrelated cause.)

**Comment by wing328** [comment]
@log0ymxm thanks for the PR, which looks good to me.

Eventually, we might want to consolidate `scala`, `async-scala` and `akka-scala` into a single Scala API client generator. @clasnake has begun the effort with https://github.com/swagger-api/swagger-codegen/pull/5115. Please review the change when you've time.

**Pull request merged**
