### PR TITLE
Updated to support .net core 3

### PR DESCRIPTION
**Pull request by knom**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

@mandrean - I've added support for .NET Core 3 / Swashbuckle 5.
#9781

### CODE REVIEW

**Comment by frantuma** [comment]
Thanks for this! we will review soon.

**Comment by knom** [comment]
@frantuma any update?

**Comment by knom** [comment]
Hmm.. I really liked the project - and did a few contributions every now and then..
(especially in combination w. https://editor.swagger.io)

But the community has changed, @wing328 is gone it seems..
Not sure how active / alive the codegen still is..

**Comment by HugoMario** [comment]
thanks for your PR @knom, and sorry for this delay. Next time you need help with something in this project. Please, let me know.

**Comment by rdecarreau** [comment]
Was this built into the CLI? I have 3.0.18 CLI and it only builds aspnet2.2.

**Comment by HugoMario** [comment]
@rdecarreau this was written for version 2, but will ported soon to codegen v3

**Comment by phil-warner** [comment]
Hi @HugoMario was this ported to codegen v3 yet? I'll have to drop to version 2 if not.

**Comment by HugoMario** [comment]
@phil-warner 

it was:
https://github.com/swagger-api/swagger-codegen-generators/pull/502

**Pull request merged**
