### PR TITLE
[QT5CPP] General Improvements

### PR DESCRIPTION
**Pull request by stmeyer**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- check C++ Keywords
- setter for SSL configuration

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by stmeyer** [comment]
@wing328 I didn't pass any Email with the commits. Is it required?

**Comment by wing328** [comment]
@stmeyer it's not required for this PR to be merged into master. Just that this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors

**Comment by stmeyer** [comment]
includes a fix for #6319

**Comment by wing328** [comment]
cc @stkrwork

**Comment by stmeyer** [comment]
@stkrwork yes it still compiles and runs :-)

I can use the abstract CPPGenerator but I'm not able to test for example the C++ REST client.

**Comment by stkrwork** [comment]
The change is only important for forbidding specific words. The only way the other c++ clients/servers would break is if they use the reserved words.

**Comment by stmeyer** [comment]
CircleCI tests faile due to errors like
```
[ERROR] COMPILATION ERROR : 
[ERROR] /home/ubuntu/swagger-codegen/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/User.java:[5,30] package io.swagger.annotations does not exist
[ERROR] /home/ubuntu/swagger-codegen/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/User.java:[12,1] package io.swagger.annotations does not exist
[ERROR] /home/ubuntu/swagger-codegen/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/User.java:[17,2] cannot find symbol
  symbol: class ApiModel
[ERROR] /home/ubuntu/swagger-codegen/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Order.java:[5,30] package io.swagger.annotations does not exist
[ERROR] /home/ubuntu/swagger-codegen/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Order.java:[12,1] package io.swagger.annotations does not exist
[ERROR] /home/ubuntu/swagger-codegen/samples/server/petstore/jaxrs-cxf-cdi/src/gen/java/io/swagger/model/Order.java:[17,2] cannot find symbol
  symbol: class ApiModel
```

I do not know how this PR affected this errors. I did not change `jaxrs-cxf-cdi`

/cc @wing328 @stkrwork

**Comment by wing328** [comment]
@stmeyer don't worry about that error. I already fixed it over the weekend.

**Pull request merged**
