### PR TITLE
[TypeScript][Aurelia] Create Aurelia code generator #5987

### PR DESCRIPTION
**Pull request by ksm2**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

I created a code generator for the (Aurelia Framework)[http://aurelia.io]! This resolves issue #5987

### CODE REVIEW

**Comment by wing328** [comment]
@ksm2 thanks for the PR.

cc @Vrolijkx @taxpon @sebastianhaas @kenisteward @TiFu

**Comment by wing328** [comment]
Suggestion: Can you please also create [shell scripts](https://github.com/swagger-api/swagger-codegen/blob/master/bin/typescript-angular2-petstore.sh) and [batch files](https://github.com/swagger-api/swagger-codegen/blob/master/bin/windows/typescript-angular2.bat) similar to typescript-angular2 and include the samples in this PR?

**Comment by TiFu** [comment]
Suggestion: Would it be possible to provide some test  cases for the generated API? 

A test for the API could look similar to the [test](https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-node/npm/client.ts) for typescript-node.  The test is called in [pom.xml](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-node/npm/pom.xml) by executing the test script in the [package.json](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/typescript-node/npm/package.json)

**Comment by wing328** [comment]
@ksm2 thanks for the new generator, which has been merged into master.

I'll create a separate ticket to track enhancements.

**Pull request merged**
