### PR TITLE
Fix date-time params in Java-Play codegen

### LINKED ISSUE #6087: Java Play date-time params don't work
##### Description

A query param with a date-time format will generate the following code, which does not compile:

```java
        String valuestartDate = OffsetDateTime.parse()request().getQueryString("startDate");
        OffsetDateTime startDate;

        startDate = valuestartDate;
```

##### Swagger-codegen version
2.2.3

### PR DESCRIPTION
**Pull request by edrevo**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixes #6087

### CODE REVIEW

**Comment by wing328** [comment]
@edrevo thanks for the PR.

cc @JFCote

**Comment by JFCote** [comment]
@edrevo Thanks for the PR. Looks good to me. 
@wing328 You can merge !

**Comment by JFCote** [comment]
@wing328 Maybe just run the `.sh` before?

**Comment by edrevo** [comment]
I did run the `.sh` but the only change they cause is that they added a @Generated annotation with the current date and that change is unrelated to this PR, so I didn't commit those changes.

**Comment by edrevo** [comment]
@wing328 is there anything else needed in this PR before it gets merged?

**Comment by wing328** [comment]
@edrevo I'll review shortly...

**Comment by wing328** [comment]
Tests (with updated Petstore samples) passed via https://circleci.com/gh/swagger-api/swagger-codegen/1011

**Comment by wing328** [comment]
FYI. Java Play Petstore samples updated via bc68e97 (by running `./bin/java-play-framework-petstore-server-all.sh`)

**Pull request merged**
