### PR TITLE
Updated versions for 2.2.3 release and other minor enhancements

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- updated versions for release 2.2.3
- add header support to qt5 C++
- remove .travis.objc_swift_test.yml as it's no longer needed
- update Java client version in config-help

### CODE REVIEW

**Comment by wing328** [comment]
I'll need to rollback the build image to xcode8.2 as xcode9 does not have the ruby version we've been using.

**Comment by wing328** [comment]
Travis tests passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/253948678?utm_source=github_status&utm_medium=notification

**Comment by fehguy** [comment]
Thanks @wing328.  I have to do one last update to patch a vulnerability in jackson.  Any concerns about the travis PR failing?

**Comment by wing328** [comment]
Duplicated Travis jobs were created: 1 [passed](https://travis-ci.org/swagger-api/swagger-codegen/builds/253948678?utm_source=github_status&utm_medium=notification) while the other failed with the following reason:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project swagger-codegen-project: Failed to deploy artifacts: Could not transfer artifact io.swagger:swagger-codegen-project:pom:2.2.3 from/to sonatype-nexus-staging (https://oss.sonatype.org/service/local/staging/deploy/maven2/): Failed to transfer file: https://oss.sonatype.org/service/local/staging/deploy/maven2/io/swagger/swagger-codegen-project/2.2.3/swagger-codegen-project-2.2.3.pom. Return code is: 401, ReasonPhrase: Unauthorized. -> [Help 1]
```
Looks like it's related to the deployment of the snapshot:
```
  - if [ $SONATYPE_USERNAME ] && [ -z $TRAVIS_TAG ] && [ "$TRAVIS_BRANCH" = "master" ]; then
      mvn clean deploy --settings .travis/settings.xml;
      echo "Finished mvn clean deploy";
    fi;
```
Given another job passed, I wouldn't worry too much and we can dig deeper into the `401 unauthorized` issue later.

**Pull request merged**
