### PR TITLE
[C#][aspnetcore] Improve generated code

### LINKED ISSUE #5252: [C#][aspnetcore] [SwaggerResponse()]:s missing for non HTTP 200 OK responses
##### Description

* The `[SwaggerResponse()]` is set to `200 OK` by default (even if response-code is e.g. `204 No Content`)
* `[SwaggerResponse()]` for `400 Bad Request`, `404 Not Found` etc. aren't even added by the generator

##### Swagger-codegen version

`v2.3.0` or latest `master`, doesn't matter.

##### Swagger declaration file content or url

`sh ./bin/aspnetcore-petstore-server.sh` or your own `Swagger.json`, doesn't matter.

##### Steps to reproduce

0. `git clone https://github.com/swagger-api/swagger-codegen && cd swagger-codegen`
1. `git checkout origin 2.3.0 && git pull origin 2.3.0 --rebase`
2. `mvn clean package`
3. `sh ./bin/aspnetcore-petstore-server.sh`
4. `cd samples/server/petstore/aspnetcore/src/IO.Swagger`
5. `sh build.sh`
6. Check `swagger-codegen/samples/server/petstore/aspnetcore/src/IO.Swagger/Controllers/PetApi.cs`

##### Suggest a Fix

Update `controller.mustache` to loop through all responses and generate a `[SwaggerResponse()]` for each of them.

### PR DESCRIPTION
**Pull request by mandrean**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

* Migrate from `Swashbuckle` to `Swashbuckle.AspNetCore`
* Add `[SwaggerResponse()]` for *all* responses, not just `200 OK`
* Add `[Required]` attribute for required fields in generated models
* Improve whitespace and remove some redundant code
* Fix all compiler warnings
* Add proper model state/input validation
* Regenerate AspNetCore PetStore sample

Fixes #5252, #5253, #5254, #5255 and #5256.

### CODE REVIEW

**Comment by wing328** [comment]
@mandrean thanks for the PR (I've restarted the Travis CI job - the failure was due to network issue when downloading nodejs modules for JS/TS API client tests)

cc @jimschubert

**Comment by mandrean** [comment]
@wing328 The `golang` petstore tests are failing. Not sure why, haven't touched those.

image

image

**Comment by wing328** [comment]
We noticed the intermittent issue with Go API client tests and there're some ongoing works trying to address that.

Milestone updated to `2.3.0`

All CI test results passed after restarting the job.

**Comment by wing328** [comment]
@mandrean the change looks good to me.

FYI. I'll later file a PR to remove the trailing whitespaces in the auto-generated code (by updating the templates)

**Pull request merged**
