### PR TITLE
[java] Improve pom.xml to qualify for publishing to Maven central

### PR DESCRIPTION
**Pull request by cliffano**
I've made the following changes to all Java-related pom.xml templates so the generated pom qualifies for publishing to Maven central:
- add description
- add url
- add developer info (name, email, organization, organization URL)
- parameterise scm info (connection, developer connection, URL)
- generate javadoc
- generate sources
- add GPG signing

This PR was tested (and the petstore generated) using swagger-parser 1.0.24 due to the issue with 1.0.25-SNAPSHOT as described on https://github.com/swagger-api/swagger-codegen/issues/4462 .

However, I didn't change swagger-parser dependency version to 1.0.24 as part of this PR since I didn't know what's the decision with issue 4462.

### CODE REVIEW

**Comment by cliffano** [comment]
@wing328 Travis test failure is related to Clojure petstore and I don't think it has anything to do with my pom template changes. Any idea?

**Comment by wing328** [comment]
@cliffano there's an issue with Clojure Petstore client after updating the code. I think what I'll do is to cherry pick the commits in your PR.

**Comment by cliffano** [comment]
@wing328 Any chance to cherry pick this PR?

**Comment by wing328** [comment]
@cliffano I'll do it over the weekend.

**Comment by wing328** [comment]
@cliffano I've filed https://github.com/swagger-api/swagger-codegen/pull/4616 by cherry-picking some of the commits in this PR and fixing some docstring issues with the Java API clients.

Please take a look and let me know if you spot any issues.

**Comment by cliffano** [comment]
@wing328 LGTM.
Thanks for cherry-picking this.
👍

**Comment by wing328** [comment]
Thanks for reviewing the PR (https://github.com/swagger-api/swagger-codegen/pull/4616), which has been merged into master.

Closing this one.

**Pull request closed without merging**
