### PR TITLE
guzzle http psr7 2.0 compliant

### PR DESCRIPTION
**Pull request by manzolo**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Fix php generator for PHP language so that it's used Query::build class method instead of build_query function

Issue https://github.com/swagger-api/swagger-codegen/issues/11198

### CODE REVIEW

**Comment by manzolo** [comment]
Related to https://github.com/swagger-api/swagger-codegen/pull/11104

**Comment by pajasry** [comment]
Any progress on this?

**Comment by chrillep** [comment]
ping @frantuma

**Comment by chrillep** [comment]
relates to https://github.com/swagger-api/swagger-codegen/pull/11773

**Comment by manzolo** [comment]
Duplicated of #11773

**Pull request closed without merging**
