### PR TITLE
[Feign] Support joda dates in feign client and use it in petstore sample

### PR DESCRIPTION
**Pull request by cbornet**

### CODE REVIEW

**Comment by wing328** [comment]
**Upgrade note from 2.1.6 to 2.2.0**

Starting from 2.2.0, Java Feign API client will use `org.joda.time.LocalDate` (date), `org.joda.time.DateTim` (date-time) instead of `java.util.Date`

**Comment by cbornet** [comment]
@wing328 Actually, java.util.Date is still the default. You have to set dateLibrary=joda to use joda.

**Comment by wing328** [comment]
Ah I miss that. Thanks for pointing it out. Deleted the upgrade note.

**Comment by cbornet** [comment]
My idea is to first add support for joda in all java clients then do the default date lib swap after that.

**Pull request merged**
