### PR TITLE
[Java] Fixed @Deprecated annotations

### PR DESCRIPTION
**Pull request by brian-byungsookim**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
Fixed a previous PR (#6166) by adding the `@Deprecated` annotation to appropriate methods in the jersey2, okhttp-gson, resteasy libraries. 

@bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet

### CODE REVIEW

**Comment by cbornet** [comment]
LGTM

**Comment by wing328** [comment]
@brian-byungsookim thanks for the PR, which has been merged into master.

I also did a case-insensitive grep on other Java generator (e.g. server) and confirmed there's no other references to `@Deprecated`

**Comment by martypitt** [comment]
From what I can tell, this doesn't address deprecated properties within models.  Is that by design?

**Comment by brian-byungsookim** [comment]
Sorry for the late response, but yes, I didn't address deprecated models in this PR.

**Comment by wing328** [comment]
@martypitt may I know if you've time to file a PR to address deprecated properties within models?

**Comment by martypitt** [comment]
Unfortunately no. The underlying problem is that the swagger model jar
doesn't support deprecated property attributes in the current version,
making it a non-starter.

**Pull request merged**
