### PR TITLE
Kotlin client

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Initial implementation of a kotlin client generator. See #5071

There are currently some missing pieces to this, such as enum support (see findPetsByStatus) and correctly handling default response codes (see addPet, returns Unit rather than Pet). This should be a good starting point, at least, for community contributions to further flesh it out.

This generator fully qualifies kotlin and java types to reduce conflicts with swagger defined models.

I'll be going on vacation later this week, so I may not be able to revisit the enum generation and default responses for a couple weeks.

\cc @wing328 @michalharakal

### CODE REVIEW

**Comment by jimschubert** [comment]
reference prototype project: https://github.com/jimschubert/kotlin-petstore-example/

**Comment by jimschubert** [comment]
An example test suite:

```
package io.swagger.petstore.functional

import io.kotlintest.matchers.shouldBe
import io.kotlintest.matchers.should
import io.kotlintest.matchers.beGreaterThan
import io.kotlintest.specs.ShouldSpec
import io.swagger.client.apis.PetApi
import io.swagger.client.models.Category
import io.swagger.client.models.Pet
import io.swagger.client.models.Tag

class EvaluateTest : ShouldSpec() {
    init {
        should("query against pet statuses") {
            val api = PetApi()
            val results = api.findPetsByStatus(arrayOf("available", "pending"))

            results.size should beGreaterThan(1)
        }

// TODO: Handle default (200) response
/*
        should("post data (new pet)") {
            val api = PetApi()
            val pet = Pet(
                    id = 0,
                    name = "kotlin client test",
                    category = Category(0, "string"),
                    tags = listOf(Tag(0, "string"))
            )
            val result = api.addPet(pet)

            result.name shouldBe(pet.name)
            result.category shouldBe(pet.category)
            result.tags shouldBe(pet.tags)
        }
*/
    }
}
```

The `query against pet statuses` test fails because the generator generates `Pet` as:

```
data class Pet (
  val id: kotlin.Long?,
  val category: Category?,
  val name: kotlin.String,
  val photoUrls: kotlin.Array<kotlin.String>,
  val tags: kotlin.Array<Tag>?,
  /* pet status in the store */
  val status: kotlin.String?
)
```

Where `name` and `photoUrls` are the required properties defined in `petstore.yaml`. However, when querying `findPetsByStatus`, Pets exist in the array without a `name` property. I haven't dug into why this is, or any settings available in moshi to loosen this behavior. The test fails, and I believe that's to be expected with the given data.

**Comment by wing328** [comment]
> There are currently some missing pieces to this, such as enum support (see findPetsByStatus) and correctly handling default response codes (see addPet, returns Unit rather than Pet). This should be a good starting point, at least, for community contributions to further flesh it out.

Yeah. Definitely a very good starting point.

> I'll be going on vacation later this week, so I may not be able to revisit the enum generation and default responses for a couple weeks.

Enjoy your vacation 👍 

And thanks for the "new.sh" to make it much easier in creating new generators 👏

**Comment by cbornet** [comment]
:clap: now we definitely need the retrofit library !

**Comment by jimschubert** [comment]
I tried to structure ApiClient to be agnostic of the underlying libraries. Hopefully this makes it easier to include retrofit. I tried to make it as small of a library as possible for the base generator.

**Pull request merged**
