### PR TITLE
Make optional properties in models optional parameters

### PR DESCRIPTION
**Pull request by bvwells**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny

### Description of the PR

Make optional properties in models optional parameters in generated typescript-node client. Addresses issue #7791.

### CODE REVIEW

**Comment by bvwells** [comment]
Thanks for the review.

**Comment by bvwells** [comment]
Hi @wing328, I've been having some issues with the circleci builds. I think there might be some random failures occurring. Are you able to do a clean build for me please?

**Comment by wing328** [comment]
The commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by bvwells** [comment]
@wing328 thanks for pointing this out. I'll fix up the author in my PR.

**Pull request closed without merging**
