### PR TITLE
Adding a new Scala client codegen

### PR DESCRIPTION
**Pull request by tbrown1979**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
This pull request adds a new Scala code generator. The new generator uses a few different libraries than the other Scala codegens. These libraries enable the generation to automatically derive serializers/deserializers for the generated `case class`es.  

This codegen generates two different kinds of clients. One of them is a normal client where you provide a host and it will make an http request to it. The other is http4s specific and allows us to test our `HttpService` without actually standing up an http service. People may not find the latter useful (especially if they do not use http4s) and so I have provided both.

Libraries used: [scalaz](https://github.com/scalaz/scalaz), [http4s](https://github.com/http4s/http4s), [argonaut](https://github.com/argonaut-io/argonaut)

If this pull request is missing anything please let me know! Any and all critiques are welcome. Thanks!

@clasnake if you get the chance to look through this that would be appreciated.

### CODE REVIEW

**Comment by clasnake** [comment]
@tbrown1979 Thank you very much for the PR. I'll take a look after it passes all the CI jobs.

**Comment by tbrown1979** [comment]
It appears I left in a few wrongly generated files. I removed those so hopefully this next build will pass!

**Comment by wing328** [comment]
@tbrown1979 when you've time, I wonder if you can add some integration tests for Petstore server by reusing https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/scala/src/test/scala

**Comment by tbrown1979** [comment]
@wing328 I definitely can! It might take me a few days to get around to adding those. I'll post a comment when I've completed them.

**Comment by wing328** [comment]
@tbrown1979 I've merged this PR into master so that the community can try it out and provide feedbacks to make it better. Thanks for the new generator.

(I'll add the word "beta" to the help text)

**Comment by wing328** [comment]
UPDATE:
- added @tbrown1979 as the template creator for `scalaz`
- created enhancement list: https://github.com/swagger-api/swagger-codegen/issues/6701
- added "beta" to help text: 5c14f90

@tbrown1979 please review the enhancement list when you've time.

cc @clasnake

**Comment by wing328** [comment]
Tweet to promote the new generator: https://twitter.com/wing328/status/920238132385030144

**Pull request merged**
