### PR TITLE
Docker build script and Dockerfile

### PR DESCRIPTION
**Pull request by moander**
The run-in-docker.sh script is not related to the Dockerfile.

### CODE REVIEW

**Comment by olensmar** [comment]
Thanks for this! Out of curiosity; why would one use this instead of just running "directly"? Because you wouldn't have to install java/maven?

**Comment by moander** [comment]
Yes. My motivation was a cross-platform "one-liner" to get it up and running :)

**Comment by olensmar** [comment]
ok cool - thanks for clarifying :-)

**Comment by wing328** [comment]
@moander thanks for the PR. I followed the instruction in the README but got the following error:
```
swagger-codegen|feature/docker ⇒ docker version
Client version: 1.7.0
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 0baf609
OS/Arch (client): darwin/amd64
Server version: 1.7.0
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 0baf609
OS/Arch (server): linux/amd64
swagger-codegen|feature/docker ⇒ pwd
/var/tmp/moander/swagger-codegen
swagger-codegen|feature/docker ⇒ ./run-in-docker.sh mvn package
+ docker run -it -w /gen -v /var/tmp/moander/swagger-codegen:/gen -v /Users/williamcheng/.m2/repository:/root/.m2/repository maven:3-jdk-7 mvn package
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.118 s
[INFO] Finished at: 2015-07-23T01:33:33+00:00
[INFO] Final Memory: 5M/58M
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/gen). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
```
From the error message, it looks like it's looking for pom.xml in the directory `gen` but couldn't find it.

Have you seen similar error before ?

**Comment by moander** [comment]
Are you running boot2docker locally, or do you use a remote docker machine?

Please post the output of this command:
```
docker run -it -w /gen -v /var/tmp/moander/swagger-codegen:/gen -v /Users/williamcheng/.m2/repository:/root/.m2/repository maven:3-jdk-7 ls -la
```

You can also try this command to get a shell inside the docker to do some more investigation:
```
docker run -it -w /gen -v /var/tmp/moander/swagger-codegen:/gen -v /Users/williamcheng/.m2/repository:/root/.m2/repository maven:3-jdk-7 bash
```

**Comment by wing328** [comment]
@moander here is the output of running the command you provided:
```
bash-3.2$ ls
Dockerfile		bin			run-in-docker.sh
LICENSE			modules			samples
README.md		pom.xml
bash-3.2$ git branch
  develop_2.0
* feature/docker
bash-3.2$ docker run -it -w /gen -v /var/tmp/moander/swagger-codegen:/gen -v /Users/williamcheng/.m2/repository:/root/.m2/repository maven:3-jdk-7 ls -la
total 8
drwxr-xr-x  2 root root 4096 Jul 23 01:25 .
drwxr-xr-x 50 root root 4096 Jul 24 13:53 ..
```
In the shell, I don't see files/directories:
```
root@fa10678f5448:/gen# ls -al
total 8
drwxr-xr-x  2 root root 4096 Jul 23 01:25 .
drwxr-xr-x 50 root root 4096 Jul 24 13:54 ..
```
Am I doing anything wrong with docker ?

**Comment by moander** [comment]
I don't think you are doing anything wrong, but I suspect that you are using a remote docker machine. The volume mounts (-v) are only working when using boot2docker or when running directly on a linux machine.

Check if DOCKER_HOST points to a IP on your local machine:
```
$ env | grep DOCKER
```

You can also check the status of boot2docker:
```
$ boot2docker status
```

**Comment by wing328** [comment]
I'm using boot2docker on Mac and here is the output of the commands:
```
bash-3.2$ env | grep DOCKER
DOCKER_HOST=tcp://192.168.59.103:2376
DOCKER_TLS_VERIFY=1
DOCKER_CERT_PATH=/Users/williamcheng/.boot2docker/certs/boot2docker-vm
bash-3.2$ boot2docker status
running
bash-3.2$ ./run-in-docker.sh 
+ docker run -it -w /gen -v /var/tmp/moander/swagger-codegen:/gen -v /Users/williamcheng/.m2/repository:/root/.m2/repository maven:3-jdk-7 java -jar /gen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
Error: Unable to access jarfile /gen/modules/swagger-codegen-cli/target/swagger-codegen-cli.jar
bash-3.2$ 
```

**Comment by moander** [comment]
Strange.. The "unable to access jarfile" message is expected because it's not yet been built, but the DOCKER_HOST seems to be local so why the volume mount don't work is a mystery for me.

I have successfully tested the same commands on 3 different mac's using docker v1.7.1. Is it something special about your /var/tmp folder? Can you post the output of `$ df`?

Is this command working btw?
```
$ docker run -it -v $HOME:/gen maven:3-jdk-7 ls -la /gen
```

**Comment by wing328** [comment]
I didn't do anything special to my /var/tmp folder and here is the output of `df`:
```
tmp|⇒ df -h
Filesystem      Size   Used  Avail Capacity  iused   ifree %iused  Mounted on
/dev/disk1     233Gi  215Gi   17Gi    93% 56546633 4432181   93%   /
devfs          188Ki  188Ki    0Bi   100%      650       0  100%   /dev
map -hosts       0Bi    0Bi    0Bi   100%        0       0  100%   /net
map auto_home    0Bi    0Bi    0Bi   100%        0       0  100%   /home
```
and the command `docker run -it -v $HOME:/gen maven:3-jdk-7 ls -la /gen` is working - listing out files and directories.

I'll ask my friends to try as well to see if it's machine-specified issue. will keep you posted.

**Comment by moander** [comment]
@wing328  Then volume mounts are working inside your $HOME. Could you try running these commands? :)

```
git clone -b feature/docker https://github.com/moander/swagger-codegen $HOME/testing-swagger-codegen

cd $HOME/testing-swagger-codegen

./run-in-docker.sh mvn package
```

**Comment by wing328** [comment]
@moander thanks. that works for me
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  4.299 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [01:11 min]
[INFO] swagger-codegen (executable) ....................... SUCCESS [ 14.887 s]
[INFO] swagger-codegen (maven-plugin) ..................... SUCCESS [ 24.201 s]
[INFO] swagger-generator .................................. SUCCESS [ 55.562 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:52 min
[INFO] Finished at: 2015-07-29T01:20:19+00:00
[INFO] Final Memory: 38M/294M
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
