### PR TITLE
Fixes for issue 4226. Detects and warns about more than one inline ob…

### PR DESCRIPTION
**Pull request by jeff9finger**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

…ject; sets discriminator on CodegenModel; Adds templates to other Java languages

Changes to be committed:
	modified:   modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java
	modified:   modules/swagger-codegen/src/main/resources/Java/typeInfoAnnotation.mustache
	new file:   modules/swagger-codegen/src/main/resources/JavaInflector/typeInfoAnnotation.mustache
	new file:   modules/swagger-codegen/src/main/resources/JavaJaxRS/typeInfoAnnotation.mustache
	new file:   modules/swagger-codegen/src/main/resources/JavaSpring/typeInfoAnnotation.mustache

### CODE REVIEW

**Comment by jeff9finger** [comment]
Link [Issue 4226](https://github.com/swagger-api/swagger-codegen/pull/4251)

**Comment by wing328** [comment]
@jeff9finger I'll review by this week and let you know if I've any question.

**Comment by wing328** [comment]
@jeff9finger is this PR still required? I believe we've merged another PR from you, which should cover the changes in this PR.

**Comment by jeff9finger** [comment]
@wing328 This pr is not required. The changes from this PR were merged in another pr (as you said)

Thanks

**Pull request closed without merging**
