### PR TITLE
Swift4: Add additional initializer for initializing model object with properties.

### PR DESCRIPTION
**Pull request by ehyche**
### Description of the PR

This change fixes this issue: https://github.com/swagger-api/swagger-codegen/issues/6641

It adds an additional initializer which allows model objects to be initialized using the properties. For example, if we had this model:

```
        "ErrorInfo": {
          "type": "object",
          "properties": {
            "code": {
              "type": "integer",
              "format": "int32"
            },
            "message": {
              "type": "string"
            },
            "details": {
              "type": "array",
              "items": {
                "type": "string"
              }
            }
          },
          "description": "Example Error object"
        },
```
    
With this change, we generate an initializer for this model object like this:
    
```
        public init(code: Int?, message: String?, details: [String]?) {
            self.code = code
            self.message = message
            self.details = details
        }
```

### PR checklist

- [ x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### CODE REVIEW

**Comment by jaz-ah** [comment]
@ehyche is it worth adding an additional check if we have additionalProperties so we don't generate empty init() { } functions?

**Comment by ehyche** [comment]
@jaz-ah : good suggestion. Will add that check.

**Comment by ehyche** [comment]
@jaz-ah : updated to add hasVars checks around the initializer per your suggestion.

I had also forgotten to run the scripts, so I re-ran these scripts:

- bin/swift4-petstore-all.sh
- bin/swift4-petstore-objcCompatible.sh
- bin/swift4-test.sh

**Comment by jaz-ah** [comment]
+1 looks good thx @ehyche - @wing328 ready to merge

**Comment by wing328** [comment]
@jaz-ah thanks for reviewing the change.

@ehyche thanks for the enhancement

cc @jgavris @Edubits

**Comment by jgavris** [comment]
Nice! I might have mentioned this before, it's too bad we couldn't have made these `struct`'s and gotten convenience initializers auto-generated since the `Codable` protocol requires an initializer.

**Comment by ehyche** [comment]
@jgavris : that's a really good idea to make them struct's. Then we get value semantics and immutability for free. I've been thinking about that, and will look into it.

**Pull request merged**
