### PR TITLE
Issue 5431 Support jaxrs client api interfaces

### PR DESCRIPTION
**Pull request by jarlesat**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

* Added jaxrs client as interfaces as a new language "jaxrs-interface". The model is still created as pojos. It is implemented by extending JavaJAXRSSpecServerCodegen and override api.mustache with apiInterface.mustache.
* Creation of pom.xml is made optional with a cliOption "createPom", defaulting to false.
* Added shell script to create sample-files.

### CODE REVIEW

**Comment by wing328** [comment]
@jarlesat thanks for the PR. I wonder if you can also add an auto-generated pom.xml so that developers can build the library more easily.

cc @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov

**Comment by jarlesat** [comment]
I added an option "createPom" that defaults to false, as that suited our use case best (we use swagger-codegen to generate the java source for the interfaces on every build). If this option is true a pom.xml will be generated. Maybe the default should be changed to true?

I also see that the generated pom.xml should be altered slightly, to generate a jar instead of a war :-)

**Comment by jarlesat** [comment]
Close and reopen to trigger new build.

**Comment by wing328** [comment]
@jarlesat thanks for the PR. Can this be merged into `jaxrs-spec` generator via CLI option instead of creating a separate generator?

**Comment by jarlesat** [comment]
@wing328 Sure. Is _interfaceOnly_ a nice cli-option?

**Comment by wing328** [comment]
@jarlesat Yup, spring generator also has this option:
```
	interfaceOnly
	    Whether to generate only API interface stubs without the server files. (Default: false)
```

**Comment by jarlesat** [comment]
@wing328 Should I rebase on a recent master (followed by a forced push), or merge master into issue-5431? Or something else?

**Comment by wing328** [comment]
> Should I rebase on a recent master (followed by a forced push)

That's what I usually do.

**Comment by jarlesat** [comment]
Summary of changes from master: The language jaxrs-spec has to command line arguments (cli):
* generatePom (default true)
* interfaceOnly (default false)

generatePom defaults true to stay compatible with earlier versions.

If interfaceOnly is true, only transfer object classes and interfaces are generated. The RestApplication.java is skipped. The optionally generated pom.xml is altered to reflect that only interfaces are created (package type is set to jar instead of war, plugin is jar-plugin instead of war-plugin for instance).

Hence interfaceOnly behaves slightly different from what was commited in #6398: 
* The methods does not return Response, but the proper type.
* The horrible _throws Exception_ anti-pattern has been removed.

**Comment by wing328** [comment]
@jarlesat I ran some tests and the result is good. Thanks for your contribution.

**Pull request merged**
