### PR TITLE
[Java][Spring][Server] Issue #4680 and objectMapper issue

### PR DESCRIPTION
**Pull request by MZinchenko**
### PR checklist
- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
Changes in Java Spring only:
* Issue #4680 fixed in proper way
* In controllers objectMapper must not exists for delegate=true config

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by MZinchenko** [comment]
Thank you very much. I'm very new at hithub :)
My git client app set incorrect field "Author" and "email".
But I think no reason to patch commits.
I setup this email for my account toom that's no problem.

P.S. can you say, why travis-ci is falling on my PR?

2017-10-19 16:21 GMT+03:00 wing328 <notifications@github.com>:

**Comment by wing328** [comment]
@cbornet do we still need this PR? I think your recent PR may have fixed it.

**Comment by cbornet** [comment]
I think https://github.com/swagger-api/swagger-codegen/pull/6732/commits/fb18b3b3ba161d1c49fb0ab523cb2fd02c6378ea is still relevant but https://github.com/swagger-api/swagger-codegen/pull/6732/commits/35c255a6f86e795c94282fc9c899ecae6129a8e7 is not needed anymore

**Comment by wing328** [comment]
@MZinchenko do you mind submitting another PR with just fb18b3b?

You may find `git cherry-pick` useful to do that.

**Comment by MZinchenko** [comment]
Ok, that's done: https://github.com/swagger-api/swagger-codegen/pull/6890

I don't ran shell scripts for update PetStore.
I can do it, if necessary.

2017-11-05 10:43 GMT+03:00 wing328 <notifications@github.com>:

**Comment by wing328** [comment]
Closed via 6890

**Pull request closed without merging**
