### PR TITLE
Typescript angular linting fixes

### PR DESCRIPTION
**Pull request by gupbeheer**
Technical committee: @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

When I added the generated Typescript Angular code to my project, my 'tslint' did not like the generated code. I updated the code to make my 'tslint' happy. This PR is to share my changes with the community.

### CODE REVIEW

**Comment by kenisteward** [comment]
Your winter might break others due  to the nature of linting I do not
suggest this pe be merged .  Just lint iit in your own project

**Comment by kenisteward** [comment]
What o truly suggest is not putting the code into you project but building
it and serving it as a bundle .  The code is generated and shouldn't really
be changed by hand.

**Comment by kenisteward** [comment]
Another suggestion would be to use the exclude option for tslint to ignore
the generated code. https://palantir.github.io/tslint/usage/configuration/

**Comment by wing328** [comment]
So I think what @kenisteward suggested is to use customized templates to meet different linting requirement and use the `-t` option when generating the code.

**Comment by kenisteward** [comment]
@wing328 that is definitely one way of going about it. I honestly forgot about that! haha.  I was trying to give a solution without them having to learn the inner workings of mustache stuff.

@gupbeheer while your changes meet your (and mostly my) ts lint restrictions there are some of them that are preferential and definitely may not (e.g. forcing single quotes instead of double is based on preference not necessity)

You could definitely create your own templates that fit your coding style but to be honest linting mostly covers keeping code made by developers under check to make sure we write similar code (in my opinion).  Since this is generated, you can just ignore linting rules on this folder as  you (should) never be working directly on this code.

**Comment by sebastianhaas** [comment]
I go with @kenisteward here, I would recommend not putting the auto-generated sources in your project but rather include it per npm and use it as a dependency.

**Comment by gupbeheer** [comment]
No problem. I saw the code I committed in #6751 and the linting errors that came up in the files I committed were 90% my new code. So I made it more 'as the other code' and made the linting pass. I thought I should contribute this. That is the reason for this PR. 
In our own codebase we exempt the generated code from linting and we generate service clients and push them to our NPM registry by using the Typescript specific properties:  `--additional-properties npmName="",npmVersion="",npmRepository=""`

**Comment by kenisteward** [comment]
@gupbeheer great to hear!  If you could close this issue then that'd be great :)

**Pull request closed without merging**
