### PR TITLE
Replaced auto-generated equals/hashCode with apache commons builder

### PR DESCRIPTION
**Pull request by heinrichj**
+ Replaces auto-generated methods for equals and hashCode with builders from apache.commons

### CODE REVIEW

**Comment by wing328** [comment]
@heinrichj thanks for the PR. Would there be performance concern? 

Ref: http://stackoverflow.com/a/11036608/677735

**Comment by heinrichj** [comment]
Hi wing328,

thank you for reviewing my PR.
I took a look at the stackoverflow post and made a very little and simple test. Yes it is slower, as expected. But in my opinion it is not very critical.
There is a trade-off. The commons implementation is less code and the avantage is that it is save against changes. If new fields are introduced these will be taking into consideration. You don't have to regenerate the methods, so you cannot forget to do so as well.

**Comment by fehguy** [comment]
this really doesn't make sense to merge.  The whole idea of auto-generated code is that it will be faster and dependency free.  Why clog it up with a utility to do something that the codegen has done already?

Will leave this to @wing328 but I think this is a bad idea to bring into everyone's projects.

**Comment by wing328** [comment]
@fehguy I also prefer our current approach as it's better in terms of performance.

@heinrichj you can update the mustache template locally and pass the customized templates via the `-t` option.

If there are more demands, we'll make this an option so that developers will have a choice on which one they prefer when generating the code.

**Comment by wing328** [comment]
I've opened #3580 for tracking. Closing this for the time being.

Will reopen if there's a demand from the community.

**Pull request closed without merging**
