### PR TITLE
[Python][Flask] add optional argument to flask controller

### PR DESCRIPTION
**Pull request by wing328**
For https://github.com/swagger-api/swagger-codegen/issues/2576

### CODE REVIEW

**Comment by tommyjcarpenter** [comment]
@wing328 is this a self-merge? Does this project have a formal PR process?

**Comment by wing328** [comment]
No. I manually merged it and here is the contribution guideline: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
@tommyjcarpenter if you find issue with this PR or other ways to do it better, please let me know.

**Comment by tommyjcarpenter** [comment]
@wing328 it's just the first time I've seen anyone merge their own PR. PR stands for peer review.

**Comment by tommyjcarpenter** [comment]
thanks for the fix! any ideas as to when .io will update to pull this in?

**Comment by wing328** [comment]
Well I can do it directly in master but I prefer using a PR so that we've something for tracking (and easily searchable in Github)

About when editor.swagger.io will pick up the change. I don't have an answer on that.

Does our current workflow depend on editor.swagger.io to generate the Flask server stub?

**Pull request merged**
