### PR TITLE
GO Plain string body type can not be set in generated API

### LINKED ISSUE #7751: Golang Generated api client does not work for plain text body types
##### Description
The Generated API Client for GoLang does not work properly for plain string body types.

The error message is: `Invalid body type text/plain`
 
##### Swagger-codegen version

 2.3.1

##### Swagger declaration file content or url

```yaml
/Token/:
    post:
      operationId: Token
      consumes:
        - text/plain
      responses:
        '200':
          description: OK
          schema:
           type: string
        '400':
          description: Bad Request
          schema:
            type: string
      produces:
        - "application/json"
        - "text/json"
      parameters:
        - in: body
          name: body
          description: The Grand Type
          schema:
            type: string
```
##### Steps to reproduce

Api_client.go

```go
func setBody(body interface{}, contentType string) (bodyBuf *bytes.Buffer, err error) {
	if bodyBuf == nil {
		bodyBuf = &bytes.Buffer{}
	}

	if reader, ok := body.(io.Reader); ok {
		_, err = bodyBuf.ReadFrom(reader)
	} else if b, ok := body.([]byte); ok {
		_, err = bodyBuf.Write(b)
	} else if s, ok := body.(string); ok {  // <<--
		_, err = bodyBuf.WriteString(s)
	} else if jsonCheck.MatchString(contentType) {
		err = json.NewEncoder(bodyBuf).Encode(body)
	} else if xmlCheck.MatchString(contentType) {
		xml.NewEncoder(bodyBuf).Encode(body)
	}

	if err != nil {
		return nil, err
	}

	if bodyBuf.Len() == 0 {
		err = fmt.Errorf("Invalid body type %s\n", contentType)
		return nil, err
	}
	return bodyBuf, nil
}
```

##### Suggest a fix/enhancement

The check should be changed from `body.(string); ok 
The body is an interface containing the pointer to the string.
```
	} else if s, ok := body.(*string); ok {
		_, err = bodyBuf.WriteString(*s)
```

### PR DESCRIPTION
**Pull request by Vad1mo**
fixes #7751

Can you review
@antihax  @bvwells

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by antihax** [comment]
Looks good.

I did a quick look. The problem was here in the generated code:
```
	// body params
	if localVarTempParam, localVarOk := localVarOptionals["body"].(string); localVarOk {
		localVarPostBody = &localVarTempParam
	}
...
	r, err := a.client.prepareRequest(ctx, localVarPath, localVarHttpMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFileName, localVarFileBytes)
	if err != nil {
		return successPayload, nil, err
	}
```
So set body should be expecting a string pointer and not a string.

Ran the tests also and did not find any issues.

**Comment by jmini** [comment]
If you update something in the `mustache` templates, it should be reflected in the generated `samples`, shouldn't it?

Here:
https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/go

You can use the scripts:

* `bin/go-petstore.sh`
* `bin/go-petstore-server.sh`
*  ...

Or is it something that can't be seen in the examples?

**Comment by antihax** [comment]
A test case would need to be added to the fake endpoint yaml.

**Comment by HugoMario** [comment]
covered by #7987

**Pull request closed without merging**
