### PR TITLE
Issue: #3483 - fixed objects defined as extension of primitives - brute force

### PR DESCRIPTION
**Pull request by joevalerio**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by joevalerio** [comment]
brute forced the change only in java after codegenModel is created, I was not sure if the base model should be updated, as that affects all other languages.  But atleast this gives you an idea into what needs to change.

**Comment by joevalerio** [comment]
Why would changes to the abstractJavaCodeGen affect C-Sharp Code?

**Comment by wing328** [comment]
@joevalerio please ignore that or rebase on the latest master, which has the issue fixed.

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@joevalerio can you please also elaborate a bit more on what issue you're trying to fix? Can you share a spec so that we can more easily reproduce the issue?

**Comment by joevalerio** [comment]
Sorry, thought I linked this to issue [#3483](https://github.com/swagger-api/swagger-codegen/issues/3483). In a swagger I am processing a definition defined like this:

  LanguageCode:
    description: 'ISO 639-1 language code'
    type: string
    minLength: 2
    maxLength: 2
    example: 'fi'

For java this should create fields of type String with validation to only allows 2 characters.  I am balking on the validation with this PR, but the defect I reference refers to this creating an object with no accessor.  That part was fixed, however all the references to that object still exist.  This is an issue for definitions that extends any primitive type.  So I just change the codegen model to correctly generate the right code for all java codegen targets.  I was not sure how this effects other languages, so i did not want to do this work in the base swagger model, or the base translation to the codegen model.

FWIW, don't care about credit, just want it to work.

**Comment by joevalerio** [comment]
This was fixed in 2.2.3...

**Comment by joevalerio** [comment]
ok, been using 2.2.3, and now can get what I want.  If you use spring, the order of the definitions seem to matter for the original issue.  I am using java with library: feign to get what I want.

**Pull request closed without merging**
