### PR TITLE
sanitize specification url, so it works for all types of OS. Fix for Wind…

### PR DESCRIPTION
**Pull request by SlavchoArsovski**
### PR checklist

- [ DONE] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ DONE] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [DONE ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ DONE] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix for:
File path for the specification was not sanitized and failing for Windows.

- https://github.com/swagger-api/swagger-codegen/issues/10844 
- https://github.com/swagger-api/swagger-codegen/issues/10823

### CODE REVIEW

**Comment by SlavchoArsovski** [comment]
@HugoMario could you review? this is fix for the blocker issues: 
#10844
#10823

**Comment by HugoMario** [comment]
thanks @SlavchoArsovski ,

Going to check (and merge) this after next release.

**Comment by SlavchoArsovski** [comment]
@HugoMario, don't you think that would be too much time to wait for a urgent fix?

**Comment by SlavchoArsovski** [comment]
@HugoMario is there a chance to merge it, sry for being persistent but the branch is opened more than a month :)

**Comment by HugoMario** [comment]
Hi @SlavchoArsovski sorry for delay

Yea, this PR LGTM but i need to test your changes first make sure it works in differents OS as the title suggest. Just a doubt, why to create a one line method to this, instead just to call the string method directly?

**Comment by SlavchoArsovski** [comment]
> Hi @SlavchoArsovski sorry for delay
> 
> Yea, this PR LGTM but i need to test your changes first make sure it works in differents OS as the title suggest. Just a doubt, why to create a one line method to this, instead just to call the string method directly?

From my side, it was tested on Windows 10 and Macintosh V10.15.7. Feel free to test it.
I have created a new line method as the expression is now used on two places.

**Pull request merged**
