### PR TITLE
Mark `not required` swagger properties as optional typescript properties

### PR DESCRIPTION
**Pull request by bjarnij**
Properties that aren't required in the swagger contract should be marked as optional TypeScript properties, i.e. with `?` after their name when they are defined.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This change marks swagger properties that aren't required as optional properties in the generated TypeScript classes. 
For information about optional properties: https://www.typescriptlang.org/docs/handbook/interfaces.html

@TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx @macjohnny

### CODE REVIEW

**Comment by kenisteward** [comment]
What version of the codegen are you using? It already does this

**Comment by kenisteward** [comment]
NVM just notice this was for typescript-angular

**Comment by kenisteward** [comment]
I meant for typescript-node phone keeps auto correcting....

**Comment by bjarnij** [comment]
Yes, I did.
There were at lot of `?` additions in the generated files.

```
diff before/api.ts after/api.ts
143,145c143,145
<     'code': number;
<     'type': string;
<     'message': string;
---
>     'code'?: number;
>     'type'?: string;
>     'message'?: string;
175,176c175,176
<     'id': number;
<     'name': string;
---
>     'id'?: number;
>     'name'?: string;
201,204c201,204
<     'id': number;
<     'petId': number;
<     'quantity': number;
<     'shipDate': Date;
---
>     'id'?: number;
>     'petId'?: number;
>     'quantity'?: number;
>     'shipDate'?: Date;
208,209c208,209
<     'status': Order.StatusEnum;
<     'complete': boolean;
---
>     'status'?: Order.StatusEnum;
>     'complete'?: boolean;
261,262c261,262
<     'id': number;
<     'category': Category;
---
>     'id'?: number;
>     'category'?: Category;
265c265
<     'tags': Array<Tag>;
---
>     'tags'?: Array<Tag>;
269c269
<     'status': Pet.StatusEnum;
---
>     'status'?: Pet.StatusEnum;
321,322c321,322
<     'id': number;
<     'name': string;
---
>     'id'?: number;
>     'name'?: string;
347,353c347,353
<     'id': number;
<     'username': string;
<     'firstName': string;
<     'lastName': string;
<     'email': string;
<     'password': string;
<     'phone': string;
---
>     'id'?: number;
>     'username'?: string;
>     'firstName'?: string;
>     'lastName'?: string;
>     'email'?: string;
>     'password'?: string;
>     'phone'?: string;
357c357
<     'userStatus': number;
---
>     'userStatus'?: number;
```

**Comment by macjohnny** [comment]
@bjarnij please commit the generated petstore sample files, too. It is not unusual that the `?` was added in many places, since most of the properties in the petstore example are not required.

**Comment by bjarnij** [comment]
@macjohnny I've added the generated files

**Pull request merged**
