### PR TITLE
CSharp: add support for DateTimeOffset and sourceFolder configuration…

### PR DESCRIPTION
**Pull request by jhancock93**
… options

Adds an option to csharp generator to use DateTimeOffset to model date-time fields (instead of DateTime) to allow preservation of timezone information. Modifies ApiClient.ParameterToString to support DateTimeOffset. Also adds sourceFolder option to csharp generator to control filepaths.

### CODE REVIEW

**Comment by wing328** [comment]
@jhancock93 the change looks good (except minor code formatting issue that I'll later submit a PR to adjust). I'll merge the change later today.

**Comment by wing328** [comment]
@jhancock93 please rebase on the latest master to resolve the issue with Travis CI.

**Comment by jhancock93** [comment]
@wing328, Rebased against master and changed tabs to spaces to match whitespace used elsewhere.

**Comment by wing328** [comment]
@jhancock93 my guess is that you didn't do the rebase correctly.

**Comment by wing328** [comment]
One way to resolve this is to checkout master and then pull the latest from "upstream" (swagger-api/swagger-codegen), then create a new branch and cherry-pick the 3 commits in this PR.

**Comment by jhancock93** [comment]
OK, I'll try the cherry-pick method tonight. I assume that if I submit as new branch I will have to submit as a new pull request? Should I close this one then?

**Comment by jhancock93** [comment]
Created a pull request with a new branch to avoid the rebase issue. Closing this pull request as a result.

**Pull request closed without merging**
