### PR TITLE
[Scala] Fix inconsistency between *Api and *ApiAsyncHelper default parameters

### LINKED ISSUE #7273: [Scala] Inconsistency between *Api and *ApiAsyncHelper default parameters
##### Description

In #6538, we defaulted non-required Option parameters to `None` for both sync and async methods in the *Api classes. However, the helper methods in *ApiAsyncHelper (which the methods in *Api simply wrap) default to `defaultValue` which is inconsistent and also error prone (will open a separate issue for this, but see https://github.com/swagger-api/swagger-codegen/pull/6538#discussion_r140950422 for context /cc @wing328).

##### Swagger-codegen version

2.3.0

### PR DESCRIPTION
**Pull request by gmarz**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language. (/cc @clasnake @jimschubert)

### Description of the PR

Closes #7273

### CODE REVIEW

**Comment by gmarz** [comment]
> Unless I'm reading this incorrectly, the change removes support for default values for types that are optionally required and have a default defined.

That's correct. However, I believe there are > 1 issues with defaulting to `defaultValue` at the moment (in addition to https://github.com/swagger-api/swagger-codegen/pull/6538#discussion_r140950422, I also think `defaultValue = "someString"` ends up as `Some(someString)` which is also wrong...but I need to test that again to confirm).

More importantly, the `*Api` methods at the moment default to `None` so this change at least makes `*ApiAsyncHelper` consistent with that behavior until we fix the default values.

**Comment by jimschubert** [comment]
@gmarz please see my pr #7286, where I added integration tests referring to this PR and changing from the `None` default change from the other linked PR back to supporting default values.

I don't understand your comment that a spec defining `defaultValue = "some string"` resulting in the generated code ending up at `Some(some string)` is wrong. Are you saying that the string isn't quoted? If so, that's an easy enough fix, and I can make the change with an appropriate test modification in PR #7286.  I think string is the only primitive value that would have this issue in Scala (if it's not be properly quoting).

Sorry, I meant to tag you in that other pr as it directly relates to and partially conflicts with this pr.

**Comment by gmarz** [comment]
> Are you saying that the string isn't quoted? 

Yep, sorry for not being clear. This is what I observed during my testing of 2.3.0, but would be great if you could confirm as part of #7286 and even better if you can add a fix!

> I think string is the only primitive value that would have this issue in Scala (if it's not be properly quoting).

Sounds right.

**Comment by jimschubert** [comment]
@gmarz I'm working on a fix. I have the string issue fixed locally, but there were issues with string types having formats (date, date-time, byte, binary). I'll try to have those fixed and added to that PR within a day or two.

Thanks for raising that as an issue, because it was a pretty big one.

**Comment by jimschubert** [comment]
I updated #7286 to support all previously missing functionality, and this should allow for full support of default values. Please review, as I think that PR would supersede this one.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/7286 instead

**Pull request closed without merging**
