### PR TITLE
[JavaPlayFramework ]Update the Java Play Framework generator to version 2.6.3

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This fix issue https://github.com/swagger-api/swagger-codegen/issues/6096
All samples runs fine except, as always, the "fake endpoint" one which has never compile 100% yet because of unsupported cases.

@wing328 I have file this PR against branche 3.0.0 because it contains breaking changes. Let me know if it's ok.

### CODE REVIEW

**Comment by JFCote** [comment]
@wing328 : There seems to be a problem with my PR. It seems it contains all the commit from my latest update. Do you want me to restart it over with only my commit? Sorry about that.

**Comment by JFCote** [comment]
@wing328 : There might be another problem. I've done my changes from a branch created from the "master" but have created the PR against the branch 3.0.0... Maybe that it's causing the problem? Anyway, let me know the best way to fix this and I'll do it.

**Comment by JFCote** [comment]
Yeah the problem is definitely related to the fact that I have created the PR against branche 3.0.0. Let me know best way to fix this. Thanks and sorry about that!

**Comment by wing328** [comment]
@JFCote I've changed the base to master (2.3.0), which allows breaking changes.

**Pull request merged**
