### PR TITLE
[Jaxrs-cxf-cdi] merge beanvalidation templates to single one #4719

### PR DESCRIPTION
**Pull request by jfiala**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

see #4719 

Implementation for language jaxrs-cxf-cdi

### CODE REVIEW

**Comment by jfiala** [comment]
@wing328 @nickcmaynard pls review, I merged both into beanValidationCore.mustache. 
Can I then update all other languages in one PR or do you want one PR for each language?

**Comment by nickcmaynard** [comment]
beanValidationCore appears to be missing.

**Comment by jfiala** [comment]
@nickcmaynard sorry, now its here...

**Comment by nickcmaynard** [comment]
@jfiala Good stuff, thank you.  Now I think we need some corresponding sample updates...  After that, I'm happy.

**Comment by wing328** [comment]
@jfiala to me, 1 PR is fine.

**Pull request merged**
