### PR TITLE
[Issue 9178] Handle multiple formats when decoding dates

### PR DESCRIPTION
**Pull request by plam4u**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR adds multiple date formats discussed and suggested in #9178

When parsing dates, the `CodableHelper` was handling only one specific date format. This means that responses with a different format failed to decode.

Changes done:
- Migrated the samples in swift4 folder to actually use Swift 4.2
- Fixed the issue with the date formatting
- Added tests to confirm that the formatting is working
- Executed the mvn-integration script and updated the script to say Swift 4 instead of 3

### CODE REVIEW

**Comment by plam4u** [comment]
@HugoMario could you check this PR?

**Comment by HugoMario** [comment]
hi @plam4u, sorry for delay, sure, looking now

**Comment by HugoMario** [comment]
@plam4u, unfortunately i'm not so familiar with swift, however i tested locally generating codew with differents inputs and worked fine for me. If you are confident with your changes i can merge them now.

**Comment by plam4u** [comment]
hi @HugoMario 
ideally, someone else should test this as well but since this is a simpler change, I'm pretty confident with it. If you know somebody with Swift knowledge, you could ping him to at least run it and see that it works fine for him as well.

If nobody responds soon, if it is okay with you, you can merge it. Thank you :)

**Comment by HugoMario** [comment]
@plam4u, sure, let's do as you suggest.

**Comment by saltwat5r** [comment]
Hi, why the latest version of generator (3.0.22) doesn't use this version of the template?

**Pull request merged**
