### PR TITLE
Issue 4244 - Add x-discriminator-value

### PR DESCRIPTION
**Pull request by jeff9finger**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@jeff9finger thanks for the PR. I'll review and let you know if I've any question.

Linked to #4244

**Comment by jeff9finger** [comment]
I have a minor addition to the template files.Will merge soon.

**Comment by jeff9finger** [comment]
@wing328 Please also review  issue #4426 and it related pr. These 2 are closely related.

**Comment by jeff9finger** [comment]
@wing328 Can this be reviewed soon? I'd like to see it in the released version.

**Comment by wing328** [comment]
@jeff9finger I'll do it right after syncing master to 2.3.0. Stay tuned.

**Comment by wing328** [comment]
@jeff9finger I did some tests locally and the result is good. Thanks for your contribution.

**Comment by wing328** [comment]
FYI. I'll also update the Java, Java-inflector, etc Petstore sample later (which is what we usually do as part of the PR).

**Pull request merged**
