### PR TITLE
Add JSONModel to objective-c client

### PR DESCRIPTION
**Pull request by geekerzp**
This PR will replace integrate JSONModel(https://github.com/icanzilb/JSONModel) into Obj-C client.

* JSONModel can create model from dictionary and easily export properties to dictionary.
* JSONModel supports conversion between date/datetime string and NSDate (so we no longer need   SWGDate)
* JSONModel is similar to the use of @jsonproperty in Java client.

### CODE REVIEW

**Comment by fehguy** [comment]
Can you please confirm that the generated code works by running this:

```
mvn integration-test -Psamples
```

If xcode is installed it will run the unit tests in `samples/client/petstore/objc`

**Comment by fehguy** [comment]
Also I'm not sure why the build is failing.  You might update the dependencies to swagger-core-1.5.4-M1-SNAPSHOT

**Comment by geekerzp** [comment]
When i run the command `mvn integration-test -Psamples`, it will throw some errors:
```sh
[INFO] ------------------------------------------------------------------------
[INFO] Building Objective-C Swagger Petstore Client 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default) @ PetstoreClient ---
[INFO] Copying swagger-java-jersey-sample-app-1.5.4-M1-SNAPSHOT.war to /Users/geekerzp/swagger/swagger-codegen/samples/client/petstore/objc/target/swagger-java-jersey-sample-app-1.5.4-M1-SNAPSHOT.war
[INFO]
[INFO] >>> jetty-maven-plugin:9.2.9.v20150224:deploy-war (start-jetty) > validate @ PetstoreClient >>>
[INFO]
[INFO] <<< jetty-maven-plugin:9.2.9.v20150224:deploy-war (start-jetty) < validate @ PetstoreClient <<<
[INFO]
[INFO] --- jetty-maven-plugin:9.2.9.v20150224:deploy-war (start-jetty) @ PetstoreClient ---
2015-03-26 22:08:26.498:INFO::main: Logging initialized @54094ms
[INFO] Configuring Jetty for project: Objective-C Swagger Petstore Client
[INFO] Context path = /
[INFO] Tmp directory = /Users/geekerzp/swagger/swagger-codegen/samples/client/petstore/objc/target/tmp
[INFO] Web defaults = org/eclipse/jetty/webapp/webdefault.xml
[INFO] Web overrides =  none
2015-03-26 22:08:26.642:INFO:oejs.Server:main: jetty-9.2.9.v20150224
三月 26, 2015 10:08:30 下午 com.sun.jersey.api.core.PackagesResourceConfig init
信息: Scanning for root resource and provider classes in the packages:
  com.wordnik.swagger.jaxrs.json
  com.wordnik.swagger.sample.resource
  com.wordnik.swagger.jaxrs.listing
三月 26, 2015 10:08:30 下午 com.sun.jersey.api.core.ScanningResourceConfig logClasses
信息: Root resource classes found:
  class com.wordnik.swagger.jaxrs.listing.ApiListingResource
  class com.wordnik.swagger.sample.resource.PetResource
  class com.wordnik.swagger.sample.resource.PetStoreResource
  class com.wordnik.swagger.sample.resource.UserResource
三月 26, 2015 10:08:30 下午 com.sun.jersey.api.core.ScanningResourceConfig logClasses
信息: Provider classes found:
  class com.wordnik.swagger.jaxrs.json.JacksonJsonProvider
  class com.wordnik.swagger.jaxrs.listing.SwaggerSerializers
三月 26, 2015 10:08:30 下午 com.sun.jersey.server.impl.application.WebApplicationImpl _initiate
信息: Initiating Jersey application, version 'Jersey: 1.13 06/29/2012 05:14 PM'
22:08:30,579 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
22:08:30,579 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
22:08:30,579 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [file:/Users/geekerzp/swagger/swagger-codegen/samples/client/petstore/objc/target/tmp/webapp/WEB-INF/classes/logback.xml]
22:08:30,613 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
22:08:30,614 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
22:08:30,618 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDOUT]
22:08:30,658 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - This appender no longer admits a layout as a sub-component, set an encoder instead.
22:08:30,658 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
22:08:30,658 |-WARN in ch.qos.logback.core.ConsoleAppender[STDOUT] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
22:08:30,659 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [com.wordnik] to ERROR
22:08:30,659 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to ERROR
22:08:30,659 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDOUT] to Logger[ROOT]
22:08:30,660 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
22:08:30,661 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@79050c91 - Registering current configuration as safe fallback point

2015-03-26 22:08:31.309:INFO:oejsh.ContextHandler:main: Started o.e.j.m.p.JettyWebAppContext@4fd190a6{/,file:/Users/geekerzp/swagger/swagger-codegen/samples/client/petstore/objc/target/tmp/webapp/,AVAILABLE}{/Users/geekerzp/swagger/swagger-codegen/samples/client/petstore/objc/target/swagger-java-jersey-sample-app-1.5.4-M1-SNAPSHOT.war}
2015-03-26 22:08:31.311:WARN:oejsh.RequestLogHandler:main: !RequestLog
2015-03-26 22:08:31.338:WARN:oejuc.AbstractLifeCycle:main: FAILED ServerConnector@4e0a3b93{HTTP/1.1}{0.0.0.0:8002}: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.doStart(MavenServerConnector.java:120)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357)
	at org.eclipse.jetty.maven.plugin.JettyRunWarMojo.execute(JettyRunWarMojo.java:64)
	at org.eclipse.jetty.maven.plugin.JettyDeployWar.execute(JettyDeployWar.java:67)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-03-26 22:08:31.340:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.maven.plugin.MavenServerConnector@1cd57ec: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.doStart(MavenServerConnector.java:120)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357)
	at org.eclipse.jetty.maven.plugin.JettyRunWarMojo.execute(JettyRunWarMojo.java:64)
	at org.eclipse.jetty.maven.plugin.JettyDeployWar.execute(JettyDeployWar.java:67)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
2015-03-26 22:08:31.342:WARN:oejuc.AbstractLifeCycle:main: FAILED org.eclipse.jetty.maven.plugin.JettyServer@48516d38: java.net.BindException: Address already in use
java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:444)
	at sun.nio.ch.Net.bind(Net.java:436)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:214)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:321)
	at org.eclipse.jetty.server.AbstractNetworkConnector.doStart(AbstractNetworkConnector.java:80)
	at org.eclipse.jetty.server.ServerConnector.doStart(ServerConnector.java:236)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.doStart(MavenServerConnector.java:120)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.server.Server.doStart(Server.java:366)
	at org.eclipse.jetty.maven.plugin.JettyServer.doStart(JettyServer.java:73)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.startJetty(AbstractJettyMojo.java:534)
	at org.eclipse.jetty.maven.plugin.AbstractJettyMojo.execute(AbstractJettyMojo.java:357)
	at org.eclipse.jetty.maven.plugin.JettyRunWarMojo.execute(JettyRunWarMojo.java:64)
	at org.eclipse.jetty.maven.plugin.JettyDeployWar.execute(JettyDeployWar.java:67)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:347)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:154)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:582)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ............................ SUCCESS [  1.586 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [ 28.377 s]
[INFO] swagger-codegen (executable) ....................... SUCCESS [  4.686 s]
[INFO] swagger-generator .................................. SUCCESS [ 17.183 s]
[INFO] Objective-C Swagger Petstore Client ................ FAILURE [  5.592 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 57.770 s
[INFO] Finished at: 2015-03-26T22:08:31+08:00
[INFO] Final Memory: 49M/774M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.jetty:jetty-maven-plugin:9.2.9.v20150224:deploy-war (start-jetty) on project PetstoreClient: Failure: Address already in use -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :PetstoreClient
2015-03-26 22:08:31.667:WARN:oejuc.AbstractLifeCycle:Thread-26: FAILED org.eclipse.jetty.maven.plugin.JettyServer@1edcfad: java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
	at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:281)
	at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
	at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:285)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.shutdown(MavenServerConnector.java:140)
	at org.eclipse.jetty.server.Server.doStop(Server.java:359)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:90)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:133)
Caused by:
java.lang.ClassNotFoundException: org.eclipse.jetty.util.FutureCallback
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:281)
	at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
	at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:285)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.shutdown(MavenServerConnector.java:140)
	at org.eclipse.jetty.server.Server.doStop(Server.java:359)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:90)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:133)
Exception in thread "Thread-26" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/FutureCallback
	at org.eclipse.jetty.server.AbstractConnector.shutdown(AbstractConnector.java:281)
	at org.eclipse.jetty.server.AbstractNetworkConnector.shutdown(AbstractNetworkConnector.java:108)
	at org.eclipse.jetty.server.ServerConnector.shutdown(ServerConnector.java:285)
	at org.eclipse.jetty.maven.plugin.MavenServerConnector.shutdown(MavenServerConnector.java:140)
	at org.eclipse.jetty.server.Server.doStop(Server.java:359)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.stop(AbstractLifeCycle.java:90)
	at org.eclipse.jetty.util.thread.ShutdownThread.run(ShutdownThread.java:133)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.FutureCallback
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
```

**Comment by fehguy** [comment]
Silly question but do you have something running on port 8002?

**Comment by fehguy** [comment]
Seems like there's a bug in how the tests are being executed.  If you run `mvn integration-test` directly from the `samples/client/petstore/objc` folder, you shouldn't have that happen.  I'll get it fixed shortly from the root of the project.

**Comment by geekerzp** [comment]
I have run the command `mvn integration-test -Psamples` and it shows the blow:
```sh
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] swagger-codegen-project ............................ SUCCESS [  1.210 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [  6.570 s]
[INFO] swagger-codegen (executable) ....................... SUCCESS [  4.349 s]
[INFO] swagger-generator .................................. SUCCESS [ 10.774 s]
[INFO] Objective-C Swagger Petstore Client ................ SUCCESS [01:37 min]
[INFO] swagger-client ..................................... SUCCESS [ 19.157 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:19 min
[INFO] Finished at: 2015-03-29T17:54:31+08:00
[INFO] Final Memory: 55M/778M
[INFO] ------------------------------------------------------------------------
```

**Comment by fehguy** [comment]
I had to make some changes to make this work.  Please see https://github.com/swagger-api/swagger-codegen/commit/8de8f486796cb9bd1ab7ba90a4a2c4cc69c04bdd and https://github.com/swagger-api/swagger-codegen/commit/510254e5a3982ee753b746469ea7985c2e18fec0

**Pull request merged**
