### PR TITLE
Allow control of HTML escaping in templates (#3436)

### PR DESCRIPTION
**Pull request by DavidBiesack**
See #3436 for description

I tried to change the version in pom.xml from 2.2.3-SNAPSHOT to 2.2.4-SNAPSHOT but the build fails with google checkstyle (not finding the .xml file???) and I don't know how to address that, so I left the version number unchanged; I supposed that's OK since this is still a -SNAPSHOT, but really this should be a bump in the minor version (2.3.0-SNAPSHOT) because this is not really just a patch but a new feature (new API).

### CODE REVIEW

**Comment by ePaul** [comment]
I think the idea is for breaking changes to go into the 2.3.0 branch, not directly into master.

**Comment by DavidBiesack** [comment]
This is *not* a breaking change. All the existing tests pass without modification - this is an enhancement/new feature (thus a dot release bump; in semantic versioning, a breaking change would have to be a 3.0.0 version instead of a dot release). 

That said, this change could go into a 2.3.0 branch instead of master if that is preferred for such enhancements.

(I think my problem with version in pom.xml is that I need to set it in the parent, but also update all the module poms.)

**Comment by DavidBiesack** [comment]
Is there a release plan for 2.3.0 -- i.e. if pushed there, when might such a fix be available in Maven Central or other public Maven repo?

**Comment by DavidBiesack** [comment]
Closing this pull request. Upon inspection of the code, I can see a better way to achieve the desired result. The `CodegenConfig` interface defines
```java
 Compiler processCompiler(Compiler compiler);
```
which a custom language class that extends `DefaultCodegen` can override.
I suggest the html and html2 langs do this:
```java
    /**
     * Disable HTML escaping done by the Mustache {@link Compiler} 
     * by setting the compiler to {@link Escapers#NONE Escapers.NONE}
     */
    @Override
    public Compiler processCompiler(Compiler compiler) {
        return compiler.withEscaper(Escapers.NONE);
    }
```

**Pull request closed without merging**
