### PR TITLE
Remove swagger play dependency + cleanup

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Removed the "swagger-play" dependency and now use the raw json as the source for the swagger-ui. Removed all the annotation and did a good cleanup of the mustache files. Add the generated sample.

Let me know if I need to change something

### CODE REVIEW

**Comment by wing328** [comment]
@JFCote when I generated the play framework using swagger spec in a different folder (e.g. /var/tmp/java/play4), I got the following errors:
```
play4|⇒ sbt test
[info] Loading project definition from /private/var/tmp/java/play4/project
[info] Updating {file:/private/var/tmp/java/play4/project/}play4-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to swagger-java-playframework (in build file:/private/var/tmp/java/play4/)
[info] Updating {file:/private/var/tmp/java/play4/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 4 Scala sources and 15 Java sources to /private/var/tmp/java/play4/target/scala-2.11/classes...
[error] /private/var/tmp/java/play4/app/controllers/UserApiController.java:64: <identifier> expected
[error]         body = mapper.readValue(nodebody.toString(), List<User>.class);
[error] /private/var/tmp/java/play4/app/controllers/UserApiController.java:81: <identifier> expected
[error]         body = mapper.readValue(nodebody.toString(), List<User>.class);
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 65 s, completed Mar 20, 2017 3:36:59 PM
```

**Comment by JFCote** [comment]
Fix this one too by merging with another sub-branch I had on my fork. It add a couple of small things + lots of bug fixes.

**Comment by wing328** [comment]
@JFCote I still got the same error when generating a new play framework based on Petstore spec while the one in our project `samples/server/petstore/java-play-framework` works fine. Here is the error message:
```
play5|⇒ sbt test
[info] Loading project definition from /private/var/tmp/java/play5/project
[info] Updating {file:/private/var/tmp/java/play5/project/}play5-build...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Set current project to swagger-java-playframework (in build file:/private/var/tmp/java/play5/)
[info] Updating {file:/private/var/tmp/java/play5/}root...
[info] Resolving jline#jline;2.12.1 ...
[info] Done updating.
[info] Compiling 4 Scala sources and 19 Java sources to /private/var/tmp/java/play5/target/scala-2.11/classes...
[error] /private/var/tmp/java/play5/app/controllers/UserApiController.java:53: <identifier> expected
[error]         body = mapper.readValue(nodebody.toString(), List<User>.class);
[error] /private/var/tmp/java/play5/app/controllers/UserApiController.java:65: <identifier> expected
[error]         body = mapper.readValue(nodebody.toString(), List<User>.class);
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 49 s, completed Mar 21, 2017 3:34:20 PM
```

Did you get similar error when generating new Play framework server code in a different folder?

**Comment by JFCote** [comment]
@wing328 : Fixed. There was a bug. It seems I was not using the exact same "petstore" example.

**Comment by wing328** [comment]
Commits merged into master via https://github.com/swagger-api/swagger-codegen/pull/5159 (with updated samples to resolve merge conflicts).

**Pull request closed without merging**
