### PR TITLE
[csharp] Refactor Configuration usage

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This is a resubmit of #3530. Please see that PR's description and conversation. This is being resubmitted because of multiple questionable merge conflicts when merging branch 2.3.0 into the original branch. This new PR/branch is a rebase of the previous submission against 2.3.0.

### Related Issues/PRs

* #2858
* #3530 
* #3632
* #4961

I believe the above can all be closed once this is merged.

### CODE REVIEW

**Comment by jimschubert** [comment]
@wing328 I'm not able to build the Net Standard project for some reason, and it looks like build fails are due to some missing netStandard conditionals (netStandard was added after my work on this branch).

I was wondering if the project builds for you, would you mind looking at fixing those conditions? If not, I'll just need to get the project building locally.

**Comment by wing328** [comment]
> I was wondering if the project builds for you, would you mind looking at fixing those conditions? If not, I'll just need to get the project building locally.

Sure. Let me look into that.

**Comment by jimschubert** [comment]
@wing328 I fixed it. You must not have seen that I edited my comment. Sorry, I sometimes forget that GitHub emails don't get updated or resent when a comment is edited.

**Comment by wing328** [comment]
@jimschubert no worry. I'll take another look tonight and merge accordingly.

**Comment by wing328** [comment]
@jimschubert I ran some tests and overall it's very good. I found some minor issues with .net 3.5 and will file a PR to address those after merging this PR into 2.3.0 tomorrow. (There are a few enhancements I will make as well: docstring, dependency version, etc)

**Comment by jimschubert** [comment]
@wing338 sounds good. I didn't test every supported framework, so I appreciate the extra testing and enhancements.

**Comment by jimschubert** [comment]
@wing338 on a side note, I was considering where to add additional docs on configuration usage, or overall client usage. I think the code in the readme is sufficient to get started but users may like to have a deeper explanation.

Do you think it would be possible to create a mirror repo of the wiki, to allow for PRs against wiki documentation?

**Comment by wing328** [comment]
@jimschubert totally agree some users may like to have a deeper explanation. I was thinking about generating an advanced.md file to show advanced usage of the API client (e.g. logging, debugging, how to disable TLS cert verification, etc)

>Do you think it would be possible to create a mirror repo of the wiki

What do you mean by "mirror repo of the wiki"?  For wiki, are you referring to https://github.com/swagger-api/swagger-codegen/wiki/?

**Comment by jimschubert** [comment]
GitHub wikis can be cloned locally... https://github.com/swagger-api/swagger-codegen.wiki.git

I believe only contributors with push rights can edit the wiki directly. If we were to pull the wiki and create something like Swagger-api/swagger-codegen-wiki with issues disabled, that repo could accept PRs against the wiki. It could be at up with a default branch of `contrib` or something, and whoever maintains it would be responsible for integrating contrib back to master and pushing master to origin (ie this repo).

It's a little maintenance overhead, but an added benefit would be the possibility of versions wikis which we can't currently do with GitHub wikis.

**Comment by wing328** [comment]
Enhancements via https://github.com/swagger-api/swagger-codegen/pull/5756

**Pull request merged**
