### PR TITLE
add multi-arch docker build for linux/arm64/v8

### LINKED ISSUE #11650: Docker image fails on Apple silicone / M1
##### Description

Unable to run via Docker on Apple silicone (arm / M1)

Example:
```shell
$ docker run --rm -it swaggerapi/swagger-codegen-cli
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```

Then my terminal crashes

##### Swagger-codegen version

"latest" on Dockerhub appears to be `2.4.25`

##### Steps to reproduce

On an Apple computer with an M1 processor — run
```
docker run --rm -it swaggerapi/swagger-codegen-cli
```

##### Related issues/PRs

https://github.com/swagger-api/swagger-editor/issues/2725

### PR DESCRIPTION
**Pull request by mitjaziv**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR adds multi-arch build with `docker buildx` to add support for Apple M1 machines.

Closes #11650

### CODE REVIEW

**Comment by mitjaziv** [comment]
@frantuma @HugoMario What do you think about this change? Could we release this with next version so swagger-codegen would be supported on M1 machines.

**Comment by joaosa** [comment]
This would be a very welcome change to our CI pipelines 👍

**Comment by fellnerse** [comment]
Do you know when the first image will be available?

**Comment by mitjaziv** [comment]
For everyone who is waiting for this pull request in the meanwhile you can use this.

https://hub.docker.com/r/mitjaziv/swagger-codegen-cli
https://github.com/mitjaziv/swagger-codegen

**Comment by Dynehart** [comment]
Can one of the organization members take a look at this PR and merge it?
@char0n @frantuma @gracekarina @HugoMario @ponelat

**Comment by joshmurrayeu** [comment]
Similar response to @Dynehart above. Could someone look into updating this PR and merging? Thanks!

**Comment by andresvia** [comment]
@mitjaziv I'm not a maintainer but I would recommend to make only the change that is required.

Replace `docker build` with `docker buildx build --platform linux/arm64/v8,linux/amd64`

They are probably too busy to understand the rest of the change. Even though I agree it should be done. They probably don't use `shellcheck` 🤷

**Comment by repositarian** [comment]
Bump
Somebody please check & merge this PR. We really need this 
 @char0n @frantuma @gracekarina @HugoMario @ponelat @HugoMario

**Comment by mitjaziv** [comment]
> Hi folks, sorry for all the waiting. Will take a look into this. Thank you for your patience.

I guess this is really old PR, and a lot was changed since it was opened, so I would need to re-investigate what needs to be changed, to fix pipelines.

**Comment by frantuma** [comment]
Thanks all for your patience, this has been replaced by the following changes adding multi-platform images builds:

[#12290, #12291, #12292, #12293, #12294](https://github.com/swagger-api/swagger-codegen/compare/d97e6c6343832554f66f7de1352b7b3d4f90843f..d249140100b38754f469907aaf01bb1aa2fecc56)

similar changes are being applied to 3.0.0 branch

**Pull request closed without merging**
