### PR TITLE
Add support for typescript-jquery (typescript-based API calls using jquery ajax in the browser)

### PR DESCRIPTION
**Pull request by bherila**
### PR checklist

- [X] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Adds a typescript-jquery language option.

### CODE REVIEW

**Comment by wing328** [comment]
@bherila thanks for the PR. I did some tests and the result is good.

**Comment by wing328** [comment]
Tweet: https://twitter.com/wing328/status/841685880473509891

Please help retweet to promote the new generator.

**Comment by wing328** [comment]
@bherila for your upcoming PRs, I would suggest creating a new branch as per git best practice.

**Comment by bherila** [comment]
@wing328 sure, I will do that

**Comment by JFCote** [comment]
@bherila : As proposed by @wing328 , I'm letting you know that I will start to work on a refactor of your `typescript-jquery` template to use the very good model generator from the `typescript-angular2` template. Since your are the creator of this template, I will tag you in all my future PR to make sure you can comment on them! I should create a PR since the end of the week. Thanks!

**Comment by wing328** [comment]
@JFCote please pull the latest as I've merged a PR to replace tab with 4-space for code indentation.

**Comment by JFCote** [comment]
@wing328 : Yes I have the latest
@bherila : My PR is probably going to be pushed in 2-3 weeks. I forgot our typescript specialist is currently gone for 2 weeks and he will review my submission before I create the PR.
I'll keep you posted. If you do any update until then, please notify me if possible!

**Comment by bherila** [comment]
The only thing I will add is that I have a very large API by now and I really hope it's not going to be a breaking change in terms of the generated models!

Thanks,
Ben

Sent with thumbs

On Apr 3, 2017, at 11:05 AM, Jean-François Côté <notifications@github.com<mailto:notifications@github.com>> wrote:


@wing328<https://github.com/wing328> : Yes I have the latest
@bherila<https://github.com/bherila> : My PR is probably going to be pushed in 2-3 weeks. I forgot our typescript specialist is currently gone for 2 weeks and he will review my submission before I create the PR.
I'll keep you posted. If you do any update until then, please notify me if possible!

**Comment by JFCote** [comment]
@bherila : Fear not, will make sure it doesn't break anything and if it does, tell us and we will work this out.

As for my PR, it will take longer. I have been flooded at work and did not have time to work on this a lot.
Will let you know when it's ready!

**Comment by wing328** [comment]
If the enhancements contain breaking changes, please submit against 2.3.0 branch instead.

**Comment by bherila** [comment]
Since the jquery and fetch APIs are not compatible, it will certainly be a breaking change. The jquery api returns the response object and the content is retrieved with `{response}.body` whereas the fetch API returns the body directly as the result of the promise.

**Comment by JFCote** [comment]
@bherila : I'm not changing anything related to that. It will still use jquery but it will use the model generation from the Angular2 and made additionnal improvement in the generator itself. It should be backward compatible for the moment (almost 75% done for now).

If I'm not sure at the end, I will submit it in the 2.3.0 branch and you will be able to test it. If it doesn't break anything, we could also merge it in the master.

Will let you know when it's ready! Thanks!

**Pull request merged**
