### PR TITLE
[Python] Option to skip client validations

### PR DESCRIPTION
**Pull request by arunnalla**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- Adds option to skip all client-side validations for python client
- https://github.com/swagger-api/swagger-codegen/issues/5530

### CODE REVIEW

**Comment by HugoMario** [comment]
Thanks for this PR @slash-arun 

can you please fix failing tests, such as:
```
Traceback (most recent call last):
  File "/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/python/tests/test_enum_arrays.py", line 157, in test_equals
    self.assertEqual(fish1, fish2)
AssertionError: {'array_enum': ['fish'], 'just_symbol': '$'} != {'array_enum': ['fish'], 'just_symbol': '$'}
```
in order to merge them?

**Comment by slash-arun** [comment]
@HugoMario Sorry for leaving this PR hanging, I was caught up with something else. I will fix these asap

**Comment by slash-arun** [comment]
@HugoMario @kenjones-cisco This PR is ready for review. Please take a look.

**Comment by HugoMario** [comment]
thanks a lot @slash-arun, this LGTM but would like also someone else review

**Comment by slash-arun** [comment]
Sure @HugoMario , let me know if I should CC anyone else in particular. I already cc'd kenjones as per the document.

**Review by sebastian-hatala-leanix — APPROVED** [review]
LGTM 👍

**Comment by HugoMario** [comment]
please build

**Comment by HugoMario** [comment]
it seems the source repo was removed, i'm going to migrate changes to another PR in order to merge this

**Pull request closed without merging**
