### PR TITLE
[nodejs server] add CORS support

### PR DESCRIPTION
**Pull request by markuseckstein**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Adds built-in CORS support to generated nodejs server.

Please review
@CodeNinjai 
@frol 
@cliffano

### CODE REVIEW

**Comment by markuseckstein** [comment]
By default it will enable CORS on all routes (I think this is by far the most common use-case). 
But users can change the line
`app.use(cors());`
with any configuration they like (or remove it completely to disable it).

**Comment by frol** [comment]
I consider this to be an unsafe default as this basically just disables the security protection. I am not the maintainer / envisioner of the project, so I won't make any decision here.

**Comment by markuseckstein** [comment]
I updated the PR so that default is still to disable CORS completely. But everything is prepared to enable CORS simply by uncommenting one line. This way, we have no unsafe defaults, but users still have a convenient way of enabling it if they wish.

**Comment by AxelGanter** [comment]
Hey there, is CORS now enabled?
My Server ist only queried by one Frontend (from another server). What is the suggested configuration for that? thanks.

**Pull request closed without merging**
