### PR TITLE
fix(swift3): add en_US_POSIX locale to date formatters

### PR DESCRIPTION
**Pull request by julienfouilhe**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

The same thing has been done for the swift generator, it resolves the same issue, described there: https://github.com/swagger-api/swagger-codegen/issues/2159
https://github.com/swagger-api/swagger-codegen/pull/5008

The only file edited is this one: `modules/swagger-codegen/src/main/resources/swift3/Models.mustache`

### CODE REVIEW

**Comment by wing328** [comment]
@julienfouilhe thanks for the PR.

cc @Edubits @jaz-ah @jgavris for review.

**Comment by jgavris** [comment]
👍  possible / easy to isolate a unit test in the example suite?

**Comment by julienfouilhe** [comment]
@jgavris Where are they located? I don't see any swift tests.

**Comment by wing328** [comment]
@julienfouilhe you can find the test cases for Swift3 Petstore client under https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/swift3

**Comment by julienfouilhe** [comment]
@wing328 @jgavris After giving it some thought I'm not sure how to test that as it depends on the user's device locale. But here is a link to Apple's recommendations: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/DataFormatting/Articles/dfDateFormatting10_4.html

> If you're working with fixed-format dates, you should first set the locale of the date formatter to something appropriate for your fixed format. In most cases the best locale to choose is en_US_POSIX, a locale that's specifically designed to yield US English results regardless of both user and system preferences. en_US_POSIX is also invariant in time (if the US, at some point in the future, changes the way it formats dates, en_US will change to reflect the new behavior, but en_US_POSIX will not), and between platforms (en_US_POSIX works the same on iPhone OS as it does on OS X, and as it does on other platforms).

**Comment by jgavris** [comment]
I've had success swizzling `+[NSLocale currentLocale]` in tests (not in this project though). You could maybe do one or two examples.

**Comment by wing328** [comment]
@jgavris @jaz-ah @Edubits shall we add the tests in a separate PR instead and merge this PR into master if the PR looks good and has been tested manually?

**Comment by jaz-ah** [comment]
i'm ok w/ that @wing328

**Comment by jgavris** [comment]
👍  as well, sorry for the delay

**Pull request merged**
