### PR TITLE
[JaxrsResteasy] Fix EAP dependencies for Java 8

### PR DESCRIPTION
**Pull request by ianjoneill**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

* Depend on Joda by default, like the default JAX-RS server.
* If Java 8 is specified add Jackson JSR-310 dependency and import
  in the JacksonConfig.

### CODE REVIEW

**Comment by ianjoneill** [comment]
Test failure is in the `typescript-angular` module and has nothing to do with my change:
```
> petstore-typescript-node-sample@1.0.0 postinstall /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-angular

> tsd reinstall --overwrite





-> running reinstall

[ERR!] GitHub API: GitHub rate limit reached.

    To increase the limit use GitHub authentication.

    See: https://github.com/DefinitelyTyped/tsd#tsdrc
```

**Comment by ianjoneill** [comment]
Just noticed a slight issue with this, will resolve soon.

**Comment by ianjoneill** [comment]
@wing328 any chance this could make the 2.2.3 release? The Resteasy EAP library doesn't compile if you select Java8 as the date library in the master branch.

**Comment by wing328** [comment]
@ianjoneill sorry we just released 2.2.3 but we should release 2.3.0 by the end of Aug.

Thanks for fix. I'll add a test to cover the Java8 as date library later.

**Comment by wing328** [comment]
FYI. Setup CI tests via https://github.com/swagger-api/swagger-codegen/pull/6091

**Pull request merged**
