### PR TITLE
Fix NullPointerException for info.version on Javascript client codegen

### PR DESCRIPTION
**Pull request by erdarun**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Issue Reference #5467

### CODE REVIEW

**Comment by wing328** [comment]
@erdarun the function is used by other operations as well so I don't think it's a good idea to default to "1.0.0" if it's set to null.

I can show you where to set the default for "version" if it's missing.

**Comment by wing328** [comment]
You will need to add an else-clause to set a default version/appVersion:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L152-L154

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L181-L183

**Comment by wing328** [comment]
Please also use LOGGER.error to report the missing required fields.

**Comment by erdarun** [comment]
@wing328 
Can we report LOGGER.WARN for version missing and
Can we return default value as 1.0.0 at,
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L152-L154

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L181-L183

**Comment by erdarun** [comment]
@wing328 PR updated as per your comments

**Comment by wing328** [comment]
@erdarun also looks good to me.

**Pull request merged**
