### PR TITLE
Feat/travis fail if generator changes

### PR DESCRIPTION
**Pull request by JLLeitschuh**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Travis now runs all of the code generation to ensure that the person opening the PR has updated the samples with any changes that they have made.

If the individual has not run the generation scripts then travis will fail the build.

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
The perl project needs to have the date removed from the readme for this to work correctly.

**Comment by JLLeitschuh** [comment]
I don't know why travis is failing the way it is unless there exists a problem in the generated code as it is now.

**Comment by wing328** [comment]
@JLLeitschuh thanks for the PR. It's definitely a good attempt.

If I only update README.md (in which I did quite often), will your mechanism to detect changes report errors?

**Comment by JLLeitschuh** [comment]
It detects any diff that running the code generator creates.
So if you forget to run the code generator and there is a change that would have happened in the samples this will fail.

**Comment by JLLeitschuh** [comment]
My company has decided to go a different route than use the swagger codegenerator.
I don't think I'm going to have the time to clean this up ever. This PR can be closed unless you think that someone else would be willing to take on cleaning this up.

**Pull request closed without merging**
