### PR TITLE
Topic resteasy queryparams defaultvalue: issue #6716

### PR DESCRIPTION
**Pull request by andreaformica**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)
Copy into queryParams.mustache terms to add a DefaultValue in the generated API for Resteasy.

### CODE REVIEW

**Comment by wing328** [comment]
@andreaformica thanks for the PR. I updated the samples and got:
```
         @io.swagger.annotations.ApiResponse(code = 400, message = "Invalid tag value", response = Void.class) })
-    public Response findPetsByTags( @NotNull  @QueryParam("tags") List<String> tags,@Context SecurityContext securityContext)
+    public Response findPetsByTags( @NotNull ) @QueryParam("tags") List<String>tags,@Context SecurityContext securityContext)
```

Seems like there's an additional ")", which will make the code failed to compile.

Also please remove the new line at the end of the file.

**Comment by andreaformica** [comment]
I do not know what I should do to make the technical commit aware of the pull request.
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09)

**Comment by andreaformica** [comment]
Hi @wing328 , I will do it a little bit later. Thanks for the feedback.

**Comment by andreaformica** [comment]
I think there was more than one problem. I am going to do another PR...is that ok ?

**Comment by wing328** [comment]
> I think there was more than one problem. I am going to do another PR...is that ok ?

Definitely. I'm closing this one. Please file another one when the fix is ready.

**Pull request closed without merging**
