### PR TITLE
Fixed #1304: Migrate tests from the Scala to the plain Java. Part 3

### LINKED ISSUE #1304: Migrate tests from the Scala to the plain Java
Rework all test to the Java with the TestNG framework

Tests from the swagger-codegen module:
- [ ] main https://github.com/swagger-api/swagger-codegen/pull/1305, https://github.com/swagger-api/swagger-codegen/pull/1329
- [x] java https://github.com/swagger-api/swagger-codegen/pull/1305, https://github.com/swagger-api/swagger-codegen/pull/1312
- [x] Objc https://github.com/swagger-api/swagger-codegen/pull/1312
- [x] php https://github.com/swagger-api/swagger-codegen/pull/1312
- [x] python https://github.com/swagger-api/swagger-codegen/pull/1312
- [ ] scala https://github.com/swagger-api/swagger-codegen/pull/1329
- [ ] staticDocs https://github.com/swagger-api/swagger-codegen/pull/1329
- [ ] typescriptnode https://github.com/swagger-api/swagger-codegen/pull/1329
- [ ] typescriptangular https://github.com/swagger-api/swagger-codegen/pull/1329

Tests from the swagger-generator module:
- [x] all https://github.com/swagger-api/swagger-codegen/pull/1305

### PR DESCRIPTION
**Pull request by iushankin**
Please pay your attention to the `modules/swagger-codegen/pom.xml` file while reviewing

### CODE REVIEW

**Comment by wing328** [comment]
@iushankin thanks for the heads-up about `modules/swagger-codegen/pom.xml` and I notice that you've removed some scala plug-ins from pom.xml. There are still 3 scala test files pending to be migrated: ObjcModelTest.scala, PhpModelTest.scala, PythonTest.scala and I don't see test result for these 3 test files any more. Is that due to the removal of the scala plug-ins or am I doing something wrong when running the tests?

**Comment by iushankin** [comment]
@wing328 those tests was migrated in the other PR https://github.com/swagger-api/swagger-codegen/pull/1312

**Comment by wing328** [comment]
@iushankin so those 3 scala test files should be removed as well (given that they've already been migrated)?

**Comment by iushankin** [comment]
@wing328 yes, those files were deleted in https://github.com/swagger-api/swagger-codegen/pull/1312

**Comment by wing328** [comment]
@iushankin I see. I asked because I found those files under the `issue-1304-part3` branch.

**Pull request merged**
