### PR TITLE
[ObjC] Fix deprecated JSONModel API usage

### PR DESCRIPTION
**Pull request by Dreddik**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
Replaced deprecated call `-[JSONKeyMapper initWithDictionary:]` with `-[JSONKeyMapper initWithModelToJSONDictionary:]`, inverting keys and values of dictionary as required.

### CODE REVIEW

**Comment by Dreddik** [comment]
Fix for #4129

**Comment by wing328** [comment]
@Dreddik thanks for the PR. Do we also need to update `jsonmodel` to the latest stable version (1.7) in the podspec: https://github.com/Dreddik/swagger-codegen/blob/9510ba5462317734b8237754a73e871dfba506af/modules/swagger-codegen/src/main/resources/objc/podspec.mustache#L34 ?

Btw, please run `objc-petstore-all.sh` to update ObjC Petstore samples (CoreData) as well.

cc @mateuszmackowiak

**Comment by Dreddik** [comment]
@wing328 
> Do we also need to update jsonmodel to the latest stable version (1.7) 

Actually, API changed in v1.4, so we can use it, I suppose? In any way, clients will use version 1.7, because minor version is not specified in `podspec`.
> Btw, please run objc-petstore-all.sh to update ObjC Petstore samples (CoreData) as well.

Already done.

**Comment by wing328** [comment]
> Actually, API changed in v1.4, so we can use it, I suppose? In any way, clients will use version 1.7, because minor version is not specified in podspec.

Yes, please update it to v1.4 as that is the minimal version required for the auto-generated ObjC SDK after this change.

Also to confirm my understanding, I believe developers can still do the following after the change:
```
    pet = [[SWGPet alloc] initWithDictionary:petDict error:nil];
```
and they will receive a warning saying that `initWithDictionary` has been deprecated. In other words, this PR (change) is backward compatible. Please kindly correct me if I misunderstood.

**Comment by Dreddik** [comment]
>Also to confirm my understanding, I believe developers can still do the following after the change...

This PR is backward compatible, because it is only affects initialization of JSONKeyMapper inside of model classes. 
`[[SWGPet alloc] initWithDictionary:petDict error:nil]` won't be affected (and actually not deprecated).

**Comment by wing328** [comment]
@Dreddik PR merged into master. Thanks for your contribution.

**Pull request merged**
