### PR TITLE
Add DefaultValue Annotation to @FormParam

### PR DESCRIPTION
**Pull request by qtstc**
It is included in queryParams.mustache but not in formParams.mustache for some reason.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by wing328** [comment]
Please also rebase on the latest master to resolve the merge conflicts.

**Comment by qtstc** [comment]
@wing328 thanks for the suggestion on fixing my commit history. I linked my other email to this Github account, that should help right?

BTW I think some integration tests are flaky. Not sure why this failed: https://travis-ci.org/swagger-api/swagger-codegen/builds/143133868. I am sending out [this PR ](https://github.com/swagger-api/swagger-codegen/pull/3322)to address one of the problems in the test, but I don't think it will fix the flakiness.

**Comment by wing328** [comment]
@qtstc thanks for the PR, which has been merged into master.

About the CI tests, I agree that it's not ideal as all CI tests in different langauges are sharing the same backend (petstore server) for testing.

In the next release, we'll try to run the petstore server locally in the CI test container instead.

**Pull request merged**
