### PR TITLE
[Spring] Add beanvalidation annotations

### PR DESCRIPTION
**Pull request by jfiala**
### PR checklist

- [x Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

add beanvalidation annotation support to language spring + libraries spring-boot, spring-mvc, spring-cloud

for details see #4091

### CODE REVIEW

**Comment by cbornet** [comment]
spring-cloud is a client lib. It should not be generated in samples/server

**Comment by jfiala** [comment]
thx for the hint - removed server sample & updated client/spring-cloud.

**Comment by wing328** [comment]
@jfiala when you've time, would you please rebase on the latest master to resolve the merge conflicts?

**Comment by jfiala** [comment]
@wing328 I rebased and updated the samples for spring-boot and spring-cloud once more.

**Comment by jfiala** [comment]
closing PR as it shows too many changes due to error during rebase.

**Pull request closed without merging**
