### PR TITLE
[WIP] Support Swift code generation

### PR DESCRIPTION
**Pull request by tkQubo**
issue from #471

### CODE REVIEW

**Comment by tkQubo** [comment]
Sorry I didn't notice yissachar's ongoing branch.  So I will close this PR.

**Comment by yissachar** [comment]
@tkQubo Unfortunately it doesn't look like I'll have time to finish off my branch in the near future, and it's still missing file upload support, so if you've got a working implementation, I think it's better if you just reopen your PR.

**Comment by webron** [comment]
@tkQubo - however, if you do resubmit it, please make sure to do it against the develop_2.0 branch.

**Comment by tkQubo** [comment]
@yissachar OK.  Although I haven't implemented much of functionality, I'll try it anyway

**Comment by tkQubo** [comment]
@webron I see.  I'll do it on develop_2.0 branch :bow:

**Comment by tkQubo** [comment]
@webron Sorry I have a question.  Is it better to make a new branch from develop_2.0?

**Comment by webron** [comment]
Yup. The develop_2.0 branch already contains quite a few changes slated for the next release, and in order to integrate with it, your own development should branch off of it.

**Comment by tkQubo** [comment]
I understand.  Thanks a lot! :star2:

**Pull request closed without merging**
