### PR TITLE
[csharp] Client nuspec

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Per #3350, this generates a nuspec for C# client generated code.

To test, run:

```
./bin/csharp-petstore.sh
```

On Windows:

```
cd samples\client\petstore\csharp\SwaggerClient\src\IO.Swagger
nuget pack -Build -OutputDirectory out IO.Swagger.csproj
```

This will create the `.nupkg` file under a new directory called `out`.

This implementation bundles the README.md and docs.

### CODE REVIEW

**Comment by wing328** [comment]
@jimschubert thanks for the PR but the CI reported the following issue:
```
$ /bin/bash ./bin/utils/detect_carriage_return.sh
modules/swagger-codegen/src/main/resources/csharp/nuspec.mustache
Templates contain carriage return '/r'. Please remove it and try again.
```
I believe the NuGET packing will still work after removing the carriage return from nuspec.mustache.

Please take a look when you've time.

**Comment by jimschubert** [comment]
@wing328 I can save with line feed only. The file looks terrible in Windows without carriage returns. Is that alright? I don't understand the need to warn for carriage returns, does it cause problems somehow?

**Comment by wing328** [comment]
@jimschubert another way is to change your git setting so that git will clean it up for you during commit: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md#tips

We did receive complains about auto-generated files containing '/r' before.

Personally I think it would be a good idea to standardize the line break in the project unless there's a specific use case that we must use '/r'. I'm definitely open to discussion to allow '/r' in the code or template files.

**Comment by jimschubert** [comment]
@wing328 I think files predominately used by Windows users like the C# stuff should probably allow carriage returns. It might make sense to disallow it in the templates, but output with carriage returns as an option?

**Comment by wing328** [comment]
@jimschubert one thing I also consider is the experience programming in Mac/Linux (using Mono) with the C# client/server generated by Swagger Codegen. I think it depends on what IDE/editor is being used and some editors may not have the (default) setting to hide/convert "\r\n" properly.

**Pull request merged**
