### PR TITLE
[Java Play Framework] Fix conversions

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

A small fix to the conversion of boolean value

### CODE REVIEW

**Comment by wing328** [comment]
@JFCote thanks for the PR. Please run `./bin/java-play-framework-petstore-server.sh` to update Petstore samples.

You may be interested in adding "examples" response support to Play generator: https://github.com/swagger-api/swagger-codegen/issues/5423

**Comment by JFCote** [comment]
@wing328 : You are totally right! I forgot to commit  the sample! I did this in a hurry, I will add this tomorrow maybe.

As for the "examples" response support, I'm not sure to understand exactly what this is. Can you give me more information? Thanks!

**Comment by wing328** [comment]
> As for the "examples" response support, I'm not sure to understand exactly what this is. Can you give me more information? Thanks!

https://github.com/wing328/swagger-codegen/blob/813949dd00a2e195a1f448b5e13c92d47082ec71/modules/swagger-codegen/src/main/resources/JavaSpring/apiController.mustache#L51-L61 is a good starting point. Basically that code block leverages the `examples` defined in the OpenAPI/Swagger spec and uses these `examples` as the endpoint response.

**Comment by JFCote** [comment]
@wing328 : I added the generated sample. I don't know if I will have time very soon to add "examples" support, I'm very busy right now. Can you add me to the existing task so I have a reminder. Also add Java Play Framework to the list. Thanks

**Comment by wing328** [comment]
@JFCote Travis CI reported the following issue:
```
[2K[0m[[0minfo[0m] [0mResolving jline#jline;2.12.1 ...[0m
[0m[[0minfo[0m] [0mDone updating.[0m
[0m[[0minfo[0m] [0mCompiling 4 Scala sources and 20 Java sources to /home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/target/scala-2.11/classes...[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/PetApiControllerImp.java:28: illegal start of type[0m
[0m[[31merror[0m] [0m    public List<Pet> findPetsByStatus( @NotNullList<String> status) throws Exception {[0m
[0m[[31merror[0m] [0m                                                   ^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/PetApiControllerImp.java:63: identifier expected but `}' found.[0m
[0m[[31merror[0m] [0m}[0m
[0m[[31merror[0m] [0m^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/PetApiControllerImpInterface.java:19: illegal start of type[0m
[0m[[31merror[0m] [0m    List<Pet> findPetsByStatus( @NotNullList<String> status) throws Exception;[0m
[0m[[31merror[0m] [0m                                            ^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/PetApiControllerImpInterface.java:31: identifier expected but `}' found.[0m
[0m[[31merror[0m] [0m}[0m
[0m[[31merror[0m] [0m^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/UserApiControllerImp.java:45: identifier expected but `,' found.[0m
[0m[[31merror[0m] [0m    public String loginUser( @NotNullString username,  @NotNullString password) throws Exception {[0m
[0m[[31merror[0m] [0m                                                    ^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/UserApiControllerImp.java:62: `)' expected but `}' found.[0m
[0m[[31merror[0m] [0m}[0m
[0m[[31merror[0m] [0m^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/UserApiControllerImpInterface.java:24: identifier expected but `,' found.[0m
[0m[[31merror[0m] [0m    String loginUser( @NotNullString username,  @NotNullString password) throws Exception;[0m
[0m[[31merror[0m] [0m                                             ^[0m
[0m[[31merror[0m] [0m/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/UserApiControllerImpInterface.java:30: `)' expected but `}' found.[0m
[0m[[31merror[0m] [0m}[0m
[0m[[31merror[0m] [0m^[0m
[0m[[31merror[0m] [0m8 errors found[0m
[0m[[31merror[0m] [0m(compile:[31mcompileIncremental[0m) Compilation failed[0m
[0m[[31merror[0m] [0mTotal time: 6 s, completed May 12, 2017 2:58:24 PM[0m
```

Please take a look when you've time.

**Comment by JFCote** [comment]
@wing328 : Here is the fix. It was introduced by "polci" in a previous merge. I don't understand why it didn't failed on his/her PR instead of mine :) Anyway, it's fixed. Maybe it would be good to check if the problem introduced in the Play Generator was also introduced in other generator (missing space)

**Comment by wing328** [comment]
@JFCote I checked other Java stub server generators and they didn't seem to have the same issue:
```
swagger-codegen|master⚡ ⇒ grep -R '@NotNull{{' modules/swagger-codegen/src/main/resources/*
modules/swagger-codegen/src/main/resources/Java/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}} 
modules/swagger-codegen/src/main/resources/JavaJaxRS/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}} 
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}} 
modules/swagger-codegen/src/main/resources/JavaJaxRS/cxf-cdi/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}} 
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}} 
modules/swagger-codegen/src/main/resources/JavaJaxRS/resteasy/eap/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{#pattern}} @Pattern(regexp="{{{pattern}}}"){{/pattern}}{{#minLength}}{{#maxLength}} @Size(min={{minLength}},max={{maxLength}}){{/maxLength}}{{/minLength}}{{#minLength}}{{^maxLength}} @Size(min={{minLength}}){{/maxLength}}{{/minLength}}{{^minLength}}{{#maxLength}} @Size(max={{maxLength}}){{/maxLength}}{{/minLength}}{{#minItems}}{{#maxItems}} @Size(min={{minItems}},max={{maxItems}}){{/maxItems}}{{/minItems}}{{#minItems}}{{^maxItems}} @Size(min={{minItems}}){{/maxItems}}{{/minItems}}{{^minItems}}{{#maxItems}}   @Size(max={{maxItems}}){{/maxItems}}{{/minItems}}{{#minimum}} @Min({{minimum}}){{/minimum}}{{#maximum}} @Max({{maximum}}){{/maximum}}
modules/swagger-codegen/src/main/resources/JavaJaxRS/spec/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}} 
modules/swagger-codegen/src/main/resources/JavaPlayFramework/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{#pattern}} @Pattern(regexp="{{{pattern}}}"){{/pattern}}{{#minLength}}{{#maxLength}} @Size(min={{minLength}},max={{maxLength}}){{/maxLength}}{{/minLength}}{{#minLength}}{{^maxLength}} @Size(min={{minLength}}){{/maxLength}}{{/minLength}}{{^minLength}}{{#maxLength}} @Size(max={{maxLength}}){{/maxLength}}{{/minLength}}{{#minItems}}{{#maxItems}} @Size(min={{minItems}},max={{maxItems}}){{/maxItems}}{{/minItems}}{{#minItems}}{{^maxItems}} @Size(min={{minItems}}){{/maxItems}}{{/minItems}}{{^minItems}}{{#maxItems}}   @Size(max={{maxItems}}){{/maxItems}}{{/minItems}}{{#minimum}} @Min({{minimum}}){{/minimum}}{{#maximum}} @Max({{maximum}}){{/maximum}}
modules/swagger-codegen/src/main/resources/JavaSpring/beanValidationQueryParams.mustache:{{#required}} @NotNull{{/required}}{{>beanValidationCore}}
```
Can you please refactor the following into {{>beanValidationCore}} similar to what we've done for other Java server stub generator?
```
{{#pattern}} @Pattern(regexp="{{{pattern}}}"){{/pattern}}{{#minLength}}{{#maxLength}} @Size(min={{minLength}},max={{maxLength}}){{/maxLength}}{{/minLength}}{{#minLength}}{{^maxLength}} @Size(min={{minLength}}){{/maxLength}}{{/minLength}}{{^minLength}}{{#maxLength}} @Size(max={{maxLength}}){{/maxLength}}{{/minLength}}{{#minItems}}{{#maxItems}} @Size(min={{minItems}},max={{maxItems}}){{/maxItems}}{{/minItems}}{{#minItems}}{{^maxItems}} @Size(min={{minItems}}){{/maxItems}}{{/minItems}}{{^minItems}}{{#maxItems}}   @Size(max={{maxItems}}){{/maxItems}}{{/minItems}}{{#minimum}} @Min({{minimum}}){{/minimum}}{{#maximum}} @Max({{maximum}}){{/maximum}}
```

**Comment by JFCote** [comment]
Here is the requested refactor. I hope I understand it well :)

**Comment by wing328** [comment]
@JFCote looks good to me. Thanks for the enhancement.

**Pull request merged**
