### PR TITLE
[Java] Implemented support for Play! 2.5.x (java8) for retrofit2 client

### PR DESCRIPTION
**Pull request by lukoyanov**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Support for Play! 2.5.x (java8) for retrofit2 client

### CODE REVIEW

**Comment by cbornet** [comment]
Are we going to pull a new option for each new version of Play ?!

**Comment by wing328** [comment]
@lukoyanov I agree with @cbornet that we should avoid introducing another option for this case.

For TypeScript Angular2, we recently introduced the option `ngVersion` so that developers can choose TS Angular 2x or 4x based on their use case.

For your case, I would suggest renaming the option to `usePlayWS` and make the change (this PR) to 2.3.0 as it's a breaking change.

If users need to use Play! (2.4.x), they can use the master.

**Comment by lukoyanov** [comment]
@wing328 ok, i'll take a look at TS Angular 2x implementation and update this PR.

**Comment by wing328** [comment]
@lukoyanov if you need any help, just let me know.

**Comment by lukoyanov** [comment]
I've finished the implementation and improved several things along the way (backport to play24 in 6302). Now Play! support can be enabled via usePlayWS config option, and specific version can be set via playVersion (play24, play25 is supported).

**Comment by lukoyanov** [comment]
@wing328 Should I reopen this PR against 3.0 branch?

**Comment by wing328** [comment]
@lukoyanov sorry I incorrectly closed it. Please still target current master for the change.

3.0.0 is mainly for supporting OpenAPI spec 3.0.

**Comment by lukoyanov** [comment]
Fixed issues after merge.

**Comment by lukoyanov** [comment]
@wing328 @cbornet Is there something else I should fix/implement here?

**Comment by wing328** [comment]
@lukoyanov Let me review tomorrow and merge accordingly (sorry too busy these days...)

**Comment by wing328** [comment]
@lukoyanov I ran `./bin/java-petstore-retrofit2-play25.sh` to udpate the petstore sample but got errors running `mvn test` in `samples/client/petstore/java/retrofit2-play25`.

Please take a look when you've time.

**Comment by lukoyanov** [comment]
@wing328 sorry, fixed it.

**Comment by wing328** [comment]
@lukoyanov np. I performed some tests and the result is good.

Thanks for the enhancement.

**Pull request merged**
