### PR TITLE
[C#] Added RestSharp.dll and updated compile.bat

### PR DESCRIPTION
**Pull request by wing328**
For #782 and the user reported the fix works.

### CODE REVIEW

**Comment by wing328** [comment]
Are you testing against the `csharp_add_restsharp_dll` branch from my (wing328) repo ?

**Comment by uniprof** [comment]
Yes I am.

**Comment by wing328** [comment]
In another machine, I could pull the branch and execute the batch file to produce IO.Swagger.Client.dll and IO.Swagger.Client.xml

screen shot 2015-05-26 at 6 05 56 pm

**Comment by wing328** [comment]
@uniprof I updated the code to use file separator. Please give it another try.

**Comment by uniprof** [comment]
@wing328  AH AHHH..... it is working perfect now !!!
I would like to ask you one question out of the box.. hope you will not laugh too much.....

How can I merge your csharp_add_restsharp_dll branch with the developer2.0 branch in the main project ?

**Comment by wing328** [comment]
@uniprof we don't have permission to merge that. Only the owners of this project has the permission to do so.

How urgent do you need this PR to be merged into `develop_2.0` ?

**Comment by uniprof** [comment]
not much, just want to use the last changes they did.
I can't perform them merge locally as well?

G.

**Comment by wing328** [comment]
I think technically you can get a diff file from this PR (branch: csharp_add_restsharp_dll) and then manually patch your local copy. (not something I would recommend)

**Comment by webron** [comment]
@uniprof - you can clone @wing328's fork, and sync the branch with develop_2.0 for now. That's pretty much it.

**Pull request merged**
