### PR TITLE
[Python] Fix bug of test files about packageName

### PR DESCRIPTION
**Pull request by taxpon**
PR for issue #3055

### CODE REVIEW

**Comment by wing328** [comment]
@taxpon thank you for the prompt fix.

cc @scottrw93

**Comment by wing328** [comment]
@taxpon I ran the Python tests manually and got the following errors
```
Ran 72 tests in 28.408s

FAILED (errors=1)
ERROR: InvocationError: '/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/python/.tox/py34/bin/nosetests'
______________________________________________________ summary ______________________________________________________
  py27: commands succeeded
ERROR:   py34: commands failed
```
Here are the commands to reproduce:
```
samples/client/petstore/python
virtualenv venv
source venv/bin/activate
./test_python2_and_3.sh
```

**Comment by taxpon** [comment]
@wing328 When I ran the same tests on my machine, I got following result successfully:

```
  py27: commands succeeded
  py34: commands succeeded
  congratulations :)
```

I guess your `InvocationError` is caused by `.tox` in your machine (and `.tox` directory is ignored by git).

**Comment by taxpon** [comment]
@wing328 I've also omit `venv` directory and  `.python-version` file from git management in df11034.

**Comment by wing328** [comment]
Thanks @taxpon. I did another test with the lateat and all test cases passed:
```
______________________________________________________ summary ______________________________________________________
  py27: commands succeeded
  py34: commands succeeded
  congratulations :)
```

**Pull request merged**
