### PR TITLE
add support for relative path in specs files for SpringMVC.   

### PR DESCRIPTION
**Pull request by YaoYao-dd**
### PR checklist
when we define basePath in spec like this   petstore/v2,   it normally means in the web container,   petstore is the context path,  v2  is global  relative path for all resource path.  so it is good to generate API with this relative path for @RequestMapping(value = "/v2/dogs"),   also it is better to define the controller level  mapping since controller is resource based.

- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@beingcoder thanks for the PR. Please use 4-space instead for code indentation in the Java files.

**Comment by beingcoder** [comment]
@wing328   ,  adjusted the format,  thx.

**Comment by wing328** [comment]
@beingcoder there are still tabs in the Java files.

Please provide an example and retarget this for 2.3.0 branch instead as it might be a breaking change.

**Comment by wing328** [comment]
cc @cbornet

**Comment by cbornet** [comment]
I'm not sure I understand what this does and I'm not sure I agree with it...

**Pull request closed without merging**
