### PR TITLE
Issue 9926

### PR DESCRIPTION
**Pull request by mitchnull**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

implement issue #9926 ("parentContainer" property). Add "itemsDepth" property for proper nested variable name creation in templates (without shadowing violations).

### CODE REVIEW

**Comment by mitchnull** [comment]
Erm, how can I add a reviewer?  Any chance of this getting merged?

**Comment by HugoMario** [comment]
Hi @mitchnull, i can help with review, thanks a lot for PR btw!

**Comment by mitchnull** [comment]
> Hi @mitchnull, i can help with review, thanks a lot for PR btw!

Hello,

 Thanks!  Let me know what are the next steps to take with this.

cheers,
mitch

**Comment by HugoMario** [comment]
The PR looks good to me, i don't see this could affect current output code from generators, i just have one doubt, why `public CodegenModel parentModel` is not working for what you need on #9926 ?

**Comment by mitchnull** [comment]
TBH, I haven't  found parentModel when I tried to solve my problem, I'll check it now...  At a quick glance it seems to only work for polymorphic models.  The parentContainer is set when the parent is just a plain List or Map, like with this model:

ArrOfString:
  type: array
  items:
    type: string

I believe parentModel doesn't help with the above case.  Also, I still need the itemsDepth for the variable-declarations to avoid shadowing.

**Comment by HugoMario** [comment]
got it, thanks again for PR!

**Pull request merged**
