### PR TITLE
Refine CXF Add Spring Annotation-Config + Jboss flag for CXF/Resteasy + fix OuterEnum

### PR DESCRIPTION
**Pull request by jfiala**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
> updated server/petstore/jaxrs-cxf and created client/petstore/jaxrs-cxf

- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

see #4088 for cxf improvements
see #4160 + #3859 for cxf enumOuterClass.mustache fix

former PR see #4147 (closed as showed all changes from master)

### CODE REVIEW

**Comment by jfiala** [comment]
@wing328 pls check (details are in the issue #4088), you can merge if everything is alright.
Sorry for the second PR, but it always after I do a rebase on my branch the PR shows all my changes + all changes to the origin/master, if I create a new PR everything is clean again.

**Comment by jfiala** [comment]
@wing328 the samples for server/petstore/jaxrs-cxf are outdated (and source folder is gen/java instead of new src/gen/java) and client/jaxrs-cxf is missing. Shall I re-generate both languages and commit?
I assume you want to have the files generated with default-options. 
Should I also create an additional folder with all flags active to have a showcase for this as well?

**Comment by jfiala** [comment]
@wing328 updated samples/petstore for jaxrs-cxf and added the new client/petstore/jars-cxf + verified both compile.

For the API-tests I had to comment the invocation and assertion as there is a problem with the uploadFile-test of PetApiTest.java because java.io.File is used instead of org.apache.cxf.jaxrs.ext.multipart.Attachment. But I think this should be better solved in a separate issue, then we can also invoke the tests of the generated methods and thus ensure the generated tests are actually running.

**Comment by wing328** [comment]
I'll review this weekend and let you know if I've any question.

**Comment by jfiala** [comment]
@wing328 also added CLI-flag useSwaggerUI to allow SwaggerUI to be used immediately.

**Comment by wing328** [comment]
@jfiala I went through all the changes, which look good to me. Thanks for the contribution.

**Pull request merged**
