### PR TITLE
Swift3 Clener template of client methods

### PR DESCRIPTION
**Pull request by tomekc**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixed an error which in some cases could lead to generate improper API function, for example not uploading files.

Done a little makeover of `api.mustache`. Limited capabilities of mustache templates led to extremely convoluted and hardly comprehensible templates. 

The template has been reformatted a little, added a couple of newlines, as I believe that readibility of template is much more important than resulting code having a couple extra newlines.

I tested on following use-cases, created privately against httpbin.org:

* upload a file with one more form param and query params
* POST an object with query params
* GET with couple of parameters

### CODE REVIEW

**Comment by wing328** [comment]
@tomekc thanks for the PR. Please run `./bin/swift3-petstore.sh` to update Petstore sample (swift3).

**Comment by tomekc** [comment]
@wing328 It is updated, I forgot `git push` ;-)

BTW Travis checks failed for no reason, and it fixed itself after just updating the PR. I hope it will succeed this time...

**Comment by wing328** [comment]
@tomekc when I ran the integration test for Swift 3 (default), I got the following errors:
```
Testing failed:
	Cannot convert value of type 'Error?' to expected argument type 'ErrorResponse?'
** TEST FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/williamcheng/Code/jan2017/swagger-codegen/samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

Did you get similar error when running the test locally?

**Comment by tomekc** [comment]
`swagger-codegen/samples/client/petstore/swift3/default/SwaggerClientTests|swift3_parameters_cleanup⚡
$`

`mvn clean integration-test`

Result:

```
Test Suite 'UserAPITests' passed at 2017-01-13 19:06:18.611.
	 Executed 5 tests, with 0 failures (0 unexpected) in 1.364 (1.367) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2017-01-13 19:06:18.611.
	 Executed 12 tests, with 0 failures (0 unexpected) in 3.372 (3.379) seconds
Test Suite 'All tests' passed at 2017-01-13 19:06:18.612.
	 Executed 12 tests, with 0 failures (0 unexpected) in 3.372 (3.380) seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 20.253 s
[INFO] Finished at: 2017-01-13T19:06:18+01:00
[INFO] Final Memory: 10M/304M
[INFO] ------------------------------------------------------------------------
```

**Comment by wing328** [comment]
@tomekc that's good. Probably issue with my local environment.

cc @jgavris @jaz-ah @Edubits @hexelon

**Comment by jaz-ah** [comment]
+1 @wing328

**Comment by wing328** [comment]
I did another clone and got good test results:
```
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' passed (0.432 seconds).
Test Suite 'UserAPITests' passed at 2017-01-16 00:00:12.691.
	 Executed 5 tests, with 0 failures (0 unexpected) in 2.176 (2.181) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2017-01-16 00:00:12.695.
	 Executed 12 tests, with 0 failures (0 unexpected) in 5.876 (5.894) seconds
Test Suite 'All tests' passed at 2017-01-16 00:00:12.697.
	 Executed 12 tests, with 0 failures (0 unexpected) in 5.876 (5.897) seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:12 min
[INFO] Finished at: 2017-01-16T00:00:12+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
