### PR TITLE
[typescirpt-angular2] fix bug of InjectionToken importing in variables.ts

### PR DESCRIPTION
**Pull request by taxpon**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
- Issue #5709

### CODE REVIEW

**Comment by wing328** [comment]
@taxpon thanks for the fix. When I perform "npm install" in `samples/client/petstore/typescript-angular2/npm`, I got the following errors:
```
api/PetApi.ts(208,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
api/PetApi.ts(264,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
api/PetApi.ts(315,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
api/PetApi.ts(366,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
api/PetApi.ts(459,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
api/PetApi.ts(515,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
api/PetApi.ts(578,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.
variables.ts(1,10): error TS2305: Module '"/private/tmp/swagger-codegen/samples/client/petstore/typescript-angular2/npm/node_modules/@angular/core/index"' has no exported member 'InjectionToken'.
```

Did you get similar errors when running `npm install` locally in `samples/client/petstore/typescript-angular2/npm`?

**Comment by kirpit** [comment]
Also related: #5652.

**Comment by taxpon** [comment]
@wing328 @kirpit Oh, angular version in generated package.json is `"@angular/core": "^2.0.0-rc.5"` which does not have `InvectionToken` yet. So we need to change angular (and dependencies) version in package.json based on `useOpaqueToken` option, do we? It is possible to make some confusion for developers. What do you think? Related discussion: #5570

**Comment by taxpon** [comment]
@wing328 Regarding this error (`api/PetApi.ts(208,19): error TS2349: Cannot invoke an expression whose type lacks a call signature.`), when I updated typescript version in pacakge.json to `^2.0.0` those error disappeared all. So I think we should update typescript's version in package.mustache from `^1.8.10` to the latest stable.

**Comment by wing328** [comment]
@taxpon thanks for the details. What about "moving" the support of 'InjectionToken' to 2.3.0 branch instead to allow breaking changes?

1. roll back https://github.com/swagger-api/swagger-codegen/pull/5569
2. file https://github.com/swagger-api/swagger-codegen/pull/5569 against 2.3.0 instead
3. as part of this PR, update typescript o version ^2.0.0 and angular to new version that supports InjectionToken

**Comment by taxpon** [comment]
@wing328 I agree with your idea. OK, so I will update angular version and typescript version in package.mustache in that new PR. Sorry for bothering you.

**Comment by wing328** [comment]
@taxpon not at all. I'm sure the community appreciates your contributions to Swagger Codegen.

**Comment by wing328** [comment]
@taxpon I'll do 1 & 2 tomorrow and let you know if I need any help.

1. roll back #5569
2. file #5569 against 2.3.0 instead

**Comment by wing328** [comment]
1. Done via https://github.com/swagger-api/swagger-codegen/pull/5868
2. Done via https://github.com/swagger-api/swagger-codegen/pull/5869

@taxpon Please kindly take a look when you've time.

**Pull request closed without merging**
