### PR TITLE
[JAXRS-Spec|Resteasy|CXF] Issue 4315 - Fixed bug generating arrays of enums

### LINKED ISSUE #4315: [jaxrs-(resteasy|spec)] Bug generating arrays of enums
##### Description

Objects with a property that is an array of enums generates code that does not compile with server JAXRS code generation.

Client code generation (at least the default -l java configuration) does not have the same issue.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

```yaml
EnumArrayTest:
  type: object
  properties:
    enums:
      type: array
      items:
        type: string
        enum:
          - test1
          - test2
```

```java
public class EnumArrayTest   {


  /**
   * Gets or Sets enums
   */
  public enum List&lt;EnumsEnum&gt; {
    TEST1("test1"),

        TEST2("test2"),
    private List&lt;String&gt; value;

    List&lt;EnumsEnum&gt;(List&lt;String&gt; value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
  }


  /**
   * Gets or Sets enums
   */
  public enum EnumsEnum {
    TEST1("test1"),

        TEST2("test2"),
    private String value;

    EnumsEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }
  }

  private List<EnumsEnum> enums = new ArrayList<EnumsEnum>();
```

##### Command line used for generation

swagger-codegen generate -i swagger.yaml -l jaxrs-resteasy -o server-resteasy/

##### Steps to reproduce

Use yaml from above.
Generate -l jaxrs-resteasy using command from above.

### PR DESCRIPTION
**Pull request by markus-wa**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixes #4315

### CODE REVIEW

**Comment by jfiala** [comment]
@markus-wa Your changes currently don't reflect any changes in the generated code, can you check if you can provide a sample contract for this so we have a test as well (or enhance an existing contract, pls ask @wing328 for assistance)?

**Comment by markus-wa** [comment]
@wing328 I could certainly add an attribute like 'roles' as enum array to https://github.com/swagger-api/swagger-codegen/blob/master/samples/yaml/user.yml#L153 if you are ok with that.

Or would you prefer a new contract?

**Comment by markus-wa** [comment]
I actually noticed https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml exists and is used by various other sample generation scripts.

Any reason not to switch to this one?

**Comment by markus-wa** [comment]
Hmm, I only switched the sample contract for CXF & spec for now.

Resteasy generates other non compiling code unrelated to this issue.

One reason is enumOuterClass.mustache being seriously broken and the other is missing HashMap imports.

**Comment by wing328** [comment]
> Any reason not to switch to this one?

petstore-with-fake-endpoints-models-for-testing.yaml contains a lot more edge cases that not *all* generators can handle. Also we add new test cases to petstore-with-fake-endpoints-models-for-testing.yaml  from time to time to cover new edge cases reported by the community so currently only generators with active contribution from the community is using it

Ideally we want all generators to use it so as to cover all edge cases we've discovered so far.

**Comment by wing328** [comment]
If no one has further question or feedback on this PR, I'll merge it in the coming weekend.

**Pull request merged**
