### PR TITLE
Fix some go client formatting issues #3518

### PR DESCRIPTION
**Pull request by bvwells**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@antihax 

### Description of the PR

Make go client generated code conform to go formatting standards as part of #3518 (see https://github.com/golang/go/wiki/CodeReviewComments)
 - New lines at end of file.
 - Removal of superfluous lines.

Running
```
gofmt -w .
```
on generated code should not change formatting. Note, there is still some issue with ordering of go imports.

### CODE REVIEW

**Comment by antihax** [comment]
Looks good. Thanks.

**Comment by bvwells** [comment]
Thanks @antihax!

**Comment by wing328** [comment]
@bvwells thanks for the PR. I've merged another PR (https://github.com/swagger-api/swagger-codegen/pull/7283) to improve Go client's code format. Please take a look.

For this PR, please resolve the merge conflicts when you've time.

**Comment by wing328** [comment]
@bvwells please file a new PR if needed. Thanks.

**Comment by bvwells** [comment]
@wing328 no problems. I actually looked at merging this PR last night, but my synced master branch wasn't building. Must have synced to a dodgy build.

**Pull request closed without merging**
