### PR TITLE
Add port 80 to swagger spec

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Add port 80 to Swagger spec so as to ensure the port is shown correctly in the auto-generated code/doc.

### CODE REVIEW

**Comment by ePaul** [comment]
Shouldn't port 80 be the default for HTTP, i.e. shouldn't mentioning it be superfluous?

**Comment by wing328** [comment]
@ePaul I remember there was an issue the port number was not captured in {{host}} so that's why I put 80 there to ensure the port number is there.

Ideally we should write a unit test to ensure `:80` is part of the host.

**Comment by ePaul** [comment]
I updated the samples (in #5243), the diff might show the relevant places (potentially where we have 8080 → 80?).

**Comment by wing328** [comment]
@ePaul thanks! Later I'l add a Java test case as well.

> (potentially where we have 8080 → 80?).

Not something I would expect.

**Pull request merged**
