### PR TITLE
[Java][JAX-RS] Fix pom in jaxrs-cxf-cdi

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Update JAXRS-CXF-CDI pom.xml to avoid downloading the latest pre-release of io.swagger annotation lib.

### CODE REVIEW

**Comment by wing328** [comment]
cc @ nickcmaynard

**Comment by nickcmaynard** [comment]
@wing328 I'll admit I'm confused.  The rules `[1.5.3,2)` should have excluded anything beginning with 2... which prereleases were being installed?

**Comment by nickcmaynard** [comment]
Hmm.  It's possible this should have been `[1.5.3,2.0)` - according to https://cwiki.apache.org/confluence/display/MAVENOLD/Dependency+Mediation+and+Conflict+Resolution#DependencyMediationandConflictResolution-DependencyVersionRanges only the revision part is optional.

**Comment by wing328** [comment]
> which prereleases were being installed?

Should be this one: https://mvnrepository.com/artifact/io.swagger/swagger-annotations/2.0.0-rc1

You should be able to repeat the issue by updating pom.xml to use `[1.5.3,2)`

**Pull request merged**
