### PR TITLE
unicode type forgotten in api_client.mustache for python

### PR DESCRIPTION
**Pull request by DariusMR**

### CODE REVIEW

**Comment by wing328** [comment]
@DariusMR thanks for the PR. There're merge conflicts. Please kindly rebase on the latest master.

**Comment by DariusMR** [comment]
hi
I've rebased on the latest master and all checks have passed

**Comment by wing328** [comment]
@DariusMR thanks. Is it correct to say that the change (unicode) works for both Python 2.x and Python 3.x?

**Comment by DariusMR** [comment]
I don't think so because literal strings are unicode by default in Python3.

**Comment by wing328** [comment]
@DariusMR is there a way to make the change compatible with both Python 2.x and Python 3.x? Ideally we want to maintain one single Python client for Python 2.x and Python 3.x

**Comment by DariusMR** [comment]
I think it's to hard to do that :
*A non-exhaustive list of features which are only available in 3.x releases and won't be backported to the 2.x series:*
    strings are Unicode by default
    clean Unicode/bytes separation
    exception chaining
    function annotations
    syntax for keyword-only arguments
    extended tuple unpacking
    non-local variable declarations
source : https://wiki.python.org/moin/Python2orPython3

**Comment by wing328** [comment]
@DariusMR can you share the swagger spec for repeating the issue fixed by this PR?

**Comment by DariusMR** [comment]
yes of course : 
http://beta.app.mapotempo.com/api/swagger_doc
https://app.mapotempo.com/api/swagger_doc

**Comment by wing328** [comment]
@DariusMR thanks. We'll look into that.

Our goal is to generate a Python API client that works with Python 2.x and Python 3.x, and it should be doable, e.g. [Dropbox Python SDK](https://github.com/dropbox/dropbox-sdk-python)

**Comment by DariusMR** [comment]
ok ok
and do you want to do with this commit ? Before the future Python API client ? Will you take this commit ?

**Comment by wing328** [comment]
If this commit would break Python 3.x, then we should look for better solution that works with both Python 2.x and Python 3.x

**Comment by geekerzp** [comment]
@DariusMR I think you can do this for compatibility:
```python
import sys

if sys.version_info >= (3,0):
    unicode = str
```

So the code:
```
isinstance(obj, (str, int, float, bool, tuple, unicode))
```
will work in both python2 and python3.

**Comment by frodrigo** [comment]
`unicode` is a python 2 specific type, in python 2 there is also `str`, but in python 3 only `str`.

**Comment by DariusMR** [comment]
Here is a version which is both python2 and python3 compatible

**Comment by wing328** [comment]
@DariusMR thanks. We'll review and merge accordingly.

**Pull request merged**
