### PR TITLE
[aspnetcore] Fix string enum generation

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

fixes regression in generation of string enums. see #7564

### CODE REVIEW

**Comment by jaz-ah** [comment]
+1 LGTM

**Comment by jimschubert** [comment]
/cc wing328 as well

This change essentially makes aspnetcore enum template match the C# client template.

**Comment by wing328** [comment]
cc @knom as well who has been making quite a lot of enhancements to ASP.NET core generator.

**Pull request merged**
