### PR TITLE
fix to Go client template to address localVarFile error

### PR DESCRIPTION
**Pull request by psaffrey-origami**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is a recapitulation of https://github.com/swagger-api/swagger-codegen/pull/8051 which seems to have gone nearly all the way to being merged. It's such a small change it seemed easier to recreate it from an up-to-date copy of `master`.

The PR addresses https://github.com/swagger-api/swagger-codegen/issues/9431 - following the instructions in that issue should show the bug in master and how this PR provides a fix.

This is my first PR against swagger-codegen so happy to hear any suggestions or comments. I'd like to use swagger-codegen in a project and need this fix to avoid having to use a non-standard version.

### CODE REVIEW

**Comment by HugoMario** [comment]
@psaffrey-origami, thanks for PR, once jenkins completes its tasks i'll merge the PR

**Comment by danny-cheung** [comment]
Any luck getting this PR merged?
This bugs means that the generated code doesn't compile and can't be run.

**Comment by danny-cheung** [comment]
@HugoMario is there anything stopping this PR from being merged?

**Comment by HugoMario** [comment]
Hi @danny-cheung , sorry for delay, i had missed this one, sorry about it :/

**Pull request merged**
