### PR TITLE
replaced SWG by {{classPrefix}}

### PR DESCRIPTION
**Pull request by patulacci**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Replaced SWG by classPrefix instead

### CODE REVIEW

**Comment by wing328** [comment]
@patulacci thanks for the PR. Do we also need to do the same for ApiClient-body.mustache?
```
modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache:        SWGJSONRequestSerializer * swgjsonRequestSerializer = [SWGJSONRequestSerializer serializer];
modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache:        _requestSerializerForContentType = @{kSWGApplicationJSONType : swgjsonRequestSerializer,
modules/swagger-codegen/src/main/resources/objc/ApiClient-body.mustache:    __weak id<SWGSanitizer> sanitizer = self.sanitizer;
```

**Comment by wing328** [comment]
Please also run `./bin/objc-petstore-all.sh` to update ObjC Petstore sample.

**Comment by wing328** [comment]
To fix https://github.com/swagger-api/swagger-codegen/issues/4865

**Comment by patulacci** [comment]
Sorry, I fixed it in a new pull request

**Comment by wing328** [comment]
> Sorry, I fixed it in a new pull request

That's perfectly fine 😄 We'll review that as well.

**Comment by wing328** [comment]
I believe this is no longer needed as https://github.com/swagger-api/swagger-codegen/pull/4871 has been merged into master.

**Pull request closed without merging**
