### PR TITLE
Adds comments to TypeScript Generator

### LINKED ISSUE #1504: TypeScript and Comments
I think one could add comments to TypeScript generators. I will do a pull request if desired

### PR DESCRIPTION
**Pull request by aersamkull**
Resolves #1504

### CODE REVIEW

**Comment by wing328** [comment]
@aersamkull thanks for the PR. Do you mind running the following commands to update the TypeScript Petstore samples?
```
./bin/typescript-angular-petstore.sh
./bin/typescript-node-petstore.s
```

**Comment by aersamkull** [comment]
I did, it seems to work. I have run "npm test" in both written directories

**Comment by wing328** [comment]
Have you done a "git commit -a" to update the petstore sample for typescript (angular, node)?

I only saw 2 files updated and I expected some files under `samples/client/petstore/typescript-node` and `samples/client/petstore/typescript-angular` updated with the additional comments you've put in.

**Comment by aersamkull** [comment]
Ah, ok, I'll do that and commit a new pull request.

**Pull request closed without merging**
