### PR TITLE
[C#] RootNamespace/AssemblyName use packageName

### PR DESCRIPTION
**Pull request by jimschubert**
Uses packageName instead of packageTitle for `RootNamespace` and
`AssemblyName` in the C# generate client project. packageTitle is intended
to add additional information to AssemblyInfo.cs, and changing
packageTitle to non-FQN text breaks adding new files to the project.

packageTitle, per CodegenConstants description:

> Specifies an AssemblyTitle for the .NET Framework global assembly attributes stored in the AssemblyInfo file.

see #3441

### CODE REVIEW

**Comment by wing328** [comment]
@jimschubert thanks for the PR, which has been merged into master.

Shall we do the same for NancyFx? https://github.com/swagger-api/swagger-codegen/blob/61015488d2911bfaba9aa9277072112d1c48e81f/modules/swagger-codegen/src/main/resources/nancyfx/Project.mustache#L10

cc @mstefaniuk

**Comment by jimschubert** [comment]
Yeah, I think it would make more sense to follow the practice of naming assemblies consistently with the namespace rather than some freeform text. For some reason, I thought NancyFX was written for .NET Core, so I didn't think to check its project file.

**Comment by wing328** [comment]
OK. I'll fix it in my work-in-progress C# PR.

**Comment by wing328** [comment]
For NancyFX, I've submitted https://github.com/swagger-api/swagger-codegen/pull/3449

**Pull request merged**
