### PR TITLE
Add support for Java8 adapter when using retrofit2

### PR DESCRIPTION
**Pull request by palmithor**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
Added support for returning CompletableFuture<T> when generating Retrofit2 clients. Note that it requires java8 to be included which can be seen in the json configuration file which is used by the shell script.

All tests run and the *-petstore.sh file works.

### CODE REVIEW

**Comment by palmithor** [comment]
It seems like test fails due to a password prompt, anyone who knows how to fix this?

**Comment by palmithor** [comment]
@wing328 Do you know how I can fix the travis build?  It seems like it get's stuck on a password prompt. I've already tried to merge the upstream and it didn't fix it...

**Comment by wing328** [comment]
I've resolved the merge conflicts. Let's see how the CI tests go.

cc @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet for review.

**Comment by lukoyanov** [comment]
LGTM.

**Comment by palmithor** [comment]
Do I close the PR or do you do it when you merge it?

**Comment by wing328** [comment]
@palmithor I'm actually do some checks now. Will merge later if everything looks good.

**Comment by wing328** [comment]
Btw, we'll mark this as a breaking change as `doNotUseRx` has been renamed to `useRetrofitCall`

**Comment by wing328** [comment]
@palmithor looks like the change breaks the Java (Retrofit2) client. Here are the error message (partial) after updating the Retrofit2 Petstore sample:
```
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/StoreApi.java:[56,21] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[25,20] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[36,35] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[47,34] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[58,20] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[69,23] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[81,21] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[91,20] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/UserApi.java:[102,20] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/FakeClassnameTags123Api.java:[28,25] <identifier> expected
[ERROR] /home/ubuntu/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/api/AnotherFakeApi.java:[28,27] <identifier> expected
```
Ref: https://circleci.com/gh/swagger-api/swagger-codegen/2467

Please run "./bin/java-petstore-retrofit2-all.sh" to update Retrofit2-related Pestore samples and include your new script in "./bin/java-petstore-retrofit2-all.sh"

**Comment by wing328** [comment]
@palmithor may I know if you need help fixing the errors?

**Comment by palmithor** [comment]
I've had a lot on my plate recently. If you're interested in helping out I could add you as a contributor on my fork ?

**Pull request closed without merging**
