### PR TITLE
[C#] add test case, update c# model constructor

### PR DESCRIPTION
**Pull request by wing328**
- add test cases for readonly property and deserialization
- update constructor to include non-readonly parameters

### CODE REVIEW

**Comment by wing328** [comment]
Updated the PR to add required property check to `aspnet5` model constructor.

cc @jimschubert

**Comment by jimschubert** [comment]
The serialization with read-only properties and private setters was my big concern. Looks like `order.Id` in the test covers that and works. Thanks.

**Comment by wing328** [comment]
@jimschubert thanks for reviewing the change. PR merged.

**Comment by wing328** [comment]
**Upgrade note from 2.1.5 to 2.1.6**

Starting from 2.1.6, one must provide all the required parameters when creating a model. Otherwise, an exception will be thrown. In addition, `readOnly` parameters (which should not be set with any value) will be removed from the constructor.
 
```
			Pet p = new Pet(Name: "Csharp test", PhotoUrls: new List<string> { "http://petstore.com/csharp_test" });
```

**Pull request merged**
