### PR TITLE
change the host name as a global

### PR DESCRIPTION
**Pull request by mesteve**
Hi guys,

I just made a modification on the "basePath" under the android folder in order to be able to set it at the beginning of your initialization so you just have to set it once.

Thanks,
mesteve

### CODE REVIEW

**Comment by wing328** [comment]
@mesteve thanks for the PR. In the commit tab, it shows that your commit is not linked to your github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors. You may want to fix that.

I think your PR will make your life easier to set all API class using the same `basePath` while there may be other use cases in which API classes use different `basePath`.

cc @Shyri

**Comment by mesteve** [comment]
I see my account in the PR tab.

**Comment by wing328** [comment]
It's not linked to your github account. You can compare other PRs.

**Comment by wing328** [comment]
@mesteve thanks for the PR but we'll keep the current approach so that the API client can talk to endpoints with different base path.

**Pull request closed without merging**
