### PR TITLE
Fix package name for generator/online/Generator.java

### LINKED ISSUE #833: Wrong package in the project
Why Generator.java is under the package com.wordnik.swagger.generator.online but in the file is declared:

package com.wordnik.swagger.online;

I can't understand it

### PR DESCRIPTION
**Pull request by xhh**
fix #833

### CODE REVIEW

**Comment by webron** [comment]
@xhh - looks like the test needs to be updated as well.

**Comment by xhh** [comment]
@webron ah, apologies. i'm having to go out right now, will try to fix it later.

**Comment by webron** [comment]
No worries, I may do it manually as I'm going to make a change that would affect all code and would require rebasing of existing PRs.

**Comment by xhh** [comment]
@webron thanks, but i just fixed it

**Comment by webron** [comment]
Awesome, thanks a bunch!

**Pull request merged**
