### PR TITLE
[JaxRS]Show correct default value on CLI option description

### LINKED ISSUE #3861: [JAVA/jaxrs] Which is the actual default library template? jersey1 or jersey2
##### Description

When I print jaxrs config options by `swagger-codegen config-help -l jaxrs`, it outputs 
```
	library
	    library template (sub-template) to use (Default: jersey1)
	        jersey1 - Jersey core 1.x
	        jersey2 - Jersey core 2.x (default)
``` 
Which one is the actual default?

##### Swagger-codegen version

2.2.0 installed via Homebrew

##### Command line used for generation

`swagger-codegen config-help -l jaxrs`

##### Steps to reproduce

`swagger-codegen config-help -l jaxrs`

##### Suggest a Fix

Replace this line to jersery2
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java#L35

possibly also removing 
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JavaJerseyServerCodegen.java#L74-L77

if the default is jersey2?

### PR DESCRIPTION
**Pull request by y-higuchi**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixed jaxrs cli option handling to print correct default library template.

Fixes #3861

### CODE REVIEW

**Comment by y-higuchi** [comment]
After running ./bin/jaxrs-petstore-server.sh

I've notices `^M` in generated code, and it seems to be caused by `modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache`.

Is it OK for it to be CRLF? or should `api.mustache` be fixed to LF

**Comment by wing328** [comment]
@y-higuchi I did a search for `^M` (ctrl V + ctrl M in vim) but couldn't find it in `modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache`. 

Can you tell me which line(s) you found `^M`?

**Comment by wing328** [comment]
(btw, I'm using latest master to check so please pull the latest master if you've not done so)

**Comment by y-higuchi** [comment]
I'm on fedb0cc35226fc1f47094fa53a9b3bc72a574fb6 so I think I'm on the latest master, but I am getting:

```
$ file modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache
modules/swagger-codegen/src/main/resources/JavaJaxRS/api.mustache: ASCII Java program text, with CRLF line terminators
```

Looking with Atom editor, it seems all lines in that file is CRLF

**Comment by wing328** [comment]
OK. I'll take another look using another editor.

Your change looks good. Thanks for the contribution :)

**Comment by wing328** [comment]
I'm able to locate those ^M and will file a PR to clean those up this weekend. 

I'll also do a grep on all auto-generated code to ensure there's no ^M.

Thanks for spotting the issue.

**Comment by wing328** [comment]
@y-higuchi UPDATE: I've filed https://github.com/swagger-api/swagger-codegen/pull/3865 to fix the line breaks.

**Comment by wing328** [comment]
FYI. https://github.com/swagger-api/swagger-codegen/pull/4526 to detect the issue moving forward.

**Pull request merged**
