### PR TITLE
add enums to Java Spring path, query, and header params

### PR DESCRIPTION
**Pull request by thebignet**
Enums in header, query or path parameters where not generated as enums for Java Spring.

Inline enums are used for each api operation.

### CODE REVIEW

**Comment by cbornet** [comment]
Can you generate the samples ?

**Comment by thebignet** [comment]
Do you have a command for generating samples ?  I don't think that it is documented

**Comment by cbornet** [comment]
```bin/springboot-petstore-server.sh```

**Comment by thebignet** [comment]
Samples stayed the same.  In samples, enums in parameters are wrapped in lists.  Changes so far only generate java enum if params are enums.  Could use some help to make it work for enums wrapped in lists

**Comment by wing328** [comment]
@thebignet coincidentally I'm working on better enum support for list (or list of list) and map (or map of map). Stay tuned.

**Comment by wing328** [comment]
UPDATE: I've filed #3199 to support array/map (any dimensions) of enum (for C# in particular)

**Comment by wing328** [comment]
@thebignet about updating the Petstore sample or testing the change, please refer to https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md#testing for more information.

**Comment by radik-sabirov** [comment]
About "files changed"...
I think that it's not good idea to add inner enum to api.mustache. It will work if you have only one path in your api class. In other words you will have the same enum in this api class after each path (endpoint).
Need to add one enum model and use it in api.mustache

**Comment by wing328** [comment]
@radik-sabirov I agree that defining the enum as model so that it can be reused by different endpoints or model properties but that's up to the spec owner on how they define the enum (using enum model or inline)

**Comment by radik-sabirov** [comment]
@wing328 
I've solved this issue and it works for me.
What I did:

model.mustache
added 
```
{{#models}}
 {{#model}}{{#isEnum}}{{>modelEnum}}{{/isEnum}}{{^isEnum}}{{#description}}
...
{{/isEnum}}
  {{/model}}
{{/models}}
```
This template can create enum if it is enum...

created new modelEnum.mustache
```
 /**
 * {{^description}}{{{name}}}{{/description}}{{#description}}{{{description}}}{{/description}}
 */
 public enum {{#datatypeWithEnum}}{{.}}{{/datatypeWithEnum}}{{^datatypeWithEnum}}{{classname}}{{/datatypeWithEnum}} {
   {{#allowableValues}}{{.}}{{^-last}} , {{/-last}}{{#-last}};{{/-last}}{{/allowableValues}}
 }
```
About pathParams.mustache and queryParams.mustache 
I've added this
```
...
@ApiParam(value = "{{{description}}}"{{#required}},required=true{{/required}}{{#allowableValues}}, allowableValues="{{#allowableValues}}{{#values}}{{.}}{{^-last}} , {{/-last}}{{#-last}}{{/-last}}{{/values}}{{/allowableValues}}"{{/allowableValues}} {{#defaultValue}}, defaultValue="{{{defaultValue}}}"{{/defaultValue}}) @PathVariable("{{paramName}}") {{#isEnum}}{{datatypeWithEnum}}{{/isEnum}}{{^isEnum}}{{{dataType}}}{{/isEnum}} {{paramName}}
...
```

service.mustache
```
...
ResponseEntity<{{>returnTypes}}> {{operationId}}({{#allParams}}{{#isEnum}}{{datatypeWithEnum}}{{/isEnum}}{{^isEnum}}{{{dataType}}}{{/isEnum}} {{paramName}}{{#hasMore}},
      {{/hasMore}}{{/allParams}});
{{/operation}}
```

**Comment by thebignet** [comment]
Can you make a PR for this ?  I'd be interested in testing it.

**Comment by wing328** [comment]
@radik-sabirov may I know if you've cycle to submit a PR with the enhancement?

**Comment by TehBakker** [comment]
Any news on that?

**Comment by thebignet** [comment]
Closed for inactivity

**Pull request closed without merging**
