### PR TITLE
[qt5cpp] Remove qt5 pro.user file

### PR DESCRIPTION
**Pull request by MartinDelille**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Qt5 project specific user preferencies shouldn't be versioned. This PR removes it.

Ping @ravinikam @stkrwork @fvarose @etherealjoy

### CODE REVIEW

**Comment by etherealjoy** [comment]
I think it is a good idea. but is this filed used somewhere in the ci process?

**Comment by stkrwork** [comment]
the failure in circleci has nothing to do with your change

**Comment by etherealjoy** [comment]
Then it is OK for me.

**Comment by wing328** [comment]
Currently, there's no CI tests setup for QT5 C++ petstore client. (previously I tested it locally in my Mac) We definitely welcome contributions to set it up in the CI (Travis, CircleCI, Shippable or AppVeyor)

**Comment by MartinDelille** [comment]
I can do that. Can you give me an example of a test that is performed on another language ?

**Pull request merged**
