### PR TITLE
[TypeScript] Add CI for typescript API clients

### PR DESCRIPTION
**Pull request by wing328**
- [x] node (npm)
- [x] angular
- [ ] angular2
- [x] fetch

### CODE REVIEW

**Comment by wing328** [comment]
cc @leonyu to avoid duplicating the work.

**Comment by wing328** [comment]
CI tests for TS fetch API clients have been commented out due to the following errors:
```
Downloaded: http://repo.maven.apache.org/maven2/org/apache/commons/commons-exec/1.1/commons-exec-1.1.jar (52 KB at 827.6 KB/sec)
npm WARN optional dep failed, continuing fsevents@1.0.12

> typescript-fetch-test@1.0.0 prepublish /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default
> ./scripts/prepublish.sh


> typescript-fetch-api@0.0.0 prepublish /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/builds/default
> typings install && tsc


â”œâ”€â”€ core-js (ambient)
â”œâ”€â”€ isomorphic-fetch (ambient)
â””â”€â”€ node (ambient)

typescript-fetch-api@0.0.0 node_modules/typescript-fetch-api
â”œâ”€â”€ isomorphic-fetch@2.2.1 (whatwg-fetch@1.0.0, node-fetch@1.5.2)
â””â”€â”€ core-js@2.4.0

â”œâ”€â”€ chai (ambient)
â”œâ”€â”€ es6-promise (ambient)
â””â”€â”€ mocha (ambient)

ts-loader: Using typescript@1.8.10 and /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/tsconfig.json
Hash: ec7e72dfe6add9a95f6f
Version: webpack 1.13.0
Time: 1997ms
                          Asset    Size  Chunks             Chunk Names
  ./dist/test.webpack-bundle.js  216 kB       0  [emitted]  app
./dist/vendor.webpack-bundle.js  120 kB       1  [emitted]  vendor
   [0] multi vendor 28 bytes {1} [built]
    + 91 hidden modules
/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/node_modules/commondir/index.js:25
    }, files[0].split(/\/+|\\+/));
               ^

TypeError: Cannot read property 'split' of undefined
    at module.exports (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/node_modules/commondir/index.js:25:16)
    at Host._rootDir (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/lib/Host.js:130:16)
    at Tsifier.getCompiledFile (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/lib/Tsifier.js:273:27)
    at DestroyableTransform.flush [as _flush] (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/lib/Tsifier.js:261:24)
    at DestroyableTransform.<anonymous> (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:115:49)
    at DestroyableTransform.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at prefinish (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:465:12)
    at finishMaybe (/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/node_modules/tsify/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:473:7)

npm ERR! Linux 3.19.0-30-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! typescript-fetch-test@1.0.0 prepublish: `./scripts/prepublish.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the typescript-fetch-test@1.0.0 prepublish script './scripts/prepublish.sh'.
npm ERR! This is most likely a problem with the typescript-fetch-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/prepublish.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls typescript-fetch-test
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-fetch/tests/default/npm-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
```

We'll re-enable it later with another PR.

**Comment by wing328** [comment]
@leonyu if you've time, I wonder if you can look at the error message above to see if you've any clue what's the causing it.

**Comment by leonyu** [comment]
Will take a look tonight

**Comment by leonyu** [comment]
@wing328 #2973

**Pull request merged**
