### PR TITLE
[Swift] Handle binary data types

### PR DESCRIPTION
**Pull request by jgavris**

### CODE REVIEW

**Comment by wing328** [comment]
@jgavris thanks for the PR.

cc @Edubits @jaz-ah

**Comment by jgavris** [comment]
@wing328 @jaz-ah Any feedback here?

**Comment by Edubits** [comment]
Code looks good @jgavris

**Comment by jgavris** [comment]
Rebased again due to conflicts

**Comment by wing328** [comment]
@jgavris thanks for the quick rebase.

@Edubits thanks for reviewing the change.

**Pull request merged**
