### PR TITLE
[TypeScript] add an option to determine property naming convention

### PR DESCRIPTION
**Pull request by wing328**
Add 4 different naming conventions for Typescript model's property
- original
- camelCase (default)
- PascalCase
- snake_case

### CODE REVIEW

**Comment by fatbone008** [comment]
how to use these options? add the specificed type into CLI line? or in the yaml?

**Comment by wing328** [comment]
Yes, something like "--modelPropertyNaming=original" or "modelPropertyNaming" in the config file (JSON). Please refer to project's README on how to customize the output.

**Comment by abcox** [comment]
modelPropertyNaming: {'camelCase', 'PascalCase', 'snake_case' and 'original'}

**Comment by Matster2** [comment]
This doesn't appear to be an option in the generateAPI config. Is it available here or is there some other way to do this.
All my query paramaters start with uppercase and I would like to make them camelcase instead

**Pull request merged**
