### PR TITLE
[Spring][Issue-9820] Adding cookie parameter to operation for generation (3.0.13)

### PR DESCRIPTION
**Pull request by nataliaoliveira**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Issue: [https://github.com/swagger-api/swagger-codegen/issues/9820](https://github.com/swagger-api/swagger-codegen/issues/9820)

This change goes along with another change in swagger-codegen-generators. Please review PR https://github.com/swagger-api/swagger-codegen-generators/pull/524

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by nataliaoliveira** [comment]
@HugoMario @frantuma can you please check?

**Comment by frantuma** [comment]
Thanks for this! We are going to review in the next days

**Comment by nataliaoliveira** [comment]
Hi @frantuma! Any updates?

**Comment by frantuma** [comment]
Replaced this PR with #9869, which doesn't include the updated samples, which will be added in later release. Thanks a lot for your contribution here and in https://github.com/swagger-api/swagger-codegen-generators/pull/524 (included in swagger-api/swagger-codegen-generators/pull/543)

**Pull request closed without merging**
