### PR TITLE
[JAXRS-CXF] Issue 4569 - Re-added usage of contextPath in api.mustache (basePath)

### PR DESCRIPTION
**Pull request by markus-wa**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fix for #4569 - basePath was ignored for jaxrs-cxf

### CODE REVIEW

**Comment by wing328** [comment]
@markus-wa Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@jfiala please take a look at this PR when you've time.

**Comment by markus-wa** [comment]
I have added the email from the commit to my github account.

**Comment by jfiala** [comment]
@wing328 I removed this when I reworked the cxf template, because using the basePath in the @Path is not the usual configuration for CXF.
CXF uses spring and the basePath is configured in web.xml/spring configuration files:

@markus-wa
Please take a look at the generated web.xml file (with config generateSpringApplication=true)
``` 
<servlet-mapping>
        <servlet-name>CXFServiceServlet</servlet-name>
        <url-pattern>/rest/*</url-pattern>
    </servlet-mapping>
``` 
There the servlet mapping is done.

The next step is the JAXRS-server which is configured in Spring (see ApplicationContext.xml):
``` 
<jaxrs:server id="restServer" address="/services">
``` 
Here the services are now located at http://<servername>/<appcontext-name>/rest/services/<myservices>

The @Path(..) always is connected to the root ("/"), as there are already two other places where you can configure the servlet-mapping and the jaxrs:server-endpoint.

This is how I worked with the cxf language so far, other usages usually caused troubles with other features, so that was the most stable and also understandable solution to start with.

If you really need the basePath in @Path, I'd suggest to customize the template or if you think it makes really sense for the cxf-language, please also submit how the spring configuration should change in your opinion and verify all the features work (including swagger-ui, Swagger2Feature etc.).

**Comment by markus-wa** [comment]
Until now we have been using a single CxfNonSpringServlet for multiple services with different basePaths. The @Path seems to be the only option in this case as far as I'm aware.

I will get back to you with more details - maybe a command line option might be the way to go?

**Comment by jfiala** [comment]
@markus-wa I'm green with the CLI option, in fact the solution you proposed seems the cleaner way in JaxRS terms (contract -> jaxrs interface). You can also provide an alternative to the spring configuration I did by supporting a flag for the CxfNonSpringServlet, this would make it complete. Pls let me know if you need assistance in powering up the cxf language support...

**Comment by jfiala** [comment]
@markus-wa great, this looks good!

**Comment by jfiala** [comment]
for the generated samples, you generated them with the CLI flag turned on. In fact we would need a separate sample for all off (=default), one with all spring flags turned on and one with the generateNonSpringServlet turned on. @wing328  pls can you advise here how we should handle this in your opinion?

**Comment by markus-wa** [comment]
Woops, what happened here? https://travis-ci.org/swagger-api/swagger-codegen/jobs/195578396

**Comment by wing328** [comment]
@markus-wa I just pushed a fix to the latest master. Pls pull the latest to give it a try.

**Comment by wing328** [comment]
> @wing328 pls can you advise here how we should handle this in your opinion?

A good starting is by looking at the following 2 shell scripts:
[spring-delegate-j8.sh](https://github.com/swagger-api/swagger-codegen/blob/master/bin/spring-delegate-j8.sh#L29)
[spring-delegate.sh](https://github.com/swagger-api/swagger-codegen/blob/master/bin/spring-delegate.sh#L29)

The differences are the output folder (samples/server/petstore/springboot-delegate-j8) and the additional option (java8=true).

For your case, you can do something similar with the additional option `generateNonSpringServlet`.

If you want, I can do it later after merging this PR into master.

**Comment by markus-wa** [comment]
@jfiala @wing328 I've added the sample generation, let me know if i missed something.

**Comment by wing328** [comment]
@markus-wa I've resolved the merge conflicts and merge the changes into master. Thanks for your contribution.

**Pull request merged**
