### PR TITLE
Alternative swift code generator

### PR DESCRIPTION
**Pull request by mabedan**
I've decided to create a separate code generator for swift, given that the approach taken is very different than the existing swift code generator.

Main differentiation points:
- Handling for different response data type, per status code
- Usage of swift enums with associated values, for cleaner response callback parameters

Here are a few known issues:
- handling of NSDate in query parameters needs to be improved
- Inclusion of query parameters, in case there're body parameters as well
- Lack of unit tests
- possibility of class name collision, in case of generating multiple spec files. Could be solved by `pod`ification

Here's an example of spec file + generated swift files. [api](https://gist.github.com/mabedan/36549b524870b064beeb6785dba1f432#file-raygunapi-swift), [model](https://gist.github.com/mabedan/36549b524870b064beeb6785dba1f432#file-errordatamodel-swift), [spec](https://gist.github.com/mabedan/36549b524870b064beeb6785dba1f432#file-raygun-yaml)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by wing328** [comment]
cc @Edubits @jaz-ah

**Comment by wing328** [comment]
@mabedan if the current swift generator can achieve the following, do you agree we should just keep one Swift generator?
> Handling for different response data type, per status code
> Usage of swift enums with associated values, for cleaner response callback parameters

For `Handling for different response data type, per status code`, do you mean the response data type is different based on the status code? Can you share your Swagger spec with us?

For  `Usage of swift enums with associated values`, can you also share the spec for this and how that's represented in swift?

**Comment by mabedan** [comment]
> if the current swift generator can achieve the following, do you agree we should just keep one Swift generator?

The initial reason I started rewriting the swift layer, was the crashes I was experiencing inside ```Decoder``` methods (I assume they're already fixed), and I wasn't able to read/understand what was happening in the code.
[ObjectMapper](https://github.com/Hearst-DD/ObjectMapper) library is widely used in the swift community, and I think it makes sense to make use of it, instead of reimplementing it. Another advantage is that it supports both serlialization/deserialization out of the box.

So to answer your question, for my own project, moving away from ObjectMapper would be a dealbreaker.

One more point which I forgot to mention, is that body parameters are ignored in the original swift implementation. This one supports body parameters, but still lacks form parameters.

> For Handling for different response data type, per status code, do you mean the response data type is different based on the status code? Can you share your Swagger spec with us?

By definition, ```schema```s are defined per status code. Here's a code snippet from [swagger spec](http://swagger.io/specification/)

    responses:
        '200':
          description: pet response
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
        default:
          description: error payload
          schema:
            $ref: '#/definitions/ErrorModel'

Under responses array you can keep adding different status codes, and define a schema for each.

> For Usage of swift enums with associated values, can you also share the spec for this and how that's represented in swift?
 
    enum PostEntryResponse {
        case Res200(String, NSData)//default
        case Res202(DetailsDataModel, NSData)
        case Res400(ErrorDataModel, NSData)
        case Failure(Int?, NSData?)
    }
    
    ....
    
    Raygun.requestEntries() {response in 
        swift response {
        case .Res200(let string, _):
            print(string)
            break
        case .Res202(les detailsDataModel, _):
            self.presentDetailsViewController(detailsDataModel)
            break
        case .Res400(les errorDataModel, _):
            self.reportError(errorDataModel)
            break
        case .Failure:
            fatalError("don't do this at home")
        }
    }

The purpose is to have elegant and simple return/callback values which can support multiple types, and can be used within a switch statement.

**Comment by Edubits** [comment]
Hi @mabedan, thanks for your contribution. I would prefer to see if we can use your changes to improve the default generator. Using ObjectMapper was something suggested earlier by @wing328 in https://github.com/swagger-api/swagger-codegen/issues/2194 and would be a great improvement.

**Comment by mabedan** [comment]
That works for me too.
Unfortunately I wont have time to actively invest in changing the default generator given that I'm working on this one as part of my job, but would be happy to help other contributors.

**Comment by Erdemus** [comment]
Many thanks, @mabedan, your generator is awesome. Current one even couldn't pass parameters in headers.

**Comment by wing328** [comment]
Hi all, it's worth sharing with you that `swift3` generator has been added to the latest master.

Please pull the latest to give it a try.

**Comment by yonaskolb** [comment]
In case it's useful for anyone, I took my own approach here to as well https://github.com/yonaskolb/SwagGen

**Comment by wing328** [comment]
@mabedan thanks for the work. Please kindly try the Swift3 or Swift4 generator to see if it meets your requirement.

**Pull request closed without merging**
