### PR TITLE
Retrofit2: Return ResponseBody if response if file.

### PR DESCRIPTION
**Pull request by craffael**
Until now
--------------------
If a swagger endpoint returned a file (e.g. an image), then the Retrofit2
template has choosen the return type java.io.File. However, retrofit cannot
deal with this and throws a com.google.gson.stream.MalformedJsonException.

New:
-------------------
If a swagger endpoint returns a file, then the corresponding Retrofit2 endpoint
will return a okhttp3.ResponseBody which can be used to retrieve the file.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. 
      There is no shell script for Retrofit2
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
See issue #6406

### CODE REVIEW

**Comment by wing328** [comment]
@craffael thanks for the PR. I wonder if you and rebase the change on the latest master to resolve the merge conflicts as we just merged another PR related to retrofit2 into master.

**Comment by wing328** [comment]
FYI. I've updated the petstore samples via 0f1a61d

Next time please run `./bin/java-petstore-retrofit2-all.sh` to update the samples so that CIs can verify the change

**Comment by wing328** [comment]
I need to roll back this change due to the following errors:
```
Tests in error: 
  testUploadFile(io.swagger.client.api.PetApiTest): io.swagger.client.api.PetApi.uploadFile(Ljava/lang/Long;Ljava/lang/String;Lokhttp3/RequestBody;)Lretrofit2/Call;

Tests run: 18, Failures: 1, Errors: 1, Skipped: 0
```

**Comment by craffael** [comment]
Sorry about that. I don't know why I didn't find ./bin/java-petstore-retrofit2-all.sh. I think I was looking for something that started with java, but still is hould have found that. I will fix this now and resubmit.

**Pull request merged**
