### PR TITLE
[Java][Spring] Add examples defined in the spec to Spring MVC server generator

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

For https://github.com/swagger-api/swagger-codegen/issues/5310.

Credits also go to @elizabett, @cbornet

### CODE REVIEW

**Comment by wing328** [comment]
@kenjones-cisco because we need to determine the "Accept" in the HTTP request so as to return the response based on the format specified in "Accept".

Is it causing issue to your application?

**Comment by kenjones-cisco** [comment]
@wing328 Thanks for the explanation.

**Comment by wing328** [comment]
@kenjones-cisco I think about this a bit more and this is breaking change that should go to 2.3.0 (a branch with breaking changes) instead as the method signature has changed. (we want to avoid breaking changes to the current master)

I'm sorry for the inconvenience caused by this.

I'll file a PR to revert the change in the master and submit the change against 2.3.0 instead by coming Thursday.

cc @elizabett, @cbornet

**Comment by wing328** [comment]
> I'll file a PR to revert the change in the master and submit the change against 2.3.0 instead by coming Thursday.

Due to busy schedule, I'll revert the change tomorrow instead.

**Comment by wing328** [comment]
@kenjones-cisco the change has been rolled back via #5599 

I'll file a separate PR to make the enhancement in 2.3.0 branch.

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/5606 merged into 2.3.0 to provide the same enhancment to Spring generators.

@elizabetht @kenjones-cisco please kindly pull the latest master and 2.3.0 to give it a try.

**Comment by wingsofovnia** [comment]
Hi @wing328 !
In my application, where I'm using codegen for generating api intefaces (only) dynamically during build, `@RequestHeader("Accept") String accept` is a breaking change. As far as I can see, it's only used in a Controller stub. Can we consider disabling this param for interfaceOnly config enabled?

**Comment by wing328** [comment]
>  Can we consider disabling this param for interfaceOnly config enabled?

@wingsofovnia sounds reasonable to me. Please submit a PR so that we can review the change.

**Comment by cbornet** [comment]
I think there is a better way : instead of using RequestHeader, the header can be retreived from ((ServletRequestAttributes)RequestContextHolder.getRequestAttributes()).getRequest().getHeader("Accept"). This way the API would be the same for all implementations and cleaner IMO.

**Comment by cbornet** [comment]
And we can do it on the master since the change is non-breaking

**Pull request merged**
