### PR TITLE
Create abstract go codegen base class #6059

### PR DESCRIPTION
**Pull request by bvwells**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@antihax

### Description of the PR

Introduce an abstract codegen base class for Go to address part of issue #6059. Should be no functional changes to Go client and server generators.

### CODE REVIEW

**Comment by wing328** [comment]
@bvwells Looks good to me 👍

**Comment by antihax** [comment]
Looks good to me also.

**Comment by wing328** [comment]
I ran some tests with Go client, server generators and didn't notice any difference in terms of output.

**Comment by bvwells** [comment]
@wing328 many thanks for the testing and to you and @antihax for the reviews.

**Pull request merged**
