### PR TITLE
#779  Why is there no accessors...

### PR DESCRIPTION
**Pull request by rastaman**
Hi, here is a pull request to address the issue #779 : 
- the patch add accessors for fields of the all CodeGen classes. 
- Also it move the code wich was setting additionnalProperties and supportingFiles in the constructors to a init() method. 

The init() method, where present/needed, is called in the constructors but also in the setters of the members. So the files or properties which are computed from the value of a field can be refreshed.

The defintion and visibility of the fields of of the classes have not changed.

### CODE REVIEW

**Comment by rastaman** [comment]
I'm wondering if i have not too much messed with the commit history... :-( let me know if it's a problem.

**Comment by wing328** [comment]
I believe you need to submit the PR against the `develop_2.0` branch instead of master. Please have a look at other PRs for reference.

**Comment by rastaman** [comment]
Thanks for the hint!

**Comment by rastaman** [comment]
I will rework this patch for the develop_2.0 branch and submit it again, thanks for your patience!

**Pull request closed without merging**
