### PR TITLE
[TypeScript][Angular] Attempts to fix issues that causes enums that are not generated with a class to not generate correctly

### LINKED ISSUE #6822: [Typescript][Angular] bug: Enum generates empty name.
##### Description

I think something went wrong when the enum generation [recently changed](https://github.com/swagger-api/swagger-codegen/issues/6206). It currently generates empty names?

##### Swagger-codegen version

The current(time of writing) master (commit f78d958ec01917353fa43aad49ad4f6744843bdb ))

##### Swagger declaration file content or url
**The defined enum:**
```yaml
indicatie_actief:
    type: "string"
    maxLength: 1
    description: "Indication whether the object is active or not"
    enum: 
    - J
    - N
```

**Referenced in:**
```yaml
responses:
        200:
          description: "Status 200"
          schema:
            type: "object"
            properties:
              items:
                type: "array"
                items:
                  type: "object"
                  allOf:
                  - type: "object"
                    properties:
                      ...more props...
                      indicatie_actief:
                        $ref: "#/definitions/indicatie_actief"
```

**Results in:**
```export type  = 'J' | 'N';

export const  = {
    J: 'J' as ,
    N: 'N' as 
}

```
**Bug: The names are missing**
Any ideas how to fix?

##### Command line used for generation

generate -i <url> -l typescript-angular

### PR DESCRIPTION
**Pull request by kenisteward**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Attempts to fix #6822 causing a possible incorrect generation of enums when the enum is the base for the definition and not a class that contains an enum.

### Techies
@TiFu  @taxpon @sebastianhaas   @Vrolijkx

### CODE REVIEW

**Comment by TiFu** [comment]
Are you sure that you ran the shell scripts correctly? Shouldn't this change have some effect on the samples? IIRC the samples contain enums.

**Comment by kenisteward** [comment]
@tifu it does not. None of out samples use enums as the base class rather
than a property on a model. I can give an example when I get to my computer

**Comment by kenisteward** [comment]
This is the case that this PR fixes.  

I had used {{className}} instead of {{classname}} when the base type that is returned is an enum as opposed a property enum.

```
swagger: "2.0"
info:
  description: "This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"
tags:
- name: "pet"
  description: "Everything about your Pets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "store"
  description: "Access to Petstore orders"
- name: "user"
  description: "Operations about user"
  externalDocs:
    description: "Find out more about our store"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /pets:
    get:
       responses:
              200:
                description: "Status 200"
                schema:
                  type: "object"
                  properties:
                    items:
                      type: "array"
                      items:
                        type: "object"
                        allOf:
                        - type: "object"
                          properties:
                            code_bik:
                              type: "string"
                            bik:
                              type: "string"
                            indicatie_actief:
                              $ref: "#/definitions/indicatie_actief"
definitions:
  indicatie_actief:
    type: "string"
    description: "Indication whether the object is active or not"
    enum: 
      - "J"
      - "N"
  indicatie_uniek:
    type: "string"
    description: "Indication whether the object is unique or not"
    enum: 
      - "J"
      - "N"
```

**Comment by kenisteward** [comment]
@wing328 After this passes checks it can be merged.  @HermenOtter confirmed this works as well as I did with a local yaml.  On that note we should probably change the bast petstore example to have an enum that is represented as a {{classname}} to make sure we don't mess up templates but I'm not sure what the process for changing the example yaml or whether it needs really doing.

**Comment by kenisteward** [comment]
@wing328 merge at your soonest convenience :)

**Comment by wing328** [comment]
@kenisteward missed your message earlier. Just merged.

**Pull request merged**
