### PR TITLE
[Go] Fix API error handling

### PR DESCRIPTION
**Pull request by roycaihw**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@wing328 @antihax
### Description of the PR
Previous implementation doesn't raise error properly. Arguably we could remove the if statement.

### CODE REVIEW

**Comment by antihax** [comment]
this was intended, what is not working correctly?

`// If we succeed, return the data, otherwise pass on to decode error`

**Comment by antihax** [comment]
I see.. we should likely look at removing the >= 300 on the line below and adding a case if there was a status response with no model.

**Comment by roycaihw** [comment]
> we should likely look at removing the >= 300 on the line below and adding a case if there was a status response with no model.

I agree. And those checking StatusCode == 200 statements inside StatusCode > 300 blocks look confusing to me 
https://github.com/swagger-api/swagger-codegen/blob/4788eec0a8759eb2042688166ece908c8e305709/samples/client/petstore/go/go-petstore/api_pet.go#L714-L720

**Comment by roycaihw** [comment]
StatusCode check removed: https://github.com/swagger-api/swagger-codegen/pull/8198/commits/34e016e8da1b8878cca8061ed7d247831593421e?w=1

The second commit is generated from `bin/go-petstore.sh` and `bin/security/go-petstore.sh`. Adding testcase now

**Comment by roycaihw** [comment]
@antihax CI has passed. Actually it's not clear to me how to test this behavior. I guess I need to add a test in https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/pet_api_test.go, but I don't know how to modify the test server to create a broken endpoint which talks to some existing client method.

**Pull request closed without merging**
