### PR TITLE
Added support for VERSION, APPNAME and CONTACT from Swagger file into Startup.cs

### PR DESCRIPTION
**Pull request by knom**
#7102 
@jimschubert
Version and AppName are now used for `AddSwaggerGen(..)`, resulting in the Swagger generated being more like the original one.

### CODE REVIEW

**Comment by jimschubert** [comment]
Looks good, however, this would also need to change the API prefix in code.

**Comment by knom** [comment]
What do you mean with API prefix? Thanks.

**Comment by jimschubert** [comment]
Sorry. I was referring to controller.mustache, but it looks like it should already be accounted for by the other properties:

```
[Route("{{{basePathWithoutHost}}}{{{path}}}")]
```

**Comment by wing328** [comment]
@knom please rebase on the latest master to help resolve the merge conflicts when you've time.

**Comment by knom** [comment]
Hey @wing328 !
I rebased to the latest master.
I'm trying to query CONTACT INFO - NAME in the Mustache file as well..

Does that not exist?

```
  contact:
    name: API Support
    email: support@example.com
    url: http://example.com/support
```

**Comment by wing328** [comment]
Seems like it's not set up at the moment: https://github.com/swagger-api/swagger-codegen/blob/92ac1edd786ac3bdba34a8493f10674e18feff48/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L208-L214

**Comment by knom** [comment]
@wing328 Could you add it?
I'm not that fluent in Java.. :-(

**Comment by wing328** [comment]
@knom sure. Let me try...

**Comment by wing328** [comment]
@knom done via https://github.com/swagger-api/swagger-codegen/pull/7164

Please pull the latest master to give it a try.

**Pull request merged**
