### PR TITLE
[AspNetCore SERVER] Added support for ASP.NET Core 2.0

### PR DESCRIPTION
**Pull request by knom**
@jimschubert, @mandrean, @wing328 

Somehow related to #2886, but for the SERVER
Moved the project structure, mustache files, .. to ASP.NET Core 2.0.

Let me know what you think!

### CODE REVIEW

**Comment by jimschubert** [comment]
This looks good, but should probably go into 2.3.0. I can't see the target branch on mobile.

**Comment by wing328** [comment]
@jimschubert it's targeting current master (which is 2.3.0)

**Comment by wing328** [comment]
@knom if I understand correctly, we'll no longer support ASP.NET CORE 1.0 after merging this PR into master so I've marked this PR as a "Breaking Change" (without fallback).

**Comment by knom** [comment]
@wing328 that is right!
There's three changes..
- Moved away from project.json --> .csproj
  (see https://www.stevejgordon.co.uk/project-json-replaced-by-csproj)
- Updated all the dependencies to .NET Core 2
- Removed some of the setup code, as it's now built-in in .NET Core 2 anyways and was a duplicate

**Comment by jimschubert** [comment]
@wing328 Thanks. I haven't looked at the version in master in a while, I didn't realize it was promoted to 2.3.0. I didn't check the compile to verify, but @knom has been making quality contributions and I don't see any reason it would not work as expected.

**Comment by knom** [comment]
Thanks for the quick merge :-)

**Pull request merged**
