### PR TITLE
Java jersey2: reuse a shared Client instance

### PR DESCRIPTION
**Pull request by xhh**
According to [the feedback](https://github.com/swagger-api/swagger-codegen/issues/1435#issuecomment-151606194) from @fabiankessler

### CODE REVIEW

**Comment by chenjianjx** [comment]
Better to make the ApiClient stateless, otherwise it is not thread-safe to use it.  Currently the request and the response body are not member variables of ApiClient, but "responseHeaders" is.    Need to make the headers a per-request thing.

**Comment by wing328** [comment]
@chenjianjx thanks for the feedback. The recommendation is to use an instance of ApiClient per thread to avoid any potential multi-threading issue.

**Comment by chenjianjx** [comment]
@wing328 then there would be performance issues, wouldn't there?  User sends a request => creates a new ApiClient => Creates a new socket ?   Opening and closing sockets are expensive unless there is a connection pool like those for JDBC.

**Comment by wing328** [comment]
Very good point about performance. 

Your concern should be addressed by the connection pool, which should be something supported by the HTTP library (e.g. Retrofit, Jersey, etc). 

Is it correct to say that you already ran into performance issue using an instance of ApiClient per thread?

**Comment by fabiankessler** [comment]
The one per thread works to some extent in theory. But still

* it's not practical, developers won't do it
* still a loss depending on how things are used. Multiple requests that should be on the same Thread could be on different ones.

All you need to do is make the ApiClient immutable. I gave an example on this thread https://github.com/swagger-api/swagger-codegen/issues/1435 linking to https://gist.github.com/fabiankessler/a6cb51e247a8c450d4aa I had moved all mutability out of it.

That version of the ApiClient returns the result AND the response headers at once, using a simple wrapper object. Your generated PHP client does exactly the same, the fetcher method returns the content and the headers in an array with 2 items.

**Comment by wing328** [comment]
@fabiankessler I agree with you that the solution I recommended before is not perfect and thanks for taking time to refactor ApiClient.

When you've time, do you mind submitting a PR with the change you proposed?

Ref: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by wing328** [comment]
@fabiankessler @chenjianjx based on the feedback, I've refactored the C# (not Java) API client so that the ApiClient is reusable across multiple API class (e.g. PetApi). PR: https://github.com/swagger-api/swagger-codegen/pull/1643

Later we'll do the same for Java API client.

**Comment by wing328** [comment]
@fabiankessler @chenjianjx a few enhancements have been made to the PR and now both ApiClient and Api classes should be thread safe.

ApiResponse class is added to store the status code and header.

Again I would appreciate your feedback on the proposed change.

**Comment by chenjianjx** [comment]
has a similar PR for java been integrated? I actually need it soon.

**Pull request merged**
