### PR TITLE
Add generation of enum models

### PR DESCRIPTION
**Pull request by fehguy**
This PR allows enum classes to be generated from simple objects.  For example:

```yaml
definitions:
  Example:
    type: string
    enum:
      - First
      - Second
```

Is not supported in the current codegen.  This PR addresses #1357 and also enables references to enums directly:

```java
public enum Example {
    First, Second
}
```

### CODE REVIEW

**Comment by mateuszwinnicki** [comment]
Is it working properly right now?
I clone repo two hours ago, but still cant generate enum in definition

**Comment by hiveship** [comment]
@mateuszwinnicki I had the same problem, just tested now and it's ok !

**Comment by mateuszwinnicki** [comment]
@hiveship I clone repo again and still nothing :( maybe I need something more?

**Comment by hiveship** [comment]
I am not a developer of the project, just a classic user.
My Swagger enum is:
    "definitions": {
        "MediumStatus": {
            "type": "string",
            "enum": [
                "CLOSED",
                "OPEN_AVAILABLE",
                "OPEN_NOT_AVAILABLE",
                "NOT_AVAILABLE"
            ]
        }
    }

I generate my Java client using the following command line:
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i mySwagger.json \
  -l java \
  -o myClient/

and the MediumStatus.java generated is :+1:
package io.swagger.client.model;

import io.swagger.client.StringUtil;


import java.util.Objects;

import io.swagger.annotations.*;
import com.fasterxml.jackson.annotation.*;


public enum MediumStatus {
    CLOSED, OPEN_AVAILABLE, OPEN_NOT_AVAILABLE, NOT_AVAILABLE
}

**Comment by wing328** [comment]
@mateuszwinnicki maybe you need to do `mvn clean package`

**Comment by mateuszwinnicki** [comment]
when I generate -l java it works, when I use -l jaxrs it not working

**Comment by illukarl23** [comment]
Hi,
I'm a little confused with the generation of enum models.
What languages are supporting enums right now in the embedded CodeGen in the online Swagger Editor? 
For example when I use C# as language, no enums are generated.
Thanks

**Comment by wing328** [comment]
@illukarl23 that's for Java. For C#, there's a pending PR to add enum support: https://github.com/swagger-api/swagger-codegen/pull/1752

**Comment by mateuszwinnicki** [comment]
@illukarl23 only for Java and only for client, JAX-RS still not working

**Comment by wing328** [comment]
In the latest master, I can find https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/JavaJaxRS/jersey1_18/enumOuterClass.mustache and other related files (added 14 days ago via https://github.com/swagger-api/swagger-codegen/commit/9ca914f769ed2840b19f51d9c61a6ff4d3a3dd73)

@mateuszwinnicki do you mind pulling the latest master to confirm the issue is still there?

**Comment by hiveship** [comment]
@wing328 I can confirm you that the problem still exist for JAX-RS. It's ok for Java client.

**Pull request merged**
