### PR TITLE
Add support for Spring's RestTemplate in Java client codegen

### LINKED ISSUE #1176: Support for Spring RestTemplate
I would like support for Spring RestTemplate. It will allow easy testing of the client with the `MockRestServiceServer` providing mock API interaction.

### PR DESCRIPTION
**Pull request by nbruno**
This PR adds support for Spring's RestTemplate in Java client codegen, using Jackson for JSON handling. The PR also includes a sample implementation in `samples/client/petstore/java/resttemplate/` built against the testing Petstore spec (with fake endpoints/models), as well as unit tests for the sample implementation. The Java samples are updated for a minor change in Jackson handling of enums, where they were deserialized via `@JsonCreator` but not serialized with `@JsonValue`.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Implementation 
There are a few concepts that exist in the swagger-codegen codebase that don't apply when using Spring's `RestTemplate`. In each case, this pull request follows the Spring convention.

1. `ApiException` as a generic exception thrown on failures from API calls. This is not necessary as Spring's error handling mechanism, which by default supports 4xx and 5xx errors, throws instances of [`RestClientException`](http://docs.spring.io/spring-framework/docs/4.3.7.RELEASE/javadoc-api/org/springframework/web/client/RestClientException.html). As a result, calls to any API method throw this exception.
2. Authentication - Representing query parameters as `List<Pair>` and header parameters as `Map<String, String>` conflicts with how they are represented in Spring. Query parameters are stored in a [`MultiValueMap<String, String>`](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/MultiValueMap.html), where a single key can have multiple values. Similarly, Spring already provides its own abstraction for HTTP headers, the [`HttpHeaders`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/HttpHeaders.html) class (which itself is also a `MultiValueMap`). 
3. Mime type handing / Media types - Again, Spring has its own representation for HTTP media types, [`MediaType`](http://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/http/MediaType.html). Instead of using raw `String` objects, the core of this PR expects instances of `MediaType`, and converts any supplied `String` objects when appropriate (specifically for Accept / Content-Type headers).
4. HTTP status codes are also supported via Spring's [`HttpStatus`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/HttpStatus.html) abstraction.

This pull request also integrates with Spring's dependency injection by annotating the appropriate classes with `@Component`, allowing developers to `@Autowire` any API class into their application once they are available in the Spring context (loaded via `@ComponentScan`, etc.). If this route is chosen, the `ApiClient` expects that a `RestTemplate` object exists in the Spring context.

### Debugging

Enabling debugging on the `ApiClient` adds a `ClientHttpRequestInterceptor` that logs (with `commons-logging`) details about the request. To do this successfully, the `RestTemplate` that is used with the `ApiClient` **MUST** have a request factory that supports consuming the body of the request more than once. Otherwise, the interceptor will consume the stream to log the contents of the body, and the body of the request will be unavailable to the application. If the `ApiClient` builds its own `RestTemplate`, it will use a [`BufferingClientHttpRequestFactory`](http://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/http/client/BufferingClientHttpRequestFactory.html) to support debugging by default. 

### Dependencies
 - `spring-web`, version 4.3.7.RELEASE - The base package to obtain `RestTemplate`
 - `jackson-core`, `jackson-annotations`, `jackson-databind`, version 2.8.8 - JSON handling in models

Closes #1176

### CODE REVIEW

**Comment by wing328** [comment]
@nbruno thanks for the PR. I did some tests and the result looks good.

**Comment by wing328** [comment]
Added @nbruno as the template creator of Java RestTemplate: https://github.com/swagger-api/swagger-codegen/blob/master/README.md#template-creator 👏 👏 👏

**Comment by wing328** [comment]
If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen)

**Comment by wing328** [comment]
Tweet: https://twitter.com/wing328/status/856416983004323840

Please help retweet.

**Comment by nbruno** [comment]
@buyukim Currently this PR follows the same conventions for the pom.xml file that is used for the default Java client generation. Your request sounds like it could benefit all Java codegen, not just the one utilizing the RestTemplate library. If you agree, I would open an issue for making your proposed changes to all of the Java templates so they stay consistent.

**Comment by wing328** [comment]
> If you agree, I would open an issue for making your proposed changes to all of the Java templates so they stay consistent.

Sounds good to me. Thanks @nbruno

**Comment by wing328** [comment]
If no one is working on adding {{java8}} mustache tag to other pom.xml files, I can do it tomorrow (Tue)

**Comment by wing328** [comment]
FYI. Filed https://github.com/swagger-api/swagger-codegen/pull/5541 to use the `java8` mustache tag.

**Comment by cheeta** [comment]
Hi @wing328 ,
Hope you are doing good. Sorry if it is not right platform for this question. 

Our existing application uses Spring `RestTemplate` which is standard across our different project. as per this link https://github.com/swagger-api/swagger-codegen#compatibility 2.2.2 is the current stable release. I checked master branch and can see that `RestTemplate` feature there. 
Can you give me some estimated release (and some estimated date if possible) that could have `RestTemplate` client feature.

Thanks,
Yahya

**Pull request merged**
