### PR TITLE
[PHP] Lumen Framework v5.2 - Server Generator

### PR DESCRIPTION
**Pull request by abcsun**

### CODE REVIEW

**Comment by wing328** [comment]
@abcsun  Thanks for the PR but your first 2 commits (as shown in the Commits tab) are not linked to your Github account, which means this PR wont' count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://help.github.com/articles/changing-author-info/

**Comment by abcsun** [comment]
@wing328 according to the [https://help.github.com/articles/changing-author-info/](https://help.github.com/articles/changing-author-info/ ), i have changed my account correct, but commits from other guys were changed too, sorry for this operation and how to fix?

**Comment by wing328** [comment]
seems like you might have done a incorrect rebase or merge causing this.

but no worry i'll fix it by doing a cherry-pick

**Comment by wing328** [comment]
@abcsun I've filed #2658 by cherry-picking your commits.

Note that the credits (commits) still go back to you.

**Pull request closed without merging**
