### PR TITLE
[html] Add type anchor to body param block

### PR DESCRIPTION
**Pull request by wy-z**
- [html] Add type anchor to body param block

Signed-off-by: weiyang weiyang.ones@gmail.com

### CODE REVIEW

**Comment by wing328** [comment]
@wy-z thanks for the PR. Are you also aware of another documentation generator `html2`? Would that better meet your requirement?

**Comment by wy-z** [comment]
Uh...It will cause my browser to crash...
I will take some time to find out the reasons.

**Comment by wing328** [comment]
Does it crash all browsers (Chrome, IE, FF, Safari) in your environment?

**Comment by wy-z** [comment]
It should not be a compatibility issue~

**Pull request merged**
