### PR TITLE
[Spring] Add a generator for spring cloud feign clients

### PR DESCRIPTION
**Pull request by cbornet**
First version of a generator for [spring-cloud-feign](http://projects.spring.io/spring-cloud/spring-cloud.html#spring-cloud-feign) clients in a spring-boot application.
The generator will generate auto-configured beans for authentication (with full OAuth2 support using spring-security/spring-cloud-security).

Some things will be added later:
- [ ] README with explanation on how to use and customize (especially how to use Ribbon/Eureka/Hystrix, ...)
- [x] ~~Petstore sample tests~~

### CODE REVIEW

**Comment by cbornet** [comment]
@wing328 I see some issues while writing the tests so please wait before merging.

**Comment by wing328** [comment]
@cbornet please take your time. I will wait for update from you.

**Comment by cbornet** [comment]
Tests are now passing except the file upload because it's not supported by spring-cloud-feign (See https://github.com/spring-cloud/spring-cloud-netflix/issues/1164) so it is ignored for now.
@wing328 can be merged now ! I'll do the README later.

**Comment by wing328** [comment]
@cbornet thanks!! I'll merge shortly (after the python test enhancement PR)

**Comment by wing328** [comment]
@cbornet thanks for the contribution to add the Spring Cloud Feign API client.

**Pull request merged**
