### PR TITLE
Add CLIOptions to generate interface + fix default values

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fix default values for CliOptions + Add a new options to generate interfaces to facilitate generation by the IDE when there are changes between versions. I also removed CliOptions I was not taking care of (was copied from Swing)

### CODE REVIEW

**Comment by wing328** [comment]
@JFCote In the Petstore sample for play framework, I got the following errors when running `sbt test`:
```
java-play-framework|JFCote-improvement_use_interface_cli⚡ ⇒ sbt test
[info] Loading project definition from /Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/project
[info] Set current project to swagger-java-playframework (in build file:/Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/)
[info] Compiling 4 Scala sources and 17 Java sources to /Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/target/scala-2.11/classes...
[error] /Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/app/controllers/PetApiControllerImpInterface.java:25: package Http.MultipartFormData does not exist
[error]     void uploadFile( Long petId, String additionalMetadata, Http.MultipartFormData.FilePart file);
[info] /Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/app/swagger/SwaggerUtils.java: /Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/app/swagger/SwaggerUtils.java uses unchecked or unsafe operations.
[info] /Users/williamcheng/Code/jan2017/swagger-codegen/samples/server/petstore/java-play-framework/app/swagger/SwaggerUtils.java: Recompile with -Xlint:unchecked for details.
[error] (compile:compileIncremental) javac returned nonzero exit code
[error] Total time: 10 s, completed Mar 19, 2017 6:36:53 PM
```
Did you get similar errors when running `sbt test` locally?

**Comment by JFCote** [comment]
That is strange... will do a quick test this morning and fix it accordingly! Sorry about that :)

**Comment by JFCote** [comment]
I just fix it. I don't understand I didn't notice that. :/

**Comment by wing328** [comment]
@JFCote no worry. We should setup CI to catch any potential issue moving forward. I should have a PR by tomorrow.

**Comment by wing328** [comment]
UPDATE: The CI has been setup to test Play server code for Petstore.

**Comment by wing328** [comment]
@JFCote when you've time, would you please rebase on the latest master to resolve the merge conflicts.

Let me know if you need help on that.

**Comment by JFCote** [comment]
You can close this PR. When you merged #5048, it was included because of a merge I did to fix bugs. I forgot to come here and notice you :)

**Comment by wing328** [comment]
@JFCote that's ok. PR closed.

**Pull request closed without merging**
