### PR TITLE
[Java] fix Bad class name for JsonSubTypes

### LINKED ISSUE #5735: Bad class name for JsonSubTypes
##### Description

``@JsonSubTypes.Type(value =`` does not use the generated class name.

##### Swagger-codegen version

``2.2.2``

##### Swagger declaration file content or url

https://gist.github.com/manuc66/6949ccf855a54e65db40f32eb4b37af2

produce this:
```java
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-05-30T14:56:11.096+02:00")@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "key", visible = true )
@JsonSubTypes({
  @JsonSubTypes.Type(value = invalid-foo-error.class, name = "invalid-foo-error"),
})

public class Error {
  @JsonProperty("key")
  private String key = "generic-error";

  @JsonProperty("message")
  private String message = null;

  public Error key(String key) {
    this.key = key;
    return this;
  }
```

``invalid-foo-error.class`` should instead be ``InvalidFooError.class``

##### Suggest a Fix

I'm preparing a fix that would fix some ``.mustache`` files

### PR DESCRIPTION
**Pull request by manuc66**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Only ``.mustache`` file changed, I did know where I could add some tests so right now this PR doesn't include any new.
See #5735

### CODE REVIEW

**Comment by manuc66** [comment]
This PR might also fix #5317

**Comment by wing328** [comment]
Tests with updated samples also passed: https://circleci.com/gh/swagger-api/swagger-codegen/357

**Comment by wing328** [comment]
FYI. I've updated the Petstore samples for the affected generators via f163fdb

**Comment by manuc66** [comment]
Thanks for merging!

B.B.: the update for the affected generator doesn't seem to be related with this change

**Pull request merged**
