### PR TITLE
Moose role, docs, and automatic docs

### PR DESCRIPTION
**Pull request by dvz5**
- added a Moose role that wraps the API and flattens the whole thing into the consuming class
- documentation
- automatic documentation of the generated API
- added methods to retrieve documentation supplied in the Swagger spec

### CODE REVIEW

**Comment by wing328** [comment]
@dvz5 thanks for the PR as always. I got the following TODO messages when running the integration tests:
```
ok 16 - stored and retrieved: got the proper tag id
not ok 17 - got corrrect Pet API description # TODO Swagger spec doesn't populate all the description fields
#   Failed (TODO) test 'got corrrect Pet API description'
#   at t/04_role.t line 67.
#          got: undef
#     expected: 'Pet API description'
not ok 18 - Pet object method_documentation is available # TODO Swagger spec doesn't populate all the description fields
#   Failed (TODO) test 'Pet object method_documentation is available'
#   at t/04_role.t line 68.
#          got: undef
#     expected: 'Description of the Pet object name() method'
ok 19 - Pet API method_documentation has the correct keys
```
Do you mind elaborating a bit more? Is that an issue parsing the Swagger spec (which means likely it would affect other languages)?

**Comment by dvz5** [comment]
Hi, no, these are set as tests expected to fail until I can look a bit
closer at the petstore json. I think the return values are probably undef
simply because there is not much description text in the spec. I want to be
sure that's the reason, then I'll propose adding some descriptive text to
the spec, but I'm nervous that might break other languages tests so I'll
run anything by you first!

**Comment by wing328** [comment]
For suggestion to the Swagger spec, please open an "issue" at https://github.com/swagger-api/swagger-spec/issues

**Comment by dvz5** [comment]
From what I've figured out, it's not possible to consistently extract documentation for the endpoint APIs, so I've removed the class_documentation() method from api.mustache. I think I'm done now, it's certainly working like a dream against the Bookeo.com API I'm working with!

**Comment by wing328** [comment]
Glad to hear that the auto-generated Perl SDK is working well for you :)

**Pull request merged**
