### PR TITLE
[go][model] Use pointers to avoid circular references

### PR DESCRIPTION
**Pull request by wy-z**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- [go][model] Use pointers to avoid circular references

### CODE REVIEW

**Comment by wing328** [comment]
@wy-z thanks for the PR.

cc @antihax @guohuang @neilotoole

**Comment by antihax** [comment]
Will check tonight.

Is there a way to write a test case for this and some of the other fixed issues?

Perhaps we could use versioned `.yaml` spec with appropriate test cases for new clients going forward? This could give a good way to incrementally set the bar for the stability of the client code (all languages).

**Comment by wing328** [comment]
> Is there a way to write a test case for this and some of the other fixed issues?

@antihax I would suggest adding new models to test the scenarios in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml to start with.

**Comment by antihax** [comment]
I had done that with #4417, but it causes a lot of other clients with the same issue to break. Hence versioning may be a way to go?

**Comment by wing328** [comment]
Right. That happened before.

Let's give versioning a try to see how that goes.

**Comment by antihax** [comment]
This looks good.

I've starting writing test cases in the spec including a recursive model. Should have a PR tonight for that.

**Comment by wy-z** [comment]
Thanks for your fruitful work~
@wing328 @antihax

**Pull request merged**
