### PR TITLE
Added missing cliOptions in some languages

### PR DESCRIPTION
**Pull request by evigeant**
Added the missing cliOptions for html, dynamic-html and jaxrs.

### CODE REVIEW

**Comment by wing328** [comment]
@evigeant thanks for the PR. Please pull the latest and rebase on master to resolve the merge conflicts.

**Comment by wing328** [comment]
Sorry @evigeant please instead rebase after #1988 gets merged into master to avoid rebasing again.

#1988 will be merged tomorrow (Jan 28)

**Comment by wing328** [comment]
#1988 merged into master. Please rebase.

**Comment by evigeant** [comment]
I will rebase today

**Comment by evigeant** [comment]
@wing328 The build failed on an unrelated error in retrofit2. Should I make another fake commit for the CI?

**Comment by wing328** [comment]
@evigeant I restarted the CI job. Let's see how it goes.

**Pull request merged**
