### PR TITLE
Spring boot server generator 

### PR DESCRIPTION
**Pull request by diyfr**
A first version of SpringBoot Server generator

### CODE REVIEW

**Comment by wing328** [comment]
@diyfr thank you for contributing the SpringBoot server generator.

I made some minor changes
- renamed `bin/springboot-petstore-server2.sh` to `bin/springboot-petstore-server.sh`
- changed its permission to executable (a+x)

**Comment by cbornet** [comment]
Shouldn't Spring Boot be a sub-generator/library of Spring MVC ?
They share a lot of files.

**Comment by wing328** [comment]
@cbornet yes, that's one way to do it. If you're going to combine these 2, roughly how much effort (man day) would it take?

(personally I'm ok with springboot as a standalone generator/template)

**Comment by cbornet** [comment]
I'd say half a day for someone who has good knowledge.
To me, the interest is to reduce the time spent making evolutions on both languages so it's worth it if they evolve quickly.
The drawback is that I feel that libraries have less visibility in the docs than languages but it's certainly something we can work on.

**Comment by diyfr** [comment]
there are chances that the springboot part is evolving. Moreover SpringBoot is increasingly popular.

**Comment by diyfr** [comment]
For Api, I would rather generate interfaces rather than classes, because  with a new generation, only implementations are changing.

**Comment by diyfr** [comment]
I can modify api.mustache to interface, and add apiImpl.mustache ?

api.mustache

```
package {{apiPackage}};

import {{modelPackage}}.*;

{{#imports}}import {{import}};
{{/imports}}

import io.swagger.annotations.*;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;

import static org.springframework.http.MediaType.*;

@RequestMapping(value = "/{{{baseName}}}", produces = {APPLICATION_JSON_VALUE})
@Api(value = "/{{{baseName}}}", description = "the {{{baseName}}} API")
{{>generatedAnnotation}}
{{#operations}}
public class {{classname}} {
  {{#operation}}

  @ApiOperation(value = "{{{summary}}}", notes = "{{{notes}}}", response = {{{returnType}}}.class{{#returnContainer}}, responseContainer = "{{{returnContainer}}}"{{/returnContainer}}{{#hasAuthMethods}}, authorizations = {
    {{#authMethods}}@Authorization(value = "{{name}}"{{#isOAuth}}, scopes = {
      {{#scopes}}@AuthorizationScope(scope = "{{scope}}", description = "{{description}}"){{#hasMore}},
      {{/hasMore}}{{/scopes}}
      }{{/isOAuth}}){{#hasMore}},
    {{/hasMore}}{{/authMethods}}
  }{{/hasAuthMethods}})
  @ApiResponses(value = { {{#responses}}
    @ApiResponse(code = {{{code}}}, message = "{{{message}}}", response = {{{returnType}}}.class){{#hasMore}},{{/hasMore}}{{/responses}} })
  @RequestMapping(value = "{{{path}}}",
    {{#hasProduces}}produces = { {{#produces}}"{{mediaType}}"{{#hasMore}}, {{/hasMore}}{{/produces}} }, {{/hasProduces}}
    {{#hasConsumes}}consumes = { {{#consumes}}"{{mediaType}}"{{#hasMore}}, {{/hasMore}}{{/consumes}} },{{/hasConsumes}}
    method = RequestMethod.{{httpMethod}})
  public ResponseEntity<{{>returnTypes}}> {{operationId}}({{#allParams}}{{>queryParams}}{{>pathParams}}{{>headerParams}}{{>bodyParams}}{{>formParams}}{{#hasMore}},
    {{/hasMore}}{{/allParams}})
      throws NotFoundException ;

  {{/operation}}
}
{{/operations}}
```

apiImpl.mustache (method signature to review)
```
package {{apiPackage}}Impl;

import {{modelPackage}}.*;

{{#imports}}import {{import}};
{{/imports}}

import io.swagger.annotations.*;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;

import java.util.List;

import {{apiPackage}}.NotFoundException;
import {{apiPackage}}.{{classname}};

import static org.springframework.http.MediaType.*;

@Controller
{{#operations}}
public class {{classname}}Impl implements {{classname}} {
  {{#operation}}


  public ResponseEntity<{{>returnTypes}}> {{operationId}}({{#allParams}}{{dataType}}} {{paramName}}{{/allParams}})
      throws NotFoundException {
      // do some magic!
      return new ResponseEntity<{{>returnTypes}}>(HttpStatus.OK);
  }

  {{/operation}}
}
{{/operations}}
```

Thus one can regenerate the code without overwriting implementations 
Your opinion ?

**Comment by cbornet** [comment]
The implementation class would also be regenerated so I'm not sure this is a big gain.

**Comment by cbornet** [comment]
It would be more interesting (and more Spring way) to call a generated @Service class from the controller where the user would put its business logic. Something like
```java
@ApiOperation(value = "{{{summary}}}", notes = "{{{notes}}}", response = {{{returnType}}}.class{{#returnContainer}}, responseContainer = "{{{returnContainer}}}"{{/returnContainer}}{{#hasAuthMethods}}, authorizations = {
    {{#authMethods}}@Authorization(value = "{{name}}"{{#isOAuth}}, scopes = {
      {{#scopes}}@AuthorizationScope(scope = "{{scope}}", description = "{{description}}"){{#hasMore}},
      {{/hasMore}}{{/scopes}}
      }{{/isOAuth}}){{#hasMore}},
    {{/hasMore}}{{/authMethods}}
  }{{/hasAuthMethods}})
  @ApiResponses(value = { {{#responses}}
    @ApiResponse(code = {{{code}}}, message = "{{{message}}}", response = {{{returnType}}}.class){{#hasMore}},{{/hasMore}}{{/responses}} })
  @RequestMapping(value = "{{{path}}}",
    {{#hasProduces}}produces = { {{#produces}}"{{mediaType}}"{{#hasMore}}, {{/hasMore}}{{/produces}} }, {{/hasProduces}}
    {{#hasConsumes}}consumes = { {{#consumes}}"{{mediaType}}"{{#hasMore}}, {{/hasMore}}{{/consumes}} },{{/hasConsumes}}
    method = RequestMethod.{{httpMethod}})
public ResponseEntity<{{>returnTypes}}> {{operationId}}({{#allParams}}{{dataType}}} {{paramName}}{{/allParams}})
      throws NotFoundException {
      return apiClientService.{{operationId}}({{#allParams}}{{dataType}}} {{paramName}}{{/allParams}});
  }

**Comment by diyfr** [comment]
not exactly @cbornet You can generate interfaces, but not crush your implementations. This is what is done with other modeling after code generation solutions.
Currently, you are obliged to put your business logic in the generated classes.
It could happen implementations but they are necessary for it to be based on the code works the first generation.

**Comment by cbornet** [comment]
You still generate the implementation so the crushing existing code issue remains

**Comment by diyfr** [comment]
I See 
```
  @Override
    public boolean shouldOverwrite(String filename) {
        return super.shouldOverwrite(filename) && !filename.endsWith("ServiceImpl.java") && !filename.endsWith("ServiceFactory.java");
    }
```
in AbstractJavaJAXRSServerCodegen  ;)

**Comment by cbornet** [comment]
Yes, so if you regenerate, your xxxServiceImpl will not take the API modifications into account and you have to implement them by hand... Well, it's not perfect but why not !
In that case I still suggest to generate a @Service interface with a xxxServiceImpl class like what is done with JAX-RS in order to separate concerns.

**Comment by diyfr** [comment]
Actually I have a different behavior between javax.ws.rs and org.springframework.web We are obliged to repeat the param in the implementation. So not interesting ;(

**Pull request merged**
