### PR TITLE
remove duplicate tags, replace with extensions in templates

### LINKED ISSUE #1518: jaxrs multiple tags causes startup failure
Because tags are used to group operations and paths, when there are multiple tags it will cause errors starting the service.

### PR DESCRIPTION
**Pull request by fehguy**
fixes #1518

This moves the tags and puts them in extensions.  Only the first tag is used for naming the file:

```json
{
  "x-tags" : [ {
    "hasMore" : "true",
    "tag" : "fun"
  }, {
    "tag" : "stuff"
  } ]
}
```

### CODE REVIEW

**Comment by fehguy** [comment]
@wing328 do you mind verifying this fix?

**Comment by wing328** [comment]
@fehguy ok. I'll run some tests later today.

**Comment by wing328** [comment]
@fehguy without the fix, jaxrs petstore can't start due to multiple tags

used debugOperations to confirm the `tags` are moved to `x-tags` and jaxrs petstore can start without issue.

**Comment by fehguy** [comment]
Thanks @wing328

**Pull request merged**
