### PR TITLE
#4962 Empty Response body handling in typescript-angular2 - 

### PR DESCRIPTION
**Pull request by kenisteward**
### PR checklist

- [ X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Followed directly what the suggestion said in #4962 as it is transparent and well handled that way.

### CODE REVIEW

**Comment by kenisteward** [comment]
@wing328 This should be a quick check.

**Comment by wing328** [comment]
@kenisteward agreed. The change looks good to me.

**Comment by wing328** [comment]
@kenisteward thanks for the PR. Do we need to do the same for other Typescript generators?

e.g. typescript-fetch: https://github.com/kenisteward/swagger-codegen/blob/cdb456ef01cac6c39e5a7112433fa10d7777bb36/modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache#L150

**Comment by kenisteward** [comment]
@wing328 upon further investigation we don't have to change the fetch API unless we want to bring it on par with the angular API. When the response body won't be able to parse they just return the full response for fetch rather than the parsed body. That's fine if the users are okay with using the app differently for not parsable  response bodies (empty) In my honest opinion I think it is bad practice when you could just return an empty response which is what the problem is.

**Comment by wing328** [comment]
@kenisteward thanks for the investigation. I'll leave those generators intact.

**Pull request merged**
