### PR TITLE
[Java] Retrofit. Added package paths for retrofit class names

### LINKED ISSUE #3946: [JAVA] Bug generating with retrofit2: package conflict with user classes
##### Description

We have Entity named "Body". Swagger generates class for it `o.swagger.client.model.Body` and import it to retrofit api interface file:
```
import io.swagger.client.model.Body;
```
Name Body conflicts with retrofit body: `retrofit2.http.Body.` which is used without package specification.

```
 @POST("store/products")
  Observable<Product> createBody(
    @Body Body body
  );
``` 
##### Swagger-codegen version

2.2.1

##### Command line used for generation

java with config
```
{
  "library":"retrofit2",
  "useRxJava": true
}
```

##### Steps to reproduce

Create entity with name equals one of retrofit annotation(Body, POST, GET, Multipart, Part)

##### Suggest a Fix

It can be fixed by using full package of classes of retrofit annotations:
 ```
 @POST("store/products")
  Observable<Product> createBody(
    @retrofit2.http.Body Body body
  );
```

### PR DESCRIPTION
**Pull request by punksta**
### Description of the PR
fix #3946

### CODE REVIEW

**Comment by wing328** [comment]
@punksta thanks for the PR. Please run the following to update the Pestore samples so that CI can test the change:
```
java-petstore-retrofit.sh
java-petstore-retrofit2.sh
java-petstore-retrofit2rx.sh
```

**Comment by wing328** [comment]
@punksta it looks like some of the code are no longer indented properly. Have you updated the Petstore sample after removing the newline char in the mustache templates?

**Comment by punksta** [comment]
I have updated it. I don't see a reason of extra space (

**Comment by wing328** [comment]
I've updated the retrofit1,2 samples via https://github.com/swagger-api/swagger-codegen/commit/47d3c3a7678ccd92d829f09d2b8b95a49a38f263.

PR merged into master. Thanks for the contribution.

**Pull request merged**
