### PR TITLE
Clojure client: docstrings tweaks

### PR DESCRIPTION
**Pull request by ianmcorvidae**
Small stylistic improvements detected with `lein check` and `lein eastwood`.

* fix some reflection warnings by specifying the return type of `make-date-format`
* put docstrings/argument lists in the right order for a couple helper functions in core.mustache

### CODE REVIEW

**Comment by wing328** [comment]
@ianmcorvidae thanks for the PR. Would you please update the Petstore sample for Clojure as mentioned in the contribution guidelines? CI will use the updated Petstore sample for testing.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by xhh** [comment]
@ianmcorvidae Thanks!
To update the petstore sample, you could run this in swagger-codegen's root folder:

```shell
mvn clean package
./bin/clojure-petstore.sh
```

**Comment by ianmcorvidae** [comment]
Right, sorry for the delay/my misreading of the guidelines. I'll fix conflicts, build the examples, and re-push this in a bit.

**Comment by ianmcorvidae** [comment]
Looks like the reflection warning aspects were fixed already in master, so this is just some docstring stuff now.

**Comment by xhh** [comment]
Right, I made some same changes in another PR that got merged. Sorry for the confusion.

**Pull request merged**
