### PR TITLE
Added PHP test cases to Travis test suite.

### PR DESCRIPTION
**Pull request by arnested**
This should fail until #1451 is merged.

This is based on how the Perl tests where run and I hope I haven't some fine points in the maven, pom.xml, etc. world which is not my usual ballpark.

### CODE REVIEW

**Comment by arnested** [comment]
It failed as expected.

Now let's wait for #1451. Once it has been merged I'll rebase this pull request and then we'll see whether it will also succeed as expected :smile:

**Comment by arnested** [comment]
I rebased with #1451 merged into master and it failed.

Although that was not what I expected it is not really a surprise either...

It lacks `composer`on the Travis-environment (and would probably miss PHP as well if it passed that step).

So I need to figure out a way also add PHP to the language(s) in `.travis.yml` besides Java. Hmm..

**Comment by wing328** [comment]
@arnested I'm looking into that too. If you're busy with other tasks, please let me know and I'll look into updating .travis.yml to support PHP.

**Comment by arnested** [comment]
Hmm... That would apparently require installing PHP and composer manually via som apt-get in `before_install`: http://zezutom.blogspot.dk/2015/02/travis-ci-and-multi-language-projects.html

I think I'll leave it to you, @wing328, to consider the overall impact on the CI of the project.

Feel free to ask me for feedback etc.

**Comment by wing328** [comment]
Np, I'll take it from here to add PHP to the CI. Once again, appreciate all the effort to improve the PHP API client.

**Pull request closed without merging**
