### PR TITLE
[Java-VertX] Java Vertx client

### PR DESCRIPTION
**Pull request by lopesmcc**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

PR for Issue #6165: Java VertX client, added as a Java generator library named `vertx`.

Known issues:
- multipart-form file uploads are not supported yet by the vertx webclient, which means that generated vertx swagger clients will not support them.

### CODE REVIEW

**Comment by wing328** [comment]
@lopesmcc would the following help with the multipart-form upload?

https://stackoverflow.com/a/36479529/677735

**Comment by wing328** [comment]
@lopesmcc I ran `mvn test` under samples/client/petstore/java/vertx/src/main/java/io/swagger/client but got some errors. Would you please take a look? Part of the errors shown below:
```
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/vertx/src/test/java/io/swagger/client/api/UserApiTest.java:[127,30] method loginUser in interface io.swagger.client.api.UserApi cannot be applied to given types;
  required: java.lang.String,java.lang.String,io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.String>>
  found: java.lang.String,java.lang.String
  reason: actual and formal argument lists differ in length
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/vertx/src/test/java/io/swagger/client/api/UserApiTest.java:[142,12] method logoutUser in interface io.swagger.client.api.UserApi cannot be applied to given types;
  required: io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>>
  found: no arguments
  reason: actual and formal argument lists differ in length
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/vertx/src/test/java/io/swagger/client/api/UserApiTest.java:[159,12] method updateUser in interface io.swagger.client.api.UserApi cannot be applied to given types;
  required: java.lang.String,io.swagger.client.model.User,io.vertx.core.Handler<io.vertx.core.AsyncResult<java.lang.Void>>
  found: java.lang.String,io.swagger.client.model.User
  reason: actual and formal argument lists differ in length
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/vertx/src/test/java/io/swagger/client/api/FakeClassnameTags123ApiTest.java:[32,49] io.swagger.client.api.FakeClassnameTags123Api is abstract; cannot be instantiated
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/vertx/src/test/java/io/swagger/client/api/FakeClassnameTags123ApiTest.java:[46,30] method testClassname in interface io.swagger.client.api.FakeClassnameTags123Api cannot be applied to given types;
  required: io.swagger.client.model.Client,io.vertx.core.Handler<io.vertx.core.AsyncResult<io.swagger.client.model.Client>>
  found: io.swagger.client.model.Client
  reason: actual and formal argument lists differ in length
```

**Comment by lopesmcc** [comment]
@wing328 Re: multipart-form upload, unfortunately the the solution you posted is for the vertx server. 
VertX webclient documentation states:
> at the moment multipart files are not supported, it will likely be supported in a later revision of the API.
(http://vertx.io/docs/vertx-web-client/java/#_writing_request_bodies)

Re: tests, will look into it.

**Comment by lopesmcc** [comment]
@wing328 `mvn test` working now. Changed them to use the VertX unit testing framework. Please review.

**Comment by wing328** [comment]
@lopesmcc we'll document the multipart-form upload as a known issue. The test results look good now. Thanks for the quick fix.
```

Tests run: 5, Failures: 0, Errors: 0, Skipped: 5

[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.510 s
[INFO] Finished at: 2017-07-31T19:56:30+08:00
[INFO] Final Memory: 24M/230M
[INFO] ------------------------------------------------------------------------
```

I can think of some enhancements and will create a new ticket (issue) for tracking.

**Comment by wing328** [comment]
Sent out https://twitter.com/wing328/status/892389393658458112 to promote the new generator

**Comment by vietj** [comment]
would you mind to blog on vertx blog about it ?

**Comment by lopesmcc** [comment]
@vietj I'll try to find some time for that. 👍

**Pull request merged**
