### PR TITLE
Fix class path for DeferredResult

### PR DESCRIPTION
**Pull request by sasavilic**
### PR checklist

See #6451 for more info.
- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@sasavilic please run spring-related petstore scripts to update petstore samples so that CIs can verify the change:
```
./bin/spring-all-pestore.sh
```
cc @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet @ePaul

**Comment by sasavilic** [comment]
@wing328, I did run script and it was successful, but there is no file changes to commit. Am I missing something?

**Comment by lukoyanov** [comment]
It looks like there are no sh scripts that are using `responseWrapper` option set to `DeferredResult` that's why nothing gets changed in samples.

**Comment by wing328** [comment]
@sasavilic I did a test with your PR but got the following errors:
```
[ERROR] return type org.springframework.http.ResponseEntity<java.lang.String> is not compatible with org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity<java.lang.String>>
[ERROR] /private/var/tmp/spring/issue3/src/main/java/io/swagger/api/UserApiController.java:[57,33] getUserByName(java.lang.String,java.lang.String) in io.swagger.api.UserApiController cannot implement getUserByName(java.lang.String,java.lang.String) in io.swagger.api.UserApi
[ERROR] return type org.springframework.http.ResponseEntity<io.swagger.model.User> is not compatible with org.springframework.web.context.request.async.DeferredResult<org.springframework.http.ResponseEntity<io.swagger.model.User>>
```

Here is the config I used for testing:
```
{
    "responseWrapper": "DeferredResult"
}
```
Did you get similar errors when testing locally in your machine?

**Comment by cbornet** [comment]
I haven't tested but the change seems OK

**Comment by wing328** [comment]
Yup, the change also looks good to me but when I tested I got errors.

Btw, doing the same test on master showed different errors, which seem to be fixed by this PR.

**Comment by sasavilic** [comment]
@wing328, yes I think I got same errors. The problem is default interface implementation when java-8 is enabled, since ResponseEntity can't be converted to DeferredResult. I was not sure how to correct default template so that it supports both. 

I want to apologize for not reporting this later in PR. Since merging PR process was to slow, we patched swagger our self (including template for interface implementation (removing default implementation)) and forgot about this PR. 

But I can tell one thing, once the template is fixed, it works like a charm.

**Comment by wing328** [comment]
@sasavilic no problem. We'll merge this one and open a new issue to track the errors I reported.

Thanks again for the PR 👍

**Pull request merged**
