### PR TITLE
Jersey2 issues bis

### PR DESCRIPTION
**Pull request by mamghari**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by mamghari** [comment]
Hi @wing328 could you please validate it ?

Thank you very much ;)

**Comment by wing328** [comment]
@mamghari seems like the rebase is still incorrect, which results in a lot of commits.

I'll try to cherry-pick the commits you made.

**Comment by wing328** [comment]
@mamghari please also describe the issues you're trying to fix.

**Comment by mamghari** [comment]
Hi @wing328 ,

The main important commit is: **commit fd2f60454969e865c8bd2acb038758e47f1b290b**

Please find below what I tried to fix:
- Remove the Jersey1 import packages when generating Jersey2 code => https://github.com/swagger-api/swagger-codegen/issues/4662
- Make Java8 dates working with Jersey2
- Add empty constructor to the model classes to allow serialization/deserialization
- Register the right Jackson module for Java8 and Joda

enjoy ;)

**Comment by wing328** [comment]
@mamghari thanks for the details. I'll review and let you know if you've any question.

**Comment by wing328** [comment]
@mamghari I tried to cherry-picks the commits but got conflicts. Please do the cherry-pick by doing the following:
```
git checkout -b cherrypick_pr5002
git cherry-pick 4444b366a449718d8720d1c6603a08cc2f672dcd
git cherry-pick 528cd7e58d9bcf60ce664640ce232f1b461a4d87
git cherry-pick 2f1a4a150f08a1b11755c17de37d8b8dd7b97794
git cherry-pick fd2f60454969e865c8bd2acb038758e47f1b290b
git cherry-pick 4bc3cf250250064ce2f03233f78ed73416d0e7c8
git cherry-pick 67e54e218733cd30fcdd76de62a8750a99312979
```
Let me know if you need help on this.


ref: https://github.com/swagger-api/swagger-codegen/pull/5002/commits

**Comment by mamghari** [comment]
Thank you for review, I had the bad idea to regenerate sample...

@wing328  do you know **when the release 2.2.3 will be delivered** ?

**Comment by wing328** [comment]
> It is very important for us as we have to release our code.

3 to 4 months.

The fix in 2.2.3 (current master) will be merged into 2.3.0 as well (which is due this month).

Have you tried to create a new branch and try to cherry-pick using the command I provided above (and then file a new PR)?

**Comment by wing328** [comment]
cc @cbornet as the fix is related to datetime in Java clients.

**Comment by mamghari** [comment]
@wing328 ok, let me try the commands :)

**Comment by cbornet** [comment]
Sorry but the log is so messed up that I don't know what I need to review ...

**Comment by wing328** [comment]
@cbornet no worry. @mamghari will create a new one by cherry-picking the commits. Closing this one for the time being.

**Comment by mamghari** [comment]
Thank you all ;)

**Comment by wing328** [comment]
@mamghari I might have missed it. Have you filed a new PR instead?

**Pull request closed without merging**
