### PR TITLE
Typescript-Jquery refactor/improvement proposition

### PR DESCRIPTION
**Pull request by JFCote**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Here is a refactor/improvement for the Typescript-Jquery client generator. The main changes are the inclusion of some concept from the Typescript-Angular2 generator like:
- Improved models
- Multiple files
- Added some options for multiple usage scenario

I would like this to be tested by original contributor @bherila and also by other user of this client to make sure it doesn't break anything on their sides.

This is just a first step, my team and I have many other ideas for this generator to make it better but unfortunately we don't have a lot of time right now so this will be this version for now. I will be more than pleased to fix any bug that could be found to make it to the master.

I don't think it introduce breaking changes, that's why the pull request is done on the master. If it introduce breaking changes, let me know and we'll see if the PR needs to be done to 2.3 instead.

Thanks!

### CODE REVIEW

**Comment by wing328** [comment]
@JFCote thanks for the enhancement.

@bherila would you please take a look when you've time?

**Comment by JFCote** [comment]
Since we don't have news from @bherila , I have added a small improvement :)

**Comment by bherila** [comment]
Sorry for being afk for a while. However, I have deprecated my own use of jquery in favor of the fetch-based API.

**Comment by JFCote** [comment]
@wing328 : So what do we do? The best would be to have a user of the current version test the new version and make sure there is no breaking change. Or we could submit this to the 2.3.0 branch

**Comment by wing328** [comment]
@JFCote to play safe, we can submit this for 2.3.0 branch.

When you've time, it would be nice to add Petstore integration tests similar to what've done for TS Fetch: https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/typescript-fetch/tests/default

**Comment by JFCote** [comment]
I'm very busy right now, will try to do it in the upcoming days/week. Sorry for de delay!

**Comment by JFCote** [comment]
@wing328 How do I submit this to 2.3.0. Do I start a new PR or can I edit this one?

**Comment by wing328** [comment]
@JFCote you can edit the subject line and you will see a drop down menu to target a different branch.

**Comment by JFCote** [comment]
I have changed it to 2.3.0. I don't have time to create the petstore integration for the moment.

**Comment by wing328** [comment]
@JFCote PR merged into 2.3.0. Please create the Petstore integration tests later when you've time.

**Pull request merged**
