### PR TITLE
added some useful log/output messages and exception handling

### PR DESCRIPTION
**Pull request by F481**

### CODE REVIEW

**Comment by wing328** [comment]
@F481 thanks for the PR to output more useful info. I did a test and got the following:
```
swagger-codegen|master ⇒ ./bin/java-petstore.sh 
reading from modules/swagger-codegen/src/test/resources/2_0/petstore.json
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/User.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Category.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Pet.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Tag.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/model/Order.java
727 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet	;put io.swagger.models.Operation@30509569

736 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet	;post io.swagger.models.Operation@7c4c47f4

737 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet/findByStatus	;get io.swagger.models.Operation@8f6df775

775 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet/findByTags	;get io.swagger.models.Operation@8f46d169

784 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet/{petId}	;get io.swagger.models.Operation@799b94c0

790 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet/{petId}	;post io.swagger.models.Operation@b58ca5c9

796 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet/{petId}	;delete io.swagger.models.Operation@ee3edb02

801 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /pet/{petId}/uploadImage	;post io.swagger.models.Operation@49567a66

807 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /store/inventory	;get io.swagger.models.Operation@bf47803d

813 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /store/order	;post io.swagger.models.Operation@1bc80d64

820 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /store/order/{orderId}	;get io.swagger.models.Operation@5f24b595

824 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /store/order/{orderId}	;delete io.swagger.models.Operation@d817c461

827 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user	;post io.swagger.models.Operation@200bea54

828 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/createWithArray	;post io.swagger.models.Operation@d2fc71d

834 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/createWithList	;post io.swagger.models.Operation@7e9e10d4

840 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/login	;get io.swagger.models.Operation@43126f72

844 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/logout	;get io.swagger.models.Operation@6c117d22

845 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/{username}	;get io.swagger.models.Operation@835abe8f

852 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/{username}	;put io.swagger.models.Operation@244fe29f

853 [main] INFO io.swagger.codegen.DefaultGenerator - processOperation: resourcePath= /user/{username}	;delete io.swagger.models.Operation@87fb7859

writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/api/UserApi.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/api/PetApi.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/api/StoreApi.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/pom.xml
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiClient.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/ApiException.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/Configuration.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/JSON.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/Pair.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/StringUtil.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/TypeRef.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/Authentication.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/HttpBasicAuth.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/ApiKeyAuth.java
writing file /private/var/tmp/F481/swagger-codegen/samples/client/petstore/java/default/src/main/java/io/swagger/client/auth/OAuth.java
```
Instead of using LOGGER.info, what about using LOGGER.debug to show the `[main] INFO io.swagger.codegen.DefaultGenerator - processOperation` when the debug flag is on ? (the debug flag needs to be added and obtained from the command line, e.g. via the -d option)

**Comment by F481** [comment]
What debug flag do you exactly mean? debugOperations?

So it should look like this?
```if (System.getProperty("debugOperations") != null) {    
     +            LOGGER.debug("processOperation: resourcePath= " + resourcePath + "\t;" + httpMethod + " " + operation + "\n");
}```

**Comment by wing328** [comment]
Yes, I think debugOperations would fit the use case: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java#L160

**Comment by F481** [comment]
Added the code snippet with my last commit.

**Pull request merged**
