### PR TITLE
Add alias type definitions for Java

### PR DESCRIPTION
**Pull request by bbdouglas**
When a spec defines a Model at the top level that is a non-aggretate type (such
as string, number or boolean), it essentially represents an alias for the simple
type. For example, the following spec snippet creates an alias of the boolean
type that for all intents and purposes acts just like a regular boolean.

    definitions:
      JustABoolean:
        type: boolean

This can be modeled in some languages through built-in mechanisms, such as
typedefs in C++. Java, however, just not have a clean way of representing this.

This change introduces an internal mechanism for representing aliases. It
maintains a map in DefaultCodegen that tracks these types of definitions, and
wherever it sees the "JustABoolean" type in the spec, it generates code that
uses the built-in "Boolean" instead.

This functionality currenlty only applies to Java, but could be extended to
other languages later.

The change adds a few examples of this to the fake endpoint spec for testing,
which means all of the samples change as well.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This is a fix to #5382. It creates an internal mapping between top-level, simple type definitions and their corresponding simple types. When code is generated, only the simple types are emitted, essentially erasing the type from the API.

I also investigated creating wrapper classes instead, to reduce confusion of the class names disappearing. However, the Java language makes this awkward, for example the fact that subclasses do not inherit constructors from their parents and lack of operator overloading. This makes the classes difficult to write in a generic way and bulky to use.

The change looks large, but actually the code change inside modules/ is relatively small and the rest is changes to the samples. The samples changed because I added a few testing endpoints to the sample yaml spec. The java feign client contains the built-out tests. The generated code is not affected if there are no top-level model definitions of simple types (which is by far the most common case). I re-generated the samples by running bin/run-all-petstore.

### CODE REVIEW

**Comment by bbdouglas** [comment]
The latest CI issue seems to be a transient one. One of the two jobs passed, and the other one failed with this error:

    npm ERR! Linux 4.4.0-51-generic
    npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" 
    "/home/travis/.nvm/versions/node/v4.1.2/bin/npm" "install"
    npm ERR! node v4.1.2
    npm ERR! npm  v2.14.4
    npm ERR! code ECONNRESET
    npm ERR! errno ECONNRESET
    npm ERR! syscall read

    npm ERR! network read ECONNRESET
    npm ERR! network This is most likely not a problem with npm itself
    npm ERR! network and is related to network connectivity.
    npm ERR! network In most cases you are behind a proxy or have bad network settings.
    npm ERR! network 
    npm ERR! network If you are behind a proxy, please make sure that the
    npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

**Comment by wing328** [comment]
@bbdouglas thanks for the PR. The CI issue is tracked via https://github.com/swagger-api/swagger-codegen/issues/5304

cc @cbornet @ePaul for review.

**Comment by cbornet** [comment]
It's not common to alias a model to a native type ! Is there really an interest of doing so ?

**Comment by ePaul** [comment]
I didn't look at the code yet, but to answer @cbornet, I think there are two main use cases for a named model definition (i.e. under `definitions`) with a non object/array schema:

* Describing an enum – often strings, sometimes with numbers as values. I think this is handled by Swagger-Codegen, in the Java case by generating an `enum` class.
   (OpenAPI/JSON schema even allows mixed enums and enums with object values, I think this is not supported by Swagger Codegen yet.)
* Adding meta data (e.g. title, description) or restrictions (minimum, maximum, pattern, minLength, maxLength) to the primitive type. Of course there is not strictly a need to have this as a separate definition, you could as well inline it, but it is useful to help with the DRY principle if you have the same type of value in several places.

I didn't yet have a look if the latter is actually supported by this pull request, or if it just supports a simple aliasing.

**Comment by bbdouglas** [comment]
Thank you for the review. I agree that the two main use cases are defining enums and adding metadata/validation to a primitive type. The enum case is already supported and this PR adds support for the second. It is this second case that I ran into in my work.

One could imagine scenarios such as numbers for person height and weight aliased as "HeightInCm" and "WeightInKg" with restrictions about being within a certain range. Or a string value such as "SKU" for product numbers, which are validated against a certain regex pattern. Once defined, they can be referenced in multiple places in the API.

**Comment by bbdouglas** [comment]
It strikes me that this giant PR is 1% code change and 99% additional generated code for testing. Perhaps it would be easier to review if I split it into two PR's: one for the code change and the other for the samples generated from the new testing endpoint.

What do you think?

**Comment by ePaul** [comment]
@bbdouglas I think changes of samples caused by code changes should be in the same PR.
On the other hand, adding new samples could be in a separate PR – if so, I would add those first with the old generation code, so we later can see the differences.

**Comment by bbdouglas** [comment]
@ePaul That sounds good. I'll work on a separate PR for generating the new test endpoints with the old code, then update this PR to show the changes.

**Comment by wing328** [comment]
If no one has further question or feedback, I'll take another look tomorrow (Thur) and merge accordingly.

**Pull request merged**
