### PR TITLE
Fix some bugs for the R client

### PR DESCRIPTION
**Pull request by jschelbert**
* Fix bugs in api.mustache, model.mustache, mostly bracket errors or …small typos
* Added section about installation in README.mustace

Remaining TODOs for #6520
TODO: fix tests in testthat
TODO: fix bug in description.mustace regarding package name

### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by jschelbert** [comment]
Hi,
I added the email address as secondary to my github account. Hopefully this already fixes it...

**Comment by wing328** [comment]
Yup, the commit is now correctly linked to your github acccount

cc @ramnov @cannin

**Comment by wing328** [comment]
@jschelbert would you please also run `./bin/r-petstore.sh` or `.\bin\windows\r-petstore.bat` to update the R Petstore samples?

**Comment by jschelbert** [comment]
Do you need all files generated by the command? There seem to be some that are currently in the folder but are not generated via the command above. Others are not yet in the repository but are generated by the command.

**Comment by wing328** [comment]
Please commit the new files as well.

**Comment by jschelbert** [comment]
Mmh, seems Travis is having some kind of trouble. I'm pretty sure this has nothing to do with the changes made in this PR. How can we check whether this is caused by some other issue or if it is really related to changes introduced in the PR?

**Comment by wing328** [comment]
I've restarted the Travis job. Let's see how it goes.

**Comment by wing328** [comment]
If no one has further feedback or question, I'll merge this tomorrow.

**Comment by wing328** [comment]
@jschelbert Thanks for the PR, which has been merged into master.

Also thanks @albsantosdel for testing the PR.

**Pull request merged**
