### PR TITLE
Typescript angular2 typings

### PR DESCRIPTION
**Pull request by BastiOfBerlin**
This also removes the dependency to the typings project.
Issue #4761 

### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This PR changes the way typescript's typings are resolved, from the old-way of utilizing the typings project to using @types/* npm packages, which is the default way for typescript2.

A big drawback of the typings project was that it could not be installed offline and relied on an own registry.

The README has also been updated to reflect the changes, outline the use of `@angular/cli`'s environments and show how to use `npm link`.

### CODE REVIEW

**Comment by BastiOfBerlin** [comment]
Since this might be a breaking change (depending on typescript 2), I filed the PR against 2.3.0, but I developed against master, resulting in a bunch of conflicting files. Hope you can help to merge? @wing328 ?

**Comment by kenisteward** [comment]
@BastiOfBerlin I have made a PR that I expect will be merged soon either to this or to master.  (#4766)  In that it changes the abstract typescript to generate typings for all.  I will be making another PR to update those to only use @types instead but this should be done at the Abstract scale not per client

**Comment by BastiOfBerlin** [comment]
@kenisteward When do you expect this to work? Maybe it makes sense to work together?

**Comment by wing328** [comment]
@BastiOfBerlin Seems like the rebase failed and the PR is showing a lot of commits.

Do you mind submitting another PR for the enhancement instead?

**Comment by wing328** [comment]
@BastiOfBerlin I think what I'll do is to cherry-pick https://github.com/swagger-api/swagger-codegen/pull/4795/commits/9444c4937626227c0b912280416cca7df7d526d3

**Comment by wing328** [comment]
@kenisteward are you ok if I just cherry-pick `9444c49`?

For https://github.com/swagger-api/swagger-codegen/pull/4766#issuecomment-302214692, if you've completed the test and it's ready for merge, let me know.

**Comment by kenisteward** [comment]
@wing328 looking at 9444c49  it looks like you should be able to chery-pick it okay.

As far as #4766 goes I have not tested with all current changes yet. I may have time next week to do this but I will be in the middle of trying to integrate the changes from SCGen 2.3.0 into our build process.

**Comment by wing328** [comment]
@kenisteward thanks for reviewing. I'll do it tomorrow with a new PR

cc @BastiOfBerlin

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5966

**Pull request closed without merging**
