### PR TITLE
Feature/objc tasks

### PR DESCRIPTION
**Pull request by wberger**
I propose a change to the objc ApiClient. Instead of internally created and maintained request IDs the API implementation should return NSURLSessionTasks. This change has two advantages:
- Less internal state
- These task object provide real cancellation as compared to the request ID based implementation (even if the task is currently running)

Furthermore I changed the configuration object to be protocol based in order to allow for more flexible integration into projects and more complex configuration setups. A default configuration implementation is provided and can be passed in, if no custom implementation is required.

Finally I renamed the ApiClient to ApiSessionManager to go with the AFNetworking wording.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @mateuszmackowiak

**Comment by wberger** [comment]
@wing328 Thank you for pointing this out, I added a secondary e-mail address to my account.

**Comment by wing328** [comment]
@wberger I ran the integration test for `default` and got the following error:
```
Testing failed:
	Receiver 'SWGConfiguration' for class message is a forward declaration
	No known class method for selector 'sharedConfig'
	Property 'tempFolderPath' cannot be found in forward class object 'SWGConfiguration'
	Receiver type 'SWGConfiguration' for instance message is a forward declaration
	Property 'sslCaCert' cannot be found in forward class object 'SWGConfiguration'
	Property 'sslCaCert' cannot be found in forward class object 'SWGConfiguration'
	Property 'verifySSL' cannot be found in forward class object 'SWGConfiguration'
	Receiver 'SWGConfiguration' for class message is a forward declaration
	No known class method for selector 'sharedConfig'
** TEST FAILED **
```

For more information about ObjC client's integration test, please refer to https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-do-i-run-integration-test-with-petstore-objc-api-client

**Comment by wberger** [comment]
@wing328  Thanks for merging! Do you still need input on the failing integration test?

**Comment by wing328** [comment]
@wberger I merged it by mistake. Can you look into the integration test and update the tests accordingly?

**Comment by wing328** [comment]
@wberger It looks like this change is a breaking one (non-backward compatible) so I think what I will do it to rollback this change and target v2.3.0 instead as next release v2.2.1 is a patch release aiming for non-breaking changes only.

**Comment by wberger** [comment]
@wing328 I'm currently working on making it non-breaking by making the following changes:

- Rename ApiSessionManager back to ApiClient. This is also a better naming in the Swagger context
- Create a default initializer for the Api classes

**Comment by wberger** [comment]
On hindsight, it is a breaking change anyway (due to the api change). So v2.3.0 is the correct target.

**Comment by wing328** [comment]
Reverted via https://github.com/swagger-api/swagger-codegen/pull/3501

Please submit another PR for branch `2.3.0` when you've time.

You may also want to review the auto-generated doc to ensure the code samples are correct after your change.

**Comment by wberger** [comment]
@wing328 I have created a new PR #3510 for branch `2.3.0`.

**Pull request merged**
