### PR TITLE
[PHP] Better PSR2 compatibility

### PR DESCRIPTION
**Pull request by dkarlovi**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

These changes fix the emitted PHP compatibility with the declared [PHP-FIG's PSR2 coding style](http://www.php-fig.org/psr/psr-2/). This can be verified by using the standard tool for the task in the PHP ecosystem, [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer), for which the configuration has also been included with the `.php_cs` file.

To verify compatibility, run as follows:

    # run swagger-codegen as usual

    # install dev dependencies, which now includes PHP-CS-Fixer
    composer install

    # run PHP-CS-Fixer which should NOT alter any files at all
    vendor/bin/php-cs-fixer fix --dry-run --diff -vvv

### Notes

 - as the emitted code required PHP 5.4 in `composer.json`, array notation has been switched to new short array syntax introduced in [PHP 5.4](http://php.net/manual/en/language.types.array.php) to better match new best practices, this has also been enforced in `.php_cs`
 - additional custom fixers (see [PHP-CS-Fixer's Usage](https://github.com/FriendsOfPHP/PHP-CS-Fixer#usage)) have been enabled to make output more strict (and thus more predictable)

### CODE REVIEW

**Comment by dkarlovi** [comment]
Please not, I did run `bin/php-petstore.sh`, but did not commit its output. Don't know if it's required, please advise. Tnx.

**Comment by cbornet** [comment]
Yes, you should commit it so that your PR is tested by CI

**Comment by dkarlovi** [comment]
@cbornet thanks, done.

**Comment by wing328** [comment]
@dkarlovi thanks for the PR.

For `array()` replaced by [], shall we keep `array()` to make it compatible with PHP version before 5.4? This is not to say we officially support 5.3 or older version but just that people can still use it (without any support from us) in case they're still using 5.3 or older version in their environment.

Ref: http://php.net/manual/en/language.types.array.php
>As of PHP 5.4 you can also use the short array syntax, which replaces array() with [].

cc @arnested

**Comment by dkarlovi** [comment]
@wing328 I'm fine either way, but, the way I see it, if the [declared requirement in composer.json is 5.4](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/composer.json#L19), you can expect it will not work out of the box with 5.3.

What we could do is add a blurb on how to convert it to classic array syntax by using [PHP-CS-Fixer's `long_array_syntax` fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer#user-content-usage). This way you don't officially support PHP 5.3, but users can work around that (as they do right now anyway).

**Comment by arnested** [comment]
This looks really fine to me. Nice job, @dkarlovi.

I'm still in the habit of using `array()`.

But I think we should just move on and go all in on our 5.4 dependency and embrace `[]`. It's time to move on and we probably haven't many users stuck on 5.3 but depending on updated versions og codegen

**Comment by wing328** [comment]
OK. Let's move forward with this :)

**Comment by wing328** [comment]
@dkarlovi btw, I was not able to run the following:
```
vendor/bin/php-cs-fixer fix --dry-run --diff -vvv
```
`vendor/bin/phpcs` is available instead. Maybe it's because I'm using the latest version (2.7.0)

**Comment by dkarlovi** [comment]
Thanks, @arnested.

@wing328 after you run `composer install`, you must have it as [it has been added as a dev dependency](https://github.com/swagger-api/swagger-codegen/pull/3863/files#diff-a353e6b2ddd416adfb7195304c40a234R31). Then you'll have the command.

Thanks for the merge.

**Comment by wing328** [comment]
@dkarlovi I did but no luck:
```
SwaggerClient-php|master⚡ ⇒ vendor/bin/phpcs --version
PHP_CodeSniffer version 2.7.0 (stable) by Squiz (http://www.squiz.net)
```

**Comment by dkarlovi** [comment]
@wing328 have you re-generated the `composer.json` file? Also, if you have `composer.lock`, Composer will warn you it's out of date, but still do as it says (and not install `php-cs-fixer`). Please remove it (or run `composer update` to update it).

`phpcs` is another tool altogether and not related here.

**Comment by wing328** [comment]
@dkarlovi ok, will give it another try with a new PHP SDK. If you don't hear from him, you can assume I don't encounter any issue :)

**Comment by dkarlovi** [comment]
@wing328 if you still have an issue, I'll verify that it's not in my code and file a new PR to fix it if it is. :)

**Comment by arnested** [comment]
`composer.lock` was why it didn't install `php-cs-fixer` for me at first. I deleted it  and ran `composer install` again.

**Pull request merged**
