### PR TITLE
[Swift] fix issue 1989: generate AnyObject type from json object type instead…

### PR DESCRIPTION
**Pull request by jaz-ah**
… of generating strings

See https://github.com/swagger-api/swagger-codegen/issues/1989

Tested with various types of json files to ensure correct creation of AnyObjects from object types.  

Note that decoder also decodes correctly where it used to produce this for the example given in the above issue:
	instance.Data = Decoders.decode(clazz: String.self, source: sourceDictionary["Data"]!)
and now will produce:
	instance.Data = Decoders.decode(clazz: AnyObject.self, source: sourceDictionary["Data"]!)

### CODE REVIEW

**Comment by wing328** [comment]
@jaz-ah thanks for adding the unit tests :beers: 

I ran `mvn integration-test` under `samples/client/petstore/swift/SwaggerClientTests` but got the following errors:
```
Downloading dependencies
Using Alamofire (3.1.5)
Using OMGHTTPURLRQ (3.1.1)
Using PetstoreClient (0.0.1)
Using PromiseKit (3.0.2)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 4 total pods installed.
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (xcodebuild-test) @ SwiftPetstoreClientTests ---
xcodebuild: error: The workspace named "SwaggerClient" does not contain a scheme named "SwaggerClient". The "-list" option can be used to find the names of the schemes in the workspace.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.652 s
[INFO] Finished at: 2016-02-09T20:45:18+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (xcodebuild-test) on project SwiftPetstoreClientTests: Command execution failed. Process exited with an error: 65 (Exit value: 65) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

The error message is `The workspace named "SwaggerClient" does not contain a scheme named "SwaggerClient".`.

Did you run into similar issue in your machine?

**Comment by jaz-ah** [comment]
@wing328 sorry I forgot to share the scheme - pushed that change out now so it should build ok for you.

**Comment by wing328** [comment]
@jaz-ah no worry. let me give it another try ...

**Comment by wing328** [comment]
@jaz-ah Swift test cases ran without issue in my machine:
```
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' passed (0.440 seconds).
Test Suite 'UserAPITests' passed at 2016-02-10 00:38:51.572.
	 Executed 5 tests, with 0 failures (0 unexpected) in 2.217 (2.220) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2016-02-10 00:38:51.573.
	 Executed 11 tests, with 0 failures (0 unexpected) in 5.004 (5.014) seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:24 min
[INFO] Finished at: 2016-02-10T00:38:51+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```

Thanks again for the contribution :smile:

**Pull request merged**
