### PR TITLE
[Python/tornado] add integration tests and fix bugs

### LINKED ISSUE #6924: [Python/tornado] generated code does not work
##### Description

Generated python-tornado client doesn't work. 

##### Swagger-codegen version

From `master`.

##### Command line used for generation

`bin/python-tornado-petstore.sh` which produces samples/client/petstore/python-tornado/

##### Steps to reproduce

I have a problem with initializing SSL

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import petstore_api
>>> petstore_api.ApiClient()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "petstore_api/api_client.py", line 71, in __init__
    self.rest_client = rest.RESTClientObject(configuration)
  File "petstore_api/rest.py", line 62, in __init__
    self.ssl_context = ssl.SSLContext()
TypeError: __new__() takes at least 2 arguments (1 given)
```

and also with returning a value

```python
from functools import partial
from tornado.ioloop import IOLoop
import petstore_api
from petstore_api import Configuration

config = Configuration()
config.host = 'http://petstore.swagger.io/v2'
api_client = petstore_api.ApiClient(config)
pet_api = petstore_api.PetApi(api_client)

resp = IOLoop.current().run_sync(partial(pet_api.find_pets_by_status, 'sold'))
print(resp)  ## none!
```

##### Suggest a fix/enhancement

Add tests and fix it.

### PR DESCRIPTION
**Pull request by tomplus**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

Generated python-tornado client doesn't work. In this PR I add some tests (adopted from the main python client library) and fix code.

Fix #6924

### CODE REVIEW

**Comment by tomplus** [comment]
Please take a look @taxpon @frol @mbohlool @cbornet @kenjones-cisco 
CC @wing328

**Comment by frol** [comment]
Looks good to me!

@tomplus Thank you!

**Comment by kenjones-cisco** [comment]
LGTM!

**Comment by tomplus** [comment]
Thanks for your feedback.

**Comment by wing328** [comment]
FYI. Added python-tornado petstore client to Travis CI via 90a0b7a

**Comment by wing328** [comment]
cc @toumorokoshi

**Pull request merged**
