### PR TITLE
add upload & downlod progress for Java okhttp

### PR DESCRIPTION
**Pull request by zxy198717**
Add progress support for java okhttp.

### CODE REVIEW

**Comment by wing328** [comment]
@zxy198717 thanks for the PR.

Do you mind updating the samples for Java (okhtttp) client? 

More info can be found in https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by zxy198717** [comment]
@wing328 Sorry for this mistake.
I have updated sample & test. 
Please check.

**Comment by wing328** [comment]
@zxy198717 not a mistaken at all :)

We'll check and let you know if we've any questions.

**Comment by wing328** [comment]
@zxy198717 please rebase to resolve the merge conflicts

**Comment by zxy198717** [comment]
@wing328 done.

**Comment by wing328** [comment]
I still see "This branch has conflicts that must be resolved"

Did you run something like "git pull upstream master" to get the latest change from swagger-codegen master?

**Comment by zxy198717** [comment]
@wing328 merged.

**Comment by wing328** [comment]
@zxy198717 thanks. Will merge later today.

**Pull request merged**
