### PR TITLE
Support jaxrs cxf

### PR DESCRIPTION
**Pull request by hiveship**
Add a new Codegen to handle support for JAX-RS Apache CXF support.

### CODE REVIEW

**Comment by hiveship** [comment]
@wing328 How can I get more logs to check the build on Travis CI ? It's failing and I don't understrand why, everything looks fine during my local builds. I need more information to correct my PR :/

**Comment by fehguy** [comment]
I will restart the build, I believe this is cause by something outside of your control.

**Comment by hiveship** [comment]
I updated my branch to resolve conflicts :)
@wing328 if it's a problem to get more commits in this PR, can I let you do the cherry-pick to pick only the good commits ? Last time I tried, I just crashed my repo :/

This PR should includes all my commits excepted  4679392.

Please let me know if I need to do anything else to help you accepting this PR :)

**Comment by hiveship** [comment]
@wing328 I understand now why there is more commits. When I update my repo from the swagger-api/swagger-codegen/master, it includes all the new commits :) 
So in this PR, I don't think it's a problem since those commits are already included & validated :)

**Comment by hiveship** [comment]
@wing328 The build seems to fail because of another modification not linked to my work.
In the trace I can see:

```
java.lang.RuntimeException: Can't load config class with name go Available: android
```

**Comment by wing328** [comment]
Go API client was just merged into master a few hours ago.

Did you do a rebase on the latest master?

**Comment by hiveship** [comment]
Yes, I updated my repo from master

**Comment by wing328** [comment]
I don't think you're doing the rebase correctly as it's showing commits not done by you.

**Comment by wing328** [comment]
I'll spend sometime this weekend to cherry-pick your commits.

**Comment by hiveship** [comment]
@wing328 many thanks :) I will check tomorow my soft, I think you are right, I am not doing te rebase correctly. I think I always do a merge with the upstream master instead of a rebase.

**Pull request closed without merging**
