### PR TITLE
[csharp] Clean up ref/inner enum structure

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

This is a continuation of #6851, filed as a separate PR so we can have discussion of whether this is an appropriate workaround without blocking #6851. If this gets merged, it'll likely cause conflicts with #6873 (another continuation PR of #6851 for community discussion).

Enums defines as ref models have a different object structure
(CodegenModel) than those defined as inner enums (CodegenProperty). To
make these look as similar as possible, we walk all ref model enums and
reassign enumVars with the same properties inherited from the top level
CodegenProperty so CodegenModel enums can use the same templates as
inner enums

This PR is an attempt to resolve a question/comment in #5352 by @larssb.

/cc @mandrean

### CODE REVIEW

**Comment by jimschubert** [comment]
Test case against spec at:

Generate with:
```
generate -l csharp -o out -i https://gist.githubusercontent.com/larssb/d00e4cf200d85423152df75703d84076/raw/17bb6550e1249b19ebfb215f87cf4132caab6149/octopusdeployOpenApi.json
```

Then, compile:
```
cd out && sh build.sh
```

Evaluate:
```
$ csharp -r:bin/IO.Swagger.dll -r:bin/Newtonsoft.Json.dll -r:bin/RestSharp.dll
```

image

**Comment by jimschubert** [comment]
I've removed the `wip` on this, as I revisited and it seems to be a pretty good approach. I'll need to resolve merge conflicts in the next day or so.

**Comment by jimschubert** [comment]
I haven't regenerated samples in this branch because there are multiple issues that I fixed in #6899.

**Comment by copperorange** [comment]
Hi,

I just tried C# Enums again after having trouble before. I am experiencing the same issue as #5352 specifically [https://github.com/swagger-api/swagger-codegen/issues/5352#issuecomment-335444175](url) where generating netcore code from editor.swagger.io with the following schema

`# Enums
    StateHintEnum:
      type: string
      enum:
        - insert
        - update
        - delete`

is generating 

` /// <summary>
        /// Gets or Sets StateHintEnum
        /// </summary>
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum StateHintEnum
        {
            /// <summary>
            /// Enum INSERT for "insert"
            /// </summary>
            [EnumMember(Value = ""insert"")]
            INSERT = 0,
            /// <summary>
            /// Enum UPDATE for "update"
            /// </summary>
            [EnumMember(Value = ""update"")]
            UPDATE = 1,
            /// <summary>
            /// Enum DELETE for "delete"
            /// </summary>
            [EnumMember(Value = ""delete"")]
            DELETE = 2        }`

Each of the values has a [double quote] "" on either side of the value which fails at compile time.

Please advise if there is any way to correctly format the codegen.

**Pull request merged**
