### PR TITLE
[JAVA][SPRING-MVC]Top enum  and securityscope newline cause invalid auto-generated java code during springmvc code generation

### PR DESCRIPTION
**Pull request by beingcoder**
Two issues found during spring-mvc code generation:
1,for top enum definition, either enum parameter or enum model definition,  auto-generated code is invalid.
2,when security.scope. description has a precedent '|' ,newline in markdown, generated api will break as an extra newline is added between "description".

a sample yaml file attached.
1.user-enum&user-type enum type will generate invalid classes.
2.below | will add a unexpected newline between "string",   make java code invalid.
	AppIdTrust: |
        Validate authenticity.

#
# Copyright
#
swagger: '2.0'

################################################################################
# API Information
################################################################################
info:
  version: "2.0.0"
  title: test API
  description: |
    The descripton

    ## HTTP Response Codes
    All operations in this service conform to the following response code
    structure.  Refer to the table below for a brief description of each.

    HTTP Response Code | Description
    -------------------|---------
    200                | The request has been fulfilled successfully
    503                | The server is currently unable to handle the request due to a temporary overloading or maintenance of the server

################################################################################
# Host, Base Path, Schemes and Content Types
################################################################################
host:
  # DEV
  testApp.com
basePath:
  /test/v2
schemes:
  - https
produces:
  - application/json
consumes:
  - application/json

################################################################################
# Security
################################################################################
securityDefinitions:
  oauth:
    type: oauth2
    flow: implicit
    authorizationUrl: https://oauthr/?username=srvAPxxxxxxENV&password=xxxxxxx&client_id=CLIENT-ID&client_secret=CLIENT-SECRET&grant_type=password
    scopes:
      AppIdTrust: |
        Validate authenticity.
  Bearer:
    name: Authorization
    in: header
    type: apiKey
security:
  - oauth:
    - AppIdTrust
  - Bearer: []

################################################################################
# Tags
################################################################################
tags:
  - name: testAction

################################################################################
# Parameters
################################################################################
parameters:
  user-id:
    name: user-id
    in: header
    description: Customer id
    type: string
    required: false
  user-type:
    name: user-type
    in: header
    description: Customer type
    type: string
    required: true
    enum:
      - RETAIL
      - WHOLESALE
      - UNKNOWN

################################################################################
# Paths
################################################################################
paths:
  /plan:
    parameters:
      # Mandatory
      - $ref: '#/parameters/user-type'
    get:
      security:
        - oauth:
          - AppIdTrust
        - Bearer: []
      tags:
        - testAction
      description: |
        The test description
      responses:
        200:
          description: Plan data
          schema:
            $ref: '#/definitions/GeneralResponse'
        503:
          description: The server is currently unable to handle the request due to a temporary overloading or maintenance of the server

################################################################################
# Definitions
################################################################################
definitions:
  #----------------------------------------------------------------------------
  # Base Types
  #----------------------------------------------------------------------------

  GeneralResponse:
    type: object
    description: |
      Generic object
    required:
      - code
      - value
    properties:
      code:
        type: string
      value:
        type: string

  user-enum:
    description: Customized enum type
    type: string
    enum:
      - RETAIL
      - WHOLESALE
      - UNKNOWN

### CODE REVIEW

**Comment by wing328** [comment]
For 1, it should be fixed by https://github.com/swagger-api/swagger-codegen/pull/3511. Please pull the latest master to give it a try.

For 2, it would be helpful if you can share the spec via gist.github.com so that we can more easily reproduce the issue.

**Comment by beingcoder** [comment]
thanks,    but gist is not available for me,   the issue occurs  when there is pipe at the beginning of the description of SecurityDefinition/scope, like below

scopes:
   AppIdTrust: |
      Validate authenticity.

**Comment by wing328** [comment]
OK. No worry. I'll try to reproduce it.

**Comment by wing328** [comment]
I've merged your fix for description into master: https://github.com/swagger-api/swagger-codegen/commit/79385aa503fa8f0b949dbbffec4a7903fa28cb94.

For header enum value, I'll perform more tests.

**Comment by beingcoder** [comment]
thanks.

**Pull request merged**
