### PR TITLE
Update swagger-codegen-maven-plugin example to use current dependencies

### LINKED ISSUE #3261: Example swagger-codegen-maven-plugin/examples/java-client.xml is out of date
Example dependencies from [swagger-codegen-maven-plugin/examples/java-client.xml](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen-maven-plugin/examples/java-client.xml) do not work correctly.

I had to use the generation webservice to extract a pom with the proper dependencies for jersey2

They should be changed to something like this if they are indeed the best practices:

``` xml
<!-- HTTP client: jersey-client -->
    <dependency>
      <groupId>org.glassfish.jersey.core</groupId>
      <artifactId>jersey-client</artifactId>
      <version>${jersey-version}</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jersey.media</groupId>
      <artifactId>jersey-media-multipart</artifactId>
      <version>${jersey-version}</version>
    </dependency>
    <dependency>
      <groupId>org.glassfish.jersey.media</groupId>
      <artifactId>jersey-media-json-jackson</artifactId>
      <version>2.22.1</version>
    </dependency>

    <!-- JSON processing: jackson -->
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>${jackson-version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-annotations</artifactId>
      <version>${jackson-version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-databind</artifactId>
      <version>${jackson-version}</version>
    </dependency>
    <dependency>
      <groupId>com.fasterxml.jackson.datatype</groupId>
      <artifactId>jackson-datatype-joda</artifactId>
      <version>2.1.5</version>
    </dependency>
    <dependency>
      <groupId>joda-time</groupId>
      <artifactId>joda-time</artifactId>
      <version>${jodatime-version}</version>
    </dependency>

    <!-- Base64 encoding that works in both JVM and Android -->
    <dependency>
      <groupId>com.brsanthu</groupId>
      <artifactId>migbase64</artifactId>
      <version>2.2</version>
    </dependency>

    <!-- test dependencies -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit-version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <properties>
    <swagger-core-version>1.5.8</swagger-core-version>
    <jersey-version>2.22.2</jersey-version>
    <jackson-version>2.7.0</jackson-version>
    <jodatime-version>2.9.3</jodatime-version>
    <maven-plugin-version>1.0.0</maven-plugin-version>
    <junit-version>4.12</junit-version>
  </properties>
```

### PR DESCRIPTION
**Pull request by Trii**
@wing328 I did a little dance and added a step in the travis build to verify. I had to remove the test scope from the junit dependency because `mvn swagger-codegen:generate` would complain about `Test` not being found. Same thing for moving `<configuration>` out of `<executions>` and into the main plugin block.

Java isn't my strong suit so feel free to tear it apart.

Fixes #3261

### CODE REVIEW

**Comment by wing328** [comment]
@Trii thanks for the PR. We'll review and let you know if we've any question

cc @ePaul 

(for your next PR, I would suggest creating a new branch instead of making the change in master as per git best practices)

**Comment by Trii** [comment]
@wing328 I would still have to PR my feature branch against master here. I don't have edit rights to this repo to make a branch.

Let me know if it needs work!

**Comment by ePaul** [comment]
@Trii the feature branch convention (in your own fork) is mainly so the branch gets a nicer name (and thus looking at the history, the merge commit message is nicer). Also, it allows you to update your master to upstream's master without affecting the feature branch.

**Comment by Trii** [comment]
Fair enough. You should update the contributing details to spell that out. The line about create your own branch doesn't explain the why as well as your comment does. I'll gladly close this and resubmit it with a different branch name to stay in line with the project's goals.

**Comment by wing328** [comment]
Updated https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md#before-submitting-a-pr

**Comment by Trii** [comment]
See #3291

**Pull request closed without merging**
