### PR TITLE
adding support for java dates

### PR DESCRIPTION
**Pull request by spotby**
Hey guys,

I was having some trouble with generating an API for my jersey based java project (dropbox).  All of my dates generated for my responses were in java date format.  I added support for this format as a fallback when parsing dates. if you like it, take it :)

### CODE REVIEW

**Comment by wing328** [comment]
@spotby thanks for the PR. If I understand it correctly, the change is backward compatible. 

I'll merge this later as we already have a few Swift PRs in the queue.

**Comment by spotby** [comment]
Hey guys,  there is a small problem with this PR, but I'm new to all of this and don't know how to update it.  I pushed the fix to my swift-java-date branch that I created the PR from.  Do I have to re submit?

**Comment by fehguy** [comment]
Hi @spotby  you should be able to update your branch and the PR will update itself.

**Comment by wing328** [comment]
@spotby I saw your [change](https://github.com/spotby/swagger-codegen/commit/cdc9fb5f5e15178c6345110382beeb1823bf42d3) to change `sourceSpring` to `source`. Is there anything else you would like to change?

**Comment by spotby** [comment]
nope, its good to go. This should be a non breaking change.  thanks guys!

**Comment by wing328** [comment]
@spotby thanks again. Next time please update the Swift Petstore sample as mentioned in https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by wing328** [comment]
FYI. All test cases passed after updating the Swift petstore sample:
```
** TEST SUCCEEDED **

09:09:09.842 SwaggerClient[19930:715927] _XCT_testBundleReadyWithProtocolVersion:minimumVersion: reply received
09:09:09.848 SwaggerClient[19930:715927] _IDE_startExecutingTestPlanWithProtocolVersion:16
Test Suite 'All tests' started at 2016-02-11 09:09:09.877
Test Suite 'SwaggerClientTests.xctest' started at 2016-02-11 09:09:09.878
Test Suite 'PetAPITests' started at 2016-02-11 09:09:09.878
Test Case '-[SwaggerClientTests.PetAPITests test1CreatePet]' started.
Test Case '-[SwaggerClientTests.PetAPITests test1CreatePet]' passed (0.930 seconds).
Test Case '-[SwaggerClientTests.PetAPITests test2GetPet]' started.
Test Case '-[SwaggerClientTests.PetAPITests test2GetPet]' passed (0.596 seconds).
Test Case '-[SwaggerClientTests.PetAPITests test3DeletePet]' started.
Test Case '-[SwaggerClientTests.PetAPITests test3DeletePet]' passed (0.442 seconds).
Test Suite 'PetAPITests' passed at 2016-02-11 09:09:11.847.
	 Executed 3 tests, with 0 failures (0 unexpected) in 1.967 (1.970) seconds
Test Suite 'StoreAPITests' started at 2016-02-11 09:09:11.848
Test Case '-[SwaggerClientTests.StoreAPITests test1PlaceOrder]' started.
Test Case '-[SwaggerClientTests.StoreAPITests test1PlaceOrder]' passed (0.577 seconds).
Test Case '-[SwaggerClientTests.StoreAPITests test2GetOrder]' started.
Test Case '-[SwaggerClientTests.StoreAPITests test2GetOrder]' passed (0.510 seconds).
Test Case '-[SwaggerClientTests.StoreAPITests test3DeleteOrder]' started.
Test Case '-[SwaggerClientTests.StoreAPITests test3DeleteOrder]' passed (0.613 seconds).
Test Suite 'StoreAPITests' passed at 2016-02-11 09:09:13.551.
	 Executed 3 tests, with 0 failures (0 unexpected) in 1.701 (1.703) seconds
Test Suite 'UserAPITests' started at 2016-02-11 09:09:13.552
Test Case '-[SwaggerClientTests.UserAPITests test1CreateUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test1CreateUser]' passed (0.614 seconds).
Test Case '-[SwaggerClientTests.UserAPITests test2GetUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test2GetUser]' passed (0.613 seconds).
Test Case '-[SwaggerClientTests.UserAPITests test3DeleteUser]' started.
Test Case '-[SwaggerClientTests.UserAPITests test3DeleteUser]' passed (0.614 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogin]' passed (0.489 seconds).
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' started.
Test Case '-[SwaggerClientTests.UserAPITests testLogout]' passed (0.440 seconds).
Test Suite 'UserAPITests' passed at 2016-02-11 09:09:16.325.
	 Executed 5 tests, with 0 failures (0 unexpected) in 2.769 (2.773) seconds
Test Suite 'SwaggerClientTests.xctest' passed at 2016-02-11 09:09:16.325.
	 Executed 11 tests, with 0 failures (0 unexpected) in 6.438 (6.448) seconds
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:09 min
[INFO] Finished at: 2016-02-11T09:09:16+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```

**Pull request merged**
