### PR TITLE
[typescript-angular2] Allow lazy oauth token refresh (async access_token function)

### LINKED ISSUE #6486: [typescript-angular2] Allow lazy oauth token refresh (async access_token function)
##### Description
In case of an _OAuth2 implicit flow_ the current implementation of the `Configuration` class allows the `accessToken` to either be a _string_ or a _function returning a string_ (directly). In order to allow a lazy update of the (already expired) `access_token` using the (still valid) `refresh_token` the function should get the name of the authorization scheme as well as the necessary scopes and should return an `Observable<string>`.

```typescript
export class Configuration {
    ...
    accessToken?: string | ((name: string, scopes?: string[]) => string) => Observable<string>);
    ...
}
```

This would allow an asynchronous implementation of the `accessToken` function where the auth server can be requested for a new token.

##### Swagger-codegen version

`2.3.0-SNAPSHOT`

##### Command line used for generation

swagger-codegen-maven-plugin in version 2.3.0-SNAPSHOT for typescript-angular with ngVersion=4

##### Steps to reproduce

Try to create a _Configuration_ object which lazily refreshes the `access_token` (when the access_token has expired, but the _refresh_token_ is still valid).

##### Related issues/PRs

I commented on a PR for the typescript-fetch client suggesting this feature a few weeks ago (this time I mean the angular2 client): https://github.com/swagger-api/swagger-codegen/pull/6130#issuecomment-321244665
This PR also contains the new parameters for the `accessToken` function for the Typescript-Flow client (but does not return an `Observable<string>`): [Configuration class changes in PR 6130](https://github.com/swagger-api/swagger-codegen/pull/6130/files#diff-ad414fb91808bd31b38e08bcbb6feac6)

##### Suggest a fix/enhancement

- Change the _Configuration_ class to allow the _access_token_ function to return an `Observable<string>`
- Forward the name of the authorization scheme as well as the scope to the `access_token` function
- Build the requestOptions asynchronously before executing the http request (flatMap the Observables)

I'm working on a PR right now, I just want to make sure that the feature would be accepted. :)

### PR DESCRIPTION
**Pull request by alexrashed**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.
- [x] **Filed against 2.3.0 (and includes breaking changes).**

### Description of the PR

Fixes #6486.

- [x] Add authentication scheme name and necessary scopes as parameters for the `accessToken` function in the `Configuration` as seen in #6130 
- [x] `accessToken` function now returns an `Observable<string>` (allows lazy renewal using the `refreshToken`)
- [x] Update some old ng2 stuff to ng4 (some copy-pasting)
- [x] Added some previously not committed client / petstore code

Unfortunately Travis CI build fails due to some GitHub rate limits ([Travis CI build](https://travis-ci.org/alexrashed/swagger-codegen/builds/275052086)). I successfully executed `mvn clean verify` in the petstore client for ts-ng2 and ts-ng4, but this only invokes the compilation and no integration tests (how can I invoke any ts-ng2/4 IT locally?). But I tested it with my own project and there are no breaking changes to the petstore projects (as they are not using the `accessToken` function but return a static string instead).

### CODE REVIEW

**Comment by wing328** [comment]
@alexrashed thanks for the PR. I've changed the base to master (which is 2.3.0). Please rebase on the latest master resolve the merge conflicts.

cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by alexrashed** [comment]
Argh, please get rid of a feature branch which has the same name as your upcoming version! :D
I'm on it :)

**Comment by kenisteward** [comment]
@alexrashed Hey checkout my comment on #6846 for updating the configuration object with angular.  Let me know if that works for you cause it is the best case scenario for Angular.

**Comment by alexrashed** [comment]
As it was quite a pain to update the feature branch / merge the master in there (in comparison to the changes), I created a fresh branch / PR (#6496).

**Comment by wing328** [comment]
> Argh, please get rid of a feature branch which has the same name as your upcoming version! :D

Definitely. I'll try to do it this weekend (very busy these days ...)

**Pull request closed without merging**
