### PR TITLE
[Java Play Framework] Fix a regression bug that was introduced in a recent commit in routes

### PR DESCRIPTION
**Pull request by JFCote**
Indentations were added in the route files which prevent Play Framework compilation

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09)

### Description of the PR

Rollback the template file for routes which prevented the Play Framework from compiling.

### CODE REVIEW

**Comment by JFCote** [comment]
@wing328 Why is this in the v2.4.0 milestone? It must be merged in the 2.3.0 because right now the generator is useless (it doesn't compile)

**Comment by wing328** [comment]
@JFCote sure. I will merge it and change the milestone to 2.3.1

> 2.3.0 because right now the generator is useless (it doesn't compile)

I thought we'd integration tests (CircleCI) to make sure the auto-generated Play code compiles.

**Comment by JFCote** [comment]
@wing328 Maybe it's because the only sample that doesn't work is the "fake endpoint" one and for a long time it was not in the CI because it didn't compile at all. Could you please add this sample (and any other samples for the play framework) in the CircleCI? Thanks

**Comment by wing328** [comment]
@JFCote Sure. I'll check again and let you know if I need help fixing anything.

**Pull request merged**
