### PR TITLE
Issue 5310

### PR DESCRIPTION
**Pull request by elizabetht**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Issue 5310 - Added support to return examples if provided in the response section of swagger specification

### CODE REVIEW

**Comment by elizabetht** [comment]
@wing328 Any comments?

**Comment by wing328** [comment]
@elizabetht thanks for the PR. Will take a look shortly.

**Comment by elizabetht** [comment]
@wing328 Do I have to run some command to generate the sample *Api.java & *ApiController.java files that you had modified?

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5411

**Pull request closed without merging**
