### PR TITLE
Combine TypeScript Node output and beautify Angular output

### PR DESCRIPTION
**Pull request by tandrup**
Makes it easier to use the TypeScript Node code. Since the code can just require one file instead of having to require each model file independently.

Also adding a build system to the samples for Node and Angular to make it easier to test.

### CODE REVIEW

**Comment by wing328** [comment]
@tandrup thanks for the PR to add a build system for typescript sample. I followed the instruction `npm install; npm test` but got the following error:
```
typescript-node|combine-ts-node ⇒ npm test

> petstore-typescript-node-sample@1.0.0 test /private/var/tmp/tandrup/swagger-codegen/samples/client/petstore/typescript-node
> tsc --module commonjs api.ts typings/tsd.d.ts

api.ts(638,75): error TS2304: Cannot find name 'file'.
api.ts(686,77): error TS2304: Cannot find name 'map'.
api.ts(692,77): error TS2304: Cannot find name 'map'.
npm ERR! Test failed.  See above for more details.
```

I got the very similar error when running `npm test` in `typescript-angular`

Did you get similar error when running `npm test` in your machine ?

**Comment by tandrup** [comment]
@wing328 Yes I saw the same error. It seems the typescript generator does not support maps and files properly. I'm working on a fix.

**Comment by tandrup** [comment]
@wing328 I've added support for maps and files in the generated typescript code. I've added a small test script for the TypeScript Node petstore sample which does some test API calls including file upload.

**Comment by mhardorf** [comment]
Reviewed and looks good @tandrup, and thanks for generating new sample files, I forgot it last time.

**Comment by wing328** [comment]
@tandrup thanks!

`npm install; npm test` on `typescript-angular` does not show error:
```
typescript-angular|combine-ts-node ⇒ npm test

> petstore-typescript-node-sample@1.0.0 test /private/var/tmp/tandrup/swagger-codegen/samples/client/petstore/typescript-angular
> tsc
```

but `npm install; npm test` shows the following error:
```
typescript-node|combine-ts-node ⇒ npm test

> petstore-typescript-node-sample@1.0.0 test /private/var/tmp/tandrup/swagger-codegen/samples/client/petstore/typescript-node
> tsc && node client.js

api.ts(85,24): error TS2339: Property 'auth' does not exist on type 'Options'.
npm ERR! Test failed.  See above for more details.
```

Not sure if I'm running the test correctly.

**Comment by tandrup** [comment]
@wing328 Looks like a dirty workdir. I've added a `npm run clean` command to clean the workdir. Try running that and the do `npm install && npm test`

**Comment by wing328** [comment]
@tandrup test result looks good:
```
typescript-node|combine-ts-node⚡ ⇒ npm test

> petstore-typescript-node-sample@1.0.0 test /private/var/tmp/tandrup/swagger-codegen/samples/client/petstore/typescript-node
> tsc && node client.js

Created pet with ID 1437976393222
Updated pet using POST body
Updated pet using POST form
Uploaded image
Got pet by ID: {"id":1437976393222,"name":"TypeScriptDoggie","photoUrls":[],"tags":[],"status":"pending"}
Deleted pet
```

**Comment by tandrup** [comment]
Thanks @wing328 Sorry about the errors you had

**Comment by wing328** [comment]
@tandrup no problem at all. Learned something today :smile:

**Pull request merged**
