### PR TITLE
Feature/objc tasks 2.3.0

### PR DESCRIPTION
**Pull request by wberger**
@wing328 As agreed in PR #3391 I created a new PR for branch 2.3.0.

This replaces PR #3510.

### CODE REVIEW

**Comment by fehguy** [comment]
Hi @wberger you may have shared this with @wing328 but what is the goal of this PR?  Please create an issue and reference it in your PR, or put in some comments as to what the goal is with breaking the signatures of the generated clients.

**Comment by wberger** [comment]
@fehguy @wing328 The original motivation was this issue: #1981

The change to `AFHttpSessionManager` has been made since then, but I expanded on it by removing the request IDs for pending requests and returning `NSURLSessionTasks` instead. This allows for real task cancellation and leaves the housekeeping to the OS (see also the explanation below).

Furthermore during integration in our project I ran into the limitation of having only a single global configuration object and not being able to provide a different configurations for different ApiClient instances. Thus I reworked the code to make the configuration a component of the ApiClient which can be passed in during client creation. It results in less global state, higher configurability and less coupling - but only if required, since there are still fallbacks to global defaults.

Thus the only breaking change in the API is the return value of the API calls (`NSURLSessionTask *` instead of `NSNumber *`) and the renaming of the default configuration object from `{{classPrefix}}Configuration` to `{{classPrefix}}DefaultConfiguration`.

The original description of the changes can be found in PR #3391:

> I propose a change to the objc ApiClient. Instead of internally created and maintained request IDs the API implementation should return NSURLSessionTasks. This change has two advantages:
> 
> - Less internal state
> - These task object provide real cancellation as compared to the request ID based implementation (even if the task is currently running)
> 
> Furthermore I changed the configuration object to be protocol based in order to allow for more flexible integration into projects and more complex configuration setups. A default configuration implementation is provided and can be passed in, if no custom implementation is required.

**Comment by mateuszmackowiak** [comment]
@wing328 👍  Looks good to me

**Comment by wing328** [comment]
### Upgrade Note ###
**(1)** {classPrefix}Configuration has been renamed to {classPrefix}DefaultConfiguration, e.g.
*Before*:
```objc
    SWGConfiguration *config = [SWGConfiguration sharedConfig];
```
*After*:
```objc
    SWGDefaultConfiguration *config = [SWGDefaultConfiguration sharedConfig];
```

**(2)** Return type for API functions has been changed from `NSNumber*` to `NSURLSessionTask*`, e.g. 
*Before*
```objc
-(NSNumber*) addPetWithBody: (SWGPet*) body
```
*After*
```objc
-(NSURLSessionTask*) addPetWithBody: (SWGPet*) body
```

**Pull request merged**
