### PR TITLE
[Typscript][Fetch] add configuration to support authentication

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Add `configuration` object to support authentication (api key, HTTP basic, oauth)

cc @tht13

### CODE REVIEW

**Comment by wing328** [comment]
TODO: use dictionary instead of string for apiKey

**Comment by tht13** [comment]
@wing328 Do you have an example of where the apikey dictionary is implemented? I am trying to add this feature.

**Comment by wing328** [comment]
@tht13 would the following help?

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/csharp/api.mustache#L263-L292

**Comment by tht13** [comment]
wing328#8 is a PR adding the dictionary functionality, we shall see if it passes the tests 😄

**Comment by tht13** [comment]
Rather than use a Dictionary, I instead just defined the expected names of the api keys as an object. Makes it easier for the user when it comes to intellisense and the such. They don't have to look in the swagger.yaml file or generated api.ts to see what the exact name of the expected key is.

**Comment by wing328** [comment]
@tht13 that's perfectly fine with me and I'm sure Typescript developers would appreciate the enhancement you've made to the Typescript-fetch API clients.

**Comment by wing328** [comment]
PR merged into master. 

Thanks @tht13 for his contributions to make this happened.

**Comment by liuyang1204** [comment]
Hi, it won't compile if the api key name contains dash `-`. 

I meet this problem.

**Comment by wing328** [comment]
@liuyang1204 please open a new issue for tracking with the error message showing which line is causing the problem.

There's another PR to improve TS Fetch: https://github.com/swagger-api/swagger-codegen/pull/6130. Please review when you've time.

**Pull request merged**
