### PR TITLE
Feature/jaxrs resteasy

### PR DESCRIPTION
**Pull request by chameleon82**
Resteasy module. Generate code for Jboss/Wildfly servers. Based on Resteasy 3.0.11 framework ( JAX-RS 2.0)

### CODE REVIEW

**Comment by wing328** [comment]
@chameleon82 thanks for the PR. Here are some suggestions:

1. create `./bin/jaxrs-resteasy-petstore-server.sh` based on `./bin/jaxrs-cxf-petstore-server.sh` and output the sample under `samples/server/petstore/jaxrs-resteasy` 
2. [OPTIONAL] rename the folder `resteasy3_0_11` to `resteasy` as the RestEasy version can be changed/upgraded later.

**Comment by wing328** [comment]
@chameleon82 thanks for incorporating my feedback. PR merged.

**Comment by krisztiankocsis** [comment]
LocalDateTimeProvider.java for RESTEasy is broken, there is a LocalDate variable which should be LocalDateTime in line 16

**Comment by wing328** [comment]
@krisztiankocsis thanks for reporting the issue and suggesting a fix. Do you mind submitting a PR for the fix so that the credit goes back to you?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by krisztiankocsis** [comment]
Yeap, I’m working on it.

On 2016. március 9. at 14:13:29, wing328 (notifications@github.com) wrote:

@krisztiankocsis thanks for reporting the issue and suggesting a fix. Do you mind submitting a PR for the fix so that the credit goes back to you?

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by krisztiankocsis** [comment]
Still has issues: #2356

**Pull request merged**
