### PR TITLE
[Haskell] Add haskell-http-client to Shippable CI

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

Add haskell-http-client to Shippable CI

### CODE REVIEW

**Comment by wing328** [comment]
cc @jonschoning

**Comment by jonschoning** [comment]
Awesome!

I think you'll want to cache  `$HOME/.stack` 
in `shippable.yml` 
and remove ` $SHIPPABLE_REPO_DIR/samples/client/petstore/haskell-http-client/.stack-work`
from the cache

**Comment by wing328** [comment]
Sure. Will take your advise and cache `$HOME/.stack` only.

**Comment by wing328** [comment]
UPDATE: Done via b5200ba

**Pull request merged**
