### PR TITLE
[Java-Feign] Fixed String comparison using equals instead of == operator

### PR DESCRIPTION
**Pull request by CodeNinjai**
String comparison with equals, to avoid object reference comparison.
Run manually mvn clean package successfully.

### CODE REVIEW

**Comment by wing328** [comment]
@CodeNinjai btw, for your upcoming PRs, I would suggest creating a new branch for the fix as per git best practice.

**Comment by CodeNinjai** [comment]
Sorry  @wing328 I'll keep this in mind, will do next time ;-)

**Comment by cbornet** [comment]
@CodeNinjai  The retrofit2 ApiClient has the same issue. Would you do the PR for it also ?

**Comment by CodeNinjai** [comment]
@cbornet yes I can do this. Give me 3 or 4 hours.

**Comment by wing328** [comment]
@CodeNinjai PR merged into master. Thanks for your contribution.

For the fix to retrofit2 API client, please kindly submit a new PR (with a new branch)

**Comment by wing328** [comment]
retrofit 1.x client also has similar issue: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/ApiClient.mustache#L57

Please help fix it if you've time.

**Comment by CodeNinjai** [comment]
Shall we create an issue for both?

**Comment by wing328** [comment]
@CodeNinjai yes please

**Pull request merged**
