### PR TITLE
[Java] Assign default value for primitive properties

### PR DESCRIPTION
**Pull request by xhh**
Assign default value (if present)  for primitive properties in Java-related client and server codegen. See  #1448
For example:

```java
Integer pageSize = 100;
Long max = 10000l;
Float myFloat = 1.2f;
Double myDouble = 3.4d;
String message = "Hello";
Boolean published = false;
StatusEnum status = StatunEnum.AVAILABLE;
```

### CODE REVIEW

**Comment by cbornet** [comment]
I think this PR generates a regression fot enum lists. I get the error:
```
default value of property "expressions" is not in allowed values: new ArrayList<ExpressionsEnum>()
```

**Comment by cbornet** [comment]
Confirmed: if I comment [this block](https://github.com/xhh/swagger-codegen/commit/2595992df7112c13d5c2e98899d230fa546e197b#diff-79d6f9708f6ea5ba956fcbc53919c452R467), it works again

**Comment by xhh** [comment]
@cbornet thanks for the report! I've made a fix for it in PR #1546

**Comment by cbornet** [comment]
@xhh You're welcome. Thanks for your quick fix !

**Pull request merged**
