### PR TITLE
golang: trailing whitespace fails gofmt

### PR DESCRIPTION
**Pull request by vbatts**
Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
The generated comments have a trailing whitespace, which several format related tools check for.

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by vbatts** [comment]
there is no tech committee for golang. And do i need to file against multiple branches?

**Comment by vbatts** [comment]
testing this on a build of master looks like a number of new formatting issues now exist.

**Comment by wing328** [comment]
I'll review and let you know if I've any question.

**Comment by wing328** [comment]
> testing this on a build of master looks like a number of new formatting issues now exist.

Please open a new issue to track these.

(the Go API client in the latest master has been refactored).

**Pull request merged**
