### PR TITLE
[Elm] WIP - Add Elm language

### PR DESCRIPTION
**Pull request by trenneman**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is a **work-in-progress**, but @wing328 suggested me to open this PR in an early stage for feedback and support.

This PR adds support for the [elm-lang](http://elm-lang.org/). I'm already testing it on a ~2000 lines swagger-file and the basics are already working. What follows is a (mutable) TODO list:
- [ ] Get rid of the vendor extensions;
- [ ] Add support for path variables;
- [ ] Add support for `additionalProperties`/`Dict`s;
- [x] Add support for `Date`/`DateTime`;
- [ ] Add support for `ByteArray`/`Binary`;
- [ ] Add support for authentication;
- [x] Distinct between `Int` and `Float`;
- [x] Limit the exposure of modules;
- [ ] Support recursive types;
- [ ] ~~Try minimizing/removing dependencies (`elm-decode-pipeline`, `elm-date-extra`);~~
- [ ] Double check elm-format is applied correctly;
- [ ] General clean-up.

Most of them are quite Elm-specific, but for example the vendor extensions I use are just needed to define some decoder/encoder name. This feels kinda hacky, but I am not sure how to do so correctly. Please let me know whether I am the right track.

### CODE REVIEW

**Comment by wing328** [comment]
Related discussion in Reddit: https://www.reddit.com/r/elm/comments/7d7jwq/swagger_codegen_for_elm/

**Comment by wing328** [comment]
As discussed, let's merge this into master as a beta release so as to collect more feedback from Elm developers.

**Comment by wing328** [comment]
I've created to https://github.com/swagger-api/swagger-codegen/issues/7224 to track the enhancements.

**Comment by wing328** [comment]
Tweet to promote the new generator: https://twitter.com/wing328/status/943494382203715584

**Comment by ilyakard** [comment]
This is really great, thanks guys! Managed to parse the [FHIR](http://hl7.org/fhir/) API specification, which is pretty huge.

**Comment by andys8** [comment]
@trenneman What a great PR. It looks very promising. I started to look into it. I found smaller issues and opened issues for them. The changes are addressing formatting issues and refer to `elm-format`. Would be great to have the output matching the formatting standard. I tried to make out the files related to the issues. Hope I could help a little, even though those are small changes.

Issues: #8151 and #8152 
PR: #8150

**Comment by trenneman** [comment]
Thanks @andys8. Adhering to `elm-format` was already the intention, but isn't that simple in all cases. Are you going to file a PR for the other issues as well or can they be picked up?

**Comment by andys8** [comment]
I'm not planning to file PRs for now. So they're free to be picked up. I want to dig more into swagger codegen in the future.

**Pull request merged**
