### PR TITLE
fix net35 with JsonSubTypes

### PR DESCRIPTION
**Pull request by manuc66**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

As mentioned in #6969 this PR update JsonSubTypes to `1.2.0` which is compatible with NET35 without API changes.

As suggested I updated `compile.mustache`

In order to validate the `NET35` compliance I added a new sample generation `samples\client\petstore\csharp\SwaggerClientNet35\`

Here is the compilation status of sample available in the project:

| project | build.cmd build status  | build. _sh_ build status | VS2017 build status |
| --- | --- | --- | --- |
| csharp\SwaggerClient | OK | OK | OK |
| csharp\SwaggerClientWithPropertyChanged | OK | OK | OK |
| csharp\SwaggerClientNet35 | __NOT OK__ | OK | OK |
| csharp\SwaggerClientNet40 | __NOT OK__ |  OK |OK |
| csharp\SwaggerClientNetCoreProject  | _na_ | _na_ | OK |
| csharp\SwaggerClientNetStandard | _na_ | _na_ | OK |

The two __NOT OK__ are not related to this PR nor #6969 but seems to be related to the usage of `csc`

cc: @mandrean, @jimschubert

### CODE REVIEW

**Comment by jimschubert** [comment]
The change looks good.

What are the errors present in .NET 3.5/4.0 compile scripts? These worked previously (I resolved any issues about a week or two ago), before changing to the nuget package. Are you on an older version if mono, maybe?

I'll verify against this branch when I'm at a computer either tonight or tomorrow and report back with my mono version.

If it's a mono version issue, we'll want to open another pr to check for a minimum version before compilation, so there's no unknowns in build scripts. That's probably a good idea, anyway.

**Comment by manuc66** [comment]
@jimschubert I did not try on linux/mono but on windows.

It looks like the windows scripts are missing the `langversion` configuration. But are those kind of scripts making senses on windows ?

**Comment by jimschubert** [comment]
@manuc66 on Windows, I think it's a little different. If you're on Windows 10, I don't know if you'll be able to install .net 3.5 or 4.0. .net 4.5 is an in place install over .net 4.0, which may compile differently than having only .net 4.0 installed.

I'll need to download the IE developer images again to check.

**Comment by manuc66** [comment]
@jimschubert 

If I do use msbuild instead of csc on Windows the compilation works:

For net35:
```bat
if not exist ".\nuget.exe" powershell -Command "(new-object System.Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', '.\nuget.exe')"
.\nuget.exe restore

%SYSTEMROOT%\Microsoft.NET\Framework\v4.0.30319\msbuild IO.Swagger.sln /p:TargetFramework=3.5
```
See: https://pastebin.com/ZrCfdbrS


For net40 I still have issue with msbuild that I don't have with VS 2017:
```bat
if not exist ".\nuget.exe" powershell -Command "(new-object System.Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/latest/nuget.exe', '.\nuget.exe')"
.\nuget.exe restore

%SYSTEMROOT%\Microsoft.NET\Framework\v4.0.30319\msbuild IO.Swagger.sln /p:TargetFramework=4.0
```
see: https://pastebin.com/5mCLTqn7

**Comment by jimschubert** [comment]
@manuc66 were you ever able to resolve the issue with .NET 4.0? I intended to test this out but my VM drive crapped out and my main machine didn't have enough space for running a VM. I've upgraded my machine, and could take a look now if you were unable to.

**Comment by manuc66** [comment]
@jimschubert I did not found a solution for the compilation errors that are linked with the use of csc in the compilation stage.

Note that:
- the generated code can be build with VS2017
- the errors generated by csc are not related to the changes made by this PR

**Comment by wing328** [comment]
Thanks @manuc66.

We plan to release 2.3.0 today or tomorrow so I hope we can this into master as well.

**Comment by wing328** [comment]
I tested build.sh for the following folders and the result is good:
```
SwaggerClient
SwaggerClientNet40
SwaggerClientNet35
SwaggerClientWithPropertyChanged
```

**Pull request merged**
