### PR TITLE
inject base_path opaque token for typescript angular2

### LINKED ISSUE #3513: [typescript-angular2] baseUrl injectable
##### Description

The constructors for the Api classes in typescript-angular2 currently have the definition:
```typescript
constructor(protected http: Http, @Optional() basePath: string)
```
To be able to provide a value and have DI use this value, would it be better to set this up as:
```typescript
constructor(protected http: Http,  @Optional()@Inject(BASE_PATH) basePath: string)
```
And define a variables file with:
```typescript
export const BASE_PATH = new OpaqueToken('basePath');
```
And then this could be utilised on app bootstrap by:
```typescript
Import { BASE_PATH } from './service/variables';
bootstrap(AppComponent, [
    { provide: BASE_PATH, useValue: 'http://myservice:5000' }
]);
```

##### Swagger-codegen version
2.2.0

I'd be happy to make the contribution via a PR, just checking that there is no prior agreed way. And that this would be an appropriate way to handle this case?

### PR DESCRIPTION
**Pull request by damienpontifex**
Enable setup of base path for apis in angular2 bootstrap by providing the value to resolve #3513 

Need verifying I haven't missed anything as first code contribution to swagger-codegen and building the project from source

### CODE REVIEW

**Comment by wing328** [comment]
@damienpontifex thanks for the PR.

cc @Vrolijkx

**Comment by wing328** [comment]
@damienpontifex is it correct to say that this is a breaking change (non-backward compatible)?

If yes, please re-submit the PR for `2.1.3` branch instead.

**Comment by damienpontifex** [comment]
@wing328 I don't believe it to be a breaking change as it just provides another avenue for passing in the configuration value. 
I would be happy to have more feedback from others who are using it if it is actually causing a breaking change.

**Comment by Vrolijkx** [comment]
Nice addition to the angular2 api. Doesn't seem a breaking change to me. should be completely backward compatible.

**Comment by damienpontifex** [comment]
@wing328 @Vrolijkx just quickly added a note in the readme of how to set the custom base path. Let me know if there is any other sort of documentation we would normally add to these.

**Comment by martinmcwhorter** [comment]
I just ran into this missing OpaqueToken issue today. Im glad to see there is a pull request and hopefully this will be be in a release soon enough.

**Comment by wing328** [comment]
@damienpontifex thanks for the PR, which has been merged into master.

**Pull request merged**
