### PR TITLE
Added functionality to handle optional parameters for Scala

### PR DESCRIPTION
**Pull request by jyotsnakaran**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (NOTE: no need to update *all* Petstore sample. For instance, only need to update PHP Petstore sample by running `./bin/php-petstore.sh` if updating the PHP code generator or PHP client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
Added functionality to handle optional parameters for Scala
#3665

### CODE REVIEW

**Comment by wing328** [comment]
Please run `./bin/scala-petstore.sh` to update Scala Petstore sample.

(I'll revise the wording of the PR checklist later)

**Comment by wing328** [comment]
I think what I'll do it to cherry pick f12f70d62d73ab73283784aa7c34188dcb939641. Will let you know if I've any questions.

Moving forward, I would suggest you to create a new branch for the change as per GIT best practices.

**Comment by wing328** [comment]
I did some tests and got the following error:
```
scala|master⚡ ⇒ pwd
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/scala
scala|master⚡ ⇒ sbt test
[info] Set current project to swagger-scala-client (in build file:/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/scala/)
[info] Compiling 10 Scala sources to /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/scala/target/scala-2.11/classes...
[error] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala/io/swagger/client/api/PetApi.scala:393: ')' expected but '}' found.
[error]     }
[error]     ^
[error] one error found
[error] (compile:compileIncremental) Compilation failed
[error] Total time: 2 s, completed Aug 31, 2016 2:47:46 PM
```
Did the Scala petstore test pass for you locally in your machine?

**Comment by jyotsnakaran** [comment]
I will create a fresh PR with a new branch for these changes.

**Comment by wing328** [comment]
@jyotsnakaran thanks. Let us know if you need any help.

**Comment by jyotsnakaran** [comment]
I have created the new PR #3683. Please have a look.

**Pull request closed without merging**
