### PR TITLE
Issue 4632

### PR DESCRIPTION
**Pull request by martinkbrown**
This fixes issue 4632. It's a simple string conversion using std::stringstream. 

Tests done:
1) Build swagger-codegen on Windows
2) Use swagger-codegen-cli to generate code
3) Build the generated code, targeting Windows
4) Build the generated code, targeting Android armeabi-v7a

There aren't any unit tests to run, but I've been running this on my Android client device and sending/receiving from the server for several weeks now.

Please let me know if you think that I can improve this PR.

Thanks.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@martinkbrown if you don't have time to fix the commit authorship, it's ok with us and we'll merge your PR.

cc @Ragnis @genechang @plankswert @sdrichter

**Comment by genechang** [comment]
My PR is already merged and closed isn't it? 

    On Sunday, March 26, 2017 11:11 AM, wing328 <notifications@github.com> wrote:
 

 @martinkbrown if you don't have time to fix the commit authorship, it's ok with us and we'll merge your PR.cc @Ragnis @genechang @plankswert @sdrichter—

**Comment by martinkbrown** [comment]
Ok. You can go ahead and merge it. Thanks.

**Comment by wing328** [comment]
@genechang yes, your PR has been merged. This PR is also related to C++ (cpprest) API client so that's why I copied you for review.

**Comment by genechang** [comment]
oh I see.  I thought it was for me to merge my PR.
Thanks
Gene 

    On Sunday, March 26, 2017 12:57 PM, wing328 <notifications@github.com> wrote:
 

 @genechang yes, your PR has been merged. This PR is also related to C++ (cpprest) API client so that's why I copied you for review.—

**Comment by wing328** [comment]
@martinkbrown thanks for the PR, which has been merged into master.

**Comment by martinkbrown** [comment]
@wing328 Awesome! I'm looking forward to doing some more. Thanks for all your help.

**Comment by wing328** [comment]
FYI. I've removed some trailing spaces and update CppRest samples via aa8546893282309dcb85a67b4dc02c7d63879dc5

**Pull request merged**
