### PR TITLE
[Swift] Add sample/tests for Swift client without PromiseKit

### PR DESCRIPTION
**Pull request by Edubits**
Added sample/tests for Swift client without PromiseKit. Also moved the tests with PromiseKit to swift-promisekit (as without is the default config).

cc: @jaz-ah

### CODE REVIEW

**Comment by jaz-ah** [comment]
+1 looks good

**Comment by wing328** [comment]
Thanks both! PR merged.

**Comment by Edubits** [comment]
Thanks!

**Comment by jaz-ah** [comment]
hey btw one minor thing I noticed - java/android and other client samples are structured this way:
android/
httpclient	volley
java/
default		feign		jersey2		okhttp-gson	retrofit	retrofit2	retrofit2rx

should we move swift to the same structure - i.e.:
swift/default
swift/promisekit

**Comment by Edubits** [comment]
@jaz-ah, I noticed. However some other languages use this format (e.g. JavaScript and TypeScript). I'm fine with both. 
@wing328 would it be an idea to make this consistent for all languages?

**Comment by jaz-ah** [comment]
@wing328 I feel like it would be more straightforward to go w/ samples/client/petstore/language/language_derivation

and move javascript/typescript and I believe scala (akka-scala,async-scala,etc..) into this pattern... up to you I'm fine either way as well.

**Comment by wing328** [comment]
Both are fine. My preference is the suggestion by @jaz-ah 
```
swift/default
swift/promisekit
```

**Pull request merged**
