### PR TITLE
Issue-3168: [csharp] Allow additional-properties to set Assembly Info #3168

### PR DESCRIPTION
**Pull request by RowanJKWalker**
[csharp] Enabling Assembly Info to be set by the following command line's additional-properties:
- packageTitle
- packageProductName
- packageDescription
- packageCompany
- packageCopyright

### CODE REVIEW

**Comment by RowanJKWalker** [comment]
@wing328 @jimschubert here is my Pull Request for https://github.com/swagger-api/swagger-codegen/issues/3168

**Comment by jimschubert** [comment]
I'll test this later today or tomorrow. One thing I'd add is constant descriptions for title and description to differentiate from PACKAGE_NAME. Iirc, title is just a non-code representation of package name, while description can be a short summary of the package.  

We could probably use the explanations from MSDN Assembly Info types (AssemblyTitleAttribute for example).

**Comment by RowanJKWalker** [comment]
Good idea, will do it now.

**Comment by RowanJKWalker** [comment]
I have added a DESC for each of the new CodegenConstants. I went with the approach of saying exactly which Assembly Attribute would be set by specifying a value for the additional property.

**Comment by jimschubert** [comment]
Looks good. Tested the changes and the AssemblyInfo gets updated as expected.

I think the *_DESC constants' wording is fine for now. These aren't automatically used anywhere, but they'll remove the guesswork for anyone looking at the file. If anyone wants to reuse the constants, we can make the descriptions more generic. I'd also like to eventually expose a list of supported additional properties and descriptions, but I don't think that's a high priority.

**Comment by RowanJKWalker** [comment]
Cool, looking forward to the merge.

**Comment by wing328** [comment]
@RowanJKWalker thanks for the PR.

**Pull request merged**
