### PR TITLE
Bring generated readme and travis files into line with current value …

### PR DESCRIPTION
**Pull request by petercoles**
…of PhpClientCodegen::testBasePath

### CODE REVIEW

**Comment by petercoles** [comment]
This is a hangover from when the tests were moved. See #2743

**Comment by wing328** [comment]
@petercoles thanks for the PR. I'm working on a PR to migrate the tests under "tests" folder to "test/Api" and "test/Model"

(the travis CI failure seems to be caused by issues with the Petstore server at the moment)

**Comment by wing328** [comment]
@petercoles I've filed #3217 to merge the test cases.

I'll file another PR to clean up `tests/` this coming week.

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/3217

**Pull request closed without merging**
