### PR TITLE
[Ada] Hotfix/ada model sort

### LINKED ISSUE #7485: [Ada] wrong order for data structures in *-model.ads files
##### Description

Wrong order with the models in the *-model.ads files. The compilation ends with a:

arrowhead-orchestrator-models.ads:19:56: "StringsMap_Type" not declared in "Models"

An inspection of the ads file confirm the problem.

##### Swagger-codegen version

Current version on github (January 24th, 2018) with the patch to issues #7457 and #7462.

##### Swagger declaration file content or url

```yaml

swagger: '2.0'
host: 127.0.0.1:8442
basePath: "/orchestrator"
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json


paths: 
  /orchestration:
    post:
      description: Query an orchestrated service instance
      operationId: orchStore
      parameters:
        - name: serviceRequestForm
          in: body
          description: Requests an orchestrated service instance
          required: true
          schema:
            type: object
            required:
              - requesterSystem
              - requestedService
              - requestedQoS
            properties:
              requestedService:
                $ref: '#/definitions/arrowheadService'
      responses:
        200:
          description: Response to a service orchestration request
        default:
          description: Unexpected error



definitions: 
  arrowheadSystem:
    type: object
    required:
      - "systemName"
    properties:
      systemName:
        type: string
  arrowheadService:
    type: object
    required:
      - serviceGroup
      - serviceMetadata
    properties:
      serviceGroup:
        type: string
      serviceMetadata:
        $ref: '#/definitions/stringsMap'
  stringsMap:
    type: "object"
    properties:
      entry:
        type: string


```

##### Command line used for generation

java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i ../../openapiAHorchBadOrder.yml -l ada -o ../../ada-ahBadOrder/ --api-package Arrowhead.Orchestrator --model-package Arrowhead.Orchestrator

##### Steps to reproduce

Compile the *-models.ads / *-models.adb. The result is a:

arrowhead-orchestrator-models.ads:19:56: "StringsMap_Type" not declared in "Models"

##### Related issues/PRs

This issue is a follow-up of issues #7457 and #7462.

##### Suggest a fix/enhancement

Rework the sort method in postProcessModels method in file swagger-codegen\modules\swagger-codegen\src\main\java\io\swagger\codegen\languages\AbstractAdaCodegen.java

I am providing a potential fix in one hour, for you to consider it.

### PR DESCRIPTION
**Pull request by micheleISEP**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fix #7485.
Models are correctly sorted in terms of dependencies, and dependent models appear after dependencies in *-model.ads files.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. 

cc @stcarrez for review.

**Comment by wing328** [comment]
@micheleISEP please use 4-space instead of tab (the issue was caught by Travis CI)

**Comment by micheleISEP** [comment]
Done. I changed [tab] into 4 spaces each.

**Comment by stcarrez** [comment]
Thanks, it's ok for me.

**Pull request merged**
