### PR TITLE
Add a new cli command to output version information

### PR DESCRIPTION
**Pull request by MiguelGL**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This is as per discussed in #3007. I am using maven resources filtering support to generate a resource file with the ${project.version} stamped on it. 

Please note when running (from example from an IDE) from a non-maven env. this will lead to the 
version be **the literal** `${project.version}` string.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by MiguelGL** [comment]
I (thik I) fixed the account linking issue as per the instructions in the link (thanks!).

I can see this has sort of introduced a lot of noise, so just let me know if this still applies or maybe it's worth to reproduce the changes in another fork or something. 

Thanks.

**Comment by wing328** [comment]
@MiguelGL If it's not taking you too much time, please submit a new one as the rebase seems to have add commits not related to this change.

**Comment by MiguelGL** [comment]
Sure, i Will.

**Comment by MiguelGL** [comment]
I am closing this PR in favour of a new fresh one.

**Pull request closed without merging**
