### PR TITLE
Add option to set request timeout for Javascript request

### PR DESCRIPTION
**Pull request by vzeman**

### CODE REVIEW

**Comment by wing328** [comment]
@vzeman thanks for the PR. Would you please also update the Javascript petstore samples so that CI can verify the change?
```
./bin/javascript-petstore.sh
```

Ref: https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

**Comment by vzeman** [comment]
@wing328 could you please tell me which swagger.json should I use during compiling sample?

**Comment by wing328** [comment]
If you're on Mac/Linux, just run `./bin/javascript-petstore.sh`

For windows, please run `.\bin\windows\javascript-petstore.bat` instead.

**Comment by vzeman** [comment]
@wing328 done, please check if you need anything else from our side.

**Comment by wing328** [comment]
@vzeman looks good to me. Thanks for your contribution :beers:

**Pull request merged**
