### PR TITLE
[JaxRS] Fix response annotation generation (fixes #2588)

### LINKED ISSUE #2588: JAX-RS ApiResponse 'response' and 'responseContainer' annotations get duplicated
I used the Swagger Editor to create:

```
swagger: '2.0'
info:
  version: "0.0.1"
  title: Response annotation test
paths:
 /person:
    get:
      summary: Get all person api
      responses:
        200:
          description: Get all person
          schema:
            type: array
            items:          
              $ref: '#/definitions/Person'
        500:
          description: Unexpected error(s)
          schema:
            $ref: '#/definitions/ApiError'
definitions:
  Person:
    type: object
    properties:
      name:
        type: string
  ApiError:
    type: object
    properties:
      errorMsg:
        type: string
```

Then I generated JAX-RS Server code from the editor.  Here is the APIResponses section in the PersonApi class:

```
   @io.swagger.annotations.ApiResponses(value = { 
        @io.swagger.annotations.ApiResponse(code = 200, message = "Get all person", response = Person.class, responseContainer = "List"),
        @io.swagger.annotations.ApiResponse(code = 500, message = "Unexpected error(s)", response = Person.class, responseContainer = "List") })
```

The 'response' and 'responseContainer' annotations from the 200 response block got used in the 500 ApiResponse.

### PR DESCRIPTION
**Pull request by daveish**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixes a bug where response annotations for JaxRS server codegen got duplicated. See #2588 for detailed bug description.

### CODE REVIEW

**Comment by daveish** [comment]
circleci failed due to changes in the samples which came from the master branch. I'm looking into it.

**Comment by daveish** [comment]
This line broke the sample generation for JaxRS jersey1 with useTags option: https://github.com/swagger-api/swagger-codegen/commit/5a489f334ed553c261575aaf215589156325ff4b#diff-1069a655dc4a5f68a162d059e0e2cd0cR29

**Comment by daveish** [comment]
There is another commit on the master, which breaks the Java codegen functionality. Im working on it.

**Comment by wing328** [comment]
I've performed a few tests and the result is good. Thanks for the PR.

**Pull request merged**
