### PR TITLE
[Swift3] Fix compilation of models file

### PR DESCRIPTION
**Pull request by jgavris**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Example Swift Petstore tests did not compile on HEAD of 2.3.0 branch

### CODE REVIEW

**Comment by jgavris** [comment]
@wing328 @jaz-ah @Edubits

**Comment by jaz-ah** [comment]
+1 @wing328  - although not sure what happened to ci here

**Comment by jgavris** [comment]
I've spoken to @wing328 and I understand this project does not have Swift CI builds setup yet, though it is coming soon.

**Comment by jgavris** [comment]
cc @vineetshah

**Comment by jgavris** [comment]
Closes https://github.com/swagger-api/swagger-codegen/pull/5609

**Comment by jgavris** [comment]
Closes https://github.com/swagger-api/swagger-codegen/issues/5592

**Comment by wing328** [comment]
Yup, I'm working on moving existing Travis CI tests to other CI so as to free up Travis to run tests (objc, swfit) with ObjC build image as Travis seems to be the only provider that offers free Swift/ObjC CI tests.

**Pull request merged**
