### PR TITLE
Apex update for NamedCredentials and Salesforce DX

### PR DESCRIPTION
**Pull request by muenzpraeger**
Added support for NamedCredentials #5679 
Added support for Salesforce DX #5699

### CODE REVIEW

**Comment by wing328** [comment]
@muenzpraeger thanks for the enhancement.

(I'm no expert in Apex nor did I test the change)

**Comment by lodossDev** [comment]
Hi guys I ma new to this swagger stuff but not Salesforce is there some documentation on how to use this with apex?

**Comment by muenzpraeger** [comment]
@lodossDev There are still a few things to iron out on the current implementation. Check the blog on developer.salesforce.com over the next week or two where I'll publish a short how to.

**Comment by lodossDev** [comment]
thanks, can't wait :)

**Comment by wing328** [comment]
Like other API clients, we can create an auto-generated README.md, which contains instruction on how to use the Apex API client.

**Comment by muenzpraeger** [comment]
That's already included/done. ;-)

As said, some things need be ironed out. I tested the current implementation with several swagger definitions and there are some things to fix first.

**Pull request merged**
