### PR TITLE
Issue #3687 silence resty logging [Go]

### PR DESCRIPTION
**Pull request by neilotoole**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Addresses #3687 ... filing against `master` as it is a non-breaking change.

### CODE REVIEW

**Comment by wing328** [comment]
cc @guohuang

**Comment by guohuang** [comment]
@neilotoole why are there so many new files generated? are you using the standard pet store json?

**Comment by wing328** [comment]
@guohuang those new files are new models added to cover more edge cases.

**Comment by neilotoole** [comment]
@guohuang Yep, I was totally surprised by all the new files as well, but glad we're getting better coverage on edge cases. This is a big step in the right direction.

**Pull request merged**
