### PR TITLE
FIX: Fixed FLash Client library

### PR DESCRIPTION
**Pull request by glederrey**
Hi,

I fixed the Flash client library. It had multiple problems.. =) I also added a README.txt that explains how to use it.. (It's a bit more difficult to use than Python..)

- FlashClientCodegen
   - I changed the architecture to make it look like an ActionScript library project.
   - The Number type in as wasn't recognized by Swagger. (You have Double, Float, Integer, etc.) And since it wasn't recognized, Codegen was putting null as default value for Number. It's wrong. Therefore, I changed it to NaN
- ApiInvoker.as
   - A lot of imports were missing. I added them.
   - Bug at line 102/115 that I fixed
   - I commented a part of the function onApiRequestResult because it was trying to parse the response as a XML. And therefore, we couldn't receive anything if it's in JSON, for example. Therefore, having it RAW is better, for the moment. =)
- ApiUrlHelper.as
   - Small bug at line 34.
- api.mustache
   - Here, I simply removed the DefaultValue. It's just because if we put a DefaultValue, then it means for AS that it's an optional parameter. So, if there is other parameters after one parameter with a DefaultValue, AS will trigger an error because it doesn't accept required parameters after optional ones. 
- README.txt
   - Just some explanations.. I hope it will make it more clear how to use it.. I took quite a lot of time to understand how to use it, but I'm not an expert in flash at all.. So, I hope it can help some futur users.. 

That's everything.. So, I don't really improved this library. But at least, this library generated by Swagger will compile directly and will be ready to be used..

### CODE REVIEW

**Comment by wing328** [comment]
Thanks @glederrey :beers: 

I would suggest updating the Petstore sample by running `./bin/flash-petstore.sh`

**Comment by wing328** [comment]
Also would recommend you to create a new branch for your work.

Ref: https://www.git-tower.com/learn/git/ebook/command-line/appendix/best-practices => Use Branches

**Comment by glederrey** [comment]
@wing328 You're welcome.. 
Which branch do you want me to create?? I will update the Petstore Sample..

**Comment by glederrey** [comment]
Just a question, in order to change the branch (and this PR), do I have to delete this PR and create a new one with the new branch??

**Comment by wing328** [comment]
For this PR, you can just keep it (master) as it's.

My suggestion is more for moving forward.

**Comment by glederrey** [comment]
Okay.. Sorry about that.. 
I'll do that next time.. =)

**Comment by wing328** [comment]
I've restarted the CI build for that. Let's see how it goes.

**Comment by glederrey** [comment]
Okay, thank you

**Comment by wing328** [comment]
CI tests passed. PR merged. Thanks again for the contribution.

**Comment by glederrey** [comment]
You're welcome.. I hope I'll be able to help you more.. =)

**Comment by wing328** [comment]
Btw, I notice you seem to be using your private account (?) for the commit and therefore the [top contributor list](https://github.com/swagger-api/swagger-codegen/graphs/contributors) is not showing your contribution.

Let me know if you want to redo the change again so that the credit goes back to your public github account `glederrey`.

**Comment by glederrey** [comment]
Hi @wing328,
The swagger-codegen I forked is public.. That's what you're asking??

**Comment by wing328** [comment]
If you look at the [commit history](https://github.com/swagger-api/swagger-codegen/pull/2039/commits) for this PR, you will find that the commits are not linked to your Github account @glederrey 

That's probably why Github didn't count the 2 commits (contribution) to your Github account @glederrey

**Comment by glederrey** [comment]
You're right.. That's weird..

**Comment by wing328** [comment]
The commit log may give you a clue:
```
commit 5dc67c15e5587aa405d24c0e9cf3beb96ad5ec3c
Author: Gael Lederrey <Gael Lederrey>
Date:   Thu Feb 4 14:33:46 2016 +0100

    ADD: Add Petstore sample for flash

commit 77f9bc3642ae202772e2c4682258b9e47113c3a3
Author: Gael Lederrey <Gael Lederrey>
Date:   Thu Feb 4 14:03:13 2016 +0100

    FIX: Fixed FLash Client library

commit e926c86141a167ebe76afbdff2fdbe463126cb83
Merge: 96f9e93 7b67845
Author: wing328 <wing328hk@gmail.com>
Date:   Thu Feb 4 20:33:46 2016 +0800

    Merge pull request #2035 from wing328/csharp_fix_default_header
    
    [C#] fix default header in async method and sanitize model name
```
As you can see, mine has a proper email address linked to it. Yours is just a name. Maybe it has to do with your local git setting.

**Comment by glederrey** [comment]
Okay, I see.. There was a problem when I put the username and email..

**Comment by wing328** [comment]
Entirely up to you. If you want to redo it (so that credits go back to @glederrey), just let me know.

**Comment by glederrey** [comment]
If we can do it in an easy way.. With pleasure.. =)

**Comment by wing328** [comment]
I can roll back the change for the time being. You can then submit a PR with commits linked to @glederrey .

**Comment by glederrey** [comment]
Okay.. Thank you very much

**Comment by glederrey** [comment]
Do I have to submit a new PR??

**Comment by wing328** [comment]
Just reverted your PR. Please submit a new one with commits properly linked to your Github account.

**Comment by glederrey** [comment]
I will do that.. Thanks again..

**Comment by wing328** [comment]
Np. Just want to make sure you get the credits for your contribution that you deserved.

**Pull request merged**
