### PR TITLE
[Java] Add support for JSR310 in Jersey Clients (v3)

### PR DESCRIPTION
**Pull request by ant3**
This PR is following on from comments in #3174.

As suggested I have created a new sample called java8-petstore-jersey2 which tests the jersey2 client with the java8 date libraries.  I did not create a java8 version of the jersey1 client because it is kind of covered by other sampes and I think it is not likely that anyone will want to use Jersey1 in Java8.

I also rebuilt the jersey1 and jersey2 client samples (without java8 dates) to ensure no significant changes as a result of this work.

Finally I upgraded some of the dependencies in order to apply the new Jackson JavaTimeModule (replaces JSR310Module) as suggested by Cristophe (cbornet).

### CODE REVIEW

**Comment by cbornet** [comment]
@ant3 Can you also copy the tests from the joda-based jersey sample ?
You just have to adapt StoreApiTest to use java.time
```java
assertEquals(order.getShipDate().toInstant(), fetched.getShipDate().toInstant());
...
order.setShipDate(java.time.OffsetDateTime.now());
```

**Comment by ant3** [comment]
Yes, I will do that.  Sorry for the slow response, I have a lot going on right now :-(.

**Comment by wing328** [comment]
@ant3 please take your time and let us know if you need any help.

As always we appreciate your contribution to the project.

**Comment by wing328** [comment]
@ant3 I've merged this PR to avoid merge conflicts later. Please file another PR to add the test cases.

**Pull request merged**
