### PR TITLE
Minimal update for Ruby testing on El Capitan

### PR DESCRIPTION
**Pull request by jqr**
This PR addresses running the Ruby integration tests on El Capitan

One of the development dependencies of the generated Ruby client is [autotest-fsevent](https://github.com/svoop/autotest-fsevent/). It's used to detect file system changes and re-run the tests automatically. Building the clients works fine, but when attempting to run the integration tests for Ruby with the latest OS X (El Capitan) it errors out with this message:

```
Installing autotest-fsevent 0.2.10 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/autotest-fsevent-0.2.10/ext/fsevent
/usr/local/var/rbenv/versions/2.3.0/bin/ruby -r ./siteconf20160107-72766-a9grd3.rb extconf.rb
extconf.rb:24:in `<main>': Darwin 15 is not (yet) supported (RuntimeError)

extconf failed, exit code 1

Gem files will remain installed in /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/autotest-fsevent-0.2.10 for inspection.
Results logged to /usr/local/var/rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/autotest-fsevent-0.2.10/gem_make.out
Using typhoeus 0.7.1
Using webmock 1.21.0
Using rspec 3.2.0
An error occurred while installing autotest-fsevent (0.2.10), and Bundler cannot
continue.
Make sure that `gem install autotest-fsevent -v '0.2.10'` succeeds before
```

The issue is fixed in the latest version of autotest-fsevent, v0.2.11, see [CHANGELOG](https://github.com/svoop/autotest-fsevent/blob/master/CHANGELOG.txt).

We could fix this in two ways:

1. Adjust the version locked in `samples/client/petstore/ruby/Gemfile.lock`. Typically `Gemfile.lock` files are not actually checked in on Ruby gems, so either updating the version to `0.2.11` or removing the file entirely would be workable.
2. Adjust the development dependency to include latest version.

I opted for 2 because it seemed like a much simpler change and more in-line with how the project was being managed. I'm happy to do the work to handle 1 if you prefer.

### CODE REVIEW

**Comment by jqr** [comment]
I think the TravisCI failure here is unrelated (stall detected) and I don't see how changing the gem version would cause this.

**Comment by fehguy** [comment]
thanks.  Fixing the travis issue now...

**Comment by fehguy** [comment]
Hi, please rebase with master.  The `.travis.yml` file needs to be updated for the PR to pass.

**Comment by jqr** [comment]
Failure seems to be on a single field, only in oraclejdk7. Not even sure how that could be related. Is this a known issue?

```
[INFO] --- exec-maven-plugin:1.2.1:exec (bundle-test) @ RubyPetstoreClientTests ---
...........................F............
Failures:
  1) Pet pet methods should fetch a pet object
     Failure/Error: pet.tags[0].name.should == "tag test"
     NoMethodError:
       undefined method `name' for nil:NilClass
     # ./spec/pet_spec.rb:49:in `block (3 levels) in <top (required)>'
```

**Comment by fehguy** [comment]
Travis has been mad lately.  Some of it's my fault--I've retriggered the build.

**Comment by wing328** [comment]
@jqr the change looks good to me and I'll merge later today.

**Pull request merged**
