### PR TITLE
Several minor fixes in the Go client code generator for Camelization of elements

### PR DESCRIPTION
**Pull request by neilotoole**
See issue #2285 for more details. This fix has been verified locally against a known good swagger file, and the generated client tested against just a handful of operations, so quality is **not** assured. From my quick look around there doesn't appear to be a Go test harness, I think that's something that we many need to work on. Apologies for any violations of style etc, feel free to edit as needed.

### CODE REVIEW

**Comment by wing328** [comment]
@neilotoole yes, thank for the PR. Totally agree that we should have some test cases for Petstore GO API client.

I created a task for tracking here: https://github.com/swagger-api/swagger-codegen/issues/1948

If you've cycle, we would appreciate your contribution on that.

**Comment by neilotoole** [comment]
@wing328 Hopefully I'll have some free cycles coming up in the next few weeks. Do you have a general strategy for dealing with test harness runtimes? (Apologies, I haven't yet had a good look around the rest of the codebase). Given that this test harness would require the installation of the Go runtime, perhaps it should be done in a container? Or any other thoughts?

**Comment by wing328** [comment]
For testing, travis-ci does not support multiple languages so we've to install the lang/package manually if it's required by the test.

As an example, for ObjC/Swift, the tests are not run by the CI so currently I've to manually run the tests when reviewing changes related to ObjC/Swift.

**Comment by neilotoole** [comment]
Hmmmn... well, in this era (so far! so soon!), any CI process worth its salt should allow one to kick off a container to execute tests? Concourse CI for example.

**Comment by wing328** [comment]
I did reach out to other CI provider and hopefully they've better (and free) solution for our special case.

**Comment by neilotoole** [comment]
Best of luck with that! Let me know if I can help. Containers are really the only way to go if you'd like to (ultimately) have full end-to-end test harnesses for each of the supported languages. It's effectively physically impossible to do it otherwise, and that's really what we should be aiming for.

**Comment by wing328** [comment]
Totally agree. I'll share the update once I've more info.

**Pull request merged**
