### PR TITLE
Add option to set default model values to null (Like `List`, `Map`)

### PR DESCRIPTION
**Pull request by egormasalitin**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Issue: #5240
I added new additional param for java client coden, it will allow us to set all Model fields to null. This change is important for us, because `null` List and empty list is two different things.

### Why it is important?

For example you have api with partial update support (our case). It means that if user send json with just one field from model, API will update just this field. But current version of codegen set List and Map default values to empty list and empty map, it means that when user will send update request to our api using SDK, it will override list options as well.

### CODE REVIEW

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5363

**Comment by jmiddleton** [comment]
Hi @wing328, is this PR coming in 2.2.3 ? is there any way I can get the snapshot version including this fix?

**Comment by inthegarage** [comment]
@jmiddleton It is not in 2.2.3 and I don't see it in the snapshot either. We're stuck on 2.2.2 until it is incorporated - without avoiding major rework.

**Comment by wing328** [comment]
The PR was not merged as we added the fix in the templates directly (without introducing additional option) via #5363

If you still encounter issue with the default value, please kindly open a new issue with the details (e.g. spec to reproduce the issue) and link back to this one.

**Comment by inthegarage** [comment]
@wing328 I'm a little confused now, I agree the templates have been modified. However I ideally need this option described in this ticket (5341)  - IE the option to not set default value to null, in other words the functionality present in 2.2.2.  Using 2.2.3 means in effect there is regression as code which rightly assumes maps to be not null are now breaking.  How should we use this "defaultValue"? I don't see any reference to its usage, is a quick example possible? Obviously with Maps and Lists the default value for various classes could be all manner of things, hence my confusion.

**Comment by wing328** [comment]
@inthegarage sorry if the change may have confused you. May I know if you've read the discussion in https://github.com/swagger-api/swagger-codegen/issues/5240?

Again I would suggest opening a new issue with an example to illustrate the issue so that other contributors can also more easily look into the issue and suggest better fixes.

**Comment by inthegarage** [comment]
@wing328 That's explained it clearly, thank you. We can simply use the following construct in our yaml:

```
    required:
      - languages
```
As appropriate per model. This is a now a simple upgrade. We had already used it, however the code relied upon the auto-default (non null). This is a better, more controlled solution.

**Pull request closed without merging**
