### PR TITLE
[Java] Do not generate setter method for readonly properties

### PR DESCRIPTION
**Pull request by xhh**
Updated Java clients: default, feign, jersey2, okhttp-gson.

### CODE REVIEW

**Comment by hiveship** [comment]
I will also add it to CXF Codegen :)

**Comment by ePaul** [comment]
Note that `readOnly` for a Swagger property just means that the client shouldn't send it to the server, but the server can send it back.
So please make sure it doesn't remove the setter when generating server models.

**Comment by hiveship** [comment]
Ok sorry @ePaul . I won't remove the setter in the CXF Codegen since it only generates a server stub :)

**Comment by wing328** [comment]
FYI. The change applies to `retrofit` and `retrofit2` as well.

cc @cbornet

**Comment by wing328** [comment]
**Upgrade note from 2.1.5 to 2.1.6**

Starting from 2.1.6, there will be no setter for `readOnly` attribute in Java models.

**Pull request merged**
