### PR TITLE
Unicode escape issue

### PR DESCRIPTION
**Pull request by catinred2**
#2779

### CODE REVIEW

**Comment by wing328** [comment]
@catinred2 thanks for the PR. Have you tried upgrading to http://mvnrepository.com/artifact/org.apache.commons/commons-lang3, which has better support for double byte characters?

Ref: https://dzone.com/articles/commons-lang-3-improved-and-powerful-StringEscapeUtils

**Comment by catinred2** [comment]
@wing328 StringEscapeUtils of either version would not do.

**Comment by catinred2** [comment]
@wing328  the ci fails. I've checked out the detail. it seems that has something about javadoc style. any rules should i follow?

**Comment by wing328** [comment]
@catinred2 I'll take another look later today.

**Comment by wing328** [comment]
@catinred2 I've filed https://github.com/swagger-api/swagger-codegen/pull/2785 to fix the issue. Would you give it a try to see if it works for you as well?

(this is **not** to say your PR is not good but just that we need to upgrade `org.apache.commons.lang` to the latest version `org.apache.commons.lang` anyway so I think I would try to leverage the latest version of the library to address the problem to avoid reinventing the wheel)

**Comment by catinred2** [comment]
@wing328 #2785 works for me. 
thanks for your great work.

**Comment by wing328** [comment]
@catinred2 my PR merged into master. Please pull the latest.

**Pull request closed without merging**
