### PR TITLE
[Python][Flask] use tags to organize Python Flask controllers

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Use `tags` to organize endpoints in the controllers

### CODE REVIEW

**Comment by wing328** [comment]
## Upgrade Note ##

Starting from 2.3.0, the controllers in Python Flask are created based on `tags` instead of putting all operations into the same default_controller.py so that the endpoints are better organized.

**Comment by bs-sdev** [comment]
Is it done on the swagger editor or we should generate the controller directly on the codegen project?

Kind regards

**Comment by wing328** [comment]
editor is using the latest stable version of swagger codegen (not the latest master). Please build the JAR locally on the latest master to test the fix.

**Comment by bs-sdev** [comment]
Ok, thanks for the quick answer :)

**Pull request merged**
