### PR TITLE
[objc] Allow customizing date format

### PR DESCRIPTION
**Pull request by SirBif**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Now the date is serialized and de-serialized using a date formatter (exposed through the configuration) so its format and time zone can be changed.

Fixes this: https://github.com/swagger-api/swagger-codegen/issues/6136

### CODE REVIEW

**Comment by SirBif** [comment]
CI failed with a rate limit error, so I can't do much about it

> [ERR!] GitHub API: GitHub rate limit reached.
> To increase the limit use GitHub authentication.
> See: https://github.com/DefinitelyTyped/tsd#tsdrc

**Comment by wing328** [comment]
@SirBif ObjC tests failed with the following error messages:
```
â–¸ Compiling SWGApiClientTest.m
âŒ  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/SWGApiClientTest.m:3:9: 'ISO8601/ISO8601.h' file not found

#import <ISO8601/ISO8601.h>

     ^~~

2017-08-03 11:07:09.450 xcodebuild[3791:12536] Error Domain=IDETestOperationsObserverErrorDomain Code=3 "Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/SwaggerClient-fhldypgjqmnttibyawwuxhmqwwsl/Logs/Test/8B05E61E-CF8E-4941-A74A-353CC8F51915/Session-SwaggerClient_Tests-2017-08-03_110555-MYwzVr.log" UserInfo={NSLocalizedDescription=Test operation was canceled. If you believe this error represents a bug, please attach the log file at /Users/travis/Library/Developer/Xcode/DerivedData/SwaggerClient-fhldypgjqmnttibyawwuxhmqwwsl/Logs/Test/8B05E61E-CF8E-4941-A74A-353CC8F51915/Session-SwaggerClient_Tests-2017-08-03_110555-MYwzVr.log}
2017-08-03 11:07:09.460 xcodebuild[3791:12696] Connection peer refused channel request for "dtxproxy:XCTestManager_IDEInterface:XCTestManager_DaemonConnectionInterface"; channel canceled <DTXChannel: 0x7fd5ffcedc40>

Testing failed:
	'ISO8601/ISO8601.h' file not found
** TEST FAILED **
```

Ref: https://travis-ci.org/swagger-api/swagger-codegen/builds/260556139

Please take a look when you've time.

**Comment by SirBif** [comment]
@wing328 I fixed that test and run the objc-petstore-all script to make sure every generated class is updated, but now CI failed with the rate limit error again and I don't have an option to retrigger it.

**Comment by wing328** [comment]
@SirBif I triggered the tests again and failed with the following errors:
```
DeserializationTest

  testDeserializeDate, ((error) == nil) failed: "Error Domain=SWGDeserializationErrorDomainKey Code=143553 "Received response [2012-09-27] is not an object of type NSDate" UserInfo={NSLocalizedDescription=Received response [2012-09-27] is not an object of type NSDate}"

  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:31

  ```

    NSDate *deserializedDate = [apiClient.responseDeserializer deserialize:dateStr class:@"NSDate*" error:&error];

    XCTAssertNil(error);

    XCTAssertEqualWithAccuracy([date timeIntervalSinceReferenceDate], [deserializedDate timeIntervalSinceReferenceDate], 0.001);

  ```



  testDeserializeDate, (([date timeIntervalSinceReferenceDate]) equal to ([deserializedDate timeIntervalSinceReferenceDate]) +/- (0.001)) failed: ("370396800") is not equal to ("0") +/- ("0.001")

  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:32

  ```

    XCTAssertNil(error);

    XCTAssertEqualWithAccuracy([date timeIntervalSinceReferenceDate], [deserializedDate timeIntervalSinceReferenceDate], 0.001);

}

  ```



  testDeserializeDateTime, ((error) == nil) failed: "Error Domain=SWGDeserializationErrorDomainKey Code=143553 "Received response [1997-07-16T19:20:30+00:00] is not an object of type NSDate" UserInfo={NSLocalizedDescription=Received response [1997-07-16T19:20:30+00:00] is not an object of type NSDate}"

  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:60

  ```

    NSDate *deserializedDateTime = [apiClient.responseDeserializer deserialize:dateTimeStr class:@"NSDate*" error:&error];

    XCTAssertNil(error);

    XCTAssertEqualWithAccuracy([dateTime timeIntervalSinceReferenceDate], [deserializedDateTime timeIntervalSinceReferenceDate], 0.001);

  ```



  testDeserializeDateTime, (([dateTime timeIntervalSinceReferenceDate]) equal to ([deserializedDateTime timeIntervalSinceReferenceDate]) +/- (0.001)) failed: ("-109226370") is not equal to ("0") +/- ("0.001")

  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:61

  ```

    XCTAssertNil(error);

    XCTAssertEqualWithAccuracy([dateTime timeIntervalSinceReferenceDate], [deserializedDateTime timeIntervalSinceReferenceDate], 0.001);

}

  ```

You can also run the tests locally: 
```
cd samples/client/petstore/objc/default/ && mvn integration-test
cd samples/client/petstore/objc/core-data/ && mvn integration-test
```

**Comment by SirBif** [comment]
Hi. Right now I can't run the tests because I don't have my mac. I think I found the issue and hopefully fixed it. If it isn't that, let's pause this for now, I'll pick it up when I'm back from vacation in a couple of weeks.

**Comment by wing328** [comment]
@SirBif please take your time and enjoy your vacation.

If you need help from us, just let us know.

**Comment by SirBif** [comment]
FYI, picking this up again

**Comment by wing328** [comment]
Travis CI reports the following errors:
```
PetTest
    ✓ testDescription (0.001 seconds)
SWGApiClientTest
    ✓ testConfiguration (0.001 seconds)
    ✓ testGetBasicAuthToken (0.001 seconds)
    ✓ testSanitizeForSerialization (0.001 seconds)
    ✓ testSelectHeaderAccept (0.001 seconds)
    ✓ testSelectHeaderContentType (0.001 seconds)
StoreApiTest
    ✓ testGetInventory (0.018 seconds)
UserApiTest
    ✓ testLoginUser (0.009 seconds)


DeserializationTest
  testDeserializeDate, ((error) == nil) failed: "Error Domain=SWGDeserializationErrorDomainKey Code=143553 "Received response [2012-09-27] is not an object of type NSDate" UserInfo={NSLocalizedDescription=Received response [2012-09-27] is not an object of type NSDate}"
  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:31
  ```
    NSDate *deserializedDate = [apiClient.responseDeserializer deserialize:dateStr class:@"NSDate*" error:&error];
    XCTAssertNil(error);
    XCTAssertEqualWithAccuracy([date timeIntervalSinceReferenceDate], [deserializedDate timeIntervalSinceReferenceDate], 0.001);
  ```

  testDeserializeDate, (([date timeIntervalSinceReferenceDate]) equal to ([deserializedDate timeIntervalSinceReferenceDate]) +/- (0.001)) failed: ("370396800") is not equal to ("0") +/- ("0.001")
  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:32
  ```
    XCTAssertNil(error);
    XCTAssertEqualWithAccuracy([date timeIntervalSinceReferenceDate], [deserializedDate timeIntervalSinceReferenceDate], 0.001);
}
  ```

  testDeserializeDateTime, ((error) == nil) failed: "Error Domain=SWGDeserializationErrorDomainKey Code=143553 "Received response [1997-07-16T19:20:30+00:00] is not an object of type NSDate" UserInfo={NSLocalizedDescription=Received response [1997-07-16T19:20:30+00:00] is not an object of type NSDate}"
  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:60
  ```
    NSDate *deserializedDateTime = [apiClient.responseDeserializer deserialize:dateTimeStr class:@"NSDate*" error:&error];
    XCTAssertNil(error);
    XCTAssertEqualWithAccuracy([dateTime timeIntervalSinceReferenceDate], [deserializedDateTime timeIntervalSinceReferenceDate], 0.001);
  ```

  testDeserializeDateTime, (([dateTime timeIntervalSinceReferenceDate]) equal to ([deserializedDateTime timeIntervalSinceReferenceDate]) +/- (0.001)) failed: ("-109226370") is not equal to ("0") +/- ("0.001")
  /Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/objc/default/SwaggerClientTests/Tests/DeserializationTest.m:61
  ```
    XCTAssertNil(error);
    XCTAssertEqualWithAccuracy([dateTime timeIntervalSinceReferenceDate], [deserializedDateTime timeIntervalSinceReferenceDate], 0.001);
}
```

Ref: https://travis-ci.org/swagger-api/swagger-codegen/builds/272798881

You can also run the test locally: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-do-i-run-integration-test-with-petstore-objc-api-client

**Comment by SirBif** [comment]
Hi,

sorry for that, I was updating my fork from the latest master and forgot it'd re-trigger a build here.
I have a few updates regarding this PR. Btw now I can just run the tests on my IDE ;)

As you pointed out, what is failing are the tests that make sure we can properly serialize/deserialize dates. The issues are those:

- if I use a date formatter, it fails in deserializing the string to a date if the string does not follow the format exactly (e.g. some fields are missing). This is something that is supported by the existing conversion library ISO8601, which is more lenient
- this means that a single date formatter can't handle both date and date-time. I need to serialize and deserialize the 2 formats differently. Looks like I've stepped into the same issue as these: https://github.com/swagger-api/swagger-codegen/issues/5513 and https://github.com/swagger-api/swagger-codegen/issues/5531
- regarding this, even the approach currently on master is not serializing dates properly. Dates still get serialized in the date-time format (testSanitizeForSerialization is not covering that). Again, same problem as this https://github.com/swagger-api/swagger-codegen/issues/5513
- if I introduce 2 separate date formatters, one for date and one for date-time, I don't know which one to use when it's time to deserialize a string. I tried seeing if I could deserialize them to different classes, but that seems to be going too deep into the rabbit hole

Right now I'm considering what to do. Either
- just allow the user to configure the timezone to use when serializing (which was the issue that made me start this) and stick to the ISO8601 date format
- try to apply something similar to this: https://github.com/arnested/swagger-codegen/commit/7cb599c1489ce96a088680b0c67aa39d39c56d16, as this is a prerequisite for being allowed to even think of customizing the date format, but this requires a bigger modification for the codegen library itself, about which I'm not too confident


Btw, iOS 10 added native support for ISO8601 string<->date conversion (https://developer.apple.com/documentation/foundation/nsiso8601dateformatter) but now it's still too early to switch over I believe

**Comment by wing328** [comment]
> just allow the user to configure the timezone to use when serializing (which was the issue that made me start this) and stick to the ISO8601 date format

@SirBif Yup, I would suggest going with this approach given that it's a smaller change.

**Comment by SirBif** [comment]
Then I'll abandon this pull request and make a new one with that

**Pull request closed without merging**
