### PR TITLE
Support passing custom RequestInit options in typescript-fetch client…

### PR DESCRIPTION
**Pull request by alechill**
…, to enable fetch API specific options (eg including credentials, enabling CORS etc)

### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixes ticket https://github.com/swagger-api/swagger-codegen/issues/4025

Tests updated to include calling with and without options, and run both locally and on travis (https://travis-ci.org/alechill/swagger-codegen)

Would have liked to have made the options a `RequestInit` type but if generated api package is included as an npm module in another project (as the test suite does) it would require an extra ambient typing for the parent project (for isomorphic-fetch), and so would make it a breaking change (mildly - not in code but in typings WTFs). However, should still get the type safety (when it is internally cast to `RequestInit`) if the generated api is used directly within the same project. Best compromise I hope

### CODE REVIEW

**Comment by wing328** [comment]
@alechill thanks for the PR.

cc @Vrolijkx

**Comment by wing328** [comment]
(personally I would recommend you to create a new branch for the change as per git best practice)

**Comment by alechill** [comment]
@wing328 No probs, will do, ta

**Comment by alechill** [comment]
@wing328 Github wont allow changing branch of PR, so re-raised at https://github.com/swagger-api/swagger-codegen/pull/4038

**Pull request closed without merging**
