### PR TITLE
Fix sample script to set the correct artifact ID in the generated POM

### PR DESCRIPTION
**Pull request by ePaul**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change.
     → bin/akka-scala-petstore.sh (twice, once before and once after the change).
- [x] Filed the PR against the correct branch: master for non-breaking changes.

### Description of the PR

This was first just meant to update the Akka samples, there are no code changes here.
The first commit (updating samples from the script) undoes part of the change from #5073, which changed the name + artifact ID manually.
This shows that the default artifact ID is not what is used when running CI.

The second commit changes the sample update scripts to set the correct `--artifact-id` parameter.

The third commit updates the samples again, showing that everything is fine now. (There is a change in the generated reference.conf, not sure if it is relevant.)

### CODE REVIEW

**Comment by wing328** [comment]
@ePaul thanks for the PR, or we can leverage .swagger-codegen-ignore to prevent the file being overwritten in the next run (other clients also use this approach)

**Comment by wing328** [comment]
Actually your approach may work better as we need to update dependency in pom.xml to the latest version from time to time.

**Comment by ePaul** [comment]
@wing328 I was not aware that .swagger-codegen-ignore is used for this purpose.
Though I like this way better, as it allows to actually test the generated pom.xml, not one generated ages ago.

Should I do the same change for other generators too? (Possibly in a separate PR.)

**Comment by wing328** [comment]
> Should I do the same change for other generators too? (Possibly in a separate PR.)

Yup, if you've time, please do. Thanks.

(beware there might be other custom changes made to the auto-generated pom.xml)

**Pull request merged**
