### PR TITLE
[Java] Add "equals" and "hashCode" methods to Java clients

### PR DESCRIPTION
**Pull request by xhh**
Added "equals" and "hashCode" methods to the default, "jersey2" and "okhttp-gson" Java clients, along with test cases.

### CODE REVIEW

**Comment by dantran** [comment]
Just test with 2.1.5-SNAPSHOT, I dont see the generated hash and method, do I need to turn it on?

**Comment by dantran** [comment]
I had to build it myself.  please deploy a snapshot to sonatype. Thanks

**Comment by wing328** [comment]
Currently, the fix is in the master and will be included in the next release (2.1.5)

**Comment by webron** [comment]
@dantran - just pushed a new snapshot

**Comment by dantran** [comment]
@webron latest snapshot works for me .  Thanks

**Pull request merged**
