### PR TITLE
[Elixir] Add documentation for functions

### PR DESCRIPTION
**Pull request by niku**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Add documentation for functions to elixir-client

### CODE REVIEW

**Comment by wing328** [comment]
@niku thanks for the PR, which looks good to me.

**Comment by wing328** [comment]
@niku would it be possible to add a few test cases to test the Elixir Petstore API client so that we can use it for integration tests in Travis CI.

Let me know if you need some examples of Petstore test cases.

**Comment by niku** [comment]
@wing328 

Sure. I'll try to add test cases.
Please let me know examples 😃

**Comment by wing328** [comment]
@niku you may find the Clojure Petstore tests useful: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/clojure/test/swagger_petstore/api/pet_test.clj

If you need more examples, just let me know. Thanks!

**Pull request merged**
