### PR TITLE
[Java][RestTemplate] fix compilation issue with API client (resttemplate)

### PR DESCRIPTION
**Pull request by simingweng**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

adapt the "resttemplate" mustaches for generating client which use [threeten](http://www.threeten.org) together with [jackson-datatype-threetenbp](https://github.com/joschi/jackson-datatype-threetenbp) as default dateLibrary

### CODE REVIEW

**Comment by wing328** [comment]
@simingweng thanks for the fix. I tested it locally and the result is good except that `sbt compile` failed.

I wonder if you can update the template for `build.sbt` with the fix as well

**Comment by wing328** [comment]
Closes #5640

**Comment by simingweng** [comment]
@wing328 it seems there has never been a sbt build file created for the "resttemplate" target. I don't have any experience with sbt build system. Probably it would be more efficient to create another issue for missing sbt build support, so someone better than I could transcript maven/gradle to sbt.

**Comment by wing328** [comment]
@simingweng agreed. We'll tackle it separately.

PR merged into master. Thanks for your contribution.

**Pull request merged**
