### PR TITLE
Add a test case that demonstrates how #1993 broke swagger-codegen.

### PR DESCRIPTION
**Pull request by conet**
Demonstrates issue #2362.
cd samples/client/petstore/swift/SwaggerClientTests/
mvn verify
[...]
Testing failed:
    '_type' used within its own type
*\* TEST FAILED **

The following build commands failed:
    CompileSwift normal x86_64 /Users/cristi/Developer/swagger-codegen/samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models.swift
    CompileSwift normal x86_64 /Users/cristi/Developer/swagger-codegen/samples/client/petstore/swift/PetstoreClient/Classes/Swaggers/Models/SpecialModelName.swift
    CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(3 failures)

### CODE REVIEW

**Comment by wing328** [comment]
@conet thanks for the PR. Can you please rebase on the latest master to resolve the merge conflicts?

As shown in the "Commits" tab, the commit is not linked to your Github account so this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors

**Comment by conet** [comment]
@wing328 I rebased the commit and fixed the author (I'm working with multiple repositories and missed that).

**Comment by wing328** [comment]
I'll merge this later as I've been working on enum enhancements for different langauges.

**Comment by wing328** [comment]
@conet thanks for the PR. I wonder if you can try the latest master to see if this is still an issue with the enum in Swift

SNAPSHOT version: https://github.com/swagger-api/swagger-codegen#compatibility

**Pull request closed without merging**
