### PR TITLE
3.0.0

### PR DESCRIPTION
**Pull request by bhaktij29**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by tzimisce012** [comment]
I saw that swagger-parser has a new version too. https://github.com/swagger-api/swagger-parser/tree/v2.0.0-rc0

It would be cool if you can update the version of this since this new version of swagger parser will fix the issue https://github.com/swagger-api/swagger-codegen/issues/6184

What do you think?

**Comment by wing328** [comment]
We'll release 2.3.0 first. 

3.0.0 will be released after adding the support for OpenAPI spec 3.0

**Comment by wing328** [comment]
@tzimisce012 Can you please file a PR against 3.0.0 with the suggested change?

**Comment by tzimisce012** [comment]
Would it be possible to do this change directly in the current version, 2.3.0?

**Comment by wing328** [comment]
> Would it be possible to do this change directly in the current version, 2.3.0?

Our plan is to add OpenAPI spec 3.0 support in Swagger Codegen 3.0.0 release.

**Pull request closed without merging**
