### PR TITLE
 fix the polymorphic issue

### PR DESCRIPTION
**Pull request by AlexInGitHub**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by JeremyTangCD** [comment]
We checked the details of the failure in the AppVeyor building. It seems that the exception happened during the Petstore sample generation. 
We try to run the generation process in our local env, there is no exception comes out, which is weird.
 And we found that the error log is the same with the #8911.  
Is it possible that this is a general problem for the CI env?

**Comment by AlexInGitHub** [comment]
@wing328 team, could you help to review the issue and the PR? Do you think it's OK to merge the OK? Thanks

**Comment by JeremyTangCD** [comment]
For the failure of the "continuous-integration/appveyor/pr" above, it has been improved in https://github.com/swagger-api/swagger-codegen/commit/14ffc12aee2f6c69679af2e0805e8c3e64000079 at Nov. 12, 2018
This branch is just forked at Nov. 9, 2018.
So it is not caused by the committing codes, we could ignore it.

**Comment by JeremyTangCD** [comment]
Hi @kenjones-cisco , could you help to review this PR? Thanks a lot.

**Comment by kenjones-cisco** [comment]
LGTM!
Thanks @AlexInGitHub

**Comment by JeremyTangCD** [comment]
@kenjones-cisco Thank you for reviewing, do you know who can help to merge this PR?

**Comment by kenjones-cisco** [comment]
Sorry, I'm not able to help with merge.

**Comment by AlexInGitHub** [comment]
@kenjones-cisco Do you know who can merge the code?

**Comment by woz5999** [comment]
@webron @HugoMario Can someone please help figure out who is able to review and merge this mix?

**Comment by HugoMario** [comment]
sorry for delay guys, and thanks a lot @AlexInGitHub for PR!!!!

**Comment by motherclangercsinternal** [comment]
How is it looking on fixing the failing Petstore integration tests, please?
I have my own PR that I would like to test.

**Comment by AlexInGitHub** [comment]
@motherclangercsinternal I remembered there should be some error messages on your PR's page

**Pull request merged**
