### PR TITLE
[PHP] add OAuth support 

### PR DESCRIPTION
**Pull request by wing328**
- added OAuth support
- better handle of $ in model name

ref: https://github.com/swagger-api/swagger-codegen/pull/1441
credit: @mach-kernel

### CODE REVIEW

**Comment by wing328** [comment]
After reading the RFC for OAuth 2.0 (http://tools.ietf.org/html/rfc6749), I will rename `auth_token` to `access_token` instead so please put this PR on hold for the time being.

**Comment by mach-kernel** [comment]
@wing328 I noticed that some of the libraries use `auth_token` instead of `access_token` so I wanted to keep this consistent. I do agree, however, that keeping to the RFC is what we should do. I'm going to update this in my branch and test it - you should see the commits appear in the initial PR for the languages I initially mentioned.

Is this OK? :+1:

**Comment by wing328** [comment]
Yes, replacing auth_token with access_token sounds good to me

FYI. Here are some OAuth2 libraries I'd a look at:

https://github.com/intridea/oauth2
https://github.com/adoy/PHP-OAuth2
https://github.com/joestump/python-oauth2

so I think access_token is the preferred name to use.

**Comment by mach-kernel** [comment]
@wing328 I went ahead and did this for ruby, php, java, and python, check the original PR for the addl. commits, thanks!

**Pull request merged**
