### PR TITLE
adds configurable date library, prepares for multiple jaxrs versions

### LINKED ISSUE #1035: Java Codegen not producing joda DateTime for "date-time" format objects in swagger.json
In our codegen project, we have date-time fields that we would like to be generated to joda DateTime objects. Currently, they are parsed into Date objects.

Model in jersey service:
@ApiModelProperty(required = true, position = 9")
public DateTime getCreationTimestamp() { return ModelUtils.millisToJoda(creationTimestamp); }

swagger.json:
```js
creationTimestamp: {
type: "string",
format: "date-time"
}
```
Generated model from codegen:
```java
@ApiModelProperty(required = true, value = "")
  @JsonProperty("creationTimestamp")
  public Date getCreationTimestamp() {
    return creationTimestamp;
  }
  public void setCreationTimestamp(Date creationTimestamp) {
    this.creationTimestamp = creationTimestamp;
  }
```
Is there DateTime support currently in any form? Swagger-core seems to have support for DateTime objects according to the swagger.json, so it seems that if there is no support, it is very much needed.

### PR DESCRIPTION
**Pull request by fehguy**
Fixes #1035 

This commit adds a property for configuring the date library:

```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l jaxrs

...
	dateLibrary
	    Option. Date library to use
	        joda - Joda
	        java8 - Java 8 native

	library
	    library template (sub-template) to use (Default: <default>)
	        <default> - Jersey core 1.18.1
```

The `dateLibrary` is configured by passing `-DdateLibrary=joda` or `-DdateLibrary=java8`, which will configure the proper `@Provider` for the server based on the selection.  If not chosen, the date library will be `java.util.Date`, which is shown by #1035 to not support the `date` format for properties.

### CODE REVIEW

**Comment by dantran** [comment]
@fehguy how do i configure this feature at swagger-codegen-maven-pluign?
my guess is 

    <configOptions>
       ....
       <dateLibrary>joda</dateLibrary>
     </configOptions>

-D

**Comment by fehguy** [comment]
You are correct.  I am updating the instructions for the maven plugin to make this clear.

**Comment by dantran** [comment]
@fehguy looks like you just made changes to maven plugin to support date library config. Could you please push a snapshot to Maven repo?Thanks very much appreciated

**Comment by fehguy** [comment]
Hi, turns out it was already supported. I just improved the docs and added a help method. So current snapshot should be fine

**Comment by dantran** [comment]
I am not sure it this feature is working yet, my generated POJO always use java 'Date' object regarless dateLibrary type  i use

btw, should maven plugin error out if dateLibrary is invalid?

**Comment by fehguy** [comment]
OK I believe this PR addresses server-side generation.  I'll get this added for client generation as well--see options here:

https://generator.swagger.io/#!/servers/getServerOptions

**Pull request merged**
