### PR TITLE
Fix issue5425

### PR DESCRIPTION
**Pull request by guidovezzoni**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

**Please note**: I haven't ran those two script at point 2 as they seem to re-generate code for some java examples, but not for the only one containing parcelables, so I ran instead `./bin/java-petstore-okhttp-gson-parcelable.sh`

### Description of the PR

As requested this PR is for fixing issue [[Android] Bug generating parcelables constructors for custom classes ( missing getClassLoader() ) #5425](https://github.com/swagger-api/swagger-codegen/issues/5425)

Main change was applied to `pojo.mustache`, the other changes committed came from running the  script `./bin/java-petstore-okhttp-gson-parcelable.sh`

Hope I've taken all the steps to create this PR properly, if not please let me know and I'm happy to fix it.

**Please note**: I tried to actually open the project with AS _before_ applying any changes and it looks like there is another problem in class:
`public class AnimalFarm extends ArrayList<Animal> implements Parcelable`
The code seems to assume that just because AnimalFarm is extending another class, also the parent class is parcelable, but in this case it isn't.
I haven't touched this at all, I guess I should create a new issue as it's unrelated?

### CODE REVIEW

**Comment by wing328** [comment]
@guidovezzoni thanks for the PR. please run `./bin/java-petstore-all.sh` to update all Petstore samples for Java as pojo.mustache is used by Java API clients with different HTTP libraries (e.g. jersey, feign, etc)

**Comment by guidovezzoni** [comment]
Sorry for that. I ran both:

- `./bin/java-petstore-all.sh`
- `./bin/security/java-petstore-okhttp-gson.sh`

Not sure if it's intentional but `./bin/java-petstore-all.sh` does **not** call `./bin/java-petstore-okhttp-gson-parcelable.sh`

**Comment by wing328** [comment]
> Not sure if it's intentional but ./bin/java-petstore-all.sh does not call ./bin/java-petstore-okhttp-gson-parcelable.sh

It should. We'll fix that later

**Comment by wing328** [comment]
> I haven't touched this at all, I guess I should create a new issue as it's unrelated?

Yes, please open a new issue for tracking.

**Comment by wing328** [comment]
> Not sure if it's intentional but ./bin/java-petstore-all.sh does not call ./bin/java-petstore-okhttp-gson-parcelable.sh

Updated via b964994

**Comment by guidovezzoni** [comment]
Thanks @wing328 
As for the other issue I mentioned, I actually found an existing issue here: https://github.com/swagger-api/swagger-codegen/issues/4709
This describes the problem I'm seeing in
`public class AnimalFarm extends ArrayList<Animal> implements Parcelable`
in the `okhttp-gson-parcelableModel` example

**Pull request merged**
