### PR TITLE
Rewrite Promise.defer in new style

### PR DESCRIPTION
**Pull request by bherila**
Resolves https://github.com/swagger-api/swagger-codegen/issues/2251

### CODE REVIEW

**Comment by wing328** [comment]
@bherila thanks for the PR. Does `typescript-angular` require similar update? 

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/TypeScript-Angular/api.mustache

**Comment by bherila** [comment]
No, because Angular.js uses `q` for its Promises abstraction.

https://docs.angularjs.org/api/ng/service/$q

Regards,
Ben

**Comment by wing328** [comment]
@bherila  Ah ok. Thanks for the confirmation. I did a test wth the Typescript-Node Petstore but got errors (partially shown below):
```
api.ts(191,9): error TS2300: Duplicate identifier 'apiKey'.
api.ts(195,9): error TS2300: Duplicate identifier 'apiKey'.
api.ts(207,9): error TS2300: Duplicate identifier 'apiKey'.
api.ts(211,9): error TS2300: Duplicate identifier 'apiKey'.
api.ts(215,9): error TS2300: Duplicate identifier 'apiKey'.
api.ts(271,35): error TS2345: Argument of type '{ response: IncomingMessage; body: any; }' is not assignable to parameter of type 'Thenable<{ response: ClientResponse; body?: any; }>'.
  Object literal may only specify known properties, and 'response' does not exist in type 'Thenable<{ response: ClientResponse; body?: any; }>'.
api.ts(321,35): error TS2345: Argument of type '{ response: IncomingMessage; body: any; }' is not assignable to parameter of type 'Thenable<{ response: ClientResponse; body?: any; }>'.
  Object literal may only specify known properties, and 'response' does not exist in type 'Thenable<{ response: ClientResponse; body?: any; }>'.
api.ts(379,35): error TS2345: Argument of type '{ response: IncomingMessage; body: any; }' is not assignable to parameter of type 'Thenable<{ response: ClientResponse; body?: any; }>'.
  Object literal may only specify known properties, and 'response' does not exist in type 'Thenable<{ response: ClientResponse; body?: any; }>'.
```
To reproduce, please run the following:
```
./bin/typescript-node-petstore.sh
cd /Users/williamcheng/Code/swagger-codegen/samples/client/petstore/typescript-node
npm install && npm test
```

Some of the errors are due to new (fake) endpoints for testing mutliple authentication scheme: https://github.com/swagger-api/swagger-codegen/issues/2274 and we would appreciate if you can help fix it as well and update the test cases.

**Comment by pixelshaded** [comment]
https://github.com/swagger-api/swagger-codegen/pull/2518 for duplicate identifier issue.

**Comment by bherila** [comment]
Looks like it's fixed now.

```
$ npm test

> petstore-typescript-node-sample@1.0.0 test /Users/ben/Documents/projects/swagger-codegen/samples/client/petstore/typescript-node
> tsc && node client.js

Created pet with ID 18291
Updated pet using POST body
Updated pet using POST form
Uploaded image
Got pet by ID: {"id":18291,"name":"TypeScriptDoggie","photoUrls":["http://url1","http://url2"],"tags":[{"id":18291,"name":"TS tag 1"}],"status":"pending"}
Deleted pet
```

**Comment by wing328** [comment]
@bherila I tested with your branch and got the same result as you've shown.

But after I performed `mvn clean && ./bin/typescript-node-petstore.sh` and tested agin, I got the following errors:
```
(venv)typescript-node|bherila-typescript-es6-promises⚡ ⇒ npm test

> petstore-typescript-node-sample@1.0.0 test /Users/williamcheng/Code/swagger-codegen/samples/client/petstore/typescript-node
> tsc && node client.js

api.ts(191,35): error TS2345: Argument of type '{ response: IncomingMessage; body: any; }' is not assignable to parameter of type 'Thenable<{ response: ClientResponse; body?: any; }>'.
  Object literal may only specify known properties, and 'response' does not exist in type 'Thenable<{ response: ClientResponse; body?: any; }>'.
api.ts(254,35): error TS2345: Argument of type '{ response: IncomingMessage; body: any; }' is not assignable to parameter of type 'Thenable<{ response: ClientResponse; body?: any; }>'.
  Object literal may only specify known properties, and 'response' does not exist in type 'Thenable<{ response: ClientResponse; body?: any; }>'.
api.ts(307,35): error TS2345: Argument of type '{ response: IncomingMessage; body: any; }' is not assignable to parameter of type 'Thenable<{ response: ClientResponse; body: Pet[]; }>'.
  Object literal may only specify known properties, and 'response' does not exist in type 'Thenable<{ response: ClientResponse; body: Pet[]; }>'.
```
(I tested with petstore.yaml, which is the original petstore spec without any modificiation, but still got the same error)

I wonder if you can take a look when you've time.

**Comment by bherila** [comment]
Ah, this is because typescript is configured to compile to ES5, which does not have ES6 promises. I've updated the spec and tests one more time. Some caveats:

* `finally` is not part of the es6 promises spec... instead `catch` returns a new promise which can in turn be resolved to continue the `then` chain, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise
* I've merged in some other updates regarding the enum names which (until now) could possibly be illegal identifiers, which made it possible for me to also do some e2e testing on my own API. 

```
:typescript-node ben$ npm test

> petstore-typescript-node-sample@1.0.0 test /Users/ben/Documents/projects/swagger-codegen/samples/client/petstore/typescript-node
> tsc --target ES6 && node client.js

Created pet with ID 18291
Updated pet using POST body
Updated pet using POST form
Uploaded image
Got pet by ID: {"id":18291,"name":"TypeScriptDoggie","photoUrls":["http://url1","http://url2"],"tags":[{"id":18291,"name":"TS tag 1"}],"status":"pending"}
Deleted pet
```

**Comment by bherila** [comment]
Not sure why the build suddenly failed? 

> There were failing tests. See the report at: file:///home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/okhttp-gson/build/reports/tests/index.html

**Comment by wing328** [comment]
Don't worry. I've restarted it. Let's see how it goes.

**Comment by wing328** [comment]
@bherila  Thanks for the quick turnaround. Is it correct to say that this change is not backward-compatible with ES5?

**Comment by bherila** [comment]
Yes that is correct, I will resolve the merge conflict now.

**Comment by bherila** [comment]
> Yes that is correct, I will resolve the merge conflict now.

However:if the end user `require`s bluebird the APIs are backwards compatible with ES6 promises. We just don't include bluebird for them anymore nor do we use any bluebird-specific APIs that are not part of ES6 promises.

**Comment by bherila** [comment]
@wing328 anything you can do to address:

```

  1) StoreApi getInventoryInObject:
     Uncaught Error: Internal Server Error
      at Request.callback (node_modules/superagent/lib/node/index.js:823:17)
      at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:1046:12)
      at endReadableNT (_stream_readable.js:893:12)

```

**Comment by wing328** [comment]
I've restarted it.

(getInventoryInObject, a fake endpoint for testing return of object, will be removed from the spec shortly)

**Comment by bherila** [comment]
> I've restarted it.
👍 

Also, FWIW, I am now using this version in production and it's working (of course after Find & Replacing "Object" with "any" and removing the interface ;-) )

**Comment by wing328** [comment]
@bherila sorry I was not clear. Would it be possible to make the change backward compatible with ES5 (e.g. via CLI option)?

From what I know ES6 is only partially implemented in most modern browsers.

> ECMAScript 5 (ES5): The 5th edition of ECMAScript, standardized in 2009. This standard has been implemented fairly completely in all modern browsers
> ECMAScript 6 (ES6)/ ECMAScript 2015 (ES2015): The 6th edition of ECMAScript, standardized in 2015. This standard has been partially implemented in most modern browsers. To see the state of implementation by different browsers and tools, check out these compatibility tables.

Ref: http://benmccormick.org/2015/09/14/es5-es6-es2016-es-next-whats-going-on-with-javascript-versioning/

**Comment by pixelshaded** [comment]
Isn't this as simple as including a shim library along with it's type definitions? Like the test could still target es5 for tsc, but include those files. I think the issue would be, how do we notify the user that they will need to include these files in their own build process now?

**Comment by bherila** [comment]
The problem is if you include the library and then target ES6, you get all these tsc errors about "duplicate type: Promise<T>"

@wing328  you are right that ES6 is only supported in modern browsers. However, since we are talking about Node.js here, it is worth mentioning that Node v4 supports ES6 out of the box (and earlier versions also support ES6 with --harmony) flag. 

As for notifying the user... we could put a commented-out require('bluebird') in the generated file. Would that alleviate the concerns somewhat?

**Comment by wing328** [comment]
@bherila just want to share with you that we've recently done something similar for C# API client to support UWP via a CLI option: https://github.com/swagger-api/swagger-codegen/pull/2427.

After reviewing your change, I strongly feel that we can do something similar here.

**Comment by bherila** [comment]
That seems like a good idea 👍 

The natural question is... do we make ES6 the default, and activate ES5 with the flag... or the other way around? I'm in favor of defaulting towards ES6 as many projects seem to be moving that way (including Node itself with default ES6 in v4+)

**Comment by wing328** [comment]
@bherila Either way is fine with me (Personally I'm ok with defaulting towards ES6).

We've previously made breaking changes (with fallback) as mentioned in the [release note](https://github.com/swagger-api/swagger-codegen/releases/tag/v2.1.6).

Here is a list of breaking changes (with fallback) in the previous release:

https://github.com/swagger-api/swagger-codegen/pulls?q=is%3Apr+milestone%3Av2.1.6+label%3A%22Breaking+change+%28with+fallback%29%22+is%3Aclosed

(I've marked this PR as breaking change with fallback for the time being)

Let me know if you need any assistance adding the CLI option for selecting ES5 or ES6.

**Comment by wing328** [comment]
@bherila 

> Also, FWIW, I am now using this version in production and it's working (of course after Find & Replacing "Object" with "any" and removing the interface ;-) )

One way to replace "Object" with "any" as part of the code gen is to override `postProcessModels`, `postProcessOperations` (and would recommend you to do it in a separate PR later)

**Comment by bherila** [comment]
@wing328 now there is a merge conflict and my schedule is not lightening up... can we get this merged and address the fallback option as a separate ticket if/when someone needs it?

**Comment by bherila** [comment]
Either that or we can split typescript-node into typescript-node-es5 and typescript-node-es6 which avoids changes to the Java code.

**Comment by wing328** [comment]
@bherila I'll try to add the feature to support es5 and es6 via CLI option on Monday. Will keep the community posted.

**Comment by bherila** [comment]
Thanks @wing328 that will be a huge help. I just rebased and fixed the merge conflicts, retesting

**Comment by wing328** [comment]
@bherila thanks for the rebase. I'll work on that later today...

**Comment by wing328** [comment]
Close via #2758

**Pull request closed without merging**
