### PR TITLE
[kotlin] Fix syntax errors of localVariableHeader in api.mustache

### PR DESCRIPTION
**Pull request by yukio-e**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

mapOf function appears repeatedly when request header is supplied.

### CODE REVIEW

**Comment by wing328** [comment]
@yukio-e thanks for the fix. Please run `./bin/kotlin-client-petstore.sh` or `.\bin\windows\kotlin-client-petstore.bat` to update Kotlin petstore client.

**Comment by wing328** [comment]
cc @jimschubert

**Comment by jimschubert** [comment]
@wing328 I believe I modeled those conditionals after Java and Scala generators templates. We may have similar issues elsewhere, but I'm on mobile and don't see repro steps.

**Comment by wing328** [comment]
@jimschubert I'll do a search tomorrow and review those to see if it needs similar fixes.

**Comment by yukio-e** [comment]
@wing328 Thanks, I ran the shell again. Sorry for only executing it before modifying the mustache file.

**Comment by wing328** [comment]
@yukio-e thanks for the PR, which has been merged into the PR.

**Comment by wing328** [comment]
> @jimschubert I'll do a search tomorrow and review those to see if it needs similar fixes.

I did a grep using `{{/hasFormParams}}{{^hasHeaderParams}}){{/hasHeaderParams}}{{#hasHeaderParams}}{{#hasFormParams}}, {{/hasFormParams}}{{#headerParams}}`, `{{/isContainer}}{{^isContainer}}{{paramName}}{{/isContainer}}` but couldn't find something similar in Java, Scala templates.

**Pull request merged**
