### PR TITLE
Java support inheritance

### PR DESCRIPTION
**Pull request by ahgittin**
as per #1015 (and #946) this is now optional and disabled by default. this results in extra unnecessary code, masking fields in some cases, and breaks code generated for jax-rs in certain cases (enums with inheritance).

as noted by @xhh at #1050 this is not a perfect fix, but it improves the situation significantly (restoring `master` branch behaviour, as the current situation is a regression; my spec builds fine with master but not with `develop_2.0` ?).

### CODE REVIEW

**Comment by wing328** [comment]
@ahgittin do you mind sharing the spec with us assuming it can be shared publicly?

**Comment by ahgittin** [comment]
@wing328 here's a cut-down test case whose `-l jaxrs` makes for invalid java without this, valid java with this:

```
swagger: '2.0'
info:
  title: buggy inheritance for java
  version: "0.0.1"
definitions:
  Super:
    properties:
      my_enum:
        type: string
        enum: [ A, B ]

  Sub:
    allOf:
    - $ref: '#/definitions/Blueprint'
    - type: object
    properties:
      another:
        type: string

paths:
  /home:
    get:
      summary: with develop_2.0 prior to #1094 the java generated fails
```

**Comment by ahgittin** [comment]
also noticed this had some strange commits; i've rebased so it's just the one-line change

**Comment by webron** [comment]
FWIW, that's not inheritance, that's composition. In this case, `Sub` and `Super` have no parent-child relationship. The end result in this case would be that `Sub` would include the same properties as `Super` but will not inherit from it.

**Comment by ahgittin** [comment]
sorry @webron i mis-typed the example, it's now correct, and it definitely is implemented as inheritance (maybe it shouldn't be):

```
public class Sub extends Super {
  
  public enum MyEnumEnum {
     A,  B, 
  }
`

redeclaring the enum breaks compilation as `Super.getMyEnum()` returns the parent's `MyEnumEnum` so `Sub.getMyEnum()` has an incompatible return type

HTH

**Comment by webron** [comment]
Not sure what's changed, but as long as there's no `discriminator`, there's no inheritance (from the spec's point of view).

**Comment by wing328** [comment]
If we look at the java client in the "master" branch, we'll find that it implements `allOf` using `extends` in Java, which is not the correct implementation as Ron has pointed out that `allOf` is model composition (*not* inheritance)

@xhh previously attempt to fix `allOf` with #946 (copy parent properties) but it does not implement `discriminator` (should be implemented as `extends` in Java) due to time constraint. 

@tandrup introduced `supportsInheritance` to let people choose the behaviour with #1015.

Before someone from the community implements `discriminator`, we can merge this PR for the time being to keep the old (master) behaviour if no one has any concern.

**Comment by webron** [comment]
I'd suggest putting a hold on the `discriminator` implementation as there's a technical detail with the spec we need to resolve first. It'll be done with in the upcoming weeks, and will come with an implementation (or suggestion for implementation). Sorry for the trouble on this one.

**Comment by ahgittin** [comment]
closing and will resubmit against master as per change to swagger PR process

**Comment by ahgittin** [comment]
closed in favour of #1120

**Comment by steverice** [comment]
> there's a technical detail with the spec we need to resolve first

@webron  are you referring to https://github.com/swagger-api/swagger-spec/issues/403?

**Comment by webron** [comment]
That is correct. It should be resolved soon.

**Pull request closed without merging**
