### PR TITLE
[TypeScript][Node] support for overriding HTTP request headers

### PR DESCRIPTION
**Pull request by silasbw**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This approach is inspired by the typescript-fetch implementation.

Fixes https://github.com/swagger-api/swagger-codegen/issues/9035

### CODE REVIEW

**Comment by silasbw** [comment]
cc @CodeNinjai and @wing328

I wanted to attach an example implementation that satisfies https://github.com/swagger-api/swagger-codegen/issues/9035.  I realize this PR could be extended to provide more consistency with typescript-fetch by, for example, implementing `qs` overrides. I'm happy to help do that, or try a different approach for setting content-type.

**Comment by wing328** [comment]
@silasbw Thanks for tagging me but I'm no longer involved in this project. I hope others will be able to help you out. Good luck.

**Comment by silasbw** [comment]
@CodeNinjai are the right person to provide feedback on this? or could you tag the right person?

**Comment by silasbw** [comment]
fwiw, I added a similar change to openapi-generator: https://github.com/OpenAPITools/openapi-generator/pull/1868

**Comment by silasbw** [comment]
@frantuma, I saw you had some commit activity recently :)  any chance you can point me at the maintainers for this code so I can work with them on this change?

**Comment by HugoMario** [comment]
hello @silasbw thanks a lot for this PR. i think i'm going to take a time to port this to 3.0.x version. BTW any time you need help with a PR just let me know.

**Comment by silasbw** [comment]
Sounds good, thanks @HugoMario :+1:

**Pull request merged**
