### PR TITLE
Issue #3138

### PR DESCRIPTION
**Pull request by stunney**
https://github.com/swagger-api/swagger-codegen/issues/3138

Adds " virtual" to the controller moustache file so that the controllers
can be inheritted from.

### CODE REVIEW

**Comment by stunney** [comment]
@wing328 would it be possible to get this PR in sooner rather than later? :)

**Comment by wing328** [comment]
@stunney please run `./bin/aspnet5-petstore-server.sh` (mac/linux) or `bin/windows/aspnet5-petstore-server.bat` (windows) to update the Petstore sample

cc @jimschubert

**Comment by jimschubert** [comment]
I don't see a problem with this change, but also can't think of a use case for this inheritance. Can you provide an example?

**Comment by stunney** [comment]
Well the HttpPostAttribute and RouteAttribute have the Inherited value of true, so any subclass that overrides the methods will get the decorators implicitly.

What we are aiming to do is generate code from the main which will generate a versions NuGet package.  That package will be included in our actually impl service to separate the code gen cleanly.

TBH generating a pure abstract class would be "better" but this is the least intrusive and non breaking change I could think of.

**Comment by stunney** [comment]
I've noticed that the Swashbuckle.Swagger.Annotations.SwaggerOperationAttribute is not marked with the inheritted flag.  This can easily be fixed though.

**Comment by stunney** [comment]
@wing328, @jimschubert 
I have executed bin/windows/aspnet5-petstore-server.bat (windows).  We shall see what Travis-ci has to say about it :)

**Comment by stunney** [comment]
And actually, with regard to the SwaggerOperationAttribute (and the others), the default value for inherited is true, provided one actually marks an attribute class with the AttributeUsageAttribute attribute :)

**Comment by stunney** [comment]
@wing328, @jimschubert,
Any change I could get this PR accepted sooner than later?

I have more to make and wanted this one off my plate, pretty please with sugar on top :)

**Comment by jimschubert** [comment]
@stunney

I don't have merge rights, I only do reviews. I think @wing328 was probably waiting for a response from you, since your third previous comment sounded like you had some travis-ci validations of your own running.

**Comment by stunney** [comment]
Nope, all is done on my end.  @wing328 , can you help a coder out?

Thanks for the feedback, @jimschubert, I will attempt to be less ambiguous in the future.

**Comment by wing328** [comment]
@stunney I've merged the PR. Thanks for the contribution.

**Comment by stunney** [comment]
Thanks @wing328 !! Glad I could contribute.

**Pull request merged**
