### PR TITLE
Update gitignore to ignore dist folder

### PR DESCRIPTION
**Pull request by BastiOfBerlin**
ignore dist folder

### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Adding the dist folder to .gitignore so that it isn't packed by `npm package`.

### CODE REVIEW

**Comment by wing328** [comment]
@BastiOfBerlin thanks for the PR, which looks good to me.

**Comment by wing328** [comment]
@BastiOfBerlin shall we do the same for typescript-angular, typescript-node and typescript-fetch as well?

cc @Vrolijkx

**Comment by BastiOfBerlin** [comment]
@wing328 sounds reasonable

**Comment by wing328** [comment]
FYI. Filed https://github.com/swagger-api/swagger-codegen/pull/4799 to update other TS generators.

**Pull request merged**
