### PR TITLE
fix #2159 dataformatter error for iOS Swift

### LINKED ISSUE #2159: NSDateFormatter FatalError on iOS Swift
Setting the device to use 12-hour time format then trying to parse a 24-hour time from JSON causes the formatter to fail and the Models.swift initialize method to throw a FatalError.

Example time string: 2016-02-17T20:00:00.000+00:00

Setting the formatters locale fixes this issue:

`let formatter = NSDateFormatter() //Models.swift Line 106

formatter.locale = NSLocale(localeIdentifier:"en_US_POSIX") //Set the formatter locale

formatter.dateFormat = format

return formatter`

### PR DESCRIPTION
**Pull request by fumitoito**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

When trying to parse 24-hour time to 12-hour time, date formatter throws fatal error.
It's caused by lack of settings locale for date formatter.

see also #2159 .

### CODE REVIEW

**Comment by wing328** [comment]
@fumitoito thanks for the PR. Please run `./bin/swift-petstore-all.sh` to update Swift Petstore samples.

**Comment by wing328** [comment]
cc @jaz-ah @jgavris @Edubits

**Comment by fumitoito** [comment]
@wing328 thanks for the review and I just update samples by `./bin/swift-petstore-all.sh`. Please check it.

**Comment by jgavris** [comment]
👍

**Comment by wing328** [comment]
@jgavris thanks for reviewing the change.

@fumitoito thanks for your contribution.

**Comment by wing328** [comment]
@fumitoito If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen)

**Pull request merged**
