### PR TITLE
[JAVA-SpringFramework][5089] Added a new additional option that allows one to replace the the 'fil…

### PR DESCRIPTION
**Pull request by LEgregius**
**I reworked this PR from an earlier one.  All it really does is fix the commit email.**

I left a description of the issue here:  #5089

This adds a new additional command line property called `resourceStreams` that replaces `java.io.File` with `org.springframework.core.io.Resource` in Spring Framework when specifying a `file` type in the yaml.  I ran normal unit tests, and they passed, and what I added is simple, and should have no effect without specifying the command line option, but it allows me to return file data that isn't stored locally on the rest server serving the api, and it lets me stream it from the original place, through the server, and down to the client without having to store the whole file all at once.

The largest block of the code change is providing an example value that shows how to make it work exactly the same as it did by wrapping a `java.io.File` in a `FileSystemResource`, which is an implementation of the Resource interface.

### CODE REVIEW

**Comment by wing328** [comment]
@LEgregius thanks for the PR

cc @cbornet

**Comment by cbornet** [comment]
Instead of creating yet another option, I would prefer to generate `Resource` by default as it's better than File.
@LEgregius did you test if it works fine with the spring-cloud client impl ?

**Comment by LEgregius** [comment]
The petstore examples build, to say nothing of running them.  If you want to make it the default, that makes sense.  I don't know if that will break anyone.  If someone plans on uploading a file via an api, then it needs to use a org.springframework.web.multipart.MultipartFile, so a Resource isn't really the right solution there, but it doesn't seem like the generator is smart enough right now to make the distinction between incoming and outgoing types.

**Comment by cbornet** [comment]
I think MultipartFile is already used for file upload (see https://github.com/swagger-api/swagger-codegen/blob/fb7599652794f7127b4f5dfaba4439d1933d3c7f/modules/swagger-codegen/src/main/resources/JavaSpring/apiController.mustache#L19) . So it should be fine.

**Comment by cbornet** [comment]
The MultipartFile type is hard coded in the templates

**Comment by LEgregius** [comment]
Okay, then.  What should I do?  Remove the option?  Without the option on the type, the code change is literally just 
```
    typeMapping.put("file", "Resource");
    importMapping.put("Resource", "org.springframework.core.io.Resource");```

Plus, the example value, if that's even necessary.

**Comment by ePaul** [comment]
As I commented on the issue, I think using `java.util.File` never made sense here, so I'm for using Resource instead when we are in a Spring context anyways.

**Comment by cbornet** [comment]
@LEgregius @ePaul yes remove the option and just change the typeMapping 👍

**Comment by LEgregius** [comment]
Is there anything else I need to do for this PR before it gets merged?

**Comment by wing328** [comment]
@LEgregius taking another look now...

**Comment by wing328** [comment]
@LEgregius I've updated the Petstore samples for spring-related generators and the result looks good.

Thanks for the contribution 👍

**Pull request merged**
