### PR TITLE
fix: use information in generator host for generating spec

### PR DESCRIPTION
**Pull request by fgreinacher**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

I missed that the current implementation does not consider base path and schemes in the `GENERATOR_HOST` variable correctly, making the generate spec incorrect for some scenarions.

🛠 with ❤ at [Siemens](https://opensource.siemens.com/)

### CODE REVIEW

**Comment by fgreinacher** [comment]
@frantuma Can I do something to get this in soonish? We're eagerly waiting for it 🙂

**Comment by fgreinacher** [comment]
@HugoMario @frantuma Sorry folks to bug you, but it would be really great to have this merged. We're a bit blocked by this at the moment. Also tell me if I can help somehow!

**Comment by fgreinacher** [comment]
> @HugoMario @frantuma Sorry folks to bug you, but it would be really great to have this reviewed/merged. We're a bit blocked by this at the moment. Also tell me if I can help somehow!

@HugoMario @frantuma New month, new try 😄  Do you see a chance to make progress here? As mentioned I'll gladly help you it with whatever needs to be done, just ping me :heart:

**Comment by fgreinacher** [comment]
> New month, new try 😄 Do you see a chance to make progress here? As mentioned I'll gladly help you it with whatever needs to be done, just ping me ❤️

@HugoMario @frantuma Here is your monthly ping 🙇

**Comment by HugoMario** [comment]
lol
sorry @fgreinacher for delay. Let me check this and help you with the merge if everything is ok

**Comment by HugoMario** [comment]
thanks a lot @fgreinacher 
Sorry again for the delay to check this.

**Comment by fgreinacher** [comment]
> thanks a lot @fgreinacher
> Sorry again for the delay to check this.

No worries and thanks for taking care ✌️

**Pull request merged**
