### PR TITLE
Make generic model compatible with PHP 8.1

### PR DESCRIPTION
**Pull request by BafS**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Add `#[\ReturnTypeWillChange]` (https://php.watch/versions/8.1/ReturnTypeWillChange) to avoid deprecation notices.

Fixes https://github.com/swagger-api/swagger-codegen/issues/11820

cc. @dkarlovi and @mandrean

### CODE REVIEW

**Comment by EgorBurykin** [comment]
Hello, is there any way we can have it merged? It seems to be a valid workaround.

**Comment by mbouwer** [comment]
This would certainly help us. The PR seems valid, could this be merged into the codebase please?

**Comment by BafS** [comment]
@dkarlovi and @mandrean, would it be possible to merge this PR?

**Comment by BafS** [comment]
or @gracekarina maybe

**Comment by deguif** [comment]
Any news on this one, many projects are waiting to support PHP 8.1 as without this, it triggers deprecations.

**Comment by BafS** [comment]
@HugoMario maybe you could help me to merge the PR? The PHP maintainers do not seems to reply. Thanks in advance!

**Comment by deguif** [comment]
ping @frantuma maybe

**Review by deguif — APPROVED** [review]

**Comment by BafS** [comment]
@char0n @gracekarina @ponelat @frantuma could anyone help us to merge this PR?

**Comment by deguif** [comment]
@BafS in the meantime you can rebase the branch so that `This branch is out-of-date with the base branch` message disappears.

Let's hope that a core contributor will be able to have a look and merge this one soon as it's a real pain currently for PHP >= 8.1 and will become more and more annoying as PHP 8.2 is near to be released.

**Comment by ponelat** [comment]
Thanks for your patience folks, from my limited knowledge of PHP, `ReturnTypeWillChange` is backwards compatible with older versions of PHP? If so, I think it should be good to merge.  @HugoMario if you're happy, I think lets get this merged.
And yes please, could you rebase @BafS

**Comment by deguif** [comment]
@ponelat thanks for your feedback.
You're right, `#[\ReturnTypeWillChange]` is backward compatible as attributes are not interpreted on PHP versions lower than 8.x.

**Comment by BafS** [comment]
@ponelat Thanks for your answer! PR rebased, and yes as @deguif says, it is fully backward compatible.

**Comment by frantuma** [comment]
Thanks!

**Comment by BafS** [comment]
Thank you! Do you know when the next release will be tagged?

**Comment by BafS** [comment]
@frantuma any chance to create a new tag to have the release available to the world?

**Pull request merged**
