### PR TITLE
Add defaultInterfaces config key to spring generator

### LINKED ISSUE #8833: [JAVA/Spring] Using java8 <dateLibrary> causes default interface implementations regarding <java8>false</java8>
##### Description

When enabling `<dateLibrary>java8</dateLibrary>` in `<configOptions>`, default methods are created in API contract interface. Even if I set the value `<java8>false</java8>`.

According to the help, `<java8>` option produces the aforementioned default interface methods:

>java8
	use java8 default interface (Default: false)

I want the advantage of Java 8 types (date,...) but not default interface which is not very convenient as does **not enforce** to implement the API contract in controllers. I am using the `<interfaceOnly>true` option as I am only interested in generating the API contract and model classes.

##### Swagger-codegen version

3.0.2

    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.2</version>

##### Command line used for generation

mvn compile

##### Related issues/PRs

https://github.com/swagger-api/swagger-codegen/issues/8045

##### Suggest a fix/enhancement

Enable a dedicated option for default interface independent of other Java 8 feature such as Optional class, Date library or others, or at least fix it so we can use a mix of options such as:

    <useOptional>true</useOptional>
    <dateLibrary>java8</dateLibrary>
    <java8>false</java8>

### PR DESCRIPTION
**Pull request by sonOfRa**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This is intended to fix #8833. A similar PR has been filed for the v3 generators
under https://github.com/swagger-api/swagger-codegen-generators/pull/474

Should I actually regenerate the examples for this PR? It seems like they haven't been re-generated since 2.4.3, and a lot of them don't actually contain the ``default`` interface implementations anyways.

The technical committee for the java language doesn't seem to exist so I skipped that step.

### CODE REVIEW

**Comment by HugoMario** [comment]
hi @sonOfRa 
can you please check the test fail?
```
Failed tests: 
  SpringOptionsTest>AbstractOptionsTest.checkOptionsHelp:44 These options weren't checked: defaultInterfaces.
Tests run: 677, Failures: 1, Errors: 0, Skipped: 3
```

**Comment by sonOfRa** [comment]
@HugoMario sorry for the delay, but I'm back now to investigate. I had the problem that locally, I was apparently running on Java 11 which caused over 100 test failures, so I figured that tests weren't actually functional and didn't really look into any specific failues. Rerunning now with java 8 to take a look at the tests.

**Comment by sonOfRa** [comment]
@HugoMario is there anything else needed from me on this PR?

**Comment by HugoMario** [comment]
hey @sonOfRa , sorry for delay. please, let me find out what is wrong with `Travis CI` before merging this PR

**Comment by HugoMario** [comment]
thanks a lot @sonOfRa !!

**Pull request merged**
