### PR TITLE
Make java spring controller constructor public.

### LINKED ISSUE #4968: Make Controller constructor public in spring mvc generator
##### Description

I am using swagger codegen with the delegatePattern option. I want to manually create the swagger generated controller in the spring configuration file and inject its delegate, instead of letting spring scan for controllers and autowire the delegate. The problem is that the generated constructor is package access.

##### Swagger-codegen version

This happened in 2.2.2.

##### Suggest a Fix

Simpy add public to the generated Controllers constructor.

### PR DESCRIPTION
**Pull request by pablograna**
This lets users manually create the controller and inject the delegate in the
spring configuration file, instead of letting spring scan for controllers and
autowire the delegate.

This should fix #4968.

### PR checklist

- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Please also run `./bin/spring-all-pestore.sh` to update Spring-related Petstore samples so that CIs can verify the change.

**Comment by pablograna** [comment]
Thanks, wing328. My apologies for not going through the contributors guideline. Fixed (hopefully).

**Comment by wing328** [comment]
@pablograna thanks for the PR, which has been merged into master.

**Comment by pablo-ml** [comment]
Nice to know, thanks a lot

**Pull request merged**
