### PR TITLE
[Ruby] Can only use content-type application/json with ruby-client #4867

### PR DESCRIPTION
**Pull request by viktorchukhantsev**
Fix ruby-client work with modern content types, like application/api.vnd+json

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Can you please also do the following?

1) update https://github.com/swagger-api/swagger-codegen/blob/1dd9ee39af6c4e2f9c016a94d16ca47a88a9cb0d/samples/client/petstore-security-test/ruby/spec/api_client_spec.rb#L174 with a new test case to cover the issue you've addressed

2) run ./bin/ruby-petstore.sh to update Ruby Petstore sample so that the CIs can test the change.

**Comment by viktorchukhantsev** [comment]
@wing328 Updated.

**Comment by wing328** [comment]
@viktorchukhantsev thanks for the contribution, which has been merged into master.

**Pull request merged**
