### PR TITLE
Typescript Property Renaming Fix

### LINKED ISSUE #2776: Typescript: Dates Are Not Deserialized
If you have a property in a definition that is a string with date-time format, the typescript generated makes that property a Date type. However, the response in the client is given verbatim. It never looks for date strings and actually transforms them in to Date objects. So the project will build, but fails at runtime if you try to access Date specific methods since it's actually a string.

I imagine this relates to:
https://github.com/swagger-api/swagger-codegen/issues/1951

Since this PR focuses on deserializing dates in the response. I would suggest making those properties strings until deserialization is supported, otherwise the type checking isn't actually accurate.

### PR DESCRIPTION
**Pull request by TiFu**
First: First time contributor, so feel free to yell at me :-).

### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

Second Point: Is it enough if i recreated the samples for typescript-node (e. g. I don't have to recreate typescript-angular samples)? I only changed one file in swagger-codegen/src/main/resources/typescript-node. 

### Description of the PR

Reference: #2766
This also fixes #2776

The Typescript-Node-Client did not parse the JSON returned from requests, so that properties, which were renamed (e. g. from mounted_at in the response to mountedAt in the model), still appeared as the non-renamed version (e. g. mounted_at) in the model object.

This PR fixes this issue by adding property maps and parsing the JSON recursively.

NOTE:
I'm not sure if this change breaks backwards compatibility, so I filed the PR against 2.3.0.

I hope that I did not miss any cases, I need to handle. It would be great if someone with more experience with swagger-codegen, than I have, could take a look at the code.

### CODE REVIEW

**Comment by TiFu** [comment]
@wing328 I just read the discussion in PR #4267. I will update my PR to use Map[baseName, type] and Map[baseName, name] maps in the model and create a general deserializer/serializer. 
Compared to that my solution is ugly at best.

**Comment by wing328** [comment]
@TiFu I would suggest we wait till @gregjacobs to update his PR so that we can reuse the same solution in all Typescript API clients (node, angular, angular2, typescript)

**Comment by TiFu** [comment]
@wing328 
I have some questions:

1. How can I fix the issue appveyor is reporting? see [1]
2. How can I fix the issue travis is reporting? see [2]
    - Is there a way to trigger a rebuild?
3. The PHP Object serializer [0] has a method for sanitizing the filename which seems to be used when the Content-Disposition header is present. Why is that sanitization necessary?

[0] https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/lib/ObjectSerializer.php

[1]
```
git clone https://github.com/wing328/swagger-samples
fatal: destination path 'swagger-samples' already exists and is not an empty directory.
Command exited with code 128
```

[2]
```[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Swagger Petstore - Javascript Client 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (npm-install) @ swagger-petstore-javascript ---
npm WARN package.json swagger_petstore@1.0.0 No repository field.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/bin/npm" "install"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! syscall read```

**Comment by wing328** [comment]
1) You can ignore or it (or rebase on the latest master to fix it).

2) I've restarted that particular job manually. To trigger a rebuild, please close and reopen the PR (which will trigger **all** the tests).

3)  `sanitizeFilename` is for sanitizing filename to remove relative path (e.g. `../../../newfile.txt`) so as to prevent potential security issues when storing the file in a relative path.

**Comment by TiFu** [comment]
Some testing from the community would be appreciated :-)

**Comment by wing328** [comment]
@TiFu thanks for the PR. If it's too much work, I wonder if you can add some tests for serialization/deserialization of models similar to what we've done for PHP models: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/php/SwaggerClient-php/tests/OrderApiTest.php#L43-L132

**Comment by TiFu** [comment]
I'll look into it next week and update my PR.

**Comment by wing328** [comment]
@TiFu please take your time. I would recommend writing tests cases for the `Pet` object, which contains nested objects `Tag`, `Category`: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore.yaml#L653

**Comment by TiFu** [comment]
@wing328 I finally got around to writing the test case for the Pet class.

One of the checks still fails, which is due to some issue on the 2.3.0 branch in the python tests. Is this a known issue?

**Comment by wing328** [comment]
@TiFu yes, it's an issue that occurs 2 days ago due to Python package dependencies.

I'll review the change later today and let you know if I've any question.

**Comment by wing328** [comment]
@TiFu I notice that some indentations are using tab instead of 4-space. Do you mind using 4-space instead as per TS style guide: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#style ?

**Comment by TiFu** [comment]
@wing328 I converted the tabs to 4 spaces.

**Comment by wing328** [comment]
@TiFu after resolving the Python test issue, I got the following errors related to TS node client:
```
> @swagger/angular2-typescript-petstore@0.0.1-SNAPSHOT.201605241654 build /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-node/npm
> tsc

client.ts(138,52): error TS2345: Argument of type 'ReadStream' is not assignable to parameter of type 'Buffer'.
  Property 'write' is missing in type 'ReadStream'.

npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v4.1.2/bin/node" "/home/travis/.nvm/versions/node/v4.1.2/bin/npm" "run" "build"
npm ERR! node v4.1.2
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! @swagger/angular2-typescript-petstore@0.0.1-SNAPSHOT.201605241654 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @swagger/angular2-typescript-petstore@0.0.1-SNAPSHOT.201605241654 build script 'tsc'.
npm ERR! This is most likely a problem with the @swagger/angular2-typescript-petstore package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get their info via:
npm ERR!     npm owner ls @swagger/angular2-typescript-petstore
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/typescript-node/npm/npm-debug.log
```
Ref: https://api.travis-ci.org/jobs/198043571/log.txt?deansi=true

I wonder if you can take a look when you've time.

**Comment by TiFu** [comment]
Can you confirm that this issue also happens on the `2.3.0` branch? If I recreate the sample for ts-node and then run the test with `mvn verify`, the same issue happens.

It seems like a change in `PetAPI.uploadFile(args)` causes this issue (the type of the last argument `file` changed from `any` to `Buffer`). I have commited a fix in 6178cb0475d3afde1087ab93cb747c541eef8af7 .

If it works in `2.3.0`, I will have to dig deeper and check how I could have introduced this bug.

**Comment by wing328** [comment]
> @wing328 Can you confirm that this issue also happens on the 2.3.0 branch? If I recreate the sample for ts-node and then run the test with mvn verify, the same issue happens.

Let me try with a new branch and update the TS node petstore sample to confirm...

**Comment by wing328** [comment]
Btw, the tests now look good after you pushed 6178cb0

https://travis-ci.org/swagger-api/swagger-codegen/builds/198072272

**Comment by wing328** [comment]
Here is the job for updated TS Node Petstore based on 2.3.0: https://travis-ci.org/swagger-api/swagger-codegen/builds/198085651 (still running)

**Comment by wing328** [comment]
UPDATE: https://travis-ci.org/swagger-api/swagger-codegen/builds/198085651 finished without issue.

**Comment by TiFu** [comment]
Isn't that build based on master? 

Anyway:
The issue you noticed is caused by the typemapping from `file` => `Buffer`. This mapping was added to TypeScriptNodeCodegen.java almost a year ago. Somehow the ts node tests still contain the previous `any` type mapping defined in AbstractTypeScriptCodegen.java. 
Another thing I noticed is, that TypeScriptNodeCodegen uses `typeMapping.put("file", "Buffer");`, whereas AbstratcTypeScriptCodegen uses `typeMapping.put("File", "any");` (note the capitalization of `file`)
Does that make any difference or was that changed recently?

The issue you saw was fixed on master in 55443dae on 17 January 2017 (with the same fix I pushed a couple hours ago)
However, the fix was not applied to 2.3.0, which is why this error popped up. 

I have no idea why this did not appear earlier. Maybe it was a caching issue on my side so that the tests did not get updated properly or the behaviour of typeMapping was changed recently.

Like you said above the tests are fine now. Do I need to do anything else to get this PR merged?

**Comment by wing328** [comment]
> Like you said above the tests are fine now. Do I need to do anything else to get this PR merged?

No, I believe we all appreciate your effort in this PR and I'll merge shortly so that other developers can enjoy the enhancements you put into the Typescript generators.

**Comment by wing328** [comment]
> Another thing I noticed is, that TypeScriptNodeCodegen uses typeMapping.put("file", "Buffer");, whereas AbstratcTypeScriptCodegen uses typeMapping.put("File", "any"); (note the capitalization of file)

Ideally we want to make it consistent across all TS generators. I'll create another issue to track this.

cc @Vrolijkx

**Comment by cenkentimist** [comment]
What's the rational for transforming snake case to camel case anyway? What about just leaving things as they are? given the number of bugs caused by _ conversion this might make sense? I myself prefer camel case to snake case but the current state of things basically guarantees that '_' causes bugs. It also adds unnecessary decode overhead and complexity. 

@TiFu has anyone tested what happens if there's a model with both 
hiThere and hi_there

**Comment by wing328** [comment]
@cenkentimist 

> What's the rational for transforming snake case to camel case anyway?

We want the property naming to conform to the style guide: https://github.com/Microsoft/TypeScript/wiki/Coding-guidelines#names

> What about just leaving things as they are?

There's an option you can do so:
```
	modelPropertyNaming
	    Naming convention for the property: 'camelCase', 'PascalCase', 'snake_case' and 'original', which keeps the original name (Default: camelCase)`
```
Would that meet your requirement?

**Comment by cenkentimist** [comment]
@wing328 That's awesome.

**Comment by wing328** [comment]
@cenkentimist another reason is that other API client generators (e.g. PHP, Python) also has a serializer/deserializer for JSON and we want to make the TS generators more consistent with other generators.

**Comment by wing328** [comment]
> Seems in general language specific flags are mostly undocumented?

It's documented in `config-help`: java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar config-help -l typescript-angular2

**Comment by cenkentimist** [comment]
@wing328 Oh. I feel bad for not noticing that myself. Thanks for the clue-hammer.

**Comment by TiFu** [comment]
@cenkentimist This would create a conflict in the model (duplicate attribute name)  and the code will not compile.

**Pull request merged**
