### PR TITLE
fix npe :Unboxing of '(count < numVars) ? true : null' produce npe

### PR DESCRIPTION
**Pull request by Sodala**
Unboxing the boolean will throw java.lang.NullPointerException if the condition is false

### CODE REVIEW

**Comment by ePaul** [comment]
Do you have an example where the NPE happened? (e.g. a API definition + command line used to generate from it)?

**Comment by Sodala** [comment]
If the null was intentional then we need to use Boolean an not boolean.  I have an example but it is a bit big so I will try to keep the essentials. I come back to you as soon as it is done

**Comment by ePaul** [comment]
**Some history exploration:**

It looks like this line (and the surrounding code with `reconcileInlineEnums`) was added in f4773d3333c263 (2015-11-20, which ultimately seems to belong to #1752 from @justusth, merged in 2016-03-03).
At that time CodegenProperty.hasMore (like many more properties in this class) was a `Boolean` and using `null` was the way of doing it, it seems. #4326 (from 2016-12-07, from @sreeshas, merged 2016-12-09) changed that (and updated the placed it was set from null to false) – but it forgot updating CSharpClientCodegen.
Obviously there also were no tests where this line was covered (and there still are none).

**Suggestion**
It would be nice if we had a unit test which covers this whole reconcileInlineEnums method of CSharpClientCodegen. That one would obviously fail at the point where your pull request fixes it.
Alternatively, or additionally, one of the samples should have a case where this happens.

**Comment by Sodala** [comment]
I added a test that covers the method in question. In fact I copied a test that already existed for java and I adjusted it for csharp.

Note: I had small problems with the case where in csharp is case sensitive when adding models in the map of definitions and not in java. I do not know if it is normal to have a difference between the two tests except  the choice of the Codegen implementation

**Comment by wing328** [comment]
> Note: I had small problems with the case where in csharp is case sensitive when adding models in the map of definitions and not in java. I do not know if it is normal to have a difference between the two tests except the choice of the Codegen implementation

When you've time, please open a new issue with a sample spec to track it.

**Comment by wing328** [comment]
@Sodala thanks for the fix and the test cases.

**Pull request merged**
