### PR TITLE
Fix for Python client upload list of files Issue #2036

### PR DESCRIPTION
**Pull request by scottrw93**
Issue #2036 A fix to allow a list of files to be uploaded. The main change concerns the type of form_params being changed from a dict() to nested tuples in the form (key, (value)) to allow files with the same key not to be overwritten each iteration.

### CODE REVIEW

**Comment by wing328** [comment]
@scottrw93 thanks for the PR. We'll review and let you know if we've any questions.

Do you mind sharing the spec (with array of file as parameter) for repeating the issue?

Also I notice the commits are not linked to your Github account and therefore your contribution won't count toward https://github.com/swagger-api/swagger-codegen/graphs/contributors.

**Comment by scottrw93** [comment]
I never knew that's why my avatar is blank! The spec is available at https://github.com/scottrw93/swagger-python-test/blob/master/swagger.json. I also have a spring server and the before and after python client if you want to test in the same repo

**Comment by wing328** [comment]
@scottrw93 thanks for the spec. Will use it for testing this PR and other PRs that fix similar issue in other API clients (e.g. PHP, Ruby, etc)

**Comment by wing328** [comment]
You will need to fix your local git setting: `user.email`

Ref: http://alvinalexander.com/git/git-show-change-username-email-address

Then push again and Github should be able to link the commits correctly to your Github account.

**Comment by scottrw93** [comment]
Ok, I have  done that and the latest push is linked to my account. Thanks for your help, I'll bear it in mind for future PR's.

**Comment by wing328** [comment]
@scottrw93 in the "Commits" tab, I still see previous commits not linked to your account.

(I'm ok with that but just want to make sure you get the credits you deserved for your contribution/PR, which is reflected here: https://github.com/swagger-api/swagger-codegen/graphs/contributors)

One possible workaround is to close this PR and submit a new one.

**Comment by scottrw93** [comment]
Ok, I have created a new PR shown above. I think it might still be in the same situation but I'm happy for you to go ahead though and merge.

**Comment by wing328** [comment]
@scottrw93 I found this: https://help.github.com/articles/changing-author-info/

**Comment by scottrw93** [comment]
Thanks, I have done that.

**Comment by wing328** [comment]
It has a lot of commits so it seems to me it's not updated correctly.

I'll give it a try in my end.

**Comment by wing328** [comment]
I submitted https://github.com/swagger-api/swagger-codegen/pull/2060 with commits correctly linked to your Github account.

**Comment by scottrw93** [comment]
Thanks very much.

**Comment by wing328** [comment]
FYI. All test cases passed:
```
-----------------------------------------------------------------
TOTAL                                1338    528    61%   
----------------------------------------------------------------------
Ran 29 tests in 29.580s

OK
_____________________________________________________ summary ______________________________________________________
  py27: commands succeeded
  py34: commands succeeded
  congratulations :)
```

**Comment by wing328** [comment]
PR merged. Thanks again for the contribution.

**Pull request closed without merging**
