### PR TITLE
Android volley fix responses with additionalProperties and update sdk version

### PR DESCRIPTION
**Pull request by Shyri**
Hi
as @xhh  stated in #1775 there was an error with responses. I removed the `Responses.java` static class an replaced Response listener with base `Response.Listener<T>` from Volley library, I think is much cleaner, the intermediate class with a lot of interfaces is not necesary . Don't know why I didn't think about it earlier.

Also I updated to `compileSdkVersion 23` `buildToolsVersion '23.0.2'` and ` targetSdkVersion 23`

### CODE REVIEW

**Comment by fehguy** [comment]
Hi, please rebase with master.  The `.travis.yml` file needs to be updated for the PR to pass.

**Comment by Shyri** [comment]
@fehguy done! :)

**Comment by wing328** [comment]
@Shyri thanks for the PR. When you've time, I wonder if you can write some tests case for Petstore sample (android-volley) similar to https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/android/default/src/test/java/io/swagger/petstore/test.

**Comment by Shyri** [comment]
@wing328 Ook no problem. I'll write them when I have a moment. Should I send a new PR for that or force it into this one?

**Comment by wing328** [comment]
@Shyri just merged this PR. Please open a new one for the enhancement when you've time.

**Pull request merged**
