### PR TITLE
Adjust Date ISO Dateformat for Query Parameters: ISSUE 4745

### PR DESCRIPTION
**Pull request by gigo1980**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@gigo1980 thanks for the fix. For your upcoming PRs, I would recommend creating a branch for the change as per git best-practices.

**Comment by keradus** [comment]
this was fixed quite a long ago, but yet not released.
any chances for release ?

cc  @wing328

**Comment by wing328** [comment]
We now also publish a snapshot version of master (2.2.3) and 2.3.0 (branch with breaking changes): https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by keradus** [comment]
Sadly, I got
> no main manifest attribute, in swagger-codegen-2.2.3-20170703.101943-40.jar

**Comment by wing328** [comment]
@keradus can you try https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-codegen-cli/2.2.3-SNAPSHOT/swagger-codegen-cli-2.2.3-20170703.140356-40.jar instead ?

I'll update the links to swagger-codegen-cli instead of swagger-codegen

**Comment by keradus** [comment]
Thank you @wing328 , it's executing ;)

**Comment by wing328** [comment]
Good. I've updated the links to point to swagger-codegen-cli.

**Pull request merged**
