### PR TITLE
Fixed issue #4665 [go] required object parameters are marked omitempty.

### PR DESCRIPTION
**Pull request by vvalchev**
### Description of the PR

Details are included in the issue.

I tried to create a test, but it would take inadequate amount of time to understand how codegen works internally and how to deal with mustache. Sorry.

### CODE REVIEW

**Comment by wing328** [comment]
@vvalchev thanks for the PR and thinking about adding a test case.

I would suggest creating a file "pet_test.go" similar to https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/go/pet_api_test.go to test the Pet model. Let me know if you need any help.

**Comment by wing328** [comment]
@vvalchev also, please run `./bin/go-petstore.sh` to update the Petstore sample for Go API client so that the CIs can verify the change.

**Comment by vvalchev** [comment]
I've run the script and committed the changed files. But few of the changes are not because of the diff, I've applied. Still I was able to compile the generated client successfully.

Sorry for the test, probably somebody else can contribute one.

**Comment by wing328** [comment]
> Sorry for the test, probably somebody else can contribute one.

@vvalchev No problem at all.

**Comment by wing328** [comment]
@vvalchev the change looks good. Thanks for your contribution.

**Pull request merged**
