### PR TITLE
[go] Optimize model and api tmpl

### PR DESCRIPTION
**Pull request by wy-z**
- [api] Make the parameters optional
- [model] Use pointers whenever possible

Signed-off-by: weiyang weiyang.ones@gmail.com

### CODE REVIEW

**Comment by wy-z** [comment]
And there is a bug in `/bin/go-petstore.sh`
image

**Comment by NfNitLoop** [comment]
If I'm reading this right, (I'm not familiar w/ the codegen code base), it updates it so that function calls instead of being, ex: 

    GetFoo(int, string)

They're now:

    GetFoo(map[string]interface{})

So the type *and* number of the parameters is completely hidden from the call interface, and only checked at runtime.  (While #4308 only hides the type of parameters, but keeps their number and name as part of the generated code.)

**Comment by NfNitLoop** [comment]
Also, in https://github.com/swagger-api/swagger-codegen/pull/4306 it was pointed out that API-breaking changes need to go in a next `_.X._` semantic version release, (2.3.0), so I'd assume that applies here.

**Comment by wy-z** [comment]
They're now:
```
GetFoo(map[string]interface{}{
        "id": 6,
        "name: "foo",
})
```
~

**Comment by wing328** [comment]
Yes, this is a breaking change and it should file against `2.3.0` branch instead.

**Comment by wy-z** [comment]
ok~

**Pull request closed without merging**
