### PR TITLE
[JaxrsResteasy] Improvements for Resteasy for Jboss EAP 4512

### PR DESCRIPTION
**Pull request by jfiala**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

First draft adaption of the jaxrs-resteasy language, for details see #4512

I created a new language jaxrs-resteasy-eap so this change can make it into 2.2.2. 
With 2.3.0 this language could replace the existing jaxrs-resteasy.

The new samples are generated to samples/server/petstore/jaxrs-resteasy/eap and eap-joda to separate it from jaxrs-resteasy paths (default/joda-time).

The WAR file was verified to run on Jboss EAP 6 and 7.

This language supports Java8 and Joda datetime using the JacksonConfig, the needed dependencies included automatically (see pom.mustache).

I added the flag "joda" to AbstractJavaCodegen.java to allow checking for joda in the mustache templates.

I also added the option to generate the Swagger contract dynamically (useSwaggerFeature).

New test including the useSwaggerFeature: JavaResteasyEapServerOptionsTest.java

### CODE REVIEW

**Comment by jfiala** [comment]
Please let me know if I should also generate sample output for java8 datetime support (currently there are only sample outputs for joda).

**Comment by jfiala** [comment]
@wing328 Can we have this for 2.2.2? I provided a customer of mine with templates for this, but I would like to have this in the release.

**Comment by wing328** [comment]
@jfiala let me review first...

**Comment by wing328** [comment]
@jfiala I did some tests and merged the PR into master (2.2.2). Thanks for the contribution.

(I noticed some minor code alignment issue and will fix it later with https://github.com/swagger-api/swagger-codegen/pull/4859)

**Pull request merged**
