### PR TITLE
[Scala] format the Scala code style templete

### PR DESCRIPTION
**Pull request by shijinkui**
format the Scala code style templete, so that the generated Scala code meet the http://www.scalastyle.org

### CODE REVIEW

**Comment by wing328** [comment]
@shijinkui thanks for the PR. Please also run `./bin/scala-petstore.sh` to update the Scala Petstore client so that CIs can verify the change.

cc @clasnake

**Comment by wing328** [comment]
UPDATE: Tests with updated Scala samples passed via https://circleci.com/gh/swagger-api/swagger-codegen/1714

**Comment by wing328** [comment]
Tests passed via https://circleci.com/gh/swagger-api/swagger-codegen/1829

@clasnake any more feedback on this PR? If no, I'll merge it this coming Saturday.

**Comment by clasnake** [comment]
@wing328 Happy. Please merge. 
@shijinkui Thank you for the contribution.

**Comment by wing328** [comment]
@shijinkui thanks for the PR, which has been merged into master.

**Pull request merged**
