### PR TITLE
support latest Retrofit 2 v2.0.0-beta4

### PR DESCRIPTION
**Pull request by dhontecillas**
Retrofit v2.0.0-beta4 introduces some package changes from beta3, that should be reflected in moustache templates.

### CODE REVIEW

**Comment by wing328** [comment]
@dhontecillas thanks for the PR. Please update retrofit2 petstore sample so that CI can verify the change.

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md#testing

**Comment by DerPate** [comment]
Maybe you also push the okhttp version to okhttp3 because the beta4 for retrofit pushes this also to the same version and at least introduced some bugs at my instaltion

**Comment by wing328** [comment]
Btw, one of your commits (in the `Commits` tab) is not linked to your account, which means that commit won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors

**Comment by cbornet** [comment]
I thnik the okhttp3 dependency should be removed since it is already included in retrofit2

**Comment by wing328** [comment]
@dhontecillas may I know if you're updating the PR with the feedback from @cbornet and @DerPate? Let us know if you need any help.

**Comment by dhontecillas** [comment]
I'm sorry, I'm crunching for a release that I have the Feb 24th, so I don't expect to fix the pull request until the end of this week. If that is no problem, I will update it.

**Comment by wing328** [comment]
Thanks for the update. Please take your time :)

**Comment by dhontecillas** [comment]
I've updated the tests for retrofit2 librare, as suggested commented. Can you check everything is ok ?

**Comment by wing328** [comment]
@dhontecillas I did some tests and found some minor issues:

1) When I ran `gradle check` under `samples/client/petstore/java/retrofit2`, I got the following error:
```
/private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java:15: error: package retrofit2.converter.gson does not exist
import retrofit2.converter.gson.GsonConverterFactory;
                               ^
/private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java:324: error: cannot find symbol
	  private final GsonConverterFactory gsonConverterFactory;
	                ^
  symbol:   class GsonConverterFactory
  location: class GsonCustomConverterFactory
/private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java:329: error: cannot find symbol
	    this.gsonConverterFactory = GsonConverterFactory.create(gson);
	                                ^
```
I believe you need to update build.gradle (mustache) as well.

2) I ran `./bin/java-petstore-retrofit2rx.sh` and got the following error when running `mvn test` under `samples/client/petstore/java/retrofit2rx`
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swagger-petstore-retrofit2-rx: Compilation failure: Compilation failure:
[ERROR] /private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java:[15,31] error: package retrofit2.converter.gson does not exist
[ERROR] /private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java:[324,17] error: cannot find symbol
[ERROR] class GsonCustomConverterFactory
[ERROR] /private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java:[329,33] error: cannot find symbol
[ERROR] class GsonCustomConverterFactory
[ERROR] /private/var/tmp/pr/dhontecillas/swagger-codegen/samples/client/petstore/java/retrofit2rx/src/main/java/io/swagger/client/ApiClient.java:[340,4] error: method does not override or implement a method from a supertype
```

**Comment by dhontecillas** [comment]
I fixed the templates but I still have to check the gradle build.

**Comment by dhontecillas** [comment]
I think that now it should be ok and ready to merge.

**Comment by wing328** [comment]
@dhontecillas tested again and no longer encountered those issues. Thanks again for the PR.

**Comment by dhontecillas** [comment]
You are welcome. Thanks for the patience with the not so well done PR :)

**Comment by wing328** [comment]
Given that it's your first PR to swagger-codegen, it definitely looks good. I hope by now you feel more comfortable making changes to swagger-codegen.

If you're interested in making more enhancements to the Java API client, please refer to https://github.com/swagger-api/swagger-codegen/issues?q=is%3Aopen+label%3A%22Need+community+contribution%22+label%3A%22Client%3A+Java%22

**Pull request merged**
