### PR TITLE
[PHP] Add more flexible object serializer

### PR DESCRIPTION
**Pull request by corleonis**
### PR checklist

- [ ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@corleonis thanks for the PR. It looks to me it's a breaking change so it should be filed against 2.3.0 if I'm not mistaken.

cc @baartosz @dkarlovi @arnested

**Comment by dkarlovi** [comment]
@corleonis could you supply description of the PR? It would make it much easier to read knowing exactly where it's headed.

**Comment by corleonis** [comment]
Sorry for the sparse description. It was a bit rushed but will make sure it's fully and probably it'd be better if it's against the 2.2.3 branch as it might break some clients. Hope I'll have some free time in next two days to cleanup and document it.

**Comment by wing328** [comment]
Given that it might break some clients, please file against 2.3.0 instead.

**Comment by wing328** [comment]
@corleonis thanks again for the PR. Please rebase on the latest master to resolve the merge conflicts and provide more description for the PR. Closing this for the time being.

**Pull request closed without merging**
