### PR TITLE
issue #1875 fixing -Dapis= work for -l html, provding test.

### PR DESCRIPTION
**Pull request by mkhludnev**
here we go. I checked generated files with -Dapis= -DsupportingFiles= manually. I also checked that StaticHtmlTagsTest.java test is representative, eg. if you put  StaticDocCodegen as a mock it pass well. Note, I don't use mock library, but miss randomized test library.

Nevertheless, let me know if I can improve it. Thanks!

### CODE REVIEW

**Comment by wing328** [comment]
@mkhludnev thanks for the PR. 

The CI tests failed. Please run `mvn verify -Psamples` locally to find out more about the errors.

**Comment by mkhludnev** [comment]
screen shot 2016-02-25 at 22 36 00
It doesn't sound as an excuse, but it passed locally. Lurking into it ...

**Comment by mkhludnev** [comment]
hmmm my test and the failed one both use JUnit's rule 
`folder = new TemporaryFolder();` 
And only those two.
Can't one interfere with another somehow? I'm trying to reproduce it with travis too.

**Comment by wing328** [comment]
I'll take another look at the CI test and try to repeat the error locally...

**Comment by mkhludnev** [comment]
@wing328, hold on. I understood after all. My new test didn't clear -Dapis= I'll fix it.

**Comment by mkhludnev** [comment]
ok I went further a little: codegen (core lib) passed!
https://travis-ci.org/mkhludnev/swagger-codegen/jobs/111952755
now it breaks android tests..whazzup

**Comment by mkhludnev** [comment]
at my laptop 

> Concurrency config is parallel='methods', perCoreThreadCount=true, threadCount=2,  useUnlimitedThreads=false
> Running io.swagger.petstore.test.UserApiTest
> Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 26.818 sec

by travis

> Concurrency config is parallel='methods', perCoreThreadCount=true, threadCount=2, useUnlimitedThreads=false
> Running io.swagger.petstore.test.UserApiTest
> Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.035 sec <<< FAILURE!
> ...
> Failed tests:   testCreateUsersWithList(io.swagger.petstore.test.UserApiTest): expected:<1456475884413> but was:<1456475884461>

can it somehow related to threads?

**Comment by wing328** [comment]
I restarted the failed CI job. Let's see how it goes...

**Comment by mkhludnev** [comment]
nono, I didn't pushed last test fix.

On Fri, Feb 26, 2016 at 3:03 PM, wing328 <notifications@github.com> wrote:

> I restarted the failed CI job. Let's see how it goes...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-codegen/pull/2234#issuecomment-189246650>
> .
>



-- 
Sincerely yours
Mikhail Khludnev
Principal Engineer,
Grid Dynamics

<http://www.griddynamics.com>
<mkhludnev@griddynamics.com>

**Comment by wing328** [comment]
Now all the test cases pass

**Comment by wing328** [comment]
@mkhludnev when you've time, can you please update the Petstore sample as well (mentioned in https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md) ?

**Comment by mkhludnev** [comment]
@wing328  sure, but I don't clearly understand what's need to be done.
Nevertheless, I run /bin/html-petstore.sh and put its' result into the separate branch for a while https://github.com/mkhludnev/swagger-codegen/blob/doc-change/samples/html/index.html

At first, is uploading regenerated doc what you expect from me? or you ask me to create /bin/html-petstore-user-api-only.sh exploring -Dapis feature?

Anyway, I compare it to master's version, it's pretty the same, but operation order it different, I don't think it's a problem, but it's worth to clarify. 
Here are the more significant change, new html has two "new" operations:

get /pet/{petId}?testing_byte_array=true
post /pet?testing_byte_array=true

is it a bug or a feature? Let me know, and I explore.

**Comment by wing328** [comment]
@mkhludnev sorry for the delay. I'll review and approve by tomorrow.

**Comment by mkhludnev** [comment]
fwiw, I checked bin/dynamic-html.sh. It generates docs for these ops too i.e. it works like changed "-l html", although the operation names are not nice looking see the pic:
screen shot 2016-03-06 at 23 06 56

**Pull request merged**
