### PR TITLE
[PHP] Fix 'multi' query string serialization and array json serialization

### LINKED ISSUE #2212: Serialize collection multi PHP problem
Hi,

I have a big problem with my function parameters.
My Api is waiting for filters like this:

> ?filters[id][]=1&filters[id][]=2&filters[name]=Me

Or even

> ?filters[name][]=Me&filters[name][]=You&filters[date][before]=2012-01-01

However, in the generated code:

``` php
if (is_array($filters)) {
    $filters = $this->apiClient->getSerializer()->serializeCollection($filters, 'multi', true);
}

if ($filters !== null) {
    $queryParams['filters'] = $this->apiClient->getSerializer()->toQueryValue($filters);
}// query params
```

So i get a stupid ?filters=id=1&id=2&name=Me

The behavior should have be:

``` php
if (is_array($filters)) {
    $filters = $this->apiClient->getSerializer()->serializeCollection(['filters' => $filters], 'multi', true);
}
```

And in the serializeCollection method:

``` php
if ($allowCollectionFormatMulti && ('multi' === $collectionFormat)) {
    return http_build_query($collection, '', '&');
}
```

Because for the moment it's blowing everything up:

`preg_replace('/%5B[0-9]+%5D=/', '=', http_build_query($collection, '', '&'));`

I can't use the codegen like that, and it's not me that have to adapt my API behavior...

### PR DESCRIPTION
**Pull request by christiaanderidder**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/php-petstore.sh` and `./bin/security/php-petstore.sh` if updating the php (e.g. php, ruby, python, etc) code generator or php client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@jebentier (2017/07) @dkarlovi (2017/07) @mandrean (2017/08) @jfastnacht (2017/09) @ackintosh (2017/09)

### Description of the PR

- Fixes #2212 ('multi' collections in query string parameters)
- Allows arrays to be serialized to json when used as the request body

### CODE REVIEW

**Comment by christiaanderidder** [comment]
I'm not sure why all builds succeed except for the circle-ci one, which seems to fail on something unrelated to the changes I made to the PHP templates. Would someone be able to clarify?

**Comment by ackintosh** [comment]
The failing tests have nothing to do with your PR 👀

**Comment by ackintosh** [comment]
@christiaanderidder Could you please show me the API definition which reproduces the problem fixed by this PR?

**Comment by christiaanderidder** [comment]
@ackintosh Sorry for the late reply. The API definition can be found [here](https://demo.channelengine.net/api/swagger/docs/merchant)

The issues that this PR resolves are:
1. A call that expects json in the following format `[{"test":"1"},{"test":"2"}]` like `Product_Create`
2. A call that expects a querystring parameter of type `multi` like `Order_GetByFilter`

**Comment by ossinkine** [comment]
This fix works for me :+1:

**Comment by FireLizard** [comment]
How can we get the PR done?

**Comment by ackintosh** [comment]
Sorry that now I'm not active on this project.

I would appreciate if anyone in Technical Committee could review this PR.
https://github.com/swagger-api/swagger-codegen#members-of-technical-committee

**Comment by HugoMario** [comment]
thanks a lot for PR!! ping me anytime you guys need help to merge your changes.

**Pull request merged**
