### PR TITLE
[Swift] Fix pod authors in podspec

### PR DESCRIPTION
**Pull request by jgavris**

### CODE REVIEW

**Comment by jaz-ah** [comment]
+1

**Comment by jgavris** [comment]
https://github.com/swagger-api/swagger-codegen/pull/3378

**Comment by wing328** [comment]
@jgavris thanks for the fix. 

To do a bit of "growth hacking" for Swagger Codegen. What about defaulting to "Swagger Codegen" if not pod spec author is *not* provided?

**Comment by jgavris** [comment]
@wing328 👍

**Pull request merged**
