### PR TITLE
Add a new JAX-RS server generator - jaxrs-cxf-cdi

### PR DESCRIPTION
**Pull request by nickcmaynard**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Generate a JAX-RS server that assumes an Apache CXF framework on a Java EE server supporting CDI.

Similar to the original JAXRS generator, this creates API and Service classes in /src/gen/java and a sample ServiceImpl in /src/main/java. The API uses CDI to get an instance of ServiceImpl that implements the Service interface.

### CODE REVIEW

**Comment by nickcmaynard** [comment]
... this one should do the "right thing" with the PR template.

**Comment by nickcmaynard** [comment]
Happy to update the wiki (if possible) once merged.

**Comment by wing328** [comment]
@nickcmaynard thanks for the PR. I'll review this weekend and let you know if I've any question.

**Comment by wing328** [comment]
@nickcmaynard it looks good. Later I'll file a PR to change the indentation from tab to 4-space for JavaJAXRSCXFCDIServerCodegen as well as JavaJAXRSSpecServerCodegen.

**Comment by wing328** [comment]
@nickcmaynard I've updated the documentation here: https://github.com/swagger-api/swagger-codegen/wiki/Server-stub-generator-HOWTO#java-jax-rs-apache-cxf-framework-on-java-ee-server-supporting-cdi

It would be nice if the generator can create a pom.xml and README.md explaining a bit about the auto-generated code.

**Comment by nickcmaynard** [comment]
Great news thank you. I'll look into a pom.xml and README in a separate PR.

**Comment by wing328** [comment]
Tweet: https://twitter.com/wing328/status/787670177785585664

To all, please help retweet to promote the new generator. Thank you.

**Pull request merged**
