### PR TITLE
[C#] fix path with {{{ .. }}} in c# API mustache file

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

To fix https://github.com/swagger-api/swagger-codegen/issues/4977

### CODE REVIEW

**Comment by muralidharalladi** [comment]
when this code changes will reflect in online codegen "https://generator.swagger.io"

**Comment by wing328** [comment]
https://generator.swagger.io is using the latest "stable" version.

Please consider building the JAR locally based on the latest master or using docker: https://github.com/swagger-api/swagger-codegen#public-pre-built-docker-images

For usage on `swagger-codegen-cli`, you can reference the instruction in https://hub.docker.com/r/jimschubert/swagger-codegen-cli/ (unofficial build)

**Comment by muralidharalladi** [comment]
Thank you.

**Comment by muralidharalladi** [comment]
I have tested by taking latest master, working fine.
Thank you.

**Pull request merged**
