### PR TITLE
fixes progress for file upload with alamofire / swift3

### PR DESCRIPTION
**Pull request by Daxten**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
the progress property is wrong here, since it holds download information and this case is for upload

### CODE REVIEW

**Comment by Daxten** [comment]
could someone else pls run the ./bin/swift3-petstore.sh since I'm on a windows machine?

**Comment by wing328** [comment]
@Daxten sure, and we'll add a corresponding batch file under `.\bin\windows`

**Comment by wing328** [comment]
@Daxten batch files added via https://github.com/swagger-api/swagger-codegen/pull/4934. PR merged into master.

cc @Edubits @jaz-ah @jgavris @hexelon

**Comment by jgavris** [comment]
👍  Thanks! If you wanted to follow up with a test, you could augment https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/swift3/default/SwaggerClientTests/SwaggerClientTests/StoreAPITests.swift#L93

**Pull request merged**
