### PR TITLE
[Java] To fix missing import for @JsonValue

### LINKED ISSUE #2668: Swagger-codegen 2.1.6 fails to compile with @JsonValue
@fehguy 

Starting with swagger-codegen 2.1.6, java code fails to compile when an @JsonValue annotation is added to enum toString() with no corresponding import statement. Workaround is to use swagger-codegen 2.1.5. 

```
java -jar modules\swagger-codegen-cli\target\swagger-codegen-cli.jar generate -i C:\swagger.yaml -l java -o output
```

```
swagger: '2.0'
paths:
  /topn_search:
    post:    
definitions:
  Statistic:
    properties:
      data_tags:
        type: array
        items:
          type: string 
          enum: [upper_critical, upper_warning, typical, lower_warning, lower_critical, status]
```
Generates...

```
  public enum DataTagsEnum {
    UPPER_CRITICAL("upper_critical"),
    UPPER_WARNING("upper_warning"),
    TYPICAL("typical"),
    LOWER_WARNING("lower_warning"),
    LOWER_CRITICAL("lower_critical"),
    STATUS("status");

    private String value;

    DataTagsEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return value;
    }
  }
```

### PR DESCRIPTION
**Pull request by wing328**
To fix #2668

### CODE REVIEW

**Comment by smileyogurt** [comment]
@wing328 

I still had the same problem. I used swagger-codegen-maven-plugin 2.1.6, compile java client failed with this error.

**Comment by ePaul** [comment]
This pull-request looks like empty (just three merge-commits)?

**Comment by wing328** [comment]
Should be fixed via this one instead: https://github.com/swagger-api/swagger-codegen/pull/2806

@smileyogurt you will need to pull the latest master to obtain the fix.

**Comment by smileyogurt** [comment]
@wing328 But I am using plugin, not cli. Should I wait for plugin version 2.2.0 available?

**Comment by smileyogurt** [comment]
@wing328 I will build local 2.2.0-SNAPSHOT then. Thanks!

**Pull request merged**
