### PR TITLE
Add support to Retrofit2

### PR DESCRIPTION
**Pull request by emilianobonassi**
Related to #1522

### CODE REVIEW

**Comment by wing328** [comment]
@emilianobonassi thanks for the PR.

I got the following error when running `mvn test` under `samples/client/petstore/java/retrofit2`

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /private/var/tmp/pr/emilianobonassi/swagger-codegen/samples/client/petstore/java/retrofit2/src/main/java/io/swagger/client/ApiClient.java:[332,50] error: diamond operator is not supported in -source 1.6
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```
Please take a look.

Also, please update pom.xml to add another profile for retrofit2 for triggering the CI test for retrofit2 (petstore): https://github.com/swagger-api/swagger-codegen/blob/master/pom.xml#L345

**Comment by emilianobonassi** [comment]
Thanks @wing328 . 
I had upgraded source level to 1.7 because usually I code at that level, now it's back to 1.6 .
We will see how integration test will go.

**Comment by wing328** [comment]
Tests for Retrofit2 passed.

**Comment by emilianobonassi** [comment]
@cbornet and @wing328  , I'm sorry, the next time I will dedicate more attention to that kind of files.

**Comment by wing328** [comment]
@emilianobonassi no worry. I've submitted #1559 to remove the file.

**Pull request merged**
