### PR TITLE
Improved support for XML wrapped items

### PR DESCRIPTION
**Pull request by mobreza**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

As described in https://github.com/swagger-api/swagger-codegen/issues/5918 the codegen does not take Swagger's "xml" declarations into consideration. Trouble is in the `PropertyDeserializer` class (see https://github.com/swagger-api/swagger-core/issues/2316 and PR https://github.com/swagger-api/swagger-core/pull/2313).

Once issue https://github.com/swagger-api/swagger-core/issues/2316 is resolved this PR will generate "wrapped XML" arrays as described in https://github.com/swagger-api/swagger-codegen/issues/5918.

### CODE REVIEW

**Comment by mobreza** [comment]
Note @wing328: shell scripts under ./bin/ to update Petstore create a whole bunch of changes.

**Comment by wing328** [comment]
@mobreza thanks for the PR. Please use 4-space instead of tab for code indentation.

**Comment by mobreza** [comment]
@wing328 Sure. Checking what's new in 2.3.0-SNAPSHOT, my generated code fails to compile.

**Comment by mobreza** [comment]
@wing328 Everything still works fine, only needed to set `java8` for my example.

**Comment by wing328** [comment]
Tests passed via https://circleci.com/gh/swagger-api/swagger-codegen/1173

**Comment by jigarshah** [comment]
@mobreza I am bit confused. Is "wrapped XML" issue fixed ? this one says merged but other dependent issues are yet to be cloased ? 

I am on 2.3.1 and still 
        xml:
          wrapped: true
is ignored. And generated JSON too just removes it.

**Comment by mobreza** [comment]
@jigarshah The original PR identified a problem in swagger-core and that remains open. I guess they're busy with version 3...

> Once issue swagger-api/swagger-core#2316 is resolved this PR will generate "wrapped XML" arrays as described in #5918.

**Pull request merged**
