### PR TITLE
fix InjectionToken in typescript angular2 client also fix configuration.ts to compile in strict mode (second commit)

### PR DESCRIPTION
**Pull request by topce**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by topce** [comment]
push to proper branch 2.3.0

**Comment by sebastianhaas** [comment]
I guess this is a duplicate of #5866

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/5866

**Comment by topce** [comment]
@sebastianhaas , @wing328 
This is relativly better solution then original #5866
because it generates better code 
More Type info: InjectionToken<string>`. 
Please see https://angular.io/api/core/InjectionToken

**Pull request closed without merging**
