### PR TITLE
 [PHP][Symfony] Enhancements

### PR DESCRIPTION
**Pull request by naelrashdeen**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

The current PHP Symfony server codegen is heavily based on the vanilla PHP codegen and does not really utilize the stuff Symfony brings to the table. This PR adds the following features:

* Proper deserialization of arrays in query, header, formData and path parameters
* Adds a serialization and validation interface to make those components pluggable
* Adds default serialization using JMS serializer
* Adds default validation using the Symfony validation component
* Complete input validation that covers all cases
* Adds support for content negotiation through the Accept and Content-Type headers
* Adds support for response headers and response codes produced by the business logic
* Improve the way dependencies for the generated code is supported through composer
* Adds support for testing generated code to make sure it compiles

What is still missing:

* Add an interface for authentication handling. Authentication processing should be done in a central service in the business logic
* Make sure that the generated code always returns data that is compatible with what the client accepts (sometimes HTML formatted error messages are returned)

Please note that this PR includes the changes from PR #6578 as it builds on top of these.

### CODE REVIEW

**Comment by naelrashdeen** [comment]
@jebentier @dkarlovi @mandrean @jfastnacht @ackintosh

**Comment by ackintosh** [comment]
Thank you for your contribution!

- It looks good to me. But, I'm not familiar with Symfony. So I'd like to request a reviewing to other commitee member. 🙏 💦 
- It would be appreciated if you would keeping your commit as small as you can next time. 💡 
  - As if people who seeing commits feel like playing pair programming.

**Comment by wing328** [comment]
@naelrashdeen when you've time, can you rebase this PR on the latest master to resolve the merge conflicts?

@ackintosh thanks for reviewing the change.

**Comment by naelrashdeen** [comment]
@wing328 As requested, i have rebased this PR on the latest master.

**Comment by wing328** [comment]
@naelrashdeen thanks. Quick question: For PHP Symfony, is there anyway to quickly test the code to make sure it compiles? 

Currently, the PHP Petstore client is using `phpunit` (vendor/bin/phpunit) for testing. I wonder if we can add something similar for PHP Symfony Petstore samples.

**Comment by wing328** [comment]
If no more feedback on this PR, I'll merge it into master on coming Wednesday.

cc @jebentier @dkarlovi @mandrean @jfastnacht @ackintosh @ksm2

**Comment by naelrashdeen** [comment]
@wing328 The generated code can now be tested to make sure it works and compiles. I have updated the description of this PR as well.

**Pull request merged**
