### PR TITLE
#9808 - Dart double cast

### LINKED ISSUE #9808: [Dart] Number decoded to int causes an exception when assigning to double
##### Description

Suppose you have an API Model containing a double property, swagger-codegen will generate a class similar to this:

```dart
class ApiResponse {
  double ttl = null;
  
  LoginResponse.fromJson(Map<String, dynamic> json) {
    if (json == null) return;

    ttl =
        json['ttl']
    ;
  }
}
```
This works fine, as long as the JSON returned from the API includes a decimal place, for example:

```json
{
  "ttl": 21.1
}
```

However, If the API returns a value that contains no decimal place, Dart's `JsonCodec` will parse this as an `int`. The Model's `fromJson` method will then throw an exception, as an `int` cannot be assigned to a `double`.

An API returning the following:

```json
{
  "ttl": 21
}
```

Will be parsed by `JsonCodec` an int, and will then throw the following exception when attempting to assign it to `ApiModel.ttl`:

```
_TypeError (type 'int' is not a subtype of type 'double')
```

##### Swagger-codegen version

2.48 (compiled from 31e7ea9248ef35917ba3659150031d576fc7c554)

##### Swagger declaration file content or url

N/A

##### Command line used for generation

N/A

##### Steps to reproduce

N/A

##### Related issues/PRs

N/A

##### Suggest a fix/enhancement

To assign to a double, the value parsed from the json should be explicitly cast to a double before assigning. This works as all Dart's number types have a `toDouble` method.

### PR DESCRIPTION
**Pull request by MichaelMarner**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR resolves #9808 by explicitly casting double properties from JSON payloads before assignment. This works around dart's JsonCodec parsing numbers that look like ints to `int`, which cannot then be assigned directly to a `double`.

This PR takes advantage of the fact all Dart's number types have a [`toDouble`](https://api.flutter.dev/flutter/dart-core/num-class.html) method. As long as the JSON payload contains a number, calling `toDouble` is safe. 

@ircecho

### CODE REVIEW

**Comment by MichaelMarner** [comment]
Have added a check for null before parsing `toDouble` to prevent exception being thrown in the case where the data is not present in the json payload.

**Comment by MichaelMarner** [comment]
Hey just wondering the likelihood of this PR being merged, or if there's anything further I can do to get it merged?

**Comment by skordesign** [comment]
@MichaelMarner I saw The Travis CI build failed, have you try to solve it?

**Comment by MichaelMarner** [comment]
@skordesign sync'd with master, which made Travis pass. Thanks

**Comment by skordesign** [comment]
Any update? Still open?

**Comment by sm2017** [comment]
Why no one accept the PR?

**Pull request merged**
