### PR TITLE
updated Spring, Boot, Fox and Cloud dependencies

### PR DESCRIPTION
**Pull request by deki**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

updated Spring, Boot, Fox and Cloud dependencies, may not be fully backward compatible that's why I decided to do it in 2.3.0 branch.

Please note that the samples in 2.3.0 branch are currently not up to date. while running the scripts I saw many other unrelated changes.

### CODE REVIEW

**Comment by wing328** [comment]
@deki can you also commit the updated samples so as to see if the integration tests pass?

**Comment by wing328** [comment]
@deki thanks for updating the Petstore samples. I'll review the change and CI results tomorrow.

**Comment by wing328** [comment]
I got the following errors for `spring-boot` (samples/client/petstore/spring-cloud/):
```
Results :

Tests in error: 
  PetApiTest.testCreateAndGetPet:34 » Decode Could not read JSON document: Can n...
  PetApiTest.testDeletePet:124 » Decode Could not read JSON document: Can not co...
  PetApiTest.testUpdatePet:47 » Decode Could not read JSON document: Can not con...
  PetApiTest.testUpdatePetWithForm:111 » Decode Could not read JSON document: Ca...
  StoreApiTest.testDeleteOrder:47 » Decode Could not read JSON document: Can not...
  StoreApiTest.testGetInventory:28 » Decode Could not read JSON document: Can no...
  StoreApiTest.testPlaceOrder:35 » Decode Could not read JSON document: Can not ...
  UserApiTest.logoutUser:71 NullPointer
  UserApiTest.testCreateUser:28 NullPointer
  UserApiTest.testCreateUsersWithArray:41 NullPointer
  UserApiTest.testCreateUsersWithList:54 NullPointer
  UserApiTest.testLoginUser:63 NullPointer

Tests run: 16, Failures: 0, Errors: 12, Skipped: 3
```

Rolling back the following change in samples/client/petstore/spring-cloud/pom.xml fixes the issue:
```
-                <version>Camden.SR1</version>
+                <version>Dalston.SR1</version>
``` 

I've fixed it via https://github.com/swagger-api/swagger-codegen/pull/5969

**Comment by deki** [comment]
Sorry for that, feign.hystrix.enabled=true was missing in application.yml for spring-cloud. I'll file another PR for it.

**Comment by wing328** [comment]
No problem and we appreciate your help in this project.

**Pull request closed without merging**
