### PR TITLE
Fix spring generated annotations only generating first return type

### PR DESCRIPTION
**Pull request by JLLeitschuh**
Fixes the spring java code generator so that the ApiResponse fields are populated correctly
on the controller.

Related to #4693

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

This yaml:
```yaml
      responses:
        '200':
          description: pet response
          schema:
            type: array
            items:
              $ref: '#/definitions/pet'
        '400':
          description: unexpected error
          schema:
            $ref: '#/definitions/errorModel'
```
Will now generate this java:
```java
@ApiOperation(value = "", notes = "Returns all pets from the system that the user has access to", response = Pet.class, responseContainer = "List", tags={  })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "pet response", response = Pet.class),
        @ApiResponse(code = 400, message = "unexpected error", response = ErrorModel.class) }) // This is the line that changed
    @RequestMapping(value = "/pets",
        produces = { "application/json", "application/xml", "text/xml", "text/html" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
```

### CODE REVIEW

**Comment by JLLeitschuh** [comment]
Do you need me to fix the merge conflicts?

**Comment by wing328** [comment]
@JLLeitschuh no worry. I'll resolve it when merging the PR.

**Comment by wing328** [comment]
@JLLeitschuh sorry can you help rebase on the latest master to resolve the merge conflicts?

**Comment by baynezy** [comment]
@wing328 is this held up because you are waiting for @JLLeitschuh to fix the merge conflicts? I assume not as there do not seem to be any. 

Is it the Travis CI failure? If that is the case, on reading the logs it looks like NPM timed out, so worth re-running it to see.

Is there anything I can do yo help move this along?

**Comment by wing328** [comment]
@baynezy there were merge conflicts but after we rolled back a change to spring generator in the master, the merge conflicts are gone.

The Travis CI issue (due to NPM timed out) can be ignored.

I've just merged this PR into master. Please pull the latest master to give it a try.

**Comment by radarsh** [comment]
Will this PR also fix the return type? If it still generates a return type of `ResponseEntity<Pet>` in the example quoted above, it would lead to Java type safety warnings.

**Comment by wing328** [comment]
@radarsh I would suggest you to pull the latest master to give it a try.

If you still see the type safety warnings, please open a new issue for tracking (assuming no similar issue has been opened)

**Pull request merged**
