### PR TITLE
[Akka-scala] Clean unused dependencies such swagger-core

### PR DESCRIPTION
**Pull request by shijinkui**
Clean unused dependencies such swagger-core

generate petstore by akka-scala.

### CODE REVIEW

**Comment by wing328** [comment]
@shijinkui thanks for cleaning up the dependencies.

cc @clasnake  @jimschubert @shijinkui

**Comment by jimschubert** [comment]
Change looks fine.

Removal of Joda converters is a potential breaking change for anyone who has modified ApiInvoker and excluded those changes from generation. It may also affect users passing mappings via command line. We should probably note that in release notes, but this is preferable to including generally unused artifacts. Similarly, users could add the artifact back to the desired build script, and exclude the change in .swagger-codegen-ignore if the artifact is indeed needed.

**Comment by shijinkui** [comment]
@wing328 there is a continuous-integration, it didn't merged in. Please show me the stack, let me check whether is the code fault.

**Comment by shijinkui** [comment]
ping @wing328 resolved break changed.

**Pull request merged**
