### PR TITLE
Allow overriding of only some templates when using --template-dir option

### PR DESCRIPTION
**Pull request by sfurholm**
Allow overriding of only some templates when using --template-dir option. Templates which aren't found in the template directory will fall back to the ones packaged/distributed with Swagger. This PR replaces a previous PR, which wasn't working in all scenarios.

### CODE REVIEW

**Comment by fehguy** [comment]
@wing328 this would be a good feature to have, can you please review?

**Comment by wing328** [comment]
@fehguy sure. I'll spend sometime tonight to test.

**Comment by xhh** [comment]
@sfurholm I tested it with Java client and found that there'd be an exception when using a custom template dir without the file `generatedAnnotation.mustache`.
I've have it fixed in [this commit](https://github.com/xhh/swagger-codegen/commit/ce06700d90cb6d4e39caa85bd2ba455bf04ba445). You can pull and merge the changes from [my branch](https://github.com/xhh/swagger-codegen/commit/ce06700d90cb6d4e39caa85bd2ba455bf04ba445) if you'd like to.

**Comment by sfurholm** [comment]
@xhh Thanks! I've cherry-picked your commit and pushed...

**Comment by wing328** [comment]
@sfurholm would you please take a look at the merge conflicts when you've time?

**Comment by sfurholm** [comment]
@wing328 Thanks for notifying me, I hadn't had time to check after I pushed the patch. Merge conflicts have now been fixed and build has passed...

**Pull request merged**
