### PR TITLE
[Spring] Fixed a couple of issues with path/query parameters not picking up the correct names.

### PR DESCRIPTION
**Pull request by stevecookform3**
### Description of the PR

Fix to: https://github.com/swagger-api/swagger-codegen/issues/4460

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @epaul as this also fixes the issue using {{baseName}}

**Comment by ePaul** [comment]
Yeah, looks like the same change I made in #4875. So this is now a no-op (can be merged, but doesn't change anything).
@stevecookform3 Sorry that I preempted you here ... you made your commit first, but I made the PR first, not having seen your issue #4460.

(The example with the square brackets is a good one.)

**Comment by wing328** [comment]
@ePaul I think what I'll do it to merge @stevecookform3 PR first and then merge yours so that some credits go to @stevecookform3 as well.

**Comment by wing328** [comment]
@stevecookform3 thanks for your contribution. For your upcoming PRs, please do the following:
1) create a new branch instead of using master as per git best practice
2) update the Petstore sample (e.g. for this PR, please run `./bin/java-petstore-okhttp-gson.sh`

For more info, please refer to https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md

**Comment by ePaul** [comment]
@wing328 my one was already merged before, so now you have a no-change commit in master. (Not a problem, though.)

**Comment by wing328** [comment]
@ePaul right. Just realize that :sweat_smile:

**Pull request merged**
