### PR TITLE
[Java] Run ./bin/java-petstore-all.sh

### PR DESCRIPTION
**Pull request by tobymurray**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
The PR checklist currently states the scripts in .bin should be run before PR. Running `./bin/java-petstore-all.sh` on the head of master presently shows these changes.

Not sure what this means, but as it stands these changes could inappropriately be attributed to new work.

CC: @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov  @cbornet  @jeff9finger

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by tobymurray** [comment]
@wing328 - I've added the email to my account, if it doesn't count as a contribution I'm not too concerned.

**Comment by tobymurray** [comment]
Hey team - do you have any guidance about what to do regarding things like this? It looks like the current state of the project is such that these things are not up to date - changes are getting in that manifest in the output of the scripts without those changes being committed. How do I contribute if trying to follow the PR checklist brings in changes unrelated to the changes I want to make?

**Comment by tobymurray** [comment]
@HugoMario - no stress. There is not an associated ticket. I can make one that clarifies exactly what's happening (and what prompted this PR) if that makes it easier to track?

**Comment by HugoMario** [comment]
@tobymurray
that would be helpful, thanks!

**Comment by tobymurray** [comment]
It looks like this was kind of addressed 2 years ago when a disclaimer was added to the contribution guide:

> (If you find that there are new files generated or unexpected changes as a result of the update, that's not unusual as the test cases are added to the OpenAPI/Swagger spec from time to time. If you've questions or concerns, please open a ticket to start a discussion

**Comment by HugoMario** [comment]
sorry for delay @tobymurray , so you think we can close this?

**Comment by tobymurray** [comment]
I think the problem still exists, but it seems like it's somewhat ingrained in the process. I'm no longer invested, so feel free to close.

**Pull request closed without merging**
