### PR TITLE
Fixed bug that prevented Objective-C code from compiling when using a Sw...

### PR DESCRIPTION
**Pull request by geoand**
...agger 'map' type

As requested in PR #456, I am resubmitting the PR against branch `develop_2.0`

### CODE REVIEW

**Comment by fehguy** [comment]
As this is giving a merge error I have to hold on accepting this for the time being.

**Comment by geoand** [comment]
Do you want me to take some action to help out?

**Comment by fehguy** [comment]
Yes can you update so the pr can merge?

**Comment by geoand** [comment]
Sure, I will do that as soon as possible.

**Comment by geoand** [comment]
Should be ok now :)

**Pull request merged**
