### PR TITLE
[Swift] fix multi thread issue

### PR DESCRIPTION
**Pull request by AMiketta**
### PR checklist

- [ x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

the Pullrequest fixed a crash that I noticed in several projects when accessing the network from a background thread
@ehyche

### CODE REVIEW

**Comment by AMiketta** [comment]
@ehyche please review

**Comment by AMiketta** [comment]
so you merged the changes in ?

**Comment by ehyche** [comment]
@AMiketta : hmm... not sure why the merge button is not showing up for me. I know I used to have write access in this repo. Let me check.

**Comment by HugoMario** [comment]
hey @AMiketta  @ehyche , i'll check if i can help you to have write permission again, meantime ping me anytime you need help to merge any PR. Thanks for this btw!!

**Pull request merged**
