### PR TITLE
[WIP] - Html Docs 2 - API and Client Library Documentation - Feedback / Assistance wanted

### PR DESCRIPTION
**Pull request by jhitchcock**
Hello All! 

Further to an attempt at creating some 'slack' style docs, Here's a WIP of a HTML documentation format, in brief here's what I'm trying to achieve with these docs; 

- Nice fresh tidy documentation (Based on JSDoc format)
- Jsonschemaview for parameter and response definitions
- Formatted/Highlighted example responses
- Client Library / SDK Code samples in a tabbed interface for popular languages (Taking code samples from Readme's in each language) 
- All rendered into a single HTML file (As opposed to lots of dependencies) that can be saved/emailed/ rendered in realtime / whatever

Here's an image of where I'm at
[
htmldoc2
](url)

In general I think its working well, The code samples need some more attention, I think I'm going to come up against an issue where some languages require different casing for the same thing, so may have to start utilizing some more vendor extensions / hacks! 

This may be an ongoing project

Anyway, 

Would appreciate any feedback / advice / assistance :) Tag anyone who may be interested! Thanks for reading!

### CODE REVIEW

**Comment by jhitchcock** [comment]
p.s. If you want to merge feel free, nothing will actually break the build, Just needs template improvements :)

**Comment by wing328** [comment]
@jhitchcock thanks for the PR.

> I think I'm going to come up against an issue where some languages require different casing for the same thing, so may have to start utilizing some more vendor extensions / hacks!

If you can list out the casing required for the variables (e.g. operationId), we can start adding those mustache tags so that you can use them directly without using vendor extensions.

**Comment by wing328** [comment]
This also fixes https://github.com/swagger-api/swagger-codegen/issues/1387

**Comment by wing328** [comment]
@jhitchcock thanks for the contribution. PR merged.

**Comment by jhitchcock** [comment]
Many Thanks, I'll add the extra tags as I do new languages and improve the templates. Hopefully others will contribute too!

**Pull request merged**
