### PR TITLE
[Jaxrs-cxf] Add bean-level cascaded beanvalidation for pojos (@Valid) fix #4738

### LINKED ISSUE #4738: Add support for BeanValidation @Valid annotation on nested attributes
##### Description

When useBeanValidation flag is true, it does not add @Valid annotation to attributes of type object. For instance, I have the class JoinDetails which has a field of type MemberProfile. When I validate joinDetails instance, the validator does not validate memberProfile because there is no @Valid annotation on it. It would be better if swagger-codegen can support this use cases either using extraAnnotation (i.e. x-extraAnnotation: "@Valid") in swagger config or automatically added during code generation.

##### Swagger-codegen version

2.2.2-SNAPSHOT

##### Swagger declaration file content or url

    ```yaml
    JoinDetails:
    type: object
    required:
      - memberProfile
    properties:
      memberProfile:
        $ref: '#/definitions/MemberProfile'
     MemberProfile:
    type: object
    required:
      - firstName
      - lastName
    properties:
      firstName:
        type: string
        maxLength: 50
      lastName:
        type: string
        maxLength: 50
    ```

##### Command line used for generation

I'm using maven:

<groupId>io.swagger</groupId>
<artifactId>swagger-codegen-maven-plugin</artifactId>
<version>2.2.2-SNAPSHOT</version>

##### Suggest a Fix

Add support via x- extension or automatically detect complex object or entities from the model.

### PR DESCRIPTION
**Pull request by fabian-braun**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

fix #4738 . Followup on PR https://github.com/swagger-api/swagger-codegen/pull/4922 .

This PR allows to use cascaded bean validation for jaxrs-cxf.
In short: If a POJO contain other POJO fields, these can be validated recursively by CXF if they are annotated with `@Valid`.

In https://github.com/swagger-api/swagger-codegen/pull/4922 one open issue was mentioned:

> `@Valid` is currently also generated for properties of type:
> - java.lang.BigDecimal
> - javax.xml.datatype.XMLGregorianCalendar
> - org.joda.time.LocalDate
> - java.util.UUID

With this new PR the behavior changes: 
- java.lang.BigDecimal - `@Valid` still generated
- javax.xml.datatype.XMLGregorianCalendar - untested
- org.joda.time.LocalDate - fixed (no `@Valid` generated)
- java.util.UUID -  fixed (no `@Valid` generated)

However IMO it is not a problem that some non-applicable types are still annotated with `@Valid`. The validation provider will skip validation as soon as it notices that no further validation annotations are present on these types.

One additional change to the original PR is, that also containers are annotated with `@Valid`
According to http://beanvalidation.org/2.0/spec/:

> Collection-valued, array-valued and generally Iterable fields and properties may also be decorated with the @Valid annotation. This causes the contents of the iterator to be validated. Any object implementing java.lang.Iterable is supported.

This feature is already present since beanvalidation 1.0

Some additional remarks because this is my first contribution:

- I have added a new windows-bat file `swagger-codegen\bin\windows\jaxrs-cxf-petstore-server.bat` to the project, because it was missing (I created it based on the corresponding .sh file).
- When I checked out the current master and generated the model it was already not in line with what was committed. In the contribution guide it says that this can happen, so I just committed those files in the last commit of this PR.

@jfiala : would you be so kind to review the PR

### CODE REVIEW

**Comment by wing328** [comment]
@fabian-braun I'll merge it this weekend if there's no further question/feedback from the community.

**Comment by fabian-braun** [comment]
@wing328 Thanks for your initiative and feedback!

**Comment by wing328** [comment]
@fabian-braun PR merged into master. Have a nice weekend.

**Comment by filbert3** [comment]
Hi @wing328, is the fixed included in swagger codegen v3? What else do I need to do except set <useBeanValidation>true</useBeanValidation> in <configOptions>? I don't see nested @Valid in my generated code.

**Pull request merged**
