### PR TITLE
[python-flask] Apply template tweaks to improve lint results

### PR DESCRIPTION
**Pull request by kenjones-cisco**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

The linting results for the generated samples are as follows
where the first number is the BEFORE and the second is AFTER.

```
flaskConnexion          1843 vs. 20
flaskConnexion-python2  1841 vs. 19
```

For the complete details please see the following gist.
https://gist.github.com/kenjones-cisco/edc9d71ef7fd2bf23714ecbb693d52b3

@taxpon  @frol  @mbohlool  @cbornet 
CC @wing328

### CODE REVIEW

**Comment by cbornet** [comment]
Is it pylint output ?
Most of the templates come from the python client. Do you think you could apply the changes there also ?

**Comment by cbornet** [comment]
Also, as you change the imports, can you check that the server starts well both from command line and from pyCharm ? This can be tricky sometimes.
I guess the CI will test that tox/nose works well.

**Comment by kenjones-cisco** [comment]
I used flake8 for the linting.

As for pyCharm, I don't use that IDE so I'm not able to easily test it.

I can work on a separate PR for the python client as well.

**Comment by frol** [comment]
LGTM

**Comment by kenjones-cisco** [comment]
From command line:

```
{ flaskConnexion } task/handle-linting-errors » docker logs zen_allen
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
... OAuth2 token info URL missing. **IGNORING SECURITY REQUIREMENTS**
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```

```
{ flaskConnexion-python2 } task/handle-linting-errors » docker logs frosty_nobel
No handlers could be found for logger "connexion.operation"
 * Running on http://0.0.0.0:8080/ (Press CTRL+C to quit)
```

**Pull request merged**
