### PR TITLE
[Haskell] Add partial header to haskell http client

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

Add partial header to haskell-http-client similar to what we've done for other generators.

### CODE REVIEW

**Comment by wing328** [comment]
cc @jonschoning

**Comment by jonschoning** [comment]
looks good

**Comment by jonschoning** [comment]
BTW, the header says

```
OpenAPI spec version: 1.0.0
```
is that correct?  I thought we were on OpenAPI spec version 2.0

**Comment by wing328** [comment]
I agree with you the wording is a bit confusing and will change it to "The version of the API" instead in my next update.

**Pull request merged**
