### PR TITLE
[Bash] Feature: Adds doc generation

### PR DESCRIPTION
**Pull request by kenjones-cisco**
Reference #2359

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

@frol  @bkryza
CC: @wing328

### CODE REVIEW

**Comment by kenjones-cisco** [comment]
Bash #2359

**Comment by kenjones-cisco** [comment]
PR for Review
@frol  
@bkryza 
CC: @wing328

**Comment by kenjones-cisco** [comment]
travis timed out during `mvn -q --batch-mode verify -Psamples`

**Comment by wing328** [comment]
@kenjones-cisco looks very good to me 👍

**Pull request merged**
