### PR TITLE
[PHP] Added HTTP basic authentication to ApiClient

### PR DESCRIPTION
**Pull request by BeneficialName**

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR wont' count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

**Comment by wing328** [comment]
@BeneficialName HTTP basic authentication should be working in the PHP API client. In your spec, do you have HTTP basic authentication properly defined?

**Comment by BeneficialName** [comment]
Haven't verified if is correctly defined in the spec. I'm new to Swagger and the spec I use is made by a 3 party.
I just saw that CURL was never given the basic auth information from configuration.

**Comment by wing328** [comment]
It's already done here: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/php/api.mustache#L236-L239

**Comment by BeneficialName** [comment]
Oh. Well I can see I need to get a better understanding of the Swagger spec. Anyhow thanks for the feedback.

**Comment by wing328** [comment]
@BeneficialName we would like to thank for your time to contribute a PR. If you've any question about the PHP client, please let us know.

**Pull request closed without merging**
