### PR TITLE
generator for dart jaguar

### PR DESCRIPTION
**Pull request by jaumard**
Add Swagger generation for Jaguar dart framework.

### CODE REVIEW

**Comment by HugoMario** [comment]
awesome!!! going to check it and see if we can port it to 3.0.0

**Comment by jaumard** [comment]
Cool ! I'm working on the auth support so wait a bit before migrating to 3.0.0 ^^

**Comment by jaumard** [comment]
For now blocked by https://github.com/Jaguar-dart/jaguar_serializer/issues/155 as the `inventory` call return a `Map` directly and there a bug in Jaguar for this kind of response

**Comment by jaumard** [comment]
@HugoMario all good on my side now :) the generator is/should be ok now

**Comment by HugoMario** [comment]
thanks @jaumard , going to review/test/verify the PR this week and merge if everything is ok.

**Pull request merged**
