### PR TITLE
Adding serialize methods to swift3 objects

### PR DESCRIPTION
**Pull request by Buisson**
### PR checklist

From issue -> https://github.com/swagger-api/swagger-codegen/issues/6089

### Description of the PR
Changes on the mustache model of swift 3. Added of serialize methods

### CODE REVIEW

**Comment by Buisson** [comment]
for travis fail :

[ERR!] GitHub API: GitHub rate limit reached.

    To increase the limit use GitHub authentication.

    See: https://github.com/DefinitelyTyped/tsd#tsdrc

**Comment by wing328** [comment]
@Buisson please run `./bin/swift3-petstore-all.sh` to update the Petstore samples so that the CI (travis) can test the change.

**Comment by wing328** [comment]
cc @jaz-ah @jgavris @Edubits

**Comment by Buisson** [comment]
@wing328 I just ran ./bin/swift3-petstore-all.sh and push it.

**Comment by jgavris** [comment]
Have you considered just using JSON serialization? We already support JSON. Adding support for `NSCoding` means basically doubling the interfaces we need to maintain.

**Comment by wing328** [comment]
Your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by Buisson** [comment]
@jgavris : Yes I tried but I wanted to save my serialize Object to UserDefaults and I prefer to use NSCoding for that.

**Comment by jgavris** [comment]
The unit tests don't compile with this change. You're also turning all the serializer classes into Objective-C objects which means all dynamic dispatch (slower). I'm not sure that's a fair tradeoff to make everyone's code slower for the sake of supporting an additional serialization format.

**Comment by Buisson** [comment]
@jgavris the unit test don't pass because of : 
```
[ERR!] GitHub API: GitHub rate limit reached.

    To increase the limit use GitHub authentication.

    See: https://github.com/DefinitelyTyped/tsd#tsdrc
```

**Comment by jgavris** [comment]
I ran them locally. Try `open ./samples/client/petstore/swift3/default/SwaggerClientTests/SwaggerClient.xcworkspace` and then hit command U

**Comment by Buisson** [comment]
@jgavris I have to use NSCoding methods to save my objects to UserDefaults. How can I save my Objects with your encodeToJSON method to save on UserDefaults. Can you show me an example code ? because all code sample I have search for show the method with NSCoding. Thanks.

**Comment by jgavris** [comment]
You would use the `encodeToJSON()` method on the serializer objects we have now, and then use `JSONSerialization` to convert to `Data`. You can then store that in `UserDefaults` like anything else.

**Comment by wing328** [comment]
@Buisson Your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
@Buisson please rebase on the latest master to resolve the merge conflicts if you still want this PR to be considered merging into master.

You may also want to try the `swift4` generator as well.

Closing this for the time being.

**Pull request closed without merging**
