### PR TITLE
fix map usage in api generation #3694

### PR DESCRIPTION
**Pull request by ataraxus**
Fix for issue: 

https://github.com/swagger-api/swagger-codegen/issues/3695

### CODE REVIEW

**Comment by wing328** [comment]
@ataraxus thanks for the PR. Please run `typescript-angular2-petstore-all.sh` to update the Petstore sample as mentioned in the PR checklist.

**Comment by ataraxus** [comment]
with updated petstore

**Comment by wing328** [comment]
@ataraxus thanks. I'll review later.

**Comment by wing328** [comment]
@ataraxus two questions if you don't mind. For query parameters, we've the following:
```
 {{#queryParams}}
         if ({{paramName}} !== undefined) {
             queryParameters.set('{{baseName}}', String({{paramName}}));
         }
 
 {{/queryParams}}
```
Shall we replace String() with <any> instead (similar to what you use for formParams.set)?

For form parameters, do we need to check for `undefined`?

I think we should make the handling of query and form parameters consistent if possible.

**Comment by ataraxus** [comment]
hey @wing328  i agree with the check if the param is set. I also agree with the typeconversion. I didn't noticed it so i went for the "typescript" way of casting. but yours is also valid, see https://stackoverflow.com/questions/32554624/casting-a-number-to-a-string-in-typescript/32607656#32607656 
I changed it to my style, nevertheless ;) 
But feel free to change it

**Comment by wing328** [comment]
cc @Vrolijkx

**Comment by Vrolijkx** [comment]
seem ok for me.

**Comment by wing328** [comment]
@Vrolijkx thanks for reviewing.

@ataraxus PR merged. Thanks for your contribution.

**Pull request merged**
