### PR TITLE
Python vnd content-type header support

### PR DESCRIPTION
**Pull request by lrimkus**
Adding vendor header support like : "Content-Type: application/vnd.api+json" and "Content-Type: application/vnd.api+json; version=1"

### CODE REVIEW

**Comment by wing328** [comment]
@lrimkus thanks for the PR. Can you also run `./bin/python-petstore.sh` to update the Petstore sample so that CI (travis) can run the tests against the change?

**Comment by lrimkus** [comment]
done and done. Looks like pet-store created changes that are not connected to my enhancement.

**Comment by wing328** [comment]
@lrimkus Thanks for the prompt update. That's possible because we add more test cases to PetStore spec (for testing) from time to time and you may find changes not related to your change in the Python PetStore API client.

I'll review the change and let you know if I've any questions. (That the CI tests passed is a good sign there's no integration issues with the Petstore API client - python 2.x and python 3.x)

**Comment by wing328** [comment]
@lrimkus PR merged. Thanks for the contribution.

**Pull request merged**
