### PR TITLE
Fixed missing isWildcard method used in templates

### PR DESCRIPTION
**Pull request by chosroes**
In PHP templates (and certainly others), an isWildcard method exists to render a default proposition in switch list.
But the corresponding method was removed inconsistently from the CodegenResponse class.

So I make this PR.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by chosroes** [comment]
@wing328 I added the email to my account :-)

**Comment by wing328** [comment]
@chosroes thanks for the PR, which has been merged into master.

akka-scala is using that too so I'll file a PR to add similar fix.

**Comment by wing328** [comment]
Updated master via ef35b80

**Pull request merged**
