### PR TITLE
[html]Group api index by operations.baseName

### PR DESCRIPTION
**Pull request by wy-z**
- Group api index by operations.baseName 
- Change little style

Signed-off-by: weiyang <weiyang.ones@gmail.com>

### CODE REVIEW

**Comment by wing328** [comment]
@wy-z thanks for the PR. Please run `./bin/html-petstore.sh` to update the Petstore sample.

There's also a new HTML documentation generator `html2` that you may want to give it a try.

**Comment by wy-z** [comment]
@wing328 Done

**Comment by wing328** [comment]
@wy-z thanks for the PR, which has been merged into master.

**Comment by wy-z** [comment]
@wing328  It is my pleasure.
I have trid `html2 `, but it is unsatisfactory...
It will cause my browser to crash, when there are 200+ api...

**Comment by wing328** [comment]
@wy-z does it (html2 doc) crash in *all* browsers (chrome, firefox, safari, IE)?

**Comment by wy-z** [comment]
- Chrome  53.0.2785.116 (64-bit)
- Safari 10.0 (12602.1.50.0.10)

**Comment by wing328** [comment]
@wy-z do you mind sharing the spec so that we can more easily reproduce the issue?

**Comment by wy-z** [comment]
I'm afraid I can't...

**Comment by wing328** [comment]
@wy-z that's ok. Thanks again for the enhancement.

**Comment by wy-z** [comment]
It is my pleasure~

**Pull request merged**
