### PR TITLE
[WIP] Improve PHP client emitted code quality

### PR DESCRIPTION
**Pull request by dkarlovi**
### PR checklist

- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This is a fix for #3867 which tries to significantly improve PHP client's code quality using insights offered by PHPStorm's inspections (including built-in inspections, [EA Extended](https://plugins.jetbrains.com/plugin/7622?pr=idea),  [PHP Mess Detector](https://phpmd.org/), [PHP CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer), etc).

WIP

### CODE REVIEW

**Comment by dkarlovi** [comment]
@wing328 @arnested this is the basic direction I had in mind with #3867, it's still WIP, but if you have some sort of feedback before going further, I'd appreciate it.

**Comment by wing328** [comment]
@dkarlovi I'll review tomorrow and reply back if I've any feedback.

**Comment by wing328** [comment]
@dkarlovi the enhancements look good to me.

**Comment by arnested** [comment]
This looks really good, @dkarlovi!

**Comment by wing328** [comment]
@dkarlovi thanks for the enhancement, which has been merged into master.

For further enhancement, please file a separate PR.

**Comment by dkarlovi** [comment]
@wing328 it was a WIP, I'm not sure it's a good idea to merge now as-is, but OK, I'll continue in a separate PR. :+1:

**Comment by wing328** [comment]
I saw that (WIP) in the PR description but I don't see activity for more than a week so that's why I merged it.

**Comment by dkarlovi** [comment]
Yeah, sorry, I planned to continue this weekend.

Can you please undo the merge so we can do this properly? I haven't even checked the PR boxes, it might break stuff as is.

**Comment by wing328** [comment]
Sure. Done via https://github.com/swagger-api/swagger-codegen/pull/3968

**Comment by wing328** [comment]
Next time, I will do a better job by confirming with you (the author) first.

**Comment by dkarlovi** [comment]
Not a problem. :)

But just to clarify, do I now rebase on top of this and resubmit?

**Comment by wing328** [comment]
@dkarlovi I think you can simply resubmit.

**Pull request merged**
