### PR TITLE
Minor improvement to Java API client accept and content-type header

### PR DESCRIPTION
**Pull request by xhh**
This PR makes the behavior of handling Accept and Content-Type headers be consistent with PHP, Python and objc clients:

#759, #774, #780

### CODE REVIEW

**Comment by olensmar** [comment]
please rebase so we can merge!

**Comment by xhh** [comment]
@olensmar this PR would raise conflicts again once PR #791 is merged, so I'll wait for that PR to get merged first and then resolve the conflicts of this one

**Comment by fehguy** [comment]
@xhh #791 is merged--thank you again.

**Comment by xhh** [comment]
@fehguy resolved the merge conflicts, and tests passed successfully

**Comment by fehguy** [comment]
@xhh i'm still getting merge conflicts.

**Comment by xhh** [comment]
@fehguy fixed the merge conflicts again

**Comment by fehguy** [comment]
thanks, merged it

**Pull request merged**
