### PR TITLE
Fix #6567: [C#] Generate async methods with CancellationToken support

### LINKED ISSUE #6567: [C#] Generate async methods with CancellationToken support
More of a feature request than an issue. Would it be possible to generate async methods with CancellationToken support?

### PR DESCRIPTION
**Pull request by ozziepeeps**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Adds CancellationToken support for cancellable HTTP operations under C# (ref. https://github.com/swagger-api/swagger-codegen/issues/6567)

### CODE REVIEW

**Comment by ozziepeeps** [comment]
@mandrean @jimschubert - please review C# specifics.

**Comment by ozziepeeps** [comment]
Created https://github.com/swagger-api/swagger-codegen/issues/7927 for the CircleCI issue. I see other PRs submitted are failing automated checks due to the same underlying issue

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Please also run `./bin/csharp-petstore-all.sh` or the corresponding batch file under `.\bin\windows\` to update the C# Petstore samples so that CI (AppVeyor) can verify the change

(the CircleCI failure can be ignore as it's not related to the change)

**Comment by RicardPG-Vintra** [comment]
Hey you solved exactly the issue that i need, i'm using swagger-codegen-cli-2.3.1.jar with:
java -jar "codegen/swagger-codegen-cli-3.0.0-rc1.jar" generate -l csharp -i "yaml/genetec.yaml" -o "codegen/code"
and the process was perfect, but i had the problem with the CancellationToken, and each time that I generated the code I added it manually. Now I see that you fix this issue! THAAAAAANKS A LOT!

I downloaded the new versions 3.0.0-r0 and rc1 and csharp is not integrated yet :'(

It's possible get this fixed issue, compiling a jar file, with the capavility of execute the client like swagger 2.3.1? How? 

A lot of thanks!!!

**Comment by schrufygroovy** [comment]
Hi is this going to be fixed/implemented in part of some release in the future?

**Pull request closed without merging**
