### PR TITLE
[Swift] Use ISO-8601 date format

### PR DESCRIPTION
**Pull request by jgavris**
- Also fix up missing rawValue in Enum parameter generation for formParams.

I tried running `./bin/swift-petstore.sh` but it appears that is also broken on `master`. A potential solution to uncommenting out the integration tests for the ObjC / Swift codegen would be to add another CI service and configure that one for OS X? Maybe CircleCI?

### CODE REVIEW

**Comment by jgavris** [comment]
Resolves https://github.com/swagger-api/swagger-codegen/issues/3232

**Comment by wing328** [comment]
@jgavris when you've time, please rebase on the latest master to resolve the merge conflicts.

**Comment by wing328** [comment]
cc @Edubits @jaz-ah

**Comment by jgavris** [comment]
@wing328 Updated. Thanks for fixing `swift-petstore.sh`. I've checked in the sample project using `mvn verify -Pswift-client`.

**Comment by wing328** [comment]
@jgavris thanks for this and other PRs related to Swift. I've marked these PRs for 2.3.0 release as we'll release 2.2.0 soon.

If there's any Swift PRs you want to get into 2.2.0 stable release, please reply to let us know and we'll discuss on that.

**Comment by jgavris** [comment]
@wing328 Thanks! We're ok in the meantime using our fork. Let me know if there are any improvements or requirements to make the 2.3.0 release.

**Comment by jaz-ah** [comment]
+1 looks good to me - @wing328 good to merge here.

**Comment by jgavris** [comment]
@wing328 Would you object to putting this and my other PR's in 2.2.0? I know of a number of people who want at least the ISO-8601 formatter now.

**Comment by wing328** [comment]
@jgavris no objection from me. I'll merge the PR later today.

@jaz-ah thanks for reviewing the PR.

**Pull request merged**
