### PR TITLE
Java spring throw exceptions (#5686)

### PR DESCRIPTION
**Pull request by stevecookform3**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Adds 'throws Exception' to all controller methods. This allows servers to implement global exception handling in Spring, where controller methods can throw exceptions and have them handled globally.

Breaking change, hence filed against 2.3.0

See Issue #5686

### CODE REVIEW

**Comment by wing328** [comment]
@stevecookform3 your PR contains 2 commits not belonging to you.

I would suggest you to rebase the change on the latest 2.3.0 so as to resolve the merge conflicts (or file a new one based on the latest 2.3.0)

**Comment by stevecookform3** [comment]
@wing328 i've rebased to 2.3.0. can you take another look? thanks..

**Comment by stevecookform3** [comment]
@wing328 sorry let me fix the commit and test first

**Comment by wing328** [comment]
@stevecookform3 no worry. Please take your time and let us know if you need any help.

Most importantly, thanks for the enhancement 👍

**Comment by stevecookform3** [comment]
@wing328 fixed. can you take a look?

**Comment by wing328** [comment]
@stevecookform3 I've resolved the merge conflicts and merged your PR into 2.3.0 Please pull the latest to have a look. Thanks.

**Comment by cbornet** [comment]
Oh, too late it seems.
I think throwing `Exception` in interfaces is a bad pattern : it defeats the checked exception pattern and is just like using `Object` in your methods.
Checked exceptions should be handled in the implementations and if you want external handling (eg. ControllerAdvice/ExceptionHandler), you can rethrow runtime exceptions.

**Comment by wing328** [comment]
@cbornet well never too later to voice out :). Do you mind opening a new issue to start the discussion? 

Other server generators (e.g. Nancyfx) may need similar debate later so maybe we need a CLI option to cater both?

**Comment by Bols** [comment]
Global exception handling is generally not the right approach, and by default the generation should definitely NOT throw Exception. If anything, this should be a configurable option for those few that still use global exception handling. 
Not all breaking changes are good changes... :-)

**Comment by wing328** [comment]
@Bols Understood that not everyone likes global exception handling. Do you mind contributing the configurable option for this?

**Comment by Bols** [comment]
Jarle (who is sitting a couple of desks away) has fixed this now, right?

- Trond

**Comment by wing328** [comment]
@Bols yup, please pull the latest master to give it a try.

**Pull request merged**
