### PR TITLE
[Haskell] minor fix to template location for haskell-servant

### PR DESCRIPTION
**Pull request by wing328**
Tested and no longer have issue running `./bin/haskell-servant-petstore.sh`

### CODE REVIEW

**Comment by wing328** [comment]
cc @algas

**Comment by algas** [comment]
@wing328 Thank you

**Comment by wing328** [comment]
@algas np. Are you by any chance working on a Haskell API client as well?

**Comment by algas** [comment]
@wing328 Yes. I need time to do it.

**Pull request merged**
