### PR TITLE
Fixed minor compiler error and warning

### PR DESCRIPTION
**Pull request by RLangendam**
Fixed compiler error and warning for cpprestsdk client generator.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
Please also run `./bin/cpprest-petstore.sh` to update the Petstore samples.

**Comment by RLangendam** [comment]
After running `./bin/cpprest-petstore.sh` an untracked `VERSION` file was generated. Shouldn't this be `.gitignore`d?
```
$ git status
On branch fix-compiler-error
Your branch is up-to-date with 'origin/fix-compiler-error'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        samples/client/petstore/cpprest/.swagger-codegen/

nothing added to commit but untracked files present (use "git add" to track)
$ ls samples/client/petstore/cpprest/.swagger-codegen
VERSION
```

**Comment by wing328** [comment]
@RLangendam please add the file as well, which aims to show which version of Swagger Codegen was generated when generating the file.

The feature was added recently.

**Pull request merged**
