### PR TITLE
Fixed link to open issues (correct label is 'help wanted')

### PR DESCRIPTION
**Pull request by giuliopulina**
I noticed that the link to the search for open issues that need contributions was always showing up 0 results.
This PR changes the searched label from "Need community contribution" (I guess it was on old label) to "help wanted".

### CODE REVIEW

**Comment by wing328** [comment]
Good catch. We just renamed the label to conform to something recommended by Github.

**Comment by wing328** [comment]
Btw your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by giuliopulina** [comment]
@wing328 thanks for merging notifying me that my commit is not linked to my github account. 
I tried to add giuliopulina@users.noreply.github.com (the one in the commit) as secondary email but I receive an error: Error adding giuliopulina@users.noreply.github.com: email is already in use

Is there anything else I can try?

**Comment by wing328** [comment]
Under "Settings" => "Email", have you checked the option "Keep my email address private"? If yes, it should be able to recognize "giuliopulina@users.noreply.github.com" as your Github account.

**Comment by giuliopulina** [comment]
@wing328 yes, the option "Keep my email address private" was already checked.

**Comment by wing328** [comment]
@giuliopulina then I've no idea. I would suggest you to contact Github support to have this resolves.

**Comment by giuliopulina** [comment]
@wing328 just one more thing before contacting Github support: how can you check if the commit is not linked to my account?

Because if I look at commit history, everything seems fine:

image

**Comment by wing328** [comment]
The commit tab (https://github.com/swagger-api/swagger-codegen/pull/6779/commits) is showing the commit not linking to your account.

**Comment by giuliopulina** [comment]
Fixed :) thanks a lot.

**Comment by wing328** [comment]
Looks good now :)

**Pull request merged**
