### PR TITLE
Inject JAX-RS SecurityContext information into JAX-RS server implementation

### PR DESCRIPTION
**Pull request by nickcmaynard**
To access SecurityContext information (such as the logged-in user) from generated `*.api.impl` classes, it must have access to a SecurityContext object.

The factory/service/impl pattern in use in the JAX-RS server means the standard injection patterns won't work.

This PR injects the standard JAX-RS SecurityContext object into the signature of every operation, passing this information down into the implementation class.

### CODE REVIEW

**Comment by wing328** [comment]
Please update the sample as mentioned in the guidelines for contribution: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by nickcmaynard** [comment]
@wing328 All done, apologies for the missing bit.

**Comment by wing328** [comment]
@nickcmaynard when you've time, please rebase on the latest master so that I can merge the PR.

**Comment by nickcmaynard** [comment]
Well, that's cocked it up nicely... please don't merge this. I'll have to redo the whole thing.

**Comment by nickcmaynard** [comment]
Actually @wing328 I think your latest merge broke upstream.  See all the lines beginning "+" in master now.

**Comment by nickcmaynard** [comment]
No - I'm just confused by Github's representation of this PR now.  It's showing a bunch of "changes" against master that aren't actually real (looking at the command line, just my changes are shown).  Reopening.

Regardless @wing328, I think you want to take a look at `bin/all-petstore.sh` - something's added an extraneous `+` in there.

**Comment by wing328** [comment]
@nickcmaynard I think what I will do is to `cherry-pick` your commits and merge into master.

**Comment by wing328** [comment]
I cherry-picked 8a352f44c004bd60d5757014687156dc725bd439, updated the Petstore sample by running `./bin/jaxrs-petstore-server.sh` but got error when running `mvn test` in `samples/server/petstore/jaxrs`

Did you encounter similar error when running `mvn test` under `samples/server/petstore/jaxrs` ?

**Comment by nickcmaynard** [comment]
You're going to want fd8c768 as well.  I received no such error.

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/commit/fd8c7681a98fec2c7635087aab3daaf4f290710d contains updated Petstore samples for Jax-RS. Instead of cherry-picking it, I ran `./bin/jaxrs-petstore-server.sh` instead. Do you need to make any manual change to Jax-RS petstore sample instead to make it work with `mvn test`?

Here is the part of the error I got:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-jaxrs-server: Compilation failure: Compilation failure:
[ERROR] /Users/williamcheng/Code/wing328/swagger-codegen/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java:[22,8] io.swagger.api.impl.PetApiServiceImpl is not abstract and does not override abstract method uploadFile(java.lang.Long,java.lang.String,com.sun.jersey.core.header.FormDataContentDisposition,javax.ws.rs.core.SecurityContext) in io.swagger.api.PetApiService
[ERROR] /Users/williamcheng/Code/wing328/swagger-codegen/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java:[24,7] method does not override or implement a method from a supertype
[ERROR] /Users/williamcheng/Code/wing328/swagger-codegen/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java:[31,7] method does not override or implement a method from a supertype
[ERROR] /Users/williamcheng/Code/wing328/swagger-codegen/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java:[38,7] method does not override or implement a method from a supertype
[ERROR] /Users/williamcheng/Code/wing328/swagger-codegen/samples/server/petstore/jaxrs/src/main/java/io/swagger/api/impl/PetApiServiceImpl.java:[45,7] method does not override or implement a method from a supertype
```
I can send you the full error, which is a bit long, to your email if you need it.

**Comment by wing328** [comment]
FYI. Here is the branch that I'm working on and you can see it only contains 1 commit from you: https://github.com/swagger-api/swagger-codegen/compare/master...wing328:jaxrs_security1?expand=1

**Comment by nickcmaynard** [comment]
@wing328 This PR, and the source branch, includes two commits fd8c768 and 8a352f4.

**Comment by wing328** [comment]
I know it only contains 2 commits: fd8c768 and 8a352f4. My point is that if I only include 8a352f4 and run the ./bin/jaxrs-petstore.sh, running `mvn test` in `samples/server/petstore/jaxrs` should also work without any error. Do you agree? 

fd8c768 only contains sample update.

**Comment by nickcmaynard** [comment]
That's right.  And the error you're seeing is a compilation error in the samples.  Please use both commits.

**Comment by leonshaw** [comment]
Is it OK to also apply to JAX-RS spec codegen?

**Pull request closed without merging**
