### PR TITLE
Add new additional-property ignoreUnknownJacksonAnnotation to add a class level annotation @JsonIgnoreProperties(ignoreUnknown = true)

### PR DESCRIPTION
**Pull request by Ravisankar-Challa**
Add new additional-property ignoreUnknownJacksonAnnotation to add a class level annotation @JsonIgnoreProperties(ignoreUnknown = true)

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Add new additional-property ignoreUnknownJacksonAnnotation to add a class level annotation @JsonIgnoreProperties(ignoreUnknown = true)

### CODE REVIEW

**Comment by Ravisankar-Challa** [comment]
@HugoMario Could you please take a look at this PR. I am adding  a new addition-property ignoreUnknownJacksonAnnotation which will add @JsonIgnoreProperties(ignoreUnknown = true)

**Comment by Ravisankar-Challa** [comment]
@HugoMario Could please look in to this pull request

**Comment by HugoMario** [comment]
Yea, sure. Going to take a look on it.

**Comment by HugoMario** [comment]
LGTM
thanks a lot @Ravisankar-Challa for this PR

**Pull request merged**
