### PR TITLE
fixed the issue 5779 that html2 api doc does not display close curly brace

### PR DESCRIPTION
**Pull request by leonluocheng**
… correctly - refer to 5779

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by leonluocheng** [comment]
@wing328 aha, sure if you can help me to fix that. that will be nice. I am kind of new to github stuff.

**Comment by leonluocheng** [comment]
@wing328  looks like I mess up something that I should not to do. Is there a way I can revert this?

**Comment by wing328** [comment]
@leonluocheng ok. No worry. Please create a new one and let us know if you need any help.

**Comment by wing328** [comment]
@leonluocheng do you need help creating a new PR with the fix?

**Comment by leonluocheng** [comment]
@wing328 opps, sorry, I will create a new PR today or tomorrow.

**Comment by leonluocheng** [comment]
@wing328 new PR has been created on #6176. Please let me know if you have any questions.

**Pull request closed without merging**
