### PR TITLE
[Swift 4] Fix APIHelper to accept array parameter

### LINKED ISSUE #7796: [Swift 4] unacceptable collection parameter in query
##### Description

When calling api with query parameter which is contain collection (array, dictionary), some letters (`[`, `]` and so on) will be converted to percent-encorded letters. 

in `APIHelper.swift`, the parameter will be converted to String using string interpolation

```swift
    static func mapValuesToQueryItems(values: [String: Any?]) -> [URLQueryItem]? {
        let returnValues = values
            .filter { $0.1 != nil }
            .map { (item: (_key: String, _value: Any?)) -> URLQueryItem in
                URLQueryItem(name: item._key, value: "\(item._value!)")
            }
        if returnValues.count == 0 {
            return nil
        }
        return returnValues
    }
``` 

for example, as passing the array like `[1, 2, 3, 4,]` as a [Int], it'll be converted to `array-parameter=%5B1,%202,%203,%204,%5D` that not acceptable for server.

##### Swagger-codegen version

master, but still exist from 2.3.x

##### Swagger declaration file content or url
```yaml
  /xxx/{id}:
      parameters:
        - in: path
          name: xxx
          type: integer
          required: true
        - $ref: "#/parameters/Array-Parameter"

parameters:
  Array-Parameter:
    in: query
    name: arrayParameter
    type: array
    items:
      type: integer
```

##### Suggest a fix/enhancement

Now that we can understand whether the parameter is array or not, if we find array parameter passing to query, we just convert to string before passing to parameter.

```swift
url?.queryItems = APIHelper.mapValuesToQueryItems(values: [
  "array-parameter": arrayParameters?.reduce(into: "") { $0 += ",\($1)" }
])
```

Before:
```
?array-parameter=%5B1,%202,%203,%204,%5D // [1, 2, 3, 4]
```

After:
```
?array-parameter=1,2,3,4
```

### PR DESCRIPTION
**Pull request by d-date**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)
To be fix #7796 ,Fix APIHelper to accept array parameter with joined comma separated string. Also to improve performance, APIHelper was replaced to using `reduce(into:)`.

- [x] Fix APIHelper to accept array parameter with joined comma separated string
- [x] Performance improvement using reduce(into:)
- [x] replace `NSURLComponents` to `URLComponents`
- [x] fix failing unit tests
- [x] revise public initializers for Model Object to write unit test same as #7652 
- [x] Add `APIHelperTest`

### CODE REVIEW

**Comment by d-date** [comment]
@wing328 Could you check it?

**Comment by wing328** [comment]
@d-date sorry very busy these days. I'll review tomorrow

**Comment by wing328** [comment]
@d-date I got the following errors in Travis CI (https://travis-ci.org/swagger-api/swagger-codegen/builds/355218350): 

```
/Users/travis/build/swagger-api/swagger-codegen/samples/client/petstore/swift3/default/PetstoreClient/Classes/Swaggers/APIs/UserAPI.swift:249:58: error: extraneous argument label 'values:' in call

        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[

                                                         ^~~~~~~~

```

Did you get similar errors when running the tests locally in your machine?

**Comment by d-date** [comment]
@wing328 sorry, It's my regression and fixed it!

**Comment by wing328** [comment]
@d-date I tested again and don't see the error.

**Pull request merged**
