### PR TITLE
[New Generator] Rust API client/server generator

### PR DESCRIPTION
**Pull request by BenjaminGill-Metaswitch**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

This is a reasonably fully featured Rust client/server generator, developed independently of the existing `rust` client generator. We (@Metaswitch) are currently using some generated code in production.

At a high level, a trait is created from the swagger file. Clients can use the trait, whilst servers must implement it.

Common code is in https://github.com/Metaswitch/swagger-rs/, which should get transferred to https://github.com/swagger-api/ when this PR is accepted.

#### Current known issues

There are currently a number of known issues/feature gaps, of which the most significant are below. Only the naming issue should block this PR.

- [ ] `rust2` is not a very informative name
- [x] Need to resolve conflicts with master
- [ ] Currently uses `hyper 0.10` - work underway to upgrade to hyper `0.11` (which adds full async support)
- [ ] Documentation on how to use the generated code in a Rust project is lacking

### CODE REVIEW

**Comment by wing328** [comment]
@BenjaminGill-Metaswitch thanks for the PR

cc @lucab @farcaller @quodlibetor @ahmedcharles @frol

**Comment by BenjaminGill-Metaswitch** [comment]
@wing328 (et. al.) - we've now got no merge conflicts. I've also pulled in a couple of bug fixes (thanks @bruceadams).

I think this means that the only outstanding blocking issue is the choice of name - you suggested that `rust2` was not very descriptive.

I'm not sure I've yet got a better idea, but this PR could probably be reviewed in the interim.

**Comment by wing328** [comment]
I'll take another look by coming weekend.

**Comment by jaytiar** [comment]
@BenjaminGill-Metaswitch and I discussed ideas for a better name. Reflecting the fact that this version of the codegen supports both client and server (and is async) I suggested that `rust-complete` would be a better and suitable name. Views?

**Comment by wing328** [comment]
Just want to share with you that 'haskell-servant' is very similar to this Rust client/server generator in which `haskell-servant` generates both client and server code and `servant` is the server-side framework. Your generator can follow similar naming convention.

**Comment by BenjaminGill-Metaswitch** [comment]
Currently, we use `hyper` as the server-side framework (though we might consider switching over to something else [i.e. Rocket when it becomes stable] at a later date). The complication is that `hyper` also provides the client framework for both this generator and the existing `rust` generator.

**Comment by wing328** [comment]
Have you evaluated the current `rust` client generator? How does it compare with the Rust API client produced by the generator in this PR? Can we merge them into one as both are using `hyper`?

Maybe not for this PR. My suggestion is to make this generator for Rust server only and we can name it as `rust-server`. For Rust client, we just keep one generator `rust`.

**Comment by bruceadams** [comment]
As of about two weeks ago, the current `rust` generator produces Rust code that is hard to use and does not line up with other Rust libraries I have seen. The client generated from this pull request is much more Rust-typical.

**Comment by wing328** [comment]
@bruceadams thanks for reviewing the Rust code.

I would suggest naming this generator "rust-server" after merging this PR (understood that the generator also outputs Rust API client) and then later we pick one of the Rust API clients to become the `rust` generator or consolidate them into one (and `rust-server` will only generate server-side code after that).

cc @frol @farcaller

**Comment by wing328** [comment]
UPDATE: Resolved the merge conflicts. Will merge it tomorrow morning and make some minor enhancements.

**Comment by wing328** [comment]
UPDATE: Renamed `rust2` to `rust-server` via https://github.com/swagger-api/swagger-codegen/pull/6747

**Comment by wing328** [comment]
Future enhancements tracked via https://github.com/swagger-api/swagger-codegen/issues/6756

**Comment by wing328** [comment]
Tweet to promote the new generator: https://twitter.com/wing328/status/921009649440006144. Please help retweet.

**Pull request merged**
