### PR TITLE
[CPP] Fix cpp escape issue part of #5949

### PR DESCRIPTION
**Pull request by mmosemmle**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This change escapes special characters in the property names in the three c++ generators, while preserving the petstore samples. Part of #5949

### CODE REVIEW

**Comment by wing328** [comment]
@mmosemmle thanks for the PR. Please use 4-space instead of tab in Java files. Otherwise, the CI (travis) tests will fail.

**Comment by stkrwork** [comment]
With these changes, does everything compile and run (especially for cpprest, as a full client gets generated)?

**Comment by mmosemmle** [comment]
Hi,

Sorry about the lack of context in the PR. The specific case that this is
trying to fix is when variable names are not properly escaped, e.g.
input-name under properties, which will result in method names like
getInput-name() etc. in the corresponding class in model (Paper.h,
Paper.cpp in this case) This then gives uncompilable code. I have checked
that after the changes, the names of these methods are correct (i.e.
becomes getInputName() etc.) If you don't mind taking a look and see
whether the code do indeed compile and run properly when used as a cpprest
api, that would be great. Thank you very much for your help.

Best Regards,

Man Yue Mo

**Comment by stkrwork** [comment]
looks fine to me.

**Comment by wing328** [comment]
@mmosemmle thanks for refactor common operations into an abstract class "AbstractCppCodegen"

**Pull request merged**
