### PR TITLE
[Go-server] Fix formatting of go-server generated code

### PR DESCRIPTION
**Pull request by bvwells**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@antihax 

### Description of the PR

Make go-server generated code conform to go formatting standards as part of #3518 (see https://github.com/golang/go/wiki/CodeReviewComments)
 - Imports ordered correctly.
 - Tabs instead of spaces.
 - New lines at end of file.
 - Removal of superfluous lines.

Running
```
gofmt -w .
```
on generated code should not change formatting.

### CODE REVIEW

**Comment by wing328** [comment]
@bvwells thanks for the PR, which looks good to me

cc @antihax

**Comment by bvwells** [comment]
@wing328 thanks for the review!

**Comment by wing328** [comment]
Linked to  #3518

**Comment by bvwells** [comment]
Thanks again @wing328 for the review and merge!

**Pull request merged**
