### PR TITLE
added python flask sample

### PR DESCRIPTION
**Pull request by HugoMario**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

added flask sample.

### CODE REVIEW

**Comment by wobeng** [comment]
@HugoMario does this PR allow code generation for open 3.0 for python?

**Comment by HugoMario** [comment]
Hi @wobeng , yes it does !

**Comment by wobeng** [comment]
@HugoMario how can I use it?

**Comment by HugoMario** [comment]
@HugoMario python and python flask are currently on SNAPSHOT version, you can grab it latest bbuild [here](https://oss.sonatype.org/content/repositories/snapshots/io/swagger/codegen/v3/swagger-codegen-cli/3.0.9-SNAPSHOT/swagger-codegen-cli-3.0.9-20190610.160559-25.jar) 

and to gennerate code locally you can use this command (as example):

```
java -jar ./java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate -i http://petstore.swagger.io/v2/swagger.json -l aspnetcore -o /Users/hugomercado/Documents/tempo/v2 generate -i http://petstore.swagger.io/v2/swagger.json -l python-flask -o output
```

**Comment by HugoMario** [comment]
@wobeng

**Comment by wobeng** [comment]
@HugoMario you are the best, will try this

**Pull request merged**
