### PR TITLE
[Swift3] Add sample for unwrapRequired.

### PR DESCRIPTION
**Pull request by RyogaK**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
Before fixing a bug, I want to add a test for `unwrapRequired`.

#### What I did
- Add bin/swift3-petstore-unwraprequired.json
- Add bin/swift3-petstore-unwraprequired.sh
- Modify bin/swift3-petstore-all.sh
- And call bin/swift3-petstore-all.sh.

@wing328 Would you review this?

### CODE REVIEW

**Comment by wing328** [comment]
@RyogaK thanks for adding samples for the `unwrapRequired` option

Can you please also copy the test cases from https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/swift3/default/SwaggerClientTests?

You can then run `run_xcodebuild.sh` to test it locally (the tests may fail due to bad data in the public Petstore server, while the CI tests run a local Petstore server to avoid bad data added by the public)

Then you will need to update https://github.com/swagger-api/swagger-codegen/blob/master/pom.xml#L811 for the new samples so that the CI (travis) will run the test in the folder.

**Comment by RyogaK** [comment]
Sorry, I'll stop once working this.
I tried to use Swagger Codegen with swift3 on my work, but It seems more and more modifies needed to use on product.

I'll back after my works.

**Comment by wing328** [comment]
@RyogaK just to clarify. My suggestion above is to have a way to test Swift3 Petstore client with `unwrapRequired` enabled. It's not a "must" for your fix to be merged into master. Thanks again for contributing the fix.

@jgavris @RobBlairInq @jaz-ah would you please review the fix when you've time?

**Comment by jaz-ah** [comment]
@RyogaK could you show me a quick diff b/w the basic code and the new unwrap code - I just want to get a sense of the difference since the code looks fine.

**Comment by RyogaK** [comment]
@jaz-ah Sorry, I can't understand what I should do specially with my poor english skill.
Should I put a diff between samples?

**Comment by RyogaK** [comment]
@wing328 I agree with having a way to test it. I'll follow your suggestion and do that when I have time if it's not finished.

**Comment by jaz-ah** [comment]
@RyogaK yes please just a small diff thanks

**Comment by RyogaK** [comment]
@jaz-ah 

I modified only 3 files and called `./bin/swift3-petstore-all.sh`.

1. Added following lines to `bin/swift3-petstore-all.sh`

```
ags="$@ generate -t modules/swagger-codegen/src/main/resources/swift3 -i modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -l swift3 -c ./bin/swift3-petstore-unwraprequired.json -o samples/client/petstore/swift3/unwraprequired"
 echo "#### Petstore Swift API client (unwraprequired) ####"
 java $JAVA_OPTS -jar $executable $ags
 ```

 2. Copied `bin/swift3-petstore.json` and added a "unwrapRequired" line. And saved as `bin/swift3-petstore-unwraprequired.json`

 ```
 {
   "podSummary": "PetstoreClient",
   "podHomepage": "https://github.com/swagger-api/swagger-codegen",
   "podAuthors": "",
   "projectName": "PetstoreClient",
   "unwrapRequired": true
 } 
 ```

3. Copied `bin/swift3-petstore.sh` and modified a following line, then saved as `bin/swift3-petstore-unwraprequired.sh`

```
ags="$@ generate -t modules/swagger-codegen/src/main/resources/swift3 -i modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -l swift3 -c ./bin/swift3-petstore.json -o samples/client/petstore/swift3/default"
```

to 

```
ags="$@ generate -t modules/swagger-codegen/src/main/resources/swift3 -i modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml -l swift3 -c ./bin/swift3-petstore-unwraprequired.json -o samples/client/petstore/swift3/unwraprequired"
```

Is that enough information?

**Comment by jaz-ah** [comment]
@wing328 +1 looks ok thx

**Pull request merged**
