### PR TITLE
[Python] async error handling fix

### PR DESCRIPTION
**Pull request by baartosz**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
Fixes issue https://github.com/swagger-api/swagger-codegen/issues/4235. Implementation of solution suggested here: https://github.com/swagger-api/swagger-codegen/issues/4235#issuecomment-291086921. See test cases for examples: https://github.com/swagger-api/swagger-codegen/pull/5308/files#diff-c5c849b26d5134175812cdb46ddbe39cR143

In next iteration implementation can be improved by adding separate methods for async stuff like `api.get_pet_by_id_async()` and `api.get_pet_by_id_async_with_http_info()`.

### CODE REVIEW

**Comment by wing328** [comment]
@baartosz thanks for the PR. 

@scottrw93 @frol @taxpon @scop please take a look when you've time.

**Comment by frol** [comment]
Looks good to me!

@baartosz Thank you for the PR!

**Comment by wing328** [comment]
@baartosz I noticed that the parameter `callback` has been renamed to `async`. Would it be ok to keep using `callback` as I want to minimize the change required for developers to use the enhancement?

**Comment by wing328** [comment]
@baartosz sorry please ignore my comment above. After rereading the code I think I now have a better understanding of how it works.

**Comment by wing328** [comment]
@frol thanks for reviewing the PR.

@baartosz thanks for fix 👍 

It would be nice to update the auto-generated documentation to provide an example on how to make an async call with the Python SDK.

**Comment by arcward** [comment]
I'm a little late on this, but it is possible to handle exceptions via the callback, though it's not pretty. I ended up, similar to the suggestion in #4235, creating a wrapper around the callback that accepts ``threading.Event()`` , which is added to a list. Then I ``wait()`` on all of the events, and ``set()`` is called from inside the callback. So when an ApiException gets thrown, it doesn't happen in an untouchable background thread. There's a better example here: https://stackoverflow.com/questions/38499261/how-to-block-and-wait-for-async-callback-based-python-function-calls

**Pull request merged**
