### PR TITLE
[Spring] Fixes #5244 Include basePath @RequestMapping in Spring API template

### LINKED ISSUE #5244: basePath specified in swagger file is ignored by spring code generator
##### Description

A basePath specified in a swagger file is ignored by the spring code generator. Annotation @RequestMapping doesn't contain it. 

##### Swagger-codegen version

2.2.2 (swagger-codegen-maven-plugin)

##### Swagger declaration file content or url
```yaml
################################################################################
#                             Metadata                                         #
################################################################################
# this is an example API to illustrate the usage of Swagger 

swagger: '2.0'
info:
  title: Person API
  description: Create, maintain, and update a person database as personal contacts' list.
  version: "1.0.0"

# array of all schemes that your API supports
schemes:
  - https
  
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json

################################################################################
#                                 Paths                                        #
################################################################################  
paths:

  /persons/{id}:              
    delete:
      summary: Deletes a person.
      description: |
        Deletes a person from the database.
      tags:
        - Person
      parameters:
        - name: id
          in: path
          description: The ID of the person to be deleted.
          type: integer
          format: int64
          required: true
      responses:
        204:
          description: Person deleted.
```
generates:
```Java
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-03-28T19:13:06.141+02:00")

@Api(value = "persons", description = "the persons API")
public interface PersonsApi {

    @ApiOperation(value = "Deletes a person.", notes = "Deletes a person from the database. ", response = Void.class, tags={ "Person", })
    @ApiResponses(value = { 
        @ApiResponse(code = 204, message = "Person deleted.", response = Void.class) })
    @RequestMapping(value = "/persons/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.DELETE)
    default ResponseEntity<Void> personsIdDelete(@ApiParam(value = "The ID of the person to be deleted.",required=true ) @PathVariable("id") Long id) {
        // do some magic!
        return new ResponseEntity<Void>(HttpStatus.OK);
    }

}
```

### PR DESCRIPTION
**Pull request by kerkhofsd**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09) @jeff9finger (2018/01)

### Description of the PR
Add `@RequestMapping(value = "{{{contextPath}}}")` on class level in the api.mustache template to correctly support the `basePath` swagger parameter.

To make this work for spring-cloud, I had to introduce a mustache variable `hostWithoutBasePath` and use this in the spring-cloud `apiClient.mustache` template.

### CODE REVIEW

**Comment by jawwadfarooq** [comment]
When will a new version i.e. v2.2.4 release with this fix?

**Comment by IsaacDeLaRosa** [comment]
@kerkhofsd is this going to be merged anytime soon? what is the workaround? maybe something like a `openapi.openAPIPetstore.base-path:/v2` var in the spring properties file similar to https://github.com/OpenAPITools/openapi-generator/blob/6a00b2a802c688a235539c8425924ad6287b49d6/samples/server/petstore/springboot-reactive/src/main/java/org/openapitools/api/AnotherFakeApiController.java#L9

**Comment by mikela10000** [comment]
@kerkhofsd i would really appreciate the merge of this.
My current workaround it to put manually the path in the RestControler, but this is a temporary fix.

@RestController
@RequestMapping(path = "/api/XXX/v1")
public class MyApplicationController implements SomeApi {
}

Is this PR for swagger 3.0 version ? currently still using 2.0.

**Comment by highlysignificantbit** [comment]
Should be nice if this were fixed! Doing the same now as @mikela10000 ...

**Comment by talaviss** [comment]
When will this PR be merged?

**Comment by shark300** [comment]
Ping

**Comment by kerkhofsd** [comment]
As the creator of this PR (I'm just an open source contributor), I do not have any idea if this ever will be merged. 
As everyone can see, I didn't receive any feedback and there was no effort to get this merged so far.

**Comment by sergeypavlikhin** [comment]
Is it possible to close and reopen this PR? This step will bump one

**Comment by HugoMario** [comment]
hi @kerkhofsd , sorry for this long and no fair delay. i'm going to check your changes and merge them. Thanks !!

**Comment by frantuma** [comment]
please build

**Pull request merged**
