### PR TITLE
Fixes #429: Handling of composed models has been added.

### LINKED ISSUE #429: ClassCastException ComposedModel cannot be cast to ModelImpl trying to generate html from spec with $ref in definitions
In branch develop_2.0 I was able to do a 'git pull' and got a clean 'mvn package' build.

First, some minor problem:

I followed the README.md instructions 
```
java -cp ./target/*:./target/lib/* com.wordnik.swagger.codegen.Codegen \
  -i http://petstore.swagger.wordnik.com/v2/swagger.json \
  -l java \
  -o samples/client/petstore/java
```
but had to change the classpath because Maven puts the jars in `modules/swagger-codegen/target` and `modules/swagger-codegen/target/lib` not in `target` and `target/lib` (please fix README.md)

./bin/html.sh does not work because the URL  http://petstore.swagger.wordnik.com/v2/swagger.json does not exist (that redirects to  http://petstore.swagger.io ). I think you want **http://petstore.swagger.io/v2/swagger.json** instead

I changed html.sh and now it works.

I then substituted one of our internal Swagger 2.0 documents and got an exception:
```
./bin/html.sh
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
reading from http://swagger.na.sas.com/swagger/public/api/v1/swagger.json
no format specified for integer type, falling back to int32
java.lang.ClassCastException: com.wordnik.swagger.models.ComposedModel cannot be cast to com.wordnik.swagger.models.ModelImpl
	at com.wordnik.swagger.codegen.DefaultCodegen.fromModel(DefaultCodegen.java:361)
	at com.wordnik.swagger.codegen.DefaultGenerator.processModels(DefaultGenerator.java:348)
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:80)
	at com.wordnik.swagger.codegen.Codegen.main(Codegen.java:91)
```

The Swagger doc uses $ref in the schema definitions as shown in the sample at https://github.com/swagger-api/swagger-ui/issues/723  Perhaps this schema $ref is what results in a ComposedModel (petstore's schema do not use allOf)

This is possibly related to https://github.com/swagger-api/swagger-js/issues/188 although that bug appears tied to JavaScript (I don't know if codegen uses swagger-js)

### PR DESCRIPTION
**Pull request by tomtit**
Fixes #429: Handling of composed models has been added.

### CODE REVIEW

**Comment by Toilal** [comment]
:+1: Tested and approved here. Thanks.

**Comment by fehguy** [comment]
@tomtit can you please rebase?

**Comment by tomtit** [comment]
Rebased on develop_2.0

**Comment by fehguy** [comment]
@tomtit it looks like there are issues with the merge still

**Comment by tomtit** [comment]
Hmm... Rebased again.

**Pull request merged**
