### PR TITLE
Ts node angular2 typings

### PR DESCRIPTION
**Pull request by duanshiqiang**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [ x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
resolves issue #6163
(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by duanshiqiang** [comment]
@wing328 Thanks for reminding! I have modified the commits with correct email :)

**Comment by wing328** [comment]
@duanshiqiang thanks for the PR, which looks good to me.

(tests passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/257652049)

**Comment by wing328** [comment]
@duanshiqiang may I know if you've time to make the same enhancement to `typescript-angular` petstore client (samples/client/petstore/typescript-angular)?

Note: package.json is not automatically generated.

**Pull request merged**
