### PR TITLE
[Java] add automatic Beanvalidation check (performBeanValidation) to ok-http-gson #2549

### PR DESCRIPTION
**Pull request by jfiala**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR
Language: Java, library ok-http-gson

Added the implementation to perform a BeanValidation check on BeanValidation annotations before calling the remote service. This can be activated using the CLI flag performBeanValidation.
This effectiveley replaces the current required-check done.
The validation has been refactored into a separate *ValidateBeforeCall routine.

If there is a validation error, a BeanValidationException including the violations will be thrown.
If performBeanValidation=false (default) then the old required-check will be performed.

This implements the automatic beanvalidation demanded in #2549

### CODE REVIEW

**Comment by jfiala** [comment]
@wing328 pls take a look, now, the clients are able to perform beanvalidation automatically before calling the server and thus make use of the beanvalidation annotations.

**Comment by wing328** [comment]
I tested with `DperformBeanValidation` set to true
```
   java  -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
  -i modules/swagger-codegen/src/test/resources/2_0/petstore.json \
  -l java --library=okhttp-gson -DperformBeanValidation=true \
  -o /var/tmp/java/performBeanValidation2/ 
```
but got some errors when performing `mvn test`. Here is part of the result:
```
[ERROR] required: java.util.Set<javax.validation.ConstraintViolation<java.lang.Object>>
[ERROR] found:    java.util.Set<javax.validation.ConstraintViolation<io.swagger.client.api.StoreApi>>
[ERROR] /private/var/tmp/java/performBeanValidation/src/main/java/io/swagger/client/api/StoreApi.java:[504,97] incompatible types
[ERROR] required: java.util.Set<javax.validation.ConstraintViolation<java.lang.Object>>
[ERROR] found:    java.util.Set<javax.validation.ConstraintViolation<io.swagger.client.api.StoreApi>>
[ERROR] /private/var/tmp/java/performBeanValidation/src/main/java/io/swagger/client/api/PetApi.java:[114,97] incompatible types
[ERROR] required: java.util.Set<javax.validation.ConstraintViolation<java.lang.Object>>
[ERROR] found:    java.util.Set<javax.validation.ConstraintViolation<io.swagger.client.api.PetApi>>
[ERROR] /private/var/tmp/java/performBeanValidation/src/main/java/io/swagger/client/api/PetApi.java:[245,97] incompatible types
```

Did you get similar error in your local environment?

**Comment by jfiala** [comment]
I tried it only with primitive types first, I'll try with the petstore myself and provide an update.

**Comment by jfiala** [comment]
This was a Java 7 generics issue, with Java 8 it worked without problems.
I fixed it by casting to (Set) simply without generics (sorry api.mustache shows a complete replace but in fact I only added the ValidateBeforeCall method).

**Comment by jfiala** [comment]
@wing328 I added a minor change: I uncommented the test invocation and marked the whole test class @Ignore. this allows the compiler to check the invocations also, I think this is better than commenting the invocation out. In fact it is less time to remove the @Ignore than to remove all the comments for the methods. What do you think?

**Comment by wing328** [comment]
@jfiala Tested again and result looks good. PR merged into master.

**Pull request merged**
