### PR TITLE
Support for multiple inputSpecs for swagger codegen

### PR DESCRIPTION
**Pull request by sergeivisotsky**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
The following changes provide a support for several inputSpecs for Swagger codegen as well as Swagger Codegen Maven plugin so that it was able to generate classes from several input specification at the same time

### CODE REVIEW

**Comment by sergeivisotsky** [comment]
@wing328, @frantuma - Please review

**Comment by sergeivisotsky** [comment]
@davidkiss, @0legg, @emilianobonassi, @xhh, @xhh, @nbruno, @gayathrigs, @lopesmcc, @charlescapps, @viclovsky

Someone, pls review solution provided.
PR created more than month ago.

**Comment by sergeivisotsky** [comment]
In case if you do not consider this as a compliant solution, pls, provide a proper comments or close PR.

**Comment by HugoMario** [comment]
hey @sergeivisotsky, sorry for delay. i have not seen this before. I still dont see the purpose of using multiple inputs but going to review your changes.

**Comment by sergeivisotsky** [comment]
@HugoMario The purpose is pretty simple. Sometimes we have several swagger.json files that should be transformed to Java classes otherwise we need to define several maven phrases with the same plugin declaration but for different purpose.

**Comment by HugoMario** [comment]
@sergeivisotsky got it, that implies more changes than the proposed in this PR, also we need to considere more scenarios, for example in this case:
See this method call https://github.com/swagger-api/swagger-codegen/blob/86fed12efba392f0e304e825f7f9f71327da901e/modules/swagger-codegen-cli/src/main/java/io/swagger/codegen/cmd/Generate.java#L305

It points to:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultGenerator.java#L760-L785

But, it i use 10 input specs, which one will be used?

Also, what happen if the are models with same name in different specs, same for api classes and operations.

**Comment by sergeivisotsky** [comment]
no time for implementation

**Pull request closed without merging**
