### PR TITLE
Merge master to 2.3.0

### PR DESCRIPTION
**Pull request by ePaul**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change.
       → ran all the executable .sh files under ./bin/. (Some were not executable, I didn't try to run those.)
- [x] Filed the PR against the correct branch: `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

I noted that master and the 2.3.0 branch diverged quite a bit. So here I merged master into 2.3.0, resolving lots of conflicts.

Interesting cases:

* most objc templates had quite similar old and new code, with totally different "last known anchestor" one. I usually took the master version here.
* SpringCodegen.java also was completely replaced in both master and 2.3.0 after the latest common anchestor. I took the master version here.

I didn't try to resolve any conflicts in the samples, just regenerated all of them.

This needs some detailed review, because I'm not sure everything still works as it should.

I guess this should be done much more often, so the conflicts don't get that big.

### CODE REVIEW

**Comment by ePaul** [comment]
Hmm, Travis CI fails in building (or testing?) the clojure samples. No idea what this is about.

I didn't had any conflicts in clojure related code. I will later try to regenerate the samples in just master and just 2.3.0.

```
lein test :only swagger-petstore.core-test/test-api-context
FAIL in (test-api-context) (core_test.clj:9)
default
expected: (= {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil, "test_api_client_id" nil, "test_api_client_secret" nil, "test_api_key_query" nil, "test_api_key_header" nil}} default-api-context *api-context* (with-api-context {} *api-context*))
  actual: (not (= {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil, "test_api_client_id" nil, "test_api_client_secret" nil, "test_api_key_query" nil, "test_api_key_header" nil}} {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil}} {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil}} {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil}}))
lein test :only swagger-petstore.core-test/test-api-context
FAIL in (test-api-context) (core_test.clj:48)
customize via with-api-context
expected: (= {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil, "test_api_client_id" nil, "test_api_client_secret" nil, "test_api_key_query" nil, "test_api_key_header" nil}} default-api-context *api-context*)
  actual: (not (= {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil, "test_api_client_id" nil, "test_api_client_secret" nil, "test_api_key_query" nil, "test_api_key_header" nil}} {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil}} {:base-url "http://petstore.swagger.io/v2", :date-format "yyyy-MM-dd", :datetime-format "yyyy-MM-dd'T'HH:mm:ss.SSSXXX", :debug false, :auths {"api_key" nil, "petstore_auth" nil}}))
Ran 26 tests containing 159 assertions.
2 failures, 0 errors.
Tests failed.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ........................... SUCCESS [4.019s]
[INFO] swagger-codegen (core library) .................... SUCCESS [50.379s]
[INFO] swagger-codegen (executable) ...................... SUCCESS [31.986s]
[INFO] swagger-codegen (maven-plugin) .................... SUCCESS [6.436s]
[INFO] swagger-generator ................................. SUCCESS [19.983s]
[INFO] Ruby Swagger Petstore Client ...................... SUCCESS [26.545s]
[INFO] swagger-petstore-android-volley ................... SUCCESS [0.747s]
[INFO] Bash Swagger Petstore Client ...................... SUCCESS [1.520s]
[INFO] Swagger Petstore - Clojure Client ................. FAILURE [7.117s]
[INFO] Go Petstore Client ................................ SKIPPED
[INFO] swagger-petstore-feign ............................ SKIPPED
[INFO] swagger-java-client ............................... SKIPPED
[INFO] swagger-petstore-jersey2 .......................... SKIPPED
[INFO] swagger-petstore-okhttp-gson ...................... SKIPPED
[INFO] swagger-petstore-retrofit ......................... SKIPPED
[INFO] swagger-petstore-retrofit2 ........................ SKIPPED
[INFO] swagger-petstore-retrofit2-rx ..................... SKIPPED
[INFO] Swagger Petstore - Javascript Client .............. SKIPPED
[INFO] Python Swagger Petstore Client .................... SKIPPED
[INFO] swagger-scala-client .............................. SKIPPED
[INFO] TS Fetch Default Petstore Client .................. SKIPPED
[INFO] TS Fetch ES6 Petstore Client ...................... SKIPPED
[INFO] TS Fetch Petstore Client (with npm) ............... SKIPPED
[INFO] TS Fetch Petstore Test Client ..................... SKIPPED
[INFO] TS Angular Petstore Client ........................ SKIPPED
[INFO] TS Node npm Petstore Client ....................... SKIPPED
[INFO] swagger-inflector-server .......................... SKIPPED
[INFO] swagger-undertow-server ........................... SKIPPED
[INFO] swagger-jaxrs-jersey1-server ...................... SKIPPED
[INFO] swagger-jaxrs-server .............................. SKIPPED
[INFO] swagger-jaxrs-resteasy-server ..................... SKIPPED
[INFO] swagger-jaxrs-resteasy-joda-server ................ SKIPPED
[INFO] Scalatra server ................................... SKIPPED
[INFO] swagger-spring-mvc-server ......................... SKIPPED
[INFO] swagger-petstore-spring-cloud ..................... SKIPPED
[INFO] swagger-spring .................................... SKIPPED
[INFO] swagger-cxf-server ................................ SKIPPED
[INFO] swagger-cxf-annotated-basepath .................... SKIPPED
[INFO] swagger-jaxrs-cxf-cdi-server ...................... SKIPPED
[INFO] swagger-cxf-non-spring ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:29.848s
[INFO] Finished at: Sun Mar 12 22:25:17 UTC 2017
[INFO] Final Memory: 68M/256M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.2.1:exec (lein-test) on project swagger-petstore-clojure: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]
```

**Comment by ePaul** [comment]
Same error happens in master (#5040) and 2.3.0 (#5038). **Please don't merge yet**, I would like to see this fixed first and then this updated to see if there are other problems.

**Comment by wing328** [comment]
@ePaul one workaround is to comment out the test for Clogure client in pom.xml for the time being to see if the remaining tests pass.

**Comment by ePaul** [comment]
@wing328 I moved the clojure tests to the end (in this branch), so we can see if all the other tests work.

**Comment by ePaul** [comment]
Hmm, [now we get issues with feign](https://travis-ci.org/swagger-api/swagger-codegen/jobs/210508218):

```
...
[INFO] --- maven-compiler-plugin:2.5.1:testCompile (default-testCompile) @ swagger-petstore-feign ---
[WARNING] File encoding has not been set, using platform encoding UTF-8, i.e. build is platform dependent!
[INFO] Compiling 8 source files to /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/target/test-classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/Fake_classname_tags123ApiTest.java:[18,12] error: cannot find symbol
[ERROR]   symbol:   class Fake_classname_tags123Api
  location: class Fake_classname_tags123ApiTest
/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/Fake_classname_tags123ApiTest.java:[18,12] error: cannot find symbol
[ERROR]   symbol:   class Fake_classname_tags123Api
  location: class Fake_classname_tags123ApiTest
/home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/Fake_classname_tags123ApiTest.java:[22,42] error: cannot find symbol
[INFO] 3 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ........................... SUCCESS [6.821s]
[INFO] swagger-codegen (core library) .................... SUCCESS [53.376s]
[INFO] swagger-codegen (executable) ...................... SUCCESS [36.215s]
[INFO] swagger-codegen (maven-plugin) .................... SUCCESS [6.877s]
[INFO] swagger-generator ................................. SUCCESS [20.768s]
[INFO] Ruby Swagger Petstore Client ...................... SUCCESS [13.095s]
[INFO] swagger-petstore-android-volley ................... SUCCESS [1.129s]
[INFO] Bash Swagger Petstore Client ...................... SUCCESS [1.109s]
[INFO] Go Petstore Client ................................ SUCCESS [8.745s]
[INFO] swagger-petstore-feign ............................ FAILURE [6.654s]
[INFO] swagger-java-client ............................... SKIPPED
[INFO] swagger-petstore-jersey2 .......................... SKIPPED
...
[INFO] swagger-jaxrs-cxf-cdi-server ...................... SKIPPED
[INFO] swagger-cxf-non-spring ............................ SKIPPED
[INFO] Swagger Petstore - Clojure Client ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:36.177s
[INFO] Finished at: Mon Mar 13 10:28:35 UTC 2017
[INFO] Final Memory: 76M/247M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:testCompile (default-testCompile) on project swagger-petstore-feign: Compilation failure: Compilation failure:
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/Fake_classname_tags123ApiTest.java:[18,12] error: cannot find symbol
[ERROR] symbol:   class Fake_classname_tags123Api
[ERROR] location: class Fake_classname_tags123ApiTest
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/Fake_classname_tags123ApiTest.java:[18,12] error: cannot find symbol
[ERROR] symbol:   class Fake_classname_tags123Api
[ERROR] location: class Fake_classname_tags123ApiTest
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/java/feign/src/test/java/io/swagger/client/api/Fake_classname_tags123ApiTest.java:[22,42] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :swagger-petstore-feign
```

That happens neither on master nor on 2.3.0 (I tried to regenerate the Feign samples, and got no changes), so seems to be a result of a merge conflict. I'll have to look at it in detail.

**Comment by ePaul** [comment]
The generated interface is named `FakeClassnameTags123Api`, there is also a corresponding test, but somehow an old test file Fake_classname_tags123ApiTest is lying around, referring a Fake_classname_tags123Api (which does not exist).

I just deleted the whole samples/client/petstore/java/feign folder and generated again, let's see if that is better.

**Comment by ePaul** [comment]
Now we have the same issue with `swagger-java-client` (which is java/jersey1). Argh.

**Comment by wing328** [comment]
@ePaul I've seen this issue before (and fixed in my branch (WIP) for syncing master to 2.3.0)

I'm available in Gitter. Let's have a chat on this.

**Comment by wing328** [comment]
Btw, I've fixed the Clojure test issues via https://github.com/swagger-api/swagger-codegen/pull/5043 and will merge it into master once all the CI tests pass.

**Comment by ePaul** [comment]
The okhttp-gson conflict resolution didn't result in any result which compilable output. So here we have things left to do.

**Comment by ePaul** [comment]
Hmm, now swagger-scala-client breaks:

```
[INFO] ------------------------------------------------------------------------
[INFO] Building swagger-scala-client 1.0.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- build-helper-maven-plugin:1.9.1:add-source (add_sources) @ swagger-scala-client ---
[INFO] Source directory: /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/java added.
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ swagger-scala-client ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/resources
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:add-source (scala-compile-first) @ swagger-scala-client ---
[INFO] Add Source directory: /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala
[INFO] Add Test Source directory: /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/test/scala
[INFO] 
[INFO] --- scala-maven-plugin:3.1.5:compile (scala-compile-first) @ swagger-scala-client ---
[INFO] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala:-1: info: compiling
[INFO] Compiling 10 source files to /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/target/classes at 1489409081855
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala:34: error: object datatype is not a member of package com.fasterxml.jackson
[ERROR] import com.fasterxml.jackson.datatype.joda.JodaModule
[ERROR]                              ^
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala:44: error: not found: type JodaModule
[ERROR]     mapper.registerModule(new JodaModule());
[ERROR]                               ^
[ERROR] two errors found
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ........................... SUCCESS [5.610s]
[INFO] swagger-codegen (core library) .................... SUCCESS [53.708s]
...
[INFO] swagger-petstore-retrofit2-rx ..................... SUCCESS [8.839s]
[INFO] Swagger Petstore - Javascript Client .............. SUCCESS [4.417s]
[INFO] Python Swagger Petstore Client .................... SUCCESS [22.947s]
[INFO] swagger-scala-client .............................. FAILURE [7.238s]
[INFO] TS Fetch Default Petstore Client .................. SKIPPED
[INFO] TS Fetch ES6 Petstore Client ...................... SKIPPED
[INFO] TS Fetch Petstore Client (with npm) ............... SKIPPED
...
[INFO] Swagger Petstore - Clojure Client ................. SKIPPED
[INFO] swagger-petstore-okhttp-gson ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4:02.895s
[INFO] Finished at: Mon Mar 13 12:44:48 UTC 2017
[INFO] Final Memory: 100M/211M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:3.1.5:compile (scala-compile-first) on project swagger-scala-client: wrap: org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :swagger-scala-client
```

**Comment by ePaul** [comment]
This PR doesn't work the way I thought ... will retry later.
(The latest commits made it worse, deleting hand-crafted files I though were generated.)

**Pull request closed without merging**
