### PR TITLE
added Docker support

### LINKED ISSUE #1811: public docker image
For swagger-generator

### PR DESCRIPTION
**Pull request by fehguy**
Fixes #1811

### CODE REVIEW

**Comment by fehguy** [comment]
@wing328 somehow the ruby tests are failing, and seemingly independent of my changes

**Comment by wing328** [comment]
@fehguy let me look into that.

**Comment by wing328** [comment]
I could repeat the issue by updating to the following line in .travis.xml
```
sudo: required
```
I did a google search but couldn't find any solution to the error.

**Comment by fehguy** [comment]
thanks, I'll try to figure out why this is causing the problem

**Pull request merged**
