### PR TITLE
[PHP] error when deserializing enums #4032

### PR DESCRIPTION
**Pull request by baartosz**
### PR checklist

- [X] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fix for #4032. 
Example given in referenced ticket where Model has multiple properties is not really causing any errors on current version of SwaggerCodegen. 
This PR fixes serialization failure when we're dealing with Model containing only enum, like this one:
```
definitions:
  OuterEnum:
    type: "string"
    enum:
    - "placed"
    - "approved"
    - "delivered"
```

I added new serialization rule for this case and method `getAllowableEnumValues()` to Enum model class. Enum class is used only to validate parameters and store constants, deserialized result is just a string. Is it valid approach?

To differentiate between enum and non-enum model I am checking if model class has method `getAllowableEnumValues()`. That's dirty solution for now just to validate my idea. It would be nicer to have some EnumClassInterface instead.

Here's spec i was testing with:
```
swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger TEST
host: petstore.swagger.io
basePath: /api
paths:
  /fake:
    post:
      operationId: testPostingEnum
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/Enum_Test'
      responses:
        '200':
          description: ok
    get:
      operationId: testGettingEnum
      consumes:
        - "*/*"
      produces:
        - "*/*"
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Enum_Test'

definitions:
  Enum_Test:
    type: object
    properties:
      enum_string:
        type: string
        enum:
          - UPPER
          - lower
          - ''
      enum_integer:
        type: integer
        format: int32
        enum:
          - 1
          - -1
      enum_number:
        type: number
        format: double
        enum:
          - 1.1
          - -1.2
      outerEnum:
        $ref: '#/definitions/OuterEnum'
  OuterEnum:
    type: "string"
    enum:
    - "placed"
    - "approved"
    - "delivered"
```

Controller class for generated silex server:
```
<?php
require_once __DIR__ . '/vendor/autoload.php';

use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Silex\Application;

$app = new Silex\Application();
$app->get('/api/fake', function (Application $app, Request $request) {
    return new JsonResponse([
        'enum_string' => 'UPPER',
        'enum_integer' => -1,
        'enum_number' => -1.2,
        'outerEnum' => 'placed'
    ]);
});
$app->post('/api/fake', function (Application $app, Request $request) {
    file_put_contents('/tmp/a', print_r($request->getContent(), true));
    return new Response();
});


$app->run();
```

and php code using client:
```
   $config = new \Swagger\Client\Configuration();
    $config->setHost('http://localhost/api');
    $client = new Swagger\Client\ApiClient($config);
4032
    $fakeApi = new Swagger\Client\Api\DefaultApi($client);
    $response = $fakeApi->testGettingEnum();

    var_dump($response);
    var_dump($response->getEnumInteger());
    var_dump($response->getOuterEnum());

    $fakeApi->testPostingEnum(
        new \Swagger\Client\Model\EnumTest([
            'enum_string' => 'lower',
            'enum_integer' => 'lower',
            'enum_number' => 'lower',
            'outer_enum' => \Swagger\Client\Model\OuterEnum::DELIVERED
        ])
    );
 ```
Heres what server recives through POST:
`{"enum_string":"lower","enum_integer":"lower","enum_number":"lower","outerEnum":"delivered"}`
Heres output of test php code:
```
class Swagger\Client\Model\EnumTest#8 (1) {
  protected $container =>
  array(4) {
    'enum_string' =>
    string(5) "UPPER"
    'enum_integer' =>
    int(-1)
    'enum_number' =>
    double(-1.2)
    'outer_enum' =>
    string(6) "placed"
  }
}
int(-1)
string(6) "placed"
```

### CODE REVIEW

**Comment by baartosz** [comment]
What is preferred way to test when particular case is not available in petstore.swagger.io/v2 ?

**Comment by baartosz** [comment]
I figured I can test just serialization in this case. Added missing tests.

One problem I have here is that when serializing just string I can't check if provided value is allowed. Its not the case when enum type is nested inside some other object like in this example:
https://github.com/swagger-api/swagger-codegen/pull/4886/commits/38b5b62fe3bb00c7c206214210430cd41b8718e0#diff-872083d684159ca361436c8f51708074R81 

Is that okay? Maybe would it be better to pass instance of OuterEnum object with value inside? Spec says that its type is supposed to be string so I am not sure if its better option.

**Comment by wing328** [comment]
Yup, that's one way to test. In the C# API client, we've something similar: https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/csharp/SwaggerClient/src/IO.Swagger.Test/Api/StoreApiTests.cs#L130-L142

**Comment by wing328** [comment]
cc @arnested

**Pull request merged**
