### PR TITLE
address unused parameters and possible-nullity warnings

### PR DESCRIPTION
**Pull request by baronfel**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Newer versions of typescript allow compiler flags to mark these are errors, so the generated code should not cause app code to break.

### CODE REVIEW

**Comment by wing328** [comment]
@baronfel thanks for the PR. Please run `./bin/typescript-node-petstore-all.sh` to update the Petstore sample for Typescript Node.

**Comment by baronfel** [comment]
ah! I didn't realize the exmapls were updated and checked in. I'll get right on that.

**Comment by baronfel** [comment]
Ok, I've updated the samples.  I don't know where the whitespace changes came from, as I didn't touch those in my template update, but they are nonfunctional.  I've been looking at the jmustache documentation to see if there's anything I can do to trim it somehow.

**Comment by wing328** [comment]
@baronfel thanks for the PR, which has been merged into master.

**Pull request merged**
