### PR TITLE
Swift3: properly percent-escape path parameters

### PR DESCRIPTION
**Pull request by ehyche**
### PR checklist

- [x ] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

This change fixes the following issue:

https://github.com/swagger-api/swagger-codegen/issues/6400

The problem was that path parameters were not properly percent-escaped before being placed into the URL path. This leads to creation of an invalid URL, which then fails. So therefore, in the API template where path parameters are handled, we propertly percent escape them, using the characters which are allowed in URL paths.

In addition to this template change, then this PR includes the following changes:

1. Resulting changes in all generated code due to the above template change.
2. I added the objcCompatible run to the swift3-petstore-all.sh so that I could re-generated all of the generated code with a single script.
3. I added a unit test in UserAPITests.swift which verifies that paths are properly escaped.
4. In order to make the unit test work, then I needed access to RequestBuilder<T>.URLString to verify that the path was properly escaped. However, RequestBuilder<T>.URLString had "internal" access control so it was inaccessible from the unit test. So therefore, I made four contants in RequestBuilder<T> to be public. This should not harm anything, since they are constants ("let's") and cannot be changed from the outside of the class after initialization.
5. There were also some stray changes which look like they were caused by having not run bin/swift3-petstore-all.sh in a while.

@jaz-ah @jgavris @Edubits : please review

### CODE REVIEW

**Comment by jaz-ah** [comment]
+1 LGTM

**Comment by jgavris** [comment]
Nice. This is definitely a breaking change though right? I assume many people are already working around this by escaping some parameters manually.

**Comment by ehyche** [comment]
@jgavris : yes, folks would have had to work around this bug by passing in already-escaped path params. So it shouldn't break anyone, although their pre-escaping is unnecessary now.

**Comment by jgavris** [comment]
Won't double-encoding the parameters be an issue? That is assuming they see this change and update their request builders appropriately.

**Comment by ehyche** [comment]
@jgavris : yep, you' right. I verified that double-escaping could be an issue in a playground:

```
let pathParam = "/Some/Path With Spaces In It"
let escapedPathParam = pathParam.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
let escapedEscapedPathParam = escapedPathParam.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
print("pathParam=\(pathParam)\nescapedPathParam=\(escapedPathParam)\nescapedEscapedPathParam=\(escapedEscapedPathParam)")
```

which prints

```
pathParam=/Some/Path With Spaces In It
escapedPathParam=/Some/Path%20With%20Spaces%20In%20It
escapedEscapedPathParam=/Some/Path%2520With%2520Spaces%2520In%2520It
```

I had thought that:

```
.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed)
```

would be idempotent, but apparently '%' is not an allowed path character.

What do you think? Should I percent-decode and then re-enode? Or should we just make people aware of this potentially-breaking change? In practice, I think seeing path parameters with whitespace should be pretty rare.

**Comment by hce** [comment]
I'd just comply with the (swagger) standard, and if that says that spaces are allowed as a parameter, then they should be correctly escaped (principle of least surprise)

**Comment by hce** [comment]
=> If someone worked around a broken library before, they shouldn't be surprised if their code eventually breaks.

**Comment by jgavris** [comment]
I suppose I agree, it's not ideal but it was broken already. Let's push this through?

**Comment by hce** [comment]
I fixed the problem in my projects by manually modifying the *generated files* after each re-generation, thus a fix wouldn't cause any problems.

**Comment by wing328** [comment]
Tests passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/294707015

**Pull request merged**
