### PR TITLE
[Typescript/Fetch] Fix tslint issues in generated code

### PR DESCRIPTION
**Pull request by ChrisJamesC**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixed some typescript linting issues in the generated code.
 
Also added a test with tslint in the `package.json` of the generated typescript project. I don't know if this is how it should be done or if there is a way to run such a test in an automated way. Please let me know what's best if this is not convenient. 

The `tslint.json` config file used is the one generated by default by `tslint --init`.

### CODE REVIEW

**Comment by wing328** [comment]
@ChrisJamesC thanks for the PR, which looks good to me.

cc @Vrolijkx

**Comment by Vrolijkx** [comment]
The code change looks good for me.

**Comment by ChrisJamesC** [comment]
@Vrolijkx @wing328 Should I run the command `tslint api.ts` in the `npm install` command so that it gets tested on the automated builds? Or is `npm test` also ran?

**Comment by wing328** [comment]
@ChrisJamesC only one of the 5 tests we performed with fetch runs `npm test` while the others run `npm install`. 

I can later update pom.xml to run `npm test` instead of `npm install`. Does it sound good to you?

**Comment by ChrisJamesC** [comment]
@wing328 As you prefer. In the end, as long as it's ran as part of the build, before merging, it's all good. So if you say that it's ran, I'm all good.

**Comment by wing328** [comment]
@ChrisJamesC PR merged into master. Thanks for your contribution. 

I'll pull the latest master to play with `npm test`. Will let you know if I've any question including it in the CI.

**Comment by wing328** [comment]
@ChrisJamesC btw, would it be difficult to add the same enhancement for typescript node, angular, angular2 clients as well?

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Comment by ChrisJamesC** [comment]
I will look into it, it shouldn't be that difficult. It may be time consuming depending on the linting errors. 

(We don't use it yet, still evaluating it)

**Comment by wing328** [comment]
FYI. I've filed https://github.com/swagger-api/swagger-codegen/pull/4348 to add `npm test` to the CI (travis)

**Pull request merged**
