### PR TITLE
[javascript] Mark "fs" package as absent in browser in package.mustache

### PR DESCRIPTION
**Pull request by kemurphy**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

WIthout this, webpack and react-native both choke trying to resolve dependencies for packages generated by `swagger-codegen`.

### CODE REVIEW

**Comment by frol** [comment]
How will Electron handle this? (Electron has fs support) It seems that using package.json config option might make it uncontrollable from the user side.

The fix in #5765 might also solve the issue in browser as it catches the error of require('fs').

**Comment by kemurphy** [comment]
Electron doesn't seem to be affected -- per electron/electron#1574, the "browser" field in package.json is ignored since the author recognized Electron is more node-like than browser-like.

#5765 isn't sufficient because the breakage in both webpack and react-native isn't caused by running the code.  Rather, it's caused by static analysis of all `require` calls in the code.  Dynamic conditions don't affect it, nor can it be caught like an exception.

**Comment by frol** [comment]
@kemurphy Well, #5765 in combination with #5767 works for me in SSR mode (the chunk of code is not executed, but the module can be imported fine), in browser (Google Chrome and Firefox, but I will test it more thoroughly, yet I use Next.js so it may do some magic), and in Electron. I haven't tried react-native. It would be great if you can give #5765 a try and report the exact error you get before and after the fix (without your fix).

**Comment by kemurphy** [comment]
For #5767, the `node: { fs: 'empty' }` webpack configuration is equivalent to the `"browser": { "fs": false }` in package.json, and webpack can actually override the keys it looks for in package.json to pick alternate files and mark dependencies missing (https://webpack.js.org/configuration/resolve/#resolve-aliasfields).  (I actually suspect that AMD is not an issue and `imports-loader` isn't needed there.)  For react-native, however, there's no equivalent configuration -- it's either the "browser" field or the "react-native" field in package.json, and "browser" kills 2 birds with one stone.  #5765 and #5767 shouldn't be necessary with this one.

**Comment by frol** [comment]
@kemurphy OK, I will give it a try and report my results back tomorrow.

**Comment by kemurphy** [comment]
As expected, react-native blows up with #5765 applied instead of this one:

image

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by kemurphy** [comment]
Aha, sorry, I'll fix that now.

**Comment by wing328** [comment]
@frol if the test result looks good, I'll merge the enhancement into master.

**Comment by frol** [comment]
@wing328 I have tested it in browsers, in server-rendering mode, and in Electron. The fix works well and there is no need for the webpack config (`node: { fs: 'empty' }`) I mentioned in my PR #5767!

@kemurphy Thank you!

**Comment by wing328** [comment]
@frol thanks for testing it in different scenarios.

@kemurphy thanks again for the enhancement.

**Comment by frol** [comment]
@kemurphy You have said:

> (I actually suspect that AMD is not an issue and `imports-loader` isn't needed there.)

I would love to hear how to avoid `imports-loader`! Currently, if I remove the `imports-loader` config, I get the following errors:

On the server side:

```
These modules were not found:

* ApiClient in ./~/cloudsml-client/src/index.js
* model/BaseDataSource in ./~/cloudsml-client/src/index.js
* model/BaseDataTransformation in ./~/cloudsml-client/src/index.js
...
```

On the client side:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'ApiClient' in '/project/node_modules/cloudsml-client/src'
    at factoryCallback (/project/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/project/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/project/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel (/project/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /project/node_modules/async/dist/async.js:3838:9
    at /project/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/project/node_modules/async/dist/async.js:996:13)
    at /project/node_modules/async/dist/async.js:906:16
    at /project/node_modules/async/dist/async.js:3835:13
    at resolvers.normal.resolve (/project/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
```

**Comment by frol** [comment]
@kemurphy I am sorry to bother you, but I am still curious about the proper fix for the loader... Could you please shed some light on the issue? I am using Next.js and I am not sure what exactly they do with Webpack, but given the responses in #3466, it is not specific to Next.js usage.

**Pull request merged**
