### PR TITLE
Fix spring api operation annotation

### PR DESCRIPTION
**Pull request by wneild**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
Addresses #6699 where `@ApiOperation` annotation was using the specific response type which breaks for generic types. The fix changes the response to use the base type class instead. This change aligns the Spring template with the behavior of other Java server templates.

@bbdouglas (2017/07) @JFCote (2017/08) @sreeshas (2017/08) @jfiala (2017/08) @lukoyanov (2017/09) @cbornet (2017/09)

### CODE REVIEW

**Comment by cbornet** [comment]
LGTM
The other way would be to configure Springfox's docket with `.genericModelSubstitutes(xxx.class)`

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wneild** [comment]
Thanks for picking up on that @wing328! Should be fixed now.

**Comment by wing328** [comment]
@cbornet thanks for reviewing.

@wneild thanks for the PR to improve the Java Spring generator.

**Pull request merged**
