### PR TITLE
[Elixir] Improve Elixir client

### LINKED ISSUE #6549: [Elixir] Improving the Elixir codegen client
##### Description

Bugs:
* operation names could be invalid for elixir (have slashes)
* variable names could be invalid for elixir (a param could have '$' in the name)
* naming of mix library name could be invalid for elixir (have slashes)

Features:
* add `@typespec` hinting for Elixir dialyzer
* added documentation of all input types so the Elixir documentation generator works
* enable multipart uploads (files) with Tesla library ~ 0.8
* enable authentication
* enable generation of models - api responses should return structs rather than anonymous maps

Configuration:
* enable setting the namespace of the generated client
* allow adding license headers to the top of all generated files

### PR DESCRIPTION
**Pull request by chingor13**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixes #6549 

This PR generates more a more idiomatic Elixir client, fixes a few bugs, and adds a few more features:
* [bug] operation names could be invalid for elixir
* [bug] variable names could be invalid for elixir
* [bug] naming of mix library name could be invalid for elixir
* [feature] added `@typespec` hinting for Elixir dialyzer
* [feature] added documentation of all input types so the Elixir documentation generator works
* [feature] enable multipart uploads (files) with Tesla library ~ 0.8
* [feature] enable customization of connections with authentication handling
* [feature] enable generation of models - api responses return structs rather than anonymous maps
* [configuration] enable setting the namespace of the generated client
* [configuration] allow adding license headers to the top of all generated files

Note: This branch was used to successfully generate many hex packages after editing only the README.md and mix.exs (for packaging information): https://hex.pm/users/google-cloud

### CODE REVIEW

**Comment by wing328** [comment]
@chingor13 thanks for the PR.

cc @niku

**Comment by niku** [comment]
This PR seems very nice.
I'll review it in few days.

**Comment by niku** [comment]
I tried to compile a generated sample code for checking typings with using dialyzer. 
But I couldn't compile it.

https://gist.github.com/niku/41ad0df801fed6eff9d675320a5adfdf

I'm not sure keeping a generated sample code should work.
Anyway, I notice you 😃

**Comment by wing328** [comment]
> After removing two files, I can compile the project.

I should be able to fix the file naming. Will submit a PR soon.

**Comment by niku** [comment]
@wing328 
Thease file names are ok, modules in the files can't compile.
So, It seems that we need fix part of module name generation.

@chingor13 
Any thoughts?

```
% iex
Erlang/OTP 20 [erts-9.0.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule OkModule, do: ""
{:module, OkModule,
 <<70, 79, 82, 49, 0, 0, 2, 224, 66, 69, 65, 77, 65, 116, 85, 56, 0, 0, 0, 81,
   0, 0, 0, 7, 15, 69, 108, 105, 120, 105, 114, 46, 79, 107, 77, 111, 100, 117,
   108, 101, 8, 95, 95, 105, 110, 102, 111, ...>>, ""}

iex(2)> defmodule SwaggerPetstore.Model.$special[model.name], do: ""
** (SyntaxError) iex:2: unexpected token: "$" (column 33, codepoint U+0024)

iex(2)> defmodule SwaggerPetstore.Model.200_response, do: ""
** (SyntaxError) iex:2: syntax error before: 200
```

**Comment by wing328** [comment]
FYI. I've added compile test to Shippable CI for Elixir Petstore client via https://github.com/swagger-api/swagger-codegen/pull/6575

**Comment by wing328** [comment]
@chingor13 @niku I should have a fix shortly...

**Comment by wing328** [comment]
Fixed via https://github.com/swagger-api/swagger-codegen/commit/631add081d0163fc0946d86dd99f9cdedf911c0c (branch: https://github.com/swagger-api/swagger-codegen/tree/chingor13-elixir-client)

Local tests passed:
```
elixir|chingor13-elixir-client⚡ ⇒ mvn integration-test
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Elixir Petstore Client 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:copy-dependencies (default) @ ElixirPetstoreClientTests ---
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (dep-install) @ ElixirPetstoreClientTests ---
* creating /Users/williamcheng/.mix/archives/hex-0.17.1
[INFO] 
[INFO] --- exec-maven-plugin:1.2.1:exec (compile) @ ElixirPetstoreClientTests ---
Resolving Hex dependencies...
Dependency resolution completed:
  mime 1.1.0
  poison 3.1.0
  tesla 0.8.0
All dependencies up to date
Compiling 44 files (.ex)
Generated swagger_petstore app
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.801 s
[INFO] Finished at: 2017-09-27T22:30:34+08:00
[INFO] Final Memory: 11M/245M
[INFO] ------------------------------------------------------------------------
```

If no feedback or question from anyone, I'll merge it into master tomorrow.

(Probably not for this PR but for API file naming, we may consider appending _api so that pet_api.ex will have the module name "PetApi" as other client generators follow the same convention. In the Petstore example, there are both API and model files with the name "pet.ex". Not sure if this will potentially confuse Elixir developers)

**Comment by chingor13** [comment]
@niku I'll take a look at the naming for those cases. I had only tested against the real petstore json and using ones for Google APIs.

**Comment by wing328** [comment]
@chingor13 those naming issues are fixed by the commit I mentioned above. Please review when you have time.

**Comment by niku** [comment]
I

**Pull request merged**
