### PR TITLE
[Jaxrs-spec] Update jaxrs-spec to interface/impl pattern #4509

### PR DESCRIPTION
**Pull request by jfiala**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
> I filed against master, please review & let me know if I should do against 2.3.0. 
I'd prefer setting up a temporary language so we can have the change in 2.2.2.

### Description of the PR

see #4509

### CODE REVIEW

**Comment by jfiala** [comment]
@wing328 I filed against master for review, I'd like to have this in 2.2.2 - should I create a temporary language for this or do you want to stick with 2.3.0?

**Comment by wing328** [comment]
@jfiala from what I can tell it's a breaking change so I suggest we file it against 2.3.0 instead (we'll release 2.3.0 after the 2.2.2 release)

**Comment by jfiala** [comment]
@wing328 you're right, I can create a copy of the whole language so we can make it into 2.2.2 (as "jaxrs-spec-interface" or something like that) or we file it against 2.3.0, what do you prefer? I have a slightly preference for getting this into 2.2.2 if you agree (by copying).

**Comment by wing328** [comment]
@jfiala actually I want to freeze the current master and release 2.2.2. The community is very active (which is definitely a good thing) and we're seeing at least several new PRs (enhancements, bug fixes) every day so my take is to release 2.2.2 earlier and push those enhancements, bug fixes to the next release instead.

**Comment by jfiala** [comment]
@wing328 OK, then lets schedule this for 2.3.

**Comment by jfiala** [comment]
closed, will do again against 2.3.0.

**Comment by moshelav** [comment]
Does the suggestion from [https://github.com/swagger-api/swagger-codegen/issues/4509] was entered to specific release, if so which one?

As we are experiencing jersey (2) validation errors as swagger file type generated ReST with @Multipart Inputstream AND Attachment arguments.  By manually removing the generated Attachment argument seems it work... so does the following suggestion entered.

_look for alternatives for JAXRS-compliant alternatives to org.apache.cxf.jaxrs.ext.multipart.Attachment or comment it out
as there is currently no standardized way for supporting multipart/form-data (see https://java.net/jira/browse/JAX_RS_SPEC-413), I changed formParams.mustache to

**@FormParam(value = "{{paramName}}") InputStream {{paramName}}InputStream**
This should be a sufficient standard hint, although it will have to be adapted for CXF/Jersey/Resteasy then._

**Pull request closed without merging**
