### PR TITLE
[NancyFx] provide option to override package context

### PR DESCRIPTION
**Pull request by craffael**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR
See #6592 

@mandrean @jimschubert

### CODE REVIEW

**Comment by jimschubert** [comment]
Any idea why the generator splits these two properties rather than constructing packageName or package as other server generators do?

Asp.net Core:

https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/aspnetcore/controller.mustache

Scalatra:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/scalatra/api.mustache

**Comment by jimschubert** [comment]
Also, this change may need to be marked as a breaking change, as it will break any custom templates out in the wild.

**Comment by craffael** [comment]
@jimschubert  I have no clue why the namespace is constructed with the help of the basepath. I agree with you that the solution of Asp.net core and scalatra is much nicer.
As far as I can judge, my proposed pull request is not a breaking change because it only adds additional functionality. But I guess you're playing with thought of replacing `<packageName>.<packageContext>` with `<packageName>`? (which would be a breaking change)

**Comment by jimschubert** [comment]
@craffael I see now, I switched over to the full file before commenting, and thought that you had changed it from packageContext.packageContext, which I think is how it is described in the linked issue.

So yeah, not a breaking change... but I'd definitely push for alignment with properties used in templates.

**Comment by craffael** [comment]
Ah sorry for the confusion, I updated the linked issue. It's of course `packageName.packageContext`. I don't fully get your last comment: Would you rather change the namespace to just `packageName` (which would be a BREAKING change)?

**Comment by jimschubert** [comment]
@craffael Sorry, I seem to have forgotten the last sentence in that last comment.

I don't think it's a blocker or necessary change here, and could be opened as a new issue for the future.

However, I think it would be less of a breaking change now to move forward with package or packageName (whichever is more common) since there are already options in the default codegen to handle those. That way, there's not an extra property just for this generator which will likely become quickly deprecated.

It's a hard call, obviously, because we don't have any sort of telemetry to know the impact or what additional properties are actually being used.

**Comment by jimschubert** [comment]
@wing328 @mandrean thoughts on the above?

**Comment by wing328** [comment]
> As far as I can judge, my proposed pull request is not a breaking change because it only adds additional functionality.

I agree this is not a breaking change

> I agree with you that the solution of Asp.net core and scalatra is much nicer.

Can you please open a new "issue" (ticket) to track it to see if anyone from the community have time to work on the enhancement?

**Comment by wing328** [comment]
> However, I think it would be less of a breaking change now to move forward with package or packageName (whichever is more common)

Both are pretty common but personally I prefer "packageName"
```
swagger-codegen|master ⇒ grep -R "{{package}}" modules/swagger-codegen/src/main/resources/* | wc -l
     156
swagger-codegen|master ⇒ grep -R "{{packageName}}" modules/swagger-codegen/src/main/resources/* | wc -l
     283
```

**Pull request merged**
