### PR TITLE
akka scala fixes for invoker package, parameterized (cli) invokerPack…

### PR DESCRIPTION
**Pull request by macmacbr**
Add cli parameters for invokerPackage, groupId, artifactId, artifactversion
Also fix a "securities" bug (NPE) when there are none.

### CODE REVIEW

**Comment by fehguy** [comment]
Hi, if you can send this to the develop_2.0 branch, we will merge it.

**Comment by wing328** [comment]
@macmacbr one feedback if you don't mind, for the following
```
        cliOptions.add(new CliOption("invokerPackage", "root package for generated code"));
        cliOptions.add(new CliOption("groupId", "groupId in generated pom.xml"));
        cliOptions.add(new CliOption("artifactId", "artifactId in generated pom.xml"));
        cliOptions.add(new CliOption("artifactVersion", "artifact version in generated pom.xml"));
        cliOptions.add(new CliOption("sourceFolder", "source folder for generated code"));
```

it would be nice to include an example or default value for each option.

For my PR (#870) to add CLI for Perl, I've provided the following:
```
CONFIG OPTIONS
    moduleName
        perl module name (convention: CamelCase), default: SwaggerClient

    moduleVersion
        perl module version, default: 1.0.0
```

**Comment by wing328** [comment]
@macmacbr FYI. This PR has error reported by Travis CI.

**Comment by macmacbr** [comment]
Hi,

It will take some time to refactor the code to make it work on the
develop_2.0 branch. the cliOptions seems to have changed, plus files where
shuffled around.

I can try to refactor it later on.


Regards,

**Comment by wing328** [comment]
@macmacbr please resubmit this PR for `develop_2.0` branch as suggested by Tony. Thanks!

**Comment by webron** [comment]
@macmacbr - since develop_2.0 is quite deviated from master right now, you would require quite a few changes. I'm going to close this issue in preparation for a new version release *and* a move to development on the master branch directly.

Please look for the upcoming release and resubmit your PR against it. We'd be happy to review it again and if well, merge it in.

**Pull request closed without merging**
