### PR TITLE
[android] volley socket timeout configurable

### PR DESCRIPTION
**Pull request by sidhantgoyal**
This makes the volley request socket timeout equal to apiInvoker connection timeout.
Issue https://github.com/swagger-api/swagger-codegen/issues/3635

### CODE REVIEW

**Comment by wing328** [comment]
@sidhantgoyal please update the Android Volley Petstore sample by running `./bin/android-petstore-volley.sh` so that the CI can test the change.

**Comment by wing328** [comment]
Your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by sidhantgoyal** [comment]
@wing328 i have added the correct author info to the commits.

**Comment by wing328** [comment]
@sidhantgoyal ok. The commits are now correctly linked to your account.

For `connectionTimeout`, I think we need to set a default value. Given that `DEFAULT_TIMEOUT_MS` defaults to 2500ms, I think we should set the default value of `connectionTimeout` to 3.

**Comment by sidhantgoyal** [comment]
@wing328 The current default value of `connectionTimeout` is 30s [here](https://github.com/sidhantgoyal/swagger-codegen/blob/bd2b4c91279514f70e43ab062ca43d37960435a8/modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache#L185). This value is also being used as future timeout [also](https://github.com/sidhantgoyal/swagger-codegen/blob/bd2b4c91279514f70e43ab062ca43d37960435a8/modules/swagger-codegen/src/main/resources/android/libraries/volley/apiInvoker.mustache#L364). Should we change it to 3s ?

**Comment by wing328** [comment]
Thanks for pointing it out. Let's stick with the current value for the time being.

**Pull request merged**
