### PR TITLE
On Upgrade to Angular 7, get a tslint error for truthiness check

### PR DESCRIPTION
**Pull request by navneetkarnani**
Check these issues for a trail:
https://github.com/Microsoft/TypeScript/issues/26262
https://github.com/Microsoft/TypeScript/commit/14d3c69c722793c7a007d53081977410fb521aca

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

The Typescript 3.1 compiler (one that is used with Angular 7 onwards), has a check for void functions being checked for Truthiness. This change fixes the service function to have multiple return types if the HttpClient is being used, which is where the code gets generated.

### CODE REVIEW

**Comment by jcollard** [comment]
:+1: Resolve my issue.

**Comment by navneetkarnani** [comment]
Addresses: https://github.com/swagger-api/swagger-codegen/issues/8836

**Comment by navneetkarnani** [comment]
@roni-frantchi , since you are the creator of typescript-angular, please review. I don't see a reviewer for typescript on the technical committee

**Comment by navneetkarnani** [comment]
> Will the PR not create error when formParams is FormData type, for 'multipart/form-data'?
> 
> Since it forces the formParams to be HttpParams or void.

Changing recommendation to "any" instead of specific type to avoid having to specify all possible combinations ( and that I may not be aware of ).

**Comment by roni-frantchi** [comment]
@navneetkarnani using `any` would solve, but as you've mention, we lose type safety.
Here's another way to go at it, which I think will solve it: #9012 .
What do you think?.

**Comment by fireappsAdmin** [comment]
Is there any type of work around for this?

**Pull request closed without merging**
