### PR TITLE
[TypeScript]  All Clients Conform to same packaging scheme

### PR DESCRIPTION
**Pull request by kenisteward**
### PR checklist

- [X] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This updates all Typescript client generation to conform to one scheme.  Now The AbstractTypescriptClient handles setting up package info supporting files.

This is related to issue #2694 

Note: Not supplying npmName for any Typescript client no longer generates a default package.json with default name.  If the npmName is not present, no package information is generated.  This allows you just plop the client into an existing project.  If npmName is provided, it will generate the package information so that you can have the opportunity to publish your generated client publicly or privately with no hassle.

### CODE REVIEW

**Comment by kenisteward** [comment]
I'm not exactly sure how to fix this.  @wing328 let me know what I did wrong :x

**Comment by wing328** [comment]
@kenisteward thanks for the PR. `samples/client/petstore/typescript-angular/pom.xml` has been removed. Please add it back so that CIs can test the updated TS Pestore clients.

Also your commits (as shown in the Commits tab) are not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by kenisteward** [comment]
@wing328 Is it possible to update the CI?  I think it may be looking in the root folder but now it should be looking in the npm folder as I've updated it to be in line with the other package generators

**Comment by kenisteward** [comment]
@wing328 I've found the error and i'm going to push the correction now.  it was in the base pom.xml that I didn't update yet  how verify -Psamples runs correctly locally

**Comment by wing328** [comment]
@kenisteward is it correct to say that this is a breaking change? If yes, please file against `2.3.0` branch instead.

**Comment by kenisteward** [comment]
@wing328 This is only a breaking change for people who don't add npmName but expect to get packaging information.  Would you say that requires to be put as a breaking change in 2.3.0?  Technically all those clients would have to do is give a name and it wouldn't be a problem after.

**Comment by kenisteward** [comment]
@wing328  should I resubmit this for 2.2.3 or 2.3.0?

**Comment by kenisteward** [comment]
@wing let me know if I need to resubmit this on a different branch or if it can stay here and still be merged on 2.2.3.

**Comment by wing328** [comment]
@kenisteward sorry for late reply on this. I think it's fine to do it against the current master.

I wonder if you can rebase on the latest master to resolve the merge conflicts. Then I'll merge the enhancement into master.

**Comment by kenisteward** [comment]
@wing328 I will look to see if it will actually work but I'm assuming it won't this was the first in my efforts to make all of the languages conform to 1 typescript definition.  I'll try as soon as I can though.

Otherwise I had planned on working on #5104 which has a lot to do with this as well.

**Comment by wing328** [comment]
For https://github.com/swagger-api/swagger-codegen/issues/5104, I'll send you an email to discuss in more details.

**Comment by kenisteward** [comment]
Thanks  for closing this. Should we discuss more on this? I'm assuming the
combining to one is still wanted

**Comment by wing328** [comment]
Opened https://github.com/swagger-api/swagger-codegen/issues/7502 to continue the discussion.

**Pull request closed without merging**
