### PR TITLE
Add Closure annotated Javascript Angular generator

### PR DESCRIPTION
**Pull request by achew22**

### CODE REVIEW

**Comment by wing328** [comment]
@achew22 thanks for the PR. Here are some feedbacks/suggestions:

- create a shell script under `./bin/` to generate `javascript-closure-angular` for Petstore under `samples/client/petstore/javascript-closure-angular`
- add test cases for javascript-closure-angular petstore samples. You can refer to test cases in other programming languages under the petstore folder as a reference. A good starting point is to cover GET, POST (HTTP form, JSON model), DELETE.

**Comment by achew22** [comment]
Doing the first bullet revealed [something curious](https://github.com/swagger-api/swagger-codegen/commit/af6926bd6f092b3d34b1e7207feb6c15e3a652a2#diff-f71bccaed7f942fff0c9ba495d6e2c64R19). Do you have any idea why it it is trying to import java.util.List?

**Comment by wing328** [comment]
I think that's because you're using the default (Java) import mapping and would suggest you look at Go implementation for the imports: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java#L94

**Comment by wing328** [comment]
@achew22 if you need further assistance on the import mapping, please let me know.

**Comment by achew22** [comment]
Funny you should mention. I managed to get the imports working for the most part. However, I'm curious how I would tell it that "binary" should be a "Blob" object? Do you have any ideas on that?

**Comment by wing328** [comment]
Please set a typeMapping for `binary`, e.g.
    typeMapping.put("binary", "string");
(`binary` format is something we recently working on)

**Comment by wing328** [comment]
would also be nice if you can change the indention in `JavascriptClosureAngularClientCodegen.java` from 2-space to 4-space.

**Comment by wing328** [comment]
@achew22 are you still facing issue with `binary` and `Blob`?

**Comment by achew22** [comment]
Sorry this took me so long to get back to you. I was traveling all weekend (and again starting tomorrow). What do you think about this?

This outputs totally valid Closure compiler compatible Javascript. There are a few cleanup things that can be done that will make the output cleaner. There might even be a few tricks that can make it compile even smaller, but I won't know till I get down into the weeds and start using this in a project. In my purely synthetic tests this was pretty good, but there is always room for improvement.

I'm going to be using these in a project I'm working on so please expect a follow-up if I find anything I can improve.

**Comment by wing328** [comment]
@achew22 My recommendation is to release your current working version of `javascript-closure-angular` and document what you think can be improved so that the community can help on that as well.

**Comment by achew22** [comment]
Just for reference I believe this code is good to go. I don't explicitly know what kind of optimizations are going to be available without using it in a project for real so I don't think there is anything to document. Could you please take a look at the PR?

**Comment by wing328** [comment]
@achew22 thanks again for the contribution :beers: 

PR merged into master.

**Pull request merged**
