### PR TITLE
Removed wrong import of StrictJsonDeserializationVisitor

### PR DESCRIPTION
**Pull request by Gingonic**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

For the PHP Symfony generation this import

```php
use` Swagger\Server\Service\StrictJsonDeserializationVisitor;
```  
is wrong as the class is sitting in the same package as the JMSSerializer class.
This results in exception when the serializer is used

@jebentier  @dkarlovi  @mandrean  @jfastnacht  @ackintosh @naelrashdeen

### CODE REVIEW

**Comment by wing328** [comment]
@Gingonic thanks for the PR. Please run `./bin/php-symfony-petstore.sh` to update PHP Symfony Petstore sample.

**Comment by Gingonic** [comment]
@wing328  Sorry for that. Added the sample tests passing.

**Comment by Gingonic** [comment]
@wing328 I think this is ready. What are the next steps, will someone be assigned to this for review and merging?
Right now this bug makes the symfony bundle generator hardly unusable as you need to manually change the Serializer.
Note to whom ever has the same problem: you can generate once, fix the Serializer manually, then add the Serializer to the ignore list of the generator therefor letting it unchanged.

**Comment by wing328** [comment]
@Gingonic thanks for the PR, which has been merged into master.

**Pull request merged**
