### PR TITLE
Propsed fix for the ApiClient runtime crash

### PR DESCRIPTION
**Pull request by WendellDuncan**
### Description of the PR

This pull request is related to 
swagger-api/swagger-codegen cpprest runtime bug with form parameters
#6522 opened 18 minutes ago by WendellDuncan

### CODE REVIEW

**Comment by ravinikam** [comment]
looks good to me. @wing328 @stkrwork

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by bandrews-spirent** [comment]
@WendellDuncan Thanks for fixing this. I was having the same problem, and was about to submit a PR, but you beat me to it. :)
The problem is `cpprest` doesn't allow bodies in `GET` and `HEAD` requests. However, an empty `object` serializes to `{}` which is valid JSON, but not empty. 👍

**Comment by wing328** [comment]
FYI. I'll also cherry-pick the commit to current master.

**Pull request merged**
