### PR TITLE
[AspnetCore Server] Added Original swagger

### PR DESCRIPTION
**Pull request by knom**
Resolving issue #7159 
Adding the original swagger to the package.

@wing328 please review!
I followed your guidance..

Thanks.

### CODE REVIEW

**Comment by wing328** [comment]
@knom looks good to me. Will merge once the CI tests pass

cc @mandrean @jimschubert

**Comment by jimschubert** [comment]
Looks good, although, I don't know that there's a lot of value providing the static file or Swashbuckle option, unless it's configured as an option in the generator that conditionally includes Swashbuckle generation.

I would think a "sane default" of using Swashbuckle would be appropriate. We could then include the original in the .swagger directory with instructions in the README for those who prefer the static file. Reason is, this would be simpler the maintain than the inevitable options around dynamic or static specification.

**Comment by knom** [comment]
@wing328 do you know when any of the pull requests is going to show up on EDITOR.SWAGGER.IO?
They still use the old swagger-codegen version..

thx,

**Comment by knom** [comment]
@wing328?

**Pull request merged**
