### PR TITLE
[Typescript][Node] Fixes inccorect enum generation for enumsMap when Array<Enum> is defined

### PR DESCRIPTION
**Pull request by kenisteward**
…

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

When you have an array of enums defined:
```
swagger: "2.0"
info: 
  title: "Hello World API"
  version: "1.0"
paths: 
  /hello: 
    get: 
      parameters: 
        - 
          in: body
          name: myData
          schema: 
            properties: 
              myNumbersField: 
                items: 
                  enum: 
                    - foo
                    - bar
                  type: string
                type: array
      responses: 
        200: 
          description: "Returns the greeting."
```

 the generation gave you
```
let enumsMap = {
        "Array&ltMyData.MyNumbersFieldEnum&gt": Array&ltMyData.MyNumbersFieldEnum&gt,
}
```

now you properly get
```
let enumsMap = {
        "MyData.MyNumbersFieldEnum": MyData.MyNumbersFieldEnum,
}
```

@TiFu @taxpon @sebastianhaas @Vrolijkx @mhardorf

### CODE REVIEW

**Comment by kenisteward** [comment]
I've tested this on local and it can be merged once the checks pass.  Just hope there are no array of arrays lol.

**Comment by TiFu** [comment]
Do we actually need Array<Enum> in that map? From looking at the code I don't think we even need to put that into the map, because we check for starts with `Array<` before doing the enum check. (On mobile right now, will check more in depth later)

**Comment by kenisteward** [comment]
@TiFu this takes Array<Enum> out of that map.  it's not supposed to be in it.  In the enumsmap it should only be Enum: "Enum" and this fixes that.

**Comment by TiFu** [comment]
Ah I didn't see that you also removed it from the value saved in the map.
Looks good then.

Keni Steward <notifications@github.com> schrieb am Mo., 6. Nov. 2017 08:55:

**Comment by kenisteward** [comment]
@wing328 not sure how to fix this.  I remerged with master and still got the error. looks like it's with the java client but i'm not sure

**Comment by kenisteward** [comment]
@wing328 If possible I'd like to try to get this merged today however I'm not sure how to fix the circleci errors.

**Comment by TiFu** [comment]
`[ERROR] Failed to execute goal on project swagger-jaxrs-resteasy-server: Could not resolve dependencies for project io.swagger:swagger-jaxrs-resteasy-server:war:1.0.0: Could not transfer artifact org.jboss.resteasy:resteasy-jaxrs:jar:3.0.11.Final from/to central (https://repo.maven.apache.org/maven2): GET request of: org/jboss/resteasy/resteasy-jaxrs/3.0.11.Final/resteasy-jaxrs-3.0.11.Final.jar from central failed: Connection reset -> [Help 1]`

This looks like it had some issues connecting to maven central. Did you try restarting the CI (close PR, reopen PR)?

**Comment by kenisteward** [comment]
I didn't. I'll try that.

**Comment by kenisteward** [comment]
@TiFu thanks for the tip. I honestly had no clue how to get it to trigger without adding commits haha.

**Comment by wing328** [comment]
Let me look into it shortly (busy right now...)

**Comment by kenisteward** [comment]
@wing328 Take your time 👍

**Comment by wing328** [comment]
@kenisteward I've merged the PR into master (the travis failure was due to timeout)

**Comment by kenisteward** [comment]
@wing328 thanks!  Also when are snapshots normally published?

**Comment by wing328** [comment]
It relies on the Travis job. I'll spend some time tomorrow to switch the build image back to Linux (from MacOS). Please manually build it for the time being.

**Pull request merged**
