### PR TITLE
[JAVA] Update gradle and android build tools

### PR DESCRIPTION
**Pull request by auchri**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@auchri thanks for the PR. I wonder if you can updating the following build.gradle files as well:
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/android/build.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/android/libraries/volley/build.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/feign/build.gradle.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/jersey2/build.gradle.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/retrofit/build.gradle.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/retrofit2/build.gradle.mustache
https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/resources/Java/libraries/okhttp-gson/build.gradle.mustache

**Comment by wing328** [comment]
After updating the mustache templates, please run the following to update the Petstore samples so that CIs can verify the change:
```
./bin/java-petstore-all.sh
./bin/android-petstore-all.sh
```

**Comment by auchri** [comment]
I'll do the requested changes next week.

**Comment by auchri** [comment]
@wing328 I've updated the files you mentioned, but I can't update the samples (I'm using windows and the .sh scripts aren't executing in the [Windows Subsystem for Linux](https://msdn.microsoft.com/en-us/commandline/wsl/faq).

Also, there should be really a single place where the android version numbers are defined.

**Comment by wing328** [comment]
> Also, there should be really a single place where the android version
numbers are defined.

Very good suggestion. One way is to use {{androidVersionNumber}} mustache
tag so that we can change it in the generator more easily.

**Comment by auchri** [comment]
Yes, but that should be done in a seperate PR.

**Comment by wing328** [comment]
@auchri yup, I didn't mean you need to do it as part of this PR. 

I'll create a separate issue to track it.

Thanks for the contribution.

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Comment by wing328** [comment]
FYI. Created https://github.com/swagger-api/swagger-codegen/issues/5422 for tracking.

**Pull request merged**
