### PR TITLE
[Swift3] Set more liberal Swift3 decoder, behind lenientTypeCast option

### PR DESCRIPTION
**Pull request by rdalverny**
This adds a Swift3 option (`lenientTypeCast`) that, when set to true, generates a client JSON decoder that will accept and cast mistyped (by the server) values to their correct (expected by the client, per specification) type, as here:
 - String => Bool ("true" instead of true),
 - String => Int ("123" instead of 123),
 - NSNumber => String (123 instead of "123").

The point is to allow the same client code to handle several server implementations that may (sadly) not be up to spec, or still be "evolving".

Not a perfect/complete solution, not sure if it should be activated along other casts (I think each language/implementation handles this differently), so kept behind an option for Swift3 at this point.

See: #5746.

### CODE REVIEW

**Comment by jaz-ah** [comment]
+1 looks fine, unfortunate but glad it's off by default

**Comment by wing328** [comment]
The test result (after merging with master) is good: https://travis-ci.org/swagger-api/swagger-codegen/builds/240469935

@jaz-ah thanks for reviewing the change.

@rdalverny thanks for your contribution.

**Comment by rdalverny** [comment]
@jaz-ah @wing328 thanks to both of you!

**Comment by wing328** [comment]
@rdalverny I've sync'd the change into 2.3.0 (a branch with breaking changes) via https://github.com/swagger-api/swagger-codegen/commit/022eb0d379a057fd386e04deb16184f1b07302f8

Please help take a look to see if I resolved the merge conflict correctly: https://github.com/swagger-api/swagger-codegen/commit/022eb0d379a057fd386e04deb16184f1b07302f8#diff-940535e66d162a893df844fd9b6b45ffR143

**Comment by rdalverny** [comment]
@wing328 sorry for the delay. Looks good to me, although I'm not sure, as returned values are now wrapped in a .success/.failure (I can rewrite this if you like, as well as to match the same "if" style). I've got to try it.

**Pull request merged**
