### PR TITLE
Add apiNameSuffix config option

### PR DESCRIPTION
**Pull request by dcbroad3**
Add config option for Api Name Suffix. See issue #4028

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. Please fix the compilation errors
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/modules/swagger-codegen/src/main/java/io/swagger/codegen/config/CodegenConfigurator.java:[371,39] cannot find symbol
  symbol:   variable apiNameSuffix
  location: class io.swagger.codegen.config.CodegenConfigurator
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
```

**Comment by wing328** [comment]
@dcbroad3 do you need help fixing the compilation error? let us know.

**Comment by dcbroad3** [comment]
@wing328 I ended up writing a quick library in C# to do code generation for us, and uninstalled/deleted everything I had for swagger-codegen, sorry.

**Comment by Johanneke** [comment]
I still need this feature, if I can fix the compilation errors, what would be the best way to submit the code? A new PR?

**Comment by ndurette** [comment]
Is there a way to have this feature?
I saw modelNameSuffix additional property. To me, it looks like the same feature but for api.

**Comment by wing328** [comment]
@ndurette please open a new ticket (issue) to track it and provide more details.

**Pull request closed without merging**
