### PR TITLE
fix SpringMVCServerCodegen for maps as in JavaClientCodegen

### PR DESCRIPTION
**Pull request by TobiasPfeifer**
#952 SpringMVCServer can't handle maps with $ref

### CODE REVIEW

**Comment by xhh** [comment]
Hi @TobiasPfeifer. I can repeat issue and your PR does fix it. But It seems to introduce another syntax error for `StoreApi#getInventory` in the generated petstore spring-mvc code:

```
[INFO] -------------------------------------------------------------
[ERROR] /Users/xhh/builds/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java:[43,24] wrong number of type arguments; required 1
[ERROR] /Users/xhh/builds/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java:[36,128] cannot find symbol
  symbol:   variable String
  location: class io.swagger.api.StoreApi
[ERROR] /Users/xhh/builds/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java:[36,143] annotation values must be of the form 'name=value'
[ERROR] /Users/xhh/builds/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java:[46,32] wrong number of type arguments; required 1
```

The following is the code of `getInventory`:

```java
  @ApiOperation(value = "Returns pet inventories by status", notes = "Returns a map of status codes to quantities", response = String, Integer.class, responseContainer = "Map")
  @ApiResponses(value = { 
    @ApiResponse(code = 200, message = "successful operation") })
  @RequestMapping(value = "/inventory", 
    produces = { "application/json", "application/xml" }, 
    
    method = RequestMethod.GET)
  public ResponseEntity<String, Integer> getInventory()
      throws NotFoundException {
      // do some magic!
      return new ResponseEntity<String, Integer>(HttpStatus.OK);
  }
```

Could you try and verify it?
`getInventory` should return `Map<String, Integer>` as working in _samples/client/petstore/java/src/main/java/io/swagger/client/api/StoreApi.java_, it seems it needs to be fixed in spring-mvc server codegen as well.

**Comment by webron** [comment]
@TobiasPfeifer - did you get a chance to look into it? We're looking to release a new version and would love to be able to merge this PR in.

@dilipkrish - would be great if you can have a look into this issue too.

**Comment by dilipkrish** [comment]
I'll take a look and report back

**Comment by fehguy** [comment]
I've merged this--the code generated makes sense.  I do think it exposes a potential issue in springfox with the response type of Map.

I'll open a tracking issue for this.

**Pull request merged**
