### PR TITLE
[csharp] date proper format

### PR DESCRIPTION
**Pull request by jimschubert**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Per spec (https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types), DateTime instances defined as 'date' datatype need to be serialized as defined by full-date - RFC3339, which has the format:

```
full-date       = date-fullyear "-" date-month "-" date-mday
```

ref: https://xml2rfc.tools.ietf.org/public/rfc/html/rfc3339.html#anchor14

I've also added a unit test to FormatTestTests.cs which verifies the date-only format when serialized to JSON. I believe this test runs as part of CI, but it can be run manually with:

```
cd samples/client/petstore/csharp/SwaggerClient
sh mono_nunit_test.sh
```

When I run this locally, I have two failing tests but they're related to FindPetsByStatusTest and FindPetsByTagsTest neither of which are touched by this change (Pet, Tag, Category don't have any `date` properties, either).

see #5513
see #5531

### CODE REVIEW

**Comment by jimschubert** [comment]
@wing328 per convo in linked issue, while this is a bug in general in that we're not properly handling "date" in most (all?) generators, this is a pretty big breaking change. I opened against master, but this may be more appropriate against the 2.3.0 branch because of the client+server impact of the change for existing consumers.

**Comment by wing328** [comment]
I know some generators already have it fixed or worked around but totally agree with you that we need to review all the other generators to have the issue covered.

To me, it's ok for this fix to get into master as this is correcting the incorrect behaviour/handling of 'date'

**Comment by wing328** [comment]
FYI. Fixed minor warning due to missing XML doc via 4fd52d1

**Comment by jimschubert** [comment]
@wing328 thanks for the heads up. oddly, I'm not getting warnings about missing pubic XML docs. I'll have to see if I have a global setting somehow that is preventing those warnings, so you don't have to keep fixing them ☘️

**Pull request merged**
