### PR TITLE
[html2] curl example always shows 'apiKey' header parameter.

### PR DESCRIPTION
**Pull request by adonishi**
[html2] [htmlDoc2]
see #3560

### CODE REVIEW

**Comment by wing328** [comment]
@adonishi thanks for the contribution :)

cc @jhitchcock

**Comment by wing328** [comment]
@adonishi  Thanks for the contribution. For your upcoming PRs, I would recommend creating a new branch (e.g. `git checkout -b fix_abc`)

**Comment by adonishi** [comment]
alright, use new branch in next.
by the way html2 is awesome!

**Comment by jhitchcock** [comment]
Ah good spot @adonishi I had left something custom in there, Thanks for the update! :) 

I think we can also remove apiSecret, I'll do that in my next PR

**Pull request merged**
