### PR TITLE
[Java] Play! Framework 2.4 WS client support + retrofit2

### PR DESCRIPTION
**Pull request by lukoyanov**
Reopened PR with rewritten history

### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

I've implemented core integration with play 2.4 async http client and api key auth logic.

### CODE REVIEW

**Comment by wing328** [comment]
@lukoyanov thanks for the PR. Would you please create another Petstore sample by creating a shell script under `./bin/` (e.g. similar to [java-petstore-feign.sh](https://github.com/swagger-api/swagger-codegen/blob/master/bin/java-petstore-feign.sh)) so that we can test the sample output?

**Comment by lukoyanov** [comment]
@wing328 sure, added a script + config file.

**Comment by wing328** [comment]
Thanks. cc @cbornet, who is our Java expert to take a look.

**Comment by lukoyanov** [comment]
I've changed return type to Promise<Response<T>> to allow access to status code and raw response if needed.

**Comment by lukoyanov** [comment]
@cbornet please advice what else should be done.

**Comment by wing328** [comment]
@lukoyanov I'll take another look later today and let you know if I've any question.

**Comment by wing328** [comment]
@lukoyanov I got the following errors when running `mvn test` under `samples/client/petstore/java/retrofit2-play24`:
```
Tests in error: 
  testClientModelTest(io.swagger.client.api.FakeApiTest): play/libs/Json : Unsupported major.minor version 52.0
  testEndpointParametersTest(io.swagger.client.api.FakeApiTest): play/libs/Json
  testEnumParametersTest(io.swagger.client.api.FakeApiTest): play/libs/Json
  uploadFileTest(io.swagger.client.api.PetApiTest): play/libs/Json : Unsupported major.minor version 52.0
  deletePetTest(io.swagger.client.api.PetApiTest): play/libs/Json
  getPetByIdTest(io.swagger.client.api.PetApiTest): play/libs/Json
  findPetsByStatusTest(io.swagger.client.api.PetApiTest): play/libs/Json
  addPetTest(io.swagger.client.api.PetApiTest): play/libs/Json
  findPetsByTagsTest(io.swagger.client.api.PetApiTest): play/libs/Json
  updatePetWithFormTest(io.swagger.client.api.PetApiTest): play/libs/Json
  updatePetTest(io.swagger.client.api.PetApiTest): play/libs/Json
  placeOrderTest(io.swagger.client.api.StoreApiTest): play/libs/Json : Unsupported major.minor version 52.0
  deleteOrderTest(io.swagger.client.api.StoreApiTest): play/libs/Json
  getInventoryTest(io.swagger.client.api.StoreApiTest): play/libs/Json
  getOrderByIdTest(io.swagger.client.api.StoreApiTest): play/libs/Json
  loginUserTest(io.swagger.client.api.UserApiTest): play/libs/Json : Unsupported major.minor version 52.0
  createUsersWithArrayInputTest(io.swagger.client.api.UserApiTest): play/libs/Json
  updateUserTest(io.swagger.client.api.UserApiTest): play/libs/Json
  logoutUserTest(io.swagger.client.api.UserApiTest): play/libs/Json
  getUserByNameTest(io.swagger.client.api.UserApiTest): play/libs/Json
  createUserTest(io.swagger.client.api.UserApiTest): play/libs/Json
  createUsersWithListInputTest(io.swagger.client.api.UserApiTest): play/libs/Json
  deleteUserTest(io.swagger.client.api.UserApiTest): play/libs/Json

Tests run: 23, Failures: 0, Errors: 23, Skipped: 0
```
Did you get similar errors in your local environment?

After I ran `mvn clean && ./bin/java-petstore-retrofit2-play24.sh` and then `mvn test` again under `samples/client/petstore/java/retrofit2-play24`, I got the following compilation error instead:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-java-client: Compilation failure: Compilation failure:
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java:[144,8] possible loss of precision
[ERROR] required: long
[ERROR] found:    double
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java:[145,8] possible loss of precision
[ERROR] required: long
[ERROR] found:    double
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java:[166,8] possible loss of precision
[ERROR] required: long
[ERROR] found:    double
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java:[167,8] possible loss of precision
[ERROR] required: long
[ERROR] found:    double
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java:[188,8] possible loss of precision
[ERROR] required: long
[ERROR] found:    double
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/retrofit2-play24/src/main/java/io/swagger/client/model/FormatTest.java:[189,8] possible loss of precision
[ERROR] required: long
[ERROR] found:    double
```

Please take a look and let us know if you need help fixing these errors.

**Comment by lukoyanov** [comment]
@wing328 I've tried to reproduce that running both jdk7 and jdk8. On every jdk mvn test competes successfully. 

```
23:34:41 lukoyanov@qplace retrofit2-play24 feature/play24ws-retrofit ? java -version
java version "1.7.0_80"

....

23:37:38 lukoyanov@qplace retrofit2-play24 feature/play24ws-retrofit ? java -version
java version "1.8.0_112"
```

**Comment by lukoyanov** [comment]
After merge with upstream I can reproduce that.

**Comment by lukoyanov** [comment]
It seems that some extra bean validation was introduced recently. And for bigdecimal (and some other types) codegen produces incorrect \@Min and \@Max annotations since value parameter has type long not double.

```
...
  @Min(32.1)
  @Max(543.2)
  @ApiModelProperty(example = "null", required = true, value = "")
  public BigDecimal getNumber() { return number; }
...
```

From javax.validation:
```
public @interface Min {
    String message() default "{javax.validation.constraints.Min.message}";
...
    long value();

```

**Comment by wing328** [comment]
Looks like @Min, @Max can only be applied to long/int only. I'll submit a separate PR to fix this particular issue.

**Comment by wing328** [comment]
Submitted https://github.com/swagger-api/swagger-codegen/pull/4395 for conditional @Min @Max check

**Pull request merged**
