### PR TITLE
[Python ]set 'None' to body for request if given body is 'None' ( issue #3020 )

### PR DESCRIPTION
**Pull request by taxpon**
PR for Issue #3020

### CODE REVIEW

**Comment by taxpon** [comment]
Changes except for `rest.mustach` and `rest.py` are not my contributions, but when I ran `mvn clean && bin/python-petstore.sh` command, those change are made.

**Comment by wing328** [comment]
The test result for Python looks good:
```
OK
____________________________________________________________________________________________________ summary _____________________________________________________________________________________________________
  py27: commands succeeded
  py34: commands succeeded
  congratulations :)
```
cc @scottrw93

**Comment by scottrw93** [comment]
Looks good to me

**Comment by wing328** [comment]
@scottrw93 thanks for the review. 

@taxpon thanks for the PR.

PR merged.

**Pull request merged**
