### PR TITLE
Fix for #3712 - invalid enum array validation in Python client mustache model

### PR DESCRIPTION
**Pull request by bkryza**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

A simple fix for issue #3712.

The Python client `model.mustache` template now properly validates arrays of strings which are `enum` types.

### CODE REVIEW

**Comment by wing328** [comment]
@bkryza thanks for the PR. Please run ./bin/python-petstore.sh to update the Petstore sample so that the CIs will test the change.

cc @scottrw93

**Comment by bkryza** [comment]
@wing328 Done.

**Comment by wing328** [comment]
@bkryza for `modules/swagger-codegen/src/test/resources/2_0/array-enum.yaml`, we already have test cases to cover array of enum in https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/test/resources/2_0/petstore-with-fake-endpoints-models-for-testing.yaml#L1210

If it's not sufficient, I suggest we update `petstore-with-fake-endpoints-models-for-testing.yaml` instead.

**Comment by bkryza** [comment]
@wing328 I agree that the test you mention should be sufficient - the question is why this wasn't caught by CI - are you sure this method is actually executed during tests: 

https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/python/petstore_api/models/enum_arrays.py#L99

**Comment by wing328** [comment]
@bkryza I think the reason is that there's no test cases to cover it. It would be nice if you can add a test case under https://github.com/swagger-api/swagger-codegen/tree/master/samples/client/petstore/python/tests to cover the issue moving forward.

**Comment by bkryza** [comment]
@wing328 Ok, I'll do that.

**Comment by bkryza** [comment]
@wing328 I've added test cases for `EnumArrays`, I've also noticed that my PR affects map properties whose keys have an enum constraint, for instance in case of `MapTest` model, so I've extended my PR to cover that and also added a test for that.

**Comment by wing328** [comment]
@bkryza thanks for adding the test cases. PR merged into master.

**Pull request merged**
