### PR TITLE
Nancy fx work

### PR DESCRIPTION
**Pull request by simo9000**
### PR checklist

- [X] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

Resubmitting changes from #4061 cleaned up and on a separate branch

### CODE REVIEW

**Comment by simo9000** [comment]
@mstefaniuk @jimschubert please submit feedback if you have any as @wing328 indicated in #4061

**Comment by wing328** [comment]
### Description of the PR

Changed nancyfx template to convert collections to arrays prior to returning from the path delegates. This makes no difference when the request is for json or xml, however if the request is for html, the Nancy response negotiator can't look up view names based with generic collections. Converting the collection to an array prior to returning control to nancy work will allow the view to be discovered by "<TypeName>[]".

**Comment by mstefaniuk** [comment]
@simo9000 @wing328 In my opinion it's very good change.
@jakubmalek Any remarks?

**Comment by wing328** [comment]
@mstefaniuk thanks for the review.

@simo9000 thanks for the PR, which has been merged into master.

**Pull request merged**
