### PR TITLE
Fix Java Play server generator when path variables aren't camelCase

### LINKED ISSUE #6085: Java Play server generator fails if path variables aren't camelCase
The Java Play codegen is generating the following `routes`, which do not compile:

```
GET     /4Platform/consumption/v1/phone_numbers/:phone_number/data_reports                     controllers.RecipeApiController.getDataConsumption(phoneNumber: String)
```

This is because the varaible in the path is refered as `phone_number` but it is refered as `phoneNumber` in the method call.

### PR DESCRIPTION
**Pull request by edrevo**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fixes #6085

### CODE REVIEW

**Comment by edrevo** [comment]
The `bin` scripts weren't run because the only change they cause is that they add a `@Generated` annotation with the current date and that change is unrelated to this PR

**Comment by edrevo** [comment]
The Travis failure looks unrelated to the changes in the PR, as far as I can tell. Please do let me know if you think otherwise.

**Comment by wing328** [comment]
@edrevo thanks for the PR.

cc @JFCote

**Comment by JFCote** [comment]
@edrevo Thanks for the PR ! Seems good to me. Nice catch!
@wing328 : You can merge!

**Comment by wing328** [comment]
@JFCote thanks for the review.

@edrevo thanks for contributing the fix, which has been merged into master.

**Pull request merged**
