### PR TITLE
[Java] Basic bean-validation of @NotNull, @Size, @Pattern, @Min, @Max #2549

### PR DESCRIPTION
**Pull request by jfiala**
This is the rebased basic implementation of Java Bean-Validation-Annotations.

### CODE REVIEW

**Comment by wing328** [comment]
@jfiala  I left you some comments in https://github.com/jfiala/swagger-codegen/commit/08b3b53f0ccaddaa177c242ba7fde0e0a64f3f36

**Comment by jfiala** [comment]
@wing328 optimized mustache templates & fixed tabs (for java + cxf)

**Comment by jfiala** [comment]
@wing328 pls advise how we should best test this? or do you prefer moving the whole beanvalidation-annotation-part into a separate mustache file and then testing separately (as it matters for all java clients)?

**Comment by brentryan** [comment]
What's the status here?  This validation component is the 1 last thing holding us back from using swagger over jsonschema2pojo plugin? Anything I can do to help out here?

**Comment by wing328** [comment]
I'll try to merge this manually tomorrow with the following additional changes
- replace tab with 4-space in java files
- remove comments about TODO and create tasks (issues) in Github for tracking instead.
- target 2.3.0 instead as there're lots of changes.

**Comment by jfiala** [comment]
Thank you, I fixed the tabs in the CXF branch (jaxrs_cxf_2017), so everything is already clean there (the branch jaxrs_cxf_2017 contains all the changes of beanvalidation_2549 + the cxf changes).

However, if you're able to merge the branch beanvalidation_2549 more quickly feel free to do so.

Regarding the TODO: I can cleanup this as well, there should be two follow-ups:
* Rework all Java languages to support beanvalidation (reusing the centralized beanValidation.mustache file).

* Improve server CXF language:
** Adapt server CXF to add spring using a cli-option only
** Add additional switches for CXF features (gzip/beanvalidation/logging/swagger)

If you're green with that, I'll create two issues and remove the TODO comment in JavaCXFServerCodegen.

**Comment by jfiala** [comment]
@wing328: I rebased the branch jaxrs_cxf_2017, please pull the changes from there.

**Comment by jfiala** [comment]
These changes have already pulled in via #4003

**Pull request closed without merging**
