### PR TITLE
Added @RequestBody annotation in order for the generated code to

### PR DESCRIPTION
**Pull request by rostskadat**
properly create API Model object.

@RequestBody Annotation Ref:
http://docs.spring.io/spring/docs/current/spring-framework-reference/html/mvc.html#mvc-ann-requestbody

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR. Do you mind running `./bin/spring-mvc-petstore-server.sh` to update the petstore sample for springmvc?

**Comment by rostskadat** [comment]
OK

I followed your suggestions:
- I created a branch called springmvc_request_body_1532
- I created the pull request, which triggered the build https://travis-ci.org/swagger-api/swagger-codegen/builds/89954240
- I ran the ./bin/spring-mvc-petstore-server.sh

I'm not really sure what to do then. Should I commit the /swagger-codegen/samples/server/petstore/spring-mvc?

/Julien

**Comment by wing328** [comment]
Please do a `git commit -a` again as you've updated some files.

**Comment by rostskadat** [comment]
OK

I did the commit.

Now the @RequestBody annotation appears correctly in the generated /swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java:updatePet() method signature.

Is there anything else to be done on my part?

/Julien

**Comment by wing328** [comment]
@rostskadat thanks again for the PR.

**Comment by wing328** [comment]
Fixed #1532

**Pull request merged**
