### PR TITLE
[C#] fix the location of FodyWeavers.xml

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

- fix the location of FodyWeavers.xml
- minor template change for better code format

Tested with 
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
   -i http://petstore.swagger.io/v2/swagger.json \
   -l csharp \
   -o /var/tmp/csharp/generatePropertyChanged/ --additional-properties=generatePropertyChanged=true
```

### CODE REVIEW

**Comment by jimschubert** [comment]
@wing328 how are you building this? The XML is supposed to be in the project root, so I'm not sure what's being fixed here.

**Comment by wing328** [comment]
I did another test to confirm it's working for me (Mac, Xamarin 5.x).

The PR aims to address this particular issue: https://github.com/swagger-api/swagger-codegen/pull/3547#issuecomment-239378743

Does it work for you if you use the latest master to generate C# API client with `generatePropertyChanged` switched on?

**Comment by jimschubert** [comment]
@wing328 thanks. I'll check this when I get a chance. My new baby was born on September 2, so it's been hectic at home.

Did you update Project.mustache? I'm on mobile which sometimes doesn't show all affected files.

**Comment by wing328** [comment]
Congratulations to your new born 👏 👏 👏 

I didn't update project.mustachte, which is referring to the xml file in the project root directory (not the solution root directory).

I'll ask others to give it a try as well so don't worry about it. 

(I'll also setup CI for this)

**Comment by wing328** [comment]
Updated CI with https://github.com/swagger-api/swagger-codegen/pull/3796 to cover C# API client with "PropertyChanged"

**Pull request merged**
