### PR TITLE
add tags with API name to java @Api annotation

### PR DESCRIPTION
**Pull request by thebignet**

### CODE REVIEW

**Comment by wing328** [comment]
@thebignet thanks for the PR on spring mvc and spring boot generator. I've just merged https://github.com/swagger-api/swagger-codegen/pull/3133 into master.

Please pull the latest master and rebase the change accordingly.

**Comment by cbornet** [comment]
I think it would be better to tag the operations with ```tags={ {{#vendorExtensions.x-tags}}"{{tag}}",{{/vendorExtensions.x-tags}}``` like what is done in jax-rs jersey template

**Comment by thebignet** [comment]
Tried it out on swagger-ui and got even better results

**Comment by cbornet** [comment]
:+1:

**Comment by wing328** [comment]
@thebignet thanks for the PR. Next time, please also update the Petstore sample.

**Pull request merged**
