### PR TITLE
[BUG] [CRITICAL] [PHP] Symfony server incorrect validation: min contstraint in max condition

### PR DESCRIPTION
**Pull request by 4n70w4**
fix LessThan & LessThanOrEqual conditions

@dkarlovi @mandrean

### CODE REVIEW

**Comment by 4n70w4** [comment]
any news?

**Comment by frantuma** [comment]
please build

**Comment by 4n70w4** [comment]
@frantuma Do you expect something from me?

**Comment by HugoMario** [comment]
Hey @4n70w4, sorry for confuse, @frantuma sometimes act like a bot :)

**Comment by HugoMario** [comment]
thanks a lot for PR btw!!!

**Pull request merged**
