### PR TITLE
Adding import for Foundation.h to SWGQueryParamCollection.h

### PR DESCRIPTION
**Pull request by hyeghiazaryan**
fix for https://github.com/swagger-api/swagger-codegen/issues/636

### CODE REVIEW

**Comment by fehguy** [comment]
I can add this, but isn't this something typically in the *.pch files?

**Comment by geekerzp** [comment]
I think we should add `#import <Foundation/Foundation.h>` in the *.h files.
When we inherit the `NSObject`, we should import the Foundation.h explicitly in the head file.
Also see https://github.com/swagger-api/swagger-codegen/blob/develop_2.0/modules/swagger-codegen/src/main/resources/objc/SWGApiClient.h#L1

**Comment by hyeghiazaryan** [comment]
@fehguy

This import is usually added to .h files, you can see this import in SWGApiClient.h, SWGDate.h, SWGGile.h, SWGObject.h.
Only SWGQyeryParamCOllection.h does not have it.

**Comment by fehguy** [comment]
done, thanks.

**Pull request merged**
