### PR TITLE
updated versions for release

### PR DESCRIPTION
**Pull request by fehguy**
Prepare for the 2.2.3 final release

### CODE REVIEW

**Comment by fehguy** [comment]
@wing328 looks like there are some real errors in the swift client.  I'm not expert in Swift, but looking at the error messages (go to end of this: https://travis-ci.org/swagger-api/swagger-codegen/builds/253768667?utm_source=github_status&utm_medium=notification) I'm guessing something isn't set up correctly.  The errors are coming from Alamo Fire not our project, and they're basic syntax issues.  Perhaps the Swift setup isn't correct here?  https://github.com/swagger-api/swagger-codegen/blob/master/.travis.objc_swift_test.yml

Ping @tkqubo @hexelon @ehyche if you have any thoughts on this please share!

**Comment by ehyche** [comment]
@fehguy : Is the CI build using Xcode 9? This will not compile using Xcode 8.

**Comment by fehguy** [comment]
Thanks, trying now

**Comment by wing328** [comment]
.travis.objc_swift_test.yml is no longer being used as .travis.yml already covers tests for Swift 2.x and 3.x (4.x is not yet setup)

I'll look into the CI error.

**Comment by wing328** [comment]
Travis CI tests passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/253843201

Still working on the CircleCI failure.

**Comment by wing328** [comment]
For reference, CircleCI test failure is as follows:
```
[ERROR] The build could not read 4 projects -> [Help 1]
[ERROR]   
[ERROR]   The project io.swagger:swagger-codegen:[unknown-version] (/home/ubuntu/swagger-codegen/modules/swagger-codegen/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find io.swagger:swagger-codegen-project:pom:2.2.3 in https://oss.sonatype.org/content/repositories/snapshots was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-snapshots has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project io.swagger:swagger-codegen-cli:[unknown-version] (/home/ubuntu/swagger-codegen/modules/swagger-codegen-cli/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find io.swagger:swagger-codegen-project:pom:2.2.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 3, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project io.swagger:swagger-codegen-maven-plugin:[unknown-version] (/home/ubuntu/swagger-codegen/modules/swagger-codegen-maven-plugin/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find io.swagger:swagger-codegen-project:pom:2.2.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 6, column 13 -> [Help 2]
[ERROR]   
[ERROR]   The project io.swagger:swagger-generator:[unknown-version] (/home/ubuntu/swagger-codegen/modules/swagger-generator/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Failure to find io.swagger:swagger-codegen-project:pom:2.2.3 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 4, column 13 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```
Trying to fix it with skipping cache, upgrading maven, etc

**Comment by wing328** [comment]
Closed via https://github.com/swagger-api/swagger-codegen/pull/6070 with cleaner commit history

**Pull request closed without merging**
