### PR TITLE
[Java] To fix missing imports in inline models

### LINKED ISSUE #1804: [java] missing import java.util.Objects
From Latest 2.1.5-SNAPSHOT

I have a this json schema snippet

    "definitions" : {
      "PointInTimeGroup" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "string",
            "format" : "uuid",
            "readOnly" : true
          },
          "pointInTime" : {
            "type" : "string",
            "readOnly" : true
          },
          "values" : {
            "type" : "array",
            "readOnly" : true,
            "items" : {
              "type" : "object"
            }
          }
        }
      },

which generate this class PointInTimeGroupValues

with this hash() method

    @Override
    public int hashCode() {
      return Objects.hash();
    }

However the class does not have the required 'import  java.util.*'

### PR DESCRIPTION
**Pull request by wing328**
To fix #1804

### CODE REVIEW

**Comment by dantran** [comment]
Please push a maven snapshot :-)

**Comment by wing328** [comment]
Likely there will be a release (2.1.5) later this week.

**Comment by dantran** [comment]
@Wing328 very nice

**Comment by dantran** [comment]
@wing328  Just built latest master and integrated with my local build. Still see the same issue. not sure what I miss

**Comment by wing328** [comment]
At line 3 of the model file, do you see the following line in the template and generated file?
```
import java.util.Objects;
```

**Comment by dantran** [comment]
@wing328 , No I dont see that line.

Just to be sure, I wipe out the source, clone, and build again locally. Still see the same issue

**Comment by wing328** [comment]
I pull the latest swagger-codegen in a tmp directory and generated the Java petstore sample. I can see `import java.util.Objects;` at line 3. Here is the screenshot:

screen shot 2016-01-05 at 12 28 24 pm

**Comment by dantran** [comment]
keep in mine, my snippet is a special case.  It works on other  nomal POJO generation
here is my generated code

    package com.mycom.client.model.media;
    
    
    
    
    
    
    @javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-01-04T20:03:35.843-08:00")
    public class PointInTimeGroupValues   {
      
    
      
    
      @Override
      public boolean equals(Object o) {
        if (this == o) {
          return true;
        }
        if (o == null || getClass() != o.getClass()) {
          return false;
        }
        PointInTimeGroupValues pointInTimeGroupValues = (PointInTimeGroupValues) o;
        return true;
      }
    
      @Override
      public int hashCode() {
        return Objects.hash();
      }
    
      @Override
      public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PointInTimeGroupValues {\n");
        
        sb.append("}");
        return sb.toString();
      }
    
      /**
       * Convert the given object to string with each line indented by 4 spaces
       * (except the first line).
       */
      private String toIndentedString(Object o) {
        if (o == null) {
          return "null";
        }
        return o.toString().replace("\n", "\n    ");
      }
    }

**Comment by wing328** [comment]
In the file `modules/swagger-codegen/src/main/resources/Java/model.mustache`, do you see `import java.util.Objects;` at line 3 ?
```
Java|master⚡ ⇒ cat model.mustache 
package {{package}};

import java.util.Objects;
{{#imports}}import {{import}};
{{/imports}}

{{#serializableModel}}import java.io.Serializable;{{/serializableModel}}
{{#models}}
{{#model}}{{#description}}
/**
 * {{description}}
 **/{{/description}}
{{#isEnum}}{{>enumOuterClass}}{{/isEnum}}
{{^isEnum}}{{>pojo}}{{/isEnum}}
{{/model}}
{{/models}}
```

**Comment by dantran** [comment]
Yes I see it

**Comment by wing328** [comment]
I think I know why. Some Jave HTTP libraries have their own model.mustache. I'll submit a PR to update those as well. Sorry for the oversight.

**Comment by wing328** [comment]
Submitted https://github.com/swagger-api/swagger-codegen/pull/1814 to apply the same fix to the remaining Java template with HTTP libraries

**Comment by wing328** [comment]
#1814 merged into master. Please kindly pull the latest and give it another try.
(I'll submit another PR to update model.mustache in Java server template - jaxrs, inflector)

**Comment by dantran** [comment]
sorry, still not working :(

**Comment by wing328** [comment]
Can you share the full spec with me and which Jave API client template (e.g. retrofit, okhttp-gson, jersey2) you used to generate the API client?

You can find my personal email address in my github profile page.

**Comment by dantran** [comment]
Sent and many thanks

**Comment by wing328** [comment]
Got it. What command did you use to generate the Java API client ?

**Comment by dantran** [comment]
I am using maven plugin, here is the settings

      <plugin>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-codegen-maven-plugin</artifactId>
        <version>2.1.5-SNAPSHOT</version>
        <configuration>
          <language>java</language>
          <addCompileSourceRoot>false</addCompileSourceRoot>
          <configOptions>
            <sourceFolder>java</sourceFolder>
          </configOptions>
        </configuration>
        <executions>
          <execution>
            <id>configmgr</id>
            <phase>generate-sources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
            <configuration>
              <modelPackage>${model.root}.xxxx</modelPackage>
              <inputSpec>${project.build.directory}/apidoc/xxxx.json</inputSpec>
            </configuration>
          </execution>
          ....
      </executions>
   </plugin>

**Comment by wing328** [comment]
I couldn't repeat the issue and here is part of the model file, which is compiling fine:
```
package io.swagger.client.model;

import java.util.Objects;





@javax.annotation.Generated(value = "class io.swagger.codegen.languages.JavaClientCodegen", date = "2016-01-05T15:38:53.574+08:00")
public class PointInTimeGroupValues   {




  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PointInTimeGroupValues pointInTimeGroupValues = (PointInTimeGroupValues) o;
    return true;
  }
```
I noticed that you're using the snapshot of swagger-codegen. Have you run `mvn clean install -U` to update the build locally ?

**Comment by dantran** [comment]
Right on.   I rebuilt swagger-codegen with '-U', my generated java client is now happy. Thanks
Could you push a snapshot to sonatype? So that I can use with my production build ( yes, I am working on the edge)

**Comment by wing328** [comment]
We'll push one later this week for an official release of 2.1.5.

**Comment by wing328** [comment]
@dantran FYI. 2.1.5 has just been released.

**Comment by dantran** [comment]
@wing328 very much appreciated

**Pull request merged**
