### PR TITLE
[JaxRS-CXF][bug #4330] support containers in return types

### PR DESCRIPTION
**Pull request by MatanRubin**
before this commit if a method returned a container (List or Map) of
THING (i.e. List\<THING\> or Map<String, THING>) the generated return type would
drop the container and only leave THING.
this commit fixes this issue such that the container type is properly
generated.

I verified this change by generating JAXRS-CXF code using the following swagger definition:
```yaml
---
swagger: "2.0"
info:
  version: "1.0.2"
host: "localhost:8080"
basePath: "/api"
schemes:
- "http"
paths:
  /list:
    get:
      summary: "List Books"
      description: ""
      operationId: "listBooks"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Book"
  /book:
    get:
      summary: "get a book"
      description: ""
      operationId: "getBook"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Book"
  /void:
    get:
      summary: "Returns void"
      description: ""
      operationId: "voidBooks"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /map:
    get:
      summary: "Map of Books"
      description: ""
      operationId: "mapBooks"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              $ref: "#/definitions/Book"
definitions:
  Book:
    type: "object"
    properties:
      Author:
        type: "string"
      Length:
        type: "integer"
```

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by MatanRubin** [comment]
Thanks @wing328, turns out I was using an old gitconfig file on this computer.
I amended the commits and force pushed into the same branch. I also rebased it on master.
Does it look OK now?

**Comment by wing328** [comment]
@MatanRubin yes, it's now correctly linked to your accounts.

**Comment by wing328** [comment]
@MatanRubin thanks for the PR, which has been merged into master.

**Comment by wing328** [comment]
(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Pull request merged**
