### PR TITLE
fix(ts-fetch): preserve available headers

### PR DESCRIPTION
**Pull request by paibamboo**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
@paibamboo thanks for the PR. Can you please elaborate on the issue you're trying to fix?

Please also run `./bin/typescript-fetch-petstore-all.sh` to update TS Fetch Petstore samples.

cc @Vrolijkx @taxpon @TiFu @leonyu

**Comment by paibamboo** [comment]
Sorry, I was in a hurry, current fetch doesn't use the option parameters if header parameter don't exist so there's no way of passing in headers(from options) while calling the api. Instead of overwriting the object, we just do a object.assign and add to the current headers (otherwise headers will be lost)

**Comment by TiFu** [comment]
[Line 118](https://github.com/paibamboo/swagger-codegen/blob/077b052b24534b986d45c958dfeee8ec9244dcb8/modules/swagger-codegen/src/main/resources/TypeScript-Fetch/api.mustache#L118) seems to have the same issue. 
Would you mind implementing the same changes for this case as well?

**Comment by wing328** [comment]
@paibamboo may I know if you've a chance to review the feedback by @TiFu ?

**Comment by paibamboo** [comment]
Sorry for the delay. I've edited accordingly.

**Comment by wing328** [comment]
Tests with updated TS Fetch samples passed via https://travis-ci.org/swagger-api/swagger-codegen/builds/248240181

**Comment by wing328** [comment]
@paibamboo thanks for the fix, which has been merged into master.

**Pull request merged**
