### PR TITLE
Issue 2084

### PR DESCRIPTION
**Pull request by Glagnar**
Better follow Swift code style for naming of parameters and variables.

### CODE REVIEW

**Comment by Glagnar** [comment]
There are issues. Further testing needed.

**Comment by Glagnar** [comment]
@wing328 I am also bothered by issue 2181, so I will have a further look to see if I can fix that issue as well first.

**Comment by wing328** [comment]
OK. Please reply to #2181 if you need further assistance on fixing the issue.

I would also recommend pulling the latest before starting your work (or you can rebase later).

**Comment by Glagnar** [comment]
So, reopened this pull request, and will submit another to fix 2181.

**Pull request merged**
