### PR TITLE
Ensure that `ApiInvoker.scala` can support `UUID` types

### PR DESCRIPTION
**Pull request by log0ymxm**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Add an escape method for handling UUIDs in generated scala client code.

### CODE REVIEW

**Comment by log0ymxm** [comment]
This fixes #4806

**Comment by wing328** [comment]
@log0ymxm thanks for the PR, which has been merged into master.

FYI. After the 2.2.2 release, we plan to [merge](https://github.com/swagger-api/swagger-codegen/issues/3812) "async-scala" into the "scala" client (which means one single "scala" API client to support both async and sync HTTP calls)

(If your company is using Swagger Codegen, please consider adding your company name to [this list](https://github.com/swagger-api/swagger-codegen#companiesprojects-using-swagger-codegen))

**Comment by wing328** [comment]
Btw, for your upcoming PRs, I would recommend creating a new branch for the change as per git best practice.

**Comment by log0ymxm** [comment]
Yeah, my mistake. I noticed that guideline after already submitting the PR. I'll do that in the future. Thanks for accepting the PR.

**Comment by wing328** [comment]
@log0ymxm np. Your PR (with updated petstore sample) is good 👍

**Pull request merged**
