### PR TITLE
[PHP][C#] better enum support

### PR DESCRIPTION
**Pull request by wing328**
Better enum support for numbers and special characters

### CODE REVIEW

**Comment by bherila** [comment]
This also impacts typescript-node

**Comment by wing328** [comment]
@bherila thanks for pointing it out. This is going to be a major change and I'll need to fix all other languages that supports enum.

**Comment by wing328** [comment]
UPDATE: rebased on the latest to provide better enum support for the following:

PHP, Java, C#, JAX-RS, Spring

**Comment by wing328** [comment]
Upgrade note from 2.1.6 to 2.2.0

For better enum support (e.g. integer, special characters) we changed the following
```
public List<String> allowableValues;
```
to
```
public Map<String, Object> allowableValues;
```
Please update your code accordingly if your code has a dependency on `allowableValues`

**Comment by clicktravel-chrishern** [comment]
Hi,

We are interested in using the enhancements in this PR.  Do you have any idea when version 2.2.0 will be released?

**Comment by wing328** [comment]
@clicktravel-chrishern please refer to the FAQ: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-long-does-it-take-to-release-a-stable-version-eg-215--216

**Comment by bherila** [comment]
here is my local build: 
https://1drv.ms/u/s!AlvOZGwys91vxq5GV6WaZpNz9aQoog

hope it helps

Cheers,
Ben

**Pull request merged**
