### PR TITLE
Updated the swagger-codegen sample for generating the service side stubs

### LINKED ISSUE #957: Spring-mvc-server cannot deploy
_From @ericsodt on July 7, 2015 12:28_

I created a spring-mvc-server project from the 'minimal' project and tried to run it using mvn jetty:run however it does not seem to be deploying correctly.  I am getting the following errors: 

    No context on this server matched or handled this request.
    Contexts known to this server are:

     /api ---> o.e.j.m.p.JettyWebAppContext@6a916402{/api,[file:/C:/eclipse/workspace/spring-mvc-    swagger/target/webapp-tmp/, jar:file:/C:/Users/Jess/.m2/repository/io/springfox/springfox-swagger-    ui/2.0.0-SNAPSHOT/springfox-swagger-ui-2.0.0-SNAPSHOT.jar!/META-INF/resources],AVAILABLE}    {file:/C:/eclipse/workspace/spring-mvc-swagger/target/webapp-tmp/}

When I click on the api context I get another 404 stating:

    HTTP ERROR 404

    Problem accessing /api/. Reason:

        Not Found

_Copied from original issue: swagger-api/swagger-editor#530_

### PR DESCRIPTION
**Pull request by dilipkrish**
for spring mvc using springfox implementation

Fixes #957

### CODE REVIEW

**Comment by dilipkrish** [comment]
:bump:

**Comment by webron** [comment]
Did you just bump your own PR? :)

**Comment by dilipkrish** [comment]
clamoring for attention :)

**Comment by wing328** [comment]
@dilipkrish I did a test and got the following error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-spring-mvc-server: Compilation failure: Compilation failure:
[ERROR] /private/var/tmp/dilipkrish/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/StoreApi.java:[12,24] cannot find symbol
[ERROR] symbol:   class ApiResponse
[ERROR] location: package io.swagger.model
[ERROR] /private/var/tmp/dilipkrish/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/UserApi.java:[12,24] cannot find symbol
[ERROR] symbol:   class ApiResponse
[ERROR] location: package io.swagger.model
[ERROR] /private/var/tmp/dilipkrish/swagger-codegen/samples/server/petstore/spring-mvc/src/main/java/io/swagger/api/PetApi.java:[12,24] cannot find symbol
[ERROR] symbol:   class ApiResponse
[ERROR] location: package io.swagger.model
```
I think it's related to the following change in api.mustache:
```
-import io.swagger.annotations.ApiResponse;
 import io.swagger.annotations.ApiResponses;
+import io.swagger.model.ApiResponse;
```
I rolled back the change and no longer got the error.

I wonder if you can take a look.

**Comment by dilipkrish** [comment]
Let me take a look. I thought I tested it.

**Comment by dilipkrish** [comment]
@wing328 Not sure what happened there, I rebased and re-pushed the changes with the fixes. Let me know if you want me to squash the commits

**Comment by wing328** [comment]
@dilipkrish thanks for the quick turnaround. I did a test and jetty is now up and running:
```
[INFO] Started ServerConnector@3336ea98{HTTP/1.1}{0.0.0.0:8002}
[INFO] Started @7334ms
[INFO] Started Jetty Server
```

**Comment by dilipkrish** [comment]
Thanks for :merged:! What's the workflow to get it into editor.swagger.io?

**Comment by wing328** [comment]
I believe editor.swagger.io is using the latest stable release https://github.com/swagger-api/swagger-codegen/releases/tag/v2.1.2 so this fix will be available to editor.swagger.io in the next major release.

**Comment by webron** [comment]
To clarify, the editor simply executes the [online generator](http://generator.swagger.io) - that's updated whenever we make an official release.

**Comment by dilipkrish** [comment]
That makes sense! Let me know if there is anything else I can do to push it out to those properties (other than wait of course) :-)

**Pull request merged**
