### PR TITLE
Remove rxjs operators

### PR DESCRIPTION
**Pull request by topce**
### PR checklist

- [ x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x ] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@kenisteward @wing328  @sebastianhaas
### Description of the PR
It look like import '../rxjs-operators'; is not needed 
since angular 4.3

### CODE REVIEW

**Comment by kenisteward** [comment]
@topce beat me to the punch on this one.  Have you tested to make sure that this still works with your client  Locally?

Also I'd say that if we don't need the import then we shouldn't generate the file as the old way of using rxjs would end up importing more than we'd want.   At some point we should figure out the proper wait to include lettable operators when the time comes.

**Comment by topce** [comment]
@kenisteward 
tested locally with latest angular 5.0.0 and it works .
did not have opportunity to test it with 4.3.0
hope it works because in some online examples 
rxjs operator are not imported 
Please check if you have time
You are right for import in angular 5.0.0
you can use lettable operators for more details please check blog post 
[Version 5.0.0 of Angular Now Available](https://blog.angular.io/version-5-0-0-of-angular-now-available-37e414935ced)
for example:
`import { catchError } from "rxjs/operators/catchError";
import { tap } from "rxjs/operators/tap";`

**Comment by kenisteward** [comment]
Oh I use them now I was just asking :)

**Comment by topce** [comment]
@kenisteward  me too ;-)

**Comment by topce** [comment]
@kenisteward @wing328  
Amy news on this one ?

**Comment by wing328** [comment]
cc @TiFu @taxpon @sebastianhaas @kenisteward @Vrolijkx

**Comment by kenisteward** [comment]
As long as it is locally test to not break anything I'm cool with it!

**Pull request merged**
