### PR TITLE
Fully resolve external $ref tree

### PR DESCRIPTION
**Pull request by jweisman**
Fully resolve references when loading OpenAPI specification. This is required to fully traverse the external $ref tags

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.

### Description of the PR

Call `ParseOptions.setResolveFully` to fully walk the reference tree for responseBodies and schemas.

### CODE REVIEW

**Comment by jweisman** [comment]
Hi there. Any chance this can be merged? Is there something else I can do on this PR? Thanks!

**Comment by daemonfire300** [comment]
Came here because we probably also need such a fix. 
Saw the failing test, but I am no java/library expert so I could not fix it.

Fyi: But I tried skipping it and it turns out that it is not just this test that is failing. If you skip this test two more tests within the same suite fail.

**Comment by daemonfire300** [comment]
@jweisman any plans on resolving those failed tests?

**Comment by jweisman** [comment]
Since this PR has been open for 9 months, the upstream repository changed considerably. I will need to rebase and see why the tests are failing.

**Comment by daemonfire300** [comment]
@jweisman Thank you 👍

**Comment by jweisman** [comment]
Hi @daemonfire300 . I decided to add resolveFully as an option to avoid breaking any tests or previous behavior. I opened a new PR for that- #10200. Would be grateful if you could take a look there and provide any comments. Thanks!

**Pull request closed without merging**
