### PR TITLE
Feature/7722 liberate defaultgenerator

### PR DESCRIPTION
**Pull request by dankling**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [n/a] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Changed most private fields and methods on DefaultGenerator to protected.
Changed names of boolean fields so methods and field names weren't different only by capitalization:  squid:S1845

### CODE REVIEW

**Comment by dankling** [comment]
I didn't commit the changes from ./bin/java-petstore-all.sh because over 1,100 files were changed and it looks like the build failed during cleanup. Since my changes most likely shouldn't cause any downstream changes since these name-changed fields are not accessible from the mustache templates. I would appreciate guidance on if these changes really should be committed.

Here's the exception with a little context:
`Removing files and folders under samples/client/petstore/java/google-api-client/src/main
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Exception in thread "Thread-1" java.lang.IllegalArgumentException: Template directory modules/swagger-codegen/src/main/resources/Java/libraries/google-api-client does not exist.
	at io.swagger.codegen.config.CodegenConfigurator.setTemplateDir(CodegenConfigurator.java:173)
	at io.swagger.codegen.cmd.Generate.run(Generate.java:245)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by dankling** [comment]
@macjohnny @HugoMario would love to get some help on this PR that's been hanging in limbo for https://github.com/swagger-api/swagger-codegen/issues/7722

It looks like the first circleci failure was due to dependencies not being reachable, but since I updated java-petstore (with many more changes than I anticipated) I seem to have actual test failures that I don't know how to diagnose. Any help would be appreciated.

**Comment by HugoMario** [comment]
Hey @dankling this LGTM, thanks a lot!!. I think it would be good if @frantuma take a look of this before merging.

About the circle ci error, there is an issue on it not related to these changes.

**Comment by HugoMario** [comment]
Actually i also think it would be nice to port this to `3.0.0`, i can help with that.

**Comment by dankling** [comment]
@HugoMario progress on this?

**Comment by dankling** [comment]
Looking for help on moving this forward.

**Comment by dankling** [comment]
@frantuma Are you able to take a look at this? This has been open for quite a while. I can remove the updates to java-petstore if that would help, since they are unrelated to my changes.

**Comment by frantuma** [comment]
Thanks! included in #9136

**Pull request closed without merging**
