### PR TITLE
[Swift3] Fix handling of query item with array value

### PR DESCRIPTION
**Pull request by jgavris**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Query items with array values should be returned as a multiple query items, each with a single value, as per the URI specification.

### CODE REVIEW

**Comment by jaz-ah** [comment]
+1 cool @jgavris  - were there any tests that can be added to validate?

**Comment by jgavris** [comment]
Happy to add tests once @wing328 's changes land :)

**Comment by wing328** [comment]
@jgavris existing tests passed when merged into master: https://travis-ci.org/swagger-api/swagger-codegen/builds/241652944

Please file another PR to add new test cases to cover the change when you've time.

**Comment by wing328** [comment]
FYI. I improved the code format of Swift3 client a bit via b7fe612cc706b7d5b1d4dbb95a69479e998a3f46

**Comment by jaz-ah** [comment]
thx @wing328

**Pull request merged**
