### PR TITLE
PHP Client Fixes

### PR DESCRIPTION
**Pull request by hkz-aarvesen**
Dear Swagger,

I have updated the php client generator.  I'm not personally a php guy, but have worked with our php guys to produce something that they are happy with.  I humbly submit this PR for your consideration.

Notable Functionality
================
- Modified Java code
  - The package is based on the hostname rather than being hard coded to `SwaggerPetstore`
  - Renamed `processOpts` to `preGenerate`
  - Renamed `processSwagger` to `postGenerate`
  - Passing the `swagger` object to both `pre-` and `postGenerate`
  - Added a setter method for `invokerPackage`
  - Numerous additional values depend on `invokerPackage`, so these were moved inside of the setter
- Modified mustache templates
  - Added code to avoid warnings when running php with `E_STRICT`
  - Added additional deserialization code to handle translating the JSON schema types into valid php types (e.g. "number" to "float")
  - Change some tabs to spaces
- Modified php client layout
  - Renamed the autoloader file to just be `loader.php`.  This avoided the problem of having files with weird names like `yoyodyne\\db.php`
- Modified scala
  - Added a unit test for the hostname to package name method. This is literally the first piece of Scala I have written so YMMV.

I originally submitted this PR 3 weeks ago but against master than develop_2.0.  I've merged in the changes from that branches into this fork.  I'm about to make some breaking changes in my fork, so this will be the last time I can sync up :)

### CODE REVIEW

**Comment by fehguy** [comment]
@wing328 can you look at this?

**Comment by wing328** [comment]
@fehguy sure. will look into it and report back with test result.

**Comment by wing328** [comment]
@hkz-aarvesen thanks for submitting the PR. Here are some suggestions:

Given that you originally submitted the PR against the master, I would suggest you submit 2 separate PRs based on the latest `develop_2.0` branch
1) "Modified Java code", "Modified Scala"
2) "Modified mustache templates", "Modified php client layout"
as smaller changes are easier to review

@fehguy please take note that the change rename/redefine some methods as follows:
- Renamed processOpts to preGenerate
- Renamed processSwagger to postGenerate
- Passing the swagger object to both pre- and postGenerate
(Personally I'm happy with the current method naming)

**Comment by fehguy** [comment]
see comment from @wing328

**Pull request closed without merging**
