### PR TITLE
Convert snake case models naming to cameCase naming

### PR DESCRIPTION
**Pull request by iCEAGE**
Simply based on the JavaScript's code style guide naming should be camelCase.
`baseName` might be snake_case or some other variations but when the `name` is used it is camelCase.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but we need to use the base name (original name) since the base name can contain special characters, e.g. -, $

**Comment by iCEAGE** [comment]
@wing328 Thanks for your reply.

To be consistent in all the clients, I think `name` should be used. I've seen in the other clients e.g. Go client, special characters (`-`) are replaced with `_`. I think that happens in the [toVarName()](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java#L185) method.

I'm wondering what [sanitizeName()](https://github.com/swagger-api/swagger-codegen/blob/5b4eb96ba1b2e49c16db75963a091e259dacacc4/modules/swagger-codegen/src/main/java/io/swagger/codegen/DefaultCodegen.java#L3047) method does? Don't you think should we replace the special characters with style guide's way?

**Comment by iCEAGE** [comment]
````
-{{/interfaceModels}}{{/useInheritance}}{{#vars}}{{#required}}    _this['{{baseName}}'] = {{name}};{{/required}}
````
I'm not sure what this part does but in my case it just generates some empty lines. You can find the spec [here](https://newsapi.aylien.com/swagger/spec/news-api.json).

In the spec in one of the model there are some attributes which are snake_case. For example there is a Stories model which has an attribute called `next_page_cursor`. I expect the following:
```
console.log('API called successfully. next page cursor is: ' + data.nextPageCursor);
````
but I get:
````
console.log('API called successfully. next page cursor is: ' + data.next_page_cursor);
````
Let me know if you have any questions. Thanks

**Comment by wing328** [comment]
@iCEAGE basically we need a way in JS API client to maintain a mapping between JS model property name and JSON key name. I'm not aware of any node module to do that.

Here is a similar discussion but for typescript: https://github.com/swagger-api/swagger-codegen/issues/2766

**Comment by wing328** [comment]
Sorry we can't merge this as this will break others. Please use the `-t` option with the customized templates to meet your requirement.

**Pull request closed without merging**
