### PR TITLE
Factory interface for typescript-fetch

### PR DESCRIPTION
**Pull request by cjang5**
added a Factory interface for typescript-fetch, as well as tests

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by wing328** [comment]
cc @leonyu

**Comment by cjang5** [comment]
Oh that's odd.. I'll work on fixing it, thanks!

**Comment by leonyu** [comment]
Looks good :+1:

**Comment by wing328** [comment]
@cjang5 you can try adding that email address in the commit as your secondary email address in your github account.

**Comment by wing328** [comment]
@leonyu thanks for reviewing the change.

**Comment by cjang5** [comment]
@wing328 The email I just added (chris.jang423@gmail.com) is my primary Github email address, but I think on this machine I hadn't set it as the `git config --global user.email` which is why those first few commits didn't appear under my name as usual.

**Comment by wing328** [comment]
@cjang5 PR merged into master. Thanks for the contribution.

**Comment by wing328** [comment]
@cjang5 for your upcoming PR, I would suggest you to create a new branch as per git best practice.

**Pull request merged**
