### PR TITLE
Honor Enum's value

### PR DESCRIPTION
**Pull request by dantran**
see #1620

### CODE REVIEW

**Comment by wing328** [comment]
@dantran thanks for the PR. Next time, please update the Petstore sample as well.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/Guidelines-for-Contribution

**Comment by dantran** [comment]
Thank you for the merge.  Could you please deploy a snapshot to Sonatype?

**Comment by wing328** [comment]
@webron @fehguy when you've time, do you mind deploying the latest as a snapshot to Sonatype?

**Comment by webron** [comment]
Deployed.

**Comment by dantran** [comment]
Regress at #5797

**Pull request merged**
