### PR TITLE
Output models for go-server #3851

### PR DESCRIPTION
**Pull request by bvwells**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.
@antihax

### Description of the PR
Output the swagger models to separate model files to address issue #3851. Also, ...
 - Correct bug in writing of swagger.yaml.
 - Add standard header to generated go files to be consistent with go client.
 - Remove app.yaml as is unnecessary,

### CODE REVIEW

**Comment by wing328** [comment]
@bvwells thanks for adding the model template (which is same as the one used in the Go client generator). The change looks good to me.

**Comment by bvwells** [comment]
I just added another minor change to make the go client and server code closer to one another. It might be worth investigating an AbstractGoCodegen class at some point as much of the code is shared.

**Comment by wing328** [comment]
> It might be worth investigating an AbstractGoCodegen class at some point as much of the code is shared.

Very good suggestion. We've done similar refactoring for other languages (C#, Java, TypeScript, PHP, etc)

Ref: https://github.com/swagger-api/swagger-codegen/issues/6059

**Comment by bvwells** [comment]
If I get a chance, I'll take a look at refactoring the go generators.

**Comment by antihax** [comment]
Looks good to me also.

I agree on refactoring into a single generator for server and client; there shouldn't be much difference between the two and could help folks who are tweaking the templates to their needs.

Good suggestion.

**Comment by wing328** [comment]
@antihax thanks for reviewing.

PR merged into master.

**Comment by bvwells** [comment]
Thanks for the reviews and merge!

**Pull request merged**
