### PR TITLE
[Swift4]Update templates for swift 4

### PR DESCRIPTION
**Pull request by d-date**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

#### 1. Updated Dependencies
Updated swift4 & 3 dependencies due to RxSwift 4.0.0 was released.

To build generated source code with `ResponseAs=RxSwift` in Swift 4, we need to build RxSwift 4.0.0 via Carthage / Cocoapods.

Also, Alamofire 4.5.1 is needed for Swift 4.

In this PR, I fixed minimum version for dependencies.

#### 2. Update syntax for Swift 4
According [SE-0110: Distinguish between single-tuple and multiple-argument function types
](https://swift.org/migration-guide-swift4/), we need to use tuple `f(())` insted of `f()`, 

so when function returns `Observable<Void>` type, we need to change `onNext()` to `onNext(())`.

#### 3. Adoption for Codable

When using Codable, which is introduced on Swift4, with class inheritance, we must call `try super.init(from: decoder)` .

### CODE REVIEW

**Comment by wing328** [comment]
@d-date thanks for the PR.

cc @jgavris @ehyche  @Edubits @jaz-ah

**Comment by d-date** [comment]
@jgavris @ehyche @Edubits @jaz-ah
Added more improvement for swift syntax. please check it out.

**Comment by jgavris** [comment]
👍

**Comment by d-date** [comment]
@wing328 How about this PR?

**Comment by wing328** [comment]
@d-date let me review shortly and get back to you.

**Comment by ehyche** [comment]
I'll review tomorrow morning.

**Comment by wing328** [comment]
@d-date not related to this PR but the Petstore integration for Swift 4 client is already failing in the latest master. I wonder if you can take a look when you've time: https://github.com/swagger-api/swagger-codegen/issues/6944 

(swift3 petstore integration tests passed without issue)

**Comment by d-date** [comment]
@wing328 I found that errors related to Codable, which is introduced on Swift4. The swift 4 pet store has little order sample models than generated ones. I’ll try to work on another issue, and fix on another PR, after merged this PR.

**Comment by wing328** [comment]
@d-date FYI. We've just merged https://github.com/swagger-api/swagger-codegen/pull/6672. Please pull the latest before trying to fix the Swift4 Petstore integration issue.

**Comment by d-date** [comment]
@wing328  finish fixing #6944

**Comment by d-date** [comment]
@wing328 cc @jgavris @ehyche @Edubits @jaz-ah
How about this PR?

**Comment by wing328** [comment]
@d-date when I ran `./run_xcodebuild.sh` in `samples/client/petstore/swift4/default/SwaggerClientTests`, I got the following errors:
```
tended-module-overlay.yaml -Xcc -working-directory/tmp/swagger-codegen/samples/client/petstore/swift4/default/SwaggerClientTests/Pods
<unknown>:0: error: no such file or directory: '/tmp/swagger-codegen/samples/client/petstore/swift4/default/PetstoreClient/Classes/Swaggers/APIs/Fake_classname_tags123API.swift'
<unknown>:0: error: no such file or directory: '/tmp/swagger-codegen/samples/client/petstore/swift4/default/PetstoreClient/Classes/Swaggers/APIs/FakeclassnametagsAPI.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1

** TEST BUILD FAILED **
```
(this error is different than the one I found in master)
Did you get similar errors when running the script locally?

(I don't think it's caused by this PR but would be nice if you can look into it)

**Comment by d-date** [comment]
@wing328  I found the reason why tests are failed. We cannot use `object` type in spec as `Any` in Swift4. The `Codable` is a kind of `Protocol` so that we can adopt for `struct` (f.e. `String`, `Int`) types, but `Any` is primitive, not `struct`.

As I read below, `object` is not written in type. How can I handle `object` in Swift4?
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types 

I have alternative as below, but I don't know how to get whether `dataType` is `object` in mastache.

before:
```swift
open class func testInlineAdditionalPropertiesWithRequestBuilder(param: Any) -> RequestBuilder<Void> {
        let path = "/fake/inline-additionalProperties"
        let URLString = PetstoreClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: param)
//Compile Error: cannot convert type
...
    }
```

After:
```swift
open class func testInlineAdditionalPropertiesWithRequestBuilder<T: Encodable>(param: T) -> RequestBuilder<Void> {
        let path = "/fake/inline-additionalProperties"
        let URLString = PetstoreClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: param)
    }
```

**Comment by d-date** [comment]
already issued #6483

**Comment by wing328** [comment]
Please get some rest (I believe it's already late in Japan. 3am?) I'll take another look tomorrow

**Comment by wing328** [comment]
@jgavris @ehyche @Edubits @jaz-ah would you please take another look at this PR when you've time today?

**Pull request merged**
