### PR TITLE
updated versions for release

### PR DESCRIPTION
**Pull request by fehguy**

### CODE REVIEW

**Comment by cbornet** [comment]
See #3004 for the parser upgrade

**Comment by fehguy** [comment]
@cbornet that is a huge PR.  I can try merging into this branch

**Comment by fehguy** [comment]
@cbornet as @wing328 has tagged this to 2.3.0, I suggest we hold off.  Objections?

**Comment by cbornet** [comment]
No problem.
Then just pick https://github.com/swagger-api/swagger-codegen/pull/3004/commits/fc516115236136beb17ee8c296317375d268d354 to solve the CI issue.

**Comment by cbornet** [comment]
On the other hand, I think that upgrading the parser without merging my PR can lead to surprises as allOf will no longer set the parent and this is an issue when you have a discriminator (see Dog/Cat/Animal). So maybe wait my PR to upgrade the parser.

**Comment by fehguy** [comment]
@wing328 what do you think?  I'll update this PR to include the discriminator fixes from #3004 but not merge until we discuss.

**Comment by wing328** [comment]
@fehguy yes, as discussed with @cbornet we plan to include #3004 in v2.3.0
(and as @fehguy have pointed out, it's a huge PR and I don't think we should include it in the v2.2.0 release. Personally I didn't have a chance to test #3004, which is not to say the PR is not ready)

**Comment by fehguy** [comment]
OK I will have to adjust the PR then.

**Comment by wing328** [comment]
UPDATE: I'm drafting the release note, which is 50% done.

**Comment by cbornet** [comment]
Maybe just pick https://github.com/swagger-api/swagger-codegen/pull/3004/commits/2ce9a11b7665b11f1903e936226244eddc185b2c which sets the interface that has a discriminator as parent. And check that the generated samples don't change (if not included, Cat & Dog will no longer extend Animal).

**Pull request merged**
