### PR TITLE
Run docker in vagrant

### PR DESCRIPTION
**Pull request by wizardbyron**
Just one Vagrantfile that can help you run docker in vagrant without errors. 
:exclamation: : You have to install [vagrant](https://www.vagrantup.com/downloads.html) and [virtualbox](https://www.virtualbox.org/wiki/Downloads) first.

### usage:
```
git clone git@github.com:wizardbyron/swagger-codegen.git
cd swagger-codegen
vagrant up
```
:exclamation: You need to run docker by __sudo__
Then, you can run `./run-in-docker.sh ` in vagrant. And the directory /swagger-codegen was mapped as /vagrant
```
vagrant ssh
cd /vagrant
sudo ./run-in-docker.sh mvn package
```

### CODE REVIEW

**Comment by wing328** [comment]
@wizardbyron thanks for the PR. Are you using the latest master when creating this PR? 

Please kindly rebase to resolve the merge conflicts and let us know if you need help with the rebase.

**Comment by wizardbyron** [comment]
I've resolved the conflicts. 
Just had a glance at the latest .gitignore file, it's mess. 
I'll open another issue and PR to reorganize the ignore entries.

**Comment by wing328** [comment]
@wizardbyron thanks for the PR. Testing looks good:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] swagger-codegen-project ............................ SUCCESS [  2.167 s]
[INFO] swagger-codegen (core library) ..................... SUCCESS [01:05 min]
[INFO] swagger-codegen (executable) ....................... SUCCESS [01:07 min]
[INFO] swagger-codegen (maven-plugin) ..................... SUCCESS [02:22 min]
[INFO] swagger-generator .................................. SUCCESS [04:32 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 09:09 min
[INFO] Finished at: 2016-01-27T08:29:45+00:00
[INFO] Final Memory: 46M/311M
[INFO] ------------------------------------------------------------------------
vagrant@vagrant-ubuntu-trusty-64:/vagrant$ 
```

**Comment by wizardbyron** [comment]
That's great! Do I need create a new PR to add instructions in README.md ?

**Comment by wing328** [comment]
I'm updating it :)

**Comment by wing328** [comment]
UPDATE: https://github.com/swagger-api/swagger-codegen/blob/master/README.md#run-docker-in-vagrant

**Comment by wizardbyron** [comment]
Cool!

**Pull request merged**
