### PR TITLE
[Android] fix issue 2512: crash w/ NPE when dereferencing networkStatus which c…

### PR DESCRIPTION
**Pull request by jaz-ah**
…ould be nil on a volley timeout error

also regenerated android/volley sample classes.

### CODE REVIEW

**Comment by wing328** [comment]
@jaz-ah I got an error when running `gradle check`:
```
volley|jaz-ah-issue/2512⚡ ⇒ pwd
/Users/williamcheng/Code/swagger-codegen/samples/client/petstore/android/volley
volley|jaz-ah-issue/2512⚡ ⇒ gradle check

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'volley'.
> Could not resolve all dependencies for configuration ':_debugCompile'.
   > Could not find org.apache.httpcomponents:httpcore:4.5.2.
     Searched in the following locations:
         https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.pom
         https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.jar
         file:/Users/williamcheng/Library/Android/sdk/extras/android/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.pom
         file:/Users/williamcheng/Library/Android/sdk/extras/android/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.jar
         file:/Users/williamcheng/Library/Android/sdk/extras/google/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.pom
         file:/Users/williamcheng/Library/Android/sdk/extras/google/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.jar
     Required by:
         io.swagger:volley:1.0.0
   > Could not find org.apache.httpcomponents:httpcore:4.5.2.
     Searched in the following locations:
         https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.pom
         https://jcenter.bintray.com/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.jar
         file:/Users/williamcheng/Library/Android/sdk/extras/android/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.pom
         file:/Users/williamcheng/Library/Android/sdk/extras/android/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.jar
         file:/Users/williamcheng/Library/Android/sdk/extras/google/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.pom
         file:/Users/williamcheng/Library/Android/sdk/extras/google/m2repository/org/apache/httpcomponents/httpcore/4.5.2/httpcore-4.5.2.jar
     Required by:
         io.swagger:volley:1.0.0 > org.apache.httpcomponents:httpmime:4.5.2 > org.apache.httpcomponents:httpclient:4.5.2

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.832 secs
```
Is it running fine without issue in your local environment?

**Comment by jaz-ah** [comment]
hmmm... it's working w/o issue in my local environment but let me see if I can look into the problem you're hitting...

**Comment by jaz-ah** [comment]
@wing328 figured out the build.gradle issue - it was a regression from 00c97c8ff6a0b50027d6805d78b1b0f185c174e3
I've fixed that in this build but for some reason Travis is failing now but I'm not sure exactly what the issue is.. .

**Comment by wing328** [comment]
@jaz-ah no worry. I'll take another look at the build later.

**Comment by wing328** [comment]
@jaz-ah it now works for me. Thanks again for the fix.

**Comment by pradeepkumarreddyk** [comment]
what is the fix for volley timeout error

**Comment by jaz-ah** [comment]
@pradeepkumarreddyk the volley timeout error was occurring as just a random server timeout on our end.

**Pull request merged**
