### PR TITLE
Fix for issue #674

### PR DESCRIPTION
**Pull request by marcinkiewiczblazej**
Added missing `required` parameter in Spring annotation.

### CODE REVIEW

**Comment by webron** [comment]
Fixes #674.

**Comment by fehguy** [comment]
@webron it seems like this fix only adds a newline?

**Comment by webron** [comment]
@fehguy - didn't really look at the PR. Just wanted to create a link to the issue. The fix actually removes a line too, so I'm not really sure how/why it fixes anything.

**Comment by marcinkiewiczblazej** [comment]
There's a problem with Github diff, if you check the file there are changes. Most important one is:
```
@RequestParam(value = "{{paramName}}"{{#required}}, required = true{{/required}}{{^required}}, required = false{{/required}}
```
So I've added required param to `@RequestParam` in both cases just to be future proof if the default settings in Spring are changed.

**Pull request merged**
