### PR TITLE
Fix generate additionalProperties array type #6081

### PR DESCRIPTION
**Pull request by isman-usoh**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Fix generate additionalProperties array type #6081

### CODE REVIEW

**Comment by wing328** [comment]
@isman-usoh thanks for the PR. 

cc @Vrolijkx @taxpon @sebastianhaas @kenisteward @TiFu

**Comment by wing328** [comment]
@isman-usoh I did a test and confirmed the fix works
```
export interface Model1 {
    [key: string]: Array<Pet>;
}
```

**Comment by damienpontifex** [comment]
Just reviewing my PR and wondering if this change should be in the `AbstractTypeScriptClientCodegen` class if it's valid to all TypeScript?

**Comment by kenisteward** [comment]
That is actually preferred if possible but my change to put all common
things into the abstract hasn't. Been fixed to be merged yet

**Pull request merged**
