### PR TITLE
Add okhttp4-gson codegen

### LINKED ISSUE #9606: [Java] [okhttp-gson] Updating OkHttp to version 3.x
##### Description

I'd like to gauge the appetite for upgrading the version of OkHttp in the `okhttp-gson` module to a version in the 3.x series. Version 2.7.5 dates back to Feb 26, 2016, and there hasn't been an update since then.

Happy to put together a patch just for this module, but I first wanted to check to see if this is something that makes sense? Would this type of change need to wait for a major release of swagger-codegen, or could it be something that's released in a minor version - from what I can tell there would be API changes given the OkHttp package name is different in version 3.x and the API in okhttp-gson exposes some OkHttp classes.

##### Swagger-codegen version

3.0.10.

##### Related issues/PRs

This would help make progress on kubernetes-client/java#430. We'd love to be using a more recent version of OkHttp!

##### Suggest a fix/enhancement

Would be willing to offer up a patch (I have something already) if there's someone that would be willing to guide me through the process (my first time committing to this repo, so I might be missing some subtleties).

### PR DESCRIPTION
**Pull request by deepsan**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR
Add support for okhttp4-gson as a replacement for okhttp-gson

okhttp-gson is based on okhttp 2.x which is no longer supported. okhttp 3.x is also [not supported anymore](https://square.github.io/okhttp/security/security/)

Creating a new target for codegen since okhttp 4.x is a breaking change over the okhttp 2.x with changed package names.

The overall change is similar to the existing code with a few updates
- updates due to deprecations documented in https://square.github.io/okhttp/changelogs/changelog_3x/#version-300-rc1
- kept the utility methods in the existing code as-is

tested `mvn package`, ran the petstore generation scripts and the integration tests that are generated

Fixes #9606

### CODE REVIEW

**Comment by HugoMario** [comment]
thanks a lot @deepsan !!

**Comment by czy006** [comment]
It seem not used in 3.x,is it support 3.x ?

**Comment by Ragulrangarajan** [comment]
Hope this fix will be part of 2.4.37...do we have any planned release date for 2.4.37?

**Comment by brigadoon0** [comment]
You need to specify `okhttp4-gson` library in `<configOptions>` to use okhttp3 in the generated code.
```
            <plugin>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-codegen-maven-plugin</artifactId>
                <version>2.4.36</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
    
                            <configOptions>
                                <library>okhttp4-gson</library>
                            </configOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Pull request merged**
