### PR TITLE
Fix for issue #3743

### PR DESCRIPTION
**Pull request by ataraxus**
### Description of the PR

Fix for issue #3743

### CODE REVIEW

**Comment by wing328** [comment]
@ataraxus thanks for the PR.

@sebastianhaas @Vrolijkx would you please review the PR to see if it looks good from your perspective?

**Comment by Vrolijkx** [comment]
Looks OK to me.

**Comment by wing328** [comment]
Thanks for the review. PR merged.

**Comment by wing328** [comment]
@ataraxus for your upcoming PRs, I would suggest creating a new branch for the change.

**Pull request merged**
