### PR TITLE
[9703] Kotlin multiplatform client

### PR DESCRIPTION
**Pull request by andrewemery**
Support for the generation of [Kotlin Multiplatform](https://kotlinlang.org/docs/reference/multiplatform.html) clients.

**Background**

The ```kotlin``` language defined in the Swagger Codegen project currently generates a Kotlin client that can run on the JVM. Somewhat recently, JetBrains introduced [Kotlin Multiplatform](https://kotlinlang.org/docs/reference/multiplatform.html), a platform that provides the ability to share code between various platforms: JVM, JS, iOS, Windows, etc. This pull request adds the ability to generate a Kotlin Multiplatform client.

**Library**

The pull request includes Kotlin Multiplatform generation under the ```kotlin``` language and introduces two library options:
1. ```jvm```: (default) to target the existing Kotlin JVM generation.
2. ```multiplatform```: to target Kotlin Multiplatform generation.

**Limitations**

The current pull request only currently adds support for JVM and iOS platforms (largely because I don't have enough experience with the other supported platforms to guarantee their correctness), but support for other platforms should be trivial to add.

At present, ```date``` and ```date-time``` objects are rendered as strings. No attempt is made to integrate any third-party date/time libraries.

**Tests**

The current implementation doesn't include any tests beyond those already included as part of the ```kotlin``` language implementation. A test project can be found [here](https://github.com/andrewemery/swagger-kotlin-multiplatform-petstore) that generates the ```petstore``` sample and includes tests to verify the correctness of the implementation, however some guidance here about an acceptable level of testing would be appreciated.

Comments welcome.

**References**

https://github.com/swagger-api/swagger-codegen/issues/9703
https://github.com/andrewemery/swagger-kotlin-multiplatform-petstore

### CODE REVIEW

**Comment by HugoMario** [comment]
thanks a lot @andrewemery for this PR, i'm going to take a time to check it before merge it

**Comment by HugoMario** [comment]
@andrewemery , any special reason you closed it? 
do you mind if we use your changes?

**Comment by andrewemery** [comment]
@HugoMario You're welcome to the changes but they're several commits and bugfixes behind https://github.com/OpenAPITools/openapi-generator. 

I assumed this wasn't progressing. It's functional in its current state, albeit limited. I can resurrect this branch in its current state if you want, but it might be a while before I bring it up to parity.

**Comment by HugoMario** [comment]
sure, please, reopen it, we're really interesting in this PR. i'm no so familiar with kotlin, but anything else i can help you just let me know.

**Pull request closed without merging**
