### PR TITLE
A new property additionalModelTypeAnnotations that allows to add any custom annotations on the top of generated java class model

### PR DESCRIPTION
**Pull request by Ravisankar-Challa**
A new property **additionalModelTypeAnnotations** that allows to add any custom annotations on the top of generated java class model

java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l spring --additional-properties **additionalModelTypeAnnotations="@com.fasterxml.jackson.annotation.JsonIgnoreProperties(ignoreUnknown = true);@com.fasterxml.jackson.annotation.JsonInclude(JsonInclude.Include.NON_NULL)"**,dateLibrary=java8,interfaceOnly=true,useTags=true,serializableModel=true -o ravi

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by Ravisankar-Challa** [comment]
@HugoMario Could you please look in to this pull request.

**Comment by Ravisankar-Challa** [comment]
@HugoMario Could please look in to this pull request

**Comment by u784912** [comment]
@Ravisankar-Challa  / @HugoMario 

When this change will be merged?

**Comment by Ravisankar-Challa** [comment]
@HugoMario  Could you please look in to this pull request

**Comment by HugoMario** [comment]
Hey guys, sorry for delay answer.
Yes, i'll take a look on this.

**Comment by HugoMario** [comment]
Hey @Ravisankar-Challa sorry again for my delay response.

I like the idea proposed on this PR, however there are a few things that i think it should be implemented in a different way.
- The annotations must be available to be used with simple names instead full names.
- The semicolon should be addressed on template side.

I'm proposing this in order to keep the same behavior in template-generators relationship.

Let me know what you think about it, also i can help with the changes i'm proposing, just add me to your PR and let me know.

**Comment by Ravisankar-Challa** [comment]
@HugoMario The idea for additionalModelTypeAnnotations is taken from open api generator. In open api code generator they are using semicolon. additionalModelTypeAnnotations let's us add any annotation on the top of generated classes. ex:- I want to add @Entity annotation which comes from the package "javax.persistence" on the top of the generated classes. Then we have to provide full package name like this. java -jar swagger-codegen-cli.jar generate -i swagger.yaml -l spring --additional-properties additionalModelTypeAnnotations="@javax.persistence.Entity" -o output

**Comment by Ravisankar-Challa** [comment]
@HugoMario Please look in to this pull request

**Comment by HugoMario** [comment]
@Ravisankar-Challa i'm on it

**Comment by HugoMario** [comment]
LGTM thanks @Ravisankar-Challa !!

**Pull request merged**
