### PR TITLE
[PHP][Symfony] Add a Symfony server generator

### PR DESCRIPTION
**Pull request by ksm2**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Hi, I added an implementation for a Symfony server bundle generator (see issue #3486)!

### CODE REVIEW

**Comment by wing328** [comment]
@ksm2 thanks for the contribution! We'll review and let you know if we've any question.

**Comment by wing328** [comment]
@ksm2 overall it looks pretty good 👍 

There are some enhancements I can think of and will create a separate ticket (issue) for tracking.

**Comment by wing328** [comment]
Tweet https://twitter.com/wing328/status/882522959159541761 to promote the new generator. Please help retweet.

**Comment by wing328** [comment]
cc @arnested @baartosz @dkarlovi @ackintosh

**Comment by wing328** [comment]
FYI. Opened https://github.com/swagger-api/swagger-codegen/issues/5985 to track enhancements.

**Comment by dkarlovi** [comment]
@ksm2 this looks very nice! \o/

**Pull request merged**
