### PR TITLE
java jax rs code generation fix and formatting tidy

### PR DESCRIPTION
**Pull request by ahgittin**
introduction of `skipOverwrite` in #831 / #859 caused `Factory` and `Impl` classes **never** to be written for jax-rs.  this fixes that.

also i noticed the old jax-rs templates have bad spacing, e.g.

       public method(...) {
       // body
    }

this aligns things and generally improves whitespace (superseding #1092 as per @wing328 's comment)

### CODE REVIEW

**Comment by ahgittin** [comment]
see https://github.com/swagger-api/swagger-codegen/pull/859/files#r37515455 for the introduction of the bug

**Comment by wing328** [comment]
@ahgittin thanks! will review and let you know if I've any questions.

**Comment by ahgittin** [comment]
@wing328 noticed the generated code did not compile in some cases due to `supportsInheritance` now defaulting to false; have pushed one more one-liner to fix that.  can unwind and open separate PR if you prefer (didn't expect you to get to it so quickly!).

**Comment by ahgittin** [comment]
@wing328 actually having seen #1050 i've reverted that so nvm.  i will open a separate PR.

**Comment by wing328** [comment]
@ahgittin under `samples/server/petstore/jaxrs` I ran `mvn test` but got the following:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /private/var/tmp/ahgittin/swagger-codegen/samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApi.java:[32,153] cannot find symbol
  symbol:   variable String
  location: class io.swagger.api.StoreApi
[ERROR] /private/var/tmp/ahgittin/swagger-codegen/samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApi.java:[32,168] annotation values must be of the form 'name=value'
[INFO] 2 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.005 s
[INFO] Finished at: 2015-08-21T21:58:41+08:00
[INFO] Final Memory: 15M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project swagger-jaxrs-server: Compilation failure: Compilation failure:
[ERROR] /private/var/tmp/ahgittin/swagger-codegen/samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApi.java:[32,153] cannot find symbol
[ERROR] symbol:   variable String
[ERROR] location: class io.swagger.api.StoreApi
[ERROR] /private/var/tmp/ahgittin/swagger-codegen/samples/server/petstore/jaxrs/src/gen/java/io/swagger/api/StoreApi.java:[32,168] annotation values must be of the form 'name=value'
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
jaxrs|jax-rs-format-fixes ⇒ 
jaxrs|jax-rs-format-fixes ⇒ pwd
/var/tmp/ahgittin/swagger-codegen/samples/server/petstore/jaxrs
```
Is this PR supposed to address that or the error is already there before you submitted the fix ?
(I've run `mvn clean && ./bin/jaxrs-petstore-server.sh` to update the sample before running `mvn test`)

**Comment by webron** [comment]
@ahgittin - due to a development procedure change, you'll have to resubmit the PR against the `master` branch.

**Comment by ahgittin** [comment]
@wing328 I've rebased on master and will submit PR shortly.  I've no idea why that error appeared, it is supposed to build, and when I do this (after the rebase and tidies) all works well:

```
rm -rf samples/server/petstore/jaxrs/
bin/jaxrs-petstore-server.sh
cd samples/server/petstore/jaxrs/
mvn clean install
```

**Comment by ahgittin** [comment]
Closing in preference to #1119

**Pull request closed without merging**
