### PR TITLE
Java: Fix UUID mapping to a UUID instead of a string

### PR DESCRIPTION
**Pull request by brentryan**
### PR checklist

- [X] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run`./bin/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [X] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

It looks like there was a commit back in January that reverted a previous fix that added UUID types for java.  The commit is 7aac639.

This fixes the issue by allowing UUID to be used in generated code.

### CODE REVIEW

**Comment by cbornet** [comment]
The commit you mention didn't change the behavior regarding UUID : the line you want to remove was already there in JavaClientCodegen.

**Comment by cbornet** [comment]
Acutally, the UUID mapping was added in #2754

**Comment by brentryan** [comment]
@cbornet I don't see anything referencing UUID in JavaClientCodegen.  I know that when I remove that line in AbstractJavaCodegen.java that it works fine now for me.  Without removing that line it always maps to a string type.

**Comment by cbornet** [comment]
I just mean that your reference to https://github.com/swagger-api/swagger-codegen/commit/7aac639aad48fa0cce773486ed9bf651eb3bbdc6 is wrong. It's #2754 that added the line.

**Comment by brentryan** [comment]
Thank you.

**Comment by wing328** [comment]
@brentryan thanks for the PR. I did some tests and the result looks good. Please run the following to update Java API clients and server stubs so that the CIs can verify the change:

Java API clients
```
./bin/java-petstore-all.sh
```


Java server stubs:
```
jaxrs-resteasy-joda-petstore-server.sh  
jaxrs-jersey1-petstore-server.sh
jaxrs-resteasy-petstore-server.sh       
jaxrs-petstore-server.sh
```

**Comment by wing328** [comment]
Also I think this is a breaking change as UUID will no longer be a `string` in Java API client and server stubs. Please resubmit the PR for `2.3.0` branch instead.

**Pull request closed without merging**
