### PR TITLE
Updated to .NET Core 2.1

### PR DESCRIPTION
**Pull request by knom**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Updated ASPNET Core Generator to support .NET Core 2.1.
As per https://docs.microsoft.com/en-us/dotnet/core/migration/20-21

@jimschubert @wing328

### CODE REVIEW

**Comment by knom** [comment]
This is solving #8761

**Comment by knom** [comment]
@wing328 can you merge this?

**Comment by jimschubert** [comment]
@knom we've moved to our own fork (https://github.com/OpenAPITools/openapi-generator), and neither of us have commit access to this project.

openapi-generator had a similar PR a couple months ago. See OpenAPITools/openapi-generator#1008

**Comment by HugoMario** [comment]
already covered

**Pull request closed without merging**
