### PR TITLE
issue2061_fix_DeprecationWarning_in_unit_tests

### PR DESCRIPTION
**Pull request by cobain**
@wing328 please help to review.

### CODE REVIEW

**Comment by wing328** [comment]
@cobain thanks for the PR. I'll review later today.

(linked to #2061)

**Comment by wing328** [comment]
@cobain I did a test and no longer see the warning. Will merge the PR this weekend.

**Comment by cobain** [comment]
Yes, totally fixed 4 warnings.

**Comment by wing328** [comment]
@cobain PR merged. Thanks for the contribution.

**Pull request merged**
