### PR TITLE
[javascript] Added README section for Webpack configuration

### LINKED ISSUE #3466: [Javascript][2.2.0] AMD define module paths fails in Webpack
##### Description

Version 2.1.6 produced AMD paths with `./` prefixes. For example:

```
define(['./ApiClient', './model/Article', './model/ArticleResourceSingle', ... , './api/DefaultApi'], factory);
```

Version 2.2.0 produces AMD paths without `./` prefixes. For example: 

```
define(['ApiClient', 'model/Article', 'model/ArticleResourceSingle', ..., 'api/DefaultApi'], factory);
```

This has broken my webpack build.

```
ERROR in ../api/build/swagger/javascript/src/index.js
Module not found: Error: Cannot resolve module 'model/Article' in ../api/build/swagger/javascript/src
 @ ../api/build/swagger/javascript/src/index.js 28:4-701

ERROR in ../api/build/swagger/javascript/src/index.js
Module not found: Error: Cannot resolve module 'model/ArticleResourceSingle' in ../api/build/swagger/javascript/src
 @ ../api/build/swagger/javascript/src/index.js 28:4-701

```
##### Swagger-codegen version

2.2.0

### PR DESCRIPTION
**Pull request by frol**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This PR closes #3466.

### CODE REVIEW

**Comment by kemurphy** [comment]
I suspect this is solved by #5768 and that AMD is irrelevant here.

**Comment by wing328** [comment]
@fol thanks for the enhancement. I'm sure JS developers will find it helpful.

**Comment by kemurphy** [comment]
@wing328 did you read the discussion on #5768?  This patch shouldn't be necessary, and I think the instructions here aren't actually related to the problem.

**Comment by frol** [comment]
@wing328 I am sorry that I didn't mark the PR as WIP! @kemurphy has brought some valid concerns in his PRs, so I had to test them before I close this PR. Don't revert the change just yet; let us work on this for a little while.

**Comment by wing328** [comment]
@kemurphy Not yet. Will check it out later. Thanks for pointing it out.

@frol no worry. I'll roll back the change.

**Comment by wing328** [comment]
Changes reverted via #5770

**Comment by wing328** [comment]
Sorry I missed the line about not reverting the PR.

Please file a new one when the change is ready for review.

**Pull request merged**
