### PR TITLE
Add VendorExtensions to root swagger

### PR DESCRIPTION
**Pull request by jhitchcock**

### CODE REVIEW

**Comment by wing328** [comment]
@jhitchcock thanks for the PR. Do you think you've cycle to add a simple test case for the root level vendor extensions?

**Comment by jhitchcock** [comment]
Will do

**Comment by jhitchcock** [comment]
Hm actually the global vendorExtensions only appear in the final model sent to moustache, that is only created in the generate() method. 

I can't figure out how to access that via a test as before generate() I don't have it, and after generate() I only have the generator output. 

Any ideas?

**Comment by fehguy** [comment]
@jhitchcock there is a `void preprocessSwagger(Swagger swagger)` function you can override and do any mutation of the swagger definition then.

**Comment by wing328** [comment]
I'll add the test later when I've time. PR merged.

**Pull request merged**
