### PR TITLE
[csharp] Return ICollection<T> instead of List<T>

### PR DESCRIPTION
**Pull request by jimschubert**
This change is inline with Microsoft's [recommended guidelines for
collections]
(https://msdn.microsoft.com/en-us/library/dn169389(v=vs.110).aspx).

This code is based on the discussion in swagger-api/swagger-codegen#1338

As mentioned in the issue, converting method signatures to return `ICollection<T>` rather than `List<T>` should be considered a **breaking change**.

This change also reduces the specific type of input parameters from `List<T>` to `ICollection<T>`, which is not a breaking change because `List<T>` implements `ICollection<T>`.

### CODE REVIEW

**Comment by wing328** [comment]
@jimschubert thanks for the PR. Given that it's a breaking (non-backward compatible) change, I would suggest adding a CLI option (e.g. returnICollection) that defaults to false to begin with.

**Comment by jimschubert** [comment]
@wing328 I've added two options: `useCollection` and `returnICollection`. I rebased my branch and merged master.

* **useCollection**: Deserialize responses into and return `Collection<T>`  
* **returnICollection**: For `List<T>` or `Collection<T>`, return `ICollection<T>`
  instead of the concrete type

**Comment by wing328** [comment]
@jimschubert thanks for adding the option. I tested with useCollection only and got the following error:

screen shot 2016-01-25 at 10 12 49 am

But when I tested witih both useCollection and returnICollection set to true, I didn't get the error.

**Comment by jimschubert** [comment]
@wing328 I don't know why that would happen. Commented on the line above which includes the import.

I noticed that any time I changed the resources, I had to run `mvn clean package` before generating the sample. I didn't get a chance to look into why.

**Comment by wing328** [comment]
Forgot to mention that the error I got is in Pet.cs (model.mustache) and I don't see `System.Collections.ObjectModel` hardcoded in model.mustache.

**Comment by jimschubert** [comment]
Ah. That's weird. I can update the model template tomorrow. I can also rebase.

**Comment by wing328** [comment]
Thank you :beer:

**Comment by jimschubert** [comment]
@wing328 I've added that using directive to model.mustache. Looked like my config was only testing both options. Sorry about that. Couldn't rebase all commits because of the merge from master, but everything on my branch is now up to date.

**Comment by wing328** [comment]
@jimschubert no problem bro. I'll give it another try later and merge into master accordingly.

**Pull request merged**
