### PR TITLE
New sync master to 2.3.0

### PR DESCRIPTION
**Pull request by ePaul**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change.
   → all of bin/*.sh (if executable).
- [x] Filed the PR against the correct branch:  `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

@wing328 in #5072 merged the state of master at february 8 into branch 2.3.0.
This follows up with a current master (today).

### CODE REVIEW

**Comment by wing328** [comment]
@ePaul thanks for the PR but Travis CI failed with the following error message:
```
[ERROR]     Child module /home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/springboot/pom.xml of /home/travis/build/swagger-api/swagger-codegen/pom.xml does not exist
```
Did you run `./bin/run-all-petstore` to update all Petstore samples?

**Comment by ePaul** [comment]
I used `for d in bin/*.sh ; do $d ; done` in my bash. I was not aware of `run-all-petstore`, will use this in the future.

The springboot/pom.xml is missing due to #5063 – I though #5064 was already merged, but it wasn't. Will fix this right now.

**Comment by wing328** [comment]
Just merged https://github.com/swagger-api/swagger-codegen/pull/5064.

**Comment by ePaul** [comment]
Now fails with the tests of Go Petstore client:

```
=== RUN TestDeletePet
--- PASS: TestDeletePet (0.00s)
=== RUN TestConcurrency
--- FAIL: TestConcurrency (1.02s)
	Error Trace:	pet_api_test.go:193
			pet_api_test.go:165
	Error:      	Not equal: 
	            	expected: 0
	            	received: 12348
	Messages:   	Pet id should be equal
	Error Trace:	pet_api_test.go:194
			pet_api_test.go:165
	Error:      	Not equal: 
	            	expected: ""
	            	received: "gopherJohn"
	Messages:   	Pet name should be gopherJohn
	Error Trace:	pet_api_test.go:195
			pet_api_test.go:165
	Error:      	Not equal: 
	            	expected: ""
	            	received: "dead"
	Messages:   	Pet status should be dead
	pet_api_test.go:200: &{404 Not Found 404 HTTP/1.1 1 1 map[Server:[Jetty(9.2.9.v20150224)] Date:[Wed, 15 Mar 2017 17:31:27 GMT] Access-Control-Allow-Origin:[*] Access-Control-Allow-Methods:[GET, POST, DELETE, PUT] Access-Control-Allow-Headers:[Content-Type, api_key, Authorization] Content-Type:[application/json]] 0xc208128440 -1 [chunked] false map[] 0xc20801f520 <nil>}
	pet_api_test.go:182: &{404 Not Found 404 HTTP/1.1 1 1 map[Access-Control-Allow-Origin:[*] Access-Control-Allow-Methods:[GET, POST, DELETE, PUT] Access-Control-Allow-Headers:[Content-Type, api_key, Authorization] Content-Length:[0] Server:[Jetty(9.2.9.v20150224)] Date:[Wed, 15 Mar 2017 17:31:27 GMT]] 0xc208128a00 0 [] false map[] 0xc20801ec30 <nil>}
=== RUN TestCreateUser
--- PASS: TestCreateUser (0.00s)
```

(It looks like expected and received are swapped here?)

**Comment by ePaul** [comment]
Next step: scala-client.

```
[INFO] --- scala-maven-plugin:3.1.5:compile (scala-compile-first) @ swagger-scala-client ---
[INFO] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala:-1: info: compiling
[INFO] Compiling 10 source files to /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/target/classes at 1489672768547
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala:34: error: object datatype is not a member of package com.fasterxml.jackson
[ERROR] import com.fasterxml.jackson.datatype.joda.JodaModule
[ERROR]                              ^
[ERROR] /home/travis/build/swagger-api/swagger-codegen/samples/client/petstore/scala/src/main/scala/io/swagger/client/ApiInvoker.scala:44: error: not found: type JodaModule
[ERROR]     mapper.registerModule(new JodaModule());
[ERROR]                               ^
[ERROR] two errors found
```

**Comment by ePaul** [comment]
Hmm, in master scala-client has jackson-datatype-joda as an indirect dependency due to swagger-core 1.5.9. Same in branch 2.3.0. But in this branch we somehow have swagger-code 1.5.12, which doesn't depend on jackson-datatype-joda anymore.

Turns out the template in master also has 1.5.2, changed in #4881, but the samples were not updated yet.
I'll open a separate PR to update this in master (and potentially also fix it).

**Comment by ePaul** [comment]
Shippable doesn't run here?

**Comment by wing328** [comment]
@ePaul I've seen similar issue in which some CI tests are not shown/triggered. It could be an issue with the CI provider.

**Comment by wing328** [comment]
@ePaul thanks for the effort. Moving forward, I'll try to sync master to 2.3.0 every day to minimize the effort in resolving the merge conflicts during the sync.

**Pull request merged**
