### PR TITLE
Added support for enums in Dart.

### PR DESCRIPTION
**Pull request by pylaligand**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Previously enum types resulted in regular Dart objects, which failed miserably at deserialization time. Now Dart enums are properly generated, with an appropriate serialization/deserialization mechanism.

### CODE REVIEW

**Comment by wing328** [comment]
@pylaligand thanks for the PR. 

@ircecho please review when you've time.

**Comment by ircecho** [comment]
@wing328 I will review the code as soon as I have time, but this might only be next week or the week after.

**Comment by wing328** [comment]
@pylaligand building the JAR failed due to the following:
```
Tests run: 511, Failures: 1, Errors: 0, Skipped: 3, Time elapsed: 556.339 sec <<< FAILURE! - in TestSuite
checkOptionsHelp(io.swagger.codegen.dart.DartClientOptionsTest)  Time elapsed: 0.017 sec  <<< FAILURE!
java.lang.AssertionError: These options weren't checked: useEnumExtension.


Results :

Failed tests: 
  DartClientOptionsTest>AbstractOptionsTest.checkOptionsHelp:44 These options weren't checked: useEnumExtension.

Tests run: 511, Failures: 1, Errors: 0, Skipped: 3
```

Let me know if you need help fixing it.

**Comment by pylaligand** [comment]
I'll fix it, no worries.

**Comment by wing328** [comment]
@pylaligand @ircecho is there any easy way to do a syntax check or compile test (to JS code) on the Dart Petstore client so that we can setup CI to ensure moving forward changes related to Dart won't cause compilation error?

**Comment by ircecho** [comment]
@wing328 I am using the following piece of code to validate dart code.

`pub get && dartanalyzer --fatal-warnings . || die "Dart package $1_client_dart has errors."`

This also shows warnings as fatal but the command line flag could be removed if so desired. However, I think it should stay and the generated code should be made warning-free instead.

This requires the dart SDK to be installed on the system. I hope it can be incorporated into the CI system.

**Comment by wing328** [comment]
@ircecho I'll give it a try and let you guys know if I need any help.

**Comment by wing328** [comment]
I got errors when running `find . -name "*.dart" | xargs dartanalyzer`:
```
swagger|dart_ci⚡ ⇒ pwd                                       
/Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/dart/swagger
swagger|dart_ci⚡ ⇒ find . -name "*.dart" | xargs dartanalyzer
Analyzing [./lib/api/pet_api.dart, ./lib/api/store_api.dart, ./lib/api/user_api.dart, ./lib/api.dart, ./lib/api_client.dart, ./lib/api_exception.dart, ./lib/api_helper.dart, ./lib/auth/api_key_auth.dart, ./lib/auth/authentication.dart, ./lib/auth/http_basic_auth.dart, ./lib/auth/oauth.dart, ./lib/model/api_response.dart, ./lib/model/category.dart, ./lib/model/order.dart, ./lib/model/pet.dart, ./lib/model/tag.dart, ./lib/model/user.dart]...
Unhandled exception:
AnalysisException: Cannot compute LIBRARY_ELEMENT for /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/dart/swagger/lib/api.dart
Caused by Unexpected exception while performing InferInstanceMembersInUnitTask for source /Users/williamcheng/.pub-cache/hosted/pub.dartlang.org/async-1.11.2/lib/src/typed/stream_subscription.dart
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:339)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:664)
#5      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:637)
#6      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:232)
#7      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#8      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:231)
#9      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#10     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#11     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:541)
#12     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:201)
#13     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:144)
#14     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#15     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:143)
#16     Driver.start (package:analyzer_cli/src/driver.dart:129)
#17     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#18     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#19     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by IllegalArgumentException: argumentTypes.length (1) != typeFormals.length (0) null
#0      FunctionTypeImpl.instantiate (package:analyzer/src/dart/element/type.dart:690)
#1      InstanceMemberInferrer._inferExecutable (package:analyzer/src/task/strong_mode.dart:291)
#2      List.forEach (dart:core-patch/growable_array.dart:254)
#3      InstanceMemberInferrer._inferClass (package:analyzer/src/task/strong_mode.dart:235)
#4      InstanceMemberInferrer.inferCompilationUnit.<anonymous closure> (package:analyzer/src/task/strong_mode.dart:98)
#5      List.forEach (dart:core-patch/growable_array.dart:254)
#6      InstanceMemberInferrer.inferCompilationUnit (package:analyzer/src/task/strong_mode.dart:96)
#7      InferInstanceMembersInUnitTask.internalPerform (package:analyzer/src/task/dart.dart:2850)
#8      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:329)
#9      AnalysisTask.perform (package:analyzer/task/model.dart:229)
#10     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:274)
#11     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#12     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:664)
#13     AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:637)
#14     AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:232)
#15     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#16     AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:231)
#17     AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#18     AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#19     Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:541)
#20     Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:201)
#21     Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:144)
#22     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#23     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:143)
#24     Driver.start (package:analyzer_cli/src/driver.dart:129)
#25     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#26     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)


#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:668)
#1      AnalysisContextImpl.computeLibraryElement (package:analyzer/src/context/context.dart:637)
#2      AnalyzerImpl._resolveLibrary.<anonymous closure> (package:analyzer_cli/src/analyzer_impl.dart:232)
#3      _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#4      AnalyzerImpl._resolveLibrary (package:analyzer_cli/src/analyzer_impl.dart:231)
#5      AnalyzerImpl._analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:165)
#6      AnalyzerImpl.analyzeSync (package:analyzer_cli/src/analyzer_impl.dart:126)
#7      Driver._runAnalyzer (package:analyzer_cli/src/driver.dart:541)
#8      Driver._analyzeAllImpl (package:analyzer_cli/src/driver.dart:201)
#9      Driver._analyzeAll.<anonymous closure> (package:analyzer_cli/src/driver.dart:144)
#10     _PerformanceTagImpl.makeCurrentWhile (package:analyzer/src/generated/utilities_general.dart:212)
#11     Driver._analyzeAll (package:analyzer_cli/src/driver.dart:143)
#12     Driver.start (package:analyzer_cli/src/driver.dart:129)
#13     main (file:///b/build/slave/dart-sdk-mac-stable/build/sdk/pkg/analyzer_cli/bin/analyzer.dart:11)
#14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)
```

Not sure if it's due to incomplete setup of Dart in my machine. Can you guys give it a try and see if you get similar errors?

**Comment by wing328** [comment]
@pylaligand @ircecho I suggest merging this PR into master to avoid leaving it open for too long.

**Comment by wing328** [comment]
Thanks for the PR, which has been merged into master. 

@pylaligand please file another PR for further enhancements to the Dart client generator.

**Pull request merged**
