### PR TITLE
Added ModelInterface for PHP Models

### PR DESCRIPTION
**Pull request by nexsja**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

All Model classes include a set of methods - it makes sense to align them to a concrete interface to improve strict typing when referencing these models.
This PR references #6330

### CODE REVIEW

**Comment by wing328** [comment]
@nexsja thanks for the PR.

cc @baartosz @dkarlovi @arnested for review.

**Comment by alexniedreacn** [comment]
Thanks guys. Maven doesn't wanna pass but it seems that there's some Java code missing?
Not sure whether it's due to my change or something else but if somebody would point me in the right direction I'd be happy to fix and get this rolling. :)

**Comment by nexsja** [comment]
Thanks guys. Maven doesn't wanna pass but it seems that there's some Java code missing?
Not sure whether it's due to my change or something else but if somebody would point me in the right direction I'd be happy to fix and get this rolling. :)

**Comment by nexsja** [comment]
@baartosz @dkarlovi @arnested any idea when this might get merged?

**Comment by wing328** [comment]
cc @jebentier @mandrean as well

**Comment by wing328** [comment]
@nexsja the change looks good to me. If no further feedback from anyone, I'll merge in by coming weekend.

We should probably do the same to models generated by PHP server generators (e.g. Slim, Lumen, etc)

**Comment by alexniedreacn** [comment]
Thanks! I'll try to find a free moment today and add the same thing to other php generators. :)

**Comment by nexsja** [comment]
Thanks! I'll try to find a free moment today and add the same thing to other php generators. :)

**Pull request merged**
