### PR TITLE
fix: codegen does not support spec 2.0 properties for parameters:

### PR DESCRIPTION
**Pull request by gaalandr**
With pull request: https://github.com/swagger-api/swagger-core/pull/1524 swagger-core should support missing properties defined in spec 2.0:
``` 
maximum, exclusiveMaximum, minimum, exclusiveMinimum, maxLength,
minLength, pattern, maxItems, miIems, uniqueItems, multipleOf
```
Codegen should copy them into CodegenParameter.

Please verify and merge into master.
Thank you.

### CODE REVIEW

**Comment by wing328** [comment]
@gaalandr thanks for the PR but the CI (travis) failed. Please review the [log](https://travis-ci.org/swagger-api/swagger-codegen/builds/87853697)

**Comment by gaalandr** [comment]
swagger-api/swagger-core#1524  has to be merged first...

**Comment by wing328** [comment]
@gaalandr ok. We will wait for that before reviewing this PR.

**Comment by gaalandr** [comment]
thanks

**Comment by gaalandr** [comment]
Hi wing328

some swagger-core changes are merged into swagger-core 1.5.5-SNAPSHOT so the build of this pull request does not fail anymore. 

Can you please check, and merge if it's ok?

Regards,
Andras

**Comment by wing328** [comment]
@gaalandr reviewed and the change looks good.

**Comment by gaalandr** [comment]
Great! Thank you!

**Pull request merged**
