### PR TITLE
Added support for datetime query parameters in cpprest

### PR DESCRIPTION
**Pull request by genechang**
Signed-off-by: Gene Chang <gene.chang@anyconnect.com>

### PR checklist

- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Added an overload in apiclient-header.mustache and apiclient-source.mustache files to parameterToString for utility:datetime.  It will use datetime.to_string to convert to ISO_8601.  This was tested by generating code from our swagger and verifying the datetime object is properly converted to a URL for the GET request on the server.

### CODE REVIEW

**Comment by wing328** [comment]
@genechang thanks for the PR. Please run `./bin/cpprest-petstore.sh` so as to update the Petstore sample up-to-date.

**Comment by genechang** [comment]
@wing328 Just ran the script and updated the pull request.  Let me know what else you need me to do.  Thanks.

**Comment by wing328** [comment]
(linked to https://github.com/swagger-api/swagger-codegen/issues/4549)

**Comment by wing328** [comment]
@genechang thanks for the PR, which has been merged into master.

(we've just added Swagger Codegen to ProductHunt: https://www.producthunt.com/posts/swagger-codegen, pleae upvote if you found Swagger Codegen useful)

**Pull request merged**
