### PR TITLE
fix #3477, add RxSwift support for Swift

### LINKED ISSUE #3477: [Swift] Add RxSwift support
##### Description

We want to introduce a CLI option `supportRxSwift` to add RxSwift support to the Swift API client.

Ref: https://github.com/ReactiveX/RxSwift

If anyone wants to contribute or is interesting in the work, please reply to let us know.

### PR DESCRIPTION
**Pull request by wwwjfy**

### CODE REVIEW

**Comment by wwwjfy** [comment]
I don't know what AppVeyor means by "AppVeyor was unable to build non-mergeable pull request", as Github says there is no conflict to merge

**Comment by wing328** [comment]
Linked to #3477

**Comment by wwwjfy** [comment]
I didn't add `supportRxSwift` as a CLI option described in #3477, but a `responseAs` option, because RxSwift is very much like PromiseKit, with different way for callbacks.

**Comment by wing328** [comment]
@wwwjfy perfectly fine to use `responseAs`.

I've restarted the CI jobs and the AppVeyor has passed.

We'll review your change and let you know if we've any question.

Thanks for the contribution.

**Comment by wing328** [comment]
cc @Edubits @jaz-ah

**Comment by jaz-ah** [comment]
+1 looks good to me @wing328

**Comment by wing328** [comment]
@wwwjfy all the local Swift tests passed. Thanks for the contribution.

**Pull request merged**
