### PR TITLE
Updated feign library to use latest version of OpenFeign and Jackson.

### PR DESCRIPTION
**Pull request by oteichmann**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)
Issue-5107

### CODE REVIEW

**Comment by wing328** [comment]
@oteichmann thanks for the PR, which has been merged into master.

**Comment by wing328** [comment]
FYI. I pushed the change from master to 2.3.0 via f477ae83aab64a76adc3d22b555f64127300bef0.

I tried to updated jackson threepane version to the latest (2.8.4) but got the following error message:
```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /private/tmp/swagger-codegen/samples/client/petstore/java/feign/src/main/java/io/swagger/client/CustomInstantDeserializer.java:[8,49] cannot find symbol
  symbol:   class DateTimeUtils
  location: package com.fasterxml.jackson.datatype.threetenbp
[INFO] 1 error
```
Looks like `DateTimeUtils` has been removed in the latest version. For the time being, I keep the version at 2.6.4.

cc @cbornet

**Comment by cbornet** [comment]
Yes DateTimeUtils.timeZoneToZoneId() is now in org.threeten.bp.DateTimeUtils.toZoneId().
We should also check if this custom deserializer is still needed with the new jackson version.

**Comment by cbornet** [comment]
I confirm that the CustomInstantDeserializer is not needed anymore and must be removed.

**Pull request merged**
