### PR TITLE
[Java] Add maven-javadoc-plugin to all Java clients.

### PR DESCRIPTION
**Pull request by cliffano**
This covers issue #3499 about adding maven-javadoc-plugin to all Java clients.

### CODE REVIEW

**Comment by wing328** [comment]
@cliffano the change looks good. Do you mind updating the Java Petstore sample as well by running `/bin/java-petstore-all.sh` so that the CI can test the change?

**Comment by cliffano** [comment]
Java Petstore samples updated.

**Comment by cliffano** [comment]
@wing328 I was going to create a new PR for 1ee186694241bb6d9a0dccefcdca5afe3f5a1dd2 , forgetting that any push would be included in the current live PR.

The test failures seem to be caused by repo fetch failure and not change related.
Is there a way to re-trigger the build from contributor's end?

Please let me know if you'd like me to revert the ruby param fix on this PR.

**Comment by wing328** [comment]
@cliffano to retrigger the build, I can only think of closing and reopening the PR.

Since this PR is for Java only (accordingly to the description), I would suggest creating another PR for the Ruby parameter fix.

**Comment by cliffano** [comment]
@wing328 Done.

**Comment by wing328** [comment]
@cliffano the change looks good.

For your upcoming contributions (PRs), I would suggest you to create a new branch instead.

**Pull request merged**
