### PR TITLE
[Javascript] NPM module, bug fixes, clean-ups, unit tests

### PR DESCRIPTION
**Pull request by xhh**
This PR makes the following changes to the Javascript client codegen:

* Add `package.json` and code changes to make the generated Javascript client a valid [npm](https://www.npmjs.com/) module, which could be published to a repository like npm and be installed and used in the browser with browserify or webpack.

* Add some config options:
```
        projectName
            name of the project (Default: generated from info.title or "swagger-js-client")

        moduleName
            module name for AMD, Node or globals (Default: generated from <projectName>)

        projectDescription
            description of the project (Default: using info.description or "Client library of <projectName>")

        projectVersion
            version of the project (Default: using info.version or "1.0.0")

        projectLicenseName
            name of the license the project uses (Default: using info.license.name)
```

* Add unit tests to the Javascript Petstore sample (only a create-and-get-pet test for now)
  The test can be run locally via `npm test`, or by opening the `run_tests.html` in the browser.
  The tests of Javascript Petstore sample are also included into swagger-codegen's integration tests which will be run by travis-ci.
  See #1692

* Some bug fixes and clean-ups
  - Fixed the apiClient-related issues, see #1715
  - Fixed the `constructFromObject` issue, see #1721
  - Remove unused code in api.mustache
  - Return the promise-like object from `jQuery.ajax` in API call so that it could be used when needed (for example, it is used in the test code: PetApiTest.js)

### CODE REVIEW

**Comment by xhh** [comment]
@jfiala could you review this PR when you have time?

**Comment by jfiala** [comment]
@xhh: yes I'll do it later today!
Did I see it correctly that you are also adding test scenarios here?
I have two applications for testing (one using the plain js scenario and one with amd, it would be great to add this to the tests)...

**Comment by xhh** [comment]
@jfiala yes, the tests are added for the petstore sample here:
https://github.com/xhh/swagger-codegen/tree/javascript-testing/samples/client/petstore/javascript
like other languages, the petstore sample is used to test the generated code.

**Comment by jfiala** [comment]
great, everything looks good so far, my own tests are still green!
It would be nice to also have tests for modifying pets and use the test the other features (nested objects, enumerations, maybe also verify the Jsdoc data types and the type mappings).

**Pull request merged**
