### PR TITLE
Not compare Java String with "=="

### PR DESCRIPTION
**Pull request by sinofool**
Replaced with equals()

### CODE REVIEW

**Comment by wing328** [comment]
@sinofool thanks for the PR. There are several "ApiKeyAuth.mustache" for different Java HTTP library (e..g retrofit), etc as shown in https://github.com/swagger-api/swagger-codegen/search?utf8=%E2%9C%93&q=ApiKeyAuth.mustache+in%3Apath&type=Code.

Do you mind fixing those as well?

**Comment by sinofool** [comment]
@wing328 Sure, I will search and fix them all.

**Comment by wing328** [comment]
@sinofool thank you! Let us know if you need any help on that.

Also after the change, please run `./bin/java-petstore-all.sh` to update all the Java Petstore API client so that the CI can cover the change.

**Comment by wing328** [comment]
@sinofool the fix looks good. Thanks for the contribution.

**Pull request merged**
