### PR TITLE
[Scala][Finch] Adding security definitions to Finch

### PR DESCRIPTION
**Pull request by erikwj**
@jimschubert: An addition to #6818 
Added scalafix for cleanup
fixed an issue with the path parameters (String :: String vs string :: string) 
Some refactoring of the code 
No tests yet.

### CODE REVIEW

**Comment by jimschubert** [comment]
Thanks. I'll check this out in the next day or two. I know the Finch generator is a little bit of a beast as FP requires jumping through more hoops than OOP in mustache templates. Really appreciate the work!

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by erikwj** [comment]
Ok thanks didn't pay attention to it. Will fix it. Tonight

**Comment by erikwj** [comment]
@wing328 a full rewrite as explained in post, didn't work out. So merged the commits and added author manually. Let me know if you have any comments

**Comment by wing328** [comment]
## Upgrade Note

`date-time` is mapped to "ZonedDateTime" instead of "LocalDateTime".

To roll back the change, please use the `--type-mappings` option.

**Comment by jimschubert** [comment]
@erikwj @wing328 hey, I just saw the upgrade note from earlier today. I had planned on reviewing the new PR and never saw the update regarding the merge & manual author update. Sorry about that.

fwiw, the change looks good and I had no additional comments.

**Pull request merged**
