### PR TITLE
Issue #2564 : Modified Go generator to provide an additional CodegenP…

### PR DESCRIPTION
**Pull request by neilotoole**
…arameter value 'exportParamName' that is always exported (uppercase first letter). See Issue #2564 for more detail.

### CODE REVIEW

**Comment by wing328** [comment]
To have the param name in Pascal case, have you considered updating `toParamName` in the go generator instead? 

Ref: https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/GoClientCodegen.java#L188

**Comment by neilotoole** [comment]
@wing328 The problem is that we need that same param name in different case in different locations. Let's say the base name (in the swagger) of the param (which is a query param) is `user_id`. For the function argument, the Go convention is that this becomes `userId` (well, it should be `userID`, but that's another story), e.g. `myRestCall( userId int32 )`. That is, function parameters are `lowerCamelCase`. However, because we're using sling's QueryStruct mechanism, and we're passing  that struct outside of the package (to sling), the identifier must be `UpperCamel` in order to be exported, e.g. `type QueryParams struct { UserId    int32 ...`. If we were using a template library more sophisticated than mustache I could transform the identifier case just where it's needed for the struct in the template file.. However, I don't immediately see an alternative mechanism whereby we meet the requirements that:

- The identifier is `lowerCamel` for the function argument, per Go conventions
- The identifier is `UpperCamel` for the struct field, as required for export

I'm open to suggestion though!

**Comment by wing328** [comment]
Definitely a valid use case to have another property storing the parameter name in Pascal case.

One approach is to override `postProcessOperations` in the Go generator
similar to [this one](https://github.com/swagger-api/swagger-codegen/blob/d84f848831b66e5941ac26ba0269432959f7ebd4/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/AbstractJavaJAXRSServerCodegen.java#L114).

The param name in Pascal case can be stored in `vendorExtensions .x-param-name-pascal-case`.

**Comment by neilotoole** [comment]
@wing328 Interesting, I hadn't considered that approach, and it certainly could be done that way. However, I do sense that as we continue to improve the Go generator (there's still a lot left to meet the full spec, e.g. polymorphic return types) that we'll be needing the "export" / "PascalCase" names in several other situations, and it might be more elegant (from the template's perspective at least) for the exported name to be a first-class citizen. Also, whether we went with this PR's approach or with the vendor extension, I personally would still be inclined to name it `exportParamName` as opposed to the `x-param-name-pascal-case`, as `exportParamName` is more information-bearing... that is, it has semantic value that makes the intended purpose clearer to a reader of the template file.

**Comment by neilotoole** [comment]
@wing328 Let me know your thoughts on my comments above, and whether this PR is good to go, or if you want me to use the vendor extensions mechanism and resubmit.

**Comment by wing328** [comment]
I think both your approach and my suggested approach can meet your requirement. Let me think about it and get back to you by tomorrow.

**Comment by wing328** [comment]
@neilotoole one minor drawback I can think of with `exportParamName` is that other developers who are customizing codegen may mistakenly think that `{{exportParamName}}` is also available in other code generator (PHP, Ruby, etc) but it's not.

Given that `exportParamName` is only available to Go at the moment, I prefer using vendor extension to store it and make it accessible in the template via `{{vendorExtension.x-exportParamName}}`

**Comment by neilotoole** [comment]
@wing328 That's a fair point, I'll go the vendorExtension route.

**Comment by neilotoole** [comment]
@wing328 Created new PR per your suggestion: https://github.com/swagger-api/swagger-codegen/pull/2591

**Pull request closed without merging**
