### PR TITLE
Update samples after 2.2.2

### PR DESCRIPTION
**Pull request by ePaul**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. 

### Description of the PR

No functional changes at all, just updated the samples for all the languages mentioned in #4898.
This will later allow to see what happened when fixing the bug there.

### CODE REVIEW

**Comment by ePaul** [comment]
#4874 did the same for just the spring samples.

**Comment by wing328** [comment]
The CI (travis) issue will be resolved by https://github.com/swagger-api/swagger-codegen/pull/4904. I'll let you know once it's merged into master.

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/4904 has been merged into master. Please rebase on the latest master to see if the CI (travis) issue goes away.

**Comment by ePaul** [comment]
Rebased.

**Comment by ePaul** [comment]
@wing328 now it complains about dependencies for Scalatra:

https://travis-ci.org/swagger-api/swagger-codegen/jobs/207441746

```
[info] Set current project to scalatra-sample (in build file:/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/scalatra/)
[info] Updating {file:/home/travis/build/swagger-api/swagger-codegen/samples/server/petstore/scalatra/}scalatra...
java.lang.IllegalArgumentException: Cannot add dependency 'com.github.finagle#finch-test_2.11;0.9.2-SNAPSHOT' to configuration 'it' of module io.swagger#scalatra-sample_2.11;0.1.0-SNAPSHOT because this configuration doesn't exist!
	at org.apache.ivy.core.module.descriptor.DefaultDependencyDescriptor.addDependencyConfiguration(DefaultDependencyDescriptor.java:559)
	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:157)
	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:128)
	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:118)
	at org.apache.ivy.plugins.parser.AbstractModuleDescriptorParser$AbstractParser.parseDepsConfs(AbstractModuleDescriptorParser.java:113)
	at sbt.CustomXmlParser$CustomParser.parseDepsConfs(CustomXmlParser.scala:35)
	at sbt.IvySbt$.convertDependency(Ivy.scala:561)
	at sbt.IvySbt$$anonfun$5.apply(Ivy.scala:511)
	at sbt.IvySbt$$anonfun$5.apply(Ivy.scala:511)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
	at scala.collection.AbstractTraversable.map(Traversable.scala:105)
	at sbt.IvySbt$.addDependencies(Ivy.scala:511)
	at sbt.IvySbt$Module.configureInline(Ivy.scala:152)
	at sbt.IvySbt$Module.x$6$lzycompute(Ivy.scala:131)
	at sbt.IvySbt$Module.x$6(Ivy.scala:126)
	at sbt.IvySbt$Module.sbt$IvySbt$Module$$moduleDescriptor0$lzycompute(Ivy.scala:126)
	at sbt.IvySbt$Module.sbt$IvySbt$Module$$moduleDescriptor0(Ivy.scala:126)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:115)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:103)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:48)
	at sbt.IvySbt$$anon$3.call(Ivy.scala:57)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:98)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:81)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:102)
	at xsbt.boot.Using$.withResource(Using.scala:11)
	at xsbt.boot.Using$.apply(Using.scala:10)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:62)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:52)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:57)
	at sbt.IvySbt.withIvy(Ivy.scala:98)
	at sbt.IvySbt.withIvy(Ivy.scala:94)
	at sbt.IvySbt$Module.withModule(Ivy.scala:115)
	at sbt.IvyActions$.update(IvyActions.scala:125)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1223)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1221)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1244)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$74.apply(Defaults.scala:1242)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1246)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1241)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1249)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1214)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) java.lang.IllegalArgumentException: Cannot add dependency 'com.github.finagle#finch-test_2.11;0.9.2-SNAPSHOT' to configuration 'it' of module io.swagger#scalatra-sample_2.11;0.1.0-SNAPSHOT because this configuration doesn't exist!
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 

No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by ePaul** [comment]
Ah, I didn't actually regenerate the samples after rebasing. Trying it now for scalatra.

**Comment by ePaul** [comment]
Hmm, executing either `bin/jaxrs-jersey1-petstore-server.sh` or `bin/scalatra-petstore-server.sh` produces no change.

**Comment by ePaul** [comment]
I'll try to split this up into several PRs to isolate the problem.

**Comment by ePaul** [comment]
After showing in #4910 that the Scalatra samples are the reason for the problem, I'm rebasing this to omit the scalatra changes (as well as swift3, which is in a separate PR #4911). Let's see what CI says now.

**Comment by ePaul** [comment]
Build passed now.

**Comment by wing328** [comment]
@ePaul thanks for the PR to update the samples.

**Pull request merged**
