### PR TITLE
[JAXRS-CXF] Correct issue with void api method.

### PR DESCRIPTION
**Pull request by deblockt**
If api method don't have return, the void return type is not present.

### Description of the PR

I'have build the last version (master) of code generator. when i use jaxrs-cxf-client language. void API method don't have "void" return type. 

The generated code is like this.
``` java
@Path("/")
@Api(value = "/", description = "")
public interface ContextsApi  {

    @POST
    @Path("/contexts")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Permet de créer un nouveau contexte.", tags={  })
    public Context createContext(NewContextData newContextData);

    @DELETE
    @Path("/contexts/{idContext}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Permet de supprimer un contexte.", tags={  })
    public deleteContext(@PathParam("idContext") String idContext);

    @GET
    @Path("/contexts/{idContext}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Renvoie un contexte à partir de son ID.", tags={  })
    public Context findContextById(@PathParam("idContext") String idContext);

    @GET
    @Path("/contexts")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Renvoie la liste des contextes.", tags={  })
    public List<Context> findContexts(@QueryParam("offset")Integer offset, @QueryParam("limit")Integer limit, @QueryParam("sort")String sort);

    @PUT
    @Path("/contexts/{idContext}")
    @Consumes({ "application/json-patch+json" })
    @Produces({ "application/json" })
    @ApiOperation(value = "Permet de modifier partiellement un contexte (ajout / modification / suppression d&#39;informations) [FAKE PUT --&gt; PATCH].", tags={  })
    public  patchContext(@PathParam("idContext") String idContext, @HeaderParam("X-HTTP-Method-Override") String xHTTPMethodOverride, List<PatchOperation> patchOperations);
}
```

I'have correct the api.mustache to add "void" if no returnTypes are present

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by deblockt** [comment]
Thanks for this informations, i'have  correct the issue

**Comment by wing328** [comment]
@deblockt looks good now.

Please also run `./bin/jaxrs-cxf-petstore-server.sh` to update the Petstore sample so that the CIs can test the change.

**Comment by wing328** [comment]
I noticed that there's no Petstore sample for `jaxrs-cxf-client` at the moment. I'll create one ...

**Comment by wing328** [comment]
@deblockt thanks again for the fix. I did some tests and seems like the change will break jaxrs-cxf server generator. I ran `./bin/jaxrs-cxf-petstore-server.sh` and here is part of the change:
```
--- a/samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/api/PetApi.java
+++ b/samples/server/petstore/jaxrs-cxf/src/gen/java/io/swagger/api/PetApi.java
@@ -39,13 +39,13 @@ public interface PetApi  {
     @Path("/pet/findByStatus")
     @Produces({ "application/xml", "application/json" })
     @ApiOperation(value = "Finds Pets by status", tags={ "pet",  })
-    public List<Pet> findPetsByStatus(@QueryParam("status") @NotNull List<String> status);
+    public Pet findPetsByStatus(@QueryParam("status") @NotNull List<String> status);
 
     @GET
     @Path("/pet/findByTags")
     @Produces({ "application/xml", "application/json" })
     @ApiOperation(value = "Finds Pets by tags", tags={ "pet",  })
-    public List<Pet> findPetsByTags(@QueryParam("tags") @NotNull List<String> tags);
+    public Pet findPetsByTags(@QueryParam("tags") @NotNull List<String> tags);
 ```

Did you get similar issue when running `./bin/jaxrs-cxf-petstore-server.sh` locally?

**Comment by wing328** [comment]
https://github.com/swagger-api/swagger-codegen/pull/4823 should also fix this issue.

@deblockt please help review that change to see if it meets your need as well: https://github.com/swagger-api/swagger-codegen/pull/4823/files#diff-563d4b5a0d57e0184af3b98607bbb4a5R828

**Comment by deblockt** [comment]
I'm sorry but i'have done this update on a professional project. Now I have a new job and I don't have the sources.

**Comment by wing328** [comment]
@deblockt that's ok. Thanks for the update.

I've added Petstore samples for jaxrs-cxf-client.

I believe @jfiala also has filed another [PR](https://github.com/swagger-api/swagger-codegen/issues/4994) to fix the issue.

**Pull request closed without merging**
