### PR TITLE
[Swift] Add support for NSUUID

### PR DESCRIPTION
**Pull request by jgavris**

### CODE REVIEW

**Comment by wing328** [comment]
@jgavris thanks for the PR.

cc @Edubits @jaz-ah

**Comment by jaz-ah** [comment]
+1 - looks good @jgavris sorry to just jump on here.  @wing328 looks good to merge.

**Comment by jgavris** [comment]
@wing328 @jaz-ah Rebased after #3264

**Comment by wing328** [comment]
@jgavris thanks for the PR.

@jaz-ah thanks for reviewing the change.

**Pull request merged**
