### PR TITLE
[Qt5 C++] Actually use the model name prefix in the Qt5 generator

### PR DESCRIPTION
**Pull request by Ragnis**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Actually use the model name prefix, if one has been specified.

### CODE REVIEW

**Comment by fehguy** [comment]
@Ragnis can you specify what version of the QT framework you're testing with?  Some recent changes seem to have broken support for 5.3.x, and I think it'd be wise for us to declare what version the templates support.

**Comment by Ragnis** [comment]
I use Qt 5.7, but for this specific PR it shouldn't really matter.

**Comment by wing328** [comment]
@Ragnis thanks for the PR. When I tried to compile the Petstore project, I got the following error:
```
In file included from ../PetStore/main.cpp:2:
In file included from ../PetStore/PetApiTests.h:7:
../PetStore/../client/SWGPetApi.h:30:10: fatal error: 'SWGPet.h' file not found
#include "SWGPet.h"
         ^
1 error generated.
make: *** [main.o] Error 1
15:52:46: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project PetStore (kit: Desktop Qt 5.7.0 clang 64bit)
When executing step "Make"
15:52:46: Elapsed time: 00:01.
```
Did the project compile and the tests pass for you locally in your machine?

**Comment by Ragnis** [comment]
Are you sure you were on the correct and up-to-date branch (the branch has been rebased multiple times, this might cause problems when checking it out)?

**Comment by wing328** [comment]
I did the following early:
```
git checkout -b Ragnis-fix-model-name-prefix 2.3.0
git pull https://github.com/Ragnis/swagger-codegen.git fix-model-name-prefix
```
Later I'll give it another try using your repo directly.

**Comment by wing328** [comment]
I cloned your repo directly and tests ran fine.
```
Totals: 6 passed, 0 failed, 0 skipped, 0 blacklisted, 7642ms
```
Thanks for the contribution.

**Comment by wing328** [comment]
## Upgrade note ##

Model prefix was set to "SWG" before. Starting at version 2.3.0, model prefix will be set to `modelNamePrefix` (default to empty string) obtained via the configuration.

To keep "SWG" as the prefix, just set `modelNamePrefix` to "SWG" when generating the `qt5cpp` client.

**Pull request merged**
