### PR TITLE
[Scala][Finch] Fix interpretation of queryParams and headers

### PR DESCRIPTION
**Pull request by jfraudeau**
Interpretation of parameters by the Finch server generator is broken, this commit fixes it partially

### CODE REVIEW

**Comment by wing328** [comment]
@jfraudeau thanks for the PR.

cc @clasnake @jimschubert

**Comment by jimschubert** [comment]
This looks good. What are remaining todos (referred to as "partially" above)?

**Comment by jfraudeau** [comment]
I didn't check the specs so I can't say for sure. Off the top of my head  it misses at least : 
 - Cookie parameters
 - Query parameters and Header that are not interpreted as strings
 - All arities aren't always handled
 - Code is ugly as hell

**Comment by wing328** [comment]
PR merged into master.

For the enhancements, it's tracked under https://github.com/swagger-api/swagger-codegen/issues/6818

**Pull request merged**
