### PR TITLE
[JAXRS] Issue 4581 - Added flag useGenericWsResponse

### PR DESCRIPTION
**Pull request by markus-wa**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

This PR adresses #4581 and adds a new flag `useGenericWsResponse` for JAXRS-Server code generators.

When the flag is set operations in the ServiceApi interface return the type javax.ws.rs.core.Response instead of the actual return type. This allows for setting custom 'success' HTTP return codes like 299 instead of the default of 200.

Currently the flag only takes effect for CXF, all other APIs already default to returning javax.ws.rs.core.Response

Example:

Without useGenericWsResponse
```java
...
public User getUserByName(@PathParam("username") String username);
```
useGenericWsResponse=true
```java
import javax.ws.rs.core.Response;
...
public Response getUserByName(@PathParam("username") String username);
```

### CODE REVIEW

**Comment by markus-wa** [comment]
Squashed commits

**Comment by jfiala** [comment]
@markus-wa in fact I did the same for cxf on 2017-02-12 days ago, I used CLI useGenericResponse: #4779

**Comment by jfiala** [comment]
@markus-wa looks pretty the same, I added some more code in the apiServiceImpl.mustache so the API is already implemented using JAXRS Response.

**Comment by markus-wa** [comment]
@jfiala I see, didn't see it linked to #4581 so I missed it. Closing this one in that case.

**Pull request closed without merging**
