### PR TITLE
Add option for resolveFully

### PR DESCRIPTION
**Pull request by jweisman**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Add option to set `ParseOptions.setResolveFully` to fully walk the reference tree for responseBodies and schemas.

### CODE REVIEW

**Comment by daemonfire300** [comment]
@jweisman I could test this against my locally present collection of yaml's to check whether this is working, but need to figure out the command parameters again, since it has been quite some time since I had a look at this.

**Comment by jweisman** [comment]
Hi @daemonfire300 - I used the following to test:
```
java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate \
-i https://developers.exlibrisgroup.com/wp-content/uploads/alma/openapi/users.json \
-l java \
-o ~/java-client \
--resolve-fully
````

**Comment by HugoMario** [comment]
Hi @jweisman , thanks for your PR's and sorry for delay on previous one. Please, ping me next time you want a PR be merged. I really like the idea of adding the resolve-fully feature as an option, in that case we dont force to anybody to use it if they dont want.

**Comment by HugoMario** [comment]
please build

**Comment by HugoMario** [comment]
thanks again @jweisman !!!

**Pull request merged**
