### PR TITLE
Fixed unicode error and supported allow_nonstandard_methods in tornado based python client

### PR DESCRIPTION
**Pull request by shwetas1205**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

This PR will fix https://github.com/swagger-api/swagger-codegen/issues/7559 and https://github.com/swagger-api/swagger-codegen/issues/7109

1) Setting  _allow_nonstandard_methods_ flag by default to TRUE to make sure that tornado client can be used for DELETE and other methods with body.

2) six.u does not support Unicode as an input and end up throwing exception in python2 for unicode inputs. Now, using six.text_type to for reliable conversion.

### CODE REVIEW

**Comment by wing328** [comment]
@shwetas1205 thanks for PR.

cc @taxpon @frol @mbohlool @cbornet @kenjones-cisco for review.

**Comment by kenjones-cisco** [comment]
LGTM

Thanks for the PR.

**Comment by frol** [comment]
LGTM

@shwetas1205  Thank you for the fix!

**Comment by wing328** [comment]
@shwetas1205 thanks for the PR, which has been merged into master.

@kenjones-cisco @frol thanks for the prompt review of this PR.

**Comment by shwetas1205** [comment]
Awesome. Thanks a lot @wing328 @frol @kenjones-cisco for the quick turnaround

**Pull request merged**
