### PR TITLE
[Flutter/Dart] - Add flutter client generator

### LINKED ISSUE #7367: [Dart/Flutter] Dart files generated not working on flutter platform
##### Description

The code generated by the [DartClientCodegen](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/DartClientCodegen.java) is not working in flutter projects since it relies on dartson which relies on [dart-mirrors](https://api.dartlang.org/stable/1.24.3/dart-mirrors/dart-mirrors-library.html). dart-mirrors is not supported in flutter and [maybe never will be](https://github.com/flutter/flutter/issues/1150#issuecomment-254033107).

I'd suggest to either change it or add a new generator specifically for flutter. I started with a new generator for now [which I started](https://github.com/Jimdo/swagger-codegen/tree/add-flutter-client-generator) as a copy of the existing Dart generator.

##### Swagger-codegen version

2.3.0

##### Swagger declaration file content or url

Reproducible with any kind of declaration file, since it is a basic serialization/deserialization problem.

##### Command line used for generation

```
java -jar swagger-codegen-cli.jar generate -l dart -i swagger.yaml  \
        -o ./api-client -DbrowserClient=false
```

##### Suggest a fix/enhancement

As mentioned above I'd try to add a new generator which generates dart code compatible to flutter.

### PR DESCRIPTION
**Pull request by joernahrens**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Resolves #7367 

PTAL @ircecho 

The dart code generated by the `DartClientCodegen` is not working with [Flutter](https://flutter.io/) due to the usage of [dartson](https://pub.dartlang.org/packages/dartson), which uses dart-mirrors. This PR introduces a generator specifically for Flutter which generates flutter-compatible Dart code.

Basically I copied the dart-related code and made changes to it. 

#### Sample 

In `/samples/client/petstore/flutter` I created a flutter app which is basically doing some petstore API calls and logging the output.

This is not to see as a complete solution, I didn't test every feature of swagger, for example I left out authentication completely for now. There might be still a decent amount of work to be done for that.
But the sample shows that there are some things working already. If you want to test that you will have to setup the [Flutter SDK](https://flutter.io/setup/). Afterwards running the app from the folder `/samples/client/petstore/flutter/flutter_petstore` should be working and show you some API responses in the console output.

#### Output
```bash
$ flutter run
Launching lib/main.dart on Pixel in debug mode...
Initializing gradle...                                1.0s
Resolving dependencies...                             1.3s
Running 'gradlew assembleDebug'...                    8.5s
Built build/app/outputs/apk/app-debug.apk (22.9MB).
Installing build/app/outputs/apk/app.apk...           6.0s
I/FlutterActivityDelegate( 3435): onResume setting current activity to this
Syncing files to device Pixel...
I/flutter ( 3435): fetching pets by status...
I/flutter ( 3435): fetching inventory...
I/flutter ( 3435): fetching user1...
I/flutter ( 3435): user received:
I/flutter ( 3435): User[id=0, username=user1, firstName=FN, lastName=LN, email=user1@ssgcard.com, password=password, phone=string, userStatus=0, ]
I/flutter ( 3435): inventory received:
I/flutter ( 3435): {available%')) RLIKE SLEEP(4) AND (('%'=': 1, available%')) RLIKE (SELECT * FROM (SELECT(SLEEP(4)))rGyM) AND (('%'=': 1, unavailable: 36, available;SELECT COUNT(*) FROM DOMAIN.DOMAINS AS T1,DOMAIN.COLUMNS AS T2,DOMAIN.TABLES AS T3# DENYALLjCod: 1, '--: 1, available) AND 3610=(SELECT COUNT(*) FROM SYSMASTER:SYSPAGHDR)--: 1, 21121212212: 1, aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

🔥  To hot reload your app on the fly, press "r". To restart the app entirely, press "R".
An Observatory debugger and profiler on Pixel is available at: http://127.0.0.1:8106/
For a more detailed help message, press "h". To quit, press "q".
I/flutter ( 3435): pets received:
I/flutter ( 3435): [Pet[id=9123612807670197307, category=Category[id=0, name=string, ], name=<IMG SRC=&#x6A&#x61&#x76&#x61&#x73&#x63&#x72&#x69&#x70&#x74&#x3A&#x61&#x6C&#x65&#x72&#x74&#x28&#x27&#x58&#x53&#x53&#x27&#x29>, photoUrls=[string], tags=[Tag[id=0, name=string, ]], status=available, ], Pet[id=9123612807670197310, category=Category[id=0, name=string, ], name=<IMG SRC="jav&#x0A;ascript:alert('XSS');">, photoUrls=[string], tags=[Tag[id=0, name=string, ]], status=available, ], Pet[id=9123612807670197312, category=Category[id=0, name=string, ], name=perl -e 'print "<IMG SRC=java\0script:alert(\"XSS\")>";' > out, photoUrls=[string], tags=[Tag[id=0, name=string, ]], status=available, ], Pet[id=9123612807670197313, category=Category[id=0, name=string, ], name=perl -e 'print "<SCR\0IPT>alert(\"XSS\")</SCR\0IPT>";' > out, photoUrls=[string], tags=[Tag[id=0, name=string, ]], status=available, ], Pet[id=9123612807670197314, category=Category[id=0, name=string, ], name=<IMG SRC=" &#14;  javascript:alert('XSS');">, photoUrls=[string]
I/flutter ( 3435): Order[id=0, petId=9123612807670197307, quantity=1, shipDate=null, status=null, complete=false, ]
```

Btw, the output of the inventory looks really weird, but it looks the same when using [Swagger UI](http://petstore.swagger.io/#/store/getInventory)

### CODE REVIEW

**Comment by ircecho** [comment]
This looks fabulous! Actually I wanted to get rid of dartson for a long time, and was thinking about using an approach that would have been very similar to yours!

A few questions:

1. Would it be possible to get rid of the old code altogether and use the new generator for both flutter and dart? Or is there anything flutter-specific in the new code generator?
2. Did you try this with dartdevc?

**Comment by joernahrens** [comment]
Thanks for the feedback @ircecho! I just wanted to get it done ™️  for flutter, without breaking anything for users of the existing Dart generator. I even removed the [browserClient](https://github.com/swagger-api/swagger-codegen/blob/master/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/DartClientCodegen.java#L25) switch because it doesn't make sense for flutter (so, I didn't try `dartdevc`).

But generally it should be possible, I don't use anything flutter-specific. I will give it a try and report in the next days.

**Comment by joernahrens** [comment]
Closing this one in favor of https://github.com/swagger-api/swagger-codegen/pull/7418

**Comment by kirikakis** [comment]
Good work!! It is lean and does not break dart.
I am using the latest 2.4.0 version and still the generated [api](https://github.com/swagger-api/swagger-codegen/blob/master/samples/client/petstore/dart/swagger/lib/api.dart) has dependency to the 'http/browser_client.dart'. I am doing something wrong here?

**Comment by joernahrens** [comment]
@kirikakis  When generating your code you have to supply this configuration parameter: 
`-DbrowserClient=false`

```
```

**Pull request closed without merging**
