### PR TITLE
Update APIHelper.mustache so that it can handle real boolean to string conversion

### PR DESCRIPTION
**Pull request by JMDHo**
This is a fix attempt for : [Swift] Bool value conversion #2446 
It is copied from http://stackoverflow.com/questions/36185530/how-to-check-dictionary-value-to-be-exactly-a-bool/36186159#36186159

### CODE REVIEW

**Comment by cjolif** [comment]
this should help, but this does seem to solve the full issue, this probably needs to be called somewhere to fix the conversion when it occurs.

**Comment by JMDHo** [comment]
the [PR#2705](https://github.com/swagger-api/swagger-codegen/issues/2705) i just entered implements the fix entered here and also contains a reproducing sample.

**Comment by wing328** [comment]
@JMDHo do you mind adding this commit to #2705 and close this PR? You can do so using `cherry-pick` in git.

**Comment by JMDHo** [comment]
ok, will do that

**Comment by JMDHo** [comment]
ok, cherry-pick performed. closing this PR.
It is replaced with PR [PR 2705](https://github.com/swagger-api/swagger-codegen/pull/2705)

**Pull request closed without merging**
