### PR TITLE
Qt5cpp plug memleaks

### PR DESCRIPTION
**Pull request by etherealjoy**
### PR checklist

- [X] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [X] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [X] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [X] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Remove some Memory Leaks in the Model Factory and API

cc @fvarose @stkrwork @ravinikam 

Plug some of the Qt Memory leaks.
Based on #7194 by @antis81

### CODE REVIEW

**Comment by antis81** [comment]
Gave it a short review. -> Looking good in general, only some tests seem to fail. Prbly those need a little adjustment…

**Comment by etherealjoy** [comment]
Tests
[X] PetStore Examples updated and passed
[X] Docker API used for fetching container images and starting containers

**Comment by etherealjoy** [comment]
Next set of updates planned would be to 
- QSharedPointer for member objects in the models
- QSharedPointer for API Callbacks to ensure the memory de-allocation happens automatically after the callback has been invoked after the Endpoint API is called.

**Comment by etherealjoy** [comment]
@wing328 Why does the circleci failed? I tested the petstore samples with the IDE and they passed.

**Comment by wing328** [comment]
@etherealjoy probably due to maven repo throttling the connection to download dependencies.

I've restarted the job and the result is good.

**Comment by etherealjoy** [comment]
Hi @fvarose @stkrwork @ravinikam
Any news :(

**Comment by wing328** [comment]
@etherealjoy as always, thanks for your work 👍 

@stkrwork thanks for reviewing the change.

**Pull request merged**
