### PR TITLE
[Java] Interpret consumes '*/*' as 'application/json'

### PR DESCRIPTION
**Pull request by lwander**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

I'm having trouble with the `./bin/java-petstore-all.sh` script since it's introducing a lot of changes unrelated to this change, even when I run against `upstream/master` with no changes staged. It seems like at some point changes to the templates were not checked in alongside their changes to the petstore examples.

### Description of the PR

Servers can describe their desired (consumed) content type for an operation as "*/*", which the current swagger API sends as the content type for any request against that operation. This is troublesome because "*/*" provides no info to the server as to what is being sent. Given that swagger already defaults to "application/json", this seems appropriate.

### CODE REVIEW

**Comment by wing328** [comment]
@lwander thanks for the PR. The change is for "jersey1.x" Java API client but I believe Kubernetes is using the default (okhttp-gson): https://github.com/kubernetes-client/java/blob/master/kubernetes/pom.xml#L198

I'll file a PR shortly to add the enhancement to other Java's ApiClient.mustache (some other generators such as Ruby, PHP also have such enhancements but we'll review again to ensure all generators have the same enhancement in place)

**Comment by wing328** [comment]
FYI. Filed https://github.com/swagger-api/swagger-codegen/pull/6188 for other Java API clients.

**Comment by lwander** [comment]
Thanks @wing328, I appreciate all the help

**Comment by chlung** [comment]
@wing328 Do you know when v2.3.0 will be released.  thanks.

**Comment by wing328** [comment]
@chlung we hope to release it by the end of Aug.

**Comment by chlung** [comment]
@wing328  thanks.  If we would like to try v2.3.0 locally to build k8s-client java api, do you know the procedures/steps to do that?

**Comment by wing328** [comment]
Please try the snapshot version: https://github.com/swagger-api/swagger-codegen#compatibility

**Comment by chlung** [comment]
@wing328 thanks

**Pull request merged**
