### PR TITLE
Update JMustache dependency to support whitespace and line breaks trimming

### PR DESCRIPTION
**Pull request by stremlenye**
To support nice structured `mustache` syntax, mentioned [here](https://github.com/samskivert/jmustache#newline-trimming).

### CODE REVIEW

**Comment by wing328** [comment]
@stremlenye thanks for the PR. How urgent do you need the new syntax?

We'll need to review the existing mustache templates on the impact (e.g. newline trimming).

Personally I like the new syntax as it would make my life easier output the code the way I want.

**Comment by stremlenye** [comment]
@wing328 thanks for coming up so fast!
I've already 'workarounded' that in my local mustache templates, so thats not urgent. But at some point I want to get rid of that mess which I currently have in templates.
Just tell me if I could help you somehow.
P.S. I've haven't found tests for the generated code. Is there any?

**Comment by wing328** [comment]
To test, please run `mvn verify -Psamples` (the same command used by travis-ci) given that you've updated the sample (e.g. by running ./bin/php-petstore.sh to update PHP Petstore)

**Comment by stremlenye** [comment]
Sure, thanks.

**Comment by wing328** [comment]
PR merged.

**Comment by stremlenye** [comment]
👍

**Pull request merged**
