### PR TITLE
Closes #2118

### LINKED ISSUE #2118: JMeter API ignores basePath in service URL
Spec: https://gist.github.com/foragerr/1daf27b05abab842d197
codegen version: 2.1.5
Language: JMeter

As the title says, basePath should be added to the URL, but is completely dropped by JMeter codegen.

### PR DESCRIPTION
**Pull request by foragerr**
Add basePath without url to jmeter sampler path

### CODE REVIEW

**Comment by wing328** [comment]
@foragerr thanks for the PR. If someone already has `x-path` set, would that result in duplicated base path?

**Comment by foragerr** [comment]
unsure. How does one set `x-path`?
[Looks like JMeter codegen sets `x-path` BTW](https://github.com/swagger-api/swagger-codegen/blob/ee8547f3b4e6260c6b9ae3dbfd94652109adcb3e/modules/swagger-codegen/src/main/java/io/swagger/codegen/languages/JMeterCodegen.java#L109)

**Comment by wing328** [comment]
Looks like it's adding $ as a prefix to some variables. My guess is that it's for JMeter to recognize that as a variable.

**Comment by wing328** [comment]
My guess is that the author of the JMeter template does to use base path (e..g /v2) in his/her API.

We'll go with your change. Thanks again with the PR.

**Comment by foragerr** [comment]
`${...}` is indeed a variable in JMeter.

**Comment by wing328** [comment]
Ok. Learned something today :smiley:

**Comment by wing328** [comment]
One suggestion if you don't mind. For upcoming PR. I would recommend creating a new branch for the change.

**Comment by foragerr** [comment]
Sure, that makes sense. I was wondering about that when I wanted to push some changes before you merged PR.

**Pull request merged**
