### PR TITLE
[Java] Add auto-generated documentation in Markdown to Java clients

### PR DESCRIPTION
**Pull request by xhh**
Add auto-generated documentation in Markdown to Java clients: default, jersey2 and okhttp-gson.

See [here](https://github.com/xhh/swagger-petstore-java) for the generated docs for the petstore sample.

Related: #2320 (Markdown docs for Perl)

### CODE REVIEW

**Comment by KevinGlinski** [comment]
what happened to this PR?  we are in the need for java doc

**Comment by wing328** [comment]
@KevinGlinski  It's been merged already. Please pull the latest master and give it a try.

**Comment by KevinGlinski** [comment]
my bad, missed it in the src when looking yesterday and saw the revert pr 2679 so thought it was put in and taken back out.

Thanks!

**Comment by wing328** [comment]
@KevinGlinski no problem. Let me know if you've any feedback on the auto-generated documentation.

**Pull request merged**
