### PR TITLE
Fix Java CXF on parameter names containing '_' or '-'

### PR DESCRIPTION
**Pull request by salemXpresso**
[java-cxf] 	Fix Java CXF on parameter names containing '_' or '-'. The template uses only the parameter name which result on misnaming parameters.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: http://stackoverflow.com/questions/3042437/change-commit-author-at-one-specific-commit

**Comment by wing328** [comment]
@salemXpresso I believe your fix is for XML only. Can you also fix the issue for JSON as well?

**Comment by salemXpresso** [comment]
It's not a problem if I am not counted among contributors. Thanks anyway for mentioning it.

The annotations @XmlElement is not dedicated to XML, it's also used for JSON as well. For my part, I am impacted with JSON elements and this annotation solves the problem. Would you like me to send you an example ?

**Comment by wing328** [comment]
@salemXpresso thanks for the details. Please also run `./bin/jaxrs-cxf-petstore-server.sh` to keep the Petstore sample up-to-date.

**Comment by salemXpresso** [comment]
@wing328 The petstore is now up to date.

**Pull request merged**
