### PR TITLE
minor bug fixes and enhancement to Swagger.php

### PR DESCRIPTION
**Pull request by wing328**
add logic to handle all 2xx response code
bug fix for string response
bug fix for showing error message using serialize
update php petstore sample

### CODE REVIEW

**Comment by wing328** [comment]
Here is more information about the bug: json_decode($response)->message will result in exception since not *all* error response is in JSON format and has a property named "message" (it could be error_message, err_message, error, etc)

**Comment by fehguy** [comment]
we know the response model and the error model, so we should construct the proper types, correct?

**Comment by wing328** [comment]
Ideally yes. I'd a look at other API clients (e.g. Java) and it simply returns the entity (body) at the moment

```
    else {
      throw new ApiException(
                response.getClientResponseStatus().getStatusCode(),
                response.getEntity(String.class));
    }
```
One of the goals of this PR is to avoid `json_decode($response)->message` throwing exception. Later we can further enhance it with the error model defined by the user.

**Comment by fehguy** [comment]
yes, that makes sense.  The PR isn't mergable, can you see about addressing that?

**Comment by wing328** [comment]
pushed the change to resolve the conflicts

**Pull request merged**
