### PR TITLE
Build and upload Swagger Codegen CLI Docker image on release

### PR DESCRIPTION
**Pull request by arnested**
### PR checklist

- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Follow-up on the improved Docker stuff in #2945 this pull request adds building and uploading a [Swagger Codegen CLI Docker image](https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/) to Docker Hub on releases.

### CODE REVIEW

**Comment by arnested** [comment]
I had to add running `mvn verify -Psamples` in batch mode (`mvn --batch-mode verify -Psamples `) to make mvn be less verbose when downloading ressources (it was by Travis' log limit of 4 MB).

**Comment by arnested** [comment]
@fehguy, I guess you are the one to have a look at this? Would you also consider manually pushing v2.2.2 og Swagger Codegen CLI to https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/?

**Comment by wing328** [comment]
@arnested one question if you don't mind. Does it mean pull request (not yet approved) will also update the docker images and push those to the docker hub?

**Comment by arnested** [comment]
It does the same as it does for the https://hub.docker.com/r/swaggerapi/swagger-generator image.

Pushing a versioned tag for future releases and pushes to `latest` for master).

**Comment by wing328** [comment]
Just to be clear. I'm not saying your PR introduces additional issue.

Since the commands are triggered by PR (not yet approved) as well, I was wondering what if the PR has issue (e.g. due to bad changes). Would the images in docker hub still be updated regardless? If yes, then maybe we should only push `master` to docker hub if possible (assuming my understanding of the potential issue is correct).

**Comment by arnested** [comment]
Nitpicking is fine :smile:

Only tags will trigger a tagged push to Docker Hub.

The push to the `latest` on Docker Hub will happen just like the existing [Swagger Generator](https://hub.docker.com/r/swaggerapi/swagger-generator/) image: For pushes to master and pull request coming from the same repos (which I don't think ever happens).

Actually it will happen whenever the `DOCKER_HUB_EMAIL`, `DOCKER_HUB_USERNAME`, and `DOCKER_HUB_PASSWORD` are present in the build and since the Travis configuration seems to have marked them as secure this only happens on pushes/pull requests from the same repos.

I guess it would make sense to tighten this to only pushes to master (although this is no worse than what is already done for the generator images).

I'll give it shot on improving this later today.

**Comment by arnested** [comment]
I have added a commit that should ensure pushes to Docker Hub only happens for `master` and tags.

**Comment by wing328** [comment]
@arnested I'm sorry I sound like nitpicking 😞  and thanks for updating the PR to address my concern. The change looks good to me.

@fehguy does the change look good to you as well?

**Comment by arnested** [comment]
Don't worry. Nitpicking was meant in a positive way (carring for details).

**Comment by wing328** [comment]
@arnested PR merged into master. Developers using the docker images will likely find this enhancement useful.

cc @fehguy

**Comment by arnested** [comment]
Thank you, @wing328!

The image was build on master and pushed to latest as it was supposed to: https://hub.docker.com/r/swaggerapi/swagger-codegen-cli/tags/

**Pull request merged**
