### PR TITLE
improved Multipart/form-data file upload support

### LINKED ISSUE #3389: Generated JAVA API does not support file upload
##### Description

I generated a Java API which should allow me to upload files, but it does not. Looks like there is something wrong with choosing the right content type

##### Swagger declaration file content or url

#...
basePath: /
produces:
  - application/json
paths:
  /1/upload:
    post:
      summary: Upload document
      operationId: upload
      parameters:
     #...
        - name: file1
          in: formData
          description: File 1 
          required: true
          type: file
      responses:
        default:
          description: UploadResponse
          schema:
            $ref: '#/definitions/UploadResponse'         
#...
definitions:
  UploadResponse:
    type: object
    properties:
      taskId:
        type: string
#...

##### Steps to reproduce

1. Generate JAVA API
2. use upload

### PR DESCRIPTION
**Pull request by kartenkarsten**
this code will fix #3389 ( change of content Type to MediaType.APPLICATION_OCTET_STREAM_TYPE)
+ possibility for multi file upload (as List)

### CODE REVIEW

**Comment by wing328** [comment]
@kartenkarsten thanks for the PR. Please also run `./bin/java-petstore-all.sh` to update Java Petstore sample so that the CI can test the change.

**Comment by wing328** [comment]
Also please note that the `ApiClient.mustache` you updated is for Jersey1.x.

Since Swagger Codegen v2.2.0, Java API client uses `okhttp-gson` by default.

**Comment by kartenkarsten** [comment]
@wing328 I get no additional changes by running  `./bin/java-petstore-all.sh` do I have to do something else?

We used the codegen from [http://editor.swagger.io/#/](http://editor.swagger.io/#/) some days ago, but you are right - now it uses `okhttp-gson`. So it might be allready fixed.

**Comment by kartenkarsten** [comment]
`okhttp-gson` can handle single Files uploaded in a multipart body. A List of Files is not possible right now.

so this PR wont change anything on a currently generated java-client because of library change. Maybe a new PR for current code is requrired.

**Comment by wing328** [comment]
@kartenkarsten  I did a test locally in my machine by running `mvn clean && ./bin/java-petstore-jersey1.sh` but the code won't compile:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.3.2:compile (default-compile) on project swagger-java-client: Compilation failure: Compilation failure:
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/ApiClient.java:[519,51] error: ';' expected
[ERROR] /Users/williamcheng/Code/swagger-api/swagger-codegen/samples/client/petstore/java/jersey1/src/main/java/io/swagger/client/ApiClient.java:[522,10] error: 'else' without 'if'
```
Would you please take a look ?

**Comment by wing328** [comment]
I could no longer repeat the compilation error. PR merged. Thanks for your contribution.

**Pull request merged**
