### PR TITLE
[python] fix tests, tornado ssl fix

### PR DESCRIPTION
**Pull request by tomplus**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

Fixes related to:

1. Travis doesn't know that tests fail because an exit codes from bash scripts are always zero - fixed
2. Tornado client doesn't work in python < 2.7.9 - fixed
3. Some tests are skipped because public PetStore endpoint has incorrect data. Travis use local instance of PetStore server and all test can run. I removed `@skip` and also force endpoint name to `localhost`. IMO it'll remind developers about starting a local instance. #6907 

Please take a look: @wing328 @taxpon @frol @mbohlool @cbornet @kenjones-cisco

### CODE REVIEW

**Comment by frol** [comment]
> Travis doesn't know that tests fail because an exit codes from bash scripts are always zero - fixed

Does this mean that flake8 failure will be also ignored? Should we use `set -e` or run the scripts with explicit `bash -e ./test_python2_and_3.sh`?

**Comment by tomplus** [comment]
Travis sees an exit code from a script but it's exit code from last command. So now we have situation where python test failed but flake8 "covers" it and returns 0. Now I exit immediately if python tests failed. flake8 is a last command so its code will be interpreted correctly. If flake return non-zero code, Travis will notice it.

I consider using `set -e` but I think it would be too big change in this quite simple case.

**Comment by tomplus** [comment]
> Tornado client doesn't work in python < 2.7.9 - fixed

Finally I had to drop compatibility with older Python. It's more complicated and I'll fix it in next PR.

**Comment by frol** [comment]
Looks good to me!

**Comment by wing328** [comment]
cc @toumorokoshi as well

**Pull request merged**
