### PR TITLE
Formdata parameter fix in spring

### PR DESCRIPTION
**Pull request by demtnt**
As per documentation https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/bind/annotation/RequestPart.html @RequestParam should be used instead of @requestpart if not file.

### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [ ] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming langauge.

### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by wing328** [comment]
cc @bbdouglas @JFCote @sreeshas @jfiala @lukoyanov @cbornet

**Comment by cbornet** [comment]
@demtnt please update the samples for spring

**Comment by wing328** [comment]
>Annotation that can be used to associate the part of a "multipart/form-data" request with a method argument.

@demtnt What if the request content-type is `x-www-form-urlencoded`? Would this change still be applicable?

**Comment by wing328** [comment]
Related: https://github.com/swagger-api/swagger-codegen/issues/6438

**Comment by wing328** [comment]
Tests passed via https://circleci.com/gh/swagger-api/swagger-codegen/2778

**Pull request merged**
