### PR TITLE
implemented tornado-based client.

### PR DESCRIPTION
**Pull request by toumorokoshi**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: master for non-breaking changes and `3.0.0` branch for breaking (non-backward compatible) changes.

### Description of the PR

Similar to #6245, this adds support in Python for the [tornado](http://tornadoweb.org/) web framework.

### CODE REVIEW

**Comment by wing328** [comment]
@toumorokoshi thanks for the PR. We may need your help to setup integration tests for tornado &asyncio Python clients in CircleCI later.

cc @taxpon @scottrw93 @frol

**Comment by frol** [comment]
Looks good to me.

@toumorokoshi Thank you for the contribution!

**Comment by toumorokoshi** [comment]
Thanks! I can take a look at integration tests, is there any guide I can visit to learn more about how to add those?

**Comment by wing328** [comment]
Sure, I'll add some doc on how to add integration tests for new samples in https://github.com/swagger-api/swagger-codegen/wiki/Integration-Tests by coming Friday.

**Comment by wing328** [comment]
Updated https://github.com/swagger-api/swagger-codegen/wiki/Integration-Tests#how-to-add-integration-tests-for-new-petstore-samples

Please take a look to see if the instructions are clear when you've time.

**Pull request merged**
