### PR TITLE
[WIP][Scala] Finch generator

### PR DESCRIPTION
**Pull request by wing328**
### PR checklist
- [ ] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [ ] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [ ] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
### Description of the PR

Still work in progress. Here are some of the errors when running `sbt test`

```
[error] /Users/williamcheng/Code/jul2016/swagger-codegen/samples/server/petstore/finch/src/main/scala/endpoint.scala:270: identifier expected but ']' found.
[error]   def logoutUser(db: PetstoreDb): Endpoint[] =
[error]                                            ^
[error] /Users/williamcheng/Code/jul2016/swagger-codegen/samples/server/petstore/finch/src/main/scala/endpoint.scala:279: ']' expected but ';' found.
[error]   def updateUser(db: PetstoreDb): Endpoint[] =
[error] ^
[error] /Users/williamcheng/Code/jul2016/swagger-codegen/samples/server/petstore/finch/src/main/scala/endpoint.scala:279: identifier expected but ']' found.
```

(I'll do a rebase later to resolve the merge conflicts)

### CODE REVIEW

**Comment by wing328** [comment]
UPDATE: rebase on the latest master to resolve merge conflicts

**Comment by clasnake** [comment]
Have fetched the feature branch and continued with the work now.

**Comment by jimschubert** [comment]
I just saw this. I'll pull it and take a look

**Comment by jimschubert** [comment]
@clasnake @wing328 I checked this out, and made a few changes on my fork's branch:

https://github.com/jimschubert/swagger-codegen/tree/jrs-finch-generator

In the branch, I have fixes for the casecodecX counts required for the parameter count in models via extensions. Also:

* sorted API code out
* removed Scalatra and other unused references
* cleaned up endpoint.scala
* provided an service loaded data accessor in place of the PetstoreDb object

There are a few other things to fix, mostly parameter inputs, but I think it's close.

**Comment by wing328** [comment]
@jimschubert 👍 please submit a PR against my branch so that I can include the enhancements you've made.

**Comment by jimschubert** [comment]
@wing328 sure, I opened a PR against your branch.

Have you used hub (https://hub.github.com/)? I believe you could just do the following with hub:

```
git fetch jimschubert
git merge jimschubert/jrs-finch-generator
```

Then again, with the PR I opened you could apply the changes directly to your working branch:

```
git am -3 https://github.com/wing328/swagger-codegen/issues/9
```

**Comment by jimschubert** [comment]
Lol. I just saw the merge commit in my email and noticed one of the messages said "Removed Finatra stuff". Should have said Scalatra.  I use Finatra at work, and typed it out of habit.

**Comment by wing328** [comment]
@jimschubert that's fine. Don't worry about the commit message.

Is this ready for a beta release?

**Comment by jimschubert** [comment]
@wing328 my PR against yours was missing a couple things. The main one was passing parameters correctly to the verb method. As it is now, it shouldn't compile.

I could look at it a little more later.

**Comment by schrepfler** [comment]
Targetting swagger 2.x or 3.x?

**Comment by wing328** [comment]
Swagger Codegen relies on Swagger Parser (another git project) to parse the Swagger/OpenAPI spec 2.x.

I believe the support for OpenAPI 3.x in Swagger Parser is still in progress.

**Comment by ePaul** [comment]
@wing328 @jimschubert This change (specifically the build.sbt with the dependencies change) seems to have broken the Travis CI build (see #4910 for the updated samples and [the Travis build job](https://travis-ci.org/swagger-api/swagger-codegen/builds/207637284) linked from there).

I don't really now anything about SBT, so I can't really fix this.

**Comment by jimschubert** [comment]
@ePaul it looks like `modules/swagger-codegen/src/main/resources/scalatra/build.sbt` was modified by accident. I'll revert those change and open a PR for it shortly.

**Pull request merged**
