### PR TITLE
 [python][client] Comment out useless imports

### PR DESCRIPTION
**Pull request by wy-z**
### PR checklist

- [x] Read the [contribution guidelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates). Windows batch files can be found in `.\bin\windows\`.
- [x] Filed the PR against the correct branch: `3.0.0` branch for changes related to OpenAPI spec 3.0. Default: `master`.
- [x] Copied the [technical committee](https://github.com/swagger-api/swagger-codegen/#swagger-codegen-technical-committee) to review the pull request if your PR is targeting a particular programming language.

### Description of the PR

- [python][client] Comment out useless imports to avoid circular importation https://github.com/swagger-api/swagger-codegen/issues/7541

### CODE REVIEW

**Comment by cbornet** [comment]
These imports are at least used for the docstrings so I don’t think they can be removed like this.

**Comment by wy-z** [comment]
See #7541 , any PR is welcome~

**Comment by wing328** [comment]
@wy-z I think a proper way to do it is to loop through the `imports` in `postProcessModels` and remove it if it's the same as the model name.

**Comment by wing328** [comment]
Sorry we've to close this one. Please open a new one with the suggested fix.

**Comment by tomplus** [comment]
@cbornet AFAIK docstrings don't require imports. Python complains about these imports too (it's the reason why there is F401 directive for pylint).

@wing328 removing self-import was implemented by removing the first item from the list. We can do it better as you suggest, but the biggest problem is with circular dependencies. I have no idea how to fix it - it'll simpler to delete it.

**Comment by wing328** [comment]
@tomplus right. Let's go with removing it first.

@wy-z If there's a minimal spec to reproduce the issue, please share as it can help verify the fix later.

**Pull request closed without merging**
