### PR TITLE
[Swift] Use the latest Alamofire (3.4.1)

### PR DESCRIPTION
**Pull request by JackWink**
This commit updates the Swift client templates to be compatible with the
latest version of Alamofire. It bumps the dependency version in the
podspec and names the argument when calling `responseData`. We found
that XCode was having trouble with the overloaded methods and needed the
named argument for hinting.

### CODE REVIEW

**Comment by wing328** [comment]
@JackWink thanks for the PR. Please run `./bin/swift-petstore-all.sh` and you can then run the integration tests locally: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-do-i-run-integration-test-with-petstore-objc-api-client

**Comment by JackWink** [comment]
@wing328 I was able to run the integration tests locally and added a commit with the updated clients. Are you experiencing test failures? They're passing for me.

**Comment by wing328** [comment]
@JackWink I'm not saying the test failed for me locally in my machine. As part of the change we ask contributors to update the Petstore sample for the language they updated.

To manage your expectation, there are other PRs targeting Swift so we may merge those first before merging yours.

Thanks again for the contribution.

**Comment by JackWink** [comment]
Ah, I misunderstood, sorry! That might be worth adding to the contributing guidelines (or a checklist in a PR template). 

I still need to use my own templates for the time being so it's not urgent, but I'll be following any Swift client updates.

**Comment by jgavris** [comment]
+1 Would appreciate this

**Comment by wing328** [comment]
@jgavris thanks for the review.

@JackWink thanks again for the PR.

**Pull request merged**
