### PR TITLE
bugfix: issue-4051

### PR DESCRIPTION
**Pull request by schnabel**
### PR checklist
- [x] Read the [contribution guildelines](https://github.com/swagger-api/swagger-codegen/blob/master/CONTRIBUTING.md).
- [x] Ran the shell/batch script under `./bin/` to update Petstore sample so that CIs can verify the change. (For instance, only need to run `./bin/{LANG}-petstore.sh` and `./bin/security/{LANG}-petstore.sh` if updating the {LANG} (e.g. php, ruby, python, etc) code generator or {LANG} client's mustache templates)
- [x] Filed the PR against the correct branch: master for non-breaking changes and `2.3.0` branch for breaking (non-backward compatible) changes.
### Description of the PR

(details of the change, additional tests that have been done, reference to the issue for tracking, etc)
The fix converts the first two letters of a property name to lower case if the property name started with two upper case letters.
Another way to handle the problem jackson has with uppercase properties would be to put the JsonProperty annotation to the getter methods.

### CODE REVIEW

**Comment by wing328** [comment]
Thanks for the PR but your commit (as shown in the Commits tab) is not linked to your Github account, which means this PR won't count as your contribution in https://github.com/swagger-api/swagger-codegen/graphs/contributors.

Let me know if you need help fixing it.

Ref: https://github.com/swagger-api/swagger-codegen/wiki/FAQ#how-can-i-update-commits-that-are-not-linked-to-my-github-account

**Comment by schnabel** [comment]
@wing328 fixed the author stuff.

**Comment by wing328** [comment]
@schnabel seems like there's an issue with the rebase and there are now 250+ commits in this PR.

I would suggest you to submit a new one by first pulling the latest master and then rebasing accordingly.

**Comment by schnabel** [comment]
Completely new PR? Are the changes in the samples/client... a problem?

**Comment by wing328** [comment]
Well there are merge conflicts and if you click on the `Commits` and `File changed` tabs, there are too many changes (in which I don't think your PR intend to change so many files)

**Pull request closed without merging**
